'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium';
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-actions-')),file=path.join(root,'index.html'),source='<html><body><h1>Heading</h1><p>Sibling</p></body></html>';fs.writeFileSync(file,source);const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{
  browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();const page=await browser.newPage({viewport:{width:1800,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));const app=page.frameLocator('#app');
  const wait=async fn=>{for(let i=0;i<100;i++){try{if(await fn())return;}catch(error){if(!/Execution context was destroyed/.test(error.message))throw error;}await page.waitForTimeout(50);}throw Error('Actions did not settle');};
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.getByRole('heading').waitFor();await app.locator('body').evaluate(el=>el.tabIndex=-1);const dialog=()=>page.getByRole('dialog',{name:'Actions',exact:true}),input=()=>page.getByRole('combobox',{name:'Search actions',exact:true}),open=async()=>{await page.getByRole('button',{name:'Actions',exact:true}).click();await dialog().waitFor();};
  await open();await input().fill('undo preview');assert.equal(await page.getByRole('option',{name:/Undo preview size/}).getAttribute('aria-disabled'),'true');await input().press('Enter');assert.equal(await dialog().isVisible(),true);await input().press('Escape');
  await open();await input().fill('zoom selection');const disabled=page.getByRole('option',{name:/Zoom to selection/});assert.equal(await disabled.getAttribute('aria-disabled'),'true');await input().press('Enter');assert.equal(await dialog().isVisible(),true);await input().fill('not a command');assert.equal(await dialog().getByRole('option').count(),0);await input().press('Escape');await dialog().waitFor({state:'hidden'});
  await page.locator('#logo').click();await page.keyboard.press('Control+k');await dialog().waitFor();await input().fill('panel');const first=await input().getAttribute('aria-activedescendant');await input().press('ArrowDown');assert.notEqual(await input().getAttribute('aria-activedescendant'),first);await input().press('Enter');await dialog().waitFor({state:'hidden'});assert.equal(await page.locator('#panel').isVisible(),false);
  await open();await input().fill('inspector');await input().press('Enter');await dialog().waitFor({state:'hidden'});assert.equal(await page.locator('#panel').isVisible(),true);
  await app.locator('body').press('Control+k');await dialog().waitFor();await input().fill('preview phone');assert.equal(await dialog().getByRole('option').count(),1,'Default project screen does not duplicate the preset action');await page.getByRole('option',{name:'Preview: Phone',exact:true}).click();await dialog().waitFor({state:'hidden'});await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===390);assert.equal(fs.readFileSync(file,'utf8'),source);
  await page.locator('#modeBtn').click();await app.locator('body').press('Control+k');assert.equal(await dialog().count(),0,'Interact mode keeps the page shortcut');await page.locator('#modeBtn').click();
  await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();const background=page.getByLabel('Background color (CSS)',{exact:true});await background.fill('#ff0000');await background.press('Tab');await wait(async()=>fs.readFileSync(file,'utf8')!==source);await wait(async()=>await app.getByRole('heading').evaluate(el=>getComputedStyle(el).backgroundColor)==='rgb(255, 0, 0)');await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks&&panelBody.getAttribute('aria-busy')!=='true');const styledSource=fs.readFileSync(file,'utf8');await app.locator('body').evaluate(el=>{el.tabIndex=-1;el.ownerDocument.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='z')el.ownerDocument.defaultView.parent.nativeUndoPrevented=event.defaultPrevented;},true);const field=el.ownerDocument.createElement('input');field.setAttribute('aria-label','Site text');el.append(field);});await page.locator('#modeBtn').click();await app.locator('body').press('Control+z');assert.equal(await page.evaluate(()=>window.nativeUndoPrevented),false,'Interact mode leaves Undo to the site');assert.equal(fs.readFileSync(file,'utf8'),styledSource);await page.locator('#modeBtn').click();await app.getByRole('textbox',{name:'Site text',exact:true}).press('Control+z');assert.equal(await page.evaluate(()=>window.nativeUndoPrevented),false,'site text fields keep native Undo in Edit mode');assert.equal(fs.readFileSync(file,'utf8'),styledSource);await app.getByRole('textbox',{name:'Site text',exact:true}).evaluate(el=>el.remove());
  for(const kind of ['role','plaintext']){
   await app.locator('body').evaluate((body,kind)=>{const editor=body.ownerDocument.createElement('div');editor.dataset.nativeEditor=kind;editor.tabIndex=0;if(kind==='role')editor.setAttribute('role','textbox');else editor.setAttribute('contenteditable','plaintext-only');body.append(editor);},kind);
   const editor=app.locator('[data-native-editor="'+kind+'"]');await editor.press('Control+k');assert.equal(await dialog().count(),0,kind+' editors retain their command shortcut');await editor.press('2');await page.waitForTimeout(650);assert.equal(fs.readFileSync(file,'utf8'),styledSource,kind+' editors do not trigger canvas opacity');await editor.evaluate(el=>el.remove());
  }
  await open();await input().fill('undo');assert.equal(await page.getByRole('option',{name:'Undo last edit',exact:true}).getAttribute('aria-disabled'),'false');await input().press('Enter');await dialog().waitFor({state:'hidden'});await wait(async()=>fs.readFileSync(file,'utf8')===source);
  for(const surface of ['shell','site']){
   const historyKey=async key=>{await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);if(surface==='shell'){await page.locator('#logo').click();await page.keyboard.press(key);}else{await app.locator('body').evaluate(el=>el.tabIndex=-1);await app.locator('body').press(key);}};
   await historyKey('Control+y');await wait(()=>fs.readFileSync(file,'utf8')===styledSource);await historyKey('Control+z');await wait(()=>fs.readFileSync(file,'utf8')===source);
  }
  for(const [surface,key,value]of [['shell','4','0.4'],['site','0','1']]){
   await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks&&panelBody.getAttribute('aria-busy')!=='true');
   if(surface==='shell'){await page.locator('#logo').click();await page.keyboard.press(key);}else await app.locator('body').press(key);
   await wait(()=>fs.readFileSync(file,'utf8')!==source);await wait(async()=>await app.getByRole('heading').evaluate(el=>getComputedStyle(el).opacity)===value);const opacitySource=fs.readFileSync(file,'utf8');assert.notEqual(opacitySource,source);await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>fs.readFileSync(file,'utf8')===source);
  }
  for(const [digits,value]of [['25','0.25'],['05','0.05'],['00','0'],['100','1']]){
   await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await page.locator('#logo').click();await page.keyboard.type(digits,{delay:30});await wait(()=>fs.readFileSync(file,'utf8')!==source);await wait(async()=>await app.getByRole('heading').evaluate(el=>getComputedStyle(el).opacity)===value);await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>fs.readFileSync(file,'utf8')===source);
  }
  await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await page.locator('#logo').click();await page.keyboard.press('2');await page.keyboard.press('Escape');await page.waitForTimeout(650);assert.equal(fs.readFileSync(file,'utf8'),source,'Escape cancels a pending percentage');
  await page.keyboard.press('3');await page.getByRole('treeitem',{name:'p · Sibling',exact:true}).click();await page.waitForTimeout(650);assert.equal(fs.readFileSync(file,'utf8'),source,'selection changes discard a pending percentage');await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();
  await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await page.locator('#logo').click();await page.keyboard.press('2');await open();await input().press('Escape');await page.waitForTimeout(650);assert.equal(fs.readFileSync(file,'utf8'),source,'opening and closing Actions discards a pending percentage');
  await page.locator('#logo').click();await page.keyboard.press('3');await page.keyboard.press('Control+z');await page.waitForTimeout(650);assert.equal(fs.readFileSync(file,'utf8'),source,'keyboard Undo cancels a pending percentage');
  await page.keyboard.press('4');await page.locator('#modeBtn').click();await page.locator('#modeBtn').click();await page.waitForTimeout(650);assert.equal(fs.readFileSync(file,'utf8'),source,'switching modes discards a pending percentage');
  const opacityField=page.getByLabel('Opacity (%)',{exact:true});await opacityField.fill('');await opacityField.press('5');assert.equal(await opacityField.inputValue(),'5');assert.equal(fs.readFileSync(file,'utf8'),source);await opacityField.fill('100');await page.locator('#logo').click();
  await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await page.locator('#logo').click();await page.keyboard.press('Control+Shift+h');await wait(()=>fs.readFileSync(file,'utf8')!==source);await wait(async()=>await app.getByRole('heading',{includeHidden:true}).evaluate(el=>getComputedStyle(el).visibility)==='hidden');const hiddenSource=fs.readFileSync(file,'utf8');await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await app.locator('body').press('Control+Shift+h');await wait(()=>fs.readFileSync(file,'utf8')!==hiddenSource);await wait(async()=>await app.getByRole('heading').evaluate(el=>getComputedStyle(el).visibility)==='visible');await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>fs.readFileSync(file,'utf8')===hiddenSource);await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>fs.readFileSync(file,'utf8')===source);
  const run=async(query,name)=>{await open();await input().fill(query);await dialog().getByRole('option',{name,exact:true}).click();await dialog().waitFor({state:'hidden'});};
  await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await run('hide selection','Hide selection');await wait(()=>fs.readFileSync(file,'utf8')!==source);await wait(async()=>await app.getByRole('heading',{includeHidden:true}).evaluate(el=>getComputedStyle(el).visibility)==='hidden');const paletteHidden=fs.readFileSync(file,'utf8');await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await run('show selection','Show selection');await wait(()=>fs.readFileSync(file,'utf8')!==paletteHidden);await app.getByRole('heading').waitFor();await run('undo','Undo last edit');await wait(()=>fs.readFileSync(file,'utf8')===paletteHidden);await page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks);await run('undo','Undo last edit');await wait(()=>fs.readFileSync(file,'utf8')===source);
  await run('lock preview aspect','Lock preview aspect ratio');assert.equal(await page.getByRole('button',{name:'Lock screen aspect ratio',exact:true}).getAttribute('aria-pressed'),'true');await run('unlock preview aspect','Unlock preview aspect ratio');assert.equal(await page.getByRole('button',{name:'Lock screen aspect ratio',exact:true}).getAttribute('aria-pressed'),'false');
  await run('screen comparisons','Toggle screen comparisons');await page.locator('#screenComparisons').evaluate(el=>el.inert=true);await open();await input().fill('hide all previews');assert.equal(await dialog().getByRole('option',{name:/Hide all previews/}).getAttribute('aria-disabled'),'true','inert comparison controls cannot be invoked through Actions');await input().press('Enter');assert.equal(await dialog().isVisible(),true);await page.locator('#screenComparisons').evaluate(el=>el.inert=false);await wait(async()=>await dialog().getByRole('option',{name:'Hide all previews',exact:true}).getAttribute('aria-disabled')==='false');await input().press('Enter');await dialog().waitFor({state:'hidden'});assert.equal(await page.locator('.compare-surface:visible').count(),0);await run('show selection in all','Show selection in all previews');assert.equal(await page.locator('.compare-surface:visible').count(),3);await run('hide all previews','Hide all previews');await run('show all previews','Show all previews');assert.equal(await page.locator('.compare-surface:visible').count(),3);await page.frameLocator('iframe[title="Tablet comparison preview"]').locator('body').evaluate(el=>el.dataset.renameMarker='preserved');await run('rename tablet','Rename Tablet comparison');const screenName=page.getByRole('textbox',{name:'Comparison name',exact:true});await wait(async()=>await screenName.evaluate(el=>el===document.activeElement));await screenName.fill('Reading tablet');await screenName.press('Enter');await run('edit reading tablet','Edit reading tablet size');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===768);assert.equal(await page.frameLocator('iframe[title="Reading tablet comparison preview"]').locator('body').getAttribute('data-rename-marker'),'preserved');await run('rename reading tablet','Rename Reading tablet comparison');await screenName.fill('Tablet');await screenName.press('Escape');await page.getByRole('button',{name:'Rename Reading tablet comparison',exact:true}).waitFor();await run('rename reading tablet','Rename Reading tablet comparison');await screenName.fill('Tablet');await screenName.press('Enter');await run('edit tablet size','Edit tablet size');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===768);await run('edit phone size','Edit phone size');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===390);await run('hide phone preview','Hide Phone preview');assert.equal(await page.locator('.compare-surface:visible').count(),2);await run('show phone preview','Show Phone preview');await run('show selection phone','Show selection in Phone comparison');assert.equal(await page.locator('.compare-surface:visible').count(),3);await run('screen comparisons','Toggle screen comparisons');
  await run('rotate preview','Rotate preview size');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===844);await run('undo preview','Undo preview size');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===390);await run('redo preview','Redo preview size');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===844);await run('undo preview','Undo preview size');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===390);assert.equal(fs.readFileSync(file,'utf8'),source,'Preview history actions do not replay source edits');
  await page.getByRole('treeitem',{name:'p · Sibling',exact:true}).click();await run('lock selection','Lock selection');await wait(async()=>await page.evaluate(()=>layerLocks.direct(doc().querySelector('p'))));await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();
  const order=()=>app.locator('body > h1,body > p').evaluateAll(nodes=>nodes.map(node=>node.tagName)),retainedLocks=()=>page.evaluate(()=>layerLocks.direct(doc().querySelector('p'))&&!layerLocks.direct(doc().querySelector('h1'))),selectedHeading=()=>page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).getAttribute('aria-selected');
  for(const [query,name,tags]of [['move layer down','Move layer down',['P','H1']],['move layer up','Move layer up',['H1','P']],['bring to front','Bring to front',['P','H1']],['send to back','Send to back',['H1','P']]]){await run(query,name);await wait(async()=>JSON.stringify(await order())===JSON.stringify(tags));await wait(async()=>await selectedHeading()==='true');await wait(retainedLocks);}
  await run('undo','Undo last edit');await wait(async()=>JSON.stringify(await order())==='["P","H1"]');await wait(retainedLocks);await run('redo','Redo last edit');await wait(async()=>JSON.stringify(await order())==='["H1","P"]');await wait(retainedLocks);
  for(let i=0;i<4;i++){await run('undo','Undo last edit');await wait(async()=>JSON.stringify(await order())===JSON.stringify(i%2?['H1','P']:['P','H1']));await wait(retainedLocks);await wait(async()=>await selectedHeading()==='true');}await run('undo','Undo last edit');await wait(async()=>!await page.evaluate(()=>layerLocks.direct(doc().querySelector('p'))));assert.equal(fs.readFileSync(file,'utf8'),source);console.log('HOST ORDER/SELECTION/SIBLING LOCKS/UNDO/REDO PASS',engine);
  await page.getByRole('treeitem',{name:'p · Sibling',exact:true}).click();await run('lock selection','Lock selection');await wait(retainedLocks);
  const allCopyLocks=()=>page.evaluate(()=>layerLocks.direct(doc().querySelector('p'))&&[...doc().querySelectorAll('h1')].every(el=>!layerLocks.direct(el)));
  for(const action of ['Duplicate layer','Paste layer']){
   await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();if(action==='Paste layer')await run('copy layer','Copy layer');await run(action,action);await wait(async()=>await app.getByRole('heading').count()===2);await wait(allCopyLocks);
   await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source&&await app.getByRole('heading').count()===1);await wait(allCopyLocks);
   await run('redo','Redo last edit');await wait(async()=>await app.getByRole('heading').count()===2);await wait(allCopyLocks);
   await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source&&await app.getByRole('heading').count()===1);await wait(allCopyLocks);
  }
  await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();await run('delete layer','Delete layer');await wait(async()=>await app.getByRole('heading').count()===0);await wait(allCopyLocks);
  await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source&&await app.getByRole('heading').count()===1);await wait(allCopyLocks);
  await run('redo','Redo last edit');await wait(async()=>await app.getByRole('heading').count()===0);await wait(allCopyLocks);
  await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source&&await app.getByRole('heading').count()===1);await wait(allCopyLocks);console.log('DELETE SIBLING LOCKS/UNDO/REDO PASS',engine);
  await run('undo','Undo last edit');await wait(async()=>!await page.evaluate(()=>layerLocks.direct(doc().querySelector('p'))));console.log('COPY/PASTE SIBLING LOCKS/UNDO/REDO PASS',engine);
  await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();await run('lock selection','Lock selection');await wait(async()=>await page.evaluate(()=>layerLocks.direct(doc().querySelector('h1'))));await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();await run('unlock selection','Unlock selection');await wait(async()=>!await page.evaluate(()=>layerLocks.direct(doc().querySelector('h1'))));assert.equal(fs.readFileSync(file,'utf8'),source);
  await run('duplicate layer','Duplicate layer');await wait(async()=>await app.getByRole('heading').count()===2);const duplicated=fs.readFileSync(file,'utf8');await wait(async()=>await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).nth(1).getAttribute('aria-selected')==='true');await run('delete layer','Delete layer');await wait(async()=>await app.getByRole('heading').count()===1);await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===duplicated);await wait(async()=>await app.getByRole('heading').count()===2);await wait(async()=>await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).nth(1).getAttribute('aria-selected')==='true');await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source);await wait(async()=>await app.getByRole('heading').count()===1);await wait(async()=>await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).first().getAttribute('aria-selected')==='true');await run('redo','Redo last edit');await wait(async()=>await app.getByRole('heading').count()===2);await wait(async()=>await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).nth(1).getAttribute('aria-selected')==='true');await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source);await wait(async()=>await app.getByRole('heading').count()===1);
  await run('copy layer','Copy layer');await run('paste layer','Paste layer');await wait(async()=>await app.getByRole('heading').count()===2);await wait(async()=>await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).nth(1).getAttribute('aria-selected')==='true');await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source);await wait(async()=>await app.getByRole('heading').count()===1);
  await page.getByRole('treeitem',{name:'h1 · Heading',exact:true}).click();await wait(async()=>await page.locator('.kindbadge').textContent()==='H1');await page.setViewportSize({width:720,height:900});await wait(async()=>!await page.locator('#panel').isVisible());await run('rename layer','Rename layer');const layerName=page.getByLabel('Layer name',{exact:true});await wait(async()=>await layerName.evaluate(el=>el===document.activeElement));assert.equal(await page.locator('#panel').isVisible(),true);await layerName.fill('Hero heading');await layerName.press('Tab');await wait(async()=>fs.readFileSync(file,'utf8')!==source);assert.equal(await app.getByRole('heading').textContent(),'Heading');await run('undo','Undo last edit');await wait(async()=>fs.readFileSync(file,'utf8')===source);console.log('ACTIONS LAYER LOCK/DUPLICATE/DELETE/RENAME/COMPACT/UNDO PASS',engine);
  await open();await input().fill('variables');await input().press('Enter');await page.getByRole('dialog',{name:'Variable collections',exact:true}).waitFor();await page.getByRole('button',{name:'Close variable collections',exact:true}).click();
  await page.getByRole('textbox',{name:'Page URL',exact:true}).focus();await page.keyboard.press('Control+k');assert.equal(await dialog().count(),0,'Input shortcuts stay native');await page.setViewportSize({width:360,height:320});await open();await input().fill('screen');assert.equal(await dialog().evaluate(el=>{const box=el.getBoundingClientRect();return box.top>=0&&box.bottom<=innerHeight&&getComputedStyle(el).backgroundColor==='rgb(255, 255, 255)';}),true,'Light action palette stays inside a short compact window');await input().press('End');assert.equal(await dialog().getByRole('option',{selected:true}).evaluate(el=>{const row=el.getBoundingClientRect(),list=el.parentElement.getBoundingClientRect();return row.top>=list.top&&row.bottom<=list.bottom+1;}),true,'Keyboard navigation scrolls the final action into view');assert.equal(await dialog().evaluate(el=>el.scrollWidth<=el.clientWidth&&el.getBoundingClientRect().right<=innerWidth),true);if(process.env.RT_E2E_ACTIONS_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_ACTIONS_SCREENSHOT});await input().press('Escape');assert.deepEqual(errors,[]);console.log('ACTIONS SEARCH/KEYBOARD/AVAILABILITY/IFRAME/PANELS/PRESETS/SOURCE UNDO PASS',engine);
 }finally{if(browser)await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
