'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium';
(async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-add-screen-')),file=path.join(root,'index.html'),source='<html><body><h1>Compare without losing your place</h1><p>Responsive canvas</p></body></html>';fs.writeFileSync(file,source);const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
try{
 browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});await page.goto('http://localhost:'+server.address().port+'/rt');await page.frameLocator('#app').locator('h1').waitFor();await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await page.getByRole('button',{name:'Compare screens',exact:true}).click();await page.frameLocator('iframe[title="Phone comparison preview"]').locator('h1').waitFor();
 await page.locator('#app').evaluate(frame=>frame.contentWindow.__addScreenDocument=frame.contentDocument);await page.locator('iframe[title="Phone comparison preview"]').evaluate(frame=>frame.contentWindow.__addScreenDocument=frame.contentDocument);
 const add=page.getByRole('button',{name:'Add screen',exact:true}),dialog=page.getByRole('dialog',{name:'Add screen',exact:true});await add.click();await dialog.waitFor();assert.ok((await dialog.boundingBox()).height<400);assert.equal(await dialog.getByLabel('Screen name',{exact:true}).evaluate(el=>document.activeElement===el),true);await page.screenshot({path:'/tmp/retouch-add-screen-dialog-'+engine+'.png',caret:'initial'});await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await add.evaluate(el=>document.activeElement===el),true);assert.equal(await page.locator('.compare-card').count(),3);
 await add.click();const name=dialog.getByLabel('Screen name',{exact:true}),width=dialog.getByLabel('Width (px)',{exact:true}),height=dialog.getByLabel('Height (px)',{exact:true}),submit=dialog.getByRole('button',{name:'Add screen',exact:true});await name.fill('Phone');await width.fill('618');await height.fill('910');await submit.click();assert.match(await name.evaluate(el=>el.validationMessage),/name already exists/);await name.fill('Reading');await width.fill('390');await height.fill('844');await submit.click();assert.match(await width.evaluate(el=>el.validationMessage),/dimensions already exists/);await width.fill('100');await submit.click();assert.equal(await width.evaluate(el=>el.validity.rangeUnderflow),true);assert.equal(await page.locator('.compare-card').count(),3);
 await width.fill('618');await height.fill('910');await page.setViewportSize({width:360,height:800});const bounds=await dialog.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=360);assert.ok(bounds.height<400&&bounds.y>0&&bounds.y+bounds.height<800);await page.screenshot({path:'/tmp/retouch-add-screen-mobile-'+engine+'.png',caret:'initial'});await submit.click();await dialog.waitFor({state:'hidden'});await page.frameLocator('iframe[title="Reading comparison preview"]').locator('h1').waitFor();assert.equal(await page.locator('.compare-card').count(),4);assert.deepEqual(await page.evaluate(()=>RetouchScreens.get()),{width:390,height:844});assert.equal(await page.locator('iframe[title="Reading comparison preview"]').evaluate(frame=>frame.contentWindow.innerWidth),618);assert.equal(await page.locator('iframe[title="Reading comparison preview"]').evaluate(frame=>frame.contentWindow.innerHeight),910);
 for(const selector of ['#app','iframe[title="Phone comparison preview"]'])assert.equal(await page.locator(selector).evaluate(frame=>frame.contentWindow.__addScreenDocument===frame.contentDocument),true);
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/retouch-add-screen-result-'+engine+'.png',caret:'initial'});await page.reload();await page.frameLocator('#app').locator('h1').waitFor();await page.getByRole('button',{name:'Compare screens',exact:true}).click();await page.frameLocator('iframe[title="Reading comparison preview"]').locator('h1').waitFor();assert.equal(await page.locator('.compare-card').count(),4);assert.deepEqual(await page.evaluate(()=>RetouchScreens.get()),{width:390,height:844});for(let i=0;i<4;i++){await page.getByRole('button',{name:'Add screen',exact:true}).click();const form=page.getByRole('dialog',{name:'Add screen',exact:true});await form.getByLabel('Screen name',{exact:true}).fill('Extra '+i);await form.getByLabel('Width (px)',{exact:true}).fill(String(700+i));await form.getByLabel('Height (px)',{exact:true}).fill('900');await form.getByRole('button',{name:'Add screen',exact:true}).click();await form.waitFor({state:'hidden'});}assert.equal(await page.locator('.compare-card').count(),8);assert.equal(await page.getByRole('button',{name:'Add screen',exact:true}).isDisabled(),true);assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);console.log('ADD NAMED SCREEN, VALIDATION, CANCEL, PERSISTENCE AND RETAINED DOCUMENTS PASS',engine);
}finally{await browser?.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
