'use strict';
const path=require('node:path'),assert=require('node:assert/strict'),B=require('../../shell/background-paint.js');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium';
(async()=>{const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage();try{
 await page.setContent('<style>body{margin:0;background:lime}#paint{width:100px;height:80px;background-image:linear-gradient(90deg,rgba(255,0,0,.5) 50%,transparent 50%);background-size:23px 31px;background-position:7px 11px}</style><div id="paint"></div>');
 const target=page.locator('#paint'),write=changes=>target.evaluate((el,changes)=>{for(const [property,value]of Object.entries(changes)){if(value===null)el.style.removeProperty(property);else el.style.setProperty(property,value);}},changes),read=()=>target.evaluate((el,key)=>{const css=getComputedStyle(el);return {color:css.backgroundColor,stored:css.getPropertyValue(key).trim()||'none',framing:[css.backgroundImage,css.backgroundSize,css.backgroundPosition,css.backgroundRepeat]};},B.property),pixels=async()=>require(path.join(fixture,'node_modules/sharp'))(await target.screenshot()).removeAlpha().raw().toBuffer();
 for(const color of ['#33669980','#abcdef00','color(srgb 0.2 0.4 0.6 / 0.375)','color(display-p3 0.2 0.4 0.6 / 0.375)']){
  await write(B.clear());const empty=await pixels();await write({'background-color':color});const before=await read(),visible=await pixels();await write(B.toggle(before.color,before.stored,true));const hidden=await read();assert.equal(B.state(hidden.color,hidden.stored).hidden,true);assert.deepEqual(hidden.framing,before.framing);assert.deepEqual(await pixels(),empty,'Hidden background leaves image paints and the page below unchanged');
  await page.setContent(await page.content());const loaded=await read();await write(B.toggle(loaded.color,loaded.stored,false));assert.deepEqual(await pixels(),visible,'Source metadata restores exact pixels after document reconstruction');assert.deepEqual((await read()).framing,before.framing);
  const shown=await read();await write(B.toggle(shown.color,shown.stored,true));const second=await read();await write(B.edit(second.color,second.stored,'color(display-p3 0.1 0.3 0.8 / 0.25)'));assert.deepEqual(await pixels(),empty);const edited=await read();await write(B.toggle(edited.color,edited.stored,false));const result=await pixels();await write({'background-color':'color(display-p3 0.1 0.3 0.8 / 0.25)'});assert.deepEqual(await pixels(),result);assert.deepEqual((await read()).framing,before.framing);
 }
 console.log(engine+': PASS background visibility, hidden edits, alpha/P3, neighboring image pixels and serialized-document restoration');
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
