'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium';
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-breakpoint-preview-')),file=path.join(root,'index.html'),source='<html><body><main><h1>Responsive heading</h1></main></body></html>';fs.writeFileSync(file,source);const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{
  browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:'+server.address().port+'/rt');const app=page.frameLocator('#app');await app.locator('h1').waitFor();
  const settled=()=>page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks&&panelBody.getAttribute('aria-busy')!=='true');
  const size=async value=>{await page.getByLabel('Screen size',{exact:true}).focus();await page.getByLabel('Screen size',{exact:true}).selectOption(value);await page.waitForFunction(w=>doc().defaultView.innerWidth===w,Number(value.split('x')[0]));};
  const action=async label=>{await page.locator('#quickActions').click();const dialog=page.getByRole('dialog',{name:'Actions',exact:true});await dialog.getByRole('combobox',{name:'Search actions'}).fill(label);await dialog.getByRole('option',{name:label,exact:true}).click();await dialog.waitFor({state:'hidden'});};
  await size('768x1024');await page.getByRole('treeitem',{name:'h1 · Responsive heading',exact:true}).click();await action('Style changes: 768 px and larger');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'min-[768px]:');assert.equal(fs.readFileSync(file,'utf8'),source);await page.getByLabel('Opacity (%)',{exact:true}).fill('50');await page.getByLabel('Opacity (%)',{exact:true}).press('Tab');await page.waitForFunction(()=>doc()?.querySelector('h1')&&getComputedStyle(doc().querySelector('h1')).opacity==='0.5');await settled();const edited=fs.readFileSync(file,'utf8');assert.notEqual(edited,source);
  if(process.env.RT_E2E_BREAKPOINT_BOUNDARY){
   await action('Compare across breakpoint');assert.deepEqual(await page.locator('.compare-card').evaluateAll(cards=>cards.map(card=>card.getAttribute('aria-label'))),['Phone comparison','Outside 768 px and larger comparison','Tablet comparison','Desktop comparison']);const outside=page.frameLocator('iframe[title="Outside 768 px and larger comparison preview"]'),inside=page.frameLocator('iframe[title="Tablet comparison preview"]');await outside.locator('h1').waitFor();await inside.locator('h1').waitFor();assert.deepEqual(await outside.locator('body').evaluate(()=>[innerWidth,innerHeight]),[767,1024]);assert.deepEqual(await inside.locator('body').evaluate(()=>[innerWidth,innerHeight]),[768,1024]);assert.equal(await outside.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'1');assert.equal(await inside.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'0.5');await inside.locator('body').evaluate(()=>window.__comparisonOrderMarker='retained');await page.getByRole('button',{name:'Undo screen order',exact:true}).click();assert.deepEqual(await page.locator('.compare-card').evaluateAll(cards=>cards.map(card=>card.getAttribute('aria-label'))),['Phone comparison','Tablet comparison','Desktop comparison','Outside 768 px and larger comparison']);await page.getByRole('button',{name:'Redo screen order',exact:true}).click();assert.deepEqual(await page.locator('.compare-card').evaluateAll(cards=>cards.map(card=>card.getAttribute('aria-label'))),['Phone comparison','Outside 768 px and larger comparison','Tablet comparison','Desktop comparison']);assert.equal(await inside.locator('body').evaluate(()=>window.__comparisonOrderMarker),'retained');assert.equal(await page.locator('.compare-card').count(),4);await page.getByRole('button',{name:'Compare across breakpoint',exact:true}).click();assert.equal(await page.locator('.compare-card').count(),4);
   assert.equal(await page.getByRole('button',{name:'Undo Tablet comparison name',exact:true,includeHidden:true}).isVisible(),false);assert.equal(await page.getByRole('button',{name:'Undo Tablet comparison size',exact:true,includeHidden:true}).isVisible(),false);
   if(process.env.RT_E2E_BREAKPOINT_SCREENSHOT){await page.screenshot({path:process.env.RT_E2E_BREAKPOINT_SCREENSHOT});await page.setViewportSize({width:900,height:800});await page.screenshot({path:process.env.RT_E2E_BREAKPOINT_SCREENSHOT.replace('.png','-compact.png')});await page.setViewportSize({width:1600,height:1100});}

   assert.deepEqual(await page.evaluate(()=>{[500,510,520].forEach(width=>RetouchComparisons.showSize({width,height:800}));return {accepted:RetouchComparisons.showSizes([{width:530,height:800},{width:540,height:800}]),existing:RetouchComparisons.canShowSizes([{width:767,height:1024},{width:768,height:1024}])};}),{accepted:false,existing:true});assert.equal(await page.locator('.compare-card').count(),7);assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[768,1024]);assert.equal(fs.readFileSync(file,'utf8'),edited);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);console.log('BREAKPOINT BOUNDARY DIMENSIONS/CSS/REUSE/ATOMIC CAPACITY/SOURCE PASS',engine);return;
  }
  await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).click();const tablet=page.frameLocator('iframe[title="Tablet comparison preview"]');await tablet.locator('h1').waitFor();assert.equal(await tablet.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'0.5');assert.equal(await page.locator('.compare-card').count(),3);assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[768,1024]);assert.equal(fs.readFileSync(file,'utf8'),edited);assert.equal(await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).count(),0);
  const scopePicker=page.getByLabel('Style screen scope');await scopePicker.focus();await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await page.waitForFunction(()=>doc().defaultView.innerWidth===390);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await scopePicker.evaluate(el=>el===document.activeElement),true);assert.equal(await scopePicker.inputValue(),'min-[768px]:');assert.equal(fs.readFileSync(file,'utf8'),edited);await page.getByLabel('Screen size',{exact:true}).focus();await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).waitFor();assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'1');await action('Compare this breakpoint');const comparison=page.frameLocator('iframe[title="768 px and larger comparison preview"]');await comparison.locator('h1').waitFor();assert.deepEqual(await comparison.locator('body').evaluate(()=>[innerWidth,innerHeight]),[768,844]);assert.equal(await comparison.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'0.5');assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[390,844]);assert.equal(fs.readFileSync(file,'utf8'),edited);assert.equal(await page.locator('.compare-card').count(),4);
  const linkedOpacity=async value=>{await page.waitForFunction(value=>['Tablet comparison preview','768 px and larger comparison preview'].every(title=>{const frame=[...document.querySelectorAll('iframe')].find(el=>el.title===title),heading=frame?.contentDocument?.querySelector('h1');return heading&&frame.contentWindow.getComputedStyle(heading).opacity===value;}),value);assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'1');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'min-[768px]:');};
  await page.getByLabel('Opacity (%)',{exact:true}).fill('25');await page.getByLabel('Opacity (%)',{exact:true}).press('Tab');await settled();await linkedOpacity('0.25');const revised=fs.readFileSync(file,'utf8');assert.notEqual(revised,edited);
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await linkedOpacity('0.5');assert.equal(fs.readFileSync(file,'utf8'),edited);
  await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await linkedOpacity('0.25');assert.equal(fs.readFileSync(file,'utf8'),revised);
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await linkedOpacity('0.5');assert.equal(fs.readFileSync(file,'utf8'),edited);console.log('LINKED BREAKPOINT COMPARISON EDIT/UNDO/REDO PASS',engine);
  await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).click();assert.equal(await page.locator('.compare-card').count(),4);assert.deepEqual(await page.evaluate(()=>{const added=[500,510,520,530].map(width=>RetouchComparisons.showSize({width,height:800}));return {added,existing:RetouchComparisons.canShowSize({width:768,height:844}),extra:RetouchComparisons.showSize({width:540,height:800})};}),{added:[true,true,true,true],existing:true,extra:false});assert.equal(await page.locator('.compare-card').count(),8);assert.equal(await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).isDisabled(),false);assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[390,844]);await page.getByRole('button',{name:'Compare screens',exact:true}).click();await page.locator('#screenComparisons').waitFor({state:'hidden'});await page.waitForFunction(()=>!document.getElementById('compareScreens').disabled);assert.equal(await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).isDisabled(),false);await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===768&&doc().defaultView.innerHeight===844);await settled();assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'0.5');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'min-[768px]:');assert.equal(fs.readFileSync(file,'utf8'),edited);await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).waitFor({state:'detached'});
  await page.getByRole('button',{name:'Undo preview size',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===390&&doc().defaultView.innerHeight===844);await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),edited);
  await action('Style changes: All sizes · base');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'');assert.equal(fs.readFileSync(file,'utf8'),edited);await action('Style changes: 768 px and larger');await action('Preview this breakpoint');await page.waitForFunction(()=>doc().defaultView.innerWidth===768);assert.equal(fs.readFileSync(file,'utf8'),edited);await page.getByRole('button',{name:'Undo preview size',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===390);
  await page.getByRole('button',{name:'Redo preview size',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===768);await settled();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),source);await page.reload();await app.locator('h1').waitFor();await page.waitForFunction(()=>doc().defaultView.innerWidth===768&&doc().defaultView.innerHeight===844);await page.getByRole('treeitem',{name:'h1 · Responsive heading',exact:true}).click();await action('Style changes: 768 px and larger');await action('Compare this breakpoint');await comparison.locator('h1').waitFor();assert.equal(await page.locator('.compare-card').count(),8);assert.deepEqual(await comparison.locator('body').evaluate(()=>[innerWidth,innerHeight]),[768,844]);assert.equal(await comparison.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'1');assert.equal(await page.getByLabel('Screen size',{exact:true}).inputValue(),'saved:768x844');await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).click();assert.equal(await page.locator('.compare-card').count(),8);assert.equal(fs.readFileSync(file,'utf8'),source);console.log('BREAKPOINT COMPARISON RELOAD/PERSISTENCE/REUSE PASS',engine);
  assert.deepEqual(errors,[]);console.log('BREAKPOINT PREVIEW MATCHING SIZE/SCOPE/SOURCE/PREVIEW HISTORY PASS',engine);
 }finally{if(browser)await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
