'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium';
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-breakpoint-preview-')),file=path.join(root,'index.html'),source='<html><body><main><h1>Responsive heading</h1></main></body></html>';fs.writeFileSync(file,source);const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{
  browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:'+server.address().port+'/rt');const app=page.frameLocator('#app');await app.locator('h1').waitFor();
  const settled=()=>page.waitForFunction(()=>!undoBusy&&!sourceRequests&&!panelTasks&&panelBody.getAttribute('aria-busy')!=='true');
  const size=async value=>{await page.getByLabel('Screen size',{exact:true}).focus();await page.getByLabel('Screen size',{exact:true}).selectOption(value);await page.waitForFunction(w=>doc().defaultView.innerWidth===w,Number(value.split('x')[0]));};
  const action=async label=>{await page.locator('#quickActions').click();const dialog=page.getByRole('dialog',{name:'Actions',exact:true});await dialog.getByRole('combobox',{name:'Search actions'}).fill(label);await dialog.getByRole('option',{name:label,exact:true}).click();await dialog.waitFor({state:'hidden'});};
  await size('768x1024');await page.getByRole('treeitem',{name:'h1 · Responsive heading',exact:true}).click();await action('Style changes: 768 px and larger');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'min-[768px]:');assert.equal(fs.readFileSync(file,'utf8'),source);await page.getByLabel('Opacity (%)',{exact:true}).fill('50');await page.getByLabel('Opacity (%)',{exact:true}).press('Tab');await page.waitForFunction(()=>doc()?.querySelector('h1')&&getComputedStyle(doc().querySelector('h1')).opacity==='0.5');await settled();const edited=fs.readFileSync(file,'utf8');assert.notEqual(edited,source);
  const scopePicker=page.getByLabel('Style screen scope');await scopePicker.focus();await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await page.waitForFunction(()=>doc().defaultView.innerWidth===390);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await scopePicker.evaluate(el=>el===document.activeElement),true);assert.equal(await scopePicker.inputValue(),'min-[768px]:');assert.equal(fs.readFileSync(file,'utf8'),edited);await page.getByLabel('Screen size',{exact:true}).focus();await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).waitFor();assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'1');await action('Compare this breakpoint');const comparison=page.frameLocator('iframe[title="768 px and larger comparison preview"]');await comparison.locator('h1').waitFor();assert.deepEqual(await comparison.locator('body').evaluate(()=>[innerWidth,innerHeight]),[768,844]);assert.equal(await comparison.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'0.5');assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[390,844]);assert.equal(fs.readFileSync(file,'utf8'),edited);assert.equal(await page.locator('.compare-card').count(),4);await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).click();assert.equal(await page.locator('.compare-card').count(),4);assert.deepEqual(await page.evaluate(()=>{const added=[500,510,520,530].map(width=>RetouchComparisons.showSize({width,height:800}));return {added,existing:RetouchComparisons.canShowSize({width:768,height:844}),extra:RetouchComparisons.showSize({width:540,height:800})};}),{added:[true,true,true,true],existing:true,extra:false});assert.equal(await page.locator('.compare-card').count(),8);assert.equal(await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).isDisabled(),false);assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[390,844]);await page.getByRole('button',{name:'Compare screens',exact:true}).click();await page.locator('#screenComparisons').waitFor({state:'hidden'});await page.waitForFunction(()=>!document.getElementById('compareScreens').disabled);assert.equal(await page.getByRole('button',{name:'Compare this breakpoint',exact:true}).isDisabled(),false);await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===768&&doc().defaultView.innerHeight===844);await settled();assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).opacity),'0.5');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'min-[768px]:');assert.equal(fs.readFileSync(file,'utf8'),edited);await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).waitFor({state:'detached'});
  await page.getByRole('button',{name:'Undo preview size',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===390&&doc().defaultView.innerHeight===844);await page.getByRole('button',{name:'Preview this breakpoint',exact:true}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),edited);
  await action('Style changes: All sizes · base');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'');assert.equal(fs.readFileSync(file,'utf8'),edited);await action('Style changes: 768 px and larger');await action('Preview this breakpoint');await page.waitForFunction(()=>doc().defaultView.innerWidth===768);assert.equal(fs.readFileSync(file,'utf8'),edited);await page.getByRole('button',{name:'Undo preview size',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===390);
  await page.getByRole('button',{name:'Redo preview size',exact:true}).click();await page.waitForFunction(()=>doc().defaultView.innerWidth===768);await settled();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);console.log('BREAKPOINT PREVIEW MATCHING SIZE/SCOPE/SOURCE/PREVIEW HISTORY PASS',engine);
 }finally{if(browser)await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
