'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine],{capture}=require('../../src/site-capture.cjs');
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-capture-assets-')),directory=path.join(root,'saved'),font=fs.readFileSync(path.join(__dirname,'../fixtures/fonts/RobotoFlex.ttf')),svg='<svg xmlns="http://www.w3.org/2000/svg" width="80" height="50"><script>alert("should be removed")</script><rect width="80" height="50" fill="green"/></svg>';
 const source='<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="/styles/fonts.css"><style>body{margin:24px;font-family:CaptureFixture}h1{font-size:40px;font-weight:500}#background{width:120px;height:80px;background-image:url("/images/bg.svg?q=1&x=2")}img{width:80px;height:50px}</style></head><body><h1>Portable typography</h1><img src="/images/sprite.svg"><div id="background"></div><img id="blob"><svg width="80" height="50"><image href="/images/sprite.svg" width="80" height="50"/></svg><script>document.querySelector("#blob").src=URL.createObjectURL(new Blob([\'<svg xmlns="http://www.w3.org/2000/svg" width="80" height="50"><rect width="80" height="50" fill="red"/></svg>\'],{type:"image/svg+xml"}));</script></body></html>';
 const remote=http.createServer((req,res)=>{if(req.url==='/styles/fonts.css'){res.setHeader('content-type','text/css');res.end('@media (min-width:0px){@font-face{font-family:CaptureFixture;src:url("../fonts/font.ttf") format("truetype");font-weight:100 1000}}');}else if(req.url==='/fonts/font.ttf'){res.setHeader('content-type','font/ttf');res.end(font);}else if(req.url.startsWith('/images/')){res.setHeader('content-type','image/svg+xml');res.end(svg);}else if(req.url==='/bad.png'){res.writeHead(404);res.end('missing');}else{res.setHeader('content-type','text/html; charset=utf-8');res.end(req.url==='/broken'?'<!doctype html><img src="/bad.png">':source);}});remote.listen(0,'127.0.0.1');await once(remote,'listening');const url='http://127.0.0.1:'+remote.address().port;let browser,server,remoteClosed=false;
 try{
  browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1100,height:850}});await page.goto(url);await page.evaluate(()=>document.fonts.ready);const expected=await page.locator('h1').boundingBox();
  const result=await capture({url,directory,width:1100,height:850,wait:100,browserType});assert.equal(result.assets.length,4);assert.ok(result.assets.every(asset=>asset.status==='saved'));assert.deepEqual(result.warnings,[]);for(const asset of result.assets){const saved=fs.readFileSync(path.join(directory,asset.path));assert.equal(saved.length,asset.bytes);if(asset.path.endsWith('.svg'))assert.doesNotMatch(saved.toString(),/<script|onload/);}
  assert.equal(result.assets.find(asset=>asset.url.endsWith('/fonts/font.ttf')).bytes,font.length);assert.equal(result.assets.filter(asset=>asset.url.endsWith('/images/sprite.svg')).length,1,'Repeated image references download once');
  const partial=await capture({url:url+'/broken',directory:path.join(root,'partial'),wait:0,browserType});assert.equal(partial.assets[0].status,'remote');assert.match(partial.assets[0].reason,/HTTP 404/);assert.ok(partial.warnings.some(warning=>warning.includes('could not be saved')));
  remote.closeAllConnections();await new Promise(resolve=>remote.close(resolve));remoteClosed=true;
  server=require('../../src/html-site.cjs').start({root:directory,port:0,quiet:true});if(!server.listening)await once(server,'listening');const requests=[],errors=[];page.on('request',request=>requests.push(request.url()));page.on('pageerror',error=>errors.push(error.message));await page.goto('http://localhost:'+server.address().port);await page.evaluate(()=>document.fonts.ready);await page.locator('img').evaluateAll(images=>Promise.all(images.map(image=>image.decode())));assert.deepEqual(await page.locator('h1').boundingBox(),expected);assert.equal(await page.evaluate(()=>[...document.fonts].find(font=>font.family==='CaptureFixture')?.status),'loaded');assert.ok(await page.locator('img').evaluateAll(images=>images.every(image=>image.naturalWidth===80)));assert.match(await page.locator('#background').evaluate(el=>getComputedStyle(el).backgroundImage),/capture-assets/);assert.match(await page.locator('svg image').getAttribute('href'),/^\.\/capture-assets\//);assert.ok(requests.every(request=>!request.startsWith(url)),'Offline copy never requests the stopped source server');assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/retouch-capture-assets-'+engine+'.png'});console.log('CAPTURE LOCAL IMAGES, CSS URLS, BLOB, SVG, FONT, DEDUP, FAILURE REPORT AND OFFLINE GEOMETRY PASS',engine);
 }finally{await browser?.close();if(server){server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}if(!remoteClosed){remote.closeAllConnections();await new Promise(resolve=>remote.close(resolve));}fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
