'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,app,kind,read,wait,settled})=>{
 const target=app.locator('h1'),initial=read(),original=await target.textContent(),sup=page.getByRole('button',{name:'Superscript selected text',exact:true}),sub=page.getByRole('button',{name:'Subscript selected text',exact:true});
 const edit=async()=>{await target.click();await wait(async()=>await target.getAttribute('contenteditable')==='true');await target.evaluate(el=>{const d=el.ownerDocument,r=d.createRange();r.selectNodeContents(el);r.collapse(false);const selection=d.getSelection();selection.removeAllRanges();selection.addRange(r);});await wait(async()=>await sup.isEnabled());};
 const type=async text=>{await target.evaluate(el=>el.focus());await page.keyboard.insertText(text);assert.equal(read(),initial);};
 await edit();await sup.click();assert.equal(await sup.getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Finish text editing',exact:true}).click();await settled();assert.equal(read(),initial);assert.equal(await target.locator('sup').count(),0);
 await edit();const size=page.getByLabel('Selected text size (px)',{exact:true});await size.fill('24');await size.press('Enter');const color=page.getByLabel('Selected text color',{exact:true});await color.fill('#123456');await color.press('Enter');await sup.click();await type('2');await type('4');assert.equal(await target.locator('sup').count(),1);assert.equal(await target.locator('sup').textContent(),'24');assert.ok(await target.locator('sup').evaluate(el=>parseFloat(getComputedStyle(el).fontSize)<24&&getComputedStyle(el.parentElement).fontSize==='24px'));assert.equal(await target.locator('sup').evaluate(el=>getComputedStyle(el).color),'rgb(18, 52, 86)');
 await sub.click();assert.equal(await sub.getAttribute('aria-pressed'),'true');assert.equal(await sup.getAttribute('aria-pressed'),'false');await type('3');assert.equal(await target.locator('sub').textContent(),'3');assert.equal(await target.locator('sup sub,sub sup').count(),0);
 await sub.click();assert.equal(await sub.getAttribute('aria-pressed'),'false');await type('x');assert.equal(await target.textContent(),original+'243x');assert.equal(await target.locator('sup').textContent(),'24');assert.equal(await target.locator('sub').textContent(),'3');const last=await target.evaluate(el=>{const walker=el.ownerDocument.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(walker.nextNode())if(walker.currentNode.data.includes('x'))n=walker.currentNode;return [getComputedStyle(n.parentElement).fontSize,getComputedStyle(n.parentElement).color,!!n.parentElement.closest('sup,sub')];});assert.deepEqual(last,['24px','rgb(18, 52, 86)',false]);
 await page.keyboard.press('Control+z');assert.equal(await target.textContent(),original+'243');await page.keyboard.press('Control+z');assert.equal(await target.textContent(),original+'24');await page.keyboard.press('Control+Shift+z');await page.keyboard.press('Control+Shift+z');assert.equal(await target.textContent(),original+'243x');assert.equal(await target.locator('sup sub,sub sup').count(),0);
 if(process.env.RT_E2E_CARET_SCRIPT_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_CARET_SCRIPT_SCREENSHOT});
 await page.getByRole('button',{name:'Finish text editing',exact:true}).click();await settled();await wait(()=>read()!==initial);const saved=read();assert.equal(await target.textContent(),original+'243x');assert.equal(await target.locator('sup').textContent(),'24');assert.equal(await target.locator('sub').textContent(),'3');
 for(const [button,state]of [['Undo',initial],['Redo',saved],['Undo',initial]]){await page.getByRole('button',{name:button,exact:true}).click();await settled();await wait(()=>read()===state);}
 // Saved script wrappers containing literal styled leaves can split safely.
 await edit();await target.evaluate(el=>{const d=el.ownerDocument,r=d.createRange();r.setStart(el.firstChild,1);r.setEnd(el.firstChild,4);const selection=d.getSelection();selection.removeAllRanges();selection.addRange(r);});await sup.click();await color.fill('#123456');await color.press('Enter');await settled();await wait(()=>read()!==initial);const styled=read();assert.equal(await target.locator('sup > span').count(),1);
 await target.click();await wait(async()=>await target.getAttribute('contenteditable')==='true');await target.locator('sup > span').evaluate(el=>{const d=el.ownerDocument,r=d.createRange();r.setStart(el.firstChild,1);r.collapse(true);const selection=d.getSelection();selection.removeAllRanges();selection.addRange(r);});await sub.click();await target.evaluate(el=>el.focus());await page.keyboard.insertText('v');assert.equal(await target.locator('sub').textContent(),'v');assert.equal(await target.locator('sup sub,sub sup').count(),0);assert.equal(await target.locator('sub').evaluate(el=>getComputedStyle(el).color),'rgb(18, 52, 86)');await page.getByRole('button',{name:'Finish text editing',exact:true}).click();await settled();const switched=read();assert.notEqual(switched,styled);
 for(const state of [styled,initial]){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===state);}
 for(const state of [styled,switched]){await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===state);}
 for(const state of [styled,initial]){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===state);}
 console.log('CARET SCRIPT PASS '+kind+': unused draft, consecutive script typing, sup/sub/normal switching, retained size/color, no nested opposite scripts and local/source undo/redo');
};
