'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');
const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-compare-scroll-')),file=path.join(root,'index.html');
 const source='<!doctype html><html><head><style>body{margin:0;min-height:3000px;min-width:1500px}#outer{margin:10px;width:280px;height:200px;overflow:auto}#inner{width:220px;height:120px;overflow:auto;font:16px/20px sans-serif}#content{width:900px;height:600px;background:linear-gradient(red,blue)}#tail{height:1000px;width:500px}</style></head><body><div id="outer"><div id="inner"><div id="content">Scrollable content</div></div><div id="tail">Outer content</div></div></body></html>';fs.writeFileSync(file,source);fs.writeFileSync(path.join(root,'embedded-scroll.html'),'<style>body{margin:0;height:2400px}</style><p>Nested embedded page</p>');
 const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{
  browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1800,height:1200}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const wait=async fn=>{for(let n=0;n<100;n++){if(await fn())return;await new Promise(r=>setTimeout(r,50));}throw Error('Comparison scroll did not settle');};
  await page.goto('http://localhost:'+server.address().port+'/rt');await page.getByRole('button',{name:'Compare screens',exact:true}).click();await page.getByRole('button',{name:'Screen controls',exact:true}).click();
  const frame=page.frameLocator('iframe[title="Phone comparison preview"]'),viewport=page.getByRole('button',{name:'Edit from Phone comparison',exact:true});await frame.locator('#inner').waitFor();
  if(process.env.RT_E2E_COMPARE_RESIZE){
   const edge=page.getByRole('separator',{name:'Resize comparison panel',exact:true}),rail=page.locator('#screenComparisons'),width=()=>rail.evaluate(el=>el.offsetWidth);
   await frame.locator('body').evaluate(()=>window.widthProbe='kept');const originalWidth=await width();const drag=async delta=>{const box=await edge.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+80);await page.mouse.down();await page.mouse.move(box.x+box.width/2-delta,box.y+80);};
   await drag(130);await wait(async()=>await width()===originalWidth+130);await page.keyboard.press('Escape');await page.mouse.up();assert.equal(await width(),originalWidth);
   await drag(130);await page.mouse.up();assert.equal(await width(),400);await edge.press('Shift+ArrowLeft');assert.equal(await width(),450);await edge.press('ArrowRight');assert.equal(await width(),440);assert.equal(await frame.locator('body').evaluate(()=>window.widthProbe),'kept');assert.equal(await frame.locator('body').evaluate(()=>innerWidth),390);
   await page.reload();await page.getByRole('button',{name:'Compare screens',exact:true}).click();await frame.locator('#inner').waitFor();assert.equal(await width(),440);await edge.press('Home');assert.equal(await width(),240);await edge.press('End');assert.equal(await width(),640);
   await page.setViewportSize({width:1200,height:1200});await wait(async()=>await width()<640);assert.ok(await page.locator('#frameWrap').evaluate(el=>el.clientWidth)>=160);await page.setViewportSize({width:1800,height:1200});await wait(async()=>await width()===640);
   if(process.env.RT_E2E_COMPARE_WIDTH_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_COMPARE_WIDTH_SCREENSHOT});await edge.dblclick();assert.equal(await width(),270);assert.equal(fs.readFileSync(file,'utf8'),source);console.log('COMPARISON WIDTH/DRAG/CANCEL/KEYBOARD/PERSISTENCE/LIVE STATE PASS',engine);
  }
  if(process.env.RT_E2E_COMPARE_ORDER){
   const order=()=>page.locator('.compare-card').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('aria-label'))),up=()=>page.getByRole('button',{name:'Move Phone comparison up',exact:true}),down=()=>page.getByRole('button',{name:'Move Phone comparison down',exact:true});
   assert.equal(await up().isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Move Desktop comparison down',exact:true}).isDisabled(),true);
   await frame.locator('body').evaluate(()=>{window.reorderProbe='kept';const input=document.createElement('input');input.id='liveDraft';input.value='Unsaved preview draft';document.body.append(input);document.querySelector('#inner').scrollTop=70;scrollTo(0,300);});
   const phoneCard=page.getByRole('region',{name:'Phone comparison',exact:true}),hidePreview=()=>page.getByRole('button',{name:'Hide Phone preview',exact:true}),showPreview=()=>page.getByRole('button',{name:'Show Phone preview',exact:true});const expandedHeight=(await phoneCard.boundingBox()).height;
   await hidePreview().click();assert.equal(await showPreview().getAttribute('aria-expanded'),'false');assert.ok((await phoneCard.boundingBox()).height<expandedHeight-200);assert.equal(await page.locator('.compare-surface:visible').count(),2);if(process.env.RT_E2E_COLLAPSE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_COLLAPSE_SCREENSHOT});assert.equal(await frame.locator('body').evaluate(()=>window.reorderProbe),'kept');assert.equal(await frame.locator('body').evaluate(()=>innerWidth),390);await showPreview().click();assert.equal(await hidePreview().getAttribute('aria-expanded'),'true');assert.equal(await frame.locator('#liveDraft').inputValue(),'Unsaved preview draft');
   await page.getByRole('button',{name:'Hide all previews',exact:true}).click();assert.equal(await page.locator('.compare-surface:visible').count(),0);if(process.env.RT_E2E_BULK_PREVIEW_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_BULK_PREVIEW_SCREENSHOT});assert.equal(await page.getByRole('button',{name:/^Show (Phone|Tablet|Desktop) preview$/}).count(),3);assert.equal(await frame.locator('body').evaluate(()=>window.reorderProbe),'kept');assert.equal(await frame.locator('#liveDraft').inputValue(),'Unsaved preview draft');
   await page.getByRole('button',{name:'Show all previews',exact:true}).click();assert.equal(await page.locator('.compare-surface:visible').count(),3);assert.equal(await frame.locator('body').evaluate(()=>scrollY),300);assert.equal(await frame.locator('#inner').evaluate(el=>el.scrollTop),70);assert.equal(await frame.locator('#liveDraft').inputValue(),'Unsaved preview draft');
   await down().click();assert.deepEqual(await order(),['Tablet comparison','Phone comparison','Desktop comparison']);await wait(async()=>await frame.locator('body').evaluate(()=>scrollY)===300);assert.equal(await frame.locator('body').evaluate(()=>window.reorderProbe),'kept');assert.equal(await frame.locator('#liveDraft').inputValue(),'Unsaved preview draft');assert.equal(await frame.locator('#inner').evaluate(el=>el.scrollTop),70);
   assert.deepEqual(await page.locator('#screenPreset optgroup[label="Project screens"] option').allTextContents(),['Tablet · 768 × 1024','Phone · 390 × 844','Desktop · 1440 × 900']);
   const aligned=()=>page.evaluate(()=>[...document.querySelectorAll('.compare-card')].every(card=>{const viewport=card.querySelector('.compare-viewport').getBoundingClientRect(),frame=[...document.querySelectorAll('.compare-surface iframe')].find(frame=>frame.title===card.getAttribute('aria-label')+' preview'),surface=frame.parentElement.getBoundingClientRect();return ['left','top','width','height'].every(axis=>Math.abs(viewport[axis]-surface[axis])<1);}));
   await wait(aligned);await page.locator('#screenComparisons').evaluate(el=>el.scrollTop=400);await wait(aligned);await page.locator('#screenComparisons').evaluate(el=>el.scrollTop=0);
   const undoOrder=page.getByRole('button',{name:'Undo screen order',exact:true,includeHidden:true}),redoOrder=page.getByRole('button',{name:'Redo screen order',exact:true,includeHidden:true});
   await undoOrder.click();assert.deepEqual(await order(),['Phone comparison','Tablet comparison','Desktop comparison']);assert.equal(await undoOrder.isDisabled(),true);await redoOrder.click();assert.deepEqual(await order(),['Tablet comparison','Phone comparison','Desktop comparison']);assert.equal(await redoOrder.isDisabled(),true);
   await page.getByRole('button',{name:'Move Desktop comparison up',exact:true}).click();assert.deepEqual(await order(),['Tablet comparison','Desktop comparison','Phone comparison']);await undoOrder.click();await undoOrder.click();assert.deepEqual(await order(),['Phone comparison','Tablet comparison','Desktop comparison']);await redoOrder.click();assert.deepEqual(await order(),['Tablet comparison','Phone comparison','Desktop comparison']);
   await up().click();assert.equal(await redoOrder.isDisabled(),true,'A new move replaces the redo branch');await down().click();assert.equal(await frame.locator('body').evaluate(()=>window.reorderProbe),'kept');assert.equal(await frame.locator('#liveDraft').inputValue(),'Unsaved preview draft');assert.equal(await frame.locator('#inner').evaluate(el=>el.scrollTop),70);

   await hidePreview().click();await page.reload();await page.getByRole('button',{name:'Compare screens',exact:true}).click();await showPreview().waitFor();assert.equal(await showPreview().getAttribute('aria-expanded'),'false');await showPreview().click();await frame.locator('#inner').waitFor();assert.deepEqual(await order(),['Tablet comparison','Phone comparison','Desktop comparison']);
   await page.getByRole('button',{name:'Remove Tablet comparison',exact:true}).click();await wait(async()=>await page.locator('.compare-card').count()===2);const restore=page.getByRole('button',{name:'Undo remove: Tablet',exact:true});await wait(async()=>!await restore.isDisabled());await restore.click();assert.deepEqual(await order(),['Tablet comparison','Phone comparison','Desktop comparison']);assert.equal(await undoOrder.isDisabled(),true,'Changing the screen set clears order history');assert.equal(await redoOrder.isDisabled(),true);
   await down().click();assert.deepEqual(await order(),['Tablet comparison','Desktop comparison','Phone comparison']);assert.equal(await down().isDisabled(),true);await up().click();await up().click();assert.deepEqual(await order(),['Phone comparison','Tablet comparison','Desktop comparison']);assert.equal(await up().isDisabled(),true);assert.equal(fs.readFileSync(file,'utf8'),source);
   await page.getByRole('button',{name:'Compare screens',exact:true}).click();await wait(async()=>!await page.getByRole('button',{name:'Compare screens',exact:true}).isDisabled());await page.getByRole('button',{name:'Compare screens',exact:true}).click();await frame.locator('#inner').waitFor();assert.equal(await undoOrder.isDisabled(),true);assert.equal(await redoOrder.isDisabled(),true);assert.deepEqual(await order(),['Phone comparison','Tablet comparison','Desktop comparison']);
   if(process.env.RT_E2E_COMPARE_ORDER_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_COMPARE_ORDER_SCREENSHOT});await frame.locator('body').evaluate(()=>scrollTo(0,0));console.log('COMPARISON ORDER/PERSISTENCE/BOUNDARIES/SOURCE PASS',engine);
  }

  await viewport.scrollIntoViewIfNeeded();const box=await viewport.boundingBox(),scale=box.width/390;
  const wheel=async(dx,dy,deltaMode=0)=>{await viewport.dispatchEvent('wheel',{clientX:box.x+30*scale,clientY:box.y+30*scale,deltaX:dx,deltaY:dy,deltaMode,bubbles:true,cancelable:true});};
  const positions=()=>frame.locator('body').evaluate(()=>({inner:[document.querySelector('#inner').scrollLeft,document.querySelector('#inner').scrollTop],outer:[document.querySelector('#outer').scrollLeft,document.querySelector('#outer').scrollTop],page:[scrollX,scrollY]}));
  const near=(a,b)=>assert.ok(Math.abs(a-b)<1.1,`${a} vs ${b}`);
  await page.mouse.move(box.x+30*scale,box.y+30*scale);await page.mouse.wheel(40,50);await wait(async()=>(await positions()).inner[1]>0);let pos=await positions();near(pos.inner[0],40/scale);near(pos.inner[1],50/scale);assert.deepEqual(pos.outer,[0,0]);assert.deepEqual(pos.page,[0,0]);
  await frame.locator('#inner').evaluate(el=>{el.scrollLeft=0;el.scrollTop=0;});await wheel(0,2,1);near((await positions()).inner[1],40);
  await frame.locator('#inner').evaluate(el=>{el.scrollLeft=el.scrollWidth;el.scrollTop=el.scrollHeight;});
  await wheel(20,30);pos=await positions();near(pos.outer[0],20/scale);near(pos.outer[1],30/scale);assert.deepEqual(pos.page,[0,0]);
  await frame.locator('#outer').evaluate(el=>{el.scrollLeft=0;el.scrollTop=0;});
  await frame.locator('#inner').evaluate(el=>{el.style.overscrollBehavior='contain';});await wheel(20,30);pos=await positions();assert.deepEqual(pos.outer,[0,0]);assert.deepEqual(pos.page,[0,0]);
  await frame.locator('#inner').evaluate(el=>{el.style.overscrollBehavior='auto';el.scrollTop=0;el.scrollLeft=0;});
  await wheel(0,1,2);pos=await positions();assert.ok(pos.inner[1]>400);assert.ok(pos.outer[1]>0);assert.deepEqual(pos.page,[0,0]);
  await frame.locator('#outer').evaluate(el=>{el.scrollTop=el.scrollHeight;el.scrollLeft=el.scrollWidth;});
  await wheel(20,30);pos=await positions();near(pos.page[0],20/scale);near(pos.page[1],30/scale);
  await frame.locator('body').evaluate(()=>{scrollTo(0,0);for(const id of ['outer','inner']){const el=document.getElementById(id);el.scrollLeft=0;el.scrollTop=0;}});
  const widthInput=page.getByLabel('Phone comparison width',{exact:true});await widthInput.fill('650');await widthInput.press('Tab');await wait(()=>frame.locator('body').evaluate(()=>innerWidth===650));
  await wait(async()=>Math.abs((await viewport.boundingBox()).height-(box.width/650)*844)<1);
  const resized=await viewport.boundingBox(),newScale=resized.width/650;await page.mouse.move(resized.x+30*newScale,resized.y+30*newScale);await page.mouse.wheel(20,10);await wait(async()=>(await positions()).inner[1]>0);
  pos=await positions();near(pos.inner[0],20/newScale);near(pos.inner[1],10/newScale);assert.deepEqual(pos.outer,[0,0]);assert.deepEqual(pos.page,[0,0]);
  // SVG descendants have no scrollBy in either engine. Input must still reach
  // their containing scroller, including inside nested open shadow roots.
  await frame.locator('body').evaluate(()=>{
   scrollTo(0,0);const host=document.createElement('div');host.id='shadowScroll';host.style.cssText='position:fixed;inset:0;z-index:1000';document.body.append(host);
   const first=host.attachShadow({mode:'open'}),innerHost=document.createElement('div');first.append(innerHost);
   innerHost.attachShadow({mode:'open'}).innerHTML='<style>#scroller{width:600px;height:800px;overflow:auto;overscroll-behavior:contain}svg{display:block;width:1200px;height:1600px}</style><div id="scroller"><svg viewBox="0 0 1200 1600"><rect width="1200" height="1600" fill="cornflowerblue"/></svg></div>';
  });
  const shadowPosition=()=>frame.locator('#shadowScroll').evaluate(host=>{const node=host.shadowRoot.firstChild.shadowRoot.getElementById('scroller');return [node.scrollLeft,node.scrollTop];});
  const resetShadow=()=>frame.locator('#shadowScroll').evaluate(host=>host.shadowRoot.firstChild.shadowRoot.getElementById('scroller').scrollTo(0,0));
  await page.mouse.move(resized.x+30*newScale,resized.y+30*newScale);await page.mouse.wheel(20,30);await wait(async()=>(await shadowPosition())[1]>0);near((await shadowPosition())[0],20/newScale);near((await shadowPosition())[1],30/newScale);assert.deepEqual(await frame.locator('body').evaluate(()=>[scrollX,scrollY]),[0,0]);
  await resetShadow();await viewport.press('ArrowDown');assert.deepEqual(await shadowPosition(),[0,40]);await viewport.press('ArrowRight');assert.deepEqual(await shadowPosition(),[40,40]);await viewport.press('PageDown');assert.deepEqual(await shadowPosition(),[40,760]);await viewport.press('End');assert.deepEqual(await shadowPosition(),[40,800]);await viewport.press('ArrowDown');assert.deepEqual(await frame.locator('body').evaluate(()=>[scrollX,scrollY]),[0,0]);await viewport.press('Home');assert.deepEqual(await shadowPosition(),[40,0]);
  await frame.locator('#shadowScroll').evaluate(host=>{const node=host.shadowRoot.firstChild.shadowRoot.getElementById('scroller');node.style.overscrollBehavior='auto';node.scrollTop=800;});await viewport.press('ArrowDown');assert.equal(await frame.locator('body').evaluate(()=>scrollY),40,'shadow scroller boundary hands off to the page');
  await frame.locator('#shadowScroll').evaluate(host=>host.remove());await frame.locator('body').evaluate(()=>scrollTo(0,0));
  await frame.locator('body').evaluate(()=>{
   const embed=document.createElement('iframe');embed.id='scrollEmbed';embed.style.cssText='position:fixed;top:0;left:0;width:600px;height:800px;border:4px solid black;transform:scale(.75);transform-origin:top left;z-index:1000';
   embed.srcdoc='<style>html{scroll-behavior:smooth}body{margin:0;min-width:1400px;min-height:2200px}#inside{width:500px;height:600px;overflow:auto;overscroll-behavior:contain;font:16px/20px sans-serif}#art{width:1000px;height:1200px;background:linear-gradient(red,blue)}</style><div id="inside"><div id="art">Embedded</div></div>';document.body.append(embed);
  });
  const embedded=frame.locator('#scrollEmbed');await wait(()=>embedded.evaluate(el=>!!el.contentDocument?.getElementById('inside')));
  const embeddedPositions=()=>embedded.evaluate(el=>{const w=el.contentWindow,n=w.document.getElementById('inside');return {inner:[n.scrollLeft,n.scrollTop],page:[w.scrollX,w.scrollY]};});
  const embeddedReset=()=>embedded.evaluate(el=>{el.contentWindow.scrollTo({left:0,top:0,behavior:'instant'});el.contentDocument.getElementById('inside').scrollTo({left:0,top:0,behavior:'instant'});});
  await page.mouse.move(resized.x+30*newScale,resized.y+30*newScale);await page.mouse.wheel(15,30);await wait(async()=>(await embeddedPositions()).inner[1]>0);near((await embeddedPositions()).inner[0],15/(newScale*.75));near((await embeddedPositions()).inner[1],30/(newScale*.75));assert.deepEqual((await embeddedPositions()).page,[0,0]);
  await embeddedReset();await viewport.press('ArrowDown');assert.deepEqual((await embeddedPositions()).inner,[0,40]);await viewport.press('PageDown');assert.deepEqual((await embeddedPositions()).inner,[0,580]);await viewport.press('End');assert.deepEqual((await embeddedPositions()).inner,[0,600]);await viewport.press('ArrowDown');assert.deepEqual((await embeddedPositions()).page,[0,0],'inner containment prevents embedded root scroll');
  await embedded.evaluate(el=>el.contentDocument.getElementById('inside').style.overscrollBehavior='auto');await viewport.press('ArrowDown');assert.deepEqual((await embeddedPositions()).page,[0,40],'inner boundary hands off to embedded root');
  await embedded.evaluate(el=>{el.contentWindow.scrollTo({left:0,top:10000,behavior:'instant'});el.contentDocument.documentElement.style.overscrollBehavior='contain';});await viewport.press('ArrowDown');assert.deepEqual(await frame.locator('body').evaluate(()=>[scrollX,scrollY]),[0,0],'embedded root containment prevents parent scroll');
  await embedded.evaluate(el=>el.contentDocument.documentElement.style.overscrollBehavior='auto');await viewport.press('ArrowDown');assert.equal(await frame.locator('body').evaluate(()=>scrollY),30,'remaining delta maps through iframe scale before parent handoff');
  await frame.locator('body').evaluate(()=>scrollTo(0,0));await embeddedReset();
  await embedded.evaluate(el=>{const child=el.contentDocument.createElement('iframe');child.id='nested';child.style.cssText='position:fixed;inset:0;width:600px;height:800px;border:0';child.src='/embedded-scroll.html';el.contentDocument.body.append(child);});
  await wait(()=>embedded.evaluate(el=>el.contentDocument.getElementById('nested')?.contentDocument?.body?.scrollHeight>=2400));await viewport.press('PageDown');assert.equal(await embedded.evaluate(el=>el.contentDocument.getElementById('nested').contentWindow.scrollY),720,'keyboard page size uses nested embedded viewport');
  await embedded.evaluate(el=>new Promise(resolve=>{el.addEventListener('load',()=>resolve(),{once:true});el.setAttribute('sandbox','');el.srcdoc='<style>body{height:2400px}</style>Opaque embedded page';}));await viewport.press('ArrowDown');assert.equal(await frame.locator('body').evaluate(()=>scrollY),40,'opaque sandbox is not probed');
  await frame.locator('body').evaluate(()=>scrollTo(0,0));await embedded.evaluate((el,url)=>{el.removeAttribute('sandbox');el.removeAttribute('srcdoc');el.src=url;},'http://127.0.0.1:'+server.address().port+'/');await viewport.press('ArrowDown');assert.equal(await frame.locator('body').evaluate(()=>scrollY),40,'known cross-origin frame is not probed');
  await embedded.evaluate(el=>el.remove());await frame.locator('body').evaluate(()=>scrollTo(0,0));
  assert.deepEqual(await page.frameLocator('#app').locator('body').evaluate(()=>[scrollX,scrollY]),[0,0]);assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);
  await page.getByRole('button',{name:'Compare screens',exact:true}).click();await wait(async()=>await page.locator('#screenComparisons iframe').count()===0);
  console.log(engine+': PASS nested comparison scroll, both scaled axes after resizing, line/page deltas, ancestor handoff, overscroll containment, main-canvas isolation and unchanged source');
 }finally{if(browser)await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
