'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const original=read(),screen=page.getByLabel('Screen size',{exact:true}),scope=page.getByLabel('Style screen scope',{exact:true});await screen.selectOption('768x1024');await settled();await scope.selectOption(kind==='html'?'min-[768px]:':'md:');const selectedScope=await scope.inputValue();await page.getByRole('button',{name:'Compare screens',exact:true}).click();const preview=page.frameLocator('iframe[title="Phone comparison preview"]'),viewport=page.getByRole('button',{name:'Edit from Phone comparison',exact:true}),menu=page.getByRole('menu',{name:'Canvas actions',exact:true});await preview.locator('h1').waitFor();
 const bounds=await viewport.boundingBox(),point=await preview.locator('h1').evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x+Math.min(10,r.width/2),y:r.y+r.height/2};}),scale=bounds.width/390;await viewport.click({button:'right',position:{x:point.x*scale,y:point.y*scale}});await menu.waitFor();await settled();assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[390,844]);assert.equal(await scope.inputValue(),selectedScope);assert.equal(read(),original);assert.equal(await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).getAttribute('aria-selected'),'true');
 await page.keyboard.press('Escape');await menu.waitFor({state:'detached'});assert.equal(await viewport.evaluate(el=>el===document.activeElement),true);await page.getByRole('treeitem',{name:'p · Other text',exact:true}).click({modifiers:['Shift']});await settled();await viewport.press('Shift+F10');await menu.waitFor();assert.equal(await page.getByRole('treeitem',{selected:true}).count(),2);assert.equal(read(),original);assert.equal(await scope.inputValue(),selectedScope);if(process.env.RT_E2E_COMPARISON_CONTEXT_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_COMPARISON_CONTEXT_SCREENSHOT});
 if(kind!=='html'){assert.equal(await menu.locator('[data-action-id="layer-duplicateElement"]').isDisabled(),true);await page.keyboard.press('Escape');await menu.waitFor({state:'detached'});await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).click();await settled();await viewport.press('Shift+F10');await menu.waitFor();}
 await menu.locator('[data-action-id="layer-duplicateElement"]').click();await wait(()=>read()!==original);await settled();const duplicated=read();await wait(async()=>await app.locator('h1').count()===2);assert.equal(await app.locator('p').count(),kind==='html'?3:2);await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();await wait(async()=>await app.locator('h1').count()===1);await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===duplicated);await settled();await wait(async()=>await app.locator('h1').count()===2);assert.equal(await app.locator('p').count(),kind==='html'?3:2);
 assert.equal(await scope.inputValue(),selectedScope);console.log(kind+': PASS comparison pointer/keyboard context menu, scope preservation, focus return, multi-selection preservation/capability guards, duplicate and exact undo/redo');
};
