'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const fixture=process.env.RT_INSPECTOR_FIXTURE,build=process.env.RT_BUILD_FIXTURE||fixture,engine=process.env.RT_E2E_BROWSER||'chromium';if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-component-default-')),file=path.join(root,'app/page.jsx'),definition=path.join(root,'app/Card.tsx');fs.mkdirSync(path.dirname(file));fs.symlinkSync(path.join(build,'node_modules'),path.join(root,'node_modules'),'dir');fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({private:true,dependencies:{next:'16.2.5',react:'19.2.0','react-dom':'19.2.0'}}));fs.writeFileSync(path.join(root,'app/layout.jsx'),'export default function Layout({children}){return <html><body>{children}</body></html>}');
 const source='"use client";import Card from "./Card";export default function Page(){return <main><input defaultValue="Initial"/><Card/><Card label="Override" count={8} enabled={false} size="large" note="Instance note"/><Card/></main>}',original='export default function Card({label="Original",count=2,enabled=true,size="small",note}:{label?:string;count?:number;enabled?:boolean;size?:"small"|"large";note?:string}){return enabled?<output data-label={label} data-count={count} data-enabled={String(enabled)} data-size={size} data-note={note}>{label}</output>:<article data-label={label} data-count={count} data-enabled={String(enabled)} data-size={size} data-note={note}>{label}</article>}';fs.writeFileSync(file,source);fs.writeFileSync(definition,original);fs.writeFileSync(path.join(root,'tsconfig.json'),JSON.stringify({compilerOptions:{jsx:'preserve',strict:true,noEmit:true,moduleResolution:'bundler',module:'esnext',target:'es2017',esModuleInterop:true,skipLibCheck:true},include:['**/*.ts','**/*.tsx']}));
 let logs='',url,browser,page;const child=spawn(process.execPath,[path.resolve(__dirname,'../../bin/retouch.cjs'),'--',process.execPath,path.join(build,'node_modules/next/dist/bin/next'),'dev','--webpack','-p','0'],{cwd:root,env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});let exited=false;const stopped=new Promise(resolve=>child.once('exit',()=>{exited=true;resolve();}));for(const stream of [child.stdout,child.stderr])stream.on('data',chunk=>{logs+=chunk;url=logs.match(/http:\/\/localhost:(\d+)/)?.[0];});
 const wait=async fn=>{for(let i=0;i<300;i++){try{if(await fn())return;}catch(error){if(!/Execution context was destroyed|ECONNREFUSED|fetch failed/.test(error.message))throw error;}if(exited)throw Error(logs);await new Promise(resolve=>setTimeout(resolve,100));}throw Error('Timed out: '+logs.slice(-2000));};
 try{
  await wait(()=>url);await wait(async()=>(await fetch(url+'/rt/__api/health')).ok);browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();page=await browser.newPage({viewport:{width:1500,height:1000}});page.setDefaultTimeout(45000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/rt',{timeout:90000});const app=page.frameLocator('#app');await app.locator('output').first().waitFor({timeout:90000});await app.locator('input').evaluate(el=>{el.value='Retained';window.originalDocument=el.ownerDocument;});await page.getByRole('button',{name:'Compare screens',exact:true}).click();const tablet=page.frameLocator('iframe[title="Tablet comparison preview"]');await tablet.locator('output').first().waitFor();await page.waitForFunction(()=>RetouchClientMount.ready(document.querySelector('iframe[title="Tablet comparison preview"]').contentDocument));await tablet.locator('input').evaluate(el=>{el.value='Tablet retained';window.originalDocument=el.ownerDocument;});const rows=page.getByRole('treeitem',{name:'Card · component',exact:true});await wait(async()=>await rows.count()===3);await rows.first().click();const settled=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy),read=()=>fs.readFileSync(definition,'utf8');await settled();
  const dialog=page.getByRole('dialog',{name:'Edit component default'}),open=async name=>{await page.getByRole('button',{name:'Edit default for '+name,exact:true}).click();await dialog.waitFor();},update=async(name,value)=>{await open(name);const field=dialog.getByLabel('Default value',{exact:true});if(await field.evaluate(el=>el.localName)==='select')await field.selectOption({label:String(value)});else await field.fill(String(value));await dialog.getByRole('button',{name:'Update default',exact:true}).click();await dialog.waitFor({state:'hidden'});await settled();await retention(name);},values=name=>app.locator('output,article').evaluateAll((elements,name)=>elements.map(el=>el.getAttribute('data-'+name)),name),rendered=(name,expected)=>wait(async()=>JSON.stringify(await values(name))===JSON.stringify(expected)&&JSON.stringify(await tablet.locator('output,article').evaluateAll((els,name)=>els.map(el=>el.getAttribute('data-'+name)),name))===JSON.stringify(expected));
  const retention=async stage=>assert.deepEqual(await tablet.locator('input').evaluate(el=>({value:el.value,same:window.originalDocument===el.ownerDocument})),{value:'Tablet retained',same:true},stage);await retention('initial');
  await open('label');await dialog.getByLabel('Default value').fill('Cancelled');await page.keyboard.press('Escape');assert.equal(read(),original);
  await update('label','Shared "text"\nSecond line');await rendered('label',['Shared "text"\nSecond line','Override','Shared "text"\nSecond line']);assert.equal(fs.readFileSync(file,'utf8'),source);const changed=read();assert.notEqual(changed,original);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await retention('undo');assert.equal(read(),original);await rendered('label',['Original','Override','Original']);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await retention('redo');assert.equal(read(),changed);
  await update('count',-12.5);await rendered('count',['-12.5','8','-12.5']);await update('enabled',false);await rendered('enabled',['false','false','false']);await update('size','large');await rendered('size',['large','large','large']);
  await rows.nth(1).click();await settled();assert.equal(await page.getByLabel('Component property label',{exact:true}).inputValue(),'Override');await page.getByRole('button',{name:'Reset label to default',exact:true}).click();await settled();await rendered('label',['Shared "text"\nSecond line','Shared "text"\nSecond line','Shared "text"\nSecond line']);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),source);await rendered('label',['Shared "text"\nSecond line','Override','Shared "text"\nSecond line']);
  await page.getByRole('button',{name:'Reset properties',exact:true}).click();await settled();await rendered('label',['Shared "text"\nSecond line','Shared "text"\nSecond line','Shared "text"\nSecond line']);await rendered('count',['-12.5','-12.5','-12.5']);await rendered('note',[null,null,null]);await retention('reset properties');assert.equal(await page.getByRole('button',{name:'Reset properties',exact:true}).count(),0);const resetSource=fs.readFileSync(file,'utf8');assert.notEqual(resetSource,source);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),source);await rendered('count',['-12.5','8','-12.5']);await rendered('note',[null,'Instance note',null]);await retention('undo reset properties');await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),resetSource);await rendered('note',[null,null,null]);await retention('redo reset properties');await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),source);
  await open('label');await page.screenshot({path:'/tmp/retouch-component-default-'+engine+'.png'});await page.keyboard.press('Escape');await page.screenshot({path:'/tmp/retouch-component-reset-'+engine+'.png'});assert.equal(await app.locator('input').inputValue(),'Retained');assert.equal(await app.locator('input').evaluate(el=>window.originalDocument===el.ownerDocument),true);assert.equal(await tablet.locator('input').inputValue(),'Tablet retained');assert.equal(await tablet.locator('input').evaluate(el=>window.originalDocument===el.ownerDocument),true);assert.deepEqual(errors,[]);console.log(engine+': shared text/number/boolean/choice defaults, preserved overrides, reset inheritance and all editable properties, exact undo/redo and retained preview document/input passed');
 }catch(error){await page?.screenshot({path:'/tmp/retouch-component-default-failure-'+engine+'.png'});console.error(await page?.locator('#toasts').textContent());throw error;}finally{await browser?.close();if(!exited)child.kill('SIGTERM');await stopped;fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
