'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium';
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-comparison-locks-')),file=path.join(root,'index.html');
 const source='<!doctype html><html><head><style>body{margin:0}h1,h2{margin:0;padding:20px}#stack{position:relative;height:300px}#behind,#front{position:absolute;inset:0;background:white}</style></head><body><main><h1>Other layer</h1><div id="stack"><section id="behind"><h2>Behind</h2></section><article id="front"><h2>Front</h2></article></div></main></body></html>';fs.writeFileSync(file,source);
 const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{
  browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:'+server.address().port+'/rt');const app=page.frameLocator('#app');await app.locator('h1').waitFor();await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await page.getByRole('treeitem',{name:'h1 · Other layer',exact:true}).click();await page.getByLabel('Style screen scope').selectOption('min-[768px]:');
  await page.getByRole('button',{name:'Compare screens',exact:true}).click();const preview=page.frameLocator('iframe[title="Phone comparison preview"]'),viewport=page.getByRole('button',{name:'Edit from Phone comparison',exact:true});await preview.locator('h2').first().waitFor();
  const clickFront=async(waitForSelection=true)=>{const point=await preview.locator('#front h2').evaluate(el=>{const box=el.getBoundingClientRect();return{x:box.left+30,y:box.top+20,width:innerWidth};});const box=await viewport.boundingBox();await viewport.click({position:{x:point.x*box.width/point.width,y:point.y*box.width/point.width}});if(waitForSelection)await page.waitForFunction(()=>doc().defaultView.innerWidth===390&&!panelTasks&&!sourceRequests&&sel?.info?.tag==='h2');};
  const selected=label=>page.getByRole('treeitem',{name:label,exact:true}).getAttribute('aria-selected');
  await page.getByRole('button',{name:'Lock article · front',exact:true}).click();await clickFront();assert.equal(await selected('h2 · Behind'),'true','A comparison click passes through an inherited lock');assert.equal(await page.getByLabel('Style screen scope').inputValue(),'min-[768px]:');assert.equal(fs.readFileSync(file,'utf8'),source);
  await page.getByRole('button',{name:'Unlock article · front',exact:true}).click();await clickFront();await page.waitForFunction(()=>renderedSelection?.element?.textContent==='Front');assert.equal(await selected('h2 · Front'),'true');
  await page.getByRole('button',{name:'Lock h2 · Front',exact:true}).click();await clickFront();assert.equal(await selected('h2 · Behind'),'true','A comparison click passes through a direct lock');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Lock h2 · Front',exact:true}).waitFor();await clickFront();await page.waitForFunction(()=>renderedSelection?.element?.textContent==='Front');assert.equal(await selected('h2 · Front'),'true');
  await preview.locator('#front').evaluate(el=>el.style.visibility='hidden');await clickFront();await page.waitForFunction(()=>renderedSelection?.element?.textContent==='Behind');assert.equal(await selected('h2 · Behind'),'true','Hidden layers do not intercept comparison selection');await preview.locator('#front').evaluate(el=>el.style.removeProperty('visibility'));
  await page.getByRole('button',{name:'Lock main',exact:true}).click();await page.getByRole('treeitem',{name:'h1 · Other layer',exact:true}).click();await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await page.waitForFunction(()=>doc().defaultView.innerWidth===768);await clickFront(false);
  assert.equal(await selected('h1 · Other layer'),'true','No unlocked target preserves the existing Layers selection');assert.deepEqual(await app.locator('body').evaluate(()=>[innerWidth,innerHeight]),[768,1024]);assert.equal(await page.getByLabel('Style screen scope').inputValue(),'min-[768px]:');
  assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);console.log('COMPARISON DIRECT/INHERITED LOCK PICKING/UNLOCK/HISTORY/SCOPE/SOURCE PASS',engine);
 }finally{if(browser)await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
