'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const states=[read()],scope=page.getByLabel('Style screen scope',{exact:true}),screen=page.getByLabel('Screen size',{exact:true}),blur=page.getByLabel('Layer blur (px)',{exact:true}),backdrop=page.getByLabel(kind==='html'?'Background blur (px)':'Backdrop blur (px)',{exact:true}),rendered=()=>app.locator('h1').evaluate(el=>({filter:getComputedStyle(el).filter,backdrop:getComputedStyle(el).backdropFilter}));
 const open=async()=>{const button=page.getByRole('button',{name:'Expand Effects section',exact:true});if(await button.isVisible())await button.click();},edit=async(input,value)=>{await input.fill(value);await input.press('Enter');await wait(()=>read()!==states.at(-1));await settled();states.push(read());await open();};
 await open();await edit(blur,'2');await edit(backdrop,'4');await screen.focus();await screen.selectOption('768x1024');await settled();await scope.selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await edit(blur,'11');await edit(backdrop,'12');const tablet=await rendered();
 await scope.selectOption('');await settled();assert.equal(await blur.inputValue(),'2');assert.equal(await backdrop.inputValue(),'4');await edit(blur,'3');await edit(backdrop,'5');assert.deepEqual(await rendered(),tablet);
 await screen.focus();await screen.selectOption('390x844');await settled();const phone=await rendered();assert.deepEqual(phone,{filter:'blur(3px)',backdrop:'blur(5px)'});await scope.selectOption(kind==='html'?'min-[768px]:':'md:');await settled();assert.equal(await blur.inputValue(),'11');assert.equal(await backdrop.inputValue(),'12');await edit(blur,'13');assert.deepEqual(await rendered(),phone);const beforePreview=read();await page.getByRole('button',{name:'Preview edit range',exact:true}).click();await settled();assert.equal(read(),beforePreview);assert.deepEqual(await rendered(),{...tablet,filter:'blur(13px)'});
 await scope.selectOption('');await settled();for(const prefix of ['Layer','Backdrop']){const summary=page.getByText(prefix+' filter stack',{exact:true});if(!await summary.evaluate(el=>el.parentElement.open))await summary.click();await summary.locator('..').getByRole('button',{name:'Clear '+prefix.toLowerCase()+' filters',exact:true}).click();await wait(()=>read()!==states.at(-1));await settled();states.push(read());await open();}await scope.selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await screen.focus();await screen.selectOption('390x844');await settled();assert.deepEqual(await rendered(),{filter:'none',backdrop:'none'});assert.equal(await page.locator('[data-section=effects]').getAttribute('data-empty-effects'),'false');assert.equal(await blur.inputValue(),'13');assert.equal(await backdrop.inputValue(),'12');
 for(const expected of states.slice(0,-1).reverse()){await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===expected);await settled();}
 for(const expected of states.slice(1)){await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===expected);await settled();}
 console.log(kind+': PASS scoped layer/backdrop blur, base and inactive edits, source-aware Effects state, preview navigation and exact undo/redo');
};
