'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind,engine})=>{
const add=async()=>{await page.getByRole('button',{name:'Add paint',exact:true}).click();await page.getByRole('button',{name:'Add gradient paint',exact:true}).click();};
 const menu=async index=>{const button=page.getByRole('button',{name:'Paint '+index+' actions',exact:true});if(await button.getAttribute('aria-expanded')!=='true')await button.click();};
 const action=async(name,index)=>{await menu(index);await page.getByRole('button',{name,exact:true}).click();};
 const focused=async name=>wait(async()=>await page.getByRole('button',{name,exact:true}).evaluate(el=>el===document.activeElement));
   let activePaint=1;assert.ok(['react','liquid'].includes(kind));const before=read(),states=[before],open=async(index=activePaint)=>{activePaint=index;const button=page.getByRole('button',{name:'Edit gradient paint '+index,exact:true});if(await button.getAttribute('aria-expanded')!=='true')await button.click();},checkpoint=async()=>{await wait(()=>read()!==states.at(-1));
   await settled();states.push(read());
   await open();},appearance=()=>app.locator('h1').evaluate(el=>{const css=getComputedStyle(el);return [css.backgroundColor,css.backgroundSize,css.backgroundPosition,css.backgroundRepeat];}),baseline=await appearance();
   await page.getByLabel('Screen size',{exact:true}).focus();
   await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');
   await settled();
   await page.getByLabel('Style screen scope').selectOption('md:');
   await settled();assert.equal(await page.getByRole('button',{name:'Clear background images',exact:true}).isVisible(),false);
   await add();
   await open(1);
   await checkpoint();const beforeLastFillRemoval=read();
   await page.getByRole('button',{name:'Remove paint 1',exact:true}).press('Enter');
   await wait(()=>read()!==beforeLastFillRemoval);
   await settled();
   await wait(async()=>await page.getByRole('button',{name:'Add paint',exact:true}).evaluate(el=>el===document.activeElement));
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===beforeLastFillRemoval);
   await settled();
   await open(1);const pickerCanvas=()=>app.locator('h1').evaluate(el=>({image:getComputedStyle(el).backgroundImage,style:el.getAttribute('style')})),pickerCanvasBefore=await pickerCanvas();const beforePicker=read(),pickerButton=page.getByRole('button',{name:'Edit Paint 1 stop 1 color',exact:true});
   await pickerButton.click();const picker=page.getByRole('dialog',{name:'Edit Paint 1 stop 1 color',exact:true});
   await picker.getByLabel('Color value',{exact:true}).fill('hsl(210deg 50% 40% / 50%)');
   await page.evaluate(()=>renderPanel());assert.ok(await picker.isVisible());assert.equal(await picker.getByLabel('Color value',{exact:true}).inputValue(),'hsl(210deg 50% 40% / 50%)');
   await picker.getByRole('slider',{name:'Saturation and brightness',exact:true}).press('ArrowRight');assert.notEqual((await pickerCanvas()).image,pickerCanvasBefore.image);assert.ok((await pickerCanvas()).style.includes('background-image:'));assert.equal(read(),beforePicker);
   await page.keyboard.press('Escape');
   await picker.waitFor({state:'detached'});assert.equal(read(),beforePicker);assert.deepEqual(await pickerCanvas(),pickerCanvasBefore);
   await pickerButton.click();
   await picker.getByLabel('Color value',{exact:true}).fill('not-a-color');assert.equal(await picker.getByRole('button',{name:'Apply color',exact:true}).isDisabled(),true);assert.ok(await picker.isVisible());assert.equal(read(),beforePicker);
   await picker.getByLabel('Color value',{exact:true}).fill('color(display-p3 1 0.2 0.3 / 0.4)');assert.ok(await picker.getByLabel('Display P3 red',{exact:true}).isVisible());
   await picker.getByRole('slider',{name:'Opacity (%)',exact:true}).press('Home');assert.ok((await picker.getByLabel('Color value',{exact:true}).inputValue()).includes('display-p3 1 0.2 0.3 / 0'));
   await picker.getByLabel('Color value',{exact:true}).fill('#33669980');
   await picker.getByLabel('Opacity value (%)',{exact:true}).fill('50');assert.equal(await picker.getByLabel('Color value',{exact:true}).inputValue(),'rgb(51 102 153 / 0.5)');
   await picker.getByLabel('Red (0–255)',{exact:true}).fill('90');assert.equal(await picker.getByLabel('Color value',{exact:true}).inputValue(),'rgb(90 102 153 / 0.5)');
   await picker.getByLabel('Color model',{exact:true}).selectOption('hsl');assert.equal(await picker.getByLabel('Color value',{exact:true}).inputValue(),'rgb(90 102 153 / 0.5)');
   await picker.getByLabel('Hue (deg)',{exact:true}).fill('120');if(process.env.RT_E2E_PICKER_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_PICKER_SCREENSHOT});
   await picker.getByLabel('Color value',{exact:true}).press('Enter');
   await wait(()=>read()!==beforePicker);
   await settled();assert.deepEqual(await page.getByLabel('Paint 1 stop 1 color',{exact:true}).evaluate(el=>{const paint=RetouchPaletteValues.parse(RetouchColorStyles.fromComputed(el.value));return [...paint.channels.map(value=>Math.round(value*255)),paint.alpha];}),[90,153,90,0.5]);
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===beforePicker);
   await settled();await open(1);assert.deepEqual(await pickerCanvas(),pickerCanvasBefore);const stopGeometry=await page.getByLabel('Paint 1 stop 1 color',{exact:true}).evaluate(el=>{const row=el.closest('.gradient-stop-row'),color=el.getBoundingClientRect(),position=row.querySelector('input[type=number]').getBoundingClientRect(),remove=row.querySelector(':scope > button').getBoundingClientRect();return {tabOrder:row.querySelector('input').type==='number',height:row.getBoundingClientRect().height,ordered:position.right<=color.left+1&&color.right<=remove.left+1,aligned:Math.abs(position.top-color.top)<2};});assert.equal(stopGeometry.tabOrder,true);assert.ok(stopGeometry.height>0&&stopGeometry.height<=36);assert.equal(stopGeometry.ordered,true);assert.equal(stopGeometry.aligned,true);if(process.env.RT_E2E_STOP_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_STOP_SCREENSHOT});
   await page.getByLabel('Paint 1 Angle (deg)',{exact:true}).fill('45');
   await page.getByLabel('Paint 1 Angle (deg)',{exact:true}).press('Tab');
   await checkpoint();const angleHandle=page.getByRole('slider',{name:'Paint 1 angle',exact:true}),beforeRotation=read();
   await angleHandle.scrollIntoViewIfNeeded();let angleBox=await angleHandle.boundingBox(),anglePreview=await page.getByLabel('Paint 1 preview',{exact:true}).boundingBox();
   await page.mouse.move(Math.round(angleBox.x+angleBox.width/2),Math.round(angleBox.y+angleBox.height/2));
   await page.mouse.down();
   await page.keyboard.down('Shift');
   await page.mouse.move(anglePreview.x+anglePreview.width/2+30,anglePreview.y+anglePreview.height/2,{steps:5});assert.equal(await angleHandle.getAttribute('aria-valuenow'),'90');assert.equal(read(),beforeRotation);
   await page.keyboard.press('Escape');
   await page.mouse.up();
   await page.keyboard.up('Shift');assert.equal(read(),beforeRotation);assert.equal(await app.locator('h1').getAttribute('style'),null);await open(1);angleBox=await angleHandle.boundingBox();
   await page.mouse.move(Math.round(angleBox.x+angleBox.width/2),Math.round(angleBox.y+angleBox.height/2));
   await page.mouse.down();
   await page.keyboard.down('Shift');
   await page.mouse.move(anglePreview.x+anglePreview.width/2,anglePreview.y+anglePreview.height/2+30,{steps:5});
   await page.mouse.up();
   await page.keyboard.up('Shift');
   await checkpoint();assert.equal(await angleHandle.getAttribute('aria-valuenow'),'180');
   await wait(async()=>await angleHandle.evaluate(el=>el===document.activeElement));
   await page.keyboard.press('ArrowRight');
   await checkpoint();assert.equal(await angleHandle.getAttribute('aria-valuenow'),'181');for(let i=0;i<2;i++){states.pop();
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===states.at(-1));
   await settled();}assert.equal(read(),beforeRotation);await open(1);
   const draftColor=page.getByLabel('Paint 1 stop 1 color',{exact:true}),draftBefore=read(),initialColor=await draftColor.inputValue();const swatch=draftColor.locator('xpath=..').locator('.gradient-stop-swatch');assert.equal(await swatch.isVisible(),true);const initialSwatch=await swatch.evaluate(el=>el.style.backgroundImage);
   await draftColor.fill('not-a-color');
   await draftColor.press('Enter');assert.ok(await draftColor.evaluate(el=>el.validationMessage));assert.equal(read(),draftBefore);
   await draftColor.press('Escape');assert.equal(await draftColor.inputValue(),initialColor);assert.equal(await draftColor.evaluate(el=>el.validationMessage),'');
   await draftColor.fill('#123456');assert.ok((await swatch.evaluate(el=>el.style.backgroundImage)).includes('rgb(18, 52, 86)'));assert.equal(read(),draftBefore);
   await draftColor.press('Escape');
   await settled();assert.equal(await swatch.evaluate(el=>el.style.backgroundImage),initialSwatch);assert.equal(read(),draftBefore);const draftPosition=page.getByLabel('Paint 1 stop 1 Position (%)',{exact:true}),initialPosition=await draftPosition.inputValue();
   await draftPosition.fill('17');
   await draftPosition.press('Escape');
   await settled();assert.equal(await draftPosition.inputValue(),initialPosition);assert.equal(read(),draftBefore);   await page.getByLabel('Paint 1 stop 1 color',{exact:true}).fill('color(display-p3 1 .2 .1 / .4)');
   await page.getByLabel('Paint 1 stop 1 color',{exact:true}).press('Enter');
   await checkpoint();
   await page.getByRole('button',{name:'Add paint 1 stop',exact:true}).click();
   await checkpoint();
   await page.getByLabel('Paint 1 stop 2 Position (%)',{exact:true}).fill('35');
   await page.getByLabel('Paint 1 stop 2 Position (%)',{exact:true}).press('Enter');
   await checkpoint();
   await add();
   await checkpoint();
   await action('Move paint 1 down',1);activePaint=2;
   await checkpoint();
   await page.getByLabel('Paint 2 type',{exact:true}).selectOption('radial');
   await checkpoint();
   await page.getByLabel('Paint 2 Center X (%)',{exact:true}).fill('25');
   await page.getByLabel('Paint 2 Center X (%)',{exact:true}).press('Tab');
   await checkpoint();
   await page.getByLabel('Paint 2 Size',{exact:true}).selectOption('closest-side');
   await checkpoint();
   await page.getByLabel('Paint 2 Size',{exact:true}).selectOption('custom');
   await checkpoint();
   await page.getByLabel('Paint 2 Radius X',{exact:true}).fill('35%');
   await page.getByLabel('Paint 2 Radius X',{exact:true}).press('Tab');
   await checkpoint();
   await wait(async()=>await app.locator('h1').evaluate(el=>getComputedStyle(el).backgroundImage.includes('35% 50% at 25% 50%')));if(process.env.RT_E2E_RADIAL_SCREENSHOT){await page.getByLabel('Paint 2 Size',{exact:true}).scrollIntoViewIfNeeded();
   await page.screenshot({path:process.env.RT_E2E_RADIAL_SCREENSHOT});}const center=page.getByRole('button',{name:'Paint 2 center',exact:true}),beforeCenter=read();
   await center.scrollIntoViewIfNeeded();const centerBox=await center.boundingBox(),previewBox=await page.getByLabel('Paint 2 preview',{exact:true}).boundingBox();
   await page.mouse.move(Math.round(centerBox.x+centerBox.width/2),Math.round(centerBox.y+centerBox.height/2));
   await page.mouse.down();
   await page.mouse.move(Math.round(centerBox.x+centerBox.width/2)+Math.round(previewBox.width*.1),Math.round(centerBox.y+centerBox.height/2)+Math.round(previewBox.height*.1),{steps:5});assert.equal(read(),beforeCenter);assert.equal(await center.getAttribute('data-x'),'35');assert.equal(await center.getAttribute('data-y'),'60');
   await page.keyboard.press('Escape');
   await page.mouse.up();assert.equal(read(),beforeCenter);assert.equal(await app.locator('h1').getAttribute('style'),null);await open(2);
   await center.press('ArrowRight');
   await checkpoint();assert.equal(await center.getAttribute('data-x'),'26');
   await wait(async()=>await center.evaluate(el=>el===document.activeElement));
   await page.keyboard.press('Shift+ArrowDown');
   await checkpoint();assert.equal(await center.getAttribute('data-y'),'60');for(let i=0;i<2;i++){states.pop();
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===states.at(-1));
   await settled();}assert.equal(read(),beforeCenter);await open(2);
   await center.scrollIntoViewIfNeeded();const commitBox=await center.boundingBox();
   await page.mouse.move(Math.round(commitBox.x+commitBox.width/2),Math.round(commitBox.y+commitBox.height/2));
   await page.mouse.down();
   await page.mouse.move(Math.round(commitBox.x+commitBox.width/2)+Math.round(previewBox.width*.1),Math.round(commitBox.y+commitBox.height/2)+Math.round(previewBox.height*.1),{steps:5});assert.equal(read(),beforeCenter);
   await page.mouse.up();
   await checkpoint();assert.equal(await center.getAttribute('data-x'),'35');assert.equal(await center.getAttribute('data-y'),'60');states.pop();
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===beforeCenter);
   await settled();
   await action('Move paint 2 up',2);activePaint=2;
   await checkpoint();
   await wait(async()=>await app.locator('h1').evaluate(el=>{const value=getComputedStyle(el).backgroundImage;return value.startsWith('radial-gradient(')&&value.includes('linear-gradient(45deg')&&value.includes('color(display-p3');}));const beforeDrag=read();let handle=page.getByRole('slider',{name:'Paint 2 stop 2 handle',exact:true});
   await handle.scrollIntoViewIfNeeded();let railBox=await page.getByRole('group',{name:'Paint 2 stop positions',exact:true}).boundingBox(),handleBox=await handle.boundingBox();
   await page.mouse.move(handleBox.x+handleBox.width/2,handleBox.y+handleBox.height/2);
   await page.mouse.down();
   await page.mouse.move(railBox.x+railBox.width*.6,handleBox.y+handleBox.height/2,{steps:8});
   await wait(async()=>await handle.getAttribute('aria-valuenow')==='60');assert.equal(read(),beforeDrag);
   await page.mouse.up();
   await checkpoint();const dragged=read(),paintAfterDrag=await app.locator('h1').evaluate(el=>getComputedStyle(el).backgroundImage);handle=page.getByRole('slider',{name:'Paint 2 stop 2 handle',exact:true});
   await handle.scrollIntoViewIfNeeded();railBox=await page.getByRole('group',{name:'Paint 2 stop positions',exact:true}).boundingBox();handleBox=await handle.boundingBox();
   await page.mouse.move(handleBox.x+handleBox.width/2,handleBox.y+handleBox.height/2);
   await page.mouse.down();
   await page.mouse.move(railBox.x+railBox.width*.2,handleBox.y+handleBox.height/2,{steps:8});
   await page.keyboard.press('Escape');
   await page.mouse.up();assert.equal(read(),dragged);assert.equal(await app.locator('h1').getAttribute('style'),null);
   await wait(async()=>await app.locator('h1').evaluate(el=>getComputedStyle(el).backgroundImage)===paintAfterDrag);
   await open(2);await handle.press('ArrowRight');
   await checkpoint();handle=page.getByRole('slider',{name:'Paint 2 stop 2 handle',exact:true});assert.equal(await handle.getAttribute('aria-valuenow'),'61');
   await wait(async()=>await handle.evaluate(el=>el===document.activeElement));
   await page.keyboard.press('Shift+ArrowLeft');
   await checkpoint();assert.equal(await handle.getAttribute('aria-valuenow'),'51');
   await wait(async()=>await handle.evaluate(el=>el===document.activeElement));
   await open(1);
   await page.getByLabel('Paint 1 type',{exact:true}).selectOption('conic');
   await checkpoint();
   await page.getByLabel('Paint 1 Angle (deg)',{exact:true}).fill('90');
   await page.getByLabel('Paint 1 Angle (deg)',{exact:true}).press('Tab');
   await checkpoint();
   await page.getByLabel('Paint 1 Center Y (%)',{exact:true}).fill('60');
   await page.getByLabel('Paint 1 Center Y (%)',{exact:true}).press('Tab');
   await checkpoint();
   await wait(async()=>await app.locator('h1').evaluate(el=>{const value=getComputedStyle(el).backgroundImage;return value.startsWith('conic-gradient(from 90deg at 25% 60%')&&value.includes('linear-gradient(45deg');}));
   assert.equal(await page.getByLabel('Paint 1 Repeat',{exact:true}).isVisible(),false);
   await page.getByLabel('Paint 1 options',{exact:true}).click();   await page.getByLabel('Paint 1 Repeat',{exact:true}).check();
   await checkpoint();
   await wait(async()=>await app.locator('h1').evaluate(el=>getComputedStyle(el).backgroundImage.startsWith('repeating-conic-gradient(')));
   await page.getByLabel('Paint 1 stop 2 Position (%)',{exact:true}).fill('25');
   await page.getByLabel('Paint 1 stop 2 Position (%)',{exact:true}).press('Tab');
   await checkpoint();
   await wait(async()=>await page.evaluate(()=>{const fill=RetouchHTMLCSSValues.parseGradients(getComputedStyle(document.querySelector('#app').contentDocument.querySelector('h1')).backgroundImage)[0];return fill.repeat&&fill.stops.at(-1).position===25;}));
   await page.getByLabel('Paint 1 Color blending',{exact:true}).selectOption('oklch');
   await checkpoint();assert.equal(await page.getByLabel('Paint 1 Hue direction',{exact:true}).isVisible(),true,'gradient options remain expanded after source refresh');
   await page.getByLabel('Paint 1 Hue direction',{exact:true}).selectOption('longer');
   await checkpoint();
   await wait(async()=>await app.locator('h1').evaluate(el=>getComputedStyle(el).backgroundImage.includes('in oklch longer hue')));
   await page.getByRole('slider',{name:'Paint 1 angle',exact:true}).press('Shift+ArrowRight');
   await checkpoint();assert.equal(await page.getByRole('slider',{name:'Paint 1 angle',exact:true}).getAttribute('aria-valuenow'),'105');
   const duplicateBefore=read(),stack=()=>page.evaluate(()=>RetouchHTMLCSSValues.parseGradients(getComputedStyle(document.querySelector('#app').contentDocument.querySelector('h1')).backgroundImage)),stackBefore=await stack();
   await action('Duplicate paint 1',1);
   await wait(()=>read()!==duplicateBefore);
   await settled();assert.deepEqual(await stack(),[stackBefore[0],stackBefore[0],...stackBefore.slice(1)]);
   await focused('Paint 1 actions');
   const beforeFillRemoval=read();
   await page.getByRole('button',{name:'Remove paint 1',exact:true}).press('Enter');
   await wait(()=>read()!==beforeFillRemoval);
   await settled();
   await focused('Paint 1 actions');
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===beforeFillRemoval);
   await settled();
   const keyboardBefore=read();
   await menu(1);const actionsDialog=page.getByRole('dialog',{name:'Paint 1 actions',exact:true}),rect=await actionsDialog.boundingBox(),viewport=page.viewportSize();assert.ok(rect.width>0&&rect.x>=0&&rect.y>=0&&rect.x+rect.width<=viewport.width&&rect.y+rect.height<=viewport.height);
   await page.getByRole('button',{name:'Move paint 1 down',exact:true}).focus();
   await page.keyboard.press('ArrowDown');
   await focused('Duplicate paint 1');
   await page.keyboard.press('End');
   await focused('Duplicate paint 1');
   await page.keyboard.press('ArrowDown');
   await focused('Move paint 1 down');
   await page.keyboard.press('ArrowUp');
   await focused('Duplicate paint 1');
   await page.keyboard.press('Home');
   await focused('Move paint 1 down');assert.equal(read(),keyboardBefore);if(process.env.RT_E2E_ACTIONS_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_ACTIONS_SCREENSHOT});
   await page.keyboard.press('Escape');
   await focused('Paint 1 actions');
   await open(1);const beforeReverse=read(),reverseStack=await stack();
   await page.getByRole('button',{name:'Reverse paint 1 stops',exact:true}).press('Enter');
   await wait(()=>read()!==beforeReverse);
   await settled();assert.deepEqual(await stack(),[{...reverseStack[0],stops:reverseStack[0].stops.map(stop=>({...stop,position:100-stop.position})).reverse()},...reverseStack.slice(1)]);
   await focused('Reverse paint 1 stops');
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===beforeReverse);
   await settled();
   const duplicatedSource=read();
   await open(2);
   await page.getByLabel('Paint 2 stop 1 color',{exact:true}).fill('#ffee00');
   await page.getByLabel('Paint 2 stop 1 color',{exact:true}).press('Enter');
   await wait(()=>read()!==duplicatedSource);
   await settled();const changed=await stack();assert.deepEqual(changed[0],stackBefore[0]);assert.notDeepEqual(changed[1],stackBefore[0]);assert.deepEqual(changed.slice(2),stackBefore.slice(1));const beforeMove=read();
   await action('Move paint 1 down',1);
   await wait(()=>read()!==beforeMove);
   await settled();assert.deepEqual(await stack(),[changed[1],changed[0],...changed.slice(2)]);
   await focused('Paint 2 actions');
   for(const expected of [beforeMove,duplicatedSource,duplicateBefore]){await page.getByRole('button',{name:'Undo',exact:true}).click();
   await settled();
   await wait(()=>read()===expected);}await page.getByRole('button',{name:'Redo',exact:true}).click();
   await settled();assert.equal(read(),duplicatedSource);
   await page.getByRole('button',{name:'Undo',exact:true}).click();
   await settled();assert.equal(read(),duplicateBefore);
   const renderedBackground=await appearance();assert.equal(renderedBackground[0],baseline[0]);for(let i=1;i<4;i++)assert.ok(renderedBackground[i].split(',').every(value=>value.trim()===baseline[i]));if(process.env.RT_E2E_GRADIENT_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_GRADIENT_SCREENSHOT});
   await page.getByLabel('Screen size',{exact:true}).focus();
   await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');
   await settled();assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).backgroundImage),'none');
   await page.getByLabel('Screen size',{exact:true}).focus();
   await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');
   await settled();for(const expected of states.slice(0,-1).reverse()){await page.getByRole('button',{name:'Undo',exact:true}).click();
   await wait(()=>read()===expected);
   await settled();}console.log('GRADIENT FILLS PASS',kind,engine);return;
};
