'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const original=read(),group=page.getByRole('treeitem',{name:'div · Group',exact:true}),measure=()=>app.locator('h1,p').evaluateAll(nodes=>nodes.map(el=>{const r=el.getBoundingClientRect();return [r.x,r.y,r.width,r.height];}));
 for(const multiple of [false,true]){
  await group.click();if(multiple)await page.getByRole('treeitem',{name:'p · Named text',exact:true}).click({modifiers:['Meta']});await settled();
  for(const factor of [.5,1.5,2]){
   const before=await measure(),selected=before.slice(0,multiple?3:2),left=Math.min(...selected.map(r=>r[0])),top=Math.min(...selected.map(r=>r[1])),expected=before.map((r,i)=>i<2||multiple?[left+(r[0]-left)*factor,top+(r[1]-top)*factor,r[2]*factor,r[3]*factor]:r);
   const input=page.getByLabel('Scale selection (%)',{exact:true});await input.fill(String(factor*100));await input.press('Enter');await wait(()=>read()!==original);await settled();const matches=async()=>{const actual=await measure();return actual.every((r,i)=>r.every((n,j)=>Math.abs(n-expected[i][j])<.1));};await wait(matches);assert.equal(await page.getByRole('treeitem',{selected:true}).count(),multiple?2:1);assert.equal(await app.locator('h1,p').evaluateAll(nodes=>nodes.some(el=>el.style.getPropertyValue('scale'))),false,'measurement scale styles restored');const changed=read();
   await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();await wait(async()=>{const actual=await measure();return actual.every((r,i)=>r.every((n,j)=>Math.abs(n-before[i][j])<.1));});await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===changed);await settled();await wait(matches);await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();
  }
  for(const cancel of [true,false]){
   const before=await measure(),selected=before.slice(0,multiple?3:2),left=Math.min(...selected.map(r=>r[0])),top=Math.min(...selected.map(r=>r[1])),input=page.getByLabel('Scale selection (%)',{exact:true}),label=input.locator('..').locator('span').first(),r=await label.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+15,r.y+r.height/2,{steps:3});await page.mouse.move(r.x+r.width/2+30,r.y+r.height/2,{steps:3});const factor=Number(await input.inputValue())/100,expected=before.map((r,i)=>i<2||multiple?[left+(r[0]-left)*factor,top+(r[1]-top)*factor,r[2]*factor,r[3]*factor]:r),matches=async expected=>{const actual=await measure();return actual.every((r,i)=>r.every((n,j)=>Math.abs(n-expected[i][j])<.1));};assert.equal(read(),original);await wait(()=>matches(expected));await page.screenshot({path:'/tmp/retouch-group-scale-preview-'+kind+'.png'});
   if(cancel){await page.keyboard.press('Escape');await page.mouse.up();assert.equal(read(),original);await wait(()=>matches(before));}else{await page.mouse.up();await wait(()=>read()!==original);await settled();await wait(()=>matches(expected));const changed=read();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();await wait(()=>matches(before));await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===changed);await settled();await wait(()=>matches(expected));await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();}
   assert.equal(await app.locator('h1,p').evaluateAll(nodes=>nodes.some(el=>el.style.scale||el.style.translate)),false,'preview properties restored');
  }
  if(multiple){const input=page.getByLabel('Scale selection (%)',{exact:true}),label=input.locator('..').locator('span').first(),r=await label.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+20,r.y+r.height/2,{steps:3});await wait(async()=>await app.locator('h1').evaluate(el=>!!el.style.scale));const foreign=await app.locator('h1').evaluate(el=>{el.style.setProperty('scale','3 2','important');el.style.color='rgb(1, 2, 3)';return el.style.scale;});await page.locator('[data-numeric-scrub-speed]').waitFor({state:'detached'});await page.mouse.up();assert.equal(read(),original);assert.equal(await app.locator('h1').evaluate(el=>el.style.scale),foreign);assert.equal(await app.locator('h1').evaluate(el=>el.style.color),'rgb(1, 2, 3)');await app.locator('h1').evaluate(el=>{el.style.removeProperty('scale');el.style.removeProperty('color');if(!el.getAttribute('style'))el.removeAttribute('style');});}
 }
 await group.click();await settled();await page.screenshot({path:'/tmp/retouch-group-scale-'+kind+'.png'});console.log(kind+': PASS proportional group scaling at 50/150/200 percent, single and mixed selections, preserved sibling layout, removed measurement styles and exact undo/redo');
};
