'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const original=read(),measure=()=>app.locator('h1,p').evaluateAll(nodes=>nodes.map(el=>{const r=el.getBoundingClientRect();return [r.x,r.y,r.width,r.height];})),styles=()=>app.locator('h1,p').evaluateAll(nodes=>nodes.map(el=>el.getAttribute('style'))),before=await measure(),inline=await styles();
 const focus=()=>app.locator('body').evaluate(el=>{el.tabIndex=-1;el.focus({preventScroll:true});});
 const preview=()=>wait(async()=>await app.locator('h1').evaluate(el=>!!el.style.getPropertyValue('translate')));
 await focus();await page.keyboard.down('ArrowRight');await preview();assert.equal(read(),original,'held nudge previews before one source transaction');await page.keyboard.down('ArrowRight');await page.keyboard.down('Shift');await page.keyboard.down('ArrowDown');await page.keyboard.up('ArrowRight');assert.equal(read(),original,'another arrow is still held');await page.keyboard.up('ArrowDown');await page.keyboard.up('Shift');await wait(()=>read()!==original);await settled();const saved=read();await wait(async()=>Math.abs((await measure())[0][0]-before[0][0]-2)<.1);const after=await measure();for(let i=0;i<after.length;i++)for(let j=0;j<4;j++)assert.ok(Math.abs(after[i][j]-before[i][j]-(i<2&&j<2?(j?10:2):0))<.1,'nudge geometry');assert.deepEqual(await styles(),inline,'preview styles restored');assert.equal(await page.getByRole('treeitem',{name:'div · Group',selected:true,exact:true}).count(),1);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===saved);await settled();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();
 await focus();await page.keyboard.down('ArrowLeft');await preview();await page.keyboard.press('Escape');await page.keyboard.up('ArrowLeft');await settled();assert.equal(read(),original);assert.deepEqual(await styles(),inline);const restored=await measure();for(let i=0;i<before.length;i++)for(let j=0;j<4;j++)assert.ok(Math.abs(restored[i][j]-before[i][j])<.1,'Escape restores geometry');
 await focus();await page.keyboard.down('ArrowRight');await preview();const external=await app.locator('h1').evaluate(el=>{el.style.color='rgb(1, 2, 3)';el.style.translate='77px 0px';return {translate:el.style.translate,color:el.style.color};});await wait(async()=>await page.evaluate(()=>!stopDrawing));await page.keyboard.up('ArrowRight');assert.equal(read(),original);assert.equal(await app.locator('h1').evaluate(el=>el.style.translate),external.translate);assert.equal(await app.locator('h1').evaluate(el=>el.style.color),external.color);await app.locator('h1,p').evaluateAll((nodes,values)=>nodes.forEach((el,i)=>values[i]===null?el.removeAttribute('style'):el.setAttribute('style',values[i])),inline);
 let release,active=0,entered=0;const held=new Promise(resolve=>release=resolve),handler=async route=>{entered++;active++;try{await held;await route.continue();}finally{active--;}};await page.route('**/rt/__api/resolve?*',handler);await focus();await page.keyboard.down('ArrowDown');await wait(()=>entered>=2);await page.keyboard.up('ArrowDown');assert.equal(read(),original);release();await wait(()=>active===0);await page.unroute('**/rt/__api/resolve?*',handler);await wait(()=>read()!==original);await settled();await wait(async()=>Math.abs((await measure())[0][1]-before[0][1]-1)<.1);await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();
 await page.getByLabel('Screen width',{exact:true}).focus();await page.keyboard.press('ArrowRight');await settled();assert.equal(read(),original,'input arrows are not canvas nudges');assert.deepEqual(await styles(),inline);
 console.log(kind+': PASS group arrow nudge, repeat/Shift and simultaneous held keys, live preview, one-step undo/redo, Escape, foreign style preservation, delayed release and input guard');
};
