'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const original=read();await page.getByRole('treeitem',{name:'p · Other text',exact:true}).click({modifiers:['Shift']});await settled();await app.locator('h1').click({button:'right'});await page.getByRole('menu',{name:'Canvas actions',exact:true}).locator('[data-action-id="layer-groupSelection"]').click();await wait(()=>read()!==original);await settled();const grouped=read(),group=page.getByRole('treeitem',{name:'div · Group',exact:true});
 await page.evaluate(()=>clearSelection());await app.locator('h1').click();await settled();assert.equal(await group.getAttribute('aria-selected'),'true');assert.equal(await app.locator('h1').getAttribute('contenteditable'),null);assert.equal(await app.locator('[data-rt-group]').getAttribute('contenteditable'),null);await wait(async()=>await page.locator('.box.sel').count()>0);
 await app.locator('h1').dblclick();await settled();await wait(async()=>await app.locator('h1').getAttribute('contenteditable')==='true');assert.equal(await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).getAttribute('aria-selected'),'true');await app.locator('h1').press('Escape');await settled();assert.equal(read(),grouped);
 await page.getByRole('treeitem',{name:'p · Other text',exact:true}).click();await settled();await app.locator('h1').click();await settled();await wait(async()=>await app.locator('h1').getAttribute('contenteditable')==='true');await app.locator('h1').press('Escape');await settled();assert.equal(read(),grouped);
 await page.getByRole('treeitem',{name:'p · Named text',exact:true}).click();await settled();await app.locator('h1').click();await settled();assert.equal(await group.getAttribute('aria-selected'),'true');assert.equal(await app.locator('h1').getAttribute('contenteditable'),null);assert.equal(read(),grouped);
 await app.locator('h1').click({button:'right'});const menu=page.getByRole('menu',{name:'Canvas actions',exact:true});assert.equal(await menu.locator('[data-action-id="layer-removeFrame"] .context-label').textContent(),'Ungroup');await menu.locator('[data-action-id="layer-removeFrame"]').click();await wait(()=>read()===original);await settled();console.log(kind+': PASS canvas selects the group, double-click enters child text, tree selection enters group, leaving restores group picking and right-click ungroups');
};
