'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');const fixture=process.env.RT_INSPECTOR_FIXTURE,engine=process.env.RT_E2E_BROWSER||'chromium';if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');
(async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-guides-')),file=path.join(root,'index.html'),source='<html><body style="height:2500px"><h1>Guides</h1><input value="initial">'+(process.env.RT_E2E_GUIDE_SVG?'<svg width="390" height="400" viewBox="0 0 390 400"><rect aria-label="Guide box" x="40" y="50" width="80" height="60" fill="red"/></svg>':'')+'</body></html>';fs.writeFileSync(file,source);const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/rt/__api/op'))writes.push(r.url());});const app=page.frameLocator('#app'),wait=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(50);}throw Error('Guides did not settle');},values=()=>page.evaluate(()=>RetouchGuides.values().map(({axis,value})=>({axis,value})));
 await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('h1').waitFor();await app.locator('input').evaluate(el=>{el.value='retained';window.guideIdentity={};window.originalGuideIdentity=window.guideIdentity;});const preset=page.getByLabel('Screen size',{exact:true});await preset.selectOption('390x844');await page.getByRole('button',{name:'Toggle rulers',exact:true}).click();
 const drag=async(axis,value,cancel=false)=>{const ruler=page.locator(axis==='x'?'.canvas-ruler-vertical':'.canvas-ruler-horizontal'),r=await ruler.boundingBox(),f=await page.locator('#app').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(axis==='x'?f.x+value:f.x+100,axis==='y'?f.y+value:f.y+100,{steps:8});if(cancel)await page.keyboard.press('Escape');await page.mouse.up();};
 await drag('x',120);assert.deepEqual(await values(),[{axis:'x',value:120}]);await drag('y',200,true);assert.deepEqual(await values(),[{axis:'x',value:120}]);await drag('y',200);assert.deepEqual(await values(),[{axis:'x',value:120},{axis:'y',value:200}]);
 if(process.env.RT_E2E_GUIDE_SVG){
  const target=app.locator('[aria-label="Guide box"]');await page.getByRole('treeitem',{name:'rect · Guide box',exact:true}).click();await wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true');const before=await target.evaluate(el=>{const r=el.getBoundingClientRect();return {right:r.right,bottom:r.bottom};});
  await require('./shape-tools.cjs').run(page,'Move vector on canvas');const button=page.getByLabel('Move SVG vector on canvas',{exact:true}).getByRole('button',{name:'Move vector',exact:true}),b=await button.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+120-before.right-3,b.y+b.height/2+200-before.bottom-3,{steps:6});assert.equal(fs.readFileSync(file,'utf8'),source);await page.mouse.up();await wait(()=>fs.readFileSync(file,'utf8')!==source);await wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true');const after=await target.evaluate(el=>{const r=el.getBoundingClientRect();return {right:r.right,bottom:r.bottom};});assert.ok(Math.abs(after.right-120)<.1&&Math.abs(after.bottom-200)<.1,'SVG edges snap to document guides');await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>fs.readFileSync(file,'utf8')===source);await wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true');writes.length=0;
 }
 const horizontal=page.getByRole('button',{name:'Horizontal guide 200 px',exact:true});await horizontal.focus();await horizontal.press('Shift+ArrowDown');assert.deepEqual((await values())[1],{axis:'y',value:210});await page.keyboard.press('Control+z');assert.deepEqual((await values())[1],{axis:'y',value:200});await page.keyboard.press('Delete');assert.equal((await values()).length,1);await page.keyboard.press('Control+z');assert.equal((await values()).length,2);await page.keyboard.press('Control+Shift+z');assert.equal((await values()).length,1);await page.keyboard.press('Control+z');
 await page.getByRole('button',{name:'Horizontal guide 200 px',exact:true}).focus();await page.keyboard.down('ArrowDown');await page.keyboard.down('ArrowDown');await page.keyboard.down('ArrowDown');await page.keyboard.up('ArrowDown');assert.equal((await values())[1].value,203);await page.keyboard.press('Control+z');assert.equal((await values())[1].value,200,'Held keys undo as one edit');
 const vertical=page.getByRole('button',{name:'Vertical guide 120 px',exact:true}),v=await vertical.boundingBox();await page.mouse.move(v.x+4,v.y+80);await page.mouse.down();await page.mouse.move(100,80,{steps:8});await page.mouse.up();assert.deepEqual(await values(),[{axis:'y',value:200}]);await page.getByRole('button',{name:'Horizontal guide 200 px',exact:true}).focus();await page.keyboard.press('Control+z');assert.equal((await values()).length,2);
 await preset.selectOption('768x1024');await wait(async()=>(await values()).length===0);await preset.selectOption('390x844');await wait(async()=>(await values()).length===2);await page.getByLabel('Canvas zoom (%)',{exact:true}).fill('150');await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Tab');await app.locator('body').evaluate(()=>window.scrollTo(0,100));
 await wait(()=>page.evaluate(()=>{const f=document.getElementById('app'),r=f.getBoundingClientRect(),scale=r.width/f.clientWidth;return [...document.querySelectorAll('.canvas-guide')].every(node=>{const axis=node.dataset.guideAxis,value=Number(node.dataset.guideValue),b=node.getBoundingClientRect(),expected=(axis==='x'?r.left:r.top)+(value-(axis==='x'?f.contentWindow.scrollX:f.contentWindow.scrollY))*scale;return Math.abs((axis==='x'?b.left:b.top)+4-expected)<1;});}));
 assert.deepEqual(await app.locator('input').evaluate(el=>[el.value,!!window.guideIdentity&&window.guideIdentity===window.originalGuideIdentity]),['retained',true]);assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(writes,[]);if(process.env.RT_E2E_GUIDES_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_GUIDES_SCREENSHOT});await page.reload();await app.locator('h1').waitFor();await wait(async()=>(await values()).length===2);assert.deepEqual(errors,[]);console.log('GUIDES CREATE/CANCEL/KEYBOARD/DELETE/UNDO, WIDTH SCOPE, ZOOM/SCROLL AND PERSISTENCE PASS',engine);
 }finally{if(browser)await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
