'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
exports.run=async({page,app,file,wait,settled,kind})=>{
 const target=app.locator('h1'),read=()=>fs.readFileSync(file,'utf8'),original=read(),mode=page.getByLabel('Paint 1 image mode',{exact:true}),value=property=>target.evaluate((el,p)=>getComputedStyle(el).getPropertyValue(p),property);
 assert.equal(await page.locator('[data-section=fill] .paint-order-row').count(),1);assert.equal(await page.getByLabel('Image fill mode',{exact:true}).isVisible(),false);
 const open=async()=>{const button=page.getByRole('button',{name:'Edit image paint 1',exact:true});if(await button.getAttribute('aria-expanded')!=='true')await button.click();};
 const size=async choice=>{await page.getByLabel('Screen size',{exact:true}).selectOption(choice);await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===Number(choice.split('x')[0]));await settled();await open();};
 await app.locator('input').evaluate(el=>{el.value='retained';window.fillOriginalIdentity=window.fillIdentity={};});
 if(kind==='react'){const counter=app.getByRole('button',{name:'Clicks 0',exact:true});await wait(()=>counter.evaluate(el=>Object.keys(el).some(key=>key.startsWith('__reactProps$')&&typeof el[key]?.onClick==='function')));await page.locator('#modeBtn').click();await counter.click();await app.getByRole('button',{name:'Clicks 1',exact:true}).waitFor();await page.locator('#modeBtn').click();}
 if(process.env.RT_E2E_IMAGE_FILL_AUTO_HEIGHT){await open();const scale=page.getByLabel('Paint 1 tile scale (%)',{exact:true});await wait(()=>scale.isEnabled());assert.equal(await mode.inputValue(),'tile');assert.equal(await scale.inputValue(),'50','height-only imported tiles display their proportional scale');assert.equal(read(),original,'reading imported sizing leaves source unchanged');}
 await size('390x844');await mode.selectOption('fit');await settled();await wait(async()=>await value('background-size')==='contain');const fitSource=read();assert.notEqual(fitSource,original);
 await size('768x1024');await page.getByLabel('Style screen scope').selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await open();await mode.selectOption('tile');await settled();await wait(async()=>await value('background-size')==='40px 20px'&&await value('background-repeat')==='repeat');const tileSource=read();
 const input=page.getByLabel('Paint 1 tile scale (%)',{exact:true});await input.fill('50');await input.press('Tab');await settled();await wait(async()=>await value('background-size')==='20px 10px');const halfSource=read();assert.notEqual(halfSource,tileSource);
 const pixels=async()=>{const sharp=require(path.join(process.env.RT_INSPECTOR_FIXTURE,'node_modules/sharp')),result=await sharp(await target.screenshot()).removeAlpha().raw().toBuffer({resolveWithObject:true});const box=await target.boundingBox(),ratio=result.info.width/box.width;for(const [x,color]of [[5,[255,0,0]],[15,[0,0,255]],[25,[255,0,0]],[35,[0,0,255]]]){const index=(Math.round(100*ratio)*result.info.width+Math.round(x*ratio))*result.info.channels;assert.deepEqual([...result.data.subarray(index,index+3)],color,'tile pixel '+x);}};
 await pixels();await size('1440x900');assert.equal(await value('background-size'),'20px 10px');await pixels();await size('390x844');await wait(async()=>await value('background-size')==='contain'&&await value('background-repeat')==='no-repeat');await size('768x1024');await wait(async()=>await value('background-size')==='20px 10px');await wait(async()=>await input.inputValue()==='50');
 if(process.env.RT_E2E_IMAGE_FILL_SCREENSHOT){await mode.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.RT_E2E_IMAGE_FILL_SCREENSHOT});}
 if(kind==='html'){await page.getByText('More fill controls',{exact:true}).click();await page.getByRole('button',{name:'Reset image fill framing',exact:true}).click();await settled();await wait(async()=>await value('background-size')==='contain');await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===halfSource);}
 for(const expected of [tileSource,fitSource,original]){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===expected);}
 assert.deepEqual(await app.locator('input').evaluate(el=>[el.value,window.fillIdentity===window.fillOriginalIdentity]),['retained',true]);if(kind==='react')assert.equal(await app.getByRole('button',{name:'Clicks 1',exact:true}).count(),1);
 console.log(kind+': PASS image Fill/Fit/Tile, original-pixel scale across screen resizing, phone inheritance, atomic mode undo, exact source restoration and retained runtime state');
};
