'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE for Next.js, Tailwind and Playwright');
const writingMode=process.env.RT_E2E_WRITING_MODE||'horizontal-tb',textDirection=process.env.RT_E2E_DIRECTION||'ltr';
if(!['horizontal-tb','vertical-rl','vertical-lr','sideways-rl','sideways-lr'].includes(writingMode)||!['ltr','rtl'].includes(textDirection))throw Error('Unsupported writing direction');
const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-layout-mode-')),file=path.join(root,'app/page.jsx');fs.mkdirSync(path.dirname(file));fs.symlinkSync(path.join(fixture,'node_modules'),path.join(root,'node_modules'),'dir');
 fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({private:true,dependencies:{next:'16.2.5',react:'19.2.0','react-dom':'19.2.0',tailwindcss:'4.1.13','@tailwindcss/postcss':'4.1.13'}}));
 fs.writeFileSync(path.join(root,'postcss.config.mjs'),"export default {plugins:{'@tailwindcss/postcss':{}}}");fs.writeFileSync(path.join(root,'app/style.css'),'@import "tailwindcss";');
 fs.writeFileSync(path.join(root,'app/layout.jsx'),"import './style.css';export default function Layout({children}){return <html><body>{children}</body></html>}");
 const original='"use client";export default function Page(){return <main><section id="layout" className="!block sm:!rounded-[20px] sm:!overflow-x-hidden sm:!overflow-y-auto sm:!grid sm:![flex-flow:column_wrap] sm:!place-items-end sm:!place-content-end sm:![grid-template-columns:40px_40px] sm:![grid-template-rows:40px_40px] md:[display:grid] md:grid-cols-2 w-[400px] h-[300px] gap-[10px]"><div className="w-[40px] h-[40px]">One</div><div className="w-[40px] h-[40px]">Two</div></section><p id="sample" className="sm:!border-[2px] sm:!border-dashed text-[20px] leading-[28px]">Design with intention</p></main>}';fs.writeFileSync(file,original.replace('text-[20px]',process.env.RT_E2E_NUMERIC_SCRUB?'text-[20px] shadow-[2px_4px_8px_1px_rgba(0,0,0,0.3),inset_1px_2px_3px_0px_rgba(255,0,0,0.2)] [filter:brightness(.8)_blur(2px)] [backdrop-filter:contrast(1.2)_blur(3px)] [background-image:linear-gradient(90deg,red_0%,green_40%,blue_100%),radial-gradient(ellipse_at_50%_50%,white_0%,black_100%)]':'text-[20px]').replace('className="!block','className="[writing-mode:'+writingMode+'] [direction:'+textDirection+'] !block'));const read=()=>fs.readFileSync(file,'utf8');
 let logs='',url,browser,exited=false;const child=spawn(process.execPath,[path.resolve(__dirname,'../../bin/retouch.cjs'),'--',process.execPath,path.join(fixture,'node_modules/next/dist/bin/next'),'dev','--webpack','-p','0'],{cwd:root,env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']}),stopped=new Promise(resolve=>child.once('exit',()=>{exited=true;resolve();}));for(const stream of [child.stdout,child.stderr])stream.on('data',chunk=>{logs+=chunk;url=logs.match(/http:\/\/localhost:(\d+)/)?.[0];});
 const wait=async fn=>{for(let i=0;i<300;i++){try{if(await fn())return;}catch(error){if(!/ECONNREFUSED|fetch failed|Execution context was destroyed/.test(error.message))throw error;}if(exited)throw Error(logs);await new Promise(resolve=>setTimeout(resolve,100));}throw Error('Timed out: '+logs.slice(-3000));};
 try{
  await wait(()=>url);await wait(async()=>(await fetch(url+'/rt/__api/health')).ok);browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1500,height:1100}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(url+'/rt',{timeout:90000});const parent=page.frameLocator('#app').locator('#layout');await parent.waitFor({timeout:90000});const settled=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy);
  await page.getByLabel('Screen size',{exact:true}).focus();await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await page.getByRole('treeitem',{name:'section · layout',exact:true}).click();const mode=page.getByLabel('Arrange children',{exact:true});await mode.waitFor();await settled();await page.getByLabel('Style screen scope',{exact:true}).selectOption('md:');await settled();
  assert.equal(await page.getByLabel('Style screen scope',{exact:true}).locator('option:checked').textContent(),'768 px and larger · md');
  const rangeStatus=page.getByRole('status',{name:'Edit range status',exact:true});assert.equal(await rangeStatus.getAttribute('data-match'),'true');
  const beforePreview=read();await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();
  await wait(async()=>await rangeStatus.getAttribute('data-match')==='false');assert.equal(await rangeStatus.isVisible(),true);
  const previewBreakpoint=page.getByRole('button',{name:'Preview this breakpoint',exact:true});assert.equal(await previewBreakpoint.isVisible(),true);
  await previewBreakpoint.click();await settled();await wait(async()=>await rangeStatus.getAttribute('data-match')==='true');assert.equal(read(),beforePreview);
  await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();
  await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>[...document.fonts].some(font=>font.family==='Inter'&&font.status==='loaded')),true);
  const originalSource=read();
  if(process.env.RT_E2E_NUMERIC_SCRUB){
   let field=page.getByLabel('Corner radius (px)',{exact:true});
   const scrub=async(delta,modifier,cancel=false,during=null)=>{const groups=field.locator('xpath=ancestor::details');for(let i=0;i<await groups.count();i++){const group=groups.nth(i);if(!await group.evaluate(el=>el.open))await group.locator(':scope > summary').click();}await wait(async()=>{try{await field.scrollIntoViewIfNeeded();return true;}catch(error){if(/not attached/.test(error.message))return false;throw error;}});const label=field.locator('xpath=..').locator('[data-numeric-scrub]'),box=await label.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);if(modifier)await page.keyboard.down(modifier);await page.mouse.down();await page.mouse.move(box.x+box.width/2+delta,box.y+box.height/2,{steps:3});assert.equal(read(),originalSource,'drag does not write source');if(await field.getAttribute('aria-label')==='Corner radius (px)')assert.equal(await parent.evaluate(el=>parseFloat(getComputedStyle(el).borderTopLeftRadius)),Number(await field.inputValue()));if(await field.getAttribute('aria-label')==='Opacity (%)')assert.equal(await parent.evaluate(el=>Number(getComputedStyle(el).opacity)),await rangeStatus.getAttribute('data-match')==='false'?1:Number(await field.inputValue())/100);if(during)await during();if(cancel)await page.keyboard.press(typeof cancel==='string'?cancel:'Escape');await page.mouse.up();if(modifier)await page.keyboard.up(modifier);};
   for(const [delta,modifier,expected] of [[12,null,32],[3,'Shift',50],[15,'Alt',21.5],[-100,null,0]]){
    assert.equal(Number(await field.inputValue()),20);await scrub(delta,modifier);await wait(()=>read()!==originalSource);await settled();await wait(async()=>parent.evaluate((el,n)=>parseFloat(getComputedStyle(el).borderTopLeftRadius)===n,expected));assert.match(read(),/md:!rounded-/);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource,'one undo restores entire drag');
   }
   const radiusStyle=await parent.getAttribute('style');await scrub(10,null,true,()=>parent.evaluate(el=>el.style.setProperty('border-top-left-radius','42px','important')));assert.deepEqual(await parent.evaluate(el=>['borderTopLeftRadius','borderTopRightRadius','borderBottomRightRadius','borderBottomLeftRadius'].map(p=>getComputedStyle(el)[p])),['42px','20px','20px','20px']);await parent.evaluate((el,style)=>{if(style===null)el.removeAttribute('style');else el.setAttribute('style',style);},radiusStyle);
   await page.getByText('Individual corners',{exact:true}).click();field=page.getByLabel('Top right radius (px)',{exact:true});await scrub(5,null,true,async()=>assert.deepEqual(await parent.evaluate(el=>[getComputedStyle(el).borderTopLeftRadius,getComputedStyle(el).borderTopRightRadius]),['20px','25px']));assert.equal(await parent.getAttribute('style'),radiusStyle);field=page.getByLabel('Corner radius (px)',{exact:true});
   for(const cancellation of [true,'Tab']){await scrub(15,null,cancellation);assert.equal(await field.inputValue(),'20');assert.equal(read(),originalSource);}await scrub(0,null);assert.equal(read(),originalSource);await field.fill('27');await field.press('Tab');await wait(()=>read()!==originalSource);await settled();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);field=page.getByLabel('Opacity (%)',{exact:true});const initialStyle=await parent.getAttribute('style');
   await scrub(-25,null,true);assert.equal(await parent.evaluate(el=>getComputedStyle(el).opacity),'1');assert.equal(await parent.getAttribute('style'),initialStyle);assert.equal(read(),originalSource);
   await scrub(-25,null,true,()=>parent.evaluate(el=>el.style.setProperty('--runtime-preview-check','retained')));assert.equal(await parent.evaluate(el=>el.style.getPropertyValue('--runtime-preview-check')),'retained');assert.equal(await parent.evaluate(el=>el.style.getPropertyValue('opacity')),'');await parent.evaluate((el,style)=>{if(style===null)el.removeAttribute('style');else el.setAttribute('style',style);},initialStyle);
   await page.getByLabel('Screen size',{exact:true}).focus();await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();await wait(async()=>await rangeStatus.getAttribute('data-match')==='false');await scrub(-25,null,true);assert.equal(read(),originalSource);assert.equal(await parent.getAttribute('style'),initialStyle);await page.getByLabel('Screen size',{exact:true}).focus();await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();await wait(async()=>await rangeStatus.getAttribute('data-match')==='true');
   await scrub(-25,null,false,async()=>{await field.evaluate(el=>el.parentElement.remove());await wait(async()=>parent.evaluate(el=>getComputedStyle(el).opacity==='1'));});assert.equal(read(),originalSource);assert.equal(await parent.getAttribute('style'),initialStyle);await page.evaluate(()=>renderPanel());await settled();
   await scrub(-25,null);await wait(()=>read()!==originalSource);await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).opacity==='0.75'));assert.equal(await parent.getAttribute('style'),initialStyle);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);await wait(async()=>parent.evaluate(el=>getComputedStyle(el).opacity==='1'));
   await page.getByRole('treeitem',{name:'p · sample',exact:true}).click();await settled();const text=page.frameLocator('#app').locator('#sample'),textStyle=await text.getAttribute('style');
   for(const [label,property,delta,factor=1] of [['Font size (px)','font-size',12],['Line height (px)','line-height',7],['Letter spacing (px)','letter-spacing',2],['Font weight (1–1000)','font-weight',100],['Line height (%)','line-height',10,0.2],['Letter spacing (%)','letter-spacing',10,0.2]]){
    field=page.getByLabel(label,{exact:true});const before=await text.evaluate((el,p)=>getComputedStyle(el).getPropertyValue(p),property),initial=Number(await field.inputValue());
    const preview=async()=>assert.equal(await text.evaluate((el,p)=>parseFloat(getComputedStyle(el).getPropertyValue(p)),property),(initial+delta)*factor,JSON.stringify({label,input:await field.inputValue(),style:await text.getAttribute('style'),preview:await field.evaluate(el=>typeof el.retouchNumericPreview)}));
    await scrub(delta,null,true,preview);assert.equal(await text.evaluate((el,p)=>getComputedStyle(el).getPropertyValue(p),property),before);assert.equal(await text.getAttribute('style'),textStyle);assert.equal(read(),originalSource);
    await scrub(delta,null,false,preview);await wait(()=>read()!==originalSource);await settled();await wait(async()=>await text.evaluate((el,p)=>parseFloat(getComputedStyle(el).getPropertyValue(p)),property)===(initial+delta)*factor);assert.equal(await text.getAttribute('style'),textStyle);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
   }
   const shadowState=async()=>page.evaluate(value=>RetouchHTMLCSSValues.parseShadows(value),await text.evaluate(el=>getComputedStyle(el).boxShadow));
   const shadowOriginal=await shadowState(),shadowIndex=shadowOriginal.findIndex(item=>item.x===2&&item.y===4&&item.blur===8&&!item.inset);assert.ok(shadowOriginal.length>=2);assert.ok(shadowIndex>=0);assert.ok(shadowOriginal.some(item=>item.inset&&item.x===1&&item.y===2&&item.blur===3));
   for(const [label,key,delta] of [['X','x',5],['Y','y',-3],['Blur','blur',4],['Spread','spread',-2]]){
    field=page.getByLabel('Shadow '+(shadowIndex+1)+' '+label+' (px)',{exact:true});const expected=shadowOriginal.map((item,i)=>i===shadowIndex?{...item,[key]:item[key]+delta}:item),preview=async()=>assert.deepEqual(await shadowState(),expected);
    await scrub(delta,null,true,preview);assert.deepEqual(await shadowState(),shadowOriginal);assert.equal(await text.getAttribute('style'),textStyle);
    await scrub(delta,null,false,preview);await wait(()=>read()!==originalSource);await settled();await wait(async()=>JSON.stringify(await shadowState())===JSON.stringify(expected));assert.equal(await text.getAttribute('style'),textStyle);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
   }
   for(const [label,property] of [['Layer blur (px)','filter'],['Backdrop blur (px)','backdrop-filter']]){
    field=page.getByLabel(label,{exact:true});const originalFilter=await text.evaluate((el,p)=>getComputedStyle(el).getPropertyValue(p),property),expected=await page.evaluate(value=>RetouchHTMLCSSValues.withBlur(value,7),originalFilter),delta=7-Number(await field.inputValue()),get=()=>text.evaluate((el,p)=>getComputedStyle(el).getPropertyValue(p),property),preview=async()=>assert.equal(await get(),expected);
    await scrub(delta,null,true,preview);assert.equal(await get(),originalFilter);assert.equal(await text.getAttribute('style'),textStyle);await scrub(delta,null,false,preview);await wait(()=>read()!==originalSource);await settled();await wait(async()=>await get()===expected);assert.equal(await text.getAttribute('style'),textStyle);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
   }
   const gradientState=async()=>page.evaluate(value=>RetouchHTMLCSSValues.parseGradients(value),await text.evaluate(el=>getComputedStyle(el).backgroundImage)),originalGradients=await gradientState();assert.equal(originalGradients.length,2);
   for(const [label,index,key,delta] of [['Gradient 1 Angle (deg)',0,'angle',25],['Gradient 1 stop 1 Position (%)',0,'stop',60],['Gradient 2 Center X (%)',1,'x',10],['Gradient 2 Center Y (%)',1,'y',-10]]){
    field=page.getByLabel(label,{exact:true});const changed=structuredClone(originalGradients);if(key==='stop'){changed[index].stops[0].position+=delta;changed[index].stops.sort((a,b)=>a.position-b.position);}else changed[index][key]+=delta;
    const preview=async()=>{assert.deepEqual(await gradientState(),changed);const miniature=page.getByLabel('Gradient '+(index+1)+' preview',{exact:true});assert.deepEqual(await page.evaluate(value=>RetouchHTMLCSSValues.parseGradients(value),await miniature.evaluate(el=>el.style.backgroundImage)),[changed[index]]);if(key==='stop'){assert.equal(await page.getByRole('slider',{name:'Gradient 1 stop 1 handle',exact:true}).getAttribute('aria-valuenow'),'60');if(process.env.RT_E2E_GRADIENT_NUMERIC_SCREENSHOT)await field.locator('xpath=ancestor::fieldset[contains(@class,"gradient-controls")]').screenshot({path:process.env.RT_E2E_GRADIENT_NUMERIC_SCREENSHOT});}else if(key==='angle')assert.equal(await page.getByRole('slider',{name:'Gradient 1 angle',exact:true}).getAttribute('aria-valuenow'),String(changed[index].angle));else assert.equal(await page.getByRole('button',{name:'Gradient 2 center',exact:true}).getAttribute('data-'+key),String(changed[index][key]));};
    await scrub(delta,null,true,preview);assert.deepEqual(await gradientState(),originalGradients);assert.deepEqual(await page.evaluate(value=>RetouchHTMLCSSValues.parseGradients(value),await page.getByLabel('Gradient '+(index+1)+' preview',{exact:true}).evaluate(el=>el.style.backgroundImage)),[originalGradients[index]]);assert.equal(await text.getAttribute('style'),textStyle);await scrub(delta,null,false,preview);await wait(()=>read()!==originalSource);await settled();await wait(async()=>JSON.stringify(await gradientState())===JSON.stringify(changed));assert.equal(await text.getAttribute('style'),textStyle);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
   }
   assert.deepEqual(errors,[]);console.log(engine+': PASS inspector numeric label dragging, modifiers, lower bound, draft cancellation, responsive source, single undo, direct typing, live opacity, corner, typography effect and gradient previews');return;
  }
  assert.equal(await page.locator('#panel').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');
  assert.equal(await page.locator('#frameWrap').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(229, 229, 229)');
  assert.deepEqual(await page.locator('#panelBody > .inspector-section > h3').allTextContents(),['Position','Layout','Appearance','Fill','Stroke','Effects']);
  await page.getByRole('button',{name:'Horizontal layout',exact:true}).click();await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).display==='flex'&&getComputedStyle(el).flexDirection===(getComputedStyle(el).writingMode==='horizontal-tb'?'row':'column')));assert.equal(await page.getByRole('button',{name:'Horizontal layout',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
  const clipping=page.getByLabel('Clip content',{exact:true});assert.equal(await clipping.evaluate(el=>el.indeterminate),true);
  await clipping.check();await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).overflowX==='clip'&&getComputedStyle(el).overflowY==='clip'));assert.match(read(),/md:!overflow-clip/);
  await clipping.uncheck();await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).overflowX==='visible'&&getComputedStyle(el).overflowY==='visible'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(await clipping.isChecked(),true);
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);assert.equal(await clipping.evaluate(el=>el.indeterminate),true);
  await page.getByRole('button',{name:'Vertical layout',exact:true}).click();await settled();
  await wait(async()=>parent.evaluate(el=>getComputedStyle(el).display==='flex'&&getComputedStyle(el).flexDirection===(getComputedStyle(el).writingMode==='horizontal-tb'?'column':'row')));
  assert.equal(await page.getByRole('button',{name:'Vertical layout',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
  for(const direction of ['row','column','row-reverse','column-reverse']){
   await page.getByLabel('Arrange children',{exact:true}).selectOption(direction);await settled();const beforeAlignment=read();
   for(const corner of ['top left','bottom right']){
    await page.getByRole('button',{name:'Align children '+corner,exact:true}).click();await settled();
    await wait(async()=>parent.evaluate((el,corner)=>{const p=el.getBoundingClientRect(),r=[...el.children].map(child=>child.getBoundingClientRect());return corner==='top left'?Math.abs(Math.min(...r.map(r=>r.left))-p.left)<1&&Math.abs(Math.min(...r.map(r=>r.top))-p.top)<1:Math.abs(Math.max(...r.map(r=>r.right))-p.right)<1&&Math.abs(Math.max(...r.map(r=>r.bottom))-p.bottom)<1;},corner));
    assert.equal(await page.getByRole('button',{name:'Align children '+corner,exact:true}).getAttribute('aria-pressed'),'true');
    if(direction==='row'&&corner==='bottom right'){await page.locator('#panel').evaluate(panel=>{panel.scrollTop+=panel.querySelector('[data-section=layout]').getBoundingClientRect().top-panel.getBoundingClientRect().top-48;});await page.locator('#panel').screenshot({path:'/private/tmp/retouch-figma-alignment-'+engine+'.png'});}
    await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),beforeAlignment);
   }
   await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
  }
  const opacity=page.getByLabel('Opacity (%)',{exact:true});await opacity.fill('75');await opacity.press('Tab');await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).opacity==='0.75'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
  await page.getByText('Individual corners',{exact:true}).click();
  const corner=page.getByLabel('Top left radius (px)',{exact:true});await corner.fill('12');await corner.press('Tab');await settled();
  await wait(async()=>parent.evaluate(el=>getComputedStyle(el).borderTopLeftRadius==='12px'&&getComputedStyle(el).borderTopRightRadius==='20px'));
  await page.getByRole('button',{name:'Reset top left radius',exact:true}).click();await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).borderTopLeftRadius==='20px'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).borderTopLeftRadius==='12px'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
  const sharedRadius=page.getByLabel('Corner radius (px)',{exact:true});await sharedRadius.fill('6');await sharedRadius.press('Tab');await settled();
  await wait(async()=>parent.evaluate(el=>['borderTopLeftRadius','borderTopRightRadius','borderBottomLeftRadius','borderBottomRightRadius'].every(property=>getComputedStyle(el)[property]==='6px')));
  await page.getByRole('button',{name:'Reset corner radius',exact:true}).click();await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).borderTopLeftRadius==='20px'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(async()=>parent.evaluate(el=>getComputedStyle(el).borderTopLeftRadius==='6px'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
  await page.locator('#panel').evaluate(panel=>{panel.scrollTop+=panel.querySelector('[data-section=appearance]').getBoundingClientRect().top-panel.getBoundingClientRect().top-48;});await page.locator('#panel').screenshot({path:'/private/tmp/retouch-corners-'+engine+'.png'});
  await page.getByText('Layer actions',{exact:true}).click();assert.equal(await page.getByRole('button',{name:'Lock selection',exact:true}).isVisible(),true);await page.getByText('Layer actions',{exact:true}).click();
  await page.locator('#panel').evaluate(el=>el.scrollTop=0);
  assert.deepEqual(errors,[]);await page.screenshot({path:process.env.RT_UI_SCREENSHOT||'/private/tmp/retouch-figma-light-'+engine+'.png',fullPage:true});await page.locator('#panel').evaluate(panel=>{panel.scrollTop+=panel.querySelector('[data-section=appearance]').getBoundingClientRect().top-panel.getBoundingClientRect().top-48;});await page.locator('#panel').screenshot({path:'/private/tmp/retouch-figma-paint-'+engine+'.png'});await page.getByRole('treeitem',{name:'p · sample',exact:true}).click();await settled();
  const textElement=page.frameLocator('#app').locator('#sample'),beforeStroke=read();
  const strokeWidth=page.getByLabel('Border width (px)',{exact:true});await strokeWidth.fill('6');await strokeWidth.press('Tab');await settled();await wait(async()=>textElement.evaluate(el=>getComputedStyle(el).borderTopWidth==='6px'&&getComputedStyle(el).borderTopStyle==='dashed'));
  await page.getByRole('button',{name:'Reset border width',exact:true}).click();await settled();await wait(async()=>textElement.evaluate(el=>getComputedStyle(el).borderTopWidth==='2px'));
  for(let i=0;i<2;i++){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();}assert.equal(read(),beforeStroke);
  await page.getByLabel('Border style',{exact:true}).selectOption('solid');await settled();await wait(async()=>textElement.evaluate(el=>getComputedStyle(el).borderTopStyle==='solid'&&getComputedStyle(el).borderTopWidth==='2px'));
  await page.getByRole('button',{name:'Reset border style',exact:true}).click();await settled();await wait(async()=>textElement.evaluate(el=>getComputedStyle(el).borderTopStyle==='dashed'));
  for(let i=0;i<2;i++){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();}assert.equal(read(),beforeStroke);
  const type=page.locator('[data-section="typography"]');await type.waitFor();
  assert.equal(await type.locator('.type-preview').isVisible(),false);
  assert.equal(await page.getByRole('button',{name:'Apply text',exact:true}).isVisible(),false);
  await page.getByText('Text content',{exact:true}).click();assert.equal(await page.getByRole('button',{name:'Apply text',exact:true}).isVisible(),true);await page.getByText('Text content',{exact:true}).click();
  assert.equal(await page.getByLabel('Font size (px)',{exact:true}).locator('xpath=ancestor::*[contains(@class,"property-pair")]').count(),1);
  await page.getByRole('button',{name:'Align text center',exact:true}).click();await settled();
  await wait(async()=>page.frameLocator('#app').locator('#sample').evaluate(el=>getComputedStyle(el).textAlign==='center'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),originalSource);
  await page.locator('#panel').evaluate(panel=>{panel.scrollTop+=panel.querySelector('[data-section=typography]').getBoundingClientRect().top-panel.getBoundingClientRect().top-48;});
  await page.locator('#panel').screenshot({path:'/private/tmp/retouch-figma-type-'+engine+'.png'});assert.deepEqual(errors,[]);
  console.log(engine+' '+writingMode+' '+textDirection+': PASS light workspace, section order, segmented layout edits, opacity edits, exact undo, layer actions and screenshot');
 }finally{if(browser)await browser.close();if(!exited)child.kill('SIGTERM');await stopped;fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
