'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=process.env.RT_INSPECTOR_FIXTURE;
if(!root)throw Error('Set RT_INSPECTOR_FIXTURE to a disposable inspector fixture');
const {chromium}=require(path.join(root,'node_modules/playwright'));
const file=path.join(root,'app/page.jsx'),original=fs.readFileSync(file,'utf8');
const source=original.replace('</main>','<section id="layers-fixture"><p>First layer</p><p>Second layer</p><p>Third layer</p></section></main>');
const read=()=>fs.readFileSync(file,'utf8');
(async()=>{
 fs.writeFileSync(file,source);
 const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1600,height:1100}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const wait=async(fn,name)=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw Error('Timed out: '+name);};
 const tree=page.getByRole('tree',{name:'Site layers'});
 const item=name=>tree.getByRole('treeitem',{name,exact:true});
 try {
  await page.goto((process.env.RT_E2E_URL||'http://localhost:3496')+'/rt');
  await item('p · First layer').waitFor();
  assert.equal(Number(await item('p · First layer').getAttribute('aria-level')),Number(await item('section · layers-fixture').getAttribute('aria-level'))+1);
  await page.getByRole('button',{name:'Collapse section · layers-fixture',exact:true}).click();
  await wait(async()=>await item('p · First layer').count()===0,'collapsed');
  await page.getByLabel('Find a layer').fill('Second layer');
  await item('p · Second layer').waitFor();
  assert.equal(await item('p · First layer').count(),0,'search filters siblings');
  await item('p · Second layer').click();
  await wait(async()=>await item('p · Second layer').getAttribute('aria-selected')==='true','selection');
  assert.equal(await page.frameLocator('#app').getByText('Second layer',{exact:true}).getAttribute('contenteditable'),null,'layer click selects without typing');
  await page.getByLabel('Find a layer').fill('');
  await item('p · Second layer').focus();await page.keyboard.press('ArrowUp');
  assert.equal(await item('p · First layer').evaluate(el=>el===document.activeElement),true,'keyboard moves through hierarchy');
  await page.keyboard.press('Enter');
  await wait(async()=>await item('p · First layer').getAttribute('aria-selected')==='true' && !await item('p · First layer').isDisabled() && await page.getByRole('button',{name:'Duplicate layer',exact:true}).isEnabled(),'first layer selected and duplicate available');
  await item('p · First layer').focus();
  await page.keyboard.press('Meta+d');
  await wait(()=>read().split('<p>First layer</p>').length===3,'duplicate source');
  await wait(async()=>await page.frameLocator('#app').getByText('First layer',{exact:true}).count()===2,'duplicate render');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await wait(()=>read()===source,'duplicate undo exact');
  await page.getByRole('button',{name:'Redo',exact:true}).click();
  await wait(()=>read().split('<p>First layer</p>').length===3,'duplicate redo source');
  await wait(async()=>await page.frameLocator('#app').getByText('First layer',{exact:true}).count()===2,'duplicate redo render');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await wait(()=>read()===source,'duplicate redo then undo');
  await wait(async()=>(await page.getByRole('button',{name:'Undo',exact:true}).getAttribute('aria-busy'))==='false','undo finished');
  await item('p · Second layer').click();
  await page.getByRole('button',{name:'Move layer up',exact:true}).click();
  await wait(()=>read().indexOf('<p>Second layer')<read().indexOf('<p>First layer'),'move source');
  await wait(async()=>await page.frameLocator('#app').locator('#layers-fixture p').first().textContent()==='Second layer','move render');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===source,'move undo exact');
  await wait(async()=>(await page.getByRole('button',{name:'Undo',exact:true}).getAttribute('aria-busy'))==='false','move undo finished');
  await item('p · Third layer').click();
  await wait(async()=>await page.getByRole('button',{name:'Delete layer',exact:true}).isEnabled(),'delete available');
  await item('p · Third layer').focus();await page.keyboard.press('Delete');
  await wait(()=>!read().includes('<p>Third layer</p>'),'delete source');
  await wait(async()=>await page.frameLocator('#app').getByText('Third layer',{exact:true}).count()===0,'delete render');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===source,'delete undo exact');
  await page.getByRole('button',{name:'Redo',exact:true}).click();
  await wait(()=>!read().includes('<p>Third layer</p>'),'delete redo source');
  await wait(async()=>await page.frameLocator('#app').getByText('Third layer',{exact:true}).count()===0,'delete redo render');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===source,'delete redo then undo');
  await wait(async()=>(await page.getByRole('button',{name:'Undo',exact:true}).getAttribute('aria-busy'))==='false','delete undo finished');
  await page.getByRole('button',{name:'Collapse section · layers-fixture',exact:true}).click();
  await wait(async()=>await item('p · First layer').count()===0,'collapse remains enabled after undo');
  await item('div · anchor-target').click();
  assert.equal(await page.getByRole('button',{name:'Duplicate layer',exact:true}).isDisabled(),true,'authored id cannot be duplicated');
  await page.screenshot({path:'/tmp/retouch-layers.png'});
  assert.deepEqual(errors,[],'no browser errors');
  console.log('PASS layer hierarchy, search, collapse, keyboard navigation, source-backed duplicate/move/delete, rendered results, exact undo and identity refusal');
 } catch(error){console.error('Layer test status:',await page.locator('#status').textContent(),'Browser errors:',errors);throw error;} finally {fs.writeFileSync(file,original);await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
