'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-linked-scroll-')),file=path.join(root,'index.html'),source='<!doctype html><html><head><style>body{margin:0;min-height:4000px;min-width:1800px}#panel{width:300px;height:200px;overflow:auto}#content{width:1000px;height:1200px;background:linear-gradient(#ccc,#333)}@media(max-width:500px){#panel{height:300px;width:250px}body{min-height:6000px}}</style></head><body><div id="panel"><div id="content">Linked screens</div></div></body></html>';fs.writeFileSync(file,source);
 const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{
  browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1800,height:1200}}),errors=[];page.on('pageerror',error=>errors.push(error.message));const wait=async fn=>{for(let n=0;n<120;n++){if(await fn())return;await page.waitForTimeout(50);}throw Error('Linked scrolling did not settle');};
  await page.goto('http://localhost:'+server.address().port+'/rt');await page.getByRole('button',{name:'Compare screens',exact:true}).click();
  const main=page.frameLocator('#app'),phone=page.frameLocator('iframe[title="Phone comparison preview"]'),desktop=page.frameLocator('iframe[title="Desktop comparison preview"]'),frames=[main,phone,desktop],toggle=page.getByRole('button',{name:'Link scrolling across screens',exact:true});for(const frame of frames)await frame.locator('#panel').waitFor();
  const set=(frame,selector,x,y)=>frame.locator('body').evaluate((body,{selector,x,y})=>{const node=selector?document.querySelector(selector):document.scrollingElement;node.scrollTo({left:x*(node.scrollWidth-node.clientWidth),top:y*(node.scrollHeight-node.clientHeight),behavior:'instant'});},{selector,x,y});
  const ratios=(frame,selector)=>frame.locator('body').evaluate((body,selector)=>{const node=selector?document.querySelector(selector):document.scrollingElement;return [node.scrollLeft/Math.max(1,node.scrollWidth-node.clientWidth),node.scrollTop/Math.max(1,node.scrollHeight-node.clientHeight)];},selector);
  const matches=async(frame,selector,x,y)=>(await ratios(frame,selector)).every((value,index)=>Math.abs(value-[x,y][index])<.003);
  assert.equal(await toggle.getAttribute('aria-pressed'),'false');await set(phone,null,.2,.2);await page.waitForTimeout(150);assert.ok(await matches(main,null,0,0));await toggle.click();await set(phone,null,.4,.4);await wait(async()=>await matches(main,null,.4,.4)&&await matches(desktop,null,.4,.4));
  await set(main,null,.6,.65);await wait(async()=>await matches(phone,null,.6,.65)&&await matches(desktop,null,.6,.65));await page.waitForTimeout(200);assert.ok(await matches(main,null,.6,.65),'Sync feedback does not drift');
  await set(phone,'#panel',.35,.55);await wait(async()=>await matches(main,'#panel',.35,.55)&&await matches(desktop,'#panel',.35,.55));assert.ok(await matches(main,null,.6,.65),'Nested scrolling does not move the page');
  await set(desktop,'#panel',.7,.8);await wait(async()=>await matches(phone,'#panel',.7,.8)&&await matches(main,'#panel',.7,.8));
  await page.getByRole('button',{name:'Hide Phone preview',exact:true}).click();await set(main,'#panel',.1,.2);await wait(async()=>await matches(desktop,'#panel',.1,.2));assert.ok(await matches(phone,'#panel',.7,.8),'Collapsed previews keep their position');await page.getByRole('button',{name:'Show Phone preview',exact:true}).click();await set(main,'#panel',.3,.4);await wait(()=>matches(phone,'#panel',.3,.4));
  await phone.locator('#panel').evaluate(node=>{const duplicate=node.cloneNode(true);duplicate.id='duplicate';node.after(duplicate);});await set(main,'#panel',.6,.6);await wait(()=>matches(desktop,'#panel',.6,.6));assert.ok(await matches(phone,'#panel',.3,.4),'Ambiguous repeated source identities stay independent');await phone.locator('#duplicate').evaluate(node=>node.remove());
  await toggle.click();await set(main,null,.2,.3);await page.waitForTimeout(200);assert.ok(await matches(phone,null,.6,.65),'Turning linking off restores independent scrolling');await toggle.click();
  await page.reload();await page.getByRole('button',{name:'Compare screens',exact:true}).click();for(const frame of frames)await frame.locator('#panel').waitFor();assert.equal(await toggle.getAttribute('aria-pressed'),'true');await set(phone,null,.3,.4);await wait(()=>matches(main,null,.3,.4));
  await page.getByRole('button',{name:'Compare screens',exact:true}).click();await wait(async()=>!await page.getByRole('button',{name:'Compare screens',exact:true}).isDisabled());await set(main,null,.1,.1);await page.getByRole('button',{name:'Compare screens',exact:true}).click();for(const frame of frames)await frame.locator('#panel').waitFor();await set(desktop,'#panel',.4,.5);await wait(()=>matches(main,'#panel',.4,.5));await page.screenshot({path:'/tmp/retouch-linked-scroll-'+engine+'.png'});assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);console.log('LINKED ROOT/NESTED SCROLL, INDEPENDENCE, RELOAD, COLLAPSE AND AMBIGUITY PASS',engine);
 }finally{await browser?.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
