'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,target,read,wait,settled,states,kind})=>{
 const button=name=>page.getByRole('button',{name,exact:true}),field=page.getByLabel('List spacing (px)',{exact:true}),listStyle=page.getByLabel('Text layer list style',{exact:true});
 const choose=async(text,offset=0)=>{await target.focus();await target.evaluate((el,[text,offset])=>{const d=el.ownerDocument,w=d.createTreeWalker(el,4);let node;while(node=w.nextNode())if(node.data===text)break;if(!node)throw Error('Missing '+text);const range=d.createRange();range.setStart(node,offset);range.collapse(true);d.getSelection().removeAllRanges();d.getSelection().addRange(range);},[text,offset]);};
 const save=async()=>{await button('Finish text editing').click();await settled();await wait(()=>read()!==states.at(-1));states.push(read());};
 const open=async()=>{await target.dispatchEvent('dblclick');await wait(async()=>await target.getAttribute('contenteditable')==='true');};
 const check=async(selector,gap,count)=>{const boxes=await target.locator(selector).evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect(),css=getComputedStyle(node);return {top:r.top,bottom:r.bottom,end:css.marginBlockEnd,line:css.lineHeight};}));assert.equal(boxes.length,count);assert.equal(boxes.at(-1).end,'0px');for(let i=1;i<boxes.length;i++)assert.ok(Math.abs(boxes[i].top-boxes[i-1].bottom-gap)<1,JSON.stringify(boxes));return boxes;};
 assert.equal(await field.isDisabled(),true);await target.evaluate(el=>{const d=el.ownerDocument,r=d.createRange();r.selectNodeContents(el);d.getSelection().removeAllRanges();d.getSelection().addRange(r);});
 for(const [index,text]of ['A','B','C','D'].entries()){if(index)await page.keyboard.press('Shift+Enter');await page.keyboard.insertText(text);}await listStyle.selectOption('ol');await choose('A');await wait(()=>field.isEnabled());const before=await target.innerHTML();await field.fill('18');await field.press('Enter');const baseline=await check(':scope > ol > li',18,4);assert.equal(read(),states.at(-1));const changed=await target.innerHTML();await button('Undo').click();assert.equal(await target.innerHTML(),before);await button('Redo').click();assert.equal(await target.innerHTML(),changed);await save();await open();await choose('A');await wait(()=>field.isEnabled());assert.equal(await field.inputValue(),'18');await check(':scope > ol > li',18,4);
 await choose('D',1);await page.keyboard.press('Enter');await page.keyboard.insertText('E');await check(':scope > ol > li',18,5);await choose('D',1);await page.keyboard.press('Delete');await check(':scope > ol > li',18,4);await button('Undo').click();await button('Undo').click();await button('Undo').click();await check(':scope > ol > li',18,4);
 await choose('B');await button('Increase list indentation').click();await choose('C');await button('Increase list indentation').click();await choose('B');await wait(()=>field.isEnabled());await field.fill('7.5');await field.press('Enter');await check('ol ol > li',7.5,2);await choose('A');await field.fill('18');await field.press('Enter');await check(':scope > ol > li',18,2);await check('ol ol > li',7.5,2);await save();await open();await choose('B');await wait(()=>field.isEnabled());assert.equal(await field.inputValue(),'7.5');await check('ol ol > li',7.5,2);
 await field.fill('-1');await field.press('Enter');await check('ol ol > li',7.5,2);await field.fill('0');await field.press('Enter');await check('ol ol > li',0,2);await check(':scope > ol > li',18,2);await save();await open();await choose('B');assert.equal(await field.inputValue(),'0');assert.equal((await check('ol ol > li',0,2))[0].line,baseline[0].line);
 if(process.env.RT_E2E_LIST_SPACING_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_LIST_SPACING_SCREENSHOT,caret:'initial'});
 await button('Finish text editing').click();await settled();assert.equal(read(),states.at(-1));
 for(let i=states.length-2;i>=0;i--){await button('Undo').click();await settled();await wait(()=>read()===states[i]);}
 for(let i=1;i<states.length;i++){await button('Redo').click();await settled();await wait(()=>read()===states[i]);}
 console.log('LIST SPACING PASS '+kind+': item gap geometry, nested isolation, fractional/zero values, line-height retention, insertion/join inheritance, local history, save/reopen and exact source undo/redo');
};
