'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,box,read,wait,settled})=>{
 const source=read(),originalStyle=await box.getAttribute('style'),close=(a,b,label)=>assert.ok(Math.abs(a-b)<.8,label+': '+a+' vs '+b);
 const measure=()=>box.evaluate(el=>{const css=getComputedStyle(el),width=parseFloat(css.width),height=parseFloat(css.height),m=parent.RetouchSVGDraw.nativeSpace(el).matrix.translate(-el.clientLeft,-el.clientTop);return {width,height,points:[[0,0],[width,0],[width,height],[0,height]].map(([x,y])=>{const p=new DOMPoint(x,y).matrixTransform(m);return {x:p.x,y:p.y};})};});
 const before=await measure(),frame=await page.locator('#app').boundingBox(),zoom=frame.width/await box.evaluate(()=>innerWidth),center=g=>({x:(g.points[0].x+g.points[2].x)/2,y:(g.points[0].y+g.points[2].y)/2});
 const open=async handle=>{await page.getByRole('button',{name:'Resize on canvas',exact:true}).click();await page.locator('.canvas-local-resize-surface').waitFor();return page.locator('.canvas-local-resize-surface [data-resize-handle='+handle+']');};
 const drag=async(handle,dx,dy,modifiers=[])=>{const button=await open(handle);await page.evaluate(()=>{window.__retouchResizePointer={};const surface=document.querySelector('.canvas-local-resize-surface');surface.addEventListener('pointerdown',e=>{window.__retouchResizePointer.start={x:e.clientX,y:e.clientY};},true);surface.addEventListener('pointermove',e=>{window.__retouchResizePointer.end={x:e.clientX,y:e.clientY};},true);});const r=await button.boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;await page.mouse.move(x,y);await page.mouse.down();for(const key of modifiers)await page.keyboard.down(key);await page.mouse.move(x+zoom*((before.points[1].x-before.points[0].x)/before.width*dx+(before.points[3].x-before.points[0].x)/before.height*dy),y+zoom*((before.points[1].y-before.points[0].y)/before.width*dx+(before.points[3].y-before.points[0].y)/before.height*dy),{steps:4});const events=await page.evaluate(()=>window.__retouchResizePointer),a=(before.points[1].x-before.points[0].x)/before.width,b=(before.points[1].y-before.points[0].y)/before.width,c=(before.points[3].x-before.points[0].x)/before.height,d=(before.points[3].y-before.points[0].y)/before.height,xDelta=(events.end.x-events.start.x)/zoom,yDelta=(events.end.y-events.start.y)/zoom;return {x:(d*xDelta-c*yDelta)/(a*d-b*c),y:(a*yDelta-b*xDelta)/(a*d-b*c)};};
 const undo=async()=>{await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===source);close((await measure()).width,before.width,'undo width');};
 let delta=await drag('e',30,0);let live=await measure();close(live.width,before.width+delta.x,'live width');close(live.height,before.height,'live height');for(const axis of ['x','y'])close(live.points[0][axis],before.points[0][axis],'opposite corner '+axis);assert.equal(read(),source);const widthField=page.locator('input[aria-label="Width (CSS)"], input[aria-label="Width (px)"]');close(parseFloat(await widthField.inputValue()),live.width,'live inspector width');if(process.env.RT_E2E_RESIZE_LAYER_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_RESIZE_LAYER_SCREENSHOT});await page.mouse.up();await settled();await wait(()=>read()!==source);close((await measure()).width,live.width,'saved width');await undo();
 delta=await drag('nw',-20,-10,['Shift','Alt']);const expectedWidth=before.width+2*Math.max(-delta.x,-delta.y*before.width/before.height);live=await measure();close(live.width,expectedWidth,'proportional width');close(live.height,before.height*expectedWidth/before.width,'proportional height');for(const axis of ['x','y'])close(center(live)[axis],center(before)[axis],'center '+axis);await page.mouse.up();await page.keyboard.up('Alt');await page.keyboard.up('Shift');await settled();await wait(()=>read()!==source);await undo();
 const handle=await open('se');await handle.focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowDown');assert.equal(read(),source);await page.keyboard.press('Enter');await settled();await wait(()=>read()!==source);live=await measure();close(live.width,before.width+1,'keyboard width');close(live.height,before.height+1,'keyboard height');await undo();
 await drag('e',25,0);await page.keyboard.press('Escape');await page.mouse.up();assert.equal(await page.locator('.canvas-local-resize-surface').count(),0);assert.equal(read(),source);assert.equal(await box.getAttribute('style'),originalStyle,'cancel restores exact inline styles');close((await measure()).width,before.width,'cancel width');
 await drag('e',20,0);const screen=page.getByLabel('Screen size',{exact:true}),originalScreen=await screen.inputValue();await screen.selectOption(originalScreen==='768x1024'?'1440x900':'768x1024');await settled();await page.mouse.up();assert.equal(await page.locator('.canvas-local-resize-surface').count(),0);assert.equal(read(),source);assert.equal(await box.getAttribute('style'),originalStyle,'screen cancellation restores inline styles');await screen.selectOption(originalScreen);await settled();
 await drag('e',20,0);const parentStyle=await box.evaluate(el=>el.offsetParent.getAttribute('style'));try{await box.evaluate(el=>el.offsetParent.style.setProperty('transform','rotate(22deg)'));await wait(async()=>await page.locator('.canvas-local-resize-surface').count()===0);assert.equal(read(),source);assert.equal(await box.getAttribute('style'),originalStyle,'changed frame restores inline styles');}finally{await page.mouse.up();await box.evaluate((el,value)=>{if(value===null)el.offsetParent.removeAttribute('style');else el.offsetParent.setAttribute('style',value);},parentStyle);}
 if(process.env.RT_E2E_MATRIX_POSITION_LIMITS)for(const [handle,dx,width]of [['e',500,200],['w',500,120]]){await drag(handle,dx,0);close((await measure()).width,width,'CSS width bound');await page.mouse.up();await settled();await wait(()=>read()!==source);close((await measure()).width,width,'saved CSS width bound');await undo();}
 console.log('PASS transformed canvas resizing, opposite-corner preservation, centered proportional resize, keyboard, cancellation and exact undo');
};
