'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,app,kind,read,wait,settled})=>{
 const target=app.locator('h1'),initial=read(),original=await target.textContent();
 const edit=async(from=original.length,to=from)=>{await target.click();await wait(async()=>await target.getAttribute('contenteditable')==='true');await target.evaluate((el,{from,to})=>{const d=el.ownerDocument,r=d.createRange();r.setStart(el.firstChild,from);r.setEnd(el.firstChild,to);const selection=d.getSelection();selection.removeAllRanges();selection.addRange(r);},{from,to});};
 const paste=async text=>target.evaluate((el,text)=>{const data=new DataTransfer();data.setData('text/plain',text);data.setData('text/html','<img src=x onerror="throw Error(1)">');el.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data}));},text);
 const finish=()=>page.getByRole('button',{name:'Finish text editing',exact:true}).click();
 const history=async saved=>{for(const [name,state]of [['Undo',initial],['Redo',saved],['Undo',initial]]){await page.getByRole('button',{name,exact:true}).click();await settled();await wait(()=>read()===state);}};
 await edit(1,4);await paste('');assert.equal(await target.textContent(),original);await finish();await settled();assert.equal(read(),initial);
 await edit(1,4);const clipboard='A<b>\r\n\rB\n',rendered=original.slice(0,1)+'A<b>\n\nB\n'+original.slice(4);await paste(clipboard);assert.equal(await target.innerText(),rendered);assert.equal(await target.locator('br').count(),3);assert.equal(await target.locator('b,img').count(),0);assert.equal(read(),initial);
 await page.keyboard.press('Control+z');assert.equal(await target.textContent(),original);assert.equal(await target.locator('br').count(),0);assert.equal(await target.evaluate(el=>el.ownerDocument.getSelection().toString()),original.slice(1,4));await page.keyboard.press('Control+Shift+z');assert.equal(await target.innerText(),rendered);
 await finish();await settled();await wait(()=>read()!==initial);const replaced=read();assert.equal(await target.innerText(),rendered);assert.equal(await target.locator('br').count(),3);await history(replaced);
 await edit();const size=page.getByLabel('Selected text size (px)',{exact:true}),color=page.getByLabel('Selected text color',{exact:true});await size.fill('20');await size.press('Enter');await color.fill('#123456');await color.press('Enter');await page.keyboard.insertText('Z');const beforePaste=await target.innerHTML();await paste('A\n\nB\n');await page.keyboard.press('Control+z');assert.equal(await target.innerHTML(),beforePaste,'one undo removes the entire paste but preserves preceding typing');await page.keyboard.press('Control+Shift+z');assert.equal(await target.textContent(),original+'ZAB');for(const span of await target.locator('span').all())assert.deepEqual(await span.evaluate(el=>{const style=getComputedStyle(el);return [style.fontSize,style.color];}),['20px','rgb(18, 52, 86)']);
 await finish();await settled();await wait(()=>read()!==initial);const styled=read();assert.equal(await target.locator('br').count(),3);if(process.env.RT_E2E_MULTILINE_PASTE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_MULTILINE_PASTE_SCREENSHOT});await history(styled);
 // A protected source token must not be removed by selection replacement.
 await edit();await target.evaluate(el=>{const d=el.ownerDocument,token=d.createElement('span');token.contentEditable='false';token.textContent=el.textContent;el.replaceChildren(token);const range=d.createRange();range.selectNodeContents(el);const selection=d.getSelection();selection.removeAllRanges();selection.addRange(range);});const protectedMarkup=await target.innerHTML();await paste('replacement\ntext');assert.equal(await target.innerHTML(),protectedMarkup);assert.equal(read(),initial);await target.evaluate((el,text)=>el.replaceChildren(el.ownerDocument.createTextNode(text)),original);await finish();await settled();assert.equal(read(),initial);
 // Unsupported source-owned script structure must roll back the entire paste.
 await edit();await target.evaluate(el=>{const d=el.ownerDocument,script=d.createElement('sup');script.className='authored-script';script.textContent=el.textContent;el.replaceChildren(script);const range=d.createRange();range.setStart(script.firstChild,1);range.collapse(true);const selection=d.getSelection();selection.removeAllRanges();selection.addRange(range);});await size.fill('24');await size.press('Enter');const ownedMarkup=await target.innerHTML();await paste('one\ntwo');assert.equal(await target.innerHTML(),ownedMarkup);assert.equal(read(),initial);await target.evaluate((el,text)=>el.replaceChildren(el.ownerDocument.createTextNode(text)),original);await finish();await settled();assert.equal(read(),initial);
 console.log('MULTILINE PASTE PASS '+kind+': LF/CRLF/CR, blank/trailing lines, literal clipboard text, selection replacement, cursor styles, one-step local undo, source undo/redo and protected tokens');
};
