'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const kind=process.env.RT_E2E_RENDERER||'html',engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-page-fonts-')),file=path.join(root,kind==='react'?'app/page.jsx':kind==='liquid'?'sections/main.liquid':'index.html'),css=(process.env.RT_E2E_VARIABLE_FONT?'@font-face{font-family:"Variable Test";font-weight:100 900;src:url(data:font/woff2;base64,'+fs.readFileSync(path.join(fixture,'node_modules/next/dist/next-devtools/server/font/geist-latin.woff2')).toString('base64')+')}':'')+'@font-face{font-family:"Page Face";src:local("Arial")} .type-editorial{font-family:'+ (process.env.RT_E2E_VARIABLE_FONT?'"Variable Test"':'Georgia') +',serif;font-size:32px;font-weight:700}.other-font{font-family:"Studio_Test",serif}.named-font{font-family:"Page Face",serif}';fs.mkdirSync(path.dirname(file),{recursive:true});const body='<main><h1 '+(kind==='react'?'className':'class')+'="type-editorial font-bold md:opacity-90 [&:hover]:opacity-50">Headline</h1><p '+(kind==='react'?'className':'class')+'="other-font">Other text</p><p '+(kind==='react'?'className':'class')+'="named-font">Named text</p></main>',original=kind==='react'?'export default function Page(){return '+body+'}':'<html><head><style>'+css+'</style></head><body>'+(kind==='liquid'&&process.env.RT_E2E_LIQUID_DYNAMIC?body.replace('type-editorial font-bold','type-editorial font-bold {% if alternate %}font-mono{% else %}font-serif{% endif %}'):body)+'</body></html>';fs.writeFileSync(file,original);
 let server,child,stopped,browser,url,logs='';const read=()=>fs.readFileSync(file,'utf8'),wait=async fn=>{for(let i=0;i<400;i++){try{if(await fn())return;}catch(error){if(!/Execution context was destroyed|fetch failed/.test(error.message))throw error;}await new Promise(r=>setTimeout(r,100));}throw Error('Timed out '+logs.slice(-1000));};
 try{
  if(kind==='react'){fs.symlinkSync(path.join(fixture,'node_modules'),path.join(root,'node_modules'),'dir');fs.copyFileSync(path.join(fixture,'postcss.config.mjs'),path.join(root,'postcss.config.mjs'));fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({private:true,dependencies:{next:'16.2.5',react:'19.2.0','react-dom':'19.2.0'}}));fs.writeFileSync(path.join(root,'app/style.css'),'@import "tailwindcss";\n'+css);fs.writeFileSync(path.join(root,'app/layout.jsx'),'import "./style.css";export default function Layout({children}){return <html><body>{children}</body></html>}');child=spawn(process.execPath,[path.resolve(__dirname,'../../bin/retouch.cjs'),'--',process.execPath,path.join(fixture,'node_modules/next/dist/bin/next'),'dev','--webpack','-p','0'],{cwd:root,env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});stopped=new Promise(r=>child.once('exit',r));for(const stream of [child.stdout,child.stderr])stream.on('data',data=>{logs+=data;url=logs.match(/http:\/\/localhost:\d+/)?.[0];});await wait(()=>url);await wait(async()=>{try{return(await fetch(url+'/rt/__api/health')).ok;}catch{return false;}});
  }else if(kind==='liquid'){
   const liquid=require('../../src/adapters/liquid.cjs'),engine=new(require('liquidjs').Liquid)(),{Scanner}=require(path.join(fixture,'node_modules/@tailwindcss/oxide')),{compile}=require('node:module').createRequire(path.join(fixture,'package.json'))('@tailwindcss/node');
   const compiler=await compile('@import "tailwindcss";\n'+css,{base:fixture,onDependency(){}});
   server=require('../../src/server.cjs').startServer({appRoot:root,adapter:liquid,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{try{const source=read(),candidates=new Scanner({}).scanFiles([{content:source,extension:'liquid'}]),styles=compiler.build(candidates),html=await engine.parseAndRender(liquid.stamp(source,file,root).code,{alternate:req.url.includes('alternate=1')});res.setHeader('content-type','text/html');res.end(html.replace('</head>','<style>'+styles+'</style></head>'));}catch(e){res.statusCode=500;res.end(e.stack);}}});await once(server,'listening');url='http://localhost:'+server.address().port;
  }else{server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');url='http://localhost:'+server.address().port;}
  browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[],snapshots=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/rt',{timeout:90000});const app=page.frameLocator('#app');await app.locator('h1').waitFor({timeout:90000});await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).click();const settled=()=>wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true'),family=()=>app.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily);await settled();
  const options=await page.getByLabel('Page font',{exact:true}).locator('option').evaluateAll(els=>els.map(el=>el.value)),custom=options.find(v=>v.includes('Studio_Test'));assert.ok(custom);assert.ok(options.some(v=>v.includes('Page Face')));assert.equal(read(),original);
  await page.getByText('Browse page fonts',{exact:true}).click();const search=page.getByRole('searchbox',{name:'Search page fonts'});await search.fill('NoSuchFamilyZZZ');await wait(async()=>await page.locator('.font-browser [role=status]').getAttribute('data-scanning')==='false');assert.equal(await page.getByRole('group',{name:'Matching fonts'}).getByRole('button').count(),0);assert.ok((await page.getByRole('status').allTextContents()).some(t=>t.includes('No matching fonts')));assert.equal(read(),original);assert.equal(await page.getByLabel('Page font',{exact:true}).inputValue(),await family());await search.press('Escape');assert.equal(await page.locator('.font-browser').getAttribute('open'),null);assert.equal(await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).getAttribute('aria-selected'),'true');
  const choose=async(value,browse=false)=>{snapshots.push(read());if(browse){await page.getByText('Browse page fonts',{exact:true}).click();await search.fill('sTuDiO_test');assert.equal(read(),snapshots.at(-1));const matching=page.getByRole('group',{name:'Matching fonts'}).getByRole('button');assert.equal(await matching.count(),1);if(process.env.RT_E2E_FONT_SEARCH_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_FONT_SEARCH_SCREENSHOT});await search.press('Tab');assert.equal(await matching.evaluate(el=>el===el.ownerDocument.activeElement),true);await page.keyboard.press('Enter');}else await page.getByLabel('Page font',{exact:true}).selectOption(value);await wait(()=>read()!==snapshots.at(-1));await settled();const normalize=s=>s.replace(/[\"']/g,'').replace(/\s*,\s*/g,',');try{await wait(async()=>normalize(await family())===normalize(value));}catch(error){console.log('FONT DIAGNOSTIC',JSON.stringify({source:read(),family:await family(),classes:await app.locator('h1').getAttribute('class')}));throw error;}if(kind==='liquid'&&process.env.RT_E2E_LIQUID_DYNAMIC){const alternate=await browser.newPage({viewport:await app.locator('html').evaluate(el=>({width:el.ownerDocument.defaultView.innerWidth,height:el.ownerDocument.defaultView.innerHeight}))});try{await alternate.goto(url+'/?alternate=1');assert.equal(normalize(await alternate.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily)),normalize(value));assert.equal(await alternate.locator('h1').evaluate(el=>getComputedStyle(el).fontWeight),'700');}finally{await alternate.close();}}};
  await choose('monospace');assert.equal(await family(),'monospace');assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).fontWeight),'700');assert.match(read(),/type-editorial/);if(kind!=='html'){await app.locator('h1').hover();await wait(async()=>await app.locator('h1').evaluate(el=>getComputedStyle(el).opacity)==='0.5');await page.getByRole('button',{name:'Undo',exact:true}).hover();}
  await choose(options.find(v=>v.includes('Page Face')));assert.match(await family(),/Page Face/);
  await choose(options.find(v=>v.includes('Page Face')&&v.includes(',')));assert.match(await family(),/Page Face/);
  await choose(custom,true);assert.match(await family(),/Studio_Test/);assert.doesNotMatch(await family(),/Studio Test/);
  await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();await page.getByLabel('Style screen scope').selectOption(kind==='html'?'min-[768px]:':'md:');await choose('serif');assert.equal(await family(),'serif');await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();assert.match(await family(),/Studio_Test/);await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();
  if(kind!=='html')await wait(async()=>{try{return await page.frameLocator('iframe[title="Typography preview"]').locator('body div').evaluate(el=>getComputedStyle(el).fontFamily)==='serif';}catch(error){if(/Frame was detached/.test(error.message))return false;throw error;}});
  snapshots.push(read());await page.getByRole('button',{name:'Reset font family',exact:true}).click();await wait(()=>read()!==snapshots.at(-1));await settled();await wait(async()=>/Studio_Test/.test(await family()));if(process.env.RT_E2E_FONT_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_FONT_SCREENSHOT});
  while(snapshots.length){const expected=snapshots.pop();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===expected);await settled();}assert.equal(read(),original);await wait(async()=>(process.env.RT_E2E_VARIABLE_FONT?/Variable Test/:/Georgia/).test(await family()));if(process.env.RT_E2E_CUSTOM_WEIGHT){
   const weight=()=>app.locator('h1').evaluate(el=>getComputedStyle(el).fontWeight),input=page.getByLabel(kind==='html'?'Font weight (CSS)':'Font weight (1–1000)',{exact:true});
   await page.getByLabel('Style screen scope').selectOption('');await settled();
   const writeWeight=async value=>{snapshots.push(read());await input.fill(value);await input.press('Tab');await wait(()=>read()!==snapshots.at(-1));await settled();await wait(async()=>await weight()===value);if(kind!=='html')assert.equal(await input.inputValue(),value,'inspector weight must reflect the rendered revision');};
   await writeWeight('537.5');let baseInk;
   const ink=()=>app.locator('h1').evaluate(async el=>{const d=el.ownerDocument;await d.fonts.ready;const face=[...d.fonts].find(f=>f.family.replace(/["']/g,'')==='Variable Test');if(face?.status!=='loaded')throw Error('Variable font is not loaded');const css=d.defaultView.getComputedStyle(el),canvas=d.createElement('canvas');canvas.width=400;canvas.height=80;const ctx=canvas.getContext('2d');ctx.font=css.fontWeight+' 32px '+css.fontFamily;ctx.fillText(el.textContent,5,50);const data=ctx.getImageData(0,0,400,80).data;let sum=0;for(let i=3;i<data.length;i+=4)sum+=data[i];return sum;});
   if(process.env.RT_E2E_VARIABLE_FONT)baseInk=await ink();assert.match(await family(),(process.env.RT_E2E_VARIABLE_FONT?/Variable Test/:/Georgia/));if(kind!=='html'){assert.equal(await page.getByLabel('Font weight',{exact:true}).inputValue(),'');assert.equal(await page.getByLabel('Font weight',{exact:true}).locator('option:checked').textContent(),'Inherited / custom');for(const invalid of ['0','1001']){const before=read();await input.fill(invalid);await input.press('Tab');assert.equal(await input.evaluate(el=>el.checkValidity()),false);assert.equal(read(),before);}await input.fill('537.5');}
   const beforeScope=read();await page.getByLabel('Style screen scope').selectOption(kind==='html'?'min-[768px]:':'md:');await settled();assert.equal(read(),beforeScope,'changing scope after restoring an unchanged field must not write');await writeWeight('725.5');if(process.env.RT_E2E_VARIABLE_FONT){const heavyInk=await ink();assert.ok(heavyInk>baseInk*1.05,JSON.stringify({baseInk,heavyInk}));console.log('VARIABLE GLYPH INK',JSON.stringify({baseInk,heavyInk}));}
   if(process.env.RT_E2E_FONT_WEIGHT_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_FONT_WEIGHT_SCREENSHOT});
   await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();await wait(async()=>await weight()==='537.5');await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();await wait(async()=>await weight()==='725.5');
   if(kind!=='html'){snapshots.push(read());await page.getByLabel('Font weight',{exact:true}).selectOption('font-medium');await wait(()=>read()!==snapshots.at(-1));await settled();await wait(async()=>await weight()==='500');}
   snapshots.push(read());await page.getByRole('button',{name:'Reset font weight',exact:true}).click();await wait(()=>read()!==snapshots.at(-1));await settled();await wait(async()=>await weight()==='537.5');assert.match(await family(),(process.env.RT_E2E_VARIABLE_FONT?/Variable Test/:/Georgia/));
   while(snapshots.length){const expected=snapshots.pop();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===expected);await settled();}await wait(async()=>await weight()==='700');assert.equal(read(),original);
   console.log(engine+' '+kind+': PASS custom fractional weights, scope isolation, reset, family retention and exact undo'+(kind==='html'?'':', range validation and preset replacement'));
  }
  if(process.env.RT_E2E_LINE_HEIGHT){
   const height=()=>app.locator('h1').evaluate(el=>getComputedStyle(el).lineHeight),initialHeight=await height(),initialFamily=await family(),initialWeight=await app.locator('h1').evaluate(el=>getComputedStyle(el).fontWeight),input=page.getByLabel(kind==='html'?'Line height (CSS)':'Line height (px)',{exact:true});
   const write=async(action,expected)=>{snapshots.push(read());await action();await wait(()=>read()!==snapshots.at(-1));await settled();await wait(async()=>await height()===expected);assert.equal(await family(),initialFamily);assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).fontWeight),initialWeight);};
   const pixels=async value=>{await input.fill(value+(kind==='html'?'px':''));await input.press('Tab');};
   await page.getByLabel('Style screen scope').selectOption('');await settled();await write(()=>pixels('80'),'80px');
   await page.getByLabel('Style screen scope').selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await write(()=>page.getByRole('button',{name:'Automatic line height',exact:true}).click(),'normal');
   if(kind!=='html'){assert.equal(await input.inputValue(),'');assert.equal(await input.getAttribute('placeholder'),'Automatic');await write(()=>page.getByRole('button',{name:'Reset text overrides',exact:true}).click(),'80px');const automatic=snapshots.pop();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===automatic);await settled();await wait(async()=>await height()==='normal');}
   await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();await wait(async()=>await height()==='80px');await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();await wait(async()=>await height()==='normal');
   await write(()=>pixels('45'),'45px');await write(()=>page.getByRole('button',{name:'Reset line height',exact:true}).click(),'80px');
   while(snapshots.length){const expected=snapshots.pop();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===expected);await settled();}await wait(async()=>await height()===initialHeight);assert.equal(read(),original);
   console.log(engine+' '+kind+': PASS automatic/custom line height, responsive isolation, family/weight retention, reset and exact undo');
  }
  if(process.env.RT_E2E_RELATIVE_SPACING){
   const spacing=()=>app.locator('h1').evaluate(el=>getComputedStyle(el).letterSpacing),initial=await spacing();
   const edit=async(label,value,expected)=>{snapshots.push(read());const input=page.getByLabel(label,{exact:true});await input.fill(value);await input.press('Tab');await wait(()=>read()!==snapshots.at(-1));await settled();await wait(async()=>Math.abs(parseFloat(await spacing())-expected)<.02);};
   await page.getByLabel('Style screen scope').selectOption('');await settled();await edit('Letter spacing (%)','10',3.2);
   assert.match(read(),/0\.1em/);await edit(kind==='html'?'Font size (CSS)':'Font size (px)',kind==='html'?'40px':'40',4);
   await page.getByLabel('Style screen scope').selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await edit('Letter spacing (%)','-5',-2);
   await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();await wait(async()=>Math.abs(parseFloat(await spacing())-4)<.02);await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();await wait(async()=>Math.abs(parseFloat(await spacing())+2)<.02);
   while(snapshots.length){const expected=snapshots.pop();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===expected);await settled();}await wait(async()=>await spacing()===initial);assert.equal(read(),original);
   console.log(engine+' '+kind+': PASS percentage letter spacing scales with font size, negative tablet override, phone isolation and exact undo');
  }
  assert.deepEqual(errors,[]);console.log(engine+' '+kind+': PASS searchable page font catalog, keyboard apply/cancel, no-match preservation, declared and used families, underscore preservation, weight/named-style retention, responsive isolation, reset, preview and exact source undo');
 }finally{if(browser)await browser.close();if(child){child.kill('SIGTERM');await stopped;}if(server){server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));}fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
