'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const kind=process.env.RT_E2E_RENDERER||'html',engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-page-fonts-')),file=path.join(root,kind==='react'?'app/page.jsx':kind==='liquid'?'sections/main.liquid':'index.html'),css='@font-face{font-family:"Page Face";src:local("Arial")} .type-editorial{font-family:Georgia,serif;font-size:32px;font-weight:700}.other-font{font-family:"Studio_Test",serif}.named-font{font-family:"Page Face",serif}';fs.mkdirSync(path.dirname(file),{recursive:true});const body='<main><h1 '+(kind==='react'?'className':'class')+'="type-editorial font-bold md:opacity-90 [&:hover]:opacity-50">Headline</h1><p '+(kind==='react'?'className':'class')+'="other-font">Other text</p><p '+(kind==='react'?'className':'class')+'="named-font">Named text</p></main>',original=kind==='react'?'export default function Page(){return '+body+'}':'<html><head><style>'+css+'</style></head><body>'+(kind==='liquid'&&process.env.RT_E2E_LIQUID_DYNAMIC?body.replace('type-editorial font-bold','type-editorial font-bold {% if alternate %}font-mono{% else %}font-serif{% endif %}'):body)+'</body></html>';fs.writeFileSync(file,original);
 let server,child,stopped,browser,url,logs='';const read=()=>fs.readFileSync(file,'utf8'),wait=async fn=>{for(let i=0;i<400;i++){try{if(await fn())return;}catch(error){if(!/Execution context was destroyed|fetch failed/.test(error.message))throw error;}await new Promise(r=>setTimeout(r,100));}throw Error('Timed out '+logs.slice(-1000));};
 try{
  if(kind==='react'){fs.symlinkSync(path.join(fixture,'node_modules'),path.join(root,'node_modules'),'dir');fs.copyFileSync(path.join(fixture,'postcss.config.mjs'),path.join(root,'postcss.config.mjs'));fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({private:true,dependencies:{next:'16.2.5',react:'19.2.0','react-dom':'19.2.0'}}));fs.writeFileSync(path.join(root,'app/style.css'),'@import "tailwindcss";\n'+css);fs.writeFileSync(path.join(root,'app/layout.jsx'),'import "./style.css";export default function Layout({children}){return <html><body>{children}</body></html>}');child=spawn(process.execPath,[path.resolve(__dirname,'../../bin/retouch.cjs'),'--',process.execPath,path.join(fixture,'node_modules/next/dist/bin/next'),'dev','--webpack','-p','0'],{cwd:root,env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});stopped=new Promise(r=>child.once('exit',r));for(const stream of [child.stdout,child.stderr])stream.on('data',data=>{logs+=data;url=logs.match(/http:\/\/localhost:\d+/)?.[0];});await wait(()=>url);await wait(async()=>{try{return(await fetch(url+'/rt/__api/health')).ok;}catch{return false;}});
  }else if(kind==='liquid'){
   const liquid=require('../../src/adapters/liquid.cjs'),engine=new(require('liquidjs').Liquid)(),{Scanner}=require(path.join(fixture,'node_modules/@tailwindcss/oxide')),{compile}=require('node:module').createRequire(path.join(fixture,'package.json'))('@tailwindcss/node');
   const compiler=await compile('@import "tailwindcss";\n'+css,{base:fixture,onDependency(){}});
   server=require('../../src/server.cjs').startServer({appRoot:root,adapter:liquid,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{try{const source=read(),candidates=new Scanner({}).scanFiles([{content:source,extension:'liquid'}]),styles=compiler.build(candidates),html=await engine.parseAndRender(liquid.stamp(source,file,root).code,{alternate:req.url.includes('alternate=1')});res.setHeader('content-type','text/html');res.end(html.replace('</head>','<style>'+styles+'</style></head>'));}catch(e){res.statusCode=500;res.end(e.stack);}}});await once(server,'listening');url='http://localhost:'+server.address().port;
  }else{server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');url='http://localhost:'+server.address().port;}
  browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[],snapshots=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/rt',{timeout:90000});const app=page.frameLocator('#app');await app.locator('h1').waitFor({timeout:90000});await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).click();const settled=()=>wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true'),family=()=>app.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily);await settled();
  const options=await page.getByLabel('Page font',{exact:true}).locator('option').evaluateAll(els=>els.map(el=>el.value)),custom=options.find(v=>v.includes('Studio_Test'));assert.ok(custom);assert.ok(options.some(v=>v.includes('Page Face')));assert.equal(read(),original);
  await page.getByText('Browse page fonts',{exact:true}).click();const search=page.getByRole('searchbox',{name:'Search page fonts'});await search.fill('NoSuchFamilyZZZ');await wait(async()=>await page.locator('.font-browser [role=status]').getAttribute('data-scanning')==='false');assert.equal(await page.getByRole('group',{name:'Matching fonts'}).getByRole('button').count(),0);assert.ok((await page.getByRole('status').allTextContents()).some(t=>t.includes('No matching fonts')));assert.equal(read(),original);assert.equal(await page.getByLabel('Page font',{exact:true}).inputValue(),await family());await search.press('Escape');assert.equal(await page.locator('.font-browser').getAttribute('open'),null);assert.equal(await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).getAttribute('aria-selected'),'true');
  const choose=async(value,browse=false)=>{snapshots.push(read());if(browse){await page.getByText('Browse page fonts',{exact:true}).click();await search.fill('sTuDiO_test');assert.equal(read(),snapshots.at(-1));const matching=page.getByRole('group',{name:'Matching fonts'}).getByRole('button');assert.equal(await matching.count(),1);if(process.env.RT_E2E_FONT_SEARCH_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_FONT_SEARCH_SCREENSHOT});await search.press('Tab');assert.equal(await matching.evaluate(el=>el===el.ownerDocument.activeElement),true);await page.keyboard.press('Enter');}else await page.getByLabel('Page font',{exact:true}).selectOption(value);await wait(()=>read()!==snapshots.at(-1));await settled();const normalize=s=>s.replace(/[\"']/g,'').replace(/\s*,\s*/g,',');try{await wait(async()=>normalize(await family())===normalize(value));}catch(error){console.log('FONT DIAGNOSTIC',JSON.stringify({source:read(),family:await family(),classes:await app.locator('h1').getAttribute('class')}));throw error;}if(kind==='liquid'&&process.env.RT_E2E_LIQUID_DYNAMIC){const alternate=await browser.newPage({viewport:await app.locator('html').evaluate(el=>({width:el.ownerDocument.defaultView.innerWidth,height:el.ownerDocument.defaultView.innerHeight}))});try{await alternate.goto(url+'/?alternate=1');assert.equal(normalize(await alternate.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily)),normalize(value));assert.equal(await alternate.locator('h1').evaluate(el=>getComputedStyle(el).fontWeight),'700');}finally{await alternate.close();}}};
  await choose('monospace');assert.equal(await family(),'monospace');assert.equal(await app.locator('h1').evaluate(el=>getComputedStyle(el).fontWeight),'700');assert.match(read(),/type-editorial/);if(kind!=='html'){await app.locator('h1').hover();await wait(async()=>await app.locator('h1').evaluate(el=>getComputedStyle(el).opacity)==='0.5');await page.getByRole('button',{name:'Undo',exact:true}).hover();}
  await choose(options.find(v=>v.includes('Page Face')));assert.match(await family(),/Page Face/);
  await choose(options.find(v=>v.includes('Page Face')&&v.includes(',')));assert.match(await family(),/Page Face/);
  await choose(custom,true);assert.match(await family(),/Studio_Test/);assert.doesNotMatch(await family(),/Studio Test/);
  await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();await page.getByLabel('Style screen scope').selectOption(kind==='html'?'min-[768px]:':'md:');await choose('serif');assert.equal(await family(),'serif');await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();assert.match(await family(),/Studio_Test/);await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();
  if(kind!=='html')await wait(async()=>{try{return await page.frameLocator('iframe[title="Typography preview"]').locator('body div').evaluate(el=>getComputedStyle(el).fontFamily)==='serif';}catch(error){if(/Frame was detached/.test(error.message))return false;throw error;}});
  snapshots.push(read());await page.getByRole('button',{name:'Reset font family',exact:true}).click();await wait(()=>read()!==snapshots.at(-1));await settled();await wait(async()=>/Studio_Test/.test(await family()));if(process.env.RT_E2E_FONT_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_FONT_SCREENSHOT});
  while(snapshots.length){const expected=snapshots.pop();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===expected);await settled();}assert.equal(read(),original);await wait(async()=>/Georgia/.test(await family()));assert.deepEqual(errors,[]);console.log(engine+' '+kind+': PASS searchable page font catalog, keyboard apply/cancel, no-match preservation, declared and used families, underscore preservation, weight/named-style retention, responsive isolation, reset, preview and exact source undo');
 }finally{if(browser)await browser.close();if(child){child.kill('SIGTERM');await stopped;}if(server){server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));}fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
