'use strict';
const path=require('node:path'),assert=require('node:assert/strict');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE for Playwright');
const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const browser=await browserType.launch(),page=await browser.newPage({viewport:{width:1000,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.setContent('<input aria-label="Test color" value="#ff000080" style="position:absolute;right:20px;top:300px">');
  await page.addStyleTag({path:path.join(__dirname,'../../shell/shell.css')});
  for(const file of ['inspector.js','palette-values.js','color-styles.js','html-css-values.js','paint-picker.js'])await page.addScriptTag({path:path.join(__dirname,'../../shell',file)});
  await page.evaluate(()=>{window.writes=[];document.querySelector('input').onchange=event=>writes.push(event.target.value);});
  const open=()=>page.evaluate(()=>RetouchPaintPicker.open(document.querySelector('input'))),picker=page.getByRole('dialog'),value=picker.getByLabel('Color value',{exact:true});
  await open();assert.equal(await picker.evaluate(el=>getComputedStyle(el,'::backdrop').backgroundColor),'rgba(0, 0, 0, 0)');const plane=picker.getByRole('slider',{name:'Saturation and brightness',exact:true}),box=await plane.boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);assert.equal(await value.inputValue(),'#80404080');assert.deepEqual(await page.evaluate(()=>writes),[]);
  await plane.press('Shift+ArrowRight');assert.equal(await value.inputValue(),'#80333380');await value.press('Enter');await picker.waitFor({state:'detached'});assert.deepEqual(await page.evaluate(()=>writes),['#80333380']);
  await open();await picker.getByRole('button',{name:'Apply color',exact:true}).click();await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.length),1);
  await open();await value.fill('color(display-p3 1 0.2 0.3 / 0.4)');assert.equal(await plane.isVisible(),false);await picker.getByLabel('Display P3 green',{exact:true}).fill('');await picker.getByLabel('Display P3 green',{exact:true}).pressSequentially('0.6');assert.equal(await picker.getByLabel('Display P3 green',{exact:true}).inputValue(),'0.6');await picker.getByRole('button',{name:'Apply color',exact:true}).click();await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.at(-1)),'color(display-p3 1 0.6 0.3 / 0.4)');
  await page.setViewportSize({width:360,height:600});await open();const rect=await picker.boundingBox();assert.ok(rect.x>=0&&rect.y>=0&&rect.x+rect.width<=360&&rect.y+rect.height<=600);await value.fill('#000');await page.keyboard.press('Escape');await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.length),2);
  await open();await value.fill('#33669980');const alpha=picker.getByLabel('Opacity value (%)',{exact:true});await alpha.fill('12.34');assert.equal(await value.inputValue(),'rgb(51 102 153 / 0.1234)');await plane.press('ArrowRight');assert.ok((await value.inputValue()).endsWith('/ 0.1234)'));assert.equal(await alpha.inputValue(),'12.34');await alpha.fill('120');await picker.getByRole('button',{name:'Apply color',exact:true}).click();assert.ok(await picker.isVisible());await alpha.fill('');await picker.getByRole('button',{name:'Apply color',exact:true}).click();assert.ok(await picker.isVisible());await alpha.fill('50');assert.ok((await value.inputValue()).endsWith('/ 0.5)'));const opacityTrack=picker.getByRole('slider',{name:'Opacity (%)',exact:true});assert.ok((await opacityTrack.evaluate(el=>el.style.backgroundImage)).includes('conic-gradient'));await picker.getByRole('button',{name:'Apply color',exact:true}).click();await picker.waitFor({state:'detached'});assert.ok((await page.evaluate(()=>writes.at(-1))).endsWith('/ 0.5)'));
  await open();await value.fill('#33669980');await alpha.fill('12.34567');const red=picker.getByLabel('Red (0–255)',{exact:true});await red.fill('200');assert.equal(await value.inputValue(),'rgb(200 102 153 / 0.1234567)');assert.equal(await alpha.inputValue(),'12.34567');await red.fill('256');await red.press('Enter');assert.ok(await picker.isVisible());await red.fill('');await picker.getByRole('button',{name:'Apply color',exact:true}).click();assert.ok(await picker.isVisible());await red.fill('200');await red.press('Enter');await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.at(-1)),'rgb(200 102 153 / 0.1234567)');
  await open();await value.fill('#ff000080');const colorModel=picker.getByLabel('Color model',{exact:true});await colorModel.selectOption('hsl');assert.equal(await value.inputValue(),'#ff000080');const hueField=picker.getByLabel('Hue (deg)',{exact:true}),saturation=picker.getByLabel('Saturation (%)',{exact:true}),lightness=picker.getByLabel('Lightness (%)',{exact:true});assert.equal(await hueField.inputValue(),'0');assert.equal(await saturation.inputValue(),'100');assert.equal(await lightness.inputValue(),'50');await hueField.fill('120');assert.equal(await value.inputValue(),'#00ff0080');await value.fill('#ff000080');await saturation.fill('50');assert.equal(await value.inputValue(),'#bf404080');await value.fill('#ff000080');await lightness.fill('25');assert.equal(await value.inputValue(),'#80000080');await value.fill('#fff');assert.equal(await saturation.inputValue(),'0');assert.equal(await lightness.inputValue(),'100');await value.fill('#000');assert.equal(await saturation.inputValue(),'0');assert.equal(await lightness.inputValue(),'0');await value.fill('#ff000080');await alpha.fill('12.34');await hueField.fill('240');assert.equal(await value.inputValue(),'rgb(0 0 255 / 0.1234)');await hueField.fill('361');await picker.getByRole('button',{name:'Apply color',exact:true}).click();assert.ok(await picker.isVisible());await hueField.fill('240');await colorModel.selectOption('rgb');assert.equal(await value.inputValue(),'rgb(0 0 255 / 0.1234)');await picker.getByRole('button',{name:'Apply color',exact:true}).click();await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.at(-1)),'rgb(0 0 255 / 0.1234)');
  await open();const beforeKeys=await page.evaluate(()=>writes.length);await value.fill('#ff0000');await value.dispatchEvent('keydown',{key:'Enter',isComposing:true});assert.ok(await picker.isVisible());await value.press('Control+Enter');assert.ok(await picker.isVisible());await value.press('Shift+Enter');assert.ok(await picker.isVisible());assert.equal(await page.evaluate(()=>writes.length),beforeKeys);await value.press('Enter');await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.length),beforeKeys+1);assert.equal(await page.evaluate(()=>writes.at(-1)),'#ff0000');
  await page.evaluate(()=>document.querySelector('input').value='hsl(120deg 100% 50% / 12.34567%)');const beforeLiteral=await page.evaluate(()=>writes.length);await open();assert.ok(await plane.isVisible());assert.equal(await picker.getByLabel('Green (0–255)',{exact:true}).inputValue(),'255');assert.equal(await alpha.inputValue(),'12.34567');await value.press('Enter');await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.length),beforeLiteral);assert.equal(await page.getByLabel('Test color',{exact:true}).inputValue(),'hsl(120deg 100% 50% / 12.34567%)');await open();await picker.getByLabel('Red (0–255)',{exact:true}).fill('64');await value.press('Enter');await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>writes.at(-1)),'rgb(64 255 0 / 0.1234567)');
  await open();await value.fill('rebeccapurple');assert.ok(await plane.isVisible());assert.equal(await picker.getByLabel('Red (0–255)',{exact:true}).inputValue(),'102');assert.equal(await picker.getByLabel('Green (0–255)',{exact:true}).inputValue(),'51');assert.equal(await picker.getByLabel('Blue (0–255)',{exact:true}).inputValue(),'153');await value.fill('hsla(-240, 100%, 50%, 0.1234)');assert.equal(await alpha.inputValue(),'12.34');assert.equal(await picker.getByLabel('Green (0–255)',{exact:true}).inputValue(),'255');for(const contextual of ['currentColor','var(--theme-color)','CanvasText']){await value.fill(contextual);assert.equal(await plane.isVisible(),false);}await page.keyboard.press('Escape');await picker.waitFor({state:'detached'});
  const cleanup=await page.evaluate(()=>{
   const el=document.createElement('div'),group=document.createElement('fieldset'),preview=document.createElement('div');group.append(preview);document.body.append(el,group);const gradient={type:'linear',angle:90,stops:[{color:'#ff0000',position:0},{color:'#0000ff',position:100}]},other={...gradient,angle:45},start=()=>RetouchPaintPicker.gradientPreview({el,group,preview,gradient,gradients:[gradient,other],index:0,stopIndex:0});
   let session=start();session.update('#00ff00');const layers=RetouchHTMLCSSValues.parseGradients(el.style.backgroundImage);session.restore();const absent=el.getAttribute('style')===null;
   el.style.cssText='background-image:linear-gradient(red, blue) !important;width:10px';const image=el.style.backgroundImage;session=start();session.update('#00ff00');el.style.width='20px';session.restore();const concurrent=el.style.width==='20px'&&el.style.backgroundImage===image&&el.style.getPropertyPriority('background-image')==='important';
   session=start();session.update('#00ff00');el.style.setProperty('background-image','none');session.restore();const external=el.style.backgroundImage==='none';
   el.style.cssText='box-shadow:1px 2px 3px red !important;height:10px';const originalShadow=el.style.boxShadow,shadows=RetouchHTMLCSSValues.parseShadows(getComputedStyle(el).boxShadow),shadowSession=()=>RetouchPaintPicker.shadowPreview({el,group,shadows,index:0});session=shadowSession();session.update('#00ff00');el.style.height='20px';session.restore();const shadowConcurrent=el.style.boxShadow===originalShadow&&el.style.getPropertyPriority('box-shadow')==='important'&&el.style.height==='20px';session=shadowSession();session.update('#00ff00');el.style.boxShadow='none';session.restore();const shadowExternal=el.style.boxShadow==='none';
   el.style.cssText='border-color:red green blue yellow !important;height:10px';const sides=['top','right','bottom','left'].map(side=>'border-'+side+'-color'),colors=sides.map(name=>el.style.getPropertyValue(name));session=RetouchPaintPicker.propertyPreview({el,input:group,property:'border-color'});session.update('#abcdef');el.style.height='20px';el.style.setProperty('border-left-color','purple');session.restore();const solidConcurrent=sides.slice(0,3).every((name,i)=>el.style.getPropertyValue(name)===colors[i]&&el.style.getPropertyPriority(name)==='important')&&el.style.borderLeftColor==='purple'&&el.style.height==='20px';
   el.removeAttribute('style');document.querySelector('input').retouchPaintPreview=start;window.previewElement=el;return {absent,concurrent,external,shadowConcurrent,shadowExternal,solidConcurrent,layers:layers.length,neighbor:layers[1].angle};
  });assert.deepEqual(cleanup,{absent:true,concurrent:true,external:true,shadowConcurrent:true,shadowExternal:true,solidConcurrent:true,layers:2,neighbor:45});
  await open();await value.fill('#00ff00');await page.evaluate(()=>document.querySelector('input').remove());await picker.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>previewElement.getAttribute('style')),null);
  assert.deepEqual(errors,[]);console.log(engine+': PASS visual color pointer and keyboard HSV, alpha, draft cancellation, no-op apply, Display P3 channels, narrow-window bounds, live-preview cleanup and concurrent style preservation');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
