'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE for Playwright');
const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-presentation-')),file=path.join(root,'index.html');
 const original=`<!doctype html><html><head><title>Preview shop</title><style>body{min-height:1800px;font:16px system-ui;padding:24px;background:#fff;color:#222}button,input,a{display:block;margin:20px 0;padding:12px}h1{font-size:32px}</style></head><body><h1>Preview shop</h1><input aria-label="Your name" placeholder="Your name"><button id="counter" onclick="this.textContent=String(Number(this.textContent)+1)">0</button><a href="/next.html">Next page</a><script>document.addEventListener('keydown',e=>{if(e.key==='Escape'&&window.keepEscape)e.preventDefault()})</script></body></html>`;
 fs.writeFileSync(file,original);fs.writeFileSync(path.join(root,'next.html'),'<!doctype html><title>Next page</title><h1>Next page</h1>');
 const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await browserType.launch(),page=await browser.newPage({viewport:{width:1500,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const app=page.frameLocator('#app'),read=()=>fs.readFileSync(file,'utf8');
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy);
 const dimensions=()=>page.locator('#app').evaluate(el=>[el.contentWindow.innerWidth,el.contentWindow.innerHeight]);
 const canvas=()=>page.evaluate(()=>({zoom:document.getElementById('canvasZoom').value,left:document.getElementById('frameWrap').scrollLeft,top:document.getElementById('frameWrap').scrollTop}));
 const open=async()=>{await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active&&document.activeElement.id==='exitPresentation');};
 const closed=()=>page.waitForFunction(()=>!RetouchPresentation.active&&document.activeElement.id==='presentBtn');
 const retain=()=>page.evaluate(()=>{window.savedDocument=document.getElementById('app').contentDocument;window.savedInput=savedDocument.querySelector('input');});
 const retained=()=>page.evaluate(()=>savedDocument===document.getElementById('app').contentDocument&&savedInput===savedDocument.querySelector('input'));
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await page.getByRole('treeitem',{name:'h1 · Preview shop',exact:true}).click();await settle();
  let releaseWrite;const heldWrite=new Promise(resolve=>releaseWrite=resolve);let sawWrite;const writeStarted=new Promise(resolve=>sawWrite=resolve);
  await page.route('**/rt/__api/op',async route=>{sawWrite();await heldWrite;await route.continue();});
  await page.getByRole('button',{name:'Align text center',exact:true}).click();await writeStarted;
  await page.getByRole('button',{name:'Present',exact:true}).click();assert.equal(await page.evaluate(()=>RetouchPresentation.active),false);assert.match(await page.locator('#toasts').textContent(),/Finish the current edit/);
  releaseWrite();await settle();await page.unroute('**/rt/__api/op');await page.waitForFunction(()=>getComputedStyle(document.getElementById('app').contentDocument.querySelector('h1')).textAlign==='center');
  const edited=read();assert.notEqual(edited,original);
  await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await page.waitForFunction(()=>document.getElementById('app').contentWindow.innerWidth===390);
  await page.getByLabel('Canvas zoom (%)',{exact:true}).fill('150');await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Tab');
  await page.getByRole('button',{name:'Compare screens',exact:true}).click();
  await page.frameLocator('iframe[title="Phone comparison preview"]').locator('body').waitFor();
  await page.frameLocator('iframe[title="Phone comparison preview"]').locator('body').evaluate(()=>{window.savedComparison=document;document.querySelector('input').value='Comparison draft';});
  await page.locator('#frameWrap').evaluate(el=>el.scrollTop=160);const before=await canvas();await retain();
  await open();assert.deepEqual(await dimensions(),[390,844]);assert.equal(await retained(),true);
  for(const selector of ['#toolbar','#screenToolbar','#layersPanel','#panel','.design-tool-dock','#overlayLayer','#screenComparisons'])assert.equal(await page.locator(selector).isVisible(),false,selector+' hidden');
  await app.getByLabel('Your name').fill('Kept across presentation');await app.locator('#counter').click();assert.equal(await app.locator('#counter').textContent(),'1');
  await page.locator('#exitPresentation').focus();await page.keyboard.press('Control+z');await page.keyboard.press('Meta+z');assert.equal(read(),edited,'presentation does not undo source');
  // WebKit may apply native form undo even after focus moves to the toolbar.
  const inputBeforeExit=await app.getByLabel('Your name').inputValue();
  await app.locator('#counter').hover();await page.mouse.wheel(0,240);await page.waitForFunction(()=>document.getElementById('app').contentWindow.scrollY>0);const pageScroll=await page.locator('#app').evaluate(el=>el.contentWindow.scrollY);
  await page.screenshot({path:'/tmp/retouch-presentation-'+engine+'.png'});
  await page.getByRole('button',{name:'Back to editor',exact:false}).click();await closed();assert.equal(await retained(),true);assert.equal(await app.getByLabel('Your name').inputValue(),inputBeforeExit);assert.equal(await app.locator('#counter').textContent(),'1');assert.deepEqual(await canvas(),before);assert.equal(await page.locator('#app').evaluate(el=>el.contentWindow.scrollY),pageScroll,'exit retains native page scrolling');
  assert.equal(await page.frameLocator('iframe[title="Phone comparison preview"]').locator('body').evaluate(()=>window.savedComparison===document),true);assert.equal(await page.frameLocator('iframe[title="Phone comparison preview"]').getByLabel('Your name').inputValue(),'Comparison draft');assert.equal(await page.locator('#modeBtn').textContent(),'Edit mode');
  await open();await app.getByLabel('Your name').evaluate(el=>{el.ownerDocument.defaultView.keepEscape=true;});await app.getByLabel('Your name').press('Escape');assert.equal(await page.evaluate(()=>RetouchPresentation.active),true,'site can consume Escape');await app.getByLabel('Your name').evaluate(el=>{el.ownerDocument.defaultView.keepEscape=false;});await app.getByLabel('Your name').press('Escape');await closed();
  await page.locator('#modeBtn').click();await page.getByLabel('Screen size',{exact:true}).selectOption('fluid');await page.waitForFunction(()=>RetouchScreens.get()===null);await page.waitForTimeout(100);const fluid=await dimensions();await retain();await open();assert.deepEqual(await dimensions(),fluid);
  await page.setViewportSize({width:1100,height:850});assert.deepEqual(await dimensions(),fluid);assert.equal(await retained(),true);
  await page.getByRole('button',{name:'Back to editor',exact:false}).click();await closed();assert.equal(await page.locator('#modeBtn').textContent(),'Interact mode');assert.notDeepEqual(await dimensions(),fluid,'fluid sizing resumes');
  await page.setViewportSize({width:1500,height:1100});await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await open();await app.getByRole('link',{name:'Next page'}).click();await app.getByRole('heading',{name:'Next page'}).waitFor();await page.waitForFunction(()=>document.getElementById('presentationTitle').textContent==='Next page');
  await page.getByRole('button',{name:'Restart presentation',exact:true}).click();await app.getByRole('heading',{name:'Preview shop'}).waitFor();assert.equal(await app.locator('#counter').textContent(),'0');assert.equal(await app.getByLabel('Your name').inputValue(),'');
  await app.getByRole('link',{name:'Next page'}).click();await app.getByRole('heading',{name:'Next page'}).waitFor();await page.getByRole('button',{name:'Back to editor',exact:false}).click();await closed();assert.equal(await app.getByRole('heading',{name:'Next page'}).isVisible(),true,'exit retains current route');
  assert.equal(read(),edited,'presentation never changes source');
  await page.goto('http://localhost:'+server.address().port+'/rt');await page.getByRole('treeitem',{name:'h1 · Preview shop',exact:true}).click();await settle();
  if(await page.locator('#modeBtn').textContent()!=='Edit mode')await page.locator('#modeBtn').click();
  await page.locator('#textInlineEdit').click();await app.locator('h1').fill('Presented text');await open();assert.ok(read().includes('Presented text'),'Present commits inline text before entering');assert.equal(await app.locator('h1').textContent(),'Presented text');
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Fit preview',exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'presentation toolbar fits phone width');
  await page.screenshot({path:'/tmp/retouch-presentation-mobile-'+engine+'.png'});
  await page.setViewportSize({width:320,height:700});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'small toolbar wraps');await page.getByRole('button',{name:'Back to editor',exact:false}).click();await closed();assert.deepEqual(errors,[]);console.log('presentation '+engine+' passed');
 }catch(error){console.error(await page.evaluate(()=>({active:window.RetouchPresentation?.active,toasts:document.getElementById('toasts').textContent,focus:document.activeElement.id})),errors);throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
