'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',kind=process.env.RT_PROTOTYPE_RENDERER||'html';
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-motion-'))),extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind],framework=['react','vue'].includes(kind),types=['dissolve','move-in','move-out','push','slide-in','slide-out','instant'];
 const attr=item=>'data-rt-prototype="'+JSON.stringify([item]).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/\{/g,'&#123;').replace(/\}/g,'&#125;')+'"',motion=type=>type==='instant'?{type}:{type,duration:1000,easing:'linear',...(type==='dissolve'?{}:{direction:'right'})};
 const button=(id,label,action,extra={})=>'<button id="'+id+'" '+attr({trigger:'click',action,...extra})+'>'+label+'</button>';
 const art=(color,content)=>'<div id="art" '+(kind==='react'?'style={{position:"fixed",inset:0,background:"'+color+'"}}':'style="position:fixed;inset:0;background:'+color+'"')+'>'+content+'</div>';
 const shortcut=(code,extra={})=>({code,ctrl:false,alt:false,shift:false,meta:false,...extra});
 const pages={index:'<button id="open">Hotspot</button><input aria-label="Draft"/><div contenteditable="true" role="textbox" aria-label="Rich draft"></div><button id="native">Native</button>',next:button('escape','Close','close-overlay',{trigger:'keyboard',shortcut:shortcut('Escape')}),alt:'<h1>Destination</h1>'+button('back','Back','back',{trigger:'keyboard',shortcut:shortcut('KeyB')})};
 for(const [name,content]of Object.entries(pages)){const source=kind==='react'?'export default function App(){return <main>'+content+'</main>}':kind==='vue'?'<script setup>const ready=true;</script><template><main>'+content+'</main></template>':'<!doctype html><title>'+name+'</title>'+content;fs.writeFileSync(path.join(root,name+'.'+extension),source);}
 const file=path.join(root,'index.'+extension),adapter=kind==='liquid'?require('../../src/adapters/liquid.cjs'):null,renderer=adapter?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):adapter?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index':path.basename(url.pathname,'.html'),target=path.join(root,name+'.liquid');if(!/^[a-z]+$/.test(name)||!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1400,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert),phase=value=>page.waitForFunction(value=>RetouchPrototypeOverlays.phase===value,value),overlay=()=>page.frameLocator('.prototype-overlay-frame').last(),read=()=>fs.readFileSync(file,'utf8');
 const input=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');await settle();};
 const pause=()=>page.evaluate(()=>{const animations=document.getAnimations().filter(a=>a.effect?.target?.closest('.prototype-overlay-surface'));for(const a of animations){a.pause();a.currentTime=500;}return animations.map(a=>({duration:a.effect.getTiming().duration,easing:a.effect.getTiming().easing}));});
 const finish=()=>page.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.closest('.prototype-overlay-surface')).forEach(a=>a.finish()));
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settle();await input('Destination URL 1','/next.html');await page.getByLabel('Action 1',{exact:true}).selectOption('open-overlay');await settle();await page.getByLabel('Trigger 1',{exact:true}).selectOption('keyboard');await settle();
  const before=read();await page.getByRole('button',{name:'Record shortcut 1',exact:true}).click();await page.keyboard.press('Shift+KeyK');await settle();const recorded=read();assert.notEqual(recorded,before);assert.equal(await page.getByLabel('shift modifier 1',{exact:true}).isChecked(),true);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),before);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),recorded);
  await page.getByRole('button',{name:'Record shortcut 1',exact:true}).click();await page.keyboard.press('Escape');assert.equal(read(),recorded);assert.equal(await page.getByRole('button',{name:'Record shortcut 1',exact:true}).getAttribute('aria-pressed'),'false');
  await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settle();await page.getByLabel('Trigger 2',{exact:true}).selectOption('keyboard');await settle();await page.getByRole('button',{name:'Record shortcut 2',exact:true}).click();await page.keyboard.press('KeyL');await settle();await input('Destination URL 2','/alt.html');const all=read();
  await page.getByRole('button',{name:'Record shortcut 2',exact:true}).click();await page.keyboard.press('Shift+KeyK');await page.getByText('Use each trigger or keyboard shortcut only once per layer.',{exact:true}).waitFor();assert.equal(read(),all,'duplicate does not write source');await page.getByRole('button',{name:'Record shortcut 2',exact:true}).click();await page.keyboard.press('KeyL');await settle();
  await page.locator('#prototypePanel').screenshot({path:'/tmp/retouch-keys-'+kind+'-'+engine+'.png'});
  await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active&&document.activeElement.id==='exitPresentation');await app.getByLabel('Draft',{exact:true}).fill('');await app.getByLabel('Draft',{exact:true}).press('KeyL');assert.equal(await app.getByLabel('Draft',{exact:true}).inputValue(),'l');assert.equal(await app.locator('#open').count(),1);await app.getByRole('textbox',{name:'Rich draft'}).press('KeyL');assert.equal(await app.getByRole('textbox',{name:'Rich draft'}).textContent(),'l');
  await app.locator('#native').evaluate(el=>{window.nativeKeys=0;document.addEventListener('keydown',e=>{if(e.code==='KeyJ')window.nativeKeys++;});});await app.locator('#native').press('KeyJ');assert.equal(await app.locator('#native').evaluate(()=>window.nativeKeys),1);
  await app.locator('#native').press('KeyK');assert.equal(await page.locator('.prototype-overlay-frame').count(),0,'modifiers must match exactly');await app.locator('#native').press('Shift+KeyK');await page.waitForFunction(()=>RetouchPrototypeOverlays.count===1&&RetouchPrototypeOverlays.phase==='idle');await overlay().locator('#escape').press('KeyL');assert.equal(await overlay().locator('#escape').count(),1,'covered base shortcuts are inactive');await overlay().locator('#escape').press('Escape');await page.waitForFunction(()=>RetouchPrototypeOverlays.count===0);assert.equal(await page.evaluate(()=>RetouchPresentation.active),true,'authored Escape takes priority over exiting');
  await app.locator('#native').press('KeyL');await app.getByRole('heading',{name:'Destination'}).waitFor();await app.locator('#back').press('KeyB');await app.locator('#open').waitFor();
  // Delayed-mounted shortcuts and identical source copies work without duplicate actions.
  await app.locator('#open').evaluate(el=>{const copy=el.cloneNode(true);copy.id='copy';el.after(copy);});await app.locator('#native').press('Shift+KeyK');await page.waitForFunction(()=>RetouchPrototypeOverlays.count===1&&RetouchPrototypeOverlays.phase==='idle');await overlay().locator('#escape').press('Escape');await page.waitForFunction(()=>RetouchPrototypeOverlays.count===0);
  await app.locator('#copy').evaluate(el=>{el.setAttribute('data-rt-prototype',JSON.stringify([{trigger:'keyboard',shortcut:{code:'KeyK',shift:true},action:'navigate',destination:'/alt.html'}]));});await app.locator('#native').press('Shift+KeyK');await page.locator('#toasts').getByText('This shortcut has multiple destinations. Focus the intended hotspot to choose one.',{exact:true}).waitFor();assert.equal(await page.locator('.prototype-overlay-frame').count(),0);await app.locator('#copy').press('Shift+KeyK');await app.getByRole('heading',{name:'Destination'}).waitFor();await page.locator('#exitPresentation').click();assert.equal(read(),all);
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();assert.equal(await page.getByLabel('Key 1',{exact:true}).inputValue(),'KeyK');assert.equal(await page.getByLabel('Key 2',{exact:true}).inputValue(),'KeyL');assert.deepEqual(errors,[]);console.log(engine+' '+kind+': shortcut recording, multiple combinations, exact undo, duplicate guards, native typing, overlay scope, Escape and reload passed');
 }catch(error){console.error(await page.locator('#toasts').textContent().catch(()=>''),errors);throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
