'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',kind=process.env.RT_PROTOTYPE_RENDERER||'html';
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-motion-'))),extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind],framework=['react','vue'].includes(kind),types=['dissolve','move-in','move-out','push','slide-in','slide-out','instant'];
 const attr=item=>'data-rt-prototype="'+JSON.stringify([item]).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/\{/g,'&#123;').replace(/\}/g,'&#125;')+'"',motion=type=>type==='instant'?{type}:{type,duration:1000,easing:'linear',...(type==='dissolve'?{}:{direction:'right'})};
 const button=(id,label,action,extra={})=>'<button id="'+id+'" '+attr({trigger:'click',action,...extra})+'>'+label+'</button>';
 const art=(color,content)=>'<div id="art" '+(kind==='react'?'style={{position:"fixed",inset:0,background:"'+color+'"}}':'style="position:fixed;inset:0;background:'+color+'"')+'>'+content+'</div>';
 const pages={index:'<button id="open">Open</button><input aria-label="Draft"/>'+['dissolve','slide-in'].map(type=>button('open-'+type,'Open '+type,'open-overlay',{destination:'/next.html',transition:motion(type)})).join(''),next:art('rgb(255,0,0)',types.map(type=>button(type,type,'swap-overlay',{destination:'/alt.html',transition:motion(type)})).join('')),alt:art('rgb(0,0,255)',button('close','Close','close-overlay',{transition:motion('move-out')})+['dissolve','slide-out'].map(type=>button('close-'+type,'Close '+type,'close-overlay',{transition:motion(type)})).join(''))};
 for(const [name,content]of Object.entries(pages)){const source=kind==='react'?'export default function App(){return <main>'+content+'</main>}':kind==='vue'?'<script setup>const ready=true;</script><template><main>'+content+'</main></template>':'<!doctype html><title>'+name+'</title>'+content;fs.writeFileSync(path.join(root,name+'.'+extension),source);}
 const file=path.join(root,'index.'+extension),adapter=kind==='liquid'?require('../../src/adapters/liquid.cjs'):null,renderer=adapter?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):adapter?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index':path.basename(url.pathname,'.html'),target=path.join(root,name+'.liquid');if(!/^[a-z]+$/.test(name)||!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1400,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert),phase=value=>page.waitForFunction(value=>RetouchPrototypeOverlays.phase===value,value),overlay=()=>page.frameLocator('.prototype-overlay-frame').last(),read=()=>fs.readFileSync(file,'utf8');
 const input=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');await settle();};
 const pause=()=>page.evaluate(()=>{const animations=document.getAnimations().filter(a=>a.effect?.target?.closest('.prototype-overlay-surface'));for(const a of animations){a.pause();a.currentTime=500;}return animations.map(a=>({duration:a.effect.getTiming().duration,easing:a.effect.getTiming().easing}));});
 const finish=()=>page.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.closest('.prototype-overlay-surface')).forEach(a=>a.finish()));
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settle();await input('Destination URL 1','/next.html');await page.getByLabel('Action 1',{exact:true}).selectOption('open-overlay');await settle();await page.getByLabel('Animation 1',{exact:true}).selectOption('move-in');await settle();await input('Duration (ms) 1','1000');
  await page.getByLabel('Easing 1',{exact:true}).selectOption('custom');await settle();
  assert.equal(await page.getByLabel('X2 1',{exact:true}).inputValue(),'0.58','custom curve inherits selected preset');
  const preset=read();await input('Y2 1','1.5');const overshoot=read();assert.notEqual(overshoot,preset);
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),preset);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),overshoot);
  const handle=()=>page.getByRole('button',{name:'Bézier handle 1 1',exact:true});await handle().focus();await page.keyboard.down('ArrowRight');await page.keyboard.down('ArrowRight');await page.keyboard.down('ArrowRight');assert.equal(read(),overshoot,'held key only previews until release');await page.keyboard.up('ArrowRight');await settle();const keyed=read();assert.notEqual(keyed,overshoot);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),overshoot,'one undo removes entire held key gesture');await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),keyed);
  await handle().focus();await page.keyboard.down('ArrowUp');await page.keyboard.press('Escape');await page.keyboard.up('ArrowUp');await settle();assert.equal(read(),keyed,'Escape cancels keyboard preview');
  let rect=await handle().boundingBox();await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+45,rect.y-25,{steps:6});assert.equal(read(),keyed,'drag updates graph without intermediate history');await page.mouse.up();await settle();const dragged=read();assert.notEqual(dragged,keyed);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),keyed);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),dragged);
  rect=await handle().boundingBox();await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+20,rect.y+20);await page.keyboard.press('Escape');await page.mouse.up();await settle();assert.equal(read(),dragged,'Escape cancels pointer preview');
  await page.getByLabel('X1 1',{exact:true}).fill('2');await page.getByLabel('X1 1',{exact:true}).press('Tab');assert.equal(read(),dragged);assert.equal(await page.getByLabel('X1 1',{exact:true}).evaluate(el=>el.validity.valid),false);await input('X1 1','0.25');await input('Y1 1','0');await input('X2 1','0.75');await input('Y2 1','1');const final=read();
  await page.getByRole('button',{name:'Preview easing 1',exact:true}).click();const preview=await page.locator('.curve-preview>span').evaluate(el=>{const a=el.getAnimations()[0];a.pause();a.currentTime=250;return {easing:a.effect.getTiming().easing};});assert.equal(preview.easing,'cubic-bezier(0.25, 0, 0.75, 1)');
  await page.locator('#prototypePanel').screenshot({path:'/tmp/retouch-curve-'+kind+'-'+engine+'.png'});
  await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active);await app.locator('#open').click();await phase('animating');
  const actual=await page.evaluate(()=>{const card=document.querySelector('.prototype-overlay-card'),a=card.getAnimations()[0];a.pause();a.currentTime=250;return {easing:a.effect.getTiming().easing,duration:a.effect.getTiming().duration,progress:a.effect.getComputedTiming().progress,translate:getComputedStyle(card).translate,distance:document.getElementById('siteStage').clientWidth-card.offsetLeft};});assert.equal(actual.easing,'cubic-bezier(0.25, 0, 0.75, 1)');assert.equal(actual.duration,1000);assert.ok(actual.progress>.17&&actual.progress<.19,'nonlinear quarter-time progress '+actual.progress);assert.ok(Math.abs(parseFloat(actual.translate)/actual.distance-(1-actual.progress))<.002,'rendered position follows curve');await finish();await phase('idle');await page.locator('#exitPresentation').click();assert.equal(read(),final);
  await input('Y2 1','1.5');const bounce=read();await page.getByRole('button',{name:'Present',exact:true}).click();await app.locator('#open').click();await phase('animating');const beyond=await page.evaluate(()=>{const card=document.querySelector('.prototype-overlay-card'),a=card.getAnimations()[0];a.pause();a.currentTime=750;return {progress:a.effect.getComputedTiming().progress,translate:parseFloat(getComputedStyle(card).translate)};});assert.ok(beyond.progress>1&&beyond.translate<0,'overshoot moves past final position');await finish();await phase('idle');await page.locator('#exitPresentation').click();assert.equal(read(),bounce);
  await page.getByRole('button',{name:'Reset easing 1',exact:true}).click();await settle();assert.equal(await page.getByLabel('Y2 1',{exact:true}).inputValue(),'1');await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),bounce);
  await page.reload();await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();assert.equal(await page.getByLabel('Y2 1',{exact:true}).inputValue(),'1.5','custom easing survives reloading source');
  assert.deepEqual(errors,[]);console.log(engine+' '+kind+': custom curve authoring, numeric validation, pointer and held-key grouped undo, Escape, preview and nonlinear playback passed');
 }catch(error){console.error(await page.locator('#toasts').textContent(),errors);throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
