'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',kind=process.env.RT_PROTOTYPE_RENDERER||'html';
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-details-'))),extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind],framework=['react','vue'].includes(kind);
 const attr=item=>'data-rt-prototype="'+JSON.stringify([item]).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/\{/g,'&#123;').replace(/\}/g,'&#125;')+'"';
 const button=(id,label,action,extra={})=>'<button id="'+id+'" '+attr({trigger:'click',action,...extra})+'>'+label+'</button>';
 const pages={index:button('open','Layer','navigate',{destination:'/next.html'})+'<button id="other">Other layer</button>',next:'<h1>Next</h1>',alt:'<h1>Alt</h1>'};
 for(const [name,content]of Object.entries(pages)){const source=kind==='react'?'export default function App(){return <main>'+content+'</main>}':kind==='vue'?'<script setup>const ready=true;</script><template><main>'+content+'</main></template>':'<!doctype html><title>'+name+'</title>'+content;fs.writeFileSync(path.join(root,name+'.'+extension),source);}
 const file=path.join(root,'index.'+extension),adapter=kind==='liquid'?require('../../src/adapters/liquid.cjs'):null,renderer=adapter?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):adapter?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index':path.basename(url.pathname,'.html'),target=path.join(root,name+'.liquid');if(!/^[a-z]+$/.test(name)||!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1400,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert),read=()=>fs.readFileSync(file,'utf8');
 const input=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');await settle();};
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByLabel('Trigger 1',{exact:true}).waitFor();assert.equal(await page.locator('.prototype-details:popover-open').count(),1);
  const initial=read();await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settle();assert.equal(await page.locator('.prototype-connection-row').count(),2);assert.equal(await page.locator('.prototype-details:popover-open').count(),1);assert.equal(await page.getByRole('button',{name:'Edit interaction 2',exact:true}).getAttribute('aria-expanded'),'true');const before=read();await input('Destination URL 2','/next.html?changed=1');const edited=read();assert.notEqual(edited,before);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),before);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),edited);
  await page.getByLabel('Trigger 2',{exact:true}).focus();await page.keyboard.press('Escape');assert.equal(await page.locator('.prototype-details:popover-open').count(),0);assert.equal(await page.getByRole('button',{name:'Edit interaction 2',exact:true}).evaluate(el=>el===document.activeElement),true);assert.equal(read(),edited,'closing details does not write source');
  await page.getByRole('button',{name:'Edit interaction 1',exact:true}).press('Enter');assert.equal(await page.locator('.prototype-details:popover-open').count(),1);assert.equal(await page.getByLabel('Destination URL 1',{exact:true}).inputValue(),'/next.html');
  const floating=()=>page.locator('.prototype-details:popover-open'),grip=()=>floating().getByLabel('Move interaction details',{exact:true}),box=()=>floating().boundingBox();
  const anchored=await box();let header=await grip().boundingBox();await page.mouse.move(header.x+header.width-60,header.y+header.height/2);await page.mouse.down();await page.mouse.move(header.x+header.width-240,header.y+header.height/2+80,{steps:5});await page.mouse.up();let moved=await box();assert.ok(Math.abs(moved.x-anchored.x+180)<2&&Math.abs(moved.y-anchored.y-80)<2,'header drag moves details');assert.equal(read(),edited,'moving details does not edit source');
  await input('Destination URL 1','/next.html?move=1');let retained=await box();assert.ok(Math.abs(retained.x-moved.x)<2&&Math.abs(retained.y-moved.y)<2,'source save keeps the moved position');await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),edited);retained=await box();assert.ok(Math.abs(retained.x-moved.x)<2&&Math.abs(retained.y-moved.y)<2,'undo keeps panel position');
  await grip().focus();await page.keyboard.press('Shift+ArrowLeft');await page.keyboard.press('ArrowDown');let keyed=await box();assert.ok(Math.abs(keyed.x-moved.x+10)<2&&Math.abs(keyed.y-moved.y-1)<2,'keyboard moves the panel');await page.keyboard.down('ArrowRight');await page.keyboard.press('Escape');await page.keyboard.up('ArrowRight');let cancelled=await box();assert.ok(Math.abs(cancelled.x-keyed.x)<2,'Escape cancels held-key movement without closing');
  header=await grip().boundingBox();await page.mouse.move(header.x+header.width-60,header.y+header.height/2);await page.mouse.down();await page.mouse.move(header.x+header.width+20,header.y+header.height/2+50);await page.keyboard.press('Escape');await page.mouse.up();cancelled=await box();assert.ok(Math.abs(cancelled.x-keyed.x)<2&&Math.abs(cancelled.y-keyed.y)<2,'Escape cancels dragging without closing');
  await grip().press('Home');let reset=await box();assert.ok(Math.abs(reset.x-anchored.x)<2&&Math.abs(reset.y-anchored.y)<2,'Home restores anchoring');assert.equal(read(),edited);
  await page.screenshot({path:'/tmp/retouch-details-'+kind+'-'+engine+'-desktop.png'});
  header=await grip().boundingBox();await page.mouse.move(header.x+header.width-60,header.y+header.height/2);await page.mouse.down();await page.mouse.move(2000,1600);await page.mouse.up();const edge=await box(),dock=await page.locator('.design-tool-dock').boundingBox();assert.ok(edge.x+edge.width<=1389&&edge.y+edge.height<=dock.y-7,'dragging stays inside the viewport above the dock');
  for(const size of [{width:800,height:640},{width:390,height:844}]){await page.setViewportSize(size);await page.waitForTimeout(60);const box=await page.locator('.prototype-details:popover-open').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=size.width+1&&box.y+box.height<=size.height+1,'details fit '+JSON.stringify({size,box}));}
  await page.screenshot({path:'/tmp/retouch-details-'+kind+'-'+engine+'-phone.png'});await page.getByRole('button',{name:'Close interaction details',exact:true}).click();assert.equal(await page.locator('.prototype-details:popover-open').count(),0);await page.setViewportSize({width:1400,height:1000});await page.getByRole('button',{name:'Edit interaction 1',exact:true}).click();await page.getByRole('tab',{name:'Design',exact:true}).click();assert.equal(await page.locator('.prototype-details:popover-open').count(),0);await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByLabel('Trigger 1',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active);assert.equal(await page.locator('.prototype-details:popover-open').count(),0,'editing popover hides in presentation');await page.locator('#exitPresentation').click();await page.getByLabel('Trigger 1',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Remove interaction 1',exact:true}).click();await settle();await page.waitForFunction(()=>document.querySelectorAll('.prototype-connection-row').length===1);assert.equal(await page.locator('.prototype-connection-row').count(),1);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),edited);assert.notEqual(edited,initial);
  await page.getByLabel('Action 1',{exact:true}).selectOption('open-overlay');await settle();await page.getByLabel('Animation 1',{exact:true}).selectOption('move-in');await settle();await page.getByLabel('Easing 1',{exact:true}).selectOption('custom');await settle();await page.setViewportSize({width:800,height:640});await page.waitForFunction(()=>(()=>{const el=document.querySelector('.prototype-details:popover-open'),rect=el?.getBoundingClientRect();return rect?.height>0&&rect.bottom<=innerHeight&&el.scrollHeight>el.clientHeight;})());const scrollHandle=await page.waitForFunction(()=>{const el=document.querySelector('.prototype-details:popover-open');if(!el||el.inert)return false;el.scrollTop=el.scrollHeight;return el.scrollTop||false;});const scrolled=await scrollHandle.jsonValue();assert.ok(scrolled>0,JSON.stringify(await page.locator('.prototype-details:popover-open').evaluate(el=>({height:el.clientHeight,scrollHeight:el.scrollHeight,style:el.style.cssText,rect:el.getBoundingClientRect().toJSON(),text:el.textContent}))));await page.getByLabel('Direction 1',{exact:true}).selectOption('left');await settle();await page.waitForFunction(expected=>{const el=document.querySelector('.prototype-details:popover-open');return el&&!el.inert&&Math.abs(el.scrollTop-expected)<3;},scrolled);const afterScroll=await page.evaluate(()=>RetouchPrototypeDetails.snapshot().scroll);assert.ok(Math.abs(afterScroll-scrolled)<3,'source edit preserves details scroll '+JSON.stringify({scrolled,afterScroll,view:await page.evaluate(()=>RetouchPrototypeDetails.snapshot())}));const popup=await page.locator('.prototype-details:popover-open').boundingBox(),undo=await page.getByRole('button',{name:'Undo',exact:true}).boundingBox();assert.ok(popup.y+popup.height<=undo.y||popup.x+popup.width<=undo.x||popup.x>=undo.x+undo.width,'details leave Undo reachable');await page.screenshot({path:'/tmp/retouch-details-'+kind+'-'+engine+'-long.png'});await page.getByRole('button',{name:'Close interaction details',exact:true}).click();await page.setViewportSize({width:1400,height:1000});
  await app.locator('#other').click();await settle();assert.equal(await page.locator('.prototype-details:popover-open').count(),0,'selection change clears old details');assert.equal(await page.locator('.prototype-connection-row').count(),0);assert.deepEqual(errors,[]);console.log(engine+' '+kind+': compact rows, one details popover, exact history, Escape/focus, drag and keyboard positioning, save/undo position retention, desktop/phone bounds, tab/presentation lifecycle and selection cleanup passed');
 }catch(error){console.error(await page.locator('#toasts').textContent().catch(()=>''),errors);throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
