'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium';
(async()=>{
 const kind=process.env.RT_PROTOTYPE_RENDERER||'html',liquid=kind==='liquid',framework=['react','vue'].includes(kind),custom=kind!=='html',extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind];
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-prototype-'))),file=path.join(root,'index.'+extension);
 let source='<!doctype html><title>Start</title><style>body{padding:24px;font:16px system-ui}#card{position:sticky;top:0;padding:24px;background:#eef3ff}#bottom{margin-top:1500px}</style><div id="card" onclick="window.siteClicks=(window.siteClicks||0)+1">Continue</div><button id="scroll">Details</button><input aria-label="Draft"><h2 id="bottom">Details section</h2>';
 let nextSource='<!doctype html><title>Next</title><style>.long-page{height:2400px}</style><h1>Next page</h1><button id="back">Back</button><div class="long-page"></div>';
 if(framework){const content='<div id="card" '+(kind==='react'?'onClick={clicked}':'@click="clicked"')+'>Continue</div><button id="scroll">Details</button><input aria-label="Draft"/><h2 id="bottom">Details section</h2>',next='<h1>Next page</h1><button id="back">Back</button><div '+(kind==='react'?'className':'class')+'="long-page"></div>',logic='function clicked(){window.siteClicks=(window.siteClicks||0)+1;}';
  if(kind==='react'){source=logic+' export default function App(){return <main>'+content+'</main>}';nextSource='export default function App(){return <main>'+next+'</main>}';}
  else{source='<script setup>'+logic+'</script><template><main>'+content+'</main></template>';nextSource='<script setup>const ready=true;</script><template><main>'+next+'</main></template>';}
 }
 fs.writeFileSync(file,source);fs.writeFileSync(path.join(root,'next.'+extension),nextSource);
 const adapter=liquid?require('../../src/adapters/liquid.cjs'):null,renderer=liquid?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):liquid?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const target=req.url.startsWith('/next')?path.join(root,'next.liquid'):file;res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');const base='http://localhost:'+server.address().port;
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1500,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settled=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert);
 const open=async()=>{await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active&&document.activeElement.id==='exitPresentation');};
 const close=async()=>{await page.locator('#exitPresentation').click();await page.waitForFunction(()=>!RetouchPresentation.active&&document.activeElement.id==='presentBtn');};
 const select=async selector=>{await app.locator(selector).click();await settled();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByRole('button',{name:'Add interaction',exact:true}).waitFor({timeout:10000});};
 try{
  await page.goto(base+'/rt');await select('#card');await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settled();await page.getByLabel('Destination URL 1',{exact:true}).waitFor();
  if(custom){await page.getByLabel('Destination URL 1',{exact:true}).fill('/next.html');await page.getByLabel('Destination URL 1',{exact:true}).press('Tab');await settled();}assert.equal(await page.getByLabel('Destination URL 1',{exact:true}).inputValue(),'/next.html');const connected=fs.readFileSync(file,'utf8');assert.ok(connected.includes('data-rt-prototype'));
  await page.evaluate(()=>{window.keptDocument=document.getElementById('app').contentDocument;});
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();if(custom){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();}assert.equal(fs.readFileSync(file,'utf8'),source);assert.equal(await app.locator('#card').getAttribute('data-rt-prototype'),null);assert.equal(await page.evaluate(()=>keptDocument===document.getElementById('app').contentDocument),true);
  await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();if(custom){await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();}assert.equal(fs.readFileSync(file,'utf8'),connected);
  await page.screenshot({path:'/tmp/retouch-prototype-panel-'+kind+'-'+engine+'.png'});
  await page.getByLabel('Preserve scroll position 1',{exact:true}).check();await settled();
  await open();await app.locator('body').evaluate(()=>scrollTo(0,300));assert.equal(await app.locator('#card').getAttribute('role'),'button');await app.locator('#card').press('Enter');await app.getByRole('heading',{name:'Next page'}).waitFor();await page.waitForFunction(()=>Math.abs(document.getElementById('app').contentWindow.scrollY-300)<2);await close();
  await select('#back');await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settled();await page.getByLabel('Action 1',{exact:true}).selectOption('back');await settled();
  await page.goto(base+'/rt');await app.locator('#card').waitFor();await open();await app.locator('#card').click();await app.getByRole('heading',{name:'Next page'}).waitFor();await app.locator('#back').click();await app.locator('#card').waitFor();assert.equal(await app.locator('body').evaluate(()=>window.siteClicks||0),0,'prototype overrides native click');
  await close();assert.equal(await app.locator('#card').getAttribute('role'),null);assert.equal(await app.locator('#card').getAttribute('tabindex'),null);
  await page.locator('#modeBtn').click();await app.locator('#card').click();assert.equal(await app.locator('body').evaluate(()=>window.siteClicks),1,'interaction is presentation-only');await page.locator('#modeBtn').click();
  await select('#scroll');await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settled();await page.getByLabel('Action 1',{exact:true}).selectOption('scroll');await settled();await page.getByLabel('Destination element ID 1',{exact:true}).fill('bottom');await page.getByLabel('Destination element ID 1',{exact:true}).press('Tab');await settled();
  await open();await app.locator('#scroll').click();await page.waitForFunction(()=>document.getElementById('app').contentWindow.scrollY>500);await close();
  await app.locator('body').evaluate(()=>scrollTo(0,0));await select('#card');await page.getByLabel('Trigger 1',{exact:true}).selectOption('mouseenter');await settled();await open();await app.locator('#card').hover();await app.getByRole('heading',{name:'Next page'}).waitFor();await close();
  await page.goto(base+'/rt');await select('#card');await page.getByRole('button',{name:'Remove interaction 1',exact:true}).click();await settled();assert.equal(await app.locator('#card').getAttribute('data-rt-prototype'),null);await open();await app.locator('#card').click();assert.equal(await app.locator('body').evaluate(()=>window.siteClicks),1);
  assert.deepEqual(errors,[]);console.log(engine+' '+kind+': prototype authoring, persistent navigation/back/scroll/hover, native isolation and exact undo passed');
 }catch(error){console.error(await page.locator('#toasts').textContent(),await page.locator('#prototypePanel').textContent(),errors);throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
