'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE,engine=process.env.RT_E2E_BROWSER||'chromium';if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-modes-'))),file=path.join(root,'index.html'),library={version:1,collections:[{id:id(1),name:'Layout',defaultMode:id(2),modes:[{id:id(2),name:'Compact'},{id:id(4),name:'Spacious'}]}],variables:[{id:id(3),collectionId:id(1),name:'Size',type:'number',values:{[id(2)]:100,[id(4)]:200}},{id:id(5),collectionId:id(1),name:'Alias',type:'number',values:{[id(2)]:{alias:id(3)},[id(4)]:{alias:id(3)}}}]};
 const L=require('../../src/variable-library.cjs'),H=require('../../src/adapters/html.cjs'),B=require('../../src/html-variable-bindings.cjs');L.commitPlan(root,L.planChange(root,{type:'replace',revision:null,library}));let source='<html><head></head><body><button id="switch">Switch mode</button><div id="automatic">Automatic</div><div id="explicit">Explicit</div><div id="aliased">Alias</div></body></html>';
 for(const [name,binding]of [['automatic',{id:id(3)}],['explicit',{id:id(3),modes:{[id(1)]:id(2)}}],['aliased',{id:id(5)}]]){const element=H.collect(source,'index.html').elements.find(e=>e.node.attrs.some(a=>a.name==='id'&&a.value===name));assert.ok(element,name);const bound=B.plan({source,file,relPath:'index.html',hash:H.contentHash(source),element},{type:'applyVariable',width:0,property:'width',binding},library);assert.equal(bound.ok,true,bound.reason);source=bound.edits[0].after;}
 source=source.replace('</body>',`<button id="compact" data-rt-prototype='${JSON.stringify([{trigger:'click',action:'set-variable-mode',modeChange:{collectionId:id(1),modeId:id(2)}}])}'>Compact mode</button></body>`);
 source=source.replace('</body>',`<button id="increment" data-rt-prototype='${JSON.stringify([{trigger:'click',action:'set-variable',assignment:{id:id(3),type:'number',expression:{kind:'operation',op:'+',args:[{kind:'variable',type:'number',id:id(3)},{kind:'literal',type:'number',value:10}]}}}])}'>Increase this mode</button></body>`);
 fs.writeFileSync(file,source);const catalog=fs.readFileSync(path.join(root,'.retouch/variables.json'),'utf8'),server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser,page;
 try{
  browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();page=await browser.newPage({viewport:{width:1500,height:1000}});const app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));const settled=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert);
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#switch').click();await settled();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settled();await page.getByLabel('Action 1',{exact:true}).selectOption('set-variable-mode');await settled();await page.getByLabel('Mode 1',{exact:true}).selectOption(id(4));await settled();const authored=fs.readFileSync(file,'utf8');assert.ok(authored.includes('set-variable-mode'));
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.notEqual(fs.readFileSync(file,'utf8'),authored);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),authored);await page.screenshot({path:'/tmp/retouch-prototype-mode-'+engine+'.png'});
  const widths=expected=>page.waitForFunction(expected=>{const d=document.getElementById('app').contentDocument;return Object.entries(expected).every(([id,value])=>getComputedStyle(d.getElementById(id)).width===value);},expected);
  await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active);await app.locator('#switch').click();await widths({automatic:'200px',explicit:'100px',aliased:'200px'});
  await app.locator('#compact').click();await widths({automatic:'100px',explicit:'100px',aliased:'100px'});await app.locator('#switch').click();await widths({automatic:'200px',explicit:'100px',aliased:'200px'});
  await app.locator('#increment').click();await widths({automatic:'210px',explicit:'100px',aliased:'210px'});
  await app.locator('#compact').click();await widths({automatic:'100px',explicit:'100px',aliased:'100px'});await app.locator('#increment').click();await widths({automatic:'110px',explicit:'110px',aliased:'110px'});
  await app.locator('#switch').click();await widths({automatic:'210px',explicit:'110px',aliased:'210px'});
  // A newly mounted bound instance follows the current mode without another trigger.
  await app.locator('#automatic').evaluate(el=>{const copy=el.cloneNode(true);copy.id='mounted';copy.removeAttribute('style');el.after(copy);});await widths({mounted:'210px'});
  await page.locator('#restartPresentation').click();await app.locator('#switch').waitFor();await widths({automatic:'100px',explicit:'100px',aliased:'100px'});await app.locator('#switch').press('Enter');await widths({automatic:'200px',explicit:'100px',aliased:'200px'});await page.locator('#exitPresentation').click();await widths({automatic:'100px',explicit:'100px',aliased:'100px'});
  assert.equal(fs.readFileSync(file,'utf8'),authored);assert.equal(fs.readFileSync(path.join(root,'.retouch/variables.json'),'utf8'),catalog);assert.deepEqual(errors,[]);console.log(engine+': mode authoring, exact undo/redo, automatic/explicit/alias bindings, independent mode increments, remount, keyboard, restart and source preservation passed');
 }catch(error){console.error(await page?.locator('#prototypePanel').textContent(),await page?.locator('#toasts').textContent());await page?.screenshot({path:'/tmp/retouch-mode-failure-'+engine+'.png'});throw error;}finally{await browser?.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
