'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',kind=process.env.RT_PROTOTYPE_RENDERER||'html';
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-create-'))),extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind],framework=['react','vue'].includes(kind);
 const attr=item=>'data-rt-prototype="'+JSON.stringify(Array.isArray(item)?item:[item]).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/\{/g,'&#123;').replace(/\}/g,'&#125;')+'"';
 const button=(id,label,action,extra={})=>'<button id="'+id+'" '+attr({trigger:'click',action,...extra})+'>'+label+'</button>';
 const style=value=>kind==='react'?'style={'+JSON.stringify(value)+'}':'style="'+Object.entries(value).map(([key,value])=>key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())+':'+value).join(';')+'"';
 const pages={index:'<button id="open">Source</button><input aria-label="Draft"/><section data-testid="first" '+style({marginTop:'80px',marginLeft:'200px',width:'150px',height:'60px',background:'lightblue'})+'>First destination</section><section data-testid="second" '+style({marginTop:'40px',marginLeft:'100px',width:'150px',height:'60px',background:'lightgreen'})+'>Second destination</section><div '+style({height:'1800px'})+'></div>'};

 for(const [name,content]of Object.entries(pages)){const source=kind==='react'?'export default function App(){return <main>'+content+'</main>}':kind==='vue'?'<script setup>const ready=true;</script><template><main>'+content+'</main></template>':'<!doctype html><title>'+name+'</title>'+content;fs.writeFileSync(path.join(root,name+'.'+extension),source);}
 const file=path.join(root,'index.'+extension),adapter=kind==='liquid'?require('../../src/adapters/liquid.cjs'):null,renderer=adapter?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):adapter?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index':path.basename(url.pathname,'.html'),target=path.join(root,name+'.liquid');if(!/^[a-z]+$/.test(name)||!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1400,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert),read=()=>fs.readFileSync(file,'utf8');
 const input=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');await settle();};
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();const handle=()=>page.getByRole('button',{name:'Add scroll connection',exact:true});await handle().waitFor();const initial=read();await app.getByLabel('Draft',{exact:true}).fill('Keep input');await page.evaluate(()=>window.kept=document.querySelector('#app').contentDocument);
  const point=async locator=>{const box=await locator.boundingBox();return {x:box.x+box.width/2,y:box.y+box.height/2};};
  const start=async destination=>{const p=await point(handle()),q=await point(app.locator('[data-testid="'+destination+'"]'));await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:6});};
  const items=()=>app.locator('#open').evaluate(el=>JSON.parse(el.getAttribute('data-rt-prototype')||'[]'));
  await start('first');assert.equal(read(),initial);await page.keyboard.press('Escape');await page.mouse.up();assert.equal(read(),initial,'cancel leaves no anchor or interaction');await start('first');assert.equal(read(),initial);await page.screenshot({path:'/tmp/retouch-create-'+kind+'-'+engine+'.png'});await page.mouse.up();await settle();await page.getByRole('dialog',{name:'Interaction details 1',exact:true}).waitFor();const first=read(),firstItems=await items(),firstAnchor=await app.locator('[data-testid="first"]').getAttribute('id');assert.match(firstAnchor,/^rt-[a-f0-9]{24}$/);assert.deepEqual(firstItems,[{trigger:'click',action:'scroll',destination:firstAnchor}]);assert.equal(await page.evaluate(()=>kept===document.querySelector('#app').contentDocument),true);assert.equal(await app.getByLabel('Draft',{exact:true}).inputValue(),'Keep input');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),initial,'one undo removes the new interaction and anchor');assert.equal(await app.locator('[data-testid="first"]').getAttribute('id'),null);assert.deepEqual(await items(),[]);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),first);await page.getByRole('button',{name:'Close interaction details',exact:true}).click();
  await start('second');await page.mouse.up();const chooser=()=>page.getByRole('dialog',{name:'Choose connection trigger',exact:true});await chooser().waitFor();assert.equal(read(),first);assert.equal(await app.locator('[data-testid="second"]').getAttribute('id'),null);await page.keyboard.press('Escape');await chooser().waitFor({state:'hidden'});await settle();assert.equal(read(),first,'cancel trigger choice leaves the existing click untouched');
  await start('second');await page.mouse.up();await chooser().waitFor();await page.getByLabel('New connection trigger',{exact:true}).selectOption('keyboard');await page.getByRole('button',{name:'Record shortcut for new connection',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await chooser().isVisible(),true,'Escape cancels recording without discarding the trigger draft');await page.getByRole('button',{name:'Record shortcut for new connection',exact:true}).click();await page.keyboard.press('Shift+K');await page.screenshot({path:'/tmp/retouch-create-trigger-'+kind+'-'+engine+'.png'});assert.equal(read(),first,'recording is a local draft');await chooser().getByRole('button',{name:'Connect',exact:true}).click();await settle();await page.getByRole('dialog',{name:'Interaction details 2',exact:true}).waitFor();const second=read(),secondItems=await items();assert.equal(secondItems.length,2);assert.deepEqual(secondItems[0],firstItems[0]);assert.equal(secondItems[1].trigger,'keyboard');assert.equal(secondItems[1].shortcut.code,'KeyK');assert.equal(secondItems[1].shortcut.shift,true);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),first,'the additional trigger and anchor are one history step');assert.equal(await app.locator('[data-testid="second"]').getAttribute('id'),null);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),second);await page.getByRole('button',{name:'Close interaction details',exact:true}).click();
  await handle().focus();await page.keyboard.press('Enter');await chooser().waitFor();await page.getByLabel('New connection trigger',{exact:true}).selectOption('after-delay');await page.getByLabel('Connection delay (ms)',{exact:true}).fill('0');await chooser().getByRole('button',{name:'Connect',exact:true}).click();await chooser().getByRole('status').filter({hasText:'After delay'}).waitFor();assert.equal(read(),second);await page.getByLabel('Connection delay (ms)',{exact:true}).fill('1200');await chooser().getByRole('button',{name:'Connect',exact:true}).click();await page.getByRole('dialog',{name:'Choose scroll destination',exact:true}).waitFor();await page.getByLabel('Find scroll destination',{exact:true}).fill('First destination');await page.getByLabel('Find scroll destination',{exact:true}).press('Enter');await settle();const third=await items();assert.equal(third.length,3);assert.deepEqual(third.slice(0,2),secondItems);assert.equal(third[2].delay,1200);assert.equal(third[2].destination,firstAnchor);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),second);assert.deepEqual(errors,[]);console.log(engine+' '+kind+': source-handle creation, canceled drafts, atomic anchor/history, preserved click, explicit keyboard/delay triggers, keyboard picker and retained state passed');
 }catch(error){console.error(errors,await page.locator('#toasts').textContent().catch(()=>''));throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
