'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',kind=process.env.RT_PROTOTYPE_RENDERER||'html';
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-scroll-'))),extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind],framework=['react','vue'].includes(kind);
 const attr=item=>'data-rt-prototype="'+JSON.stringify([item]).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/\{/g,'&#123;').replace(/\}/g,'&#125;')+'"';
 const button=(id,label,action,extra={})=>'<button id="'+id+'" '+attr({trigger:'click',action,...extra})+'>'+label+'</button>';
 const style=value=>kind==='react'?'style={'+JSON.stringify(value)+'}':'style="'+Object.entries(value).map(([key,value])=>key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())+':'+value).join(';')+'"';
 const pages={index:'<button id="open">Scroll to section</button><input aria-label="Draft"/><div id="scroller" '+style({width:'360px',height:'240px',overflow:'auto',border:'8px solid gray',scrollPaddingTop:'12px',scrollBehavior:'smooth'})+'><div id="target" '+style({marginTop:'600px',marginLeft:'700px',width:'120px',height:'60px',scrollMarginTop:'8px',background:'tomato'})+'>Destination</div><div '+style({height:'600px',width:'1200px'})+'></div></div><div '+style({height:'1800px'})+'></div>'};

 pages.next=pages.index.replace('<button id="open">','<button id="open" '+attr({trigger:'click',action:'scroll',destination:'target',scrollOffset:{x:20,y:-30},transition:{type:'animate',duration:1000,easing:'linear'}})+'>');
 pages.index=button('show','Open overlay','open-overlay',{destination:'/next.html',overlay:{width:640,height:600,position:'center',background:'#00000040',closeOutside:true}})+pages.index;

 for(const [name,content]of Object.entries(pages)){const source=kind==='react'?'export default function App(){return <main>'+content+'</main>}':kind==='vue'?'<script setup>const ready=true;</script><template><main>'+content+'</main></template>':'<!doctype html><title>'+name+'</title>'+content;fs.writeFileSync(path.join(root,name+'.'+extension),source);}
 const file=path.join(root,'index.'+extension),adapter=kind==='liquid'?require('../../src/adapters/liquid.cjs'):null,renderer=adapter?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):adapter?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index':path.basename(url.pathname,'.html'),target=path.join(root,name+'.liquid');if(!/^[a-z]+$/.test(name)||!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1400,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert),read=()=>fs.readFileSync(file,'utf8');
 const input=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');await settle();};
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settle();await page.getByLabel('Action 1',{exact:true}).selectOption('scroll');await settle();await input('Destination element ID 1','target');await input('Scroll offset X 1','20');await input('Scroll offset Y 1','-30');const instant=read();await page.getByLabel('Animation 1',{exact:true}).selectOption('animate');await settle();await input('Duration (ms) 1','1000');await page.getByLabel('Easing 1',{exact:true}).selectOption('custom');await settle();await input('X1 1','0.25');await input('Y1 1','0');await input('X2 1','0.75');await input('Y2 1','1');const authored=read();assert.notEqual(authored,instant);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.notEqual(read(),authored);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),authored);
  await page.screenshot({path:'/tmp/retouch-prototype-scroll-'+kind+'-'+engine+'.png'});
  const enter=async()=>{await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active);};
  const exit=async()=>{await page.locator('#exitPresentation').click();await page.waitForFunction(()=>!RetouchPresentation.active);};
  const pos=()=>app.locator('#scroller').evaluate(el=>({x:el.scrollLeft,y:el.scrollTop,style:el.getAttribute('style')}));
  const reset=()=>app.locator('#scroller').evaluate(el=>{el.scrollTo({left:0,top:0,behavior:'instant'});window.scrollTo({left:0,top:0,behavior:'instant'});});
  const seek=async(time)=>{await page.waitForFunction(()=>RetouchPrototypeScroll.animations.length===1);return page.evaluate(async time=>{const animation=RetouchPrototypeScroll.animations[0];animation.pause();animation.currentTime=time;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return animation.effect.getComputedTiming().progress;},time);};
  const finish=async()=>{await page.evaluate(()=>RetouchPrototypeScroll.animations.forEach(a=>a.finish()));await page.waitForFunction(()=>RetouchPrototypeScroll.animations.length===0);};
  await enter();const before=await pos();await app.locator('#open').click();const progress=await seek(250),quarter=await pos();assert.ok(progress>.17&&progress<.19,'custom easing evaluated by browser');assert.ok(Math.abs(quarter.y-550*progress)<2,'nested scroll follows easing '+JSON.stringify({quarter,progress}));await finish();const end=await pos();assert.ok(Math.abs(end.y-550)<2,'offset, padding and margin determine destination '+JSON.stringify(end));assert.ok(Math.abs(end.x-480)<2,'horizontal offset '+JSON.stringify(end));assert.equal(end.style,before.style,'temporary scroll settings restored');
  await reset();await app.locator('#open').click();await seek(400);const partial=await pos();await app.locator('#scroller').dispatchEvent('wheel',{deltaY:20});await page.waitForFunction(()=>RetouchPrototypeScroll.animations.length===0);assert.equal((await pos()).y,partial.y,'user wheel cancels without jumping to destination');assert.equal((await pos()).style,before.style);
  await reset();await app.locator('#open').click();await seek(300);await exit();assert.equal(await page.evaluate(()=>RetouchPrototypeScroll.animations.length),0,'exit presentation cancels');assert.equal((await pos()).style,before.style);assert.equal(read(),authored,'playback does not change source');
  await reset();await page.emulateMedia({reducedMotion:'reduce'});await enter();await app.locator('#open').click();await page.waitForFunction(()=>Math.abs(document.querySelector('#app').contentDocument.querySelector('#scroller').scrollTop-550)<2);assert.equal(await page.evaluate(()=>RetouchPrototypeScroll.animations.length),0,'reduced motion completes immediately');await exit();await page.emulateMedia({reducedMotion:'no-preference'});
  await reset();await enter();await app.locator('#open').click();await seek(300);await app.locator('#scroller').evaluate(el=>{el.style.backgroundColor='rgb(1, 2, 3)';el.style.setProperty('scroll-behavior','smooth','important');el.scrollTo({left:0,top:75,behavior:'instant'});});await page.waitForFunction(()=>RetouchPrototypeScroll.animations.length===0);const external=await pos();assert.equal(external.y,75,'application scroll cancels motion');assert.equal(await app.locator('#scroller').evaluate(el=>el.style.backgroundColor),'rgb(1, 2, 3)','cleanup retains application style edits');assert.equal(await app.locator('#scroller').evaluate(el=>el.style.scrollSnapType),'','temporary snap override removed');await exit();await app.locator('#scroller').evaluate((el,style)=>el.setAttribute('style',style),before.style);
  await reset();await page.getByLabel('Animation 1',{exact:true}).selectOption('instant');await settle();await enter();await app.locator('#open').click();assert.ok(Math.abs((await pos()).y-550)<2,'instant option uses the same nested destination');assert.equal(await page.evaluate(()=>RetouchPrototypeScroll.animations.length),0);await exit();
  await reset();await page.getByLabel('Animation 1',{exact:true}).selectOption('animate');await settle();await page.getByLabel('Easing 1',{exact:true}).selectOption('spring-bouncy');await settle();await enter();await app.locator('#open').click();await page.waitForFunction(()=>RetouchPrototypeScroll.animations.length===1);const timing=await page.evaluate(()=>RetouchPrototypeScroll.animations[0].effect.getTiming());assert.ok(timing.easing.startsWith('linear('),'physical spring easing');await finish();assert.ok(Math.abs((await pos()).y-550)<2);await exit();
  await reset();await enter();await app.locator('#show').click();const overlay=page.frameLocator('.prototype-overlay-frame').last();await overlay.locator('#open').waitFor();await page.waitForFunction(()=>RetouchPrototypeOverlays.phase==='idle');await overlay.locator('#open').click();await seek(250);assert.equal((await pos()).y,0,'overlay scroll leaves the underlying page untouched');await finish();assert.ok(Math.abs(await overlay.locator('#scroller').evaluate(el=>el.scrollTop)-550)<2,'scroll animation runs in the active overlay');await exit();assert.equal(await page.evaluate(()=>RetouchPrototypeScroll.animations.length),0);
  await page.reload();await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();assert.equal(await page.getByLabel('Scroll offset Y 1',{exact:true}).inputValue(),'-30');assert.equal(await page.getByLabel('Easing 1',{exact:true}).inputValue(),'spring-bouncy');assert.deepEqual(errors,[]);console.log(engine+' '+kind+': scroll authoring/history, nested two-axis geometry, offsets, custom easing, cancellation, reduced motion, springs and reload passed');
 }catch(error){console.error(await page.locator('#toasts').textContent().catch(()=>''),errors);throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
