'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',kind=process.env.RT_PROTOTYPE_RENDERER||'html';
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-pick-'))),extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind],framework=['react','vue'].includes(kind);
 const attr=item=>'data-rt-prototype="'+JSON.stringify([item]).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/\{/g,'&#123;').replace(/\}/g,'&#125;')+'"';
 const button=(id,label,action,extra={})=>'<button id="'+id+'" '+attr({trigger:'click',action,...extra})+'>'+label+'</button>';
 const pages={index:button('open','Scroll','scroll',{destination:'old'})+'<input aria-label="Draft"/><section data-testid="destination">Destination section</section><h2 id="existing">Existing anchor</h2><div id="duplicate">One</div><div id="duplicate">Two</div>'};

 for(const [name,content]of Object.entries(pages)){const source=kind==='react'?'export default function App(){return <main>'+content+'</main>}':kind==='vue'?'<script setup>const ready=true;</script><template><main>'+content+'</main></template>':'<!doctype html><title>'+name+'</title>'+content;fs.writeFileSync(path.join(root,name+'.'+extension),source);}
 const file=path.join(root,'index.'+extension),adapter=kind==='liquid'?require('../../src/adapters/liquid.cjs'):null,renderer=adapter?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):adapter?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index':path.basename(url.pathname,'.html'),target=path.join(root,name+'.liquid');if(!/^[a-z]+$/.test(name)||!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1400,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert),read=()=>fs.readFileSync(file,'utf8');
 const input=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');await settle();};
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByLabel('Destination element ID 1',{exact:true}).waitFor({state:'attached'});const initial=read();await page.getByLabel('Move interaction details',{exact:true}).focus();await page.keyboard.press('Shift+ArrowLeft');const positioned=await page.locator('.prototype-details:popover-open').boundingBox();await app.getByLabel('Draft',{exact:true}).fill('Retain me');await page.evaluate(()=>window.kept=document.querySelector('#app').contentDocument);
  await page.getByRole('button',{name:'Choose scroll destination 1',exact:true}).click();await page.getByRole('dialog',{name:'Choose scroll destination',exact:true}).waitFor();await app.locator('[data-testid="destination"]').hover();await page.screenshot({path:'/tmp/retouch-prototype-pick-'+kind+'-'+engine+'.png'});await app.locator('[data-testid="destination"]').click();await settle();await page.getByLabel('Destination element ID 1',{exact:true}).waitFor({state:'attached'});const anchor=await app.locator('[data-testid="destination"]').getAttribute('id');assert.match(anchor,/^rt-[a-f0-9]{24}$/);assert.ok(Math.abs((await page.locator('.prototype-details:popover-open').boundingBox()).x-positioned.x)<2,'picking retains panel placement '+JSON.stringify({positioned,current:await page.locator('.prototype-details:popover-open').boundingBox(),view:await page.evaluate(()=>RetouchPrototypeDetails.snapshot())}));assert.equal(await page.getByLabel('Destination element ID 1',{exact:true}).inputValue(),anchor);const connected=read();assert.notEqual(connected,initial);assert.equal(await page.evaluate(()=>kept===document.querySelector('#app').contentDocument),true);assert.equal(await app.getByLabel('Draft',{exact:true}).inputValue(),'Retain me');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),initial,'one undo removes anchor and connection');assert.equal(await app.locator('[data-testid="destination"]').getAttribute('id'),null);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),connected);assert.equal(await app.locator('[data-testid="destination"]').getAttribute('id'),anchor);
  await page.getByRole('button',{name:'Choose scroll destination 1',exact:true}).click();await page.getByLabel('Find scroll destination',{exact:true}).fill('Existing anchor');await page.getByLabel('Find scroll destination',{exact:true}).press('Enter');await settle();assert.equal(await page.getByLabel('Destination element ID 1',{exact:true}).inputValue(),'existing');assert.equal(await app.locator('#existing').getAttribute('id'),'existing');const existing=read();
  await page.getByRole('button',{name:'Choose scroll destination 1',exact:true}).click();await app.locator('#duplicate').first().click();await page.getByText('Choose one uniquely rendered layer.',{exact:false}).waitFor();assert.equal(read(),existing);await page.keyboard.press('Escape');await page.getByLabel('Destination element ID 1',{exact:true}).waitFor({state:'attached'});assert.equal(read(),existing,'cancel does not write source');
  await page.getByRole('button',{name:'Choose scroll destination 1',exact:true}).click();await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active);assert.equal(await page.locator('.prototype-target-picker').count(),0,'presentation cancels picker');await page.locator('#exitPresentation').click();await page.getByLabel('Destination element ID 1',{exact:true}).waitFor({state:'attached'});
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),connected);await page.reload();await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();assert.equal(await page.getByLabel('Destination element ID 1',{exact:true}).inputValue(),anchor);await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),initial,'persisted undo also removes generated anchor');assert.equal(await app.locator('[data-testid="destination"]').getAttribute('id'),null);assert.deepEqual(errors,[]);console.log(engine+' '+kind+': canvas/list destination picking, generated/preserved anchors, exact atomic undo/redo, retained document/input, duplicate refusal, cancel and reload passed');
 }catch(error){console.error(await page.locator('#toasts').textContent().catch(()=>''),errors,await page.evaluate(()=>({selection:RetouchPrototypeHost.selection()?.id,panel:document.getElementById('prototypePanel').textContent,picker:!!document.querySelector('.prototype-target-picker'),inert:document.getElementById('prototypePanel').inert})));throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
