'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',kind=process.env.RT_PROTOTYPE_RENDERER||'html',PNG=require(require.resolve('pngjs',{paths:[process.env.RT_BUILD_FIXTURE||fixture]})).PNG;
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-motion-'))),extension={html:'html',liquid:'liquid',react:'jsx',vue:'vue'}[kind],framework=['react','vue'].includes(kind),types=['smart-animate','dissolve','move-in','move-out','push','slide-in','slide-out','instant'];
 const attr=item=>'data-rt-prototype="'+JSON.stringify([item]).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/\{/g,'&#123;').replace(/\}/g,'&#125;')+'"',motion=type=>type==='instant'?{type}:{type,duration:1000,easing:'linear',...(['dissolve','smart-animate'].includes(type)?{}:{direction:'right'})};
 const button=(id,label,action,extra={})=>'<button id="'+id+'" '+attr({trigger:'click',action,...extra})+'>'+label+'</button>';
 const art=(color,content)=>'<div id="art" '+(kind==='react'?'style={{position:"fixed",inset:0,background:"'+color+'"}}':'style="position:fixed;inset:0;background:'+color+'"')+'>'+content+'</div>';
 const pages={index:'<button id="open">Open</button><input aria-label="Draft"/>'+['dissolve','slide-in'].map(type=>button('open-'+type,'Open '+type,'open-overlay',{destination:'/next.html',transition:motion(type)})).join(''),next:art('rgb(255,0,0)',types.map(type=>button(type,type,'swap-overlay',{destination:'/alt.html',transition:motion(type)})).join('')),alt:art('rgb(0,0,255)',button('close','Close','close-overlay',{transition:motion('move-out')})+['dissolve','slide-out'].map(type=>button('close-'+type,'Close '+type,'close-overlay',{transition:motion(type)})).join(''))};
 for(const [name,content]of Object.entries(pages)){const source=kind==='react'?'export default function App(){return <main>'+content+'</main>}':kind==='vue'?'<script setup>const ready=true;</script><template><main>'+content+'</main></template>':'<!doctype html><title>'+name+'</title>'+content;fs.writeFileSync(path.join(root,name+'.'+extension),source);}
 const file=path.join(root,'index.'+extension),adapter=kind==='liquid'?require('../../src/adapters/liquid.cjs'):null,renderer=adapter?new(require('liquidjs').Liquid)():null;
 const server=framework?require('./prototype-framework-server.cjs')({root,renderer:kind,fixture}):adapter?require('../../src/server.cjs').startServer({appRoot:root,adapter,port:0,quiet:true,rendering:{reloadAfterWrite:true},serveSite:async(req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index':path.basename(url.pathname,'.html'),target=path.join(root,name+'.liquid');if(!/^[a-z]+$/.test(name)||!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('content-type','text/html');res.end(await renderer.parseAndRender(adapter.stamp(fs.readFileSync(target,'utf8'),target,root).code,{}));}}):require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 const browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch(),page=await browser.newPage({viewport:{width:1400,height:1000}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settle=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy&&!document.getElementById('prototypePanel').inert),phase=value=>page.waitForFunction(value=>RetouchPrototypeOverlays.phase===value,value),overlay=()=>page.frameLocator('.prototype-overlay-frame').last(),read=()=>fs.readFileSync(file,'utf8');
 const input=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');await settle();};
 const pause=()=>page.evaluate(()=>{const animations=RetouchPrototypeOverlays.animations;for(const a of animations){a.pause();a.currentTime=500;}return animations.map(a=>({duration:a.effect.getTiming().duration,easing:a.effect.getTiming().easing}));});
 const finish=()=>page.evaluate(()=>RetouchPrototypeOverlays.animations.forEach(a=>a.finish()));
 const open=async(type='move-in')=>{await app.locator(type==='move-in'?'#open':'#open-'+type).click();await phase('animating');assert.ok((await pause()).every(t=>t.duration===1000&&t.easing==='linear'));const opacity=await page.locator('.prototype-overlay-card').evaluate(el=>Number(getComputedStyle(el).opacity));assert.ok(Math.abs(opacity-(type==='move-in'?1:.5))<.01,'opening '+type+' opacity '+opacity);await finish();await phase('idle');};
 const pixels=async()=>{const png=PNG.sync.read(await page.locator('.prototype-overlay-card').screenshot());return [.25,.75].map(x=>{const index=(Math.floor(png.height*.85)*png.width+Math.floor(png.width*x))*4;return [...png.data.subarray(index,index+3)];});};
 try{
  await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#open').click();await settle();await page.getByRole('tab',{name:'Prototype',exact:true}).click();await page.getByRole('button',{name:'Add interaction',exact:true}).click();await settle();await input('Destination URL 1','/next.html');await page.getByLabel('Action 1',{exact:true}).selectOption('open-overlay');await settle();await page.getByLabel('Animation 1',{exact:true}).selectOption('move-in');await settle();await input('Duration (ms) 1','1000');const before=read();await page.getByLabel('Easing 1',{exact:true}).selectOption('linear');await settle();const after=read();await page.getByRole('button',{name:'Undo',exact:true}).click();await settle();assert.equal(read(),before);await page.getByRole('button',{name:'Redo',exact:true}).click();await settle();assert.equal(read(),after);
  await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await page.getByRole('button',{name:'Present',exact:true}).click();await page.waitForFunction(()=>RetouchPresentation.active&&document.activeElement.id==='exitPresentation');await app.getByLabel('Draft').fill('Keep me');await page.evaluate(()=>window.savedDocument=document.getElementById('app').contentDocument);
  for(const type of types){
   await open(['move-in','dissolve','slide-in'][types.indexOf(type)%3]);await overlay().locator('#'+type).click();
   if(type!=='instant'){
    await phase('animating');await pause();assert.equal(await page.locator('.prototype-overlay-frame').count(),2,'swap retains both real documents during motion');
    const [left,right]=await pixels();
    if(['dissolve','smart-animate'].includes(type))for(const pixel of [left,right])assert.ok(Math.abs(pixel[0]-128)<5&&pixel[1]<5&&Math.abs(pixel[2]-128)<5,type+' '+pixel);
    else if(['move-out','slide-out'].includes(type)){assert.ok(left[2]>left[0]+30,type+' left '+left);assert.ok(right[0]>right[2]+30,type+' right '+right);}
    else{assert.ok(left[0]>left[2]+30,type+' left '+left);assert.ok(right[2]>right[0]+30,type+' right '+right);}
    if(type==='push')await page.screenshot({path:'/tmp/retouch-motion-'+kind+'-'+engine+'.png'});await finish();
   }
   await phase('idle');assert.equal(await page.locator('.prototype-overlay-frame').count(),1);assert.deepEqual(await pixels(),[[0,0,255],[0,0,255]]);const closeType=['move-out','dissolve','slide-out'][types.indexOf(type)%3];await overlay().locator(closeType==='move-out'?'#close':'#close-'+closeType).click();await phase('closing');await pause();const opacity=await page.locator('.prototype-overlay-card').evaluate(el=>Number(getComputedStyle(el).opacity));assert.ok(Math.abs(opacity-(closeType==='move-out'?1:.5))<.01,'closing '+closeType+' opacity '+opacity);await finish();await page.waitForFunction(()=>RetouchPrototypeOverlays.count===0);
   assert.equal(await app.getByLabel('Draft').inputValue(),'Keep me');assert.equal(await page.evaluate(()=>savedDocument===document.getElementById('app').contentDocument),true);
  }
  await open();let release,started;const requested=new Promise(resolve=>started=resolve);
  await page.route('**/alt.html',route=>new Promise(resolve=>{release=()=>route.abort().catch(()=>{}).then(resolve);started();}));
  await overlay().locator('#push').click();await requested;await phase('swapping');assert.deepEqual(await pixels(),[[255,0,0],[255,0,0]],'outgoing live content stays visible while destination loads');
  await page.getByRole('button',{name:'Close overlay',exact:true}).click();await phase('closing');await pause();await finish();await page.waitForFunction(()=>RetouchPrototypeOverlays.count===0);await release();await page.unroute('**/alt.html');
  await page.emulateMedia({reducedMotion:'reduce'});await app.locator('#open').click();await page.waitForFunction(()=>RetouchPrototypeOverlays.count===1&&RetouchPrototypeOverlays.phase==='idle');assert.deepEqual(await pause(),[]);await overlay().locator('#smart-animate').click();await phase('idle');await overlay().locator('#close').click();await page.waitForFunction(()=>RetouchPrototypeOverlays.count===0);await page.emulateMedia({reducedMotion:'no-preference'});
  await app.locator('#open').click();await phase('animating');await pause();await page.locator('#exitPresentation').click();await page.waitForFunction(()=>!RetouchPresentation.active);assert.equal(await page.locator('.prototype-overlay-frame').count(),0);assert.equal(await page.locator('#app').evaluate(el=>el.inert),false);assert.deepEqual(await pause(),[]);
  assert.equal(read(),after);assert.deepEqual(errors,[]);console.log(engine+' '+kind+': eight rendered transitions, timing/easing, source undo, reduced motion, cleanup and retained state passed');
 }catch(error){console.error(await page.locator('#toasts').textContent(),errors);throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
