'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE for Next.js and Playwright');const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-react-marquee-')),file=path.join(root,'app/page.jsx');fs.mkdirSync(path.dirname(file));fs.symlinkSync(path.join(fixture,'node_modules'),path.join(root,'node_modules'),'dir');fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({private:true,dependencies:{next:'16.2.5',react:'19.2.0','react-dom':'19.2.0'}}));fs.writeFileSync(path.join(root,'postcss.config.mjs'),"export default {plugins:{'@tailwindcss/postcss':{}}}");fs.writeFileSync(path.join(root,'app/style.css'),'@import "tailwindcss"; @source "./";');fs.writeFileSync(path.join(root,'app/layout.jsx'),'import "./style.css"; export default function Layout({children}){return <html><body>{children}</body></html>}');
 const original='export default function Page(){return <main aria-label="Frame" className="absolute left-[50px] top-[50px] w-[300px] h-[260px] bg-slate-100"><div aria-label="A" className="absolute left-[20px] top-[20px] w-[50px] h-[40px] bg-red-500">A</div><div aria-label="B" className="absolute left-[140px] top-[80px] w-[60px] h-[50px] bg-blue-500">B</div><div aria-label="C" className="absolute left-[30px] top-[160px] w-[70px] h-[30px] bg-green-500">C</div></main>}';fs.writeFileSync(file,original);
 let logs='',url,browser,diagnose;const child=spawn(process.execPath,[path.resolve(__dirname,'../../bin/retouch.cjs'),'--',process.execPath,path.join(fixture,'node_modules/next/dist/bin/next'),'dev','--webpack','-p','0'],{cwd:root,env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});let exited=false;const stopped=new Promise(r=>child.once('exit',()=>{exited=true;r();}));for(const stream of [child.stdout,child.stderr])stream.on('data',chunk=>{logs+=chunk;url=logs.match(/http:\/\/localhost:(\d+)/)?.[0];});
 const wait=async fn=>{for(let i=0;i<240;i++){try{if(await fn())return;}catch(e){if(!/Execution context was destroyed|ECONNREFUSED|fetch failed/.test(e.message))throw e;}if(exited)throw Error('Next exited: '+logs);await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+logs.slice(-2500));};
 try{
  await wait(()=>url);await wait(async()=>{const res=await fetch(url+'/rt/__api/health');return res.ok;});browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/rt',{timeout:90000});const app=page.frameLocator('#app');await app.locator('[aria-label="A"]').waitFor({timeout:90000});const read=()=>fs.readFileSync(file,'utf8');
  const settled=()=>wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true'&&await app.locator('[aria-label="A"]').getAttribute('data-rt-revision')===require('../../src/id.cjs').contentHash(read())),selected=()=>page.getByRole('treeitem',{selected:true}).allTextContents(),selection=async names=>wait(async()=>JSON.stringify((await selected()).sort())===JSON.stringify(names.map(name=>'div · '+name).sort())),zoom=async value=>{await page.getByLabel('Canvas zoom (%)',{exact:true}).fill(String(value));await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Enter');await app.locator('body').evaluate(()=>scrollTo(0,0));await page.locator('#frameWrap').evaluate(async el=>{el.scrollLeft=0;el.scrollTop=96;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});};
  await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===768);await settled();const marquee=page.locator('.selection-marquee');
  const drag=async(value,{gray=false,start=[60,60],end=[270,190],append=false,cancel=false,tiny=false}={})=>{const f=await page.locator('#app').boundingBox(),scale=value/100,x=gray?f.x-12:f.x+start[0]*scale,y=f.y+start[1]*scale;if(append)await page.keyboard.down('Shift');await page.mouse.move(x,y);await page.mouse.down();if(tiny){await page.mouse.move(x+1,y);await page.waitForTimeout(100);assert.equal(await marquee.count(),0);}await page.mouse.move(f.x+end[0]*scale,f.y+end[1]*scale,{steps:5});await wait(async()=>await marquee.count()===1);assert.equal(read(),original);if(cancel)await page.keyboard.press('Escape');await page.mouse.up();if(append)await page.keyboard.up('Shift');await wait(async()=>await marquee.count()===0);};
  const clickBackground=async value=>{await app.locator('main').evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const box=await app.locator('main').boundingBox();await page.mouse.click(box.x+5*value/100,box.y+5*value/100);};
  await wait(async()=>await app.locator('main').evaluate(el=>{const r=el.getBoundingClientRect();return r.left===50&&r.top===50&&r.width===300&&r.height===260;}));
  diagnose=async()=>console.log('DIAGNOSTIC',JSON.stringify({errors,source:read(),selected:await selected()}));
  for(const value of [50,100,200]){
   await zoom(value);await clickBackground(value);await wait(async()=>await page.getByRole('treeitem',{name:'main · Frame',exact:true}).getAttribute('aria-selected')==='true');
   await drag(value,{tiny:true});await selection(['A','B']);await settled();assert.equal(await page.getByRole('button',{name:'Move selection on canvas',exact:true}).count(),1);
   await drag(value,{start:[60,200],end:[220,260],append:true});await selection(['A','B','C']);await settled();await drag(value,{cancel:true});await selection(['A','B','C']);
   await drag(value,{gray:true,start:[60,60]});await selection(['A','B']);await settled();
  }
  await zoom(100);await page.keyboard.down('Shift');await clickBackground(100);await wait(async()=>{const names=await selected();return names.length===3&&names.includes('main · Frame');});await clickBackground(100);await selection(['A','B']);await page.keyboard.up('Shift');if(process.env.RT_E2E_REACT_MARQUEE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_REACT_MARQUEE_SCREENSHOT});
  await page.getByRole('button',{name:'Move selection on canvas',exact:true}).click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();assert.deepEqual(await app.locator('[aria-label="A"],[aria-label="B"],[aria-label="C"]').evaluateAll(els=>els.map(el=>parseFloat(getComputedStyle(el).left))),[21,141,30]);await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();await selection(['A','B']);
  // An active drag is cancelled by zoom and screen changes without selecting new layers.
  for(const change of ['zoom','screen']){const f=await page.locator('#app').boundingBox();await page.mouse.move(f.x-12,f.y+60);await page.mouse.down();await page.mouse.move(f.x+280,f.y+270,{steps:4});await wait(async()=>await marquee.count()===1);if(change==='zoom'){await page.getByLabel('Canvas zoom (%)',{exact:true}).fill('50');await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Enter');}else await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await wait(async()=>await marquee.count()===0);await page.mouse.up();await selection(['A','B']);if(change==='zoom')await zoom(100);}
  assert.equal(read(),original);assert.deepEqual(errors,[]);console.log(engine+': PASS React inner-frame and gray-canvas marquee at 50/100/200% zoom, click preservation, screen-pixel threshold, additive selection, Escape/zoom/screen cancellation, group edit integration and exact source/selection undo');
 }catch(error){if(diagnose)await diagnose();throw error;}finally{if(browser)await browser.close();if(!exited)child.kill('SIGTERM');await stopped;fs.rmSync(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
