'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');const fixture=process.env.RT_INSPECTOR_FIXTURE,engine=process.env.RT_E2E_BROWSER||'chromium';if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');
(async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-rulers-')),file=path.join(root,'index.html'),source='<html><body style="height:2500px"><h1>Rulers</h1><input value="initial"></body></html>';fs.writeFileSync(file,source);const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;
 try{browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const app=page.frameLocator('#app'),wait=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(50);}throw Error('Rulers did not settle');};
 await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('h1').waitFor();await app.locator('input').evaluate(el=>{el.value='retained';window.rulerIdentity={};window.originalRulerIdentity=window.rulerIdentity;});await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await page.getByRole('button',{name:'Toggle rulers',exact:true}).click();
 const aligned=()=>page.evaluate(()=>{const frame=document.getElementById('app'),rect=frame.getBoundingClientRect(),scale=rect.width/frame.clientWidth;return [...document.querySelectorAll('.canvas-ruler')].every(svg=>{const vertical=svg.classList.contains('canvas-ruler-vertical'),bounds=svg.getBoundingClientRect(),labels=[...svg.querySelectorAll('[data-ruler-value]')];return labels.length>1&&labels.every(label=>{const coordinate=Number(label.dataset.rulerValue),actual=(vertical?bounds.top:bounds.left)+Number(label.getAttribute(vertical?'y':'x'))-3,expected=(vertical?rect.top:rect.left)+(coordinate-(vertical?frame.contentWindow.scrollY:frame.contentWindow.scrollX))*scale;return Math.abs(actual-expected)<=1;});});});await wait(aligned);
 await page.getByLabel('Canvas zoom (%)',{exact:true}).fill('150');await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Tab');await wait(aligned);await app.locator('body').evaluate(()=>window.scrollTo(0,400));await wait(aligned);await page.locator('#frameWrap').evaluate(el=>{el.scrollTop+=40;el.scrollLeft+=35;});await wait(aligned);assert.deepEqual(await app.locator('input').evaluate(el=>[el.value,!!window.rulerIdentity&&window.rulerIdentity===window.originalRulerIdentity]),['retained',true]);
 if(process.env.RT_E2E_RULERS_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_RULERS_SCREENSHOT});await page.reload();await app.locator('h1').waitFor();assert.equal(await page.getByRole('button',{name:'Toggle rulers',exact:true}).getAttribute('aria-pressed'),'true');await wait(aligned);await page.getByRole('treeitem',{name:'h1 · Rulers',exact:true}).click();await page.getByRole('button',{name:'Actions',exact:true}).click();const search=page.getByRole('combobox',{name:'Search actions',exact:true});await search.fill('rulers');await search.press('Enter');await wait(async()=>!await page.locator('.canvas-ruler-horizontal').isVisible());assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);console.log('RULERS ZOOM/PAN/PAGE SCROLL, PERSISTENCE, ACTIONS AND SOURCE ISOLATION PASS',engine);
 }finally{if(browser)await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
