'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const original=read(),measure=()=>app.locator('h1,p').evaluateAll(nodes=>nodes.map(el=>{const r=el.getBoundingClientRect();return [r.x,r.y,r.width,r.height];})),matches=async expected=>(await measure()).every((r,i)=>r.every((n,j)=>Math.abs(n-expected[i][j])<.1)),size=async value=>{const input=page.getByLabel('Screen width',{exact:true});await input.fill(String(value));await input.press('Enter');await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===value);await settled();};
 await size(390);const phone=await measure();await size(1100);await page.getByRole('treeitem',{name:'h1 · Headline',exact:true}).click();await page.getByRole('treeitem',{name:'p · Other text',exact:true}).click({modifiers:['Meta']});await settled();const desktop=await measure(),left=Math.min(...desktop.slice(0,2).map(r=>r[0])),top=Math.min(...desktop.slice(0,2).map(r=>r[1])),expected=desktop.map((r,i)=>i<2?[left+(r[0]-left)*1.5,top+(r[1]-top)*1.5,r[2]*1.5,r[3]*1.5]:r),picker=page.getByLabel('Style screen scope',{exact:true}),scope=await picker.evaluate(el=>[...el.options].find(option=>option.textContent.includes('1100'))?.value);assert.ok(scope);await picker.selectOption(scope);await settled();
 const input=page.getByLabel('Scale selection (%)',{exact:true});await input.fill('150');await input.press('Enter');await wait(()=>read()!==original);await settled();await wait(()=>matches(expected));const changed=read();await size(390);await wait(()=>matches(phone));assert.equal(await picker.inputValue(),scope);assert.equal(read(),changed);
 await wait(async()=>await page.getByRole('status',{name:'Edit range status',exact:true}).getAttribute('data-match')==='false');
 assert.equal(await input.isDisabled(),true,'inactive edit range disables numeric scaling');assert.equal(await page.getByRole('button',{name:'Scale selection on canvas',exact:true}).isDisabled(),true);assert.equal(await page.locator('#canvasScale').isDisabled(),true);
 const label=input.locator('..').locator('span').first();await label.evaluate(el=>el.scrollIntoView({block:'nearest'}));const box=await label.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2,{steps:4});await page.mouse.up();assert.equal(read(),changed);await wait(()=>matches(phone));await app.locator('body').evaluate(el=>{el.tabIndex=-1;el.focus({preventScroll:true});});await page.keyboard.press('k');assert.equal(await page.locator('.canvas-move-surface').count(),0);await page.screenshot({path:'/tmp/retouch-scale-scope-'+kind+'.png'});
 await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();await wait(()=>matches(phone));await size(1100);await wait(()=>matches(desktop));await wait(async()=>await input.isEnabled()&&await page.locator('#canvasScale').isEnabled());await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===changed);await settled();await wait(()=>matches(expected));await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();await wait(()=>matches(desktop));
 console.log(kind+': PASS desktop-only scaling preserves phone geometry, inactive range controls disabled, and exact undo/redo across screen changes');
};
