'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE,engine=process.env.RT_E2E_BROWSER||'chromium';if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const PNG=require(require.resolve('pngjs',{paths:[process.env.RT_BUILD_FIXTURE||fixture]})).PNG;
(async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-export-')),file=path.join(root,'index.html'),source='<!doctype html><title>My screen</title><style>body{margin:0;background:white}#box{width:100px;height:100px;background:red}#scroller{width:100px;height:50px;overflow:auto}#inside{height:200px;background:linear-gradient(red 50%,blue 50%)}</style><div id="box"></div><input value="Original"><div id="scroller"><div id="inside"></div></div>';fs.writeFileSync(file,source);const server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');let browser;try{
 browser=await require(path.join(fixture,'node_modules/playwright'))[engine].launch();delete process.env.PLAYWRIGHT_BROWSERS_PATH;const page=await browser.newPage({viewport:{width:1440,height:1000}}),app=page.frameLocator('#app'),errors=[];page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:'+server.address().port+'/rt');await app.locator('#box').waitFor();await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await app.locator('#box').evaluate(el=>{el.style.background='lime';el.ownerDocument.querySelector('input').value='Live value';el.ownerDocument.getElementById('scroller').scrollTop=150;el.ownerDocument.defaultView.identity=el.ownerDocument;});
 await page.keyboard.press('Meta+k');const search=page.getByRole('combobox',{name:'Search actions'});await search.fill('Export screen');await search.press('Enter');const dialog=page.getByRole('dialog',{name:'Export screen',exact:true});await page.screenshot({path:'/tmp/retouch-screen-export-'+engine+'.png'});await page.setViewportSize({width:360,height:800});const bounds=await dialog.boundingBox();assert.ok(bounds.x>=16&&bounds.x+bounds.width<=344&&bounds.y>=16&&bounds.y+bounds.height<=784);await page.setViewportSize({width:1440,height:1000});await dialog.getByLabel('Export scale').selectOption('2');const downloaded=page.waitForEvent('download');await dialog.getByRole('button',{name:'Export PNG',exact:true}).click();const download=await downloaded,png=PNG.sync.read(fs.readFileSync(await download.path()));assert.equal(png.width,780);assert.equal(png.height,1688);assert.equal(download.suggestedFilename(),'My-screen@2x.png');const pixel=(x,y)=>[...png.data.subarray((y*png.width+x)*4,(y*png.width+x)*4+4)];assert.deepEqual(pixel(20,20),[0,255,0,255]);const scrollY=await app.locator('#scroller').evaluate(el=>el.getBoundingClientRect().top);assert.deepEqual(pixel(20,Math.round((scrollY+20)*2)),[0,0,255,255]);assert.equal(await app.locator('input').inputValue(),'Live value');assert.equal(await app.locator('#box').evaluate(el=>el.ownerDocument===el.ownerDocument.defaultView.identity),true);await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Compare screens',exact:true}).click();await page.frameLocator('iframe[title="Tablet comparison preview"]').locator('#box').waitFor();await page.getByRole('button',{name:'Export screen',exact:true}).click();await dialog.getByLabel('Screen to export').selectOption({label:'Tablet · 768 × 1024'});const nextDownload=page.waitForEvent('download');await dialog.getByRole('button',{name:'Export PNG',exact:true}).click();const next=PNG.sync.read(fs.readFileSync(await (await nextDownload).path()));assert.equal(next.width,768);assert.equal(next.height,1024);assert.deepEqual([...next.data.subarray((20*768+20)*4,(20*768+20)*4+4)],[255,0,0,255]);await dialog.getByRole('button',{name:'Close',exact:true}).click();
 const auth=await page.evaluate(async()=>{const missing=await fetch('/rt/__api/screen-export',{method:'POST',body:'{}'}),method=await fetch('/rt/__api/screen-export',{headers:{'x-retouch-token':__RT_TOKEN}});return [missing.status,method.status];});assert.deepEqual(auth,[401,405]);
 const safe=await page.evaluate(async()=>{const response=await fetch('/rt/__api/screen-export',{method:'POST',headers:{'content-type':'application/json','x-retouch-token':__RT_TOKEN},body:JSON.stringify({html:'<body style="margin:0;background:lime"><script>document.body.style.background="red"</script>',width:100,height:100,scale:1,baseURL:location.origin,fontFaces:[],scroll:[],rootScroll:{x:0,y:0}})});return {status:response.status,bytes:[...new Uint8Array(await response.arrayBuffer())]};});assert.equal(safe.status,200);assert.deepEqual([...PNG.sync.read(Buffer.from(safe.bytes)).data.subarray(0,4)],[0,255,0,255]);
 const broken=await page.evaluate(async()=>{const response=await fetch('/rt/__api/screen-export',{method:'POST',headers:{'content-type':'application/json','x-retouch-token':__RT_TOKEN},body:JSON.stringify({html:'<img src="/missing.png">',width:100,height:100,scale:1,baseURL:location.origin,fontFaces:[],scroll:[],rootScroll:{x:0,y:0}})});return {status:response.status,body:await response.json()};});assert.equal(broken.status,422);assert.match(broken.body.reason,/image|resources/i);
 const refused=await page.evaluate(async()=>{const response=await fetch('/rt/__api/screen-export',{method:'POST',headers:{'content-type':'application/json','x-retouch-token':__RT_TOKEN},body:JSON.stringify({html:'hi',width:7680,height:7680,scale:2})});return response.status;});assert.equal(refused,400);
 await app.locator('body').evaluate(el=>{const frame=el.ownerDocument.createElement('iframe');el.append(frame);});await page.getByRole('button',{name:'Export screen',exact:true}).click();await dialog.getByRole('button',{name:'Export PNG',exact:true}).click();assert.match(await dialog.getByRole('status').textContent(),/Embedded documents are omitted/);assert.equal(fs.readFileSync(file,'utf8'),source);assert.deepEqual(errors,[]);console.log(engine+': live screen and comparison PNG export, 1x/2x pixels, nested scroll, state retention and refusal passed');
 }finally{await browser?.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
