'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE for Playwright');
const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-selection-spacing-')),file=path.join(root,'index.html');
 const original='<html><head><style>body{margin:0}main{position:relative;margin:20px;border:10px solid #475569;width:600px;height:500px;background:#dbeafe}.box{position:absolute;background:#34d399}.a{left:30px;top:40px;width:50px;height:40px}.b{left:140px;top:100px;width:60.03px;height:50px;padding:5px;border:2px solid black;max-width:60.03px}.c{left:250px;top:220px;width:50px;height:30px}</style></head><body><main><div class="box a" aria-label="A">A</div><div class="box b" aria-label="B">B</div><div class="box c" aria-label="C">C</div><div aria-label="Protected" style="position:absolute;left:450px!important;top:350px;width:50px;height:40px">Protected</div></main><section style="position:relative;width:600px;height:100px"><div class="other-layer" aria-label="D" style="position:absolute;left:20px;top:10px;width:40px;height:30px">D</div></section></body></html>';
 fs.writeFileSync(file,original);const read=()=>fs.readFileSync(file,'utf8'),server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});await once(server,'listening');
 const browser=await browserType.launch(),page=await browser.newPage({viewport:{width:1600,height:1100}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const wait=async fn=>{for(let i=0;i<100;i++){try{if(await fn())return;}catch(e){if(!/Execution context was destroyed/.test(e.message))throw e;}await page.waitForTimeout(100);}throw Error('Selection spacing did not settle');},settled=()=>wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true');
 const close=(a,b)=>assert.ok(Math.abs(a-b)<.3,`${a} differs from ${b}`),boxes=()=>app.locator('.box').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect(),p=el.parentElement,pr=p.getBoundingClientRect();return{x:r.left-pr.left-p.clientLeft,y:r.top-pr.top-p.clientTop,width:r.width,height:r.height};}));
 const select=async(names=['A','B','C'])=>{for(let i=0;i<names.length;i++){await page.getByRole('treeitem',{name:'div · '+names[i],exact:true}).click(i?{modifiers:['Meta']}:{ });await wait(async()=>await page.getByRole('treeitem',{selected:true}).count()===i+1);await settled();}};
 const control=(axis='x')=>page.getByRole('button',{name:'Adjust '+(axis==='x'?'horizontal':'vertical')+' gaps on canvas',exact:true});
 const start=async(axis='x',index=0)=>{await control(axis).click();assert.equal(await page.locator('.canvas-group-layer').count(),3);assert.equal(await page.locator('.canvas-gap-handle').count(),2);const r=await page.locator('.canvas-gap-handle').nth(index).boundingBox(),point={x:r.x+r.width/2,y:r.y+r.height/2};await page.mouse.move(point.x,point.y);await page.mouse.down();return point;};
 const undo=async()=>{await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();assert.equal(await page.getByRole('treeitem',{selected:true}).count(),3);};
 const size=async value=>{await page.getByLabel('Screen size',{exact:true}).selectOption(value);await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===Number(value.split('x')[0]));await settled();};
 const zoom=async value=>{await page.getByLabel('Canvas zoom (%)',{exact:true}).fill(String(value));await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Enter');await app.locator('body').evaluate(()=>scrollTo(0,0));await page.locator('#frameWrap').evaluate(async el=>{el.scrollLeft=0;el.scrollTop=96;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});};
 try{
  await page.goto(`http://localhost:${server.address().port}/rt`);await size('768x1024');await select();const baseline=await boxes();
  const verify=async(axis,gap,anchor=0,start=null)=>{const result=await boxes(),dimension=axis==='x'?'width':'height',other=axis==='x'?'y':'x';for(let i=0;i<result.length;i++){close(result[i].width,baseline[i].width);close(result[i].height,baseline[i].height);close(result[i][other],baseline[i][other]);if(i)close(result[i][axis]-result[i-1][axis]-result[i-1][dimension],gap);}if(start!==null)close(result[0][axis],start);else close(result[anchor][axis],baseline[anchor][axis]);};let lastSource;
  for(const value of [50,100,200]){await zoom(value);const scale=value/100,point=await start();await page.mouse.move(point.x+20,point.y,{steps:5});assert.equal(read(),original);assert.deepEqual(await boxes(),baseline);const ghosts=await page.locator('.canvas-group-layer').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {x:r.left,width:r.width};}));for(let i=1;i<ghosts.length;i++)close((ghosts[i].x-ghosts[i-1].x-ghosts[i-1].width)/scale,60+20/scale);assert.deepEqual(await page.locator('.canvas-gap-handle').allTextContents(),Array(2).fill((60+20/scale)+' px'));assert.equal(await page.locator('[data-spacing-axis=x]').count(),2);if(value===50&&process.env.RT_E2E_SELECTION_SPACING_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SELECTION_SPACING_SCREENSHOT});await page.mouse.up();await wait(()=>read()!==original);await settled();await verify('x',60+20/scale);lastSource=read();await undo();}
  await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===lastSource);await settled();await undo();await zoom(100);
  let point=await start('y');await page.mouse.move(point.x,point.y+15,{steps:4});await page.mouse.up();await wait(()=>read()!==original);await settled();await verify('y',35);await undo();
  // A second, initially different gap can be the drag origin.
  point=await start('x',1);await page.mouse.move(point.x+10,point.y,{steps:4});await page.mouse.up();await wait(()=>read()!==original);await settled();await verify('x',baseline[2].x-baseline[1].x-baseline[1].width+10);await undo();
  await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Shift+ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();await verify('x',71);assert.equal(await control().evaluate(el=>el===document.activeElement),true);await undo();
  await control('y').click();await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();await verify('y',19);await undo();
  // Mixed spacing stays untouched for a click, cross-axis drag, reversed key step or Escape.
  point=await start();await page.mouse.up();assert.equal(read(),original);point=await start();await page.mouse.move(point.x,point.y+20);await page.mouse.up();assert.equal(read(),original);
  await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');await page.keyboard.press('Enter');assert.equal(read(),original);await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');assert.equal(read(),original);assert.equal(await page.getByRole('treeitem',{selected:true}).count(),3);
  // Negative gaps overlap without reversing spatial order; dimensions stay intact.
  point=await start();await page.mouse.move(point.x-70,point.y,{steps:5});await page.mouse.up();await wait(()=>read()!==original);await settled();await verify('x',-10);await undo();
  point=await start();await page.mouse.move(point.x-1000,point.y);await page.mouse.up();await wait(()=>read()!==original);await settled();await verify('x',1/32-50);const clamped=await boxes();assert.ok(clamped[1].x>clamped[0].x);await undo();
  const target=page.getByLabel('Align to',{exact:true}),reference=await target.locator('option').evaluateAll(els=>els.find(el=>el.textContent.includes('2. B')).value);await target.selectOption(reference);
  await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();await verify('x',61,1);assert.ok(read().includes('<div class="box b" aria-label="B">B</div>'));await undo();
  await target.selectOption('parent');await control('y').click();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();await verify('y',21,0,0);await undo();await target.selectOption('selection');
  await control().click();await page.keyboard.press('ArrowRight');await target.selectOption('parent');assert.equal(await page.locator('.canvas-move-surface').count(),0);assert.equal(read(),original);await target.selectOption('selection');
  await control().click();await page.keyboard.press('ArrowRight');await app.locator('.b').evaluate(el=>el.style.left='141px');await wait(async()=>await page.locator('.canvas-move-surface').count()===0);assert.equal(read(),original);await app.locator('.b').evaluate(el=>el.style.removeProperty('left'));
  await control().click();await page.getByLabel('Style screen scope').selectOption('min-[768px]:');assert.equal(await page.locator('.canvas-move-surface').count(),0);await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();await verify('x',61);await size('390x844');assert.deepEqual(await boxes(),baseline);await size('768x1024');await undo();await page.getByLabel('Style screen scope').selectOption('');
  await select(['A','B','C','Protected']);await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await settled();await wait(async()=>await page.getByText('This property overlaps an important inline style. Edit that source rule first.',{exact:true}).count()>0);assert.equal(read(),original);assert.deepEqual(await boxes(),baseline);assert.deepEqual(errors,[]);
  await select(['A','D']);const cross=()=>app.locator('.a,.other-layer').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {left:r.left,top:r.top,width:r.width,height:r.height};})),before=await cross();await control().click();assert.equal(await page.locator('.canvas-gap-handle').count(),1);await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();const after=await cross();close(after[0].left,before[0].left+1);close(after[1].left,before[1].left);for(let i=0;i<after.length;i++){close(after[i].width,before[i].width);close(after[i].height,before[i].height);close(after[i].top,before[i].top);}await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();assert.equal(await page.getByRole('treeitem',{selected:true}).count(),2);assert.deepEqual(errors,[]);
  console.log(engine+': PASS direct horizontal/vertical spacing at 50/100/200% zoom, mixed/member previews, different containers, reference/frame anchors, negative/clamped gaps, keyboard/focus/no-op/cancellation, content-box preservation, scoped independence and exact atomic undo/redo');
 }catch(error){console.log('DIAGNOSTIC',JSON.stringify({errors,source:read(),boxes:await boxes()}));throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
