'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE for Playwright');
const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-selection-resize-')),file=path.join(root,'index.html');
 const original='<html><head><style>body{margin:0}main{position:relative;margin:20px;border:10px solid #475569;width:600px;height:500px;background:#dbeafe}.box{position:absolute;background:#34d399}.a{left:30px;top:40px;width:50px;height:40px;min-width:20px;max-width:100px;min-height:20px;max-height:80px}.b{left:140px;top:80px;width:60.03px;height:50px;padding:5px;border:2px solid black;min-width:20px;max-width:120.03px;min-height:20px;max-height:100px}.c{left:250px;top:170px;width:50px;height:30px;min-width:10px;max-width:200px;min-height:10px;max-height:100px}.reference{position:absolute;left:400px;top:300px;width:80px;height:50px;background:#f87171}</style></head><body><main><div class="box a" aria-label="A">A</div><div class="box b" aria-label="B">B</div><div class="box c" aria-label="C">C</div><div class="reference">Reference</div><div aria-label="Protected" style="position:absolute;left:0;top:350px;width:50px!important;height:40px">Protected</div></main><section style="position:relative;width:600px;height:100px"><div class="other-layer" aria-label="D" style="position:absolute;left:20px;top:10px;width:40px;height:30px;max-width:80px">D</div></section></body></html>';
 fs.writeFileSync(file,original);const read=()=>fs.readFileSync(file,'utf8'),server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});await once(server,'listening');
 const browser=await browserType.launch(),page=await browser.newPage({viewport:{width:1600,height:1100}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const wait=async fn=>{for(let i=0;i<100;i++){try{if(await fn())return;}catch(e){if(!/Execution context was destroyed/.test(e.message))throw e;}await page.waitForTimeout(100);}throw Error('Selection resize did not settle');},settled=()=>wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true');
 const close=(a,b)=>assert.ok(Math.abs(a-b)<.3,`${a} differs from ${b}`),boxes=()=>app.locator('.box').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect(),p=el.parentElement,pr=p.getBoundingClientRect();return{x:r.left-pr.left-p.clientLeft,y:r.top-pr.top-p.clientTop,width:r.width,height:r.height};}));
 const select=async(names=['A','B','C'])=>{for(let i=0;i<names.length;i++){await page.getByRole('treeitem',{name:'div · '+names[i],exact:true}).click(i?{modifiers:['Meta']}:{ });await wait(async()=>await page.getByRole('treeitem',{selected:true}).count()===i+1);await settled();}};
 const control=()=>page.getByRole('button',{name:'Resize selection on canvas',exact:true});
 const start=async(handle='se')=>{await control().click();assert.equal(await page.locator('.canvas-group-layer').count(),3);const r=await page.locator('[data-resize-handle='+handle+']').boundingBox(),point={x:r.x+r.width/2,y:r.y+r.height/2};await page.mouse.move(point.x,point.y);await page.mouse.down();return point;};
 const undo=async()=>{await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();assert.equal(await page.getByRole('treeitem',{selected:true}).count(),3);};
 const size=async value=>{await page.getByLabel('Screen size',{exact:true}).selectOption(value);await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===Number(value.split('x')[0]));await settled();};
 const zoom=async value=>{await page.getByLabel('Canvas zoom (%)',{exact:true}).fill(String(value));await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Enter');await app.locator('body').evaluate(()=>scrollTo(0,0));await page.locator('#frameWrap').evaluate(async el=>{el.scrollLeft=0;el.scrollTop=96;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});};
 try{
  await page.goto(`http://localhost:${server.address().port}/rt`);await size('768x1024');await select();const baseline=await boxes(),verify=async(dx,dy,width,height)=>{const result=await boxes(),sx=width/270,sy=height/160;for(let i=0;i<result.length;i++){close(result[i].x,30+dx+(baseline[i].x-30)*sx);close(result[i].y,40+dy+(baseline[i].y-40)*sy);close(result[i].width,baseline[i].width*sx);close(result[i].height,baseline[i].height*sy);}return result;};let lastSource;
  for(const value of [50,100,200]){await zoom(value);const scale=value/100,point=await start('e');await page.keyboard.down('Control');await page.mouse.move(point.x+20,point.y,{steps:5});assert.equal(read(),original);assert.deepEqual(await boxes(),baseline);const preview=await page.locator('.canvas-move-preview').boundingBox();close(preview.width,270*scale+20);close(preview.height,160*scale);const ghosts=await page.locator('.canvas-group-layer').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().width));for(let i=0;i<ghosts.length;i++)close(ghosts[i],baseline[i].width*(270+20/scale)/270*scale);if(value===50&&process.env.RT_E2E_SELECTION_RESIZE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SELECTION_RESIZE_SCREENSHOT});await page.mouse.up();await page.keyboard.up('Control');await wait(()=>read()!==original);await settled();await verify(0,0,270+20/scale,160);lastSource=read();await undo();}
  await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===lastSource);await settled();await undo();await zoom(100);
  for(const [handle,dx,dy,modifiers,expected]of [['nw',-15,-10,[],[-15,-10,285,170]],['se',30,10,['Shift'],[0,0,300,160*300/270]],['nw',-20,-15,['Alt'],[-20,-15,310,190]],['e',20,0,['Shift','Alt'],[-20,(160-160*310/270)/2,310,160*310/270]]]){
   const point=await start(handle);await page.keyboard.down('Control');for(const key of modifiers)await page.keyboard.down(key);await page.mouse.move(point.x+dx,point.y+dy,{steps:4});assert.equal(read(),original);await page.mouse.up();for(const key of modifiers.reverse())await page.keyboard.up(key);await page.keyboard.up('Control');await wait(()=>read()!==original);await settled();await verify(...expected);await undo();
  }
  // The member with the tightest content-box bounds controls the whole group.
  for(const [handle,dx,expectedWidth]of [['e',1000,134.03],['w',1000,34]]){const point=await start(handle);await page.keyboard.down('Control');await page.mouse.move(point.x+dx,point.y);const width=await page.locator('.canvas-group-layer').nth(1).evaluate(el=>el.getBoundingClientRect().width);close(width,expectedWidth);await page.mouse.up();await page.keyboard.up('Control');await wait(()=>read()!==original);await settled();close((await boxes())[1].width,expectedWidth);close(await app.locator('.b').evaluate(el=>parseFloat(getComputedStyle(el).maxWidth)),120.03);assert.match(read(),/max-width:120\.03px/);await undo();}
  // A dragged group edge snaps to an external sibling, within member limits.
  let point=await start('e');await page.mouse.move(point.x+96,point.y);assert.equal(await page.locator('[data-snap-axis=x]').count(),1);await page.mouse.up();await wait(()=>read()!==original);await settled();await verify(0,0,370,160);await undo();
  await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();await verify(0,0,271,160);assert.equal(await control().evaluate(el=>el===document.activeElement),true);await undo();
  await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');await page.keyboard.press('Enter');assert.equal(read(),original);await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');assert.equal(read(),original);assert.equal(await page.getByRole('treeitem',{selected:true}).count(),3);
  await control().click();await page.keyboard.press('ArrowRight');await app.locator('.b').evaluate(el=>el.style.maxWidth='119px');await wait(async()=>await page.locator('.canvas-move-surface').count()===0);assert.equal(read(),original);await app.locator('.b').evaluate(el=>el.style.removeProperty('max-width'));
  await control().click();await page.getByLabel('Style screen scope').selectOption('min-[768px]:');assert.equal(await page.locator('.canvas-move-surface').count(),0);await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();await verify(0,0,271,160);await size('390x844');assert.deepEqual(await boxes(),baseline);await size('768x1024');await undo();await page.getByLabel('Style screen scope').selectOption('');
  await select(['A','B','C','Protected']);await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await settled();await wait(async()=>await page.getByText('This property overlaps an important inline style. Edit that source rule first.',{exact:true}).count()>0);assert.equal(read(),original);assert.deepEqual(await boxes(),baseline);assert.deepEqual(errors,[]);
  await select(['A','D']);const cross=()=>app.locator('.a,.other-layer').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {left:r.left,top:r.top,width:r.width,height:r.height};})),before=await cross(),left=Math.min(...before.map(r=>r.left)),span=Math.max(...before.map(r=>r.left+r.width))-left;await control().click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await wait(()=>read()!==original);await settled();const after=await cross();for(let i=0;i<after.length;i++){close(after[i].left,left+(before[i].left-left)*(span+1)/span);close(after[i].width,before[i].width*(span+1)/span);close(after[i].top,before[i].top);close(after[i].height,before[i].height);}await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();assert.equal(await page.getByRole('treeitem',{selected:true}).count(),2);assert.deepEqual(errors,[]);
  console.log(engine+': PASS atomic group resizing at 50/100/200% zoom, affine member previews/bounds, ratio/center modifiers, content-box limits, different containers, snapping, keyboard, focus, cancellation, scoped independence and exact undo/redo');
 }catch(error){console.log('DIAGNOSTIC',JSON.stringify({errors,source:read(),boxes:await boxes()}));throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
