'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE for Playwright');
const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-selection-layout-')),file=path.join(root,'index.html');
 const original='<html><head><style>body{margin:0}main{position:relative;margin:20px;border:10px solid #475569;width:calc(100% - 60px);height:400px;background:#dbeafe}.box{position:absolute;background:#34d399}.a{left:20px;top:40px;width:40px;height:30px}.b{left:160px;top:115px;width:80.03px;height:50px;padding:8px;border:2px solid black;max-width:80.03px;max-height:50px}.c{left:350px;top:240px;width:60px;height:70px}</style></head><body><main><div class="box a" aria-label="A">A</div><div class="box b" aria-label="B">B</div><div class="box c" aria-label="C">C</div></main><div aria-label="Protected" style="position:absolute;left:0!important;top:500px;width:80px;height:40px">Protected</div><div aria-label="Flow">Flow</div></body></html>';
 fs.writeFileSync(file,original);const read=()=>fs.readFileSync(file,'utf8'),server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});await once(server,'listening');
 const browser=await browserType.launch(),page=await browser.newPage({viewport:{width:1600,height:1100}}),app=page.frameLocator('#app'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const wait=async fn=>{for(let i=0;i<100;i++){try{if(await fn())return;}catch(e){if(!/Execution context was destroyed/.test(e.message))throw e;}await page.waitForTimeout(100);}throw Error('Selection layout did not settle');},settled=()=>wait(async()=>await page.locator('#panelBody').getAttribute('aria-busy')!=='true');
 const close=(a,b)=>assert.ok(Math.abs(a-b)<.3,`${a} differs from ${b}`),boxes=()=>app.locator('.box').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect(),p=el.parentElement,pr=p.getBoundingClientRect();return{x:r.left-pr.left-p.clientLeft,y:r.top-pr.top-p.clientTop,width:r.width,height:r.height};}));
 const select=async(names=['A','B','C'])=>{for(let i=0;i<names.length;i++){await page.getByRole('treeitem',{name:names[i]==='main'?'main':'div · '+names[i],exact:true}).click(i?{modifiers:['Meta']}:{ });await wait(async()=>await page.getByRole('treeitem',{selected:true}).count()===i+1);await settled();}};
 const undo=async()=>{await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===original);await settled();assert.equal(await page.getByRole('treeitem',{selected:true}).count(),3);};
 const size=async value=>{await page.getByLabel('Screen size',{exact:true}).selectOption(value);await wait(async()=>await app.locator('body').evaluate(()=>innerWidth)===Number(value.split('x')[0]));await settled();};
 try{
  await page.goto(`http://localhost:${server.address().port}/rt`);await size('768x1024');await select();const baseline=await boxes();
  for(const [label,axis,dim,fraction]of [['Align left','x','width',0],['Align horizontal centers','x','width',.5],['Align right','x','width',1],['Align top','y','height',0],['Align vertical centers','y','height',.5],['Align bottom','y','height',1],['Distribute horizontal spacing','x','width',null],['Distribute vertical spacing','y','height',null]]){
   await page.getByRole('button',{name:label,exact:true}).click();await wait(()=>read()!==original);await settled();const result=await boxes();
   for(let i=0;i<result.length;i++){close(result[i].width,baseline[i].width);close(result[i].height,baseline[i].height);close(result[i][axis==='x'?'y':'x'],baseline[i][axis==='x'?'y':'x']);}
   if(fraction===null){close(result[0][axis],baseline[0][axis]);close(result[2][axis],baseline[2][axis]);close(result[1][axis]-result[0][axis]-result[0][dim],result[2][axis]-result[1][axis]-result[1][dim]);}
   else{const start=Math.min(...baseline.map(r=>r[axis])),end=Math.max(...baseline.map(r=>r[axis]+r[dim]));for(const r of result)close(r[axis]+r[dim]*fraction,start+(end-start)*fraction);}
   const unchanged=read();await page.getByRole('button',{name:label,exact:true}).click();await settled();assert.equal(read(),unchanged,'repeating alignment is a no-op');if(label==='Align horizontal centers'&&process.env.RT_E2E_SELECTION_LAYOUT_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SELECTION_LAYOUT_SCREENSHOT});await undo();assert.deepEqual(await boxes(),baseline);
  }
  const setGap=async(axis,value)=>{await page.getByLabel(axis==='x'?'Horizontal gap (px)':'Vertical gap (px)',{exact:true}).fill(String(value));await page.getByLabel(axis==='x'?'Horizontal gap (px)':'Vertical gap (px)',{exact:true}).press('Enter');};
  const verifyGap=async(axis,value)=>{const result=await boxes(),dim=axis==='x'?'width':'height',sorted=[...result].sort((a,b)=>a[axis]-b[axis]);for(let i=1;i<sorted.length;i++)close(sorted[i][axis]-sorted[i-1][axis]-sorted[i-1][dim],value);for(let i=0;i<result.length;i++){close(result[i].width,baseline[i].width);close(result[i].height,baseline[i].height);close(result[i][axis==='x'?'y':'x'],baseline[i][axis==='x'?'y':'x']);}return result;};
  assert.equal(await page.getByLabel('Horizontal gap (px)',{exact:true}).getAttribute('placeholder'),'Mixed');
  for(const [axis,value]of [['x',25],['y',18],['x',-10]]){await setGap(axis,value);await wait(()=>read()!==original);await settled();const result=await verifyGap(axis,value);assert.deepEqual(result[0],baseline[0]);const unchanged=read();await setGap(axis,value);await settled();assert.equal(read(),unchanged);if(axis==='x'&&value===25&&process.env.RT_E2E_EXACT_SPACING_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_EXACT_SPACING_SCREENSHOT});await undo();}
  await page.getByLabel('Horizontal gap (px)',{exact:true}).fill('77');await page.getByLabel('Horizontal gap (px)',{exact:true}).press('Escape');assert.equal(read(),original);assert.equal(await page.getByRole('treeitem',{selected:true}).count(),3);assert.equal(await page.getByLabel('Horizontal gap (px)',{exact:true}).inputValue(),'');
  await setGap('x',-100000);assert.equal(await page.getByLabel('Horizontal gap (px)',{exact:true}).evaluate(el=>el.checkValidity()),false);assert.equal(read(),original);await page.getByLabel('Horizontal gap (px)',{exact:true}).press('Escape');
  await page.getByLabel('Align to',{exact:true}).selectOption({label:'Layer: 2. B'});assert.equal(await page.getByRole('button',{name:'Distribute horizontal spacing',exact:true}).isDisabled(),true);
  for(const [axis,value]of [['x',20],['y',12]]){await setGap(axis,value);await wait(()=>read()!==original);await settled();const result=await verifyGap(axis,value);assert.deepEqual(result[1],baseline[1]);assert.match(read(),/<div class="box b" aria-label="B">B<\/div>/);await undo();}
  const reference=await app.locator('.b').evaluate(el=>el.outerHTML);
  for(const [label,axis,dim,fraction]of [['Align left','x','width',0],['Align horizontal centers','x','width',.5],['Align right','x','width',1],['Align top','y','height',0],['Align vertical centers','y','height',.5],['Align bottom','y','height',1]]){
   await page.getByRole('button',{name:label,exact:true}).click();await wait(()=>read()!==original);await settled();const result=await boxes();for(const b of result)close(b[axis]+b[dim]*fraction,baseline[1][axis]+baseline[1][dim]*fraction);assert.deepEqual(result[1],baseline[1]);assert.equal(await app.locator('.b').evaluate(el=>el.outerHTML),reference);assert.match(read(),/<div class="box b" aria-label="B">B<\/div>/);await undo();assert.equal(await page.getByLabel('Align to',{exact:true}).locator('option:checked').textContent(),'Layer: 2. B');
  }
  await page.getByLabel('Align to',{exact:true}).selectOption('parent');const parent=await app.locator('main').evaluate(el=>({width:el.clientWidth,height:el.clientHeight}));
  for(const [axis,value]of [['x',24],['y',0]]){await setGap(axis,value);await wait(()=>read()!==original);await settled();const result=await verifyGap(axis,value);close(result[0][axis],0);await undo();}
  for(const [label,axis,dim,fraction]of [['Align left','x','width',0],['Align horizontal centers','x','width',.5],['Align right','x','width',1],['Align top','y','height',0],['Align vertical centers','y','height',.5],['Align bottom','y','height',1],['Distribute horizontal spacing','x','width',null],['Distribute vertical spacing','y','height',null]]){
   await page.getByRole('button',{name:label,exact:true}).click();await wait(()=>read()!==original);await settled();const result=await boxes();if(fraction===null){close(result[0][axis],0);close(result[2][axis]+result[2][dim],parent[dim]);close(result[1][axis]-result[0][axis]-result[0][dim],result[2][axis]-result[1][axis]-result[1][dim]);}else for(const b of result)close(b[axis]+b[dim]*fraction,parent[dim]*fraction);for(let i=0;i<result.length;i++){close(result[i].width,baseline[i].width);close(result[i].height,baseline[i].height);}if(label==='Align horizontal centers'&&process.env.RT_E2E_ALIGNMENT_TARGET_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_ALIGNMENT_TARGET_SCREENSHOT});await undo();assert.equal(await page.getByLabel('Align to',{exact:true}).inputValue(),'parent');
  }
  await page.getByLabel('Align to',{exact:true}).selectOption('selection');
  await page.getByLabel('Style screen scope').selectOption('min-[768px]:');await setGap('x',32);await wait(()=>read()!==original);await settled();await verifyGap('x',32);await size('390x844');assert.deepEqual(await boxes(),baseline);await size('768x1024');await verifyGap('x',32);await undo();
  await page.getByLabel('Style screen scope').selectOption('min-[768px]:');await page.getByRole('button',{name:'Align left',exact:true}).click();await wait(()=>read()!==original);await settled();const scoped=read();await size('390x844');assert.deepEqual(await boxes(),baseline);await size('1440x900');for(const b of await boxes())close(b.x,20);await undo();await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===scoped);await settled();await undo();
  await select(['A','B']);assert.equal(await page.getByRole('button',{name:'Distribute horizontal spacing',exact:true}).isDisabled(),true);
  await select(['A','B','Protected']);assert.equal(await page.getByLabel('Align to',{exact:true}).locator('[value=parent]').evaluate(el=>el.disabled),true);const protectedBefore=await boxes();await page.getByRole('button',{name:'Align right',exact:true}).click();await settled();await wait(async()=>await page.getByText('This property overlaps an important inline style. Edit that source rule first.',{exact:true}).count()>0);assert.equal(read(),original,'one protected layer refuses the entire edit');assert.deepEqual(await boxes(),protectedBefore);
  await page.getByLabel('Align to',{exact:true}).selectOption({label:'Layer: 1. A'});await setGap('x',25);await settled();assert.equal(read(),original,'protected spacing change is atomic');assert.equal(await page.getByLabel('Horizontal gap (px)',{exact:true}).inputValue(),'','refused spacing restores the actual mixed value');
  await page.getByLabel('Align to',{exact:true}).selectOption({label:'Layer: 3. Protected'});await page.getByRole('button',{name:'Align left',exact:true}).click();await wait(()=>read()!==original);await settled();assert.match(read(),/<div aria-label="Protected" style="position:absolute;left:0!important;top:500px;width:80px;height:40px">Protected<\/div>/);await undo();
  await select(['A','Flow']);assert.equal(await page.getByRole('button',{name:'Align left',exact:true}).count(),0);assert.equal(read(),original);
  await select(['A','main']);assert.equal(await page.getByRole('button',{name:'Align left',exact:true}).count(),0);assert.equal(read(),original);
  await app.locator('main').evaluate(el=>el.style.transform='scale(.8)');await select(['A','B']);assert.equal(await page.getByRole('button',{name:'Align left',exact:true}).count(),0);assert.equal(read(),original);assert.deepEqual(errors,[]);
  console.log(engine+': PASS exact positive/negative/zero gaps with fixed reference/frame origin, selection/layer/frame alignment targets, fixed reference source, frame gap distribution, no-op handling, dimensions/other-axis preservation, scoped phone independence, exact atomic undo/redo and protected/flow/nested/transformed refusals');
 }catch(error){console.log('DIAGNOSTIC',JSON.stringify({errors,selected:await page.getByRole('treeitem',{selected:true}).allTextContents(),module:await page.evaluate(()=>typeof RetouchSelectionLayout),panel:(await page.locator('#panelBody').innerText()).slice(0,700),status:(await page.locator('body').innerText()).slice(0,800)}));throw error;}finally{await browser.close();server.retouchIndex.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
