'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const states=[read()],scope=page.getByLabel('Style screen scope',{exact:true}),screen=page.getByLabel('Screen size',{exact:true}),field=name=>page.getByLabel('Shadow 1 '+name,{exact:true}),stack=()=>app.locator('h1').evaluate(el=>parent.RetouchHTMLCSSValues.parseShadows(getComputedStyle(el).boxShadow));
 const open=async()=>{const expand=page.getByRole('button',{name:'Expand Effects section',exact:true});if(await expand.isVisible())await expand.click();if(kind!=='html'){const summary=page.getByText('Shadow stack',{exact:true});if(!await summary.evaluate(el=>el.parentElement.open))await summary.click();}},record=async()=>{await wait(()=>read()!==states.at(-1));await settled();await open();states.push(read());},edit=async(name,value)=>{await field(name).fill(value);await field(name).press('Enter');await record();};
 await open();for(let i=0;i<2;i++){await page.getByRole('button',{name:'Add shadow',exact:true}).click();await record();}await edit('color','#33669980');await edit('X (px)','3');
 if(process.env.RT_E2E_MIXED_SHADOW_COLORS){
  const second=page.getByLabel('Shadow 2 color',{exact:true});await second.fill('oklch(0.7 0.2 140 / 0.6)');await second.press('Enter');await record();
  await page.getByRole('button',{name:'Hide Shadow 1',exact:true}).click();await record();assert.equal(await page.evaluate(shadows=>RetouchPaintPicker.parsePaint(shadows[0].color).alpha,await stack()),0);assert.ok(read().includes('oklch'));
  const secondX=page.getByLabel('Shadow 2 X (px)',{exact:true});await secondX.fill('23');await secondX.press('Enter');await record();assert.equal((await stack())[1].x,23);assert.ok(read().includes('oklch'));assert.equal(await page.getByRole('button',{name:'Show Shadow 1',exact:true}).count(),1);
  await page.getByRole('button',{name:'Show Shadow 1',exact:true}).click();await record();assert.ok(read().includes('oklch'));assert.equal((await stack())[1].x,23);
  console.log(kind+': PASS hidden literal shadow beside editable OKLCH shadow without color conversion');
 }
 await screen.focus();await screen.selectOption('768x1024');await settled();await scope.selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await open();await page.getByRole('button',{name:'Remove shadow 2',exact:true}).click();await record();await edit('color','color(display-p3 0.2 0.4 0.6 / 0.75)');await edit('X (px)','11');const tablet=await stack();assert.equal(tablet.length,1);
 await scope.selectOption('');await settled();await open();assert.equal(await page.getByLabel('Shadow 2 type',{exact:true}).count(),1);assert.equal(await field('X (px)').inputValue(),'3');assert.ok(Math.abs(Number(await field('opacity (%)').inputValue())-128/255*100)<1e-6);await edit('opacity (%)','25');assert.deepEqual(await stack(),tablet);
 await screen.focus();await screen.selectOption('390x844');await settled();await open();const phone=await stack();assert.equal(phone.length,2);assert.equal(phone[0].x,3);const color=await page.evaluate(value=>RetouchPaintPicker.parsePaint(value),phone[0].color);assert.equal(color.alpha,.25);assert.deepEqual(color.channels.map(n=>Math.round(n*255)),[51,102,153]);
 await scope.selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await open();assert.equal(await page.getByLabel('Shadow 2 type',{exact:true}).count(),0);assert.equal(await field('X (px)').inputValue(),'11');assert.equal(await field('opacity (%)').inputValue(),'75');await edit('X (px)','13');assert.deepEqual(await stack(),phone);const source=read();await page.getByRole('button',{name:'Preview edit range',exact:true}).click();await settled();await open();assert.equal(read(),source);assert.deepEqual(await stack(),[{...tablet[0],x:13}]);
 if(process.env.RT_E2E_SHADOW_VISIBILITY){
  const action=async name=>{await page.getByRole('button',{name,exact:true}).click();await record();},paints=async()=>page.evaluate(shadows=>shadows.map(shadow=>RetouchPaintPicker.parsePaint(shadow.color)),await stack());
  await action('Hide Shadow 1');assert.equal((await paints())[0].alpha,0);assert.equal(await field('opacity (%)').inputValue(),'75');
  await edit('X (px)','17');await edit('opacity (%)','40');assert.equal((await stack())[0].x,17);assert.equal((await paints())[0].alpha,0);
  const hidden=await stack(),unchanged=read();await page.getByRole('button',{name:'Edit Shadow 1 color',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit Shadow 1 color',exact:true});await dialog.getByLabel('Color value',{exact:true}).fill('#ff000080');await settled();assert.equal((await paints())[0].alpha,0);assert.equal(read(),unchanged);await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});assert.deepEqual(await stack(),hidden);
  await action('Duplicate shadow 1');assert.ok((await paints()).every(paint=>paint.alpha===0));assert.equal(await page.getByRole('button',{name:'Show Shadow 2',exact:true}).count(),1);
  await edit('X (px)','19');await action('Move shadow 1 down');assert.deepEqual((await stack()).map(shadow=>shadow.x),[17,19]);await action('Show Shadow 1');assert.deepEqual((await paints()).map(paint=>paint.alpha),[.4,0]);
  await screen.focus();await screen.selectOption('390x844');await settled();await open();assert.deepEqual(await stack(),phone);await edit('color','color(display-p3 0.3 0.5 0.7 / 0.6)');assert.deepEqual(await stack(),phone);
  await page.getByRole('button',{name:'Show Shadow 2',exact:true}).click();await record();assert.deepEqual(await stack(),phone);const saved=read();await page.getByRole('button',{name:'Preview edit range',exact:true}).click();await settled();await open();assert.equal(read(),saved);assert.deepEqual((await paints()).map(paint=>paint.alpha),[.6,.4]);assert.equal((await paints())[0].space,'display-p3');
  console.log(kind+': PASS single shadow visibility, hidden geometry/opacity, picker cancellation, duplicate/reorder and inactive source scope');
 }
 for(const expected of states.slice(0,-1).reverse()){await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>read()===expected);await settled();}
 for(const expected of states.slice(1)){await page.getByRole('button',{name:'Redo',exact:true}).click();await wait(()=>read()===expected);await settled();}
 console.log(kind+': PASS source-scoped shadow count/color/geometry, base alpha under tablet override, inactive tablet edit, direct preview and exact undo/redo');
};
