'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{once}=require('node:events'),{promisify}=require('node:util'),execFile=promisify(require('node:child_process').execFile);
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine],{capture}=require('../../src/site-capture.cjs');
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-capture-e2e-')),directory=path.join(root,'captured'),requests=[];
 const source='<!doctype html><html><head><title>Capture fixture</title><style>body{margin:0;background:#fafafa;font-family:Arial}main{display:flex;gap:24px;padding:32px}h1{margin:0;color:rgb(120,30,60);font-size:32px}h1::before{content:"★ ";color:blue}img{width:80px;height:60px}p{max-width:240px}@media(max-width:600px){main{flex-direction:column}}</style></head><body><main><section><h1>Before script</h1><p>Content from a URL</p><input value="Initial"/><a href="/more">More</a></section><img src="/image.svg"/><canvas width="20" height="20"></canvas></main><script>document.querySelector("h1").textContent="Rendered heading";document.querySelector("input").value="Live value";const c=document.querySelector("canvas").getContext("2d");c.fillStyle="red";c.fillRect(0,0,20,20);document.querySelector("h1").onclick=()=>window.clicked=true;</script></body></html>';
 const remote=http.createServer((req,res)=>{requests.push(req.method+' '+req.url);if(req.url==='/missing'){res.writeHead(404);res.end('missing');}else if(req.url==='/image.svg'){res.writeHead(200,{'content-type':'image/svg+xml'});res.end('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="60"><rect width="80" height="60" fill="green"/></svg>');}else{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(source);}});remote.listen(0,'127.0.0.1');await once(remote,'listening');const url='http://127.0.0.1:'+remote.address().port;let browser,server;
 try{
  await assert.rejects(capture({url:url+'/missing',directory:directory+'-missing',wait:0,browserType}),/HTTP 404/);assert.equal(fs.existsSync(directory+'-missing'),false);assert.deepEqual(fs.readdirSync(root),[]);
  const result=await capture({url,directory,width:1100,height:850,wait:0,browserType});assert.equal(result.kind,'rendered-page-capture');const file=path.join(directory,'index.html'),original=fs.readFileSync(file,'utf8');assert.match(original,/Rendered heading/);assert.doesNotMatch(original,/<script|onclick/);assert.match(original,/Live value/);assert.match(original,/data:image\/png/);assert.equal(JSON.parse(fs.readFileSync(path.join(directory,'capture.json'))).sourceUrl,url+'/');
  browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1100,height:850}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(url);const metric=()=>{const h=document.querySelector('h1'),r=h.getBoundingClientRect(),s=getComputedStyle(h);return {x:r.x,y:r.y,width:r.width,height:r.height,color:s.color,font:s.fontSize,before:getComputedStyle(h,'::before').content};};const expected=await page.evaluate(metric),canvasBounds=await page.locator('canvas').boundingBox();await page.screenshot({path:'/tmp/retouch-capture-original-'+engine+'.png'});
  server=require('../../src/html-site.cjs').start({root:directory,port:0,quiet:true});if(!server.listening)await once(server,'listening');const local='http://localhost:'+server.address().port;await page.goto(local);assert.deepEqual(await page.evaluate(metric),expected);const raster=page.locator('img[src^="data:image/png"]');await raster.evaluate(img=>img.decode());assert.deepEqual(await raster.boundingBox(),canvasBounds,'Canvas raster retains its geometry');assert.deepEqual(await raster.evaluate(img=>{const c=document.createElement('canvas');c.width=c.height=1;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,1,1);return [...ctx.getImageData(0,0,1,1).data];}),[255,0,0,255],'Canvas raster retains its pixels');assert.equal(await page.locator('input').inputValue(),'Live value');assert.equal(await page.locator('a').getAttribute('href'),url+'/more');await page.locator('h1').click();assert.equal(await page.evaluate(()=>window.clicked),undefined);await page.screenshot({path:'/tmp/retouch-capture-imported-'+engine+'.png'});
  await page.setViewportSize({width:1600,height:1100});await page.goto(local+'/rt');const app=page.frameLocator('#app');await page.getByRole('treeitem',{name:'h1 · Rendered heading',exact:true}).click();const wait=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(75);}throw Error('Capture edit did not settle');};const settled=()=>wait(()=>page.evaluate(()=>!panelTasks&&!sourceRequests&&!undoBusy));await settled();
  const font=page.getByLabel('Font size (CSS)',{exact:true});await font.fill('40px');await font.press('Tab');await settled();await wait(async()=>await app.locator('h1').evaluate(el=>getComputedStyle(el).fontSize)==='40px');await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),original);
  const disclosure=page.locator('summary').filter({hasText:/^Text content$/});if(await disclosure.count()&&!await disclosure.evaluate(el=>el.parentElement.open))await disclosure.click();await page.getByLabel('Text content',{exact:true}).fill('Edited capture');await page.getByRole('button',{name:'Apply text',exact:true}).click();await settled();await wait(async()=>await app.locator('h1').textContent()==='Edited capture');await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(fs.readFileSync(file,'utf8'),original);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(async()=>await app.locator('h1').textContent()==='Edited capture');
  if(engine==='chromium'){const cli=await execFile(process.execPath,[path.resolve(__dirname,'../../bin/retouch.cjs'),'capture',url,'--out',path.join(root,'cli'),'--width=500','--height=800','--wait=0'],{cwd:fixture});assert.match(cli.stdout,/Captured editable page/);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'cli/capture.json'))).viewport.width,500);const imported=await browser.newPage();await imported.setContent(fs.readFileSync(path.join(root,'cli/index.html'),'utf8'));assert.equal(await imported.locator('main').evaluate(el=>getComputedStyle(el).flexDirection),'column');await imported.close();}
  assert.ok(requests.every(request=>request.startsWith('GET ')));assert.deepEqual(errors,[]);console.log('URL CAPTURE, GEOMETRY, GENERATED CONTENT, LOCAL EDITS, EXACT UNDO/REDO AND CLI PASS',engine);
 }finally{await browser?.close();if(server){server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}remote.closeAllConnections();await new Promise(resolve=>remote.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
