'use strict';
const fs = require('node:fs'), assert = require('node:assert/strict');
exports.run = async ({ page, app, phone, file, original, state }) => {
  const settled = () => page.waitForFunction(() => !undoBusy && !sourceRequests && !panelTasks);
  const wait = async predicate => { for (let i = 0; i < 160; i++) { if (await predicate()) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw Error('Svelte style assertion did not settle'); };
  const style = (frame, property, tag = 'h1') => frame.locator(tag).evaluate((el, property) => getComputedStyle(el).getPropertyValue(property), property);
  const read = () => fs.readFileSync(file, 'utf8');
  const set = async (label, value) => { const input = page.getByLabel(label, { exact: true }); await input.fill(value); await input.press('Tab'); await settled(); };
  await page.getByRole('treeitem', { name: 'h1 · Hello Svelte', exact: true }).click();
  await page.getByLabel('Style screen scope', { exact: true }).selectOption(''); await settled();
  await set('Padding (CSS)', '16px');
  await wait(async () => await style(app, 'padding-top') === '16px' && await style(phone, 'padding-top') === '16px'); await state();
  const padded = read();
  const proveDirective = async () => {
    if (process.env.RT_SVELTE_STYLE_DIRECTIVES !== '1') return;
    const before = read(); await page.locator('#modeBtn').click();
    await app.getByRole('button', { name: 'Toggle directive', exact: true }).click();
    await wait(async () => await style(app, 'opacity') === '0.4');
    assert.equal(await style(phone, 'opacity'), '0.6');
    await app.getByRole('button', { name: 'Toggle directive', exact: true }).click();
    await wait(async () => await style(app, 'opacity') === '0.9');
    await page.locator('#modeBtn').click(); assert.equal(read(), before); await state();
  };
  await proveDirective();

  await set('Font size (CSS)', '24px');
  await wait(async () => await style(app, 'font-size') === '24px' && await style(phone, 'font-size') === '24px'); await state();
  const base = read();
  await page.getByLabel('Screen size', { exact: true }).focus();
  await page.getByLabel('Screen size', { exact: true }).selectOption('768x1024'); await settled();
  await page.getByLabel('Style screen scope', { exact: true }).selectOption('min-[768px]:'); await settled();
  await set('Font size (CSS)', '40px');
  await wait(async () => await style(app, 'font-size') === '40px');
  assert.equal(await style(phone, 'font-size'), '24px'); await state();
  const productionSource = read();
  await page.screenshot({ path: '/tmp/retouch-svelte-css-' + (process.env.RT_E2E_BROWSER || 'chromium') + '.png' });
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled(); assert.equal(read(), base);
  await wait(async () => await style(app, 'font-size') === '24px'); await state();
  await page.getByRole('button', { name: 'Redo', exact: true }).click(); await settled(); assert.equal(read(), productionSource);
  await wait(async () => await style(app, 'font-size') === '40px'); await state(); await proveDirective();
  await page.getByText('Breakpoint options', { exact: true }).click();
  await page.getByRole('button', { name: 'Reset overrides at this size', exact: true }).click(); await settled(); assert.equal(read(), base);
  await wait(async () => await style(app, 'font-size') === '24px'); await state();
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled(); assert.equal(read(), productionSource); await state();
  for (const expected of [base, padded, original]) { await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled(); assert.equal(read(), expected); await state(); }
  await wait(async () => await style(app, 'padding-top') === '0px' && await style(phone, 'padding-top') === '0px');
  await page.getByLabel('Style screen scope', { exact: true }).selectOption(''); await settled();
  await page.getByRole('treeitem', { name: 'h1 · Hello Svelte', exact: true }).click();
  await page.getByRole('treeitem', { name: 'p · Visible branch', exact: true }).click({ modifiers: ['Meta'] });
  await set('Shared Font size', '30px');
  for (const frame of [app, phone]) for (const tag of ['h1', 'p']) await wait(async () => await style(frame, 'font-size', tag) === '30px');
  await state();
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled(); assert.equal(read(), original); await state();
  await page.getByRole('treeitem', { name: 'h1 · Hello Svelte', exact: true }).click();
  console.log('SVELTE RESPONSIVE CSS, MULTI-SELECTION, EXACT UNDO/REDO AND RETAINED STATE PASS');
  return productionSource;
};
