'use strict';
const fs = require('node:fs'), assert = require('node:assert/strict');
exports.run = async ({ page, app, phone:live, file, original:source, state }) => {
  const settled = () => page.waitForFunction(() => !undoBusy && !sourceRequests && !panelTasks);
  const wait = async predicate => { for (let i = 0; i < 160; i++) { if (await predicate()) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw Error('Svelte insertion did not settle'); };
  const retained = state;
  const read = () => fs.readFileSync(file, 'utf8');
  const undo = async () => { await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled(); await retained('undo'); };
  const select = async name => { await page.getByRole('treeitem', { name, exact: true }).click(); await settled(); };
  const action = async name => { const button = page.locator('[data-design-action=' + name + ']'); if (!await button.isVisible()) await page.getByText('Layer actions', { exact: true }).click(); await button.click(); await settled(); await retained(name); };
  const type = async (element, text) => { await wait(async () => await element.getAttribute('contenteditable') === 'true'); assert.equal(await element.evaluate(element => element.ownerDocument.getSelection().toString()), 'New text'); await element.fill(text); await element.press('Control+Enter'); await settled(); await retained('typing ' + text); };
  await select('div · empty'); await action('insertText');
  const inserted = read(); assert.notEqual(inserted, source);
  await type(app.locator('#empty > p'), 'Inserted {count}');
  await live.getByText('Inserted {count}', { exact: true }).waitFor();
  await undo(); assert.equal(read(), inserted);
  await undo(); assert.equal(read(), source);
  await page.getByRole('button', { name: 'Redo', exact: true }).click(); await settled(); assert.equal(read(), inserted);
  await undo(); assert.equal(read(), source);
  await select('div · empty'); await action('insertFrame');
  await app.locator('#empty > div[aria-label=Frame]').waitFor();
  await select('div · Frame'); await action('insertText');
  await type(app.locator('#empty > div > p'), 'Inside frame');
  await live.getByText('Inside frame', { exact: true }).waitFor();
  await undo(); await undo(); await undo(); assert.equal(read(), source);
  const tool = page.getByRole('button', { name: 'Text tool', exact: true });
  await tool.click();
  const bounds = await page.locator('#app').boundingBox();
  const point = await app.locator('main').evaluate(element => { const rect = element.getBoundingClientRect(); return { x: rect.left + 8, y: rect.top + 8, width: innerWidth }; });
  const scale = bounds.width / point.width, x = bounds.x + point.x * scale, y = bounds.y + point.y * scale;
  await page.mouse.click(x, y); await settled();
  const positioned = app.locator('main > p[style]'); await positioned.waitFor();
  const position = await positioned.evaluate(element => { const rect = element.getBoundingClientRect(); return { x: rect.left, y: rect.top }; });
  assert.ok(Math.abs(position.x - point.x) < 1.5 && Math.abs(position.y - point.y) < 1.5, 'Text appears at the canvas click');
  await type(positioned, 'Placed on canvas');
  await undo(); await undo(); assert.equal(read(), source);
  await tool.click(); await page.mouse.move(x, y); await page.mouse.down(); await page.mouse.move(x + 140 * scale, y + 70 * scale, { steps: 5 }); await page.mouse.up(); await settled();
  await positioned.waitFor();
  const geometry = await positioned.evaluate(element => { const style = getComputedStyle(element); return { width: parseFloat(style.width), height: parseFloat(style.height), wrap: style.whiteSpace }; });
  assert.ok(Math.abs(geometry.width - 140) < 2 && Math.abs(geometry.height - 70) < 2, 'Dragged text box uses the chosen dimensions');
  assert.equal(geometry.wrap, 'pre-wrap');
  await type(positioned, 'A text box created by dragging');
  await undo(); await undo(); assert.equal(read(), source);
  await state();
  await select('h1 · Hello Svelte');
  console.log('SVELTE INSERT TEXT/FRAME, CANVAS PLACEMENT, DRAGGED TEXT BOX AND EXACT HISTORY PASS');
};
