'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,app,select,read,wait,settled,original,kind})=>{
 const surface=page.getByLabel('Move SVG vector on canvas',{exact:true}),target=app.locator('[aria-label="Circle"]');
 for(const zoom of ['50','100','200']){
  const input=page.getByLabel('Canvas zoom (%)',{exact:true});await input.fill(zoom);await input.press('Enter');await select('circle','Circle');await target.evaluate(el=>{for(const sibling of el.parentElement.children)if(sibling!==el&&sibling.getAttribute('aria-label')!=='Ellipse'){sibling.dataset.snapFixtureHidden='';sibling.style.visibility='hidden';}});
  const rect=()=>target.evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};}),before=await rect(),f=await page.locator('#app').boundingBox(),scale=f.width/await app.locator('body').evaluate(()=>innerWidth),x=f.x+before.x*scale,y=f.y+before.y*scale;
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+103*scale,y+scale,{steps:5});await surface.waitFor();const snapped=await rect();assert.ok(Math.abs(snapped.x-before.x-100)<.1&&Math.abs(snapped.y-before.y)<.1,'center alignment at '+zoom+'% '+JSON.stringify({before,snapped}));assert.ok(await surface.locator('[data-snap-axis="x"]').count()>0);assert.equal(read(),original);
  await page.keyboard.down('Control');const free=await rect();assert.ok(Math.abs(free.x-before.x-103)<1.1&&Math.abs(free.y-before.y-1)<1.1);assert.equal(await surface.locator('[data-snap-axis]').count(),0,'Control removes guides without a pointer move');await page.keyboard.up('Control');assert.ok(Math.abs((await rect()).x-before.x-100)<.1);
  if(process.env.RT_E2E_SVG_SNAP_SCREENSHOT&&zoom==='100')await page.screenshot({path:process.env.RT_E2E_SVG_SNAP_SCREENSHOT});await page.mouse.up();await surface.waitFor({state:'detached'});await settled();await wait(()=>read()!==original);const changed=read();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===changed);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 }
 await page.getByLabel('Canvas zoom (%)',{exact:true}).fill('100');await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Enter');await select('circle','Circle');
 await app.locator('[aria-label="Box"]').evaluate(el=>el.style.removeProperty('visibility'));
 const layout=await target.evaluate(el=>{const r=el.getBoundingClientRect(),left=el.parentElement.querySelector('[aria-label="Box"]').getBoundingClientRect(),right=el.parentElement.querySelector('[aria-label="Ellipse"]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,destination:(left.right+right.left)/2};}),frame=await page.locator('#app').boundingBox();
 await page.mouse.move(frame.x+layout.x,frame.y+layout.y);await page.mouse.down();await page.mouse.move(frame.x+layout.destination+1,frame.y+layout.y,{steps:5});await surface.waitFor();assert.ok(await surface.locator('[data-spacing-axis="x"]').count()>0,'equal spacing guide is visible');const spaced=await target.evaluate(el=>{const r=el.getBoundingClientRect();return r.x+r.width/2;});assert.ok(Math.abs(spaced-layout.destination)<.1);assert.equal(read(),original);if(process.env.RT_E2E_SVG_SNAP_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_SNAP_SCREENSHOT.replace('.png','-spacing.png')});await page.keyboard.press('Escape');await page.mouse.up();assert.equal(read(),original);
 await app.locator('[data-snap-fixture-hidden]').evaluateAll(nodes=>nodes.forEach(el=>{el.style.removeProperty('visibility');el.removeAttribute('data-snap-fixture-hidden');}));
 await page.getByLabel('Canvas zoom (%)',{exact:true}).fill('100');await page.getByLabel('Canvas zoom (%)',{exact:true}).press('Enter');console.log('SVG SNAP: alignment guides, zoom, live Control override and exact history PASS '+kind);
};
