'use strict';
const assert=require('node:assert/strict');
module.exports=async function resizeWorkflow({page,app,kind,read,wait,settled}){
 const original=read(),surface=page.getByLabel('Resize SVG vector on canvas',{exact:true});
 const cases=[['rect','Box'],['circle','Circle'],['ellipse','Ellipse'],['line','Diagonal'],['line','Horizontal'],['line','Vertical'],['path','Curve'],['polygon','Polygon'],['polyline','Polyline'],['g','Group'],['text','Text'],['image','Picture'],['use','Symbol']];
 const select=async(tag,name)=>{await page.getByRole('treeitem',{name:tag+' · '+name,exact:true}).click();await settled();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));};
 for(const [tag,name]of cases){
  const target=app.locator('svg [aria-label="'+name+'"]');await select(tag,name);
  const snapshot=await target.evaluate(el=>{const g=el.getBBox(),m=el.getScreenCTM();return {g:{x:g.x,y:g.y,width:g.width,height:g.height},m:{a:m.a,b:m.b,c:m.c,d:m.d,e:m.e,f:m.f},transform:el.getAttribute('transform'),data:el.getAttribute('d')||el.getAttribute('points')||el.textContent};});
  const h=page.locator('.svg-resize-handles').getByRole('button',{name:'Resize vector from bottom right',exact:true});await h.waitFor({state:'visible'});const r=await h.boundingBox(),frame=await page.locator('#app').boundingBox(),scale=frame.width/await app.locator('body').evaluate(()=>innerWidth),dx=20,dy=10;
  await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await surface.waitFor();await page.mouse.move(r.x+r.width/2+(snapshot.m.a*dx+snapshot.m.c*dy)*scale,r.y+r.height/2+(snapshot.m.b*dx+snapshot.m.d*dy)*scale,{steps:4});assert.equal(read(),original);
  const preview=await target.getAttribute('transform');assert.notEqual(preview,snapshot.transform,name+' preview; surface visible '+await surface.isVisible());await page.mouse.up();await surface.waitFor({state:'detached'});await settled();await wait(()=>read()!==original);const changed=read();assert.equal(await target.getAttribute('transform'),preview);
  const g={...snapshot.g,width:snapshot.g.width+dx,height:snapshot.g.height+dy},m=snapshot.m,points=[[g.x,g.y],[g.x+g.width,g.y],[g.x+g.width,g.y+g.height],[g.x,g.y+g.height]].map(([x,y])=>({x:m.a*x+m.c*y+m.e,y:m.b*x+m.d*y+m.f})),expected={left:Math.min(...points.map(p=>p.x)),right:Math.max(...points.map(p=>p.x)),top:Math.min(...points.map(p=>p.y)),bottom:Math.max(...points.map(p=>p.y))},actual=await target.evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};});for(const key of Object.keys(expected))assert.ok(Math.abs(actual[key]-expected[key])<(name==='Text'?2:1),name+' '+key+' expected '+expected[key]+' actual '+actual[key]);
  assert.equal(await target.evaluate(el=>el.getAttribute('d')||el.getAttribute('points')||el.textContent),snapshot.data);
  if(name==='Curve'&&process.env.RT_E2E_SVG_RESIZE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_RESIZE_SCREENSHOT});
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);assert.equal(await target.getAttribute('transform'),snapshot.transform);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===changed);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);console.log('SVG RESIZE PASS',kind,name);
 }
 await select('rect','Box');const box=app.locator('[aria-label="Box"]'),initial=await box.getAttribute('transform');await require('./shape-tools.cjs').run(page,'Resize vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowRight');await page.keyboard.press('Shift+ArrowDown');assert.notEqual(await box.getAttribute('transform'),initial);assert.equal(read(),original);await page.keyboard.press('Escape');await surface.waitFor({state:'detached'});assert.equal(await box.getAttribute('transform'),initial);assert.equal(read(),original);
 await require('./shape-tools.cjs').run(page,'Resize vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await settled();await wait(()=>read()!==original);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 // Centered proportional dragging keeps the original center and one scale factor.
 await select('rect','Box');const handle=page.locator('.svg-resize-handles').getByRole('button',{name:'Resize vector from bottom right',exact:true}),hr=await handle.boundingBox();
 const before=await box.evaluate(el=>{const g=el.getBBox(),m=el.getScreenCTM();return {x:g.x+g.width/2,y:g.y+g.height/2,m:[m.a,m.b,m.c,m.d,m.e,m.f]};});
 await page.keyboard.down('Shift');await page.keyboard.down('Alt');await page.mouse.move(hr.x+hr.width/2,hr.y+hr.height/2);await page.mouse.down();await surface.waitFor();await page.mouse.move(hr.x+hr.width/2+20,hr.y+hr.height/2+12,{steps:3});
 const after=await box.evaluate(el=>{const m=el.getScreenCTM();return [m.a,m.b,m.c,m.d,m.e,m.f];}),A=require('../../shell/svg-affine.js'),cx=m=>m[0]*before.x+m[2]*before.y+m[4],cy=m=>m[1]*before.x+m[3]*before.y+m[5];assert.ok(Math.abs(cx(before.m)-cx(after))<.01);assert.ok(Math.abs(cy(before.m)-cy(after))<.01);assert.ok(Math.abs(Math.hypot(after[0],after[1])/Math.hypot(before.m[0],before.m[1])-Math.hypot(after[2],after[3])/Math.hypot(before.m[2],before.m[3]))<.001);assert.ok(!A.equivalent(before.m,after));assert.equal(read(),original);await page.keyboard.press('Escape');await page.mouse.up();await page.keyboard.up('Alt');await page.keyboard.up('Shift');assert.equal(await box.getAttribute('transform'),initial);
 // A concurrent geometry or transform update cancels without erasing that update.
 for(const [attribute,value]of [['width','77'],['transform','translate(17 19)']]){const old=await box.getAttribute(attribute);await require('./shape-tools.cjs').run(page,'Resize vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowRight');await box.evaluate((el,{attribute,value})=>el.setAttribute(attribute,value),{attribute,value});await surface.waitFor({state:'detached'});assert.equal(await box.getAttribute(attribute),value);assert.equal(read(),original);await box.evaluate((el,{attribute,old})=>old===null?el.removeAttribute(attribute):el.setAttribute(attribute,old),{attribute,old});await select('rect','Box');}
 await box.evaluate(el=>el.style.setProperty('transform','none','important'));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await handle.isVisible(),false);await box.evaluate(el=>el.style.removeProperty('transform'));await select('rect','Box');await handle.waitFor({state:'visible'});
 console.log('SVG VECTOR RESIZE: primitives, degenerate lines, curves/arcs, groups, text/image/use, pointer, keyboard and exact history PASS '+kind);
};
