'use strict';
const assert=require('node:assert/strict');
module.exports=async function resizeWorkflow({page,app,kind,read,wait,settled}){
 const original=read(),surface=page.getByLabel('Resize SVG vector on canvas',{exact:true});
 const cases=[['rect','Box'],['circle','Circle'],['ellipse','Ellipse'],['line','Diagonal'],['line','Horizontal'],['line','Vertical'],['path','Curve'],['polygon','Polygon'],['polyline','Polyline'],['g','Group'],['text','Text'],['image','Picture'],['use','Symbol']];
 const select=async(tag,name)=>{await page.getByRole('treeitem',{name:tag+' · '+name,exact:true}).click();await settled();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));};
 if(process.env.RT_E2E_SVG_GAP_EQUAL_ONLY){await require('./svg-gap-equal.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_GAP_KEYBOARD_ONLY){await require('./svg-gap-keyboard.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_GAP_CANVAS_ONLY){await require('./svg-gap-canvas.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_INDIVIDUAL_GAP_ONLY){await require('./svg-individual-gap.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_GAP_ONLY){await require('./svg-selection-gap.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_SINGLE_ALIGN_ONLY){await require('./svg-single-align.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_ALIGN_ONLY){await require('./svg-selection-align.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_ALL_SCRUB_ONLY){const context={page,app,kind,read,wait,settled,select,original};await require('./svg-scrub.cjs')(context);await require('./svg-selection-scrub.cjs')(context);return;}
 if(process.env.RT_E2E_SVG_SELECTION_SCRUB_ONLY){await require('./svg-selection-scrub.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_SCRUB_ONLY){await require('./svg-scrub.cjs')({page,app,kind,read,wait,settled,select,original});return;}
 if(process.env.RT_E2E_SVG_SELECTION_RESIZE_ONLY){const context={page,app,kind,read,wait,settled,select,original};await require('./svg-selection-resize.cjs')(context);await require('./svg-selection-resize-snap.cjs')(context);return;}
 for(const [tag,name]of cases){
  const target=app.locator('svg [aria-label="'+name+'"]');await select(tag,name);
  const snapshot=await target.evaluate(el=>{const g=el.getBBox(),m=el.getScreenCTM();return {g:{x:g.x,y:g.y,width:g.width,height:g.height},m:{a:m.a,b:m.b,c:m.c,d:m.d,e:m.e,f:m.f},transform:el.getAttribute('transform'),data:el.getAttribute('d')||el.getAttribute('points')||el.textContent};});
  const h=page.locator('.svg-resize-handles').getByRole('button',{name:'Resize vector from bottom right',exact:true});await h.waitFor({state:'visible'});const r=await h.boundingBox(),frame=await page.locator('#app').boundingBox(),scale=frame.width/await app.locator('body').evaluate(()=>innerWidth),dx=20,dy=10;
  assert.equal(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.getAttribute('aria-label'),{x:r.x+r.width/2,y:r.y+r.height/2}),'Resize vector from bottom right',name+' resize target remains clickable');await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await surface.waitFor();await page.mouse.move(r.x+r.width/2+(snapshot.m.a*dx+snapshot.m.c*dy)*scale,r.y+r.height/2+(snapshot.m.b*dx+snapshot.m.d*dy)*scale,{steps:4});assert.equal(read(),original);
  const preview=await target.getAttribute('transform');assert.notEqual(preview,snapshot.transform,name+' preview; surface visible '+await surface.isVisible());await page.mouse.up();await surface.waitFor({state:'detached'});await settled();await wait(()=>read()!==original);const changed=read();assert.equal(await target.getAttribute('transform'),preview);
  const g={...snapshot.g,width:snapshot.g.width+dx,height:snapshot.g.height+dy},m=snapshot.m,points=[[g.x,g.y],[g.x+g.width,g.y],[g.x+g.width,g.y+g.height],[g.x,g.y+g.height]].map(([x,y])=>({x:m.a*x+m.c*y+m.e,y:m.b*x+m.d*y+m.f})),expected={left:Math.min(...points.map(p=>p.x)),right:Math.max(...points.map(p=>p.x)),top:Math.min(...points.map(p=>p.y)),bottom:Math.max(...points.map(p=>p.y))},actual=await target.evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};});for(const key of Object.keys(expected))assert.ok(Math.abs(actual[key]-expected[key])<(name==='Text'?2:1),name+' '+key+' expected '+expected[key]+' actual '+actual[key]);
  assert.equal(await target.evaluate(el=>el.getAttribute('d')||el.getAttribute('points')||el.textContent),snapshot.data);
  if(name==='Curve'&&process.env.RT_E2E_SVG_RESIZE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_RESIZE_SCREENSHOT});
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);assert.equal(await target.getAttribute('transform'),snapshot.transform);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===changed);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);console.log('SVG RESIZE PASS',kind,name);
 }
 if(process.env.RT_E2E_SVG_FLIP)await require('./svg-flip.cjs')({page,app,cases,select,read,wait,settled,original,kind});
 if(process.env.RT_E2E_SVG_MOVE)await require('./svg-move-canvas.cjs')({page,app,cases,select,read,wait,settled,original,kind});
 if(process.env.RT_E2E_SVG_ROTATE)await require('./svg-rotate.cjs')({page,app,cases,select,read,wait,settled,original,kind});
 await require('./svg-single-align.cjs')({page,app,kind,read,wait,settled,select,original});await require('./svg-scrub.cjs')({page,app,kind,read,wait,settled,select,original});
 await select('rect','Box');const box=app.locator('[aria-label="Box"]'),initial=await box.getAttribute('transform');await require('./shape-tools.cjs').run(page,'Resize vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowRight');await page.keyboard.press('Shift+ArrowDown');assert.notEqual(await box.getAttribute('transform'),initial);assert.equal(read(),original);await page.keyboard.press('Escape');await surface.waitFor({state:'detached'});assert.equal(await box.getAttribute('transform'),initial);assert.equal(read(),original);
 await require('./shape-tools.cjs').run(page,'Resize vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await settled();await wait(()=>read()!==original);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 // Inspector dimensions follow the authored transform and share exact history.
 await select('rect','Box');const width=page.getByRole('textbox',{name:'Vector width',exact:true}),height=page.getByRole('textbox',{name:'Vector height',exact:true});assert.equal(Number(await width.inputValue()),60);assert.equal(Number(await height.inputValue()),40);
 await width.fill('-1');await width.press('Tab');assert.equal(read(),original);assert.equal(await width.evaluate(el=>el.validity.valid),false);await width.fill('90');await width.press('Tab');await settled();await wait(()=>read()!==original);assert.equal(Number(await width.inputValue()),90);assert.equal(Number(await height.inputValue()),40);
 await page.getByRole('button',{name:'Lock vector proportions',exact:true}).click();await height.fill('80');await height.press('Tab');await settled();assert.equal(Number(await width.inputValue()),180);assert.equal(Number(await height.inputValue()),80);assert.equal(await page.getByRole('button',{name:'Lock vector proportions',exact:true}).getAttribute('aria-pressed'),'true');if(process.env.RT_E2E_SVG_SIZE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_SIZE_SCREENSHOT});
 await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(Number(await width.inputValue()),90);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 await require('./svg-ratio.cjs')({page,app,select,read,wait,settled,original,kind});
 await require('./svg-equations.cjs')({page,select,read,wait,settled,original,kind});
 // Pose uses SVG transforms, with center-preserving rotation and parent coordinates.
 await select('rect','Box');const angle=page.getByRole('textbox',{name:'Vector rotation (°)',exact:true}),x=page.getByRole('textbox',{name:'Vector X',exact:true}),y=page.getByRole('textbox',{name:'Vector Y',exact:true});assert.equal(Number(await angle.inputValue()),-10);
 const center=()=>box.evaluate(el=>{const b=el.getBBox(),m=el.getScreenCTM();return {x:m.a*(b.x+b.width/2)+m.c*(b.y+b.height/2)+m.e,y:m.b*(b.x+b.width/2)+m.d*(b.y+b.height/2)+m.f};}),c0=await center();
 await angle.fill('361');await angle.press('Tab');assert.equal(read(),original);assert.equal(await angle.evaluate(el=>el.validity.valid),false);await angle.fill('40');await angle.press('Tab');await settled();assert.equal(Number(await angle.inputValue()),40);const rotatedSource=read(),c1=await center();assert.ok(Math.abs(c1.x-c0.x)<.01&&Math.abs(c1.y-c0.y)<.01);assert.equal(Number(await width.inputValue()),60);assert.equal(Number(await height.inputValue()),40);
 const initialY=await y.inputValue();await x.fill('77');await x.press('Tab');await settled();assert.equal(Number(await x.inputValue()),77);assert.equal(await y.inputValue(),initialY);await y.fill('-20');await y.press('Tab');await settled();assert.equal(Number(await y.inputValue()),-20);assert.equal(Number(await x.inputValue()),77);if(process.env.RT_E2E_SVG_POSE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_POSE_SCREENSHOT});
 for(let i=0;i<3;i++){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();}await wait(()=>read()===original);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===rotatedSource);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 // Centered proportional dragging keeps the original center and one scale factor.
 await select('rect','Box');const handle=page.locator('.svg-resize-handles').getByRole('button',{name:'Resize vector from bottom right',exact:true}),hr=await handle.boundingBox();
 const before=await box.evaluate(el=>{const g=el.getBBox(),m=el.getScreenCTM();return {x:g.x+g.width/2,y:g.y+g.height/2,m:[m.a,m.b,m.c,m.d,m.e,m.f]};});
 await page.keyboard.down('Shift');await page.keyboard.down('Alt');await page.mouse.move(hr.x+hr.width/2,hr.y+hr.height/2);await page.mouse.down();await surface.waitFor();await page.mouse.move(hr.x+hr.width/2+20,hr.y+hr.height/2+12,{steps:3});
 const after=await box.evaluate(el=>{const m=el.getScreenCTM();return [m.a,m.b,m.c,m.d,m.e,m.f];}),A=require('../../shell/svg-affine.js'),cx=m=>m[0]*before.x+m[2]*before.y+m[4],cy=m=>m[1]*before.x+m[3]*before.y+m[5];assert.ok(Math.abs(cx(before.m)-cx(after))<.01);assert.ok(Math.abs(cy(before.m)-cy(after))<.01);assert.ok(Math.abs(Math.hypot(after[0],after[1])/Math.hypot(before.m[0],before.m[1])-Math.hypot(after[2],after[3])/Math.hypot(before.m[2],before.m[3]))<.001);assert.ok(!A.equivalent(before.m,after));assert.equal(read(),original);await page.keyboard.press('Escape');await page.mouse.up();await page.keyboard.up('Alt');await page.keyboard.up('Shift');assert.equal(await box.getAttribute('transform'),initial);
 // A concurrent geometry or transform update cancels without erasing that update.
 for(const [attribute,value]of [['width','77'],['transform','translate(17 19)']]){const old=await box.getAttribute(attribute);await require('./shape-tools.cjs').run(page,'Resize vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowRight');await box.evaluate((el,{attribute,value})=>el.setAttribute(attribute,value),{attribute,value});await surface.waitFor({state:'detached'});assert.equal(await box.getAttribute(attribute),value);assert.equal(read(),original);await box.evaluate((el,{attribute,old})=>old===null?el.removeAttribute(attribute):el.setAttribute(attribute,old),{attribute,old});await select('rect','Box');}
 await box.evaluate(el=>el.style.setProperty('transform','none','important'));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await handle.isVisible(),false);await box.evaluate(el=>el.style.removeProperty('transform'));await select('rect','Box');await handle.waitFor({state:'visible'});
 console.log('SVG VECTOR RESIZE: primitives, degenerate lines, curves/arcs, groups, text/image/use, pointer, keyboard and exact history PASS '+kind);
};
