'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,app,cases,select,read,wait,settled,original,kind})=>{
 const surface=page.getByLabel('Rotate SVG vector on canvas',{exact:true});
 for(const [tag,name]of cases){
  await select(tag,name);const target=app.locator('svg [aria-label="'+name+'"]'),handle=page.locator('.svg-resize-handles').getByRole('button',{name:'Rotate vector from top right',exact:true});let parentTransform;if(name==='Group'){parentTransform=await target.evaluate(el=>{const old=el.parentElement.getAttribute('transform');el.parentElement.setAttribute('transform','translate(25 10) scale(.9 1.1) rotate(8)');return old;});await select(tag,name);}await handle.waitFor({state:'visible'});
  const r=await handle.boundingBox(),f=await page.locator('#app').boundingBox(),scale=f.width/await app.locator('body').evaluate(()=>innerWidth),start={x:r.x+r.width/2,y:r.y+r.height/2};
  const planned=await target.evaluate((el,{start,f,scale})=>{const w=el.ownerDocument.defaultView,g=el.getBBox(),m=el.getScreenCTM(),parent=el.parentElement.getScreenCTM(),base=parent.inverse().multiply(m),center=new w.DOMPoint(g.x+g.width/2,g.y+g.height/2).matrixTransform(base),a=new w.DOMPoint((start.x-f.x)/scale,(start.y-f.y)/scale).matrixTransform(parent.inverse()),angle=Math.PI/6,dx=a.x-center.x,dy=a.y-center.y,p=new w.DOMPoint(center.x+dx*Math.cos(angle)-dy*Math.sin(angle),center.y+dx*Math.sin(angle)+dy*Math.cos(angle)).matrixTransform(parent);return {end:{x:f.x+p.x*scale,y:f.y+p.y*scale},angle:Math.atan2(base.b,base.a)*180/Math.PI,center:{x:g.x+g.width/2,y:g.y+g.height/2},screen:{x:m.a*(g.x+g.width/2)+m.c*(g.y+g.height/2)+m.e,y:m.b*(g.x+g.width/2)+m.d*(g.y+g.height/2)+m.f},transform:el.getAttribute('transform')};},{start,f,scale});
  await page.mouse.move(start.x,start.y);await page.mouse.down();await surface.waitFor();if(name==='Box')await page.keyboard.down('Shift');await page.mouse.move(planned.end.x,planned.end.y,{steps:4});assert.equal(read(),original);assert.equal(await surface.isVisible(),true);
  const result=await target.evaluate((el,c)=>{const m=el.getScreenCTM(),base=el.parentElement.getScreenCTM().inverse().multiply(m);return {angle:Math.atan2(base.b,base.a)*180/Math.PI,x:m.a*c.x+m.c*c.y+m.e,y:m.b*c.x+m.d*c.y+m.f};},planned.center),expected=name==='Box'?45:planned.angle+30;
  assert.ok(Math.abs(result.angle-expected)<1.5,name+' angle '+result.angle+' expected '+expected);assert.ok(Math.abs(result.x-planned.screen.x)<.01&&Math.abs(result.y-planned.screen.y)<.01,name+' center');const preview=await target.getAttribute('transform');await page.mouse.up();if(name==='Box')await page.keyboard.up('Shift');await surface.waitFor({state:'detached'});await settled();await wait(()=>read()!==original);assert.equal(await target.getAttribute('transform'),preview);const changed=read();
  if(name==='Curve'&&process.env.RT_E2E_SVG_ROTATE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_ROTATE_SCREENSHOT});
  await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===changed);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);if(name==='Group')await target.evaluate((el,old)=>old===null?el.parentElement.removeAttribute('transform'):el.parentElement.setAttribute('transform',old),parentTransform);console.log('SVG ROTATE PASS',kind,name);
 }
 await select('rect','Box');const target=app.locator('[aria-label="Box"]'),old=await target.getAttribute('transform');await page.getByRole('button',{name:'Rotate vector on canvas',exact:true}).click();await surface.waitFor();await page.keyboard.press('ArrowRight');await page.keyboard.press('Shift+ArrowRight');assert.equal(read(),original);assert.notEqual(await target.getAttribute('transform'),old);await page.keyboard.press('Escape');await surface.waitFor({state:'detached'});assert.equal(await target.getAttribute('transform'),old);
 await require('./shape-tools.cjs').run(page,'Rotate vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowLeft');await page.keyboard.press('Enter');await settled();assert.equal(Number(await page.getByRole('textbox',{name:'Vector rotation (°)',exact:true}).inputValue()),-9);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 await require('./shape-tools.cjs').run(page,'Rotate vector on canvas');await surface.waitFor();await page.keyboard.press('ArrowRight');await target.evaluate(el=>el.setAttribute('transform','translate(17 19)'));await surface.waitFor({state:'detached'});assert.equal(await target.getAttribute('transform'),'translate(17 19)');assert.equal(read(),original);await target.evaluate((el,old)=>el.setAttribute('transform',old),old);await select('rect','Box');
 console.log('SVG ROTATION: pointer, center, snapping, keyboard, cancel, external changes and exact history PASS '+kind);
};
