'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,app,select,read,wait,settled,original,kind})=>{
 const hint=page.locator('[data-numeric-scrub-speed]'),box=app.locator('[aria-label="Box"]');
 const begin=async(label,inputDrag=false)=>{const input=page.getByRole('textbox',{name:label,exact:true});await input.scrollIntoViewIfNeeded();const target=inputDrag?input:input.locator('xpath=..').locator('[data-numeric-scrub]'),r=await target.boundingBox(),p={x:r.x+r.width/2,y:r.y+r.height/2};await page.mouse.move(p.x,p.y);if(inputDrag)await page.keyboard.down('Alt');await page.mouse.down();await hint.waitFor();return {input,p};};
 const history=async()=>{await settled();await wait(()=>read()!==original);const changed=read();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===changed);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);};
 for(const name of ['Vector X','Vector Y','Vector rotation (°)','Vector width','Vector height']){
  await select('rect','Box');const before=await box.getAttribute('transform'),initial=Number(await page.getByRole('textbox',{name,exact:true}).inputValue()),{input,p}=await begin(name);await page.mouse.move(p.x+10,p.y,{steps:3});assert.equal(Number(await input.inputValue()),initial+10);assert.equal(read(),original);assert.notEqual(await box.getAttribute('transform'),before,'canvas previews '+name);await page.mouse.up();await hint.waitFor({state:'detached'});await history();
 }
 await select('rect','Box');await page.getByRole('button',{name:'Lock vector proportions',exact:true}).click();let {input,p}=await begin('Vector width');
 for(const [x,y,value,speed]of [[10,0,70,'1x'],[10,-60,70,'2x'],[20,-60,90,'2x'],[20,60,90,'1/2'],[30,60,95,'1/2'],[30,100,95,'1/4'],[40,100,97.5,'1/4']]){await page.mouse.move(p.x+x,p.y+y);assert.equal(Number(await input.inputValue()),value);assert.equal(await hint.textContent(),speed);}
 assert.equal(Number(await page.getByRole('textbox',{name:'Vector height',exact:true}).inputValue()),65);const actual=await box.evaluate(el=>{const m=el.getScreenCTM(),g=el.getBBox();return {width:g.width*Math.hypot(m.a,m.b),height:g.height*Math.hypot(m.c,m.d)};});assert.ok(Math.abs(actual.width-97.5)<.01&&Math.abs(actual.height-65)<.01);if(process.env.RT_E2E_SVG_SCRUB_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_SCRUB_SCREENSHOT});await page.mouse.up();await history();await page.getByRole('button',{name:'Lock vector proportions',exact:true}).click();
 ({input,p}=await begin('Vector width',true));await page.mouse.move(p.x+12,p.y,{steps:3});assert.equal(Number(await input.inputValue()),72);await page.mouse.up();await page.keyboard.up('Alt');await history();
 for(const external of [false,true]){const old=await box.getAttribute('transform');({input,p}=await begin('Vector width'));await page.mouse.move(p.x+10,p.y);if(external){await box.evaluate(el=>el.setAttribute('transform','translate(777 888)'));await hint.waitFor({state:'detached'});assert.equal(await box.getAttribute('transform'),'translate(777 888)');await box.evaluate((el,value)=>el.setAttribute('transform',value),old);}else{await page.keyboard.press('Escape');assert.equal(await box.getAttribute('transform'),old);}await page.mouse.up();assert.equal(read(),original);assert.equal(Number(await input.inputValue()),60);}
 console.log('SVG SCRUB: pose/size preview, four speeds, Alt input, locked ratio, cancellation, ownership and exact history PASS '+kind);
};
