'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,app,select,read,wait,settled,original,kind})=>{
 const surface=page.getByLabel('Resize SVG vector on canvas',{exact:true}),lock=page.getByRole('button',{name:'Lock vector proportions',exact:true}),target=app.locator('[aria-label="Box"]');
 const ratio=()=>target.evaluate(el=>{const m=el.parentElement.getScreenCTM().inverse().multiply(el.getScreenCTM());return Math.hypot(m.a,m.b)/Math.hypot(m.c,m.d);});
 const begin=async()=>{await select('rect','Box');const h=page.locator('.svg-resize-handles').getByRole('button',{name:'Resize vector from bottom right',exact:true}),r=await h.boundingBox(),f=await page.locator('#app').boundingBox(),delta=await target.evaluate((el,f)=>{const m=el.getScreenCTM(),s=f.width/innerWidth;return {x:m.a*20*s,y:m.b*20*s};},f);await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await surface.waitFor();await page.mouse.move(r.x+r.width/2+delta.x,r.y+r.height/2+delta.y,{steps:4});assert.equal(read(),original);};
 assert.equal(await lock.getAttribute('aria-pressed'),'true');
 for(const releaseBeforeCommit of [true,false]){await begin();assert.ok(Math.abs(await ratio()-1)<.001,'canvas honors inspector lock');await page.keyboard.down('Control');assert.ok(await ratio()>1.25,'Control unlocks the same pointer position');assert.equal(read(),original);if(releaseBeforeCommit){await page.keyboard.up('Control');assert.ok(Math.abs(await ratio()-1)<.001,'releasing Control restores ratio without a move');}if(process.env.RT_E2E_SVG_RATIO_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_SVG_RATIO_SCREENSHOT});await page.mouse.up();if(!releaseBeforeCommit)await page.keyboard.up('Control');await surface.waitFor({state:'detached'});await settled();await wait(()=>read()!==original);assert.equal(await lock.getAttribute('aria-pressed'),'true');const changed=read();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===changed);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);}
 await lock.click();await begin();assert.ok(await ratio()>1.25,'unlocked resizing remains independent');await page.keyboard.down('Shift');assert.ok(Math.abs(await ratio()-1)<.001,'Shift constrains without a pointer move');await page.keyboard.up('Shift');assert.ok(await ratio()>1.25,'Shift release restores independent dimensions');await page.keyboard.press('Escape');await surface.waitFor({state:'detached'});await page.mouse.up();assert.equal(read(),original);assert.equal(await lock.getAttribute('aria-pressed'),'false');console.log('SVG RATIO: lock preference, live Control/Shift overrides, exact history and cancellation PASS '+kind);
};
