'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const original=read(),tool=page.getByRole('button',{name:'Text tool',exact:true}),main=app.locator('main');
 await page.evaluate(()=>clearSelection());await wait(()=>tool.isEnabled());await tool.click();assert.equal(read(),original);assert.equal(await tool.getAttribute('aria-pressed'),'true');await page.keyboard.press('Escape');assert.equal(await tool.getAttribute('aria-pressed'),'false');
 const point=async(x=80,y=120)=>{const f=await page.locator('#app').boundingBox(),p=await main.evaluate((el,coordinates)=>{const point=new DOMPoint(...coordinates).matrixTransform(parent.RetouchSVGDraw.nativeSpace(el).matrix);return {x:point.x,y:point.y,width:innerWidth};},[x,y]);return {x:f.x+p.x*f.width/p.width,y:f.y+p.y*f.width/p.width};};
 await tool.focus();await page.keyboard.press('t');const p=await point();await page.keyboard.down('Shift');await page.mouse.click(p.x,p.y);await page.keyboard.up('Shift');await settled();await wait(()=>read()!==original);
 const inserted=read(),text=main.locator(':scope > p').last();await wait(async()=>await text.getAttribute('contenteditable')==='true');assert.equal(await text.evaluate(el=>el.ownerDocument.getSelection().toString()),'New text');
 const position=await text.evaluate(el=>{const css=getComputedStyle(el);return {x:parseFloat(css.left),y:parseFloat(css.top)};});assert.ok(Math.abs(position.x-80)<1.5,'text X matches transformed click');assert.ok(Math.abs(position.y-120)<1.5,'text Y matches transformed click');
 if(process.env.RT_E2E_TEXT_TOOL_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_TEXT_TOOL_SCREENSHOT});
 await page.keyboard.type('Placed text');await page.keyboard.press('Escape');await settled();await wait(()=>read()!==inserted);const edited=read();const font=page.getByLabel(kind==='html'?'Font size (CSS)':'Font size (px)',{exact:true});await font.fill(kind==='html'?'24px':'24');await font.press('Enter');await settled();await wait(()=>text.evaluate(el=>getComputedStyle(el).fontSize==='24px'));await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===edited);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===inserted);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===inserted);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 // A canceled lookup must not insert text when its response arrives later.
 await page.evaluate(()=>clearSelection());let release,entered=false,active=0;const ready=new Promise(resolve=>release=resolve),handler=async route=>{entered=true;active++;try{await ready;await route.continue();}finally{active--;}};await page.route('**/rt/__api/resolve?*',handler);
 try{await tool.click();const p=await point();await page.mouse.click(p.x,p.y);await wait(()=>entered);await page.keyboard.press('Escape');release();await wait(()=>active===0);await settled();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(read(),original);assert.equal(await tool.getAttribute('aria-pressed'),'false');}finally{release();await page.unroute('**/rt/__api/resolve?*',handler);}
 for(const released of [false,true]){
  await page.evaluate(()=>clearSelection());let releaseDrag,enteredDrag=false,activeDrag=0;const readyDrag=new Promise(resolve=>releaseDrag=resolve),delay=async route=>{enteredDrag=true;activeDrag++;try{await readyDrag;await route.continue();}finally{activeDrag--;}};await page.route('**/rt/__api/resolve?*',delay);
  try{
   await tool.click();const a=released?await point(220,200):await point(),b=released?await point():await point(220,200);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:4});await wait(()=>enteredDrag);if(released)await page.mouse.up();releaseDrag();await wait(()=>activeDrag===0);
   if(!released){const surface=page.getByLabel('Draw text box',{exact:true});await surface.waitFor();assert.equal(await tool.getAttribute('aria-pressed'),'true');assert.equal(await page.getByRole('button',{name:'Shape tools',exact:true}).getAttribute('aria-pressed'),'false');assert.equal(await surface.locator('rect').evaluate(el=>getComputedStyle(el).fill),'none');assert.equal(await main.evaluate(el=>el.ownerDocument.getSelection().toString()),'','drawing does not select existing page text');if(process.env.RT_E2E_TEXT_TOOL_SCREENSHOT)await page.screenshot({path:'/tmp/retouch-text-box-preview.png'});await page.mouse.up();}
   await settled();await wait(()=>read()!==original);const boxSource=read(),box=main.locator(':scope > p').last();await wait(async()=>await box.getAttribute('contenteditable')==='true');const geometry=await box.evaluate(el=>{const css=getComputedStyle(el);return {x:parseFloat(css.left),y:parseFloat(css.top),width:parseFloat(css.width),height:parseFloat(css.height),wrap:css.whiteSpace};});for(const [key,value]of Object.entries({x:80,y:120,width:140,height:80}))assert.ok(Math.abs(geometry[key]-value)<2,'dragged text '+key+' '+JSON.stringify(geometry));assert.equal(geometry.wrap,'pre-wrap');
   await page.keyboard.type('A sentence that wraps across several lines inside the drawn text box.');assert.ok(await box.evaluate(el=>{const range=el.ownerDocument.createRange();range.selectNodeContents(el);return range.getClientRects().length>1;}),'drawn text wraps at the chosen width');await page.keyboard.press('Escape');await settled();await wait(()=>read()!==boxSource);const typedSource=read(),wrapField=page.getByLabel('Wrap style',{exact:true}),wrapGroups=wrapField.locator('xpath=ancestor::details');for(let i=0;i<await wrapGroups.count();i++){const group=wrapGroups.nth(i);if(!await group.evaluate(el=>el.open))await group.locator(':scope > summary').click();}const basics=page.getByRole('tab',{name:'Basics',exact:true});if(await basics.getAttribute('aria-selected')!=='true')await basics.click();await wrapField.selectOption('balance');await settled();await wait(()=>read()!==typedSource);const sizingStates=[read()];
   const dimensions=()=>box.evaluate(el=>{const css=getComputedStyle(el);return {width:parseFloat(css.width),height:parseFloat(css.height),wrap:css.whiteSpace,style:css.getPropertyValue('text-wrap-style')};});
   assert.equal(await page.getByRole('group',{name:'Text resizing',exact:true}).evaluate(el=>el.closest('[data-section]').dataset.section),'layout');
   for(const name of ['Auto height','Auto width','Fixed size']){const before=await dimensions();await page.getByRole('group',{name:'Text resizing',exact:true}).getByRole('button',{name,exact:true}).click();await settled();await wait(()=>read()!==sizingStates.at(-1));sizingStates.push(read());const after=await dimensions();assert.equal(after.style,'balance','resizing preserves the separate wrap style');if(name==='Auto height'){assert.ok(Math.abs(after.width-before.width)<.1);assert.equal(after.wrap,'pre-wrap');assert.ok(after.height>16&&Math.abs(after.height-before.height)>1);}else if(name==='Auto width'){assert.ok(after.width>before.width);assert.ok(after.height<before.height);assert.equal(after.wrap,'pre');}else{assert.ok(Math.abs(after.width-before.width)<.1&&Math.abs(after.height-before.height)<.1);assert.equal(after.wrap,'pre-wrap');}}
   if(process.env.RT_E2E_TEXT_TOOL_SCREENSHOT){await page.getByRole('group',{name:'Text resizing',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/retouch-text-resizing.png'});}
   for(const state of sizingStates.slice(0,-1).reverse()){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===state);}
   await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===typedSource);
   await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===boxSource);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
  }finally{releaseDrag();await page.unroute('**/rt/__api/resolve?*',delay);}
 }
 await tool.click();const cancelStart=await point(),cancelEnd=await point(220,200);await page.mouse.move(cancelStart.x,cancelStart.y);await page.mouse.down();await page.mouse.move(cancelEnd.x,cancelEnd.y,{steps:4});await page.getByLabel('Draw text box',{exact:true}).waitFor();await page.keyboard.press('Escape');await page.mouse.up();assert.equal(await page.getByLabel('Draw text box',{exact:true}).count(),0);assert.equal(read(),original,'canceling a text-box drag leaves source unchanged');
 console.log(kind+': PASS armed Text tool, transformed placement, Shift click, immediate typing, exact undo/redo delayed cancellation and held/released text-box drawing');
};
