'use strict';
const assert=require('node:assert/strict');
exports.run=async({page,app,read,wait,settled,kind})=>{
 const original=read(),tool=page.getByRole('button',{name:'Text tool',exact:true}),main=app.locator('main');
 await page.evaluate(()=>clearSelection());await wait(()=>tool.isEnabled());await tool.click();assert.equal(read(),original);assert.equal(await tool.getAttribute('aria-pressed'),'true');await page.keyboard.press('Escape');assert.equal(await tool.getAttribute('aria-pressed'),'false');
 const point=async()=>{const f=await page.locator('#app').boundingBox(),p=await main.evaluate(el=>{const point=new DOMPoint(80,120).matrixTransform(parent.RetouchSVGDraw.nativeSpace(el).matrix);return {x:point.x,y:point.y,width:innerWidth};});return {x:f.x+p.x*f.width/p.width,y:f.y+p.y*f.width/p.width};};
 await tool.focus();await page.keyboard.press('t');const p=await point();await page.keyboard.down('Shift');await page.mouse.click(p.x,p.y);await page.keyboard.up('Shift');await settled();await wait(()=>read()!==original);
 const inserted=read(),text=main.locator(':scope > p').last();await wait(async()=>await text.getAttribute('contenteditable')==='true');assert.equal(await text.evaluate(el=>el.ownerDocument.getSelection().toString()),'New text');
 const position=await text.evaluate(el=>{const css=getComputedStyle(el);return {x:parseFloat(css.left),y:parseFloat(css.top)};});assert.ok(Math.abs(position.x-80)<1.5,'text X matches transformed click');assert.ok(Math.abs(position.y-120)<1.5,'text Y matches transformed click');
 if(process.env.RT_E2E_TEXT_TOOL_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_TEXT_TOOL_SCREENSHOT});
 await page.keyboard.type('Placed text');await page.keyboard.press('Escape');await settled();await wait(()=>read()!==inserted);const edited=read();const font=page.getByLabel(kind==='html'?'Font size (CSS)':'Font size (px)',{exact:true});await font.fill(kind==='html'?'24px':'24');await font.press('Enter');await settled();await wait(()=>text.evaluate(el=>getComputedStyle(el).fontSize==='24px'));await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===edited);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===inserted);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===inserted);await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===original);
 // A canceled lookup must not insert text when its response arrives later.
 await page.evaluate(()=>clearSelection());let release,entered=false,active=0;const ready=new Promise(resolve=>release=resolve),handler=async route=>{entered=true;active++;try{await ready;await route.continue();}finally{active--;}};await page.route('**/rt/__api/resolve?*',handler);
 try{await tool.click();const p=await point();await page.mouse.click(p.x,p.y);await wait(()=>entered);await page.keyboard.press('Escape');release();await wait(()=>active===0);await settled();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(read(),original);assert.equal(await tool.getAttribute('aria-pressed'),'false');}finally{release();await page.unroute('**/rt/__api/resolve?*',handler);}
 console.log(kind+': PASS armed Text tool, transformed placement, Shift click, immediate typing, exact undo/redo and delayed cancellation');
};
