'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),{once}=require('node:events');
const fixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture)throw Error('Set RT_INSPECTOR_FIXTURE');const engine=process.env.RT_E2E_BROWSER||'chromium',browserType=require(path.join(fixture,'node_modules/playwright'))[engine];
(async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-collection-ui-'))),file=path.join(root,'.retouch/variables.json');fs.writeFileSync(path.join(root,'index.html'),'<html><body><h1>Collections</h1></body></html>');process.env.RETOUCH_STATE_DIR=path.join(root,'history');let server,browser;
 try{
  server=require('../../src/html-site.cjs').start({root,port:0,quiet:true});await once(server,'listening');browser=await browserType.launch();const page=await browser.newPage({viewport:{width:1500,height:1100}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://localhost:'+server.address().port+'/rt');await page.frameLocator('#app').locator('h1').waitFor();
  const dialog=page.getByRole('dialog',{name:'Variable collections',exact:true}),read=()=>JSON.parse(fs.readFileSync(file,'utf8')),wait=async fn=>{for(let i=0;i<150;i++){if(await fn())return;await page.waitForTimeout(50);}throw Error('Timed out');},settled=()=>wait(async()=>await dialog.locator('fieldset').first().isEnabled());
  await page.getByRole('button',{name:'Variables',exact:true}).click();await dialog.getByLabel('New collection name',{exact:true}).fill('Theme');await dialog.getByRole('button',{name:'Create collection',exact:true}).click();await settled();assert.equal(read().collections[0].name,'Theme');
  await dialog.getByText('Collection modes',{exact:true}).click();await dialog.getByLabel('New mode name',{exact:true}).fill('Dark');await dialog.getByRole('button',{name:'Add mode',exact:true}).click();await settled();const collection=read().collections[0],dark=collection.modes.find(mode=>mode.name==='Dark').id;
  await dialog.getByLabel('Collection variable name',{exact:true}).fill('Surface');await dialog.getByLabel('Default value',{exact:true}).fill('#ffffff');await dialog.getByLabel('Dark value',{exact:true}).fill('#111111');await dialog.getByRole('button',{name:'Save collection variable',exact:true}).click();await settled();const surface=read().variables[0];assert.equal(surface.values[dark],'#111111ff');
  await dialog.getByLabel('Collection variable',{exact:true}).selectOption('');await dialog.getByLabel('Collection variable name',{exact:true}).fill('Canvas');for(const mode of ['Default','Dark']){await dialog.getByLabel(mode+' value source',{exact:true}).selectOption('alias');await dialog.getByLabel(mode+' alias',{exact:true}).selectOption(surface.id);}await dialog.getByRole('button',{name:'Save collection variable',exact:true}).click();await settled();assert.equal(read().variables[1].values[dark].alias,surface.id);
  for(const [type,first,second]of [['number',24,0.5],['boolean',true,false],['string','Welcome','Good night']]){
   await dialog.getByLabel('Collection variable',{exact:true}).selectOption('');await dialog.getByLabel('Variable type',{exact:true}).selectOption(type);await dialog.getByLabel('Collection variable name',{exact:true}).fill(type+' sample');
   for(const [mode,value]of [['Default',first],['Dark',second]]){const field=dialog.getByLabel(mode+' value',{exact:true});if(type==='boolean')await field.selectOption(String(value));else await field.fill(String(value));}
   await dialog.getByRole('button',{name:'Save collection variable',exact:true}).click();await settled();const saved=read().variables.find(item=>item.name===type+' sample');assert.equal(saved.values[collection.defaultMode],first);assert.equal(saved.values[dark],second);
  }
  const grid=dialog.getByRole('table',{name:'Theme variables',exact:true});await wait(async()=>await grid.getByRole('row').count()===6);await grid.getByRole('button',{name:'Edit Canvas in Dark',exact:true}).click();const aliasCell=grid.getByLabel('Canvas in Dark',{exact:true});assert.equal(await aliasCell.evaluate(el=>el===document.activeElement),true);assert.equal(await aliasCell.inputValue(),surface.id);await aliasCell.press('Escape');assert.equal(await dialog.isVisible(),true,'Escape cancels the cell, not the dialog');
  await grid.getByRole('button',{name:'Edit Canvas in Dark',exact:true}).click();const canvasSource=grid.getByLabel('Canvas in Dark source',{exact:true});await canvasSource.selectOption('literal');await aliasCell.fill('#123456');await canvasSource.selectOption('alias');assert.equal(await aliasCell.inputValue(),surface.id);await canvasSource.selectOption('literal');assert.equal(await aliasCell.inputValue(),'#123456','Switching source retains both drafts');await aliasCell.press('Enter');await wait(async()=>await aliasCell.count()===0);assert.equal(read().variables.find(item=>item.name==='Canvas').values[dark],'#123456ff');await grid.getByRole('button',{name:'Edit Canvas in Dark',exact:true}).click();await canvasSource.selectOption('alias');await aliasCell.press('Enter');await dialog.getByText('Choose a variable for Dark.',{exact:true}).waitFor();await aliasCell.selectOption(surface.id);await aliasCell.press('Enter');await wait(async()=>await aliasCell.count()===0);assert.equal(read().variables.find(item=>item.name==='Canvas').values[dark].alias,surface.id);
  const beforeCycle=fs.readFileSync(file,'utf8');await grid.getByRole('button',{name:'Edit Surface in Dark',exact:true}).click();await grid.getByLabel('Surface in Dark source',{exact:true}).selectOption('alias');const surfaceCell=grid.getByLabel('Surface in Dark',{exact:true});await surfaceCell.selectOption(read().variables.find(item=>item.name==='Canvas').id);await surfaceCell.press('Enter');await dialog.getByText(/Variable alias cycle:/).waitFor();assert.equal(fs.readFileSync(file,'utf8'),beforeCycle);assert.equal(await surfaceCell.evaluate(el=>el===document.activeElement),true);await surfaceCell.press('Escape');
  const search=dialog.getByRole('searchbox',{name:'Search collection variables',exact:true}),beforeSearch=fs.readFileSync(file,'utf8');await search.fill('SAMPLE number');assert.equal(await grid.getByRole('row').count(),2);await search.fill('missing-variable');await dialog.getByRole('status',{name:'Variable search results',exact:true}).getByText('No matching variables',{exact:true}).waitFor();assert.equal(await grid.getByRole('row').count(),1);await search.fill('color');assert.equal(await grid.getByRole('row').count(),3);await grid.getByRole('button',{name:'Edit variable Canvas',exact:true}).click();assert.equal(await search.inputValue(),'color','Search survives selection changes');await search.fill('');await grid.getByRole('button',{name:'Edit Surface in Dark',exact:true}).click();await grid.getByLabel('Surface in Dark',{exact:true}).fill('#bada55');await search.fill('number');assert.equal(await grid.getByLabel('Surface in Dark',{exact:true}).isVisible(),false);await search.fill('');assert.equal(await grid.getByLabel('Surface in Dark',{exact:true}).inputValue(),'#bada55','Filtering retains the unfinished cell draft');await grid.getByLabel('Surface in Dark',{exact:true}).press('Escape');assert.equal(fs.readFileSync(file,'utf8'),beforeSearch);
  const inline=async(name,value)=>{await grid.getByRole('button',{name:'Edit '+name+' in Dark',exact:true}).click();const field=grid.getByLabel(name+' in Dark',{exact:true});if(name==='boolean sample')await field.selectOption(value);else await field.fill(value);await field.press('Enter');await wait(async()=>await grid.getByLabel(name+' in Dark',{exact:true}).count()===0);};
  const beforeInline=read();for(const [name,value,expected]of [['Surface','#223344','#223344ff'],['number sample','7.5',7.5],['boolean sample','true',true],['string sample','Inline words','Inline words']]){await inline(name,value);assert.equal(read().variables.find(item=>item.name===name).values[dark],expected);assert.equal(await grid.getByRole('button',{name:'Edit '+name+' in Dark',exact:true}).evaluate(el=>el===document.activeElement),true);await inline(name,String(beforeInline.variables.find(item=>item.name===name).values[dark]));}
  const inlineUndo=fs.readFileSync(file,'utf8');await inline('Surface','#abcdef');await dialog.getByRole('button',{name:'Close variable collections',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>fs.readFileSync(file,'utf8')===inlineUndo);await page.getByRole('button',{name:'Variables',exact:true}).click();await grid.waitFor();
  const unchanged=fs.readFileSync(file,'utf8');await grid.getByRole('button',{name:'Edit number sample in Dark',exact:true}).click();await grid.getByLabel('number sample in Dark',{exact:true}).fill('');await grid.getByLabel('number sample in Dark',{exact:true}).press('Enter');await dialog.getByText('Enter a number for Dark.',{exact:true}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),unchanged);await grid.getByLabel('number sample in Dark',{exact:true}).press('Escape');
  await grid.getByRole('button',{name:'Edit variable Canvas',exact:true}).click();assert.equal(await dialog.getByLabel('Collection variable name',{exact:true}).inputValue(),'Canvas');assert.equal(await dialog.getByLabel('Collection variable name',{exact:true}).evaluate(el=>el===document.activeElement),true);
  await page.setViewportSize({width:420,height:640});await grid.scrollIntoViewIfNeeded();await grid.evaluate(el=>el.parentElement.scrollLeft=el.parentElement.scrollWidth);assert.equal(await grid.locator('tbody th').first().evaluate(el=>{const name=el.getBoundingClientRect(),viewport=el.closest('.variable-grid-scroll').getBoundingClientRect();return name.left>=viewport.left&&name.right<=viewport.right;}),true,'Variable names remain visible across mode columns');await grid.evaluate(el=>el.parentElement.scrollLeft=0);assert.equal(await dialog.getByRole('button',{name:'Close variable collections',exact:true}).evaluate(el=>{const box=el.getBoundingClientRect();return box.top>=0&&box.bottom<=innerHeight;}),true,'Close remains visible while the collection scrolls');assert.equal(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth&&el.getBoundingClientRect().right<=innerWidth),true,'Variable table scrolls within a compact dialog');if(process.env.RT_E2E_VARIABLE_GRID_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_VARIABLE_GRID_SCREENSHOT});await page.setViewportSize({width:1500,height:1100});
  const beforePreview=fs.readFileSync(file,'utf8');await dialog.getByText('Preview variable modes',{exact:true}).click();await dialog.getByRole('table',{name:'Resolved variable values',exact:true}).waitFor();await dialog.getByLabel('Preview mode for Theme',{exact:true}).selectOption(dark);await wait(async()=>await dialog.getByRole('row',{name:'Theme / Canvas',exact:true}).textContent().then(text=>text.includes('#111111ff')&&text.includes('(Dark)')));if(process.env.RT_E2E_MODE_PREVIEW_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_MODE_PREVIEW_SCREENSHOT});assert.equal(fs.readFileSync(file,'utf8'),beforePreview);assert.match(await dialog.getByRole('row',{name:'Theme / boolean sample',exact:true}).textContent(),/false/);assert.match(await dialog.getByRole('row',{name:'Theme / number sample',exact:true}).textContent(),/0.5/);await dialog.getByText('Preview variable modes',{exact:true}).click();
  await dialog.getByLabel('Collection variable',{exact:true}).selectOption(surface.id);const linked=fs.readFileSync(file,'utf8');await dialog.getByRole('button',{name:'Delete collection variable',exact:true}).click();await settled();await dialog.getByText('An alias refers to a missing variable.',{exact:true}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),linked);
  await dialog.getByLabel('Collection variable name',{exact:true}).fill('Renamed surface');await dialog.getByRole('button',{name:'Save collection variable',exact:true}).click();await settled();assert.equal(read().variables[0].id,surface.id);assert.equal(read().variables[0].name,'Renamed surface');
  const bounds=await dialog.boundingBox();assert.ok(Math.abs(bounds.x+(bounds.width/2)-750)<2,'collection dialog is centered');
  if(process.env.RT_E2E_COLLECTION_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_COLLECTION_SCREENSHOT});
  await dialog.getByRole('button',{name:'Close variable collections',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await wait(()=>fs.readFileSync(file,'utf8')===linked);await page.reload();await page.getByRole('button',{name:'Variables',exact:true}).click();await dialog.getByLabel('Collection variable',{exact:true}).selectOption(surface.id);assert.equal(await dialog.getByLabel('Collection variable name',{exact:true}).inputValue(),'Surface');
  const external=read();external.collections[0].name='External theme';fs.writeFileSync(file,JSON.stringify(external,null,2)+'\n');const changed=fs.readFileSync(file,'utf8');await dialog.getByLabel('Collection name',{exact:true}).fill('Stale change');await dialog.getByRole('button',{name:'Rename collection',exact:true}).click();await settled();await dialog.getByText('Variable collections changed. Reload before saving.',{exact:true}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),changed);await grid.getByRole('button',{name:'Edit Surface in Dark',exact:true}).click();const staleCell=grid.getByLabel('Surface in Dark',{exact:true});await staleCell.fill('#fedcba');await staleCell.press('Enter');await wait(async()=>await dialog.locator('fieldset').first().isEnabled());await dialog.getByText('Variable collections changed. Reload before saving.',{exact:true}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),changed);assert.equal(await staleCell.inputValue(),'#fedcba','Conflict preserves the unsaved cell draft');if(process.env.RT_E2E_INLINE_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_INLINE_SCREENSHOT});await staleCell.press('Escape');assert.deepEqual(errors,[]);console.log('VARIABLE COLLECTION UI PASS',engine);
 }finally{await browser?.close();if(server){server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
