'use strict';
const assert=require('node:assert/strict');
module.exports=async({page,app,kind,read,wait,settled})=>{
 const target=app.locator('h1'),original=await target.textContent(),states=[read()],field=()=>page.getByLabel('Vertical trim',{exact:true});
 const geometry=()=>target.evaluate(el=>{const c=getComputedStyle(el),r=el.getBoundingClientRect(),walker=el.ownerDocument.createTreeWalker(el,NodeFilter.SHOW_TEXT),tops=[];let n;while(n=walker.nextNode()){if(!n.textContent.trim())continue;const range=el.ownerDocument.createRange();range.selectNodeContents(n);tops.push(range.getBoundingClientRect().top-r.top);}return {trim:c.getPropertyValue('text-box-trim'),edge:c.getPropertyValue('text-box-edge'),height:r.height,width:r.width,lineHeight:c.lineHeight,overflow:c.overflow,tops};});
 const open=async()=>{const opener=page.locator('summary[aria-label="Type settings"]');if(!await opener.evaluate(el=>el.parentElement.open))await opener.click();await page.getByRole('tab',{name:'Basics',exact:true}).click();};
 const edit=async value=>{await open();await field().selectOption(value);await settled();await wait(()=>read()!==states.at(-1));states.push(read());assert.equal(await target.textContent(),original);};
 await page.getByLabel('Style screen scope').selectOption('');await settled();const baseline=await geometry();assert.equal(baseline.trim,'none');assert.equal(baseline.tops.length,2);
 await edit('trim-both cap alphabetic');await wait(async()=>(await geometry()).trim==='trim-both');const trimmed=await geometry();assert.equal(trimmed.edge,'cap alphabetic');assert.ok(trimmed.height<baseline.height-20);assert.equal(trimmed.width,baseline.width);assert.equal(trimmed.lineHeight,baseline.lineHeight);assert.equal(trimmed.overflow,baseline.overflow);assert.ok(Math.abs((trimmed.tops[1]-trimmed.tops[0])-(baseline.tops[1]-baseline.tops[0]))<1);assert.ok(trimmed.tops[0]<baseline.tops[0]-10);
 assert.equal(await page.frameLocator('iframe.type-preview').locator('body > div > br').count(),1);
 await wait(async()=>page.frameLocator('iframe.type-preview').locator('body > div').evaluate(el=>getComputedStyle(el).getPropertyValue('text-box-trim')==='trim-both'));
 if(process.env.RT_E2E_VERTICAL_TRIM_SCREENSHOT)await page.screenshot({path:process.env.RT_E2E_VERTICAL_TRIM_SCREENSHOT});
 const library=page.locator('details').filter({has:page.locator(':scope > summary',{hasText:'Saved text styles'})});await library.locator(':scope > summary').click();await page.getByLabel('Text style name',{exact:true}).fill('Cap height');await page.getByRole('button',{name:'Save current typography',exact:true}).click();await page.getByText('Text style saved.',{exact:true}).waitFor();
 const properties=library.locator('details').filter({has:page.locator(':scope > summary',{hasText:'Style properties'})});await properties.locator(':scope > summary').click();assert.equal(await properties.locator('dt',{hasText:'Vertical trim'}).count(),1);assert.equal(await properties.locator('dt').evaluateAll(nodes=>nodes.every(n=>n.textContent.trim().length>0)),true);assert.match(await properties.locator('dt',{hasText:'Vertical trim'}).locator('xpath=following-sibling::dd[1]').textContent(),/cap/);assert.equal(read(),states.at(-1));states.push(read()); // Catalog creation is its own undo entry with unchanged document bytes.
 await page.getByRole('button',{name:'Apply text style',exact:true}).click();await settled();await wait(()=>read()!==states.at(-1));states.push(read());assert.equal((await geometry()).trim,'trim-both');assert.equal((await geometry()).height,trimmed.height);
 await page.getByLabel('Style screen scope').selectOption(kind==='html'?'min-[768px]:':'md:');await settled();await edit('normal');await wait(async()=>(await geometry()).trim==='none');assert.equal((await geometry()).height,baseline.height);
 await page.getByLabel('Screen size',{exact:true}).selectOption('390x844');await settled();assert.equal((await geometry()).trim,'trim-both');assert.equal((await geometry()).height,trimmed.height);
 await page.getByLabel('Screen size',{exact:true}).selectOption('768x1024');await settled();await open();await page.getByRole('button',{name:'Reset vertical trim',exact:true}).click();await settled();await wait(()=>read()!==states.at(-1));states.push(read());assert.equal((await geometry()).trim,'trim-both');
 await page.getByLabel('Style screen scope').selectOption('');await settled();await open();await page.getByRole('button',{name:'Reset vertical trim',exact:true}).click();await settled();await wait(()=>read()!==states.at(-1));states.push(read());assert.deepEqual(await geometry(),baseline);
 for(let n=states.length-2;n>=0;n--){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===states[n]);}
 for(let n=1;n<states.length;n++){await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();await wait(()=>read()===states[n]);}
 for(let n=states.length-2;n>=0;n--){await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();await wait(()=>read()===states[n]);}
 assert.deepEqual(await geometry(),baseline);console.log('VERTICAL TRIM PASS '+kind+': cap geometry, preserved line spacing/content/width, preview, saved style labels, screen isolation, reset and exact source undo/redo');
};
