'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{createRequire}=require('node:module');
const fixture=process.env.RT_SVELTE_FIXTURE,browserFixture=process.env.RT_INSPECTOR_FIXTURE,engine=process.env.RT_E2E_BROWSER||'chromium';if(!fixture||!browserFixture)throw Error('Set RT_SVELTE_FIXTURE and RT_INSPECTOR_FIXTURE.');
(async()=>{const load=createRequire(path.join(fixture,'package.json')),vite=await import(pathToFileURL(load.resolve('vite')).href),{svelte}=await import(pathToFileURL(load.resolve('@sveltejs/vite-plugin-svelte')).href),root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-vite-svelte-'));let server,browser,page;const errors=[];
 try{
 fs.symlinkSync(path.join(fixture,'node_modules'),path.join(root,'node_modules'),'dir');fs.writeFileSync(path.join(root,'package.json'),'{"type":"module"}');fs.writeFileSync(path.join(root,'index.html'),'<div id="app"></div><script type="module" src="/main.js"></script>');fs.writeFileSync(path.join(root,'main.js'),'import {mount} from "svelte";import App from "./App.svelte";mount(App,{target:document.getElementById("app")});');const file=path.join(root,'App.svelte');let original='<script>let count=$state(0);let draft=$state("Initial");let show=$state(true);</script><main><h1>Hello Svelte</h1><button onclick={()=>count++}>Count {count}</button><input aria-label="Draft" bind:value={draft}/><button onclick={()=>show=!show}>Toggle</button>{#if show}<p>Visible branch</p>{:else}<p>Other branch</p>{/if}<a href="/old">Link</a></main><style>h1{color:rgb(150,20,30)}main{padding:24px}</style>';if(process.env.RT_SVELTE_NO_STYLE==='1')original=original.replace(/<style>[\s\S]*?<\/style>/,'');fs.writeFileSync(file,original);
 const config={root,cacheDir:path.join(root,'.vite'),configFile:false,plugins:[require('../../src/vite.cjs').retouch(),svelte({configFile:false})],server:{host:'127.0.0.1',port:0},logLevel:'warn'};server=await vite.createServer(config);await server.listen();const url='http://localhost:'+server.httpServer.address().port;browser=await require(path.join(browserFixture,'node_modules/playwright'))[engine].launch();page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(45000);let dropped=0,replies=0;const sockets=[];
 if(process.env.RT_SVELTE_RECOVERY==='1')await page.routeWebSocket('**/*',socket=>{
  const remote=socket.connectToServer(),record={socket,stale:null};sockets.push(record);
  socket.onMessage(message=>remote.send(message));
  remote.onMessage(message=>{let payload;try{payload=JSON.parse(message.toString());}catch{}if(payload?.event==='retouch:svelte-source'){dropped++;record.stale??=message;return;}if(payload?.event==='retouch:svelte-snapshot')replies++;socket.send(message);});
 });
 const replay=async frames=>{
  if(process.env.RT_SVELTE_RECOVERY!=='1')return;
  assert.ok(dropped>5,'The browser test must actually lose live updates');assert.ok(replies>5,'Missed updates must recover through authoritative snapshots');
  for(const frame of frames)await frame.locator('h1').evaluate(async()=>{const {createHotContext}=await import('/@vite/client');createHotContext('/retouch-recovery-test').on('retouch:test:barrier',()=>window.retouchRecoveryBarrier=true);});
  for(const {socket,stale}of sockets){if(stale)socket.send(stale);socket.send(JSON.stringify({type:'custom',event:'retouch:test:barrier',data:{}}));}
  for(const frame of frames){await frame.locator('h1').evaluate(()=>new Promise(resolve=>{const check=()=>window.retouchRecoveryBarrier?resolve():requestAnimationFrame(check);check();}));assert.equal(await frame.locator('h1').textContent(),'Hello Svelte');}
  const waitForDrop=async before=>{for(let attempt=0;attempt<100;attempt++){if(dropped>before)return;await new Promise(resolve=>setTimeout(resolve,50));}throw Error('The external source update was not intercepted');};
  let before=dropped;fs.writeFileSync(file,original.replace('Hello Svelte','Resumed Svelte'));await waitForDrop(before);
  for(const frame of frames)assert.equal(await frame.locator('h1').textContent(),'Hello Svelte');
  for(const frame of frames){await frame.locator('h1').evaluate(()=>window.dispatchEvent(new Event('focus')));await frame.getByRole('heading',{name:'Resumed Svelte',exact:true}).waitFor();}await state();
  before=dropped;fs.writeFileSync(file,original);await waitForDrop(before);
  for(const frame of frames){await frame.locator('h1').evaluate(()=>window.dispatchEvent(new Event('focus')));await frame.getByRole('heading',{name:'Hello Svelte',exact:true}).waitFor();}await state();
  console.log('RECOVERY PASS: '+dropped+' dropped updates, '+replies+' snapshots, old broadcasts replayed without rollback, foreground recovery retained state');
 };
page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/rt');const app=page.frameLocator('#app');await app.locator('h1').waitFor();await page.getByLabel('Screen size',{exact:true}).selectOption('1440x900');await page.getByRole('button',{name:'Compare screens',exact:true}).click();const phone=page.frameLocator('iframe[title="Phone comparison preview"]');await phone.locator('h1').waitFor();
 if(process.env.RT_AGENT_BROWSER_VERIFY==='1'){
  const run=async args=>(await require('node:util').promisify(require('node:child_process').execFile)('npx',['--yes','agent-browser','--session','retouch-svelte-css',...args],{cwd:os.tmpdir(),timeout:60000})).stdout;
  try{console.log(await run(['open',url+'/rt']));console.log(await run(['snapshot','-i']));console.log(await run(['eval',`JSON.stringify({content:document.body.innerText.trim().length>0,overlay:!!document.querySelector('vite-error-overlay,[data-nextjs-dialog],#webpack-dev-server-client-overlay'),preview:!!document.querySelector('#app')?.contentDocument?.querySelector('h1')})`]));console.log(await run(['screenshot','/tmp/retouch-svelte-agent-browser.png']));}finally{await run(['close']);}
 }

 await page.locator('#modeBtn').click();await app.getByRole('button',{name:'Count 0',exact:true}).click();await app.getByRole('button',{name:'Count 1',exact:true}).waitFor();for(const frame of [app,phone]){await frame.getByLabel('Draft',{exact:true}).fill('Retained');await frame.locator('h1').evaluate(el=>{window.svelteDocument=el.ownerDocument;});}await page.locator('#modeBtn').click();
 const settled=()=>page.waitForFunction(()=>!panelTasks&&!sourceRequests&&!undoBusy),read=()=>fs.readFileSync(file,'utf8');await app.locator('h1').click();await page.waitForFunction(()=>document.querySelector('#app').contentDocument.querySelector('h1').isContentEditable);await app.locator('h1').fill('Edited {literal} & Svelte');await app.locator('h1').press('Control+Enter');await settled();await app.getByRole('heading',{name:'Edited {literal} & Svelte',exact:true}).waitFor();await phone.getByRole('heading',{name:'Edited {literal} & Svelte',exact:true}).waitFor();assert.ok(read().includes('Edited &#123;literal&#125; &amp; Svelte'));const changed=read();
 const state=async()=>{assert.equal(await app.getByRole('button',{name:'Count 1',exact:true}).count(),1);for(const frame of [app,phone])assert.deepEqual(await frame.getByLabel('Draft',{exact:true}).evaluate(el=>({draft:el.value,same:window.svelteDocument===el.ownerDocument})),{draft:'Retained',same:true});};await state();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),original);await app.getByRole('heading',{name:'Hello Svelte',exact:true}).waitFor();await phone.getByRole('heading',{name:'Hello Svelte',exact:true}).waitFor();await state();await page.getByRole('button',{name:'Redo',exact:true}).click();await settled();assert.equal(read(),changed);await app.getByRole('heading',{name:'Edited {literal} & Svelte',exact:true}).waitFor();await state();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();
 let productionSource;const h1=await app.locator('h1').getAttribute('data-rt');assert.match(h1,/^[a-f0-9]{10}$/);await page.locator('#modeBtn').click();await app.getByRole('button',{name:'Toggle',exact:true}).click();await app.getByText('Other branch',{exact:true}).waitFor();await app.getByRole('button',{name:'Toggle',exact:true}).click();await app.getByText('Visible branch',{exact:true}).waitFor();assert.equal(await app.locator('h1').getAttribute('data-rt'),h1);await page.locator('#modeBtn').click();await app.getByText('Visible branch',{exact:true}).click();await page.waitForFunction(()=>document.querySelector('#app').contentDocument.querySelector('p').isContentEditable);await app.locator('p').fill('Changed branch');await app.locator('p').press('Control+Enter');await settled();await phone.getByText('Changed branch',{exact:true}).waitFor();await page.locator('#modeBtn').click();await app.getByRole('button',{name:'Toggle',exact:true}).click();await app.getByText('Other branch',{exact:true}).waitFor();await app.getByRole('button',{name:'Toggle',exact:true}).click();await app.getByText('Changed branch',{exact:true}).waitFor();await state();await page.locator('#modeBtn').click();await page.getByRole('button',{name:'Undo',exact:true}).click();await settled();assert.equal(read(),original);await state();productionSource=await require('./svelte-css.cjs').run({page,app,phone,file,original,state});await replay([app,phone]);await state();fs.writeFileSync(file,original.replace('$state(0)','$state(5)'));await app.getByRole('button',{name:'Count 5',exact:true}).waitFor();await phone.getByRole('button',{name:'Count 5',exact:true}).waitFor();fs.writeFileSync(file,original);await app.getByRole('button',{name:'Count 0',exact:true}).waitFor();await phone.getByRole('button',{name:'Count 0',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Edit text',exact:true}).isVisible(),true);assert.equal(await page.getByText('Style editing is not available for this source yet.',{exact:true}).count(),0);await page.screenshot({path:'/tmp/retouch-vite-svelte-'+engine+'.png'});assert.deepEqual(errors,[]);await browser.close();browser=null;await server.close();server=null;
 await vite.build({...config,plugins:[require('../../src/vite.cjs').retouch(),svelte({configFile:false})]});for(const name of fs.readdirSync(path.join(root,'dist'),{recursive:true})){const full=path.join(root,'dist',name);if(fs.statSync(full).isFile()&&/\.(js|html)$/.test(name))assert.ok(!/data-rt|retouch-svelte-source|__retouch_source_/.test(fs.readFileSync(full,'utf8')),'Production must omit Retouch source markers');}assert.equal(read(),original);fs.writeFileSync(file,productionSource);await vite.build({...config,plugins:[require('../../src/vite.cjs').retouch(),svelte({configFile:false})]});let compiledCSS='',compiledJS='';for(const name of fs.readdirSync(path.join(root,'dist'),{recursive:true})){const full=path.join(root,'dist',name);if(!fs.statSync(full).isFile())continue;if(name.endsWith('.css'))compiledCSS+=fs.readFileSync(full,'utf8');if(name.endsWith('.js'))compiledJS+=fs.readFileSync(full,'utf8');}assert.match(compiledCSS,/data-rt-style/);assert.match(compiledCSS,/font-size:40px/);assert.match(compiledJS,/data-rt-style/);assert.doesNotMatch(compiledJS,/data-rt-revision|retouch-svelte-source|__retouch_source_/);fs.writeFileSync(file,original);console.log(engine+': Svelte source text, exact undo/redo, retained state/documents, conditional identity and production exclusion passed');
 }catch(error){if(page&&!page.isClosed()){console.error(await page.locator('#toasts').textContent());console.error(errors);await page.screenshot({path:'/tmp/retouch-vite-svelte-failure-'+engine+'.png'});}throw error;}finally{await browser?.close();await server?.close();fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
