'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{createRequire}=require('node:module');
const fixture=process.env.RT_VITE_FIXTURE,browserFixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture||!browserFixture)throw Error('Set RT_VITE_FIXTURE and RT_INSPECTOR_FIXTURE');
(async()=>{const load=createRequire(path.join(fixture,'package.json')),vite=await import(pathToFileURL(load.resolve('vite')).href),react=(await import(pathToFileURL(load.resolve('@vitejs/plugin-react')).href)).default,root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-vite-react-'));let server,browser;
try{
 fs.symlinkSync(path.join(fixture,'node_modules'),path.join(root,'node_modules'),'dir');fs.mkdirSync(path.join(root,'src'));fs.writeFileSync(path.join(root,'package.json'),'{}');fs.writeFileSync(path.join(root,'index.html'),'<html><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>');fs.writeFileSync(path.join(root,'src/main.jsx'),"import React from 'react';import {createRoot} from 'react-dom/client';import App from './App.jsx';createRoot(document.getElementById('root')).render(<App/>);");const file=path.join(root,'src/App.jsx'),source="import React,{useState} from 'react';export default function App(){const [count,setCount]=useState(0);return <main><h1>Hello Vite</h1><button onClick={()=>setCount(count+1)}>Count {count}</button><p>Editable React source</p></main>}";fs.writeFileSync(file,source);
 const base=process.env.RT_VITE_BASE||'/';const config={root,base,publicDir:process.env.RT_VITE_PUBLIC_DIR||'public',configFile:false,plugins:[require('../../src/vite.cjs').retouch(),react()],server:{host:'127.0.0.1',port:0},logLevel:'warn'};server=await vite.createServer(config);await server.listen();const url='http://localhost:'+server.httpServer.address().port;
 browser=await require(path.join(browserFixture,'node_modules/playwright'))[process.env.RT_E2E_BROWSER||'chromium'].launch();const page=await browser.newPage(),live=await browser.newPage(),errors=[];for(const p of [page,live]){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});}await live.goto(url+base);await live.getByRole('button',{name:'Count 0'}).click();await live.getByRole('button',{name:'Count 1'}).waitFor();await live.evaluate(()=>window.__viteDocument=document);
 await page.goto(url+'/rt?retouchFixture=1#heading');const app=page.frameLocator('#app');await app.locator('h1').waitFor();await page.waitForURL(u=>u.pathname==='/rt'+base);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.location.pathname),base);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.location.search),'?retouchFixture=1');assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.location.hash),'#heading');await app.locator('h1').evaluate(e=>e.ownerDocument.defaultView.__viteDocument=e.ownerDocument);assert.match(await app.locator('h1').getAttribute('data-rt'),/^[a-f0-9]{10}$/);assert.equal(fs.readFileSync(file,'utf8'),source);
 await app.locator('h1').click();await page.waitForFunction(()=>document.querySelector('#app').contentDocument.querySelector('h1').isContentEditable);await app.locator('h1').fill('Edited in Vite');await app.locator('h1').press('Control+Enter');try{await live.getByRole('heading',{name:'Edited in Vite'}).waitFor();}catch(error){console.error('VITE EDIT STATE',JSON.stringify({source:fs.readFileSync(file,'utf8'),errors,editor:await page.evaluate(()=>({toasts:document.querySelector('#toasts')?.textContent,status:document.querySelector('#status')?.textContent})),live:await live.locator('body').innerText()}));throw error;}assert.ok(fs.readFileSync(file,'utf8').includes('Edited in Vite'));await live.getByRole('button',{name:'Count 1'}).waitFor();assert.equal(await live.evaluate(()=>window.__viteDocument===document),true);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.defaultView.__viteDocument===e.ownerDocument),true);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await live.getByRole('heading',{name:'Hello Vite'}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),source);assert.equal((await fetch(url+'/rt/__api/health')).status,200);const svg='<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="red"/></svg>';const uploaded=await page.evaluate(async svg=>{const response=await fetch('/rt/__api/upload?name=fixture.svg',{method:'POST',headers:{'x-retouch-token':window.__RT_TOKEN},body:svg});return {status:response.status,...await response.json()};},svg);assert.equal(uploaded.status,200);assert.equal(uploaded.ok,true);assert.ok(uploaded.src.startsWith(base+'rt-assets/'));assert.equal(await (await fetch(url+uploaded.src)).text(),svg);assert.equal(await page.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();return img.naturalWidth;},uploaded.src),10);assert.equal(fs.readFileSync(path.join(root,config.publicDir,'rt-assets',path.basename(uploaded.src)),'utf8'),svg);assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/retouch-vite-react.png',caret:'initial'});await browser.close();browser=null;await server.close();server=null;
 await vite.build({...config,plugins:[require('../../src/vite.cjs').retouch(),react()],build:{minify:false}});for(const file of fs.readdirSync(path.join(root,'dist'),{recursive:true})){const full=path.join(root,'dist',file);if(fs.statSync(full).isFile()&&/\.(js|html)$/.test(file))assert.equal(/data-rt(?:-revision|-react-scale|=)|retouch\.group-scale\.runtime/.test(fs.readFileSync(full,'utf8')),false,'Production output must not contain editor instrumentation');}console.log('VITE REACT SOURCE EDIT, EXACT UNDO, HMR STATE AND PRODUCTION EXCLUSION PASS',load('vite/package.json').version);
}finally{await browser?.close();await server?.close();fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
