'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{createRequire}=require('node:module');
const fixture=process.env.RT_VITE_FIXTURE,browserFixture=process.env.RT_INSPECTOR_FIXTURE;if(!fixture||!browserFixture)throw Error('Set RT_VITE_FIXTURE and RT_INSPECTOR_FIXTURE');
(async()=>{const load=createRequire(path.join(fixture,'package.json')),vite=await import(pathToFileURL(load.resolve('vite')).href),vue=(await import(pathToFileURL(load.resolve('@vitejs/plugin-vue')).href)).default,root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-vite-vue-'));let server,browser;const vueOptions=process.env.RT_VUE_STRIP_COMMENTS==='1'?{template:{compilerOptions:{comments:false}}}:{};
try{
 fs.symlinkSync(path.join(fixture,'node_modules'),path.join(root,'node_modules'),'dir');fs.mkdirSync(path.join(root,'src'));fs.writeFileSync(path.join(root,'package.json'),'{}');fs.writeFileSync(path.join(root,'index.html'),'<html><body><div id="root"></div><script type="module" src="/src/main.js"></script></body></html>');fs.writeFileSync(path.join(root,'src/main.js'),"import {createApp} from 'vue';import App from './App.vue';createApp(App).mount('#root');");const file=path.join(root,'src/App.vue');let source=`<script setup lang="ts">import {ref} from 'vue';const count=ref(0);const items=[1,2];const clickEvent="click";const handlers={mouseenter:()=>{}};</script>
<template><main><h1>Hello
  Vite</h1><button @click="count++">Count {{ count }}</button><p v-for="item in items" :key="item">Editable Vue source</p>${process.env.RT_VUE_STRUCTURE==='1'?'<section id="order"><div aria-label="First"><span>First</span></div><div>Second</div><div>Third</div></section>':''}${process.env.RT_VUE_INSERT==='1'?'<div id="empty"/>':''}${process.env.RT_VUE_REPARENT==='1'?'<section id="move-from"><div aria-label="Mover"><span>Movable</span></div><div>Neighbor</div></section><section id="move-to"/>':''}${process.env.RT_VUE_BATCH==='1'?'<section id="batch-left"><div aria-label="Batch A"><span>A</span></div><div>Keep</div></section><section id="batch-right"><div aria-label="Batch B">B</div></section>':''}${process.env.RT_VUE_LINKS==='1'?'<section><a aria-label="Docs" href="/old" target="_blank" @click.prevent="count++"><strong>Read</strong> more</a><a aria-label="Bound" :href="String(count)">Bound link</a></section>':''}${process.env.RT_VUE_RICH_STYLES==='1'?'<h2 id="rich-styled"><span aria-label="Styled run">Styled</span> tail</h2>':''}${process.env.RT_VUE_RICH_SPLIT==='1'?'<div id="rich-split"><p><span title="Split run">Split here</span></p></div>':''}${process.env.RT_VUE_LIVE_TEXT==='1'?'<h2 id="rich-live">Hello {{ count }} <em>times</em>!</h2><h3 id="rich-empty">{{ count > 100 ? count : "" }}</h3>':''}${process.env.RT_VUE_BOUND_TEXT==='1'?"<h2 id=\"bound-rich\"><span :class=\"count % 2 ? 'odd' : 'even'\" :style=\"{ color: count % 2 ? 'rgb(180, 20, 20)' : 'rgb(20, 20, 180)' }\" @[clickEvent]=\"count = count === 2 ? 3 : 2\" v-on=\"handlers\">Click {{ count }}</span> tail</h2>":''}${process.env.RT_VUE_BOUND_LINK==='1'?"<h2 id=\"bound-link\">Read <a :href=\"'/docs/' + count\" @click.prevent=\"count = count === 2 ? 3 : 2\">the docs</a> now</h2>":''}${process.env.RT_VUE_COMMENTS==='1'?'<h2 id="comment-rich">\n  <!-- before <tag> & {{ raw }} \r\n second line -->\n  Hello<!-- between --> {{ count }} <em @click="count = count === 2 ? 3 : 2">world<!-- nested -->!</em>\n  <!-- after -->\n</h2>':''}${process.env.RT_VUE_STRIP_COMMENTS==='1'?'<h3 id="comment-pair">Pair {{ count }}<!-- pair -->{{ count + 1 }}</h3><h3 id="comment-gap"><em>First</em><!-- between --><strong>Last</strong><!-- end --></h3>':''}${process.env.RT_VUE_ORDER==='1'?'<section id="order-many">'+['A','B','C','D','E'].map(name=>'<div>Order '+name+'</div>').join('')+'</section>':''}</main></template>
<style scoped>h1 { color: rgb(24, 24, 27); } main { padding: 24px; font-family: sans-serif; }</style>`;for(const [flag,attribute,label]of [['RT_VUE_RICH_STYLES','aria-label','Styled run'],['RT_VUE_RICH_SPLIT','title','Split run']])if(process.env[flag]==='1'){const adapter=require('../../src/adapters/vue.cjs');for(const [width,value]of [[0,'19px'],[768,'27px']]){const elements=adapter.collect(source,'src/App.vue').elements,element=elements.find(element=>element.tag==='span'&&element.attributes.some(attr=>attr.name===attribute&&attr.value===label)),hash=adapter.contentHash(source),result=adapter.planOp({source,elements,element,hash,file,relPath:'src/App.vue'},{type:'setCSS',fileHash:hash,width,property:'font-size',value});assert.equal(result.ok,true,result.reason);source=result.edits[0].after;}}fs.writeFileSync(file,source);
 const base=process.env.RT_VITE_BASE||'/';const config={root,base,cacheDir:path.join(root,'.vite'),publicDir:process.env.RT_VITE_PUBLIC_DIR||'public',configFile:false,plugins:[require('../../src/vite.cjs').retouch(),vue(vueOptions)],server:{host:'127.0.0.1',port:0},logLevel:'warn'};server=await vite.createServer(config);await server.listen();const url='http://localhost:'+server.httpServer.address().port;
 browser=await require(path.join(browserFixture,'node_modules/playwright'))[process.env.RT_E2E_BROWSER||'chromium'].launch();const page=await browser.newPage(),live=await browser.newPage(),errors=[];for(const p of [page,live]){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});}await live.goto(url+base);try{await live.getByRole('button',{name:'Count 0'}).click();}catch(error){console.error('VUE STARTUP',JSON.stringify({errors,body:await live.locator('body').innerText()}));throw error;}await live.getByRole('button',{name:'Count 1'}).waitFor();await live.evaluate(()=>window.__viteDocument=document);
 await page.goto(url+'/rt?retouchFixture=1#heading');const app=page.frameLocator('#app');await app.locator('h1').waitFor();await page.waitForURL(u=>u.pathname==='/rt'+base);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.location.pathname),base);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.location.search),'?retouchFixture=1');assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.location.hash),'#heading');await app.locator('h1').evaluate(e=>e.ownerDocument.defaultView.__viteDocument=e.ownerDocument);assert.match(await app.locator('h1').getAttribute('data-rt'),/^[a-f0-9]{10}$/);assert.equal(fs.readFileSync(file,'utf8'),source);await page.locator('#modeBtn').click();await app.getByRole('button',{name:'Count 0',exact:true}).click();await app.getByRole('button',{name:'Count 1',exact:true}).click();await app.getByRole('button',{name:'Count 2',exact:true}).waitFor();await page.locator('#modeBtn').click();
 await app.locator('h1').click();await page.waitForFunction(()=>document.querySelector('#app').contentDocument.querySelector('h1')?.isContentEditable);await app.locator('h1').fill('Edited in Vite');await app.locator('h1').press('Control+Enter');try{await live.getByRole('heading',{name:'Edited in Vite'}).waitFor();}catch(error){console.error('VUE EDIT STATE',JSON.stringify({source:fs.readFileSync(file,'utf8'),errors,editor:await page.evaluate(()=>({toasts:document.querySelector('#toasts')?.textContent,status:document.querySelector('#status')?.textContent})),live:await live.locator('body').innerText()}));throw error;}assert.ok(fs.readFileSync(file,'utf8').includes('Edited in Vite'));await live.getByRole('button',{name:'Count 1'}).waitFor();assert.equal(await live.evaluate(()=>window.__viteDocument===document),true);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.defaultView.__viteDocument===e.ownerDocument),true);await app.getByRole('button',{name:'Count 2',exact:true}).waitFor();
 await page.getByRole('button',{name:'Undo',exact:true}).click();await live.getByRole('heading',{name:'Hello Vite'}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),source);await live.getByRole('button',{name:'Count 1'}).waitFor();assert.equal(await live.evaluate(()=>window.__viteDocument===document),true);
 await page.waitForFunction(()=>!document.querySelector('#redoBtn').disabled);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.defaultView.__viteDocument===e.ownerDocument),true);await app.getByRole('button',{name:'Count 2',exact:true}).waitFor();const headingId=await app.locator('h1').getAttribute('data-rt');assert.match(headingId,/^[a-f0-9]{10}$/);assert.equal(await live.locator('h1').getAttribute('data-rt'),headingId);assert.equal(await live.locator('main > p').count(),2);assert.equal(await live.locator('main > p').first().getAttribute('data-rt'),await live.locator('main > p').last().getAttribute('data-rt'));
 // A second edit after undo proves plugin-vue's hot template cache retained IDs.
 await app.locator('h1').click();await page.waitForFunction(()=>document.querySelector('#app').contentDocument.querySelector('h1')?.isContentEditable);await app.locator('h1').fill('Literal {{ count }}');await app.locator('h1').press('Control+Enter');await live.getByRole('heading',{name:'Literal {{ count }}',exact:true}).waitFor();await live.getByRole('button',{name:'Count 1'}).waitFor();assert.equal(await live.locator('h1').getAttribute('data-rt'),headingId);await page.getByRole('button',{name:'Undo',exact:true}).click();await live.getByRole('heading',{name:'Hello Vite'}).waitFor();assert.equal(fs.readFileSync(file,'utf8'),source);await page.waitForFunction(()=>!document.querySelector('#redoBtn').disabled);assert.equal(await app.locator('h1').evaluate(e=>e.ownerDocument.defaultView.__viteDocument===e.ownerDocument),true);await app.getByRole('button',{name:'Count 2',exact:true}).waitFor();assert.equal(await app.locator('h1').textContent(),'Hello Vite');
 const productionSource=process.env.RT_VUE_CSS==='1'?await require('./vue-css.cjs').run({page,app,live,file,source}):null;
 if(process.env.RT_VUE_TEXT_STYLES==='1')await require('./vue-text-styles.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_STRUCTURE==='1')await require('./vue-structure.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_COPY==='1')await require('./vue-copy.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_INSERT==='1')await require('./vue-insert.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_REPARENT==='1')await require('./vue-reparent.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_BATCH==='1')await require('./vue-batch.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_BATCH_PARENT==='1')await require('./vue-batch-parent.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_LINKS==='1')await require('./vue-links.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_FRAME==='1')await require('./vue-frame.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_ORDER==='1')await require('./vue-order-selection.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_RICH_STYLES==='1')await require('./vue-rich-styles.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_RICH_SPLIT==='1')await require('./vue-rich-split.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_RICH==='1')await require('./vue-rich-text.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_BOUND_TEXT==='1')await require('./vue-bound-text.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_BOUND_LINK==='1')await require('./vue-bound-link.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_COMMENTS==='1')await require('./vue-comments.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_STRIP_COMMENTS==='1')await require('./vue-stripped-comments.cjs').run({page,app,live,file,source});
 if(process.env.RT_VUE_LIVE_TEXT==='1')await require('./vue-live-text.cjs').run({page,app,live,file,source,errors});
 const typography=page.locator('iframe.type-preview').first();assert.equal(await typography.getAttribute('sandbox'),'allow-same-origin');await page.waitForFunction(()=>{const doc=document.querySelector('iframe.type-preview')?.contentDocument;return !!doc?.querySelector('style')&&doc.querySelectorAll('script').length===0;});
 assert.equal((await fetch(url+'/rt/__api/health')).status,200);const svg='<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="red"/></svg>';const uploaded=await page.evaluate(async svg=>{const response=await fetch('/rt/__api/upload?name=fixture.svg',{method:'POST',headers:{'x-retouch-token':window.__RT_TOKEN},body:svg});return {status:response.status,...await response.json()};},svg);assert.equal(uploaded.status,200);assert.equal(uploaded.ok,true);assert.ok(uploaded.src.startsWith(base+'rt-assets/'));assert.equal(await (await fetch(url+uploaded.src)).text(),svg);assert.equal(await page.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();return img.naturalWidth;},uploaded.src),10);assert.equal(fs.readFileSync(path.join(root,config.publicDir,'rt-assets',path.basename(uploaded.src)),'utf8'),svg);if(errors.length)console.error('VUE FRAME ERRORS',JSON.stringify({errors,frames:await page.locator('iframe.type-preview').evaluateAll(frames=>frames.map(frame=>({srcdoc:frame.srcdoc,html:frame.contentDocument?.documentElement?.outerHTML})))}));assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/retouch-vite-vue-'+(process.env.RT_E2E_BROWSER||'chromium')+'.png',caret:'initial'});await browser.close();browser=null;await server.close();server=null;
 await vite.build({...config,plugins:[require('../../src/vite.cjs').retouch(),vue(vueOptions)],build:{minify:false}});for(const file of fs.readdirSync(path.join(root,'dist'),{recursive:true})){const full=path.join(root,'dist',file);if(fs.statSync(full).isFile()&&/\.(js|html)$/.test(file))assert.equal(/data-rt(?!-style\b)|retouch\.group-scale\.runtime/.test(fs.readFileSync(full,'utf8')),false,'Production output must not contain editor instrumentation');}if(productionSource){fs.writeFileSync(file,productionSource);await vite.build({...config,plugins:[require('../../src/vite.cjs').retouch(),vue(vueOptions)],build:{minify:false}});let scripts='',styles='';for(const entry of fs.readdirSync(path.join(root,'dist'),{recursive:true})){const full=path.join(root,'dist',entry);if(!fs.statSync(full).isFile())continue;if(entry.endsWith('.js'))scripts+=fs.readFileSync(full,'utf8');if(entry.endsWith('.css'))styles+=fs.readFileSync(full,'utf8');}assert.match(scripts,/data-rt-style/);assert.doesNotMatch(scripts,/data-rt-revision|virtual:retouch-vue-css/);assert.match(styles,/padding:\s*16px\s*!important/);assert.match(styles,/font-size:\s*40px\s*!important/);assert.match(styles,/min-width:\s*768px/);console.log('VUE AUTHORED RESPONSIVE STYLES SURVIVE PRODUCTION BUILD');}console.log('VITE VUE SOURCE EDIT, EXACT UNDO, HMR STATE AND PRODUCTION EXCLUSION PASS',load('vite/package.json').version);
}finally{await browser?.close();await server?.close();fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
