'use strict';
const fs = require('node:fs'), assert = require('node:assert/strict');
exports.run = async ({ page, app, live, file, source }) => {
  const settled = () => page.waitForFunction(() => !undoBusy && !sourceRequests && !panelTasks);
  const wait = async predicate => { for (let i = 0; i < 160; i++) { if (await predicate()) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw Error('Vue style assertion did not settle'); };
  const style = (frame, property) => frame.locator('h1').evaluate((el, property) => getComputedStyle(el).getPropertyValue(property), property);
  const screen = page.getByLabel('Screen size', { exact: true }), originalScreen = await screen.inputValue();
  await screen.selectOption('390x844'); await settled();
  await page.getByLabel('Style screen scope', { exact: true }).selectOption(''); await settled();
  const set = async (label, value) => { const input = page.getByLabel(label, { exact: true }); await input.fill(value); await input.press('Tab'); await settled(); };
  await set('Padding (CSS)', '16px'); await wait(async () => await style(app, 'padding-top') === '16px');
  const padded = fs.readFileSync(file, 'utf8'); assert.notEqual(padded, source);
  await set('Font size (CSS)', '24px'); await wait(async () => await style(app, 'font-size') === '24px');
  const base = fs.readFileSync(file, 'utf8');
  await page.getByRole('button', { name: 'Compare screens', exact: true }).click();
  const previews = ['Phone', 'Tablet', 'Desktop'].map(name => page.frameLocator(`iframe[title="${name} comparison preview"]`));
  for (const preview of previews) { await preview.locator('h1').waitFor(); await wait(async () => await style(preview, 'font-size') === '24px'); await preview.locator('h1').evaluate(el => el.ownerDocument.defaultView.__vueCSSDocument = el.ownerDocument); }
  await screen.selectOption('768x1024'); await settled();
  await page.getByLabel('Style screen scope', { exact: true }).selectOption('min-[768px]:'); await settled();
  await set('Font size (CSS)', '40px'); await wait(async () => await style(app, 'font-size') === '40px');
  await wait(async () => await style(live, 'font-size') === '40px');
  assert.equal(await style(previews[0], 'font-size'), '24px');
  for (const preview of previews.slice(1)) await wait(async () => await style(preview, 'font-size') === '40px');
  const productionSource = fs.readFileSync(file, 'utf8');
  await page.screenshot({ path: '/tmp/retouch-vue-css-' + (process.env.RT_E2E_BROWSER || 'chromium') + '.png', caret: 'initial' });
  await screen.selectOption('390x844'); await settled(); await wait(async () => await style(app, 'font-size') === '24px');
  for (const expected of [base, padded, source]) { await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled(); await wait(() => fs.readFileSync(file, 'utf8') === expected); }
  await wait(async () => await style(app, 'padding-top') === '0px');
  assert.equal(await app.locator('h1').evaluate(el => el.ownerDocument.defaultView.__viteDocument === el.ownerDocument), true);
  await app.getByRole('button', { name: 'Count 2', exact: true }).waitFor();
  await live.getByRole('button', { name: 'Count 1', exact: true }).waitFor();
  for (const preview of previews) assert.equal(await preview.locator('h1').evaluate(el => el.ownerDocument.defaultView.__vueCSSDocument === el.ownerDocument), true);
  await page.getByLabel('Style screen scope', { exact: true }).selectOption(''); await settled();
  await page.getByRole('treeitem', { name: 'h1 · Hello Vite', exact: true }).click();
  await page.getByRole('treeitem', { name: 'p · Editable Vue source', exact: true }).first().click({ modifiers: ['Meta'] });
  const sharedSize = page.getByLabel('Shared Font size', { exact: true });
  await sharedSize.fill('30px'); await sharedSize.press('Tab'); await settled();
  await wait(async () => await style(app, 'font-size') === '30px' && await app.locator('main > p').evaluateAll(elements => elements.every(element => getComputedStyle(element).fontSize === '30px')));
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled();
  assert.equal(fs.readFileSync(file, 'utf8'), source);
  await app.getByRole('button', { name: 'Count 2', exact: true }).waitFor();
  for (const preview of previews) assert.equal(await preview.locator('h1').evaluate(el => el.ownerDocument.defaultView.__vueCSSDocument === el.ownerDocument), true);
  await page.getByRole('treeitem', { name: 'h1 · Hello Vite', exact: true }).click();
  await page.getByRole('button', { name: 'Compare screens', exact: true }).click();
  await screen.selectOption(originalScreen); await settled();
  await page.getByLabel('Style screen scope', { exact: true }).selectOption(''); await settled();
  console.log('VUE RESPONSIVE CSS, COMPARISON HMR, STATE AND EXACT UNDO PASS');
  return productionSource;
};
