'use strict';
const fs = require('node:fs'), assert = require('node:assert/strict');
exports.run = async ({ page, app, live, file, source }) => {
  const settled = () => page.waitForFunction(() => !undoBusy && !sourceRequests && !panelTasks);
  const wait = async predicate => { for (let i = 0; i < 160; i++) { if (await predicate()) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw Error('Vue copy assertion did not settle: ' + JSON.stringify({source:fs.readFileSync(file,'utf8'),state:await page.evaluate(()=>({toasts:document.querySelector('#toasts')?.textContent,active:document.activeElement?.tagName,mode,editing:!!editing,panelTasks,sourceRequests,undoBusy,duplicate:document.querySelector('[data-design-action=duplicateElement]')?.outerHTML,selected:sel?.info?.structure}))})); };
  const firstLayers = frame => frame.locator('#order > div[aria-label="First"]');
  const select = async (name, last = false) => { const rows = page.getByRole('treeitem', { name: 'div · ' + name, exact: true }); await (last ? rows.last() : rows.first()).click(); await settled(); };
  const padding = async value => { const input = page.getByLabel('Padding (CSS)', { exact: true }); await input.fill(value); await input.press('Tab'); await settled(); };
  const action = async name => { const button = page.locator('[data-design-action=' + name + ']'); if (!await button.isVisible()) await page.getByText('Layer actions', { exact: true }).click(); await button.click(); await settled(); };
  const undo = async () => { await page.getByRole('button', { name: 'Undo', exact: true }).click(); await settled(); };
  await select('First'); await padding('13px');
  const styled = fs.readFileSync(file, 'utf8');
  // The same shortcut advertised by the layer menu must take the source path.
  await page.getByRole('treeitem', { name: 'div · First', exact: true }).click(); await settled();
  await page.keyboard.press('Meta+d'); await settled();
  await wait(async () => await firstLayers(app).count() === 2 && await firstLayers(live).count() === 2);
  const duplicated = fs.readFileSync(file, 'utf8');
  const field = page.getByLabel('Padding (CSS)', { exact: true });
  await field.focus(); await field.press('Meta+d'); await field.press('Tab'); await settled();
  assert.equal(fs.readFileSync(file, 'utf8'), duplicated, 'Layer shortcuts must leave inspector text fields alone');
  assert.equal(new Set(await firstLayers(app).evaluateAll(elements => elements.map(element => element.getAttribute('data-rt-style')))).size, 2);
  await select('First', true); await padding('21px');
  await wait(async () => JSON.stringify(await firstLayers(app).evaluateAll(elements => elements.map(element => getComputedStyle(element).paddingTop))) === JSON.stringify(['13px', '21px']));
  const independentlyStyled = fs.readFileSync(file, 'utf8');
  await action('deleteElement');
  await wait(async () => await firstLayers(app).count() === 1 && await firstLayers(live).count() === 1);
  assert.equal(await firstLayers(app).evaluate(element => getComputedStyle(element).paddingTop), '13px');
  assert.doesNotMatch(fs.readFileSync(file, 'utf8'), /padding:21px/);
  await undo(); assert.equal(fs.readFileSync(file, 'utf8'), independentlyStyled);
  await page.getByRole('button', { name: 'Redo', exact: true }).click(); await settled();
  await wait(async () => await firstLayers(app).count() === 1);
  await undo(); await undo(); assert.equal(fs.readFileSync(file, 'utf8'), duplicated);
  await undo(); assert.equal(fs.readFileSync(file, 'utf8'), styled);
  await undo(); assert.equal(fs.readFileSync(file, 'utf8'), source);
  await select('First'); await action('copyElement'); await select('Third'); await action('pasteElement');
  await wait(async () => JSON.stringify(await app.locator('#order > div').allTextContents()) === JSON.stringify(['First', 'Second', 'Third', 'First']));
  await undo(); assert.equal(fs.readFileSync(file, 'utf8'), source);
  await select('First'); await padding('13px'); await select('First'); await page.keyboard.press('Delete'); await settled();
  await wait(async () => await firstLayers(app).count() === 0);
  const css=require('../../src/vue-css.cjs');
  assert.deepEqual(css.documentState(fs.readFileSync(file,'utf8'),'src/App.vue').model,css.documentState(source,'src/App.vue').model,'Deletion removes copied styles and preserves unrelated baseline styles');
  await undo(); await undo(); assert.equal(fs.readFileSync(file, 'utf8'), source);
  await select('First');
  await page.getByRole('treeitem', { name: 'div · Second', exact: true }).click({ modifiers: ['Meta'] }); await settled();
  for (const name of ['before', 'first'])
    assert.equal(await page.locator('[data-design-action=' + name + ']').isDisabled(), true, 'Unsupported multi-selection ' + name);
  for(const name of ['duplicateElement','deleteElement','after','last','reparentElement'])assert.equal(await page.locator('[data-design-action='+name+']').isEnabled(),true);
  assert.equal(await app.locator('h1').evaluate(element => element.ownerDocument.defaultView.__viteDocument === element.ownerDocument), true);
  assert.equal(await live.evaluate(() => window.__viteDocument === document), true);
  await app.getByRole('button', { name: 'Count 2', exact: true }).waitFor();
  await live.getByRole('button', { name: 'Count 1', exact: true }).waitFor();
  await page.getByRole('treeitem', { name: 'h1 · Hello Vite', exact: true }).click(); await settled();
  console.log('VUE DUPLICATE, INDEPENDENT STYLES, PASTE, DELETE CLEANUP AND EXACT HISTORY PASS');
};
