'use strict';
const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
function browser(...args){const r=JSON.parse(execFileSync(process.env.RT_AGENT_BROWSER_BIN||'npx',[...(process.env.RT_AGENT_BROWSER_BIN?[]:['-y','agent-browser']),'--session','retouch-zoom-test','--json',...args],{encoding:'utf8',timeout:60000}));assert.ok(r.success,JSON.stringify(r));return r.data.result;}
const evaluate=code=>browser('eval',code);
(async()=>{try{
 browser('open','http://127.0.0.1:9400/rt');
 const result=browser('eval',`(async()=>{
  const wait=async f=>{for(let i=0;i<100;i++){if(f())return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out');};
  await wait(()=>document.querySelector('iframe').contentDocument.querySelector('h1'));
  const iframe=document.querySelector('iframe'),stage=document.querySelector('#siteStage'),canvas=document.querySelector('#frameWrap');
  const initial={w:iframe.contentWindow.innerWidth,h:iframe.contentWindow.innerHeight};
  window.__zoomProbeStyle=iframe.contentDocument.createElement('style');__zoomProbeStyle.textContent='.rt-zoom-probe{height:100vh;--copy:"100vh"}';iframe.contentDocument.head.append(__zoomProbeStyle);
  if(document.querySelector('#zoomControls'))throw Error('Manual zoom controls remain');
  const hero=iframe.contentDocument.querySelector('.section-hero'),heroHeight=hero?.getBoundingClientRect().height;
  const event=new iframe.contentWindow.WheelEvent('wheel',{ctrlKey:true,deltaY:Math.log(2)/.005,bubbles:true,cancelable:true,clientX:initial.w/2,clientY:0});
  iframe.contentDocument.body.dispatchEvent(event);
  if(!event.defaultPrevented)throw Error('Pinch was not intercepted inside iframe');
  await new Promise(r=>requestAnimationFrame(r));
  const rect=iframe.getBoundingClientRect(),outer=canvas.getBoundingClientRect();
  if(iframe.contentWindow.innerWidth!==initial.w || Math.abs(iframe.contentWindow.innerHeight-initial.h*2)>1)throw Error('Zoom must reveal twice the vertical page area');
  if(hero && Math.abs(hero.getBoundingClientRect().height-heroHeight)>1)throw Error('Viewport-height hero expanded during zoom');
  if(Math.abs(rect.width-initial.w*.5)>1)throw Error('Site not scaled');
  if(rect.left<=outer.left || rect.right>=outer.right)throw Error('Missing gray side margins');
  if(Math.abs(rect.height-outer.height)>1)throw Error('Page does not fill canvas vertically');
  const el=iframe.contentDocument.querySelector('h1');await select(el);
  await new Promise(r=>requestAnimationFrame(r));
  const box=document.querySelector('.box.sel').getBoundingClientRect(),local=el.getBoundingClientRect();
  if(Math.abs(box.left-(rect.left+local.left*.5))>1 || Math.abs(box.width-local.width*.5)>1)throw Error('Outline misaligned');
  const edge=document.querySelector('.max-width-edge.right').getBoundingClientRect();
  if(Math.abs(edge.width-8)>1)throw Error('Resize target shrank');
  return {background:getComputedStyle(canvas).backgroundColor,initial,textPoint:{x:Math.round(rect.left+local.left*.5+30),y:Math.round(rect.top+local.top*.5+8)},edge:{x:Math.round(edge.x+edge.width/2),y:Math.round(edge.y+edge.height/2)},width:local.width};
 })()`);
 assert.equal(result.background,'rgb(128, 128, 128)');
 browser('mouse','move',String(result.textPoint.x),String(result.textPoint.y));browser('mouse','down');browser('mouse','up');
 assert.equal(evaluate(`(async()=>{for(let i=0;i<50;i++){const e=document.querySelector('iframe').contentDocument.querySelector('h1');if(e.contentEditable==='true' && e.ownerDocument.activeElement===e)return true;await new Promise(r=>setTimeout(r,100));}return false})()`),true,'text can be edited at 50%');

 browser('mouse','move',String(result.edge.x),String(result.edge.y));browser('mouse','down');
 browser('mouse','move',String(result.edge.x-60),String(result.edge.y));
 const resized=evaluate(`(()=>{const e=document.querySelector('iframe').contentDocument.querySelector('h1');return {max:parseFloat(e.style.maxWidth),expected:RetouchMaxWidth.nearest(RetouchMaxWidth.points(e),${result.width}-120).px}})()`);
 assert.equal(resized.max,resized.expected,'drag accounts for 50% scale');
 browser('press','Escape');browser('mouse','up');
 evaluate(`(()=>{const c=document.querySelector('#frameWrap');const r=c.getBoundingClientRect();c.dispatchEvent(new WheelEvent('wheel',{ctrlKey:true,deltaY:-Math.log(2)/.005,bubbles:true,cancelable:true,clientX:r.left+r.width/2,clientY:r.top}));})()`);
 assert.equal(evaluate(`Number(document.querySelector('#siteStage').style.getPropertyValue('--canvas-zoom'))`),1,'reverse pinch returns to 100%');
 assert.equal(evaluate(`__zoomProbeStyle.sheet.cssRules[0].style.height`),'100vh','authored viewport units restored');
 assert.equal(evaluate(`__zoomProbeStyle.sheet.cssRules[0].style.getPropertyValue('--copy')`),'"100vh"','quoted values preserved');
 const nativeScroll=evaluate(`(()=>{const c=document.querySelector('#frameWrap'),e=new WheelEvent('wheel',{deltaY:50,bubbles:true,cancelable:true});c.dispatchEvent(e);return {prevented:e.defaultPrevented,scale:Number(document.querySelector('#siteStage').style.getPropertyValue('--canvas-zoom'))}})()`);
 assert.deepEqual(nativeScroll,{prevented:true,scale:1},'canvas scrolling moves the page without zooming');
 evaluate(`(()=>{const c=document.querySelector('#frameWrap');for(const type of ['gesturestart','gesturechange','gestureend']){const e=new Event(type,{bubbles:true,cancelable:true});Object.defineProperties(e,{scale:{value:.5},clientX:{value:400},clientY:{value:0}});c.dispatchEvent(e);}})()`);
 assert.equal(evaluate(`Number(document.querySelector('#siteStage').style.getPropertyValue('--canvas-zoom'))`),.5,'Safari gesture events zoom');
 const limits=evaluate(`(()=>{
  const c=document.querySelector('#frameWrap'),f=document.querySelector('iframe'),w=f.contentWindow,d=f.contentDocument;
  const wheel=(target,delta)=>target.dispatchEvent(new w.WheelEvent('wheel',{deltaY:delta,bubbles:true,cancelable:true}));
  const gap=()=>{const a=c.getBoundingClientRect(),b=f.getBoundingClientRect();return {top:b.top-a.top,bottom:a.bottom-b.bottom};};
  w.scrollTo({top:0,behavior:'instant'});c.scrollTop=96;
  wheel(d.body,-10000);const above=gap();wheel(d.body,-10000);const aboveAgain=gap();
  wheel(d.body,48);const returning=gap();
  wheel(c,1e7);const below=gap(),atBottom=Math.abs(w.scrollY-(d.scrollingElement.scrollHeight-d.scrollingElement.clientHeight))<2;
  wheel(c,1e7);const belowAgain=gap();
  wheel(d.body,-48);const returningBottom=gap();
  w.scrollTo({top:100,behavior:'instant'});c.scrollTop=96;
  const normal=new w.WheelEvent('wheel',{deltaY:10,bubbles:true,cancelable:true});d.body.dispatchEvent(normal);
  const nested=d.createElement('div');nested.style.cssText='height:20px;overflow:auto';nested.innerHTML='<div style="height:200px"></div>';d.body.append(nested);
  const inner=new w.WheelEvent('wheel',{deltaY:10,bubbles:true,cancelable:true});nested.dispatchEvent(inner);nested.remove();
  w.scrollTo({top:0,behavior:'instant'});c.scrollTop=0;
  return {above,aboveAgain,returning,below,belowAgain,returningBottom,atBottom,native:!normal.defaultPrevented,nested:!inner.defaultPrevented};
 })()`);
 assert.equal(limits.above.top,96,'top padding has fixed 96px limit');
 assert.deepEqual(limits.aboveAgain,limits.above,'top limit cannot be exceeded');
 assert.equal(limits.returning.top,48,'scroll returns from top padding first');
 assert.equal(limits.below.bottom,96,'bottom padding has fixed 96px limit');
 assert.deepEqual(limits.belowAgain,limits.below,'bottom limit cannot be exceeded');
 assert.equal(limits.returningBottom.bottom,48,'scroll returns from bottom padding first');
 assert.ok(limits.atBottom && limits.native && limits.nested,'page endpoint and native page/nested scrolling');
 browser('screenshot','/tmp/retouch-pinch-zoom-out.png');
 console.log('PASS pinch in iframe and canvas, increased vertical coverage, stable hero height, bounded gray end padding, native page/nested scrolling, text editing, and scale-correct drag');
}finally{browser('close');}})().catch(e=>{console.error(e);process.exitCode=1;});
