'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{makeApp,cleanup,Index}=require('./helpers.cjs'),paste=require('../src/component-paste.cjs'),props=require('../src/component-props.cjs'),transactions=require('../src/transactions.cjs');
require('../shell/component-clipboard.js');const clipboard=globalThis.RetouchComponentClipboard;
const definition='export function Card({label="Default",count=2,enabled=true,size="small",note,onClick}:{label?:string;count?:number;enabled?:boolean;size?:"small"|"large";note?:string;onClick:()=>void}){return <output>{label}{count}{note}</output>}';
function fixture(usage){const root=fs.realpathSync(makeApp({'page.tsx':'import {Card} from "./Card";const action=()=>{};export default function Page(){return <main>'+usage+'</main>}','Card.tsx':definition})),index=new Index(root);index.scanAll();const members=[...index.idToFile.keys()].map(id=>index.resolve(id)).filter(item=>item.element.kind==='instance');return {root,members,close(){index.close();cleanup(root);}};}
const properties=(resolved,values)=>values.map(property=>({...property,definitionHash:props.describe(resolved,property.name).definitionHash}));
test('paste inserts multiple properties and updates multiple instances atomically without touching bindings',()=>{
 const f=fixture('<Card onClick={action}/><Card label="Old" note="Remove" onClick={action}/>');try{const values=[{name:'label',value:'New "text"\nLine'},{name:'count',value:-3},{name:'enabled',value:false},{name:'size',value:'large'},{name:'note',unset:true}],op={fileHash:f.members[0].hash,targets:f.members.map(r=>({id:r.element.id,properties:properties(r,values)}))},plan=paste.plan(f.members[0],op);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.selection.length,2);assert.equal(plan.componentPaste.refreshIds.length,1);assert.equal(plan.edits.filter(e=>e.before!==e.after).length,1);assert.equal(transactions.applyPlan(f.root,plan).ok,true);const after=fs.readFileSync(f.members[0].file,'utf8');assert.equal((after.match(/onClick=\{action\}/g)||[]).length,2);assert.ok(!after.includes('note='));assert.ok(!after.includes('label="Old"'));assert.equal(fs.readFileSync(path.join(f.root,'Card.tsx'),'utf8'),definition);}finally{f.close();}
});
test('paste rejects incompatible choices, expression bindings, special props and stale target contracts',()=>{
 const f=fixture('<Card label={getLabel()} count={9}/>');try{const r=f.members[0];for(const property of [{name:'label',value:'New'},{name:'count',value:'wrong'},{name:'size',value:'huge'},{name:'children',value:'No'},{name:'count',unset:true}]){const plan=paste.plan(r,{fileHash:r.hash,targets:[{id:r.element.id,properties:properties(r,[property])}]});assert.equal(plan.ok,false,JSON.stringify(property));}assert.equal(paste.plan(r,{fileHash:r.hash,targets:[{id:r.element.id,properties:[{name:'count',value:3,definitionHash:'stale'}]}]}).ok,false);assert.equal(fs.readFileSync(r.file,'utf8'),r.source);}finally{f.close();}
});
test('paste materializes inherited values but preserves equal explicit source and guards dependencies',()=>{
 const f=fixture('<Card/><Card count={2}/>');try{const r=f.members[0],plan=paste.plan(r,{fileHash:r.hash,targets:f.members.map(r=>({id:r.element.id,properties:properties(r,[{name:'count',value:2}])}))});assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits[0].after,r.source.replace('<Card/>','<Card count={2}/>'));fs.appendFileSync(path.join(f.root,'Card.tsx'),'\n// changed');assert.equal(transactions.applyPlan(f.root,plan).ok,false);assert.equal(fs.readFileSync(r.file,'utf8'),r.source);}finally{f.close();}
});
test('clipboard validates primitive values and previews incompatible properties without evaluating code',()=>{
 const payload=clipboard.validate(JSON.stringify({format:'retouch/component-properties@1',properties:[{name:'label',value:'Text'},{name:'count',value:3},{name:'note',unset:true}]})),match=clipboard.match({props:[{name:'label',editor:{editable:false}},{name:'count',editor:{editable:true,type:'number',definitionHash:'a'}},{name:'note',editor:{editable:true,type:'string',allowUnset:true,definitionHash:'b'}}]},payload);assert.deepEqual(match.skipped,['label']);assert.equal(match.accepted.length,2);for(const property of [{name:'__proto__',value:'x'},{name:'x',value:{}},{name:'x',value:Infinity},{name:'x',unset:true,value:'x'}])assert.throws(()=>clipboard.validate({format:'retouch/component-properties@1',properties:[property]}));assert.throws(()=>clipboard.validate('ordinary text'));assert.throws(()=>clipboard.validate({format:'retouch/component-properties@1',properties:[{name:'x',value:1},{name:'x',value:2}]}));
});
test('clipboard falls back locally on denied writes and respects a replaced system clipboard',async()=>{
 const descriptor=Object.getOwnPropertyDescriptor(globalThis,'navigator');let text='',reads=0,denied=true;
 Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{async writeText(value){if(denied)throw Error('Denied');text=value;},async readText(){reads++;return text;}}}});
 try{const component={props:[{name:'label',editor:{editable:true,type:'string',value:'Copied'}}]};assert.equal((await clipboard.copy(component)).system,false);assert.equal((await clipboard.read()).properties[0].value,'Copied');assert.equal(reads,0);denied=false;assert.equal((await clipboard.copy(component)).system,true);assert.equal((await clipboard.read()).properties[0].value,'Copied');text='Unrelated system clipboard';await assert.rejects(clipboard.read(),/Copy component properties/);}finally{if(descriptor)Object.defineProperty(globalThis,'navigator',descriptor);else delete globalThis.navigator;}
});
test('pending clipboard permission falls back instead of leaving copy unresolved',async()=>{
 const descriptor=Object.getOwnPropertyDescriptor(globalThis,'navigator');Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText:()=>new Promise(()=>{})}}});try{assert.equal((await clipboard.copy({props:[{name:'label',editor:{editable:true,type:'string',value:'Retained'}}]})).system,false);assert.equal((await clipboard.read()).properties[0].value,'Retained');}finally{if(descriptor)Object.defineProperty(globalThis,'navigator',descriptor);else delete globalThis.navigator;}
});
