'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {makeApp,cleanup,Index}=require('./helpers.cjs'),react=require('../src/adapters/react.cjs'),{collectElements}=require('../src/id.cjs'),{applyPlan}=require('../src/transactions.cjs');
function fixture(source,extra={}){const root=fs.realpathSync(makeApp({'page.jsx':source,...extra})),index=new Index(root);index.scanAll();const file=path.join(root,'page.jsx'),elements=collectElements(source,'page.jsx').elements,ids=elements.filter(el=>el.kind==='instance').map(el=>el.id),resolved=index.resolve(ids[0]);return {root,file,index,elements,ids,resolved,op:{type:'duplicateComponentSelection',id:ids[0],ids,fileHash:resolved.hash},close(){index.close();cleanup(root);}};}
const source='function Card({title}){return <h2>{title}</h2>}function Page(){return <main><Card key="a" title="A"/><p>Keep</p><Card key="b" title="B"/><Card title="C"/></main>}';
test('component selection duplication creates one reversible snapshot and composes identities for originals and copies',()=>{const f=fixture(source);try{const plan=react.planOp(f.resolved,{...f.op,ids:f.ids.slice(0,2)});assert.ok(plan.ok,plan.reason);assert.equal(plan.rootCount,2);assert.equal(plan.edits.length,1);assert.equal(fs.readFileSync(f.file,'utf8'),source);const after=plan.edits[0].after,elements=collectElements(after,'page.jsx').elements,instances=elements.filter(el=>el.kind==='instance'),mapping=new Map(plan.sourceIdMap);assert.equal(instances.length,5);assert.equal(plan.selectionIds.length,2);assert.ok(after.includes('<p>Keep</p>'));assert.ok(after.endsWith('<Card title="C"/></main>}'));for(const element of f.elements)assert.ok(elements.some(next=>next.id===(mapping.get(element.id)||element.id)&&next.kind===element.kind));assert.deepEqual(plan.selectionIds,plan.copiedComponents.map(copy=>copy.instanceId));for(const copy of plan.copiedComponents){const el=elements.find(el=>el.id===copy.instanceId);assert.match(after.slice(el.node.start,el.node.end),/key="retouch-copy-/);assert.notEqual(copy.instanceId,mapping.get(copy.originalId)||copy.originalId);}const applied=applyPlan(f.root,plan);assert.ok(applied.ok,applied.reason);assert.ok(applyPlan(f.root,{ok:true,edits:applied.edits.map(edit=>({...edit,before:edit.after,after:edit.before}))}).ok);assert.equal(fs.readFileSync(f.file,'utf8'),source);}finally{f.close();}});
test('component selection duplication refuses invalid or unsafe later members without mutation',()=>{for(const replacement of ['<Card ref={r}/>','<Card {...props}/>','<Card id="fixed"/>']){const current=source.replace('<Card key="b" title="B"/>',replacement),f=fixture(current);try{assert.equal(react.planOp(f.resolved,{...f.op,ids:f.ids.slice(0,2)}).ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),current);}finally{f.close();}}const f=fixture(source);try{for(const extra of [{ids:[]},{ids:[f.ids[0],f.ids[0]]},{ids:[f.ids[0],'0000000000']},{fileHash:'stale'}])assert.equal(react.planOp(f.resolved,{...f.op,...extra}).ok,false);const plan=react.planOp(f.resolved,f.op);fs.appendFileSync(f.file,'// external');assert.equal(applyPlan(f.root,plan).ok,false);}finally{f.close();}});
test('selected ancestor and descendant are copied once as a subtree',()=>{const f=fixture('function Wrapper({children}){return <section>{children}</section>}function Card(){return <h2>Text</h2>}function Page(){return <main><Wrapper><Card/></Wrapper><Card/></main>}');try{const plan=react.planOp(f.resolved,{...f.op,ids:f.ids.slice(0,2)});assert.ok(plan.ok,plan.reason);assert.equal(plan.rootCount,1);assert.equal(plan.selectionIds.length,1);assert.equal(collectElements(plan.edits[0].after,'page.jsx').elements.filter(el=>el.kind==='instance').length,5);}finally{f.close();}});
test('imported definition changes prevent committing duplication and wrapped usages retain identity',()=>{const f=fixture('import Card from "./Card";function First(){return <Card key="a"/>}function Second(){return <Card key="b"/>}',{'Card.jsx':'export default function Card(){return <h2>Text</h2>}'});try{const plan=react.planOp(f.resolved,f.op);assert.ok(plan.ok,plan.reason);assert.equal(plan.selectionIds.length,2);assert.equal(plan.edits.length,2);assert.equal(plan.edits[1].before,plan.edits[1].after);fs.writeFileSync(path.join(f.root,'Card.jsx'),'export default function Card(){return <h2 id="fixed">Text</h2>}');assert.equal(applyPlan(f.root,plan).ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),f.resolved.source);}finally{f.close();}});
test('single and group duplication guard re-export modules, alias configs and resolution precedence',()=>{
 const source='import Card from "@/index";function Page(){return <main><Card/><Card/></main>}',definition='export default function Card(){return <h2>Text</h2>}',extra={'jsconfig.json':'{"compilerOptions":{"paths":{"@/*":["src/*"]}}}','src/index.jsx':'export {default} from "./Card";','src/Card.jsx':definition,'src/Other.jsx':definition};
 const changes=[null,
  f=>fs.writeFileSync(path.join(f.root,'src/index.jsx'),'export {default} from "./Other";'),
  f=>fs.writeFileSync(path.join(f.root,'jsconfig.json'),'{"compilerOptions":{"paths":{"@/*":["other/*"]}}}'),
  f=>fs.writeFileSync(path.join(f.root,'tsconfig.json'),'{"compilerOptions":{"paths":{"@/*":["other/*"]}}}'),
  f=>fs.writeFileSync(path.join(f.root,'src/Card.tsx'),definition),
  f=>{fs.unlinkSync(path.join(f.root,'src/Card.jsx'));fs.symlinkSync('Other.jsx',path.join(f.root,'src/Card.jsx'));},
 ];
 for(const type of ['duplicateComponent','duplicateComponentSelection'])for(const change of changes){const f=fixture(source,extra);try{const plan=react.planOp(f.resolved,{...f.op,type});assert.ok(plan.ok,plan.reason);assert.ok(plan.edits.some(edit=>edit.file.endsWith('/src/index.jsx')&&edit.before===edit.after));assert.ok(plan.edits.some(edit=>edit.file.endsWith('/jsconfig.json')&&edit.before===edit.after));assert.ok(plan.pathChecks.some(check=>check.file.endsWith('/src/Card.tsx')&&check.kind==='missing'));if(change)change(f);assert.equal(applyPlan(f.root,plan).ok,!change);assert.equal(fs.readFileSync(f.file,'utf8'),change?source:plan.edits[0].after);}finally{f.close();}}
});

test('dependency audit permits a project-root barrel directory candidate',()=>{const f=fixture('import Card from "./";function Page(){return <main><Card/><Card/></main>}',{'index.jsx':'export default function Card(){return <h2>Text</h2>}'});try{const plan=react.planOp(f.resolved,f.op);assert.ok(plan.ok,plan.reason);assert.ok(plan.edits.some(edit=>edit.file.endsWith('/index.jsx')));assert.ok(applyPlan(f.root,plan).ok);}finally{f.close();}});
