'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{once}=require('node:events'),react=require('../src/adapters/react.cjs');
test('opening a project through a root symlink preserves source history across canonical and alias restarts',async t=>{
 const directory=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-history-alias-'))),root=path.join(directory,'project'),alias=path.join(directory,'alias'),state=path.join(directory,'history');fs.mkdirSync(root);fs.symlinkSync(root,alias,'dir');const file=path.join(root,'Page.jsx'),original='export default function Page(){return <h1 className="text-xl">Hello</h1>}';fs.writeFileSync(file,original);t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const previous=process.env.RETOUCH_STATE_DIR;process.env.RETOUCH_STATE_DIR=state;let server,base,headers;
 const stop=async()=>{server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));server=null;};
 const start=async appRoot=>{server=require('../src/server.cjs').startServer({appRoot,adapter:react,port:0,quiet:true});await once(server,'listening');base='http://127.0.0.1:'+server.address().port;const shell=await fetch(base+'/rt').then(r=>r.text());headers={'x-retouch-token':/window\.__RT_TOKEN = "([a-f0-9]+)"/.exec(shell)[1],'content-type':'application/json'};return shell;};
 const post=async body=>{const r=await fetch(base+'/rt/__api/op',{method:'POST',headers,body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 try{
  await start(alias);const element=react.collect(original,'Page.jsx').elements.find(e=>e.kind==='host'),updated=await post({type:'setClasses',id:element.id,fileHash:react.contentHash(original),classes:'text-2xl'});assert.equal(updated.status,200,JSON.stringify(updated.body));assert.ok(updated.body.undoId);assert.ok(!updated.body.historyPersistenceError,updated.body.historyPersistenceError);const after=fs.readFileSync(file,'utf8');assert.ok(after.includes('text-2xl'));
  await stop();await start(root);const undo=await post({type:'undo',undoId:updated.body.undoId});assert.equal(undo.status,200,JSON.stringify(undo.body));assert.ok(!undo.body.historyPersistenceError,undo.body.historyPersistenceError);assert.equal(fs.readFileSync(file,'utf8'),original);
  await stop();await start(alias);const redo=await post({type:'redo',undoId:updated.body.undoId});assert.equal(redo.status,200,JSON.stringify(redo.body));assert.ok(!redo.body.historyPersistenceError,redo.body.historyPersistenceError);assert.equal(fs.readFileSync(file,'utf8'),after);
  const journals=fs.readdirSync(state).filter(name=>name.endsWith('.json'));assert.equal(journals.length,1);const journal=JSON.parse(fs.readFileSync(path.join(state,journals[0]),'utf8'));assert.equal(journal.undo[0].edits[0].file,'Page.jsx');
 }finally{if(server)await stop();if(previous===undefined)delete process.env.RETOUCH_STATE_DIR;else process.env.RETOUCH_STATE_DIR=previous;}
});
