'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),html=require('../src/adapters/html.cjs'),gradient=require('../src/html-svg-gradient.cjs');
const source='<html><body><svg><defs><linearGradient id="paint" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="red"/><stop offset="100%" stop-color="blue"/></linearGradient></defs><rect fill="url(#paint)" width="20" height="20"/><circle fill="url(#paint)" r="10"/></svg><p>Unchanged</p></body></html>';
function resolve(text=source){const elements=html.collect(text,'index.html').elements;return {source:text,elements,element:elements.find(el=>el.tag==='rect'),hash:html.contentHash(text),file:'/tmp/index.html',relPath:'index.html'};}
test('Selected SVG paint exposes gradient definitions without changing layer identities',()=>{const r=resolve(),g=html.describe(r).svgGradients;assert.equal(g.length,1);assert.equal(g[0].type,'linearGradient');assert.equal(g[0].reason,null);assert.deepEqual(g[0].stops,[{offset:'0',color:'red',opacity:null},{offset:'100%',color:'blue',opacity:null}]);assert.ok(!r.elements.some(el=>el.tag==='stop'));});
test('Gradient coordinate, units and atomic stop changes preserve unrelated source and identities',()=>{
 for(const op of [{changes:{x2:'80%',gradientUnits:'objectBoundingBox'}},{stop:1,changes:{offset:'75%','stop-color':'#123456','stop-opacity':'0.5'}},{changes:{spreadMethod:'reflect'}}]){const r=resolve(),result=html.planOp(r,{type:'setSVGGradient',paint:'fill',fileHash:r.hash,...op});assert.equal(result.ok,true,result.reason);const after=result.edits[0].after;assert.ok(after.endsWith('<rect fill="url(#paint)" width="20" height="20"/><circle fill="url(#paint)" r="10"/></svg><p>Unchanged</p></body></html>'));assert.deepEqual(resolve(after).elements.map(el=>el.id),r.elements.map(el=>el.id));const fresh=gradient.describe(resolve(after))[0];if(op.stop!==undefined)assert.deepEqual(fresh.stops[1],{offset:'75%',color:'#123456',opacity:'0.5'});else for(const [name,value]of Object.entries(op.changes))assert.equal(fresh.fields.find(f=>f.name===name).value,value);}
});
test('Gradient updates refuse stale, injected, out of range and ambiguous edits atomically',()=>{
 for(const op of [{fileHash:'stale',changes:{x2:'2'}},{changes:{x2:'2" onload="x'}},{stop:2,changes:{offset:'0.5'}},{stop:0,changes:{offset:'101%'}},{stop:0,changes:{'stop-opacity':'1.1'}},{changes:{x2:'20%',onclick:'x'}},{stop:0,changes:{'stop-color':'red;fill:blue'}}]){const r=resolve(),result=gradient.plan(r,{paint:'fill',fileHash:r.hash,...op});assert.equal(result.refused,true);assert.equal(result.edits,undefined);}
 for(const text of [source.replace('id="paint"','id="paint" href="#other"'),source.replace('offset="0"','offset="0" offset="1"'),source.replace('offset="0"','style="stop-color: red" offset="0"')]){const r=resolve(text);assert.ok(gradient.describe(r)[0].reason);assert.equal(gradient.plan(r,{paint:'fill',fileHash:r.hash,stop:0,changes:{offset:'0.2'}}).refused,true);}
});
test('Radial stroke gradient supports focal geometry, reset and inherited defaults',()=>{const r=resolve(source.replace('linearGradient','radialGradient').replace('</linearGradient>','</radialGradient>').replaceAll('fill="url','stroke="url'));const result=gradient.plan(r,{paint:'stroke',fileHash:r.hash,changes:{cx:'50%',fx:'25%',fr:'2%',r:'80%'}});assert.equal(result.ok,true,result.reason);const next=resolve(result.edits[0].after),reset=gradient.plan(next,{paint:'stroke',fileHash:next.hash,changes:{fx:null}});assert.equal(reset.ok,true);assert.equal(gradient.describe(resolve(reset.edits[0].after))[0].fields.find(f=>f.name==='fx').value,null);});
