'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {collectElements,contentHash}=require('../src/id.cjs'),{plan}=require('../src/jsx-group-scale.cjs'),{applyPlan}=require('../src/transactions.cjs');
const input=`'use client';\nexport default function Page(){return <main><div data-rt-group=""><h1>Title</h1><p>Text</p></div><footer>After</footer></main>}`;
function setup(t,source=input){const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-jsx-scale-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'Page.jsx');fs.writeFileSync(file,source);const resolve=()=>{const source=fs.readFileSync(file,'utf8'),collected=collectElements(source,'Page.jsx');return {...collected,source,hash:contentHash(source),file,appRoot:root,relPath:'Page.jsx',element:collected.elements.find(e=>e.node.openingElement.name.name==='div')};};return {root,file,resolve};}
const scale=r=>plan(r,{fileHash:r.hash,width:0,factor:1.5});
test('React group source and client helper save atomically and undo exactly',t=>{const {root,file,resolve}=setup(t),before=resolve(),first=scale(before);assert.equal(first.ok,true,first.reason);assert.equal(first.edits.length,2);assert.equal(applyPlan(root,first).ok,true);const next=resolve();assert.ok(next.source.startsWith("'use client';"));assert.ok(before.elements.every(e=>next.elements.some(n=>n.id===e.id)));const second=plan(next,{fileHash:next.hash,width:1100,factor:2});assert.equal(second.ok,true,second.reason);assert.equal(second.edits.length,1);assert.equal(applyPlan(root,second).ok,true);const saved=resolve(),attribute=saved.element.node.openingElement.attributes.find(a=>a.name.name==='data-rt-scale');assert.deepEqual(JSON.parse(attribute.value.expression.value).ranges,{0:1.5,1100:3});assert.equal((saved.source.match(/<RetouchScaleRuntime \/>/g)||[]).length,1);for(const change of [second,first])assert.equal(applyPlan(root,{ok:true,edits:change.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(fs.readFileSync(file,'utf8'),input);assert.equal(fs.existsSync(path.join(root,'.retouch-group-scale.jsx')),false);});
test('React helper creation collision leaves source untouched',t=>{const {root,file,resolve}=setup(t),pending=scale(resolve());fs.writeFileSync(path.join(root,'.retouch-group-scale.jsx'),'external');assert.equal(applyPlan(root,pending).ok,false);assert.equal(fs.readFileSync(file,'utf8'),input);assert.match(scale(resolve()).reason,/outside/);});
test('React scaling snapshots literal member transforms and avoids binding collisions',t=>{const source=input.replace('export default',"const RetouchScaleRuntime=123;\nexport default").replace('<h1>','<h1 className="font-bold ![--rt-scale-factor:1.2]">'),{root,resolve}=setup(t,source),first=scale(resolve());assert.equal(first.ok,true,first.reason);assert.match(first.edits[0].after,/<RetouchScaleRuntime1 \/>/);applyPlan(root,first);const result=scale(resolve());assert.equal(result.ok,true,result.reason);const metadata=collectElements(result.edits[0].after,'Page.jsx').elements.find(e=>e.node.openingElement.name.name==='div').node.openingElement.attributes.find(a=>a.name.name==='data-rt-scale').value.expression.value;assert.equal(Object.values(JSON.parse(metadata).steps[0].styles)[0][0].factor,1.2);});
test('React source planner rejects stale files and ambiguous generated members',t=>{for(const replacement of ['<Thing />','{items.map(item=><h1>{item}</h1>)}','<h1 {...props}>Title</h1>','<h1 className={classes}>Title</h1>']){const {resolve}=setup(t,input.replace('<h1>Title</h1>',replacement));assert.equal(scale(resolve()).ok,false);}const {resolve}=setup(t);assert.equal(plan(resolve(),{fileHash:'stale',width:0,factor:2}).ok,false);});

test('React runtime import cannot be shadowed by a local component',t=>{const source="import Runtime from './.retouch-group-scale.jsx';\n"+input.replace("'use client';\n",'').replace('function Page()','function Page(Runtime)'),{resolve}=setup(t,source);assert.match(scale(resolve()).reason,/shadowed/);});
