'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {collectElements,contentHash}=require('../src/id.cjs'),{plan}=require('../src/jsx-group-scale.cjs'),{applyPlan}=require('../src/transactions.cjs');
const input=`'use client';\nexport default function Page(){return <main><div data-rt-group=""><h1>Title</h1><p>Text</p></div><footer>After</footer></main>}`;
function setup(t,source=input){const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-jsx-scale-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'Page.jsx');fs.writeFileSync(file,source);const resolve=()=>{const source=fs.readFileSync(file,'utf8'),collected=collectElements(source,'Page.jsx');return {...collected,source,hash:contentHash(source),file,appRoot:root,relPath:'Page.jsx',element:collected.elements.find(e=>e.node.openingElement.name.name==='div')};};return {root,file,resolve};}
const scale=r=>plan(r,{fileHash:r.hash,width:0,factor:1.5});
test('React group source and client helper save atomically and undo exactly',t=>{const {root,file,resolve}=setup(t),before=resolve(),first=scale(before);assert.equal(first.ok,true,first.reason);assert.equal(first.edits.length,2);assert.equal(applyPlan(root,first).ok,true);const next=resolve();assert.ok(next.source.startsWith("'use client';"));assert.ok(before.elements.every(e=>next.elements.some(n=>n.id===e.id)));const second=plan(next,{fileHash:next.hash,width:1100,factor:2});assert.equal(second.ok,true,second.reason);assert.equal(second.edits.length,1);assert.equal(applyPlan(root,second).ok,true);const saved=resolve(),attribute=saved.element.node.openingElement.attributes.find(a=>a.name.name==='data-rt-scale');assert.deepEqual(JSON.parse(attribute.value.expression.value).ranges,{0:1.5,1100:3});assert.equal((saved.source.match(/<RetouchScaleRuntime \/>/g)||[]).length,1);for(const change of [second,first])assert.equal(applyPlan(root,{ok:true,edits:change.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(fs.readFileSync(file,'utf8'),input);assert.equal(fs.existsSync(path.join(root,'.retouch-group-scale.jsx')),false);});
test('React helper creation collision leaves source untouched',t=>{const {root,file,resolve}=setup(t),pending=scale(resolve());fs.writeFileSync(path.join(root,'.retouch-group-scale.jsx'),'external');assert.equal(applyPlan(root,pending).ok,false);assert.equal(fs.readFileSync(file,'utf8'),input);assert.match(scale(resolve()).reason,/outside/);});
test('React scaling snapshots literal member transforms and avoids binding collisions',t=>{const source=input.replace('export default',"const RetouchScaleRuntime=123;\nexport default").replace('<h1>','<h1 className="font-bold ![--rt-scale-factor:1.2]">'),{root,resolve}=setup(t,source),first=scale(resolve());assert.equal(first.ok,true,first.reason);assert.match(first.edits.at(-1).after,/<RetouchScaleRuntime1 \/>/);applyPlan(root,first);const result=scale(resolve());assert.equal(result.ok,true,result.reason);const metadata=collectElements(result.edits[0].after,'Page.jsx').elements.find(e=>e.node.openingElement.name.name==='div').node.openingElement.attributes.find(a=>a.name.name==='data-rt-scale').value.expression.value;assert.equal(Object.values(JSON.parse(metadata).steps[0].styles)[0][0].factor,1.2);});
test('React source planner rejects stale files and ambiguous generated members',t=>{for(const replacement of ['<Thing />','{items.map(item=><h1>{item}</h1>)}','<h1 {...props}>Title</h1>','<h1 className={classes}>Title</h1>']){const {resolve}=setup(t,input.replace('<h1>Title</h1>',replacement));assert.equal(scale(resolve()).ok,false);}const {resolve}=setup(t);assert.equal(plan(resolve(),{fileHash:'stale',width:0,factor:2}).ok,false);});

test('React runtime import cannot be shadowed by a local component',t=>{const source="import Runtime from './.retouch-group-scale.jsx';\n"+input.replace("'use client';\n",'').replace('function Page()','function Page(Runtime)'),{resolve}=setup(t,source);assert.match(scale(resolve()).reason,/shadowed/);});

test('React adapter exposes scaling and protects structural ownership until undo',t=>{const {root,resolve}=setup(t),adapter=require('../src/adapters/react.cjs'),r=resolve();assert.equal(adapter.describe(r).groupScale.react,true);const result=adapter.planOp(r,{type:'scaleGroup',fileHash:r.hash,width:0,factor:1.5});assert.equal(result.ok,true,result.reason);applyPlan(root,result);const saved=resolve();assert.ok(adapter.describe(saved).groupScale.metadata);for(const type of ['removeFrame','setChildren','createComponent'])assert.equal(adapter.planOp(saved,{type,fileHash:saved.hash}).ok,false);const child=saved.elements.find(e=>e.node.openingElement.name.name==='h1');const footer=saved.elements.find(e=>e.node.openingElement.name.name==='footer');assert.equal(require('../src/jsx-group-scale.cjs').guard({...saved,element:footer},{type:'duplicateElement'}),null);assert.equal(adapter.describe({...saved,element:child}).scaleMember,true);assert.equal(adapter.planOp({...saved,element:child},{type:'moveElement',fileHash:saved.hash,direction:'next'}).ok,false);});

test('recognized saved React helpers upgrade transactionally and restore exactly',t=>{const {root,resolve}=setup(t),helper=path.join(root,'.retouch-group-scale.jsx'),legacy=fs.readFileSync(path.join(__dirname,'fixtures/group-scale/pre-mount-react-runtime.jsx'),'utf8');fs.writeFileSync(helper,legacy);const result=scale(resolve());assert.equal(result.ok,true,result.reason);assert.equal(result.edits.find(e=>e.file===helper).before,legacy);assert.equal(applyPlan(root,result).ok,true);assert.ok(fs.readFileSync(helper,'utf8').includes('data-rt-react-scale-pending'));assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(fs.readFileSync(helper,'utf8'),legacy);});

test('React group and member copies remap snapshots and preserve independent ownership',t=>{
 const {root,resolve}=setup(t,input.replace('<h1>','<h1 className="![--rt-scale-factor:1.2] ![--rt-scale-move-x:23px]">')),adapter=require('../src/adapters/react.cjs');applyPlan(root,scale(resolve()));applyPlan(root,scale(resolve()));const state=resolve(),attr=(e,name)=>{const a=e.node.openingElement.attributes.find(a=>a.name?.name===name);return a?.value?.expression?.value??a?.value?.value;},heading=state.elements.find(e=>e.node.openingElement.name.name==='h1'),text=state.elements.find(e=>e.node.openingElement.name.name==='p');
 for(const [element,op]of [[state.element,{type:'duplicateElement'}],[heading,{type:'duplicateElement'}],[text,{type:'pasteElement',copiedId:heading.id,copiedHash:state.hash}],[heading,{type:'duplicateSelection',ids:[heading.id,text.id]}]]){
  const result=adapter.planOp({...state,element},{...op,fileHash:state.hash});assert.equal(result.ok,true,result.reason);const next=collectElements(result.edits[0].after,'Page.jsx').elements,members=next.filter(e=>attr(e,'data-rt-scale-member')),ids=members.map(e=>attr(e,'data-rt-scale-member'));assert.equal(new Set(ids).size,ids.length);
  for(const group of next.filter(e=>attr(e,'data-rt-scale'))){const data=JSON.parse(attr(group,'data-rt-scale')),owned=members.filter(e=>e.node.start>group.node.start&&e.node.end<group.node.end&&e.node.openingElement.name.name==='h1');assert.equal(Object.keys(data.steps[0].styles).length,owned.length);for(const member of owned)assert.deepEqual(data.steps[0].styles[attr(member,'data-rt-scale-member')],{0:{factor:1.2,move:[23,0]}});}
  assert.equal(applyPlan(root,result).ok,true);assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(resolve().source,state.source);
 }
 assert.equal(adapter.describe(state).structure.canDuplicate,true);assert.equal(adapter.describe(state).structure.canDelete,false);assert.equal(adapter.describe(state).structure.canMoveAfter,false);fs.writeFileSync(path.join(root,'.retouch-group-scale.jsx'),'export default function Custom(){return null}');assert.equal(adapter.planOp(state,{type:'duplicateElement',fileHash:state.hash}).ok,false);assert.equal(adapter.describe(state).structure.canDuplicate,false);
});
