'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {collectElements,contentHash}=require('../src/id.cjs'),{plan}=require('../src/jsx-group-scale.cjs'),{applyPlan}=require('../src/transactions.cjs');
const input=`'use client';\nexport default function Page(){return <main><div data-rt-group=""><h1>Title</h1><p>Text</p></div><footer>After</footer></main>}`;
function setup(t,source=input){const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-jsx-scale-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'Page.jsx');fs.writeFileSync(file,source);const resolve=()=>{const source=fs.readFileSync(file,'utf8'),collected=collectElements(source,'Page.jsx');return {...collected,source,hash:contentHash(source),file,appRoot:root,relPath:'Page.jsx',element:collected.elements.find(e=>e.node.openingElement.name.name==='div')};};return {root,file,resolve};}
const scale=r=>plan(r,{fileHash:r.hash,width:0,factor:1.5});
test('React group source and client helper save atomically and undo exactly',t=>{const {root,file,resolve}=setup(t),before=resolve(),first=scale(before);assert.equal(first.ok,true,first.reason);assert.equal(first.edits.length,2);assert.equal(applyPlan(root,first).ok,true);const next=resolve();assert.ok(next.source.startsWith("'use client';"));assert.ok(before.elements.every(e=>next.elements.some(n=>n.id===e.id)));const second=plan(next,{fileHash:next.hash,width:1100,factor:2});assert.equal(second.ok,true,second.reason);assert.equal(second.edits.length,1);assert.equal(applyPlan(root,second).ok,true);const saved=resolve(),attribute=saved.element.node.openingElement.attributes.find(a=>a.name.name==='data-rt-scale');assert.deepEqual(JSON.parse(attribute.value.expression.value).ranges,{0:1.5,1100:3});assert.equal((saved.source.match(/<RetouchScaleRuntime \/>/g)||[]).length,1);for(const change of [second,first])assert.equal(applyPlan(root,{ok:true,edits:change.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(fs.readFileSync(file,'utf8'),input);assert.equal(fs.existsSync(path.join(root,'.retouch-group-scale.jsx')),false);});
test('React helper creation collision leaves source untouched',t=>{const {root,file,resolve}=setup(t),pending=scale(resolve());fs.writeFileSync(path.join(root,'.retouch-group-scale.jsx'),'external');assert.equal(applyPlan(root,pending).ok,false);assert.equal(fs.readFileSync(file,'utf8'),input);assert.match(scale(resolve()).reason,/outside/);});
test('React scaling snapshots literal member transforms and avoids binding collisions',t=>{const source=input.replace('export default',"const RetouchScaleRuntime=123;\nexport default").replace('<h1>','<h1 className="font-bold ![--rt-scale-factor:1.2]">'),{root,resolve}=setup(t,source),first=scale(resolve());assert.equal(first.ok,true,first.reason);assert.match(first.edits.at(-1).after,/<RetouchScaleRuntime1 \/>/);applyPlan(root,first);const result=scale(resolve());assert.equal(result.ok,true,result.reason);const metadata=collectElements(result.edits[0].after,'Page.jsx').elements.find(e=>e.node.openingElement.name.name==='div').node.openingElement.attributes.find(a=>a.name.name==='data-rt-scale').value.expression.value;assert.equal(Object.values(JSON.parse(metadata).steps[0].styles)[0][0].factor,1.2);});
test('React source planner rejects stale files and ambiguous generated members',t=>{for(const replacement of ['<Thing />','{items.map(item=><h1>{item}</h1>)}','<h1 {...props}>Title</h1>','<h1 className={classes}>Title</h1>']){const {resolve}=setup(t,input.replace('<h1>Title</h1>',replacement));assert.equal(scale(resolve()).ok,false);}const {resolve}=setup(t);assert.equal(plan(resolve(),{fileHash:'stale',width:0,factor:2}).ok,false);});

test('React runtime import cannot be shadowed by a local component',t=>{const source="import Runtime from './.retouch-group-scale.jsx';\n"+input.replace("'use client';\n",'').replace('function Page()','function Page(Runtime)'),{resolve}=setup(t,source);assert.match(scale(resolve()).reason,/shadowed/);});

test('React adapter exposes scaling and protects structural ownership until undo',t=>{const {root,resolve}=setup(t),adapter=require('../src/adapters/react.cjs'),r=resolve();assert.equal(adapter.describe(r).groupScale.react,true);const result=adapter.planOp(r,{type:'scaleGroup',fileHash:r.hash,width:0,factor:1.5});assert.equal(result.ok,true,result.reason);applyPlan(root,result);const saved=resolve();assert.ok(adapter.describe(saved).groupScale.metadata);for(const type of ['removeFrame','setChildren','createComponent'])assert.equal(adapter.planOp(saved,{type,fileHash:saved.hash}).ok,false);const child=saved.elements.find(e=>e.node.openingElement.name.name==='h1');const footer=saved.elements.find(e=>e.node.openingElement.name.name==='footer');assert.equal(require('../src/jsx-group-scale.cjs').guard({...saved,element:footer},{type:'duplicateElement'}),null);assert.equal(adapter.describe({...saved,element:child}).scaleMember,true);assert.equal(adapter.planOp({...saved,element:child},{type:'moveElement',fileHash:saved.hash,direction:'next'}).ok,false);});

test('recognized saved React helpers upgrade transactionally and restore exactly',t=>{const {root,resolve}=setup(t),helper=path.join(root,'.retouch-group-scale.jsx'),legacy=fs.readFileSync(path.join(__dirname,'fixtures/group-scale/pre-mount-react-runtime.jsx'),'utf8');fs.writeFileSync(helper,legacy);const result=scale(resolve());assert.equal(result.ok,true,result.reason);assert.equal(result.edits.find(e=>e.file===helper).before,legacy);assert.equal(applyPlan(root,result).ok,true);assert.ok(fs.readFileSync(helper,'utf8').includes('data-rt-react-scale-pending'));assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(fs.readFileSync(helper,'utf8'),legacy);});

test('React group and member copies remap snapshots and preserve independent ownership',t=>{
 const {root,resolve}=setup(t,input.replace('<h1>','<h1 className="![--rt-scale-factor:1.2] ![--rt-scale-move-x:23px]">')),adapter=require('../src/adapters/react.cjs');applyPlan(root,scale(resolve()));applyPlan(root,scale(resolve()));const state=resolve(),attr=(e,name)=>{const a=e.node.openingElement.attributes.find(a=>a.name?.name===name);return a?.value?.expression?.value??a?.value?.value;},heading=state.elements.find(e=>e.node.openingElement.name.name==='h1'),text=state.elements.find(e=>e.node.openingElement.name.name==='p');
 for(const [element,op]of [[state.element,{type:'duplicateElement'}],[heading,{type:'duplicateElement'}],[text,{type:'pasteElement',copiedId:heading.id,copiedHash:state.hash}],[heading,{type:'duplicateSelection',ids:[heading.id,text.id]}]]){
  const result=adapter.planOp({...state,element},{...op,fileHash:state.hash});assert.equal(result.ok,true,result.reason);const next=collectElements(result.edits[0].after,'Page.jsx').elements,members=next.filter(e=>attr(e,'data-rt-scale-member')),ids=members.map(e=>attr(e,'data-rt-scale-member'));assert.equal(new Set(ids).size,ids.length);
  for(const group of next.filter(e=>attr(e,'data-rt-scale'))){const data=JSON.parse(attr(group,'data-rt-scale')),owned=members.filter(e=>e.node.start>group.node.start&&e.node.end<group.node.end&&e.node.openingElement.name.name==='h1');assert.equal(Object.keys(data.steps[0].styles).length,owned.length);for(const member of owned)assert.deepEqual(data.steps[0].styles[attr(member,'data-rt-scale-member')],{0:{factor:1.2,move:[23,0]}});}
  assert.equal(applyPlan(root,result).ok,true);assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(resolve().source,state.source);
 }
 assert.equal(adapter.describe(state).structure.canDuplicate,true);assert.equal(adapter.describe(state).structure.canDelete,true);assert.equal(adapter.describe(state).structure.canMoveAfter,true);fs.writeFileSync(path.join(root,'.retouch-group-scale.jsx'),'export default function Custom(){return null}');assert.equal(adapter.planOp(state,{type:'duplicateElement',fileHash:state.hash}).ok,false);assert.equal(adapter.describe(state).structure.canDuplicate,false);
});

test('deleting React members prunes saved snapshots and undo restores exact ownership',t=>{
 const {root,resolve}=setup(t,input.replace('<h1>','<h1 className="![--rt-scale-factor:1.2]">').replace('<p>','<p className="![--rt-scale-move-x:11px]">')),adapter=require('../src/adapters/react.cjs');applyPlan(root,scale(resolve()));applyPlan(root,scale(resolve()));const state=resolve(),heading=state.elements.find(e=>e.node.openingElement.name.name==='h1'),text=state.elements.find(e=>e.node.openingElement.name.name==='p');
 for(const [element,operation]of [[heading,{type:'deleteElement'}],[state.element,{type:'deleteElement'}],[heading,{type:'deleteSelection',ids:[heading.id,text.id]}]]){
  const result=adapter.planOp({...state,element},{...operation,fileHash:state.hash});assert.equal(result.ok,true,result.reason);const next=collectElements(result.edits[0].after,'Page.jsx').elements,group=next.find(e=>e.node.openingElement.name.name==='div');
  if(group){const data=JSON.parse(group.node.openingElement.attributes.find(a=>a.name?.name==='data-rt-scale').value.expression.value);if(operation.type==='deleteSelection')assert.deepEqual(data.steps[0].styles,{});else{assert.equal(Object.keys(data.steps[0].styles).length,1);assert.deepEqual(Object.values(data.steps[0].styles)[0],{0:{factor:1,move:[11,0]}});}assert.equal(next.filter(e=>e.node.openingElement.name.name==='h1').length,0);if(operation.type==='deleteSelection')assert.equal(next.filter(e=>e.node.openingElement.name.name==='p').length,0);}else assert.equal(element,state.element);
  assert.equal(applyPlan(root,result).ok,true);assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(resolve().source,state.source);
 }
});

test('React sibling reordering preserves member transforms and exact source undo',t=>{
 const source=input.replace('<h1>','<h1 className="![--rt-scale-factor:1.2]">').replace('</p>','</p><aside>Third</aside>'),{root,resolve}=setup(t,source),adapter=require('../src/adapters/react.cjs');applyPlan(root,scale(resolve()));applyPlan(root,scale(resolve()));const state=resolve(),name=e=>e.node.openingElement.name.name,heading=state.elements.find(e=>name(e)==='h1'),text=state.elements.find(e=>name(e)==='p'),metadata=adapter.describe(state).groupScale.metadata,markers=adapter.describe(state).groupScale.members;
 for(const [element,operation]of [[heading,{type:'moveElement',direction:'after'}],[state.element,{type:'moveElement',direction:'after'}],[heading,{type:'moveSelection',direction:'last',ids:[heading.id,text.id]}]]){
  const result=adapter.planOp({...state,element},{...operation,fileHash:state.hash});assert.equal(result.ok,true,result.reason);const after=result.edits[0].after,collected=collectElements(after,'Page.jsx'),group=collected.elements.find(e=>name(e)==='div'),updated={...state,...collected,source:after,element:group,hash:contentHash(after)},description=adapter.describe(updated).groupScale;
  assert.equal(description.metadata,metadata);assert.deepEqual(Object.values(description.members).sort(),Object.values(markers).sort());if(element===heading){const order=collected.elements.filter(e=>['h1','p','aside'].includes(name(e))).map(name);assert.deepEqual(order,operation.type==='moveSelection'?['aside','h1','p']:['p','h1','aside']);}
  assert.equal(applyPlan(root,result).ok,true);assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(resolve().source,state.source);
 }
});

test('React ungrouping retains a sibling-scoped responsive ownership record',t=>{
 const {root,resolve}=setup(t,input.replace('data-rt-group=""','data-rt-frame="" data-rt-group="" className="contents"').replace('<h1>','<h1 className="![--rt-scale-factor:1.2]">')),release=require('../src/jsx-group-release.cjs');applyPlan(root,scale(resolve()));applyPlan(root,scale(resolve()));const state=resolve(),result=require('../src/adapters/react.cjs').planOp(state,{type:'removeFrame',fileHash:state.hash});assert.equal(result.ok,true,result.reason);assert.equal(require('../src/adapters/react.cjs').describe(state).structure.canRemoveFrame,true);const collected=collectElements(result.edits[0].after,'Page.jsx'),calls=collected.elements.filter(e=>e.kind==='instance');assert.equal(calls.length,1);assert.equal(collected.elements.some(e=>e.node.openingElement.name.name==='div'),false);assert.equal(result.selectionIds.length,2);assert.ok(result.selectionIds.every(id=>collected.elements.some(e=>e.id===id&&e.kind==='host')));const payload=calls[0].node.openingElement.attributes.find(a=>a.name.name==='released').value.expression,properties=Object.fromEntries(payload.properties.map(p=>[p.key.value,p.value]));assert.deepEqual(JSON.parse(properties.metadata.value).ranges,{0:1.5});assert.equal(properties.metadata.value,require('../src/adapters/react.cjs').describe(state).groupScale.metadata);assert.equal(Object.keys(JSON.parse(properties.metadata.value).steps[0].styles).length,1);assert.equal(properties.members.elements.length,2);assert.equal(applyPlan(root,result).ok,true);assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(resolve().source,state.source);
 for(const source of [state.source.replace('className="contents"','className="contents text-red-500"'),state.source.replace('data-rt-frame=""','data-rt-frame="" onClick={handler}')]){if(source===state.source)continue;const collected=collectElements(source,'Page.jsx'),r={...state,...collected,source,hash:contentHash(source),element:collected.elements.find(e=>e.node.openingElement.name.name==='div')};assert.equal(release.plan(r,{fileHash:r.hash}).ok,false);}
});

test('ungrouping upgrades a recognized React helper in the same undoable transaction',t=>{
 const {root,resolve}=setup(t,input.replace('data-rt-group=""','data-rt-frame="" data-rt-group="" className="contents"'));applyPlan(root,scale(resolve()));const state=resolve(),helper=path.join(root,'.retouch-group-scale.jsx'),legacy=fs.readFileSync(path.join(__dirname,'fixtures/group-scale/pre-release-react-runtime.jsx'),'utf8');fs.writeFileSync(helper,legacy);const result=require('../src/adapters/react.cjs').planOp(state,{type:'removeFrame',fileHash:state.hash});assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,2);assert.equal(applyPlan(root,result).ok,true);assert.equal(fs.readFileSync(helper,'utf8'),require('../src/react-group-scale-runtime.cjs').component());assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(resolve().source,state.source);assert.equal(fs.readFileSync(helper,'utf8'),legacy);fs.writeFileSync(helper,legacy+'\n// external edit');assert.equal(require('../src/adapters/react.cjs').planOp(state,{type:'removeFrame',fileHash:state.hash}).ok,false);
});

test('regrouping reclaims the complete React ownership record and preserves later edits',t=>{
 const {root,resolve}=setup(t,input.replace('data-rt-group=""','data-rt-frame="" data-rt-group="" className="contents"')),adapter=require('../src/adapters/react.cjs');applyPlan(root,scale(resolve()));const grouped=resolve(),released=adapter.planOp(grouped,{type:'removeFrame',fileHash:grouped.hash});assert.equal(released.ok,true,released.reason);applyPlan(root,released);
 const source=fs.readFileSync(grouped.file,'utf8'),collected=collectElements(source,'Page.jsx'),heading=collected.elements.find(e=>e.node.openingElement.name.name==='h1'),edited=adapter.planOp({...grouped,...collected,source,hash:contentHash(source),element:heading},{type:'setClasses',fileHash:contentHash(source),classes:'![--rt-scale-move-x:23px]'});assert.equal(edited.ok,true,edited.reason);applyPlan(root,edited);
 const before=fs.readFileSync(grouped.file,'utf8'),state=collectElements(before,'Page.jsx'),roots=state.elements.filter(e=>['h1','p'].includes(e.node.openingElement.name.name)),resolved={...grouped,...state,source:before,hash:contentHash(before),element:roots[0]},op={type:'groupSelection',fileHash:contentHash(before),ids:roots.map(e=>e.id)},result=adapter.planOp(resolved,op);assert.equal(result.ok,true,result.reason);assert.equal(adapter.describe(resolved).structure.canFrame,true);assert.ok(adapter.describe(resolved).structure.parentId);assert.equal(result.selectionIds.length,1);assert.equal(result.edits[0].after.includes(' released='),false);assert.ok(result.edits[0].after.includes('--rt-scale-move-x:23px'));applyPlan(root,result);assert.equal(adapter.describe(resolve()).groupScale.metadata,adapter.describe(grouped).groupScale.metadata);assert.equal(scale(resolve()).ok,true);assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(fs.readFileSync(grouped.file,'utf8'),before);
 assert.equal(adapter.planOp(resolved,{...op,ids:[roots[0].id]}).ok,false);
 const record=state.elements.find(e=>e.kind==='instance'),text=before.slice(record.node.start,record.node.end);for(const changed of [before.replace(text,'<aside>Intervening</aside>'+text),before.replace(text,text+text)]){const collected=collectElements(changed,'Page.jsx'),roots=collected.elements.filter(e=>['h1','p'].includes(e.node.openingElement.name.name));assert.equal(adapter.planOp({...resolved,...collected,source:changed,hash:contentHash(changed),element:roots[0]},{...op,fileHash:contentHash(changed),ids:roots.map(e=>e.id)}).ok,false);}
});

test('released React deletion prunes descendants and removes the final ownership record with exact undo',t=>{
 const source=input.replace('data-rt-group=""','data-rt-frame="" data-rt-group="" className="contents"').replace('<h1>Title</h1>','<h1 className="![--rt-scale-factor:1.2]"><span className="![--rt-scale-move-x:7px]">Title</span></h1>').replace('<p>Text</p>','<p className="![--rt-scale-move-y:11px]">Text</p>'),{root,resolve}=setup(t,source),adapter=require('../src/adapters/react.cjs');
 applyPlan(root,scale(resolve()));applyPlan(root,scale(resolve()));let state=resolve();const release=adapter.planOp(state,{type:'removeFrame',fileHash:state.hash});assert.equal(release.ok,true,release.reason);applyPlan(root,release);
 const read=()=>{const state=resolve();return {...state,element:state.elements.find(e=>e.node.openingElement.name.name==='h1')||state.elements.find(e=>e.node.openingElement.name.name==='p')};};state=read();const original=state.source,heading=state.element,text=state.elements.find(e=>e.node.openingElement.name.name==='p'),footer=state.elements.find(e=>e.node.openingElement.name.name==='footer');assert.equal(adapter.describe(state).structure.canDelete,true);
 assert.equal(adapter.planOp(state,{type:'deleteElement',fileHash:'stale'}).ok,false);assert.equal(adapter.planOp(state,{type:'deleteSelection',fileHash:state.hash,ids:[heading.id,footer.id]}).ok,false);
 for(const op of [{type:'deleteElement'},{type:'deleteSelection',ids:[heading.id,text.id]}]){
  const result=adapter.planOp(state,{...op,fileHash:state.hash});assert.equal(result.ok,true,result.reason);assert.equal(applyPlan(root,result).ok,true);const after=read();assert.equal(after.elements.some(e=>e.node.openingElement.name.name==='h1'||e.node.openingElement.name.name==='span'),false);assert.equal(after.elements.filter(e=>e.node.openingElement.name.name==='footer').length,1);
  if(op.type==='deleteElement'){const claim=require('../src/jsx-group-regroup.cjs').claim(after);assert.equal(claim.record.data.members.length,1);assert.equal(JSON.parse(claim.record.data.metadata).steps.filter(s=>s.styles).every(s=>Object.keys(s.styles).length===1),true);assert.deepEqual(JSON.parse(claim.record.data.metadata).steps.find(s=>s.styles).styles[claim.record.data.members[0]],{0:{factor:1,move:[0,11]}});const regroup=adapter.planOp(after,{type:'groupSelection',fileHash:after.hash,ids:[after.element.id]});assert.equal(regroup.ok,true,regroup.reason);const last=adapter.planOp(after,{type:'deleteElement',fileHash:after.hash});assert.equal(last.ok,true,last.reason);assert.equal(last.edits[0].after.includes(' released='),false);
  }else assert.equal(after.source.includes(' released='),false);
  assert.equal(applyPlan(root,{ok:true,edits:result.edits.map(e=>({...e,before:e.after,after:e.before}))}).ok,true);assert.equal(read().source,original);
 }
 fs.writeFileSync(path.join(root,'.retouch-group-scale.jsx'),'// modified helper');assert.equal(adapter.planOp(state,{type:'deleteElement',fileHash:state.hash}).ok,false);assert.equal(adapter.describe(state).structure.canDelete,false);
});
