'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),liquid=require('../src/adapters/liquid.cjs'),names=require('../src/liquid-layer-name.cjs'),{Liquid}=require('liquidjs');
function resolve(source,tag='h1'){const relPath='sections/main.liquid',elements=liquid.collect(source,relPath).elements;return {source,relPath,file:'/project/'+relPath,elements,element:elements.find(el=>el.tag===tag),hash:liquid.contentHash(source)};}
test('Liquid names preserve rendered output, conditional attributes and source identities',async()=>{
 const engine=new Liquid(),source='<main><h1 {% if alternate %}class="bold"{% else %}class="calm"{% endif %} aria-label="Accessible">{{ title }}</h1><p>Sibling</p></main>',resolved=resolve(source),label='Hero "& <tag> {{ secret }} {% assign hacked = 1 %} 🌞',plan=liquid.planOp(resolved,{type:'renameElement',fileHash:resolved.hash,name:label});assert.equal(plan.ok,true,plan.reason);const after=plan.edits[0].after,named=resolve(after);assert.deepEqual(named.elements.map(el=>el.id),resolved.elements.map(el=>el.id));assert.equal(liquid.describe(named).layerName,label);assert.equal(named.element.attributeExpressions,resolved.element.attributeExpressions);assert.deepEqual(named.element.attributes.map(a=>[a.name,a.value]),resolved.element.attributes.map(a=>[a.name,a.value]));
 for(const alternate of [false,true]){const context={alternate,title:'Page title',secret:'DO NOT SUBSTITUTE'};assert.equal(await engine.parseAndRender(after,context),await engine.parseAndRender(source,context));const stamped=liquid.stamp(after,'/project/sections/main.liquid','/project').code,rendered=await engine.parseAndRender(stamped,context);assert.ok(rendered.includes(names.attribute(label)));assert.ok(!rendered.includes('DO NOT SUBSTITUTE'));}
 const cleared=liquid.planOp(named,{type:'renameElement',fileHash:named.hash,name:''});assert.equal(cleared.ok,true,cleared.reason);assert.equal(cleared.edits[0].after,source);assert.equal(liquid.planOp(named,{type:'renameElement',fileHash:'stale',name:'x'}).ok,false);for(const name of [null,'x'.repeat(201),'bad\nname'])assert.equal(liquid.planOp(named,{type:'renameElement',fileHash:named.hash,name}).ok,false);
});
test('Liquid names survive styling and tag edits without blocking duplicate or move',()=>{
 const source='<main><h1 aria-label="Accessible">Heading</h1><p>Sibling</p></main>';let selected=resolve(source);
 for(const op of [{type:'renameElement',name:'Page heading'},{type:'setClasses',classes:'text-xl'},{type:'setTag',tag:'h2'}]){const plan=liquid.planOp(selected,{...op,fileHash:selected.hash});assert.equal(plan.ok,true,plan.reason);selected=resolve(plan.edits[0].after,op.tag||selected.element.tag);assert.equal(liquid.describe(selected).layerName,'Page heading');assert.equal(selected.element.attributeExpressions,false);assert.equal(liquid.describe(selected).classSelection,true);}
 for(const op of [{type:'duplicateElement'},{type:'moveElement',direction:'after'}]){const plan=liquid.planOp(selected,{...op,fileHash:selected.hash});assert.equal(plan.ok,true,plan.reason);const copies=liquid.collect(plan.edits[0].after,selected.relPath).elements.filter(el=>el.tag==='h2');assert.equal(copies.length,op.type==='duplicateElement'?2:1);assert.ok(copies.every(el=>names.describe({element:el}).layerName==='Page heading'));}
});
test('names do not hide runtime Liquid expressions from structural guards or change parent rich-text capability',()=>{
 const named='<main><h1'+names.comment('Title')+'>Heading</h1><p>Sibling</p></main>';assert.equal(liquid.describe(resolve(named,'main')).canSetChildren,true);
 const dynamic=named.replace('Heading','{{ title }}'),plan=liquid.planOp(resolve(dynamic),{type:'duplicateElement'});assert.equal(plan.ok,false);assert.match(plan.reason,/Liquid expressions/);assert.equal(names.strip('{% comment %}retouch-layer-v1:not-valid{% endcomment %}'),'{% comment %}retouch-layer-v1:not-valid{% endcomment %}');
});
test('names on dynamic tag hosts preserve the tag binding and exact rendered output',async()=>{
 const source='<main><{{ heading_tag }}>Heading</{{ heading_tag }}></main>',elements=liquid.collect(source,'sections/main.liquid').elements,resolved={...resolve(source,'main'),element:elements.find(el=>el.dynamicTag)},plan=liquid.planOp(resolved,{type:'renameElement',fileHash:resolved.hash,name:'Dynamic heading'});assert.equal(plan.ok,true,plan.reason);const engine=new Liquid();for(const heading_tag of ['h1','h2'])assert.equal(await engine.parseAndRender(plan.edits[0].after,{heading_tag}),await engine.parseAndRender(source,{heading_tag}));
});
