'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),liquid=require('../src/adapters/liquid.cjs'),batch=require('../src/text-style-selection.cjs'),engine=new(require('liquidjs').Liquid)();
const source='<h1 class="{% if active %}font-bold{% else %}font-normal{% endif %}">First</h1><p class="{% if active %}tracking-wide{% else %}tracking-normal{% endif %}">Second</p>',id=n=>String(n).repeat(8)+'-'+String(n).repeat(4)+'-4'+String(n).repeat(3)+'-8'+String(n).repeat(3)+'-'+String(n).repeat(12);
const definitions={text:[{'font-size':'32px'},{'font-size':'20px'}],color:[{color:'#123456ff'},{color:'#cc3300ff'}],effect:[{filter:'blur(2px)'},{filter:'blur(4px)'}]};
const resolve=source=>{const elements=liquid.collect(source,'main.liquid').elements;return {source,elements,element:elements[0],file:'/tmp/main.liquid',relPath:'main.liquid',hash:liquid.contentHash(source)};};
for(const [family,properties]of Object.entries(definitions))test('Liquid '+family+' style batches retain conditional branches and each linked definition',async()=>{
 const prefix=family[0].toUpperCase()+family.slice(1),linked=require('../src/liquid-'+family+'-styles.cjs'),styles=properties.map((properties,i)=>({id:id(i+1),name:'Style '+i,properties}));
 const op=(current,type)=>{const r=resolve(current);return {type:type+prefix+'StyleSelection',ids:r.elements.map(element=>element.id),contexts:Object.fromEntries(r.elements.map(element=>[element.id,{className:element.tag==='h1'?'font-bold':'tracking-wide'}])),fileHash:r.hash,scope:'md:',property:'color'};};
 const applied=batch.plan(resolve(source),op(source,'apply'),styles[0],liquid,family);assert.equal(applied.ok,true,applied.reason);assert.equal(applied.edits.length,1);let current=applied.edits[0].after,r=resolve(current);r.element=r.elements[1];r.context={className:'tracking-wide'};const second=linked.plan(r,{type:'apply'+prefix+'Style',scope:'md:',property:'color'},styles[1]);assert.equal(second.ok,true,second.reason);current=second.edits[0].after;
 const updated=styles.map((style,i)=>({...style,properties:definitions[family][1-i]})),reset=batch.plan(resolve(current),op(current,'reset'),{styles:updated},liquid,family);assert.equal(reset.ok,true,reset.reason);
 const links=info=>family==='color'?info.colorStyleLinks['md:'].color:info[family+'StyleLinks']['md:'];assert.deepEqual(reset.selection.map(info=>links(info).id),styles.map(style=>style.id));assert.deepEqual(reset.selection.map(info=>family==='color'?{color:links(info).value}:links(info).properties),updated.map(style=>style.properties));
 for(const active of [true,false]){const rendered=await engine.parseAndRender(reset.edits[0].after,{active}),hosts=liquid.collect(rendered,'main.liquid').elements;assert.ok(hosts[0].classAttr.value.includes(active?'font-bold':'font-normal'));assert.ok(!hosts[0].classAttr.value.includes('tracking-'));assert.ok(hosts[1].classAttr.value.includes(active?'tracking-wide':'tracking-normal'));assert.ok(!hosts[1].classAttr.value.includes('font-bold'));assert.ok(!hosts[1].classAttr.value.includes('font-normal'));}
 const detached=batch.plan(resolve(reset.edits[0].after),op(reset.edits[0].after,'detach'),undefined,liquid,family);assert.equal(detached.ok,true,detached.reason);assert.deepEqual(detached.selection.map(info=>info.className),reset.selection.map(info=>info.className));
 const bad=source.replace('<p ','<p data-rt-'+family+'-styles="bad" '),failed=batch.plan(resolve(bad),op(bad,'apply'),styles[0],liquid,family);assert.equal(failed.ok,false);assert.equal(failed.edits,undefined);
 const missing=batch.plan(resolve(current),op(current,'reset'),{styles:[styles[0]]},liquid,family);assert.equal(missing.ok,false);assert.equal(missing.edits,undefined);
 const absent=op(source,'apply');delete absent.contexts[absent.ids[1]];assert.equal(batch.plan(resolve(source),absent,styles[0],liquid,family).ok,false);
});
