'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),liquid=require('../src/adapters/liquid.cjs'),linked=require('../src/liquid-variable-bindings.cjs'),engine=new(require('liquidjs').Liquid)();
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),source='<p class="{% if active %}text-red-500{% else %}text-blue-500{% endif %} border-2">{{ title }}</p>';
function library(){return {version:1,collections:[{id:id(1),name:'Theme',defaultMode:id(2),modes:[{id:id(2),name:'Light'},{id:id(3),name:'Dark'}]}],variables:[['color','#ffffff','#000000'],['number',24,48],['boolean',true,false],['string','"Open Sans", sans-serif','"Font_Name", serif']].map(([type,light,dark],i)=>({id:id(i+4),collectionId:id(1),name:type,type,values:{[id(2)]:light,[id(3)]:dark}}))};}
function resolve(source,context){const elements=liquid.collect(source,'main.liquid').elements;return {source,file:'/tmp/main.liquid',relPath:'main.liquid',element:elements[0],elements,hash:liquid.contentHash(source),context};}
async function attrs(source,active=true){const html=await engine.parseAndRender(source,{active,title:'Title'});return Object.fromEntries(require('parse5').parseFragment(html).childNodes[0].attrs.map(a=>[a.name,a.value]));}
test('Liquid typed bindings preserve conditional expressions and mode/unit identity across unopened refresh',async()=>{
 const data=library();assert.equal(linked.plan(resolve(source),{type:'applyVariable',property:'color',binding:{id:id(4)}},data).ok,false);
 let current=source;for(const [property,n,extra]of [['color',4,{}],['padding',5,{unit:'rem'}],['visibility',6,{modes:{[id(1)]:id(3)}}],['font-family',7,{modes:{[id(1)]:id(3)}}]]){const result=linked.plan(resolve(current,{className:(await attrs(current)).class}),{type:'applyVariable',property,scope:'md:',binding:{id:id(n),...extra}},data);assert.equal(result.ok,true,result.reason);current=result.edits[0].after;}
 assert.ok(current.includes('{% if active %}text-red-500{% else %}text-blue-500{% endif %} border-2'));assert.ok(current.includes('{{ title }}'));
 data.variables[0].name='Renamed';data.variables[0].values[id(2)]='#ff8800';data.variables[1].values[id(2)]=32;const result=linked.planFile('/tmp/main.liquid','main.liquid',current,data);assert.equal(result.ok,true,result.reason);assert.equal(result.updated,4);current=result.edits[0].after;
 for(const active of [true,false]){const rendered=await attrs(current,active),links=JSON.parse(rendered['data-rt-variables'])['md:'];assert.ok(rendered.class.includes(active?'text-red-500':'text-blue-500'));for(const token of ['md:![color:#ff8800ff]','md:![padding:32rem]','md:![visibility:hidden]','md:![font-family:"Font\\_Name",_serif]'])assert.ok(rendered.class.includes(token),token);assert.equal(links.padding.unit,'rem');assert.equal(links['font-family'].modes[id(1)],id(3));}
 assert.deepEqual(linked.planFile('/tmp/main.liquid','main.liquid',current,data).edits,[]);
});
test('Liquid overrides persist through refresh until reset; detach and removal have distinct effects',()=>{
 const data=library(),plain='<p class="p-2">Text</p>';let result=linked.plan(resolve(plain),{type:'applyVariable',property:'color',binding:{id:id(4)}},data);let current=result.edits[0].after.replace('![color:#ffffffff]','![color:#ff0000ff]');data.variables[0].values[id(2)]='#ff0000';result=linked.planFile('/tmp/main.liquid','main.liquid',current,data);assert.equal(result.ok,true,result.reason);current=result.edits[0].after;assert.equal(linked.describe(resolve(current)).variableLinks[''].color.override,true);
 data.variables[0].values[id(2)]='#00ff00';result=linked.planFile('/tmp/main.liquid','main.liquid',current,data);current=result.edits[0].after;assert.ok(liquid.describeElement(resolve(current)).className.includes('![color:#ff0000ff]'));
 result=linked.plan(resolve(current),{type:'resetVariable',property:'color'},data);assert.equal(result.ok,true,result.reason);current=result.edits[0].after;assert.ok(liquid.describeElement(resolve(current)).className.includes('![color:#00ff00ff]'));assert.deepEqual(linked.describe(resolve(current)).variableOverrides[''],[]);
 const detached=linked.plan(resolve(current),{type:'detachVariable',property:'color'});assert.equal(detached.ok,true,detached.reason);assert.equal(liquid.describeElement(resolve(detached.edits[0].after)).className,liquid.describeElement(resolve(current)).className);
 const removed=linked.plan(resolve(current),{type:'removeVariable',property:'color'});assert.equal(removed.ok,true,removed.reason);assert.equal(liquid.describeElement(resolve(removed.edits[0].after)).className,'p-2');
});
test('Liquid variable planning rejects malformed metadata, dynamic attributes and incomplete linked references',()=>{
 const data=library();for(const bad of ['<p {{ attrs }}>Text</p>','<p class="a" class="b">Text</p>','<p data-rt-variables="{{ links }}">Text</p>','<p data-rt-variables="bad">Text</p>','<p style="color:{{ color }}">Text</p>','<p style="color:red!important">Text</p>']){const result=linked.plan(resolve(bad),{type:'applyVariable',property:'color',binding:{id:id(4)}},data);assert.equal(result.ok,false,bad);assert.equal(result.edits,undefined);}
 assert.equal(linked.plan(resolve('<p>Text</p>'),{type:'applyVariable',property:'color',fileHash:'stale',binding:{id:id(4)}},data).ok,false);
 const bound=linked.plan(resolve('<p>Text</p>'),{type:'applyVariable',property:'color',binding:{id:id(4),modes:{[id(1)]:id(3)}}},data).edits[0].after;
 for(const unsafe of [bound.replace('<p ','<template ').replace('</p>','</template>'),bound+'<p data-rt-variables="broken">Other</p>',bound.replace(/class="[^"]*"/,'class="{{ classes }}"')]){const result=linked.planFile('/tmp/main.liquid','main.liquid',unsafe,data);assert.equal(result.ok,false,unsafe);assert.equal(result.edits,undefined);}
 data.variables[0].values[id(3)]={alias:id(4)};const cycle=linked.planFile('/tmp/main.liquid','main.liquid',bound,data);assert.equal(cycle.ok,false);assert.match(cycle.reason,/cycle/);assert.equal(cycle.edits,undefined);
 data.variables=[];const missing=linked.planFile('/tmp/main.liquid','main.liquid',bound,data);assert.equal(missing.ok,false);assert.equal(missing.edits,undefined);
});
