'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{once}=require('node:events'),liquid=require('../src/adapters/liquid.cjs'),linked=require('../src/liquid-variable-bindings.cjs'),library=require('../src/variable-library.cjs'),engine=new(require('liquidjs').Liquid)();
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),source='<p class="{% if active %}font-bold{% else %}font-normal{% endif %}">{{ title }}</p>';
const data=()=>({version:1,collections:[{id:id(1),name:'Theme',defaultMode:id(2),modes:[{id:id(2),name:'Light'},{id:id(3),name:'Dark'}]}],variables:[{id:id(4),collectionId:id(1),name:'Brand',type:'color',values:{[id(2)]:'#123456',[id(3)]:'#cc3300'}}]});
function resolve(root,name,source){const elements=liquid.collect(source,name).elements;return {file:path.join(root,name),relPath:name,source,hash:liquid.contentHash(source),elements,element:elements[0],context:{className:'font-bold'}};}
test('Liquid API preserves conditional branches while propagating variable modes and undoing all files',async t=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-liquid-variables-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const input=data();library.commitPlan(root,library.planChange(root,{type:'replace',revision:null,library:input}));fs.writeFileSync(path.join(root,'main.liquid'),source);
 const other=linked.plan(resolve(root,'other.liquid',source),{type:'applyVariable',scope:'md:',property:'color',binding:{id:id(4),modes:{[id(1)]:id(3)}}},input);assert.equal(other.ok,true,other.reason);fs.writeFileSync(path.join(root,'other.liquid'),other.edits[0].after);
 const snapshot=()=>Object.fromEntries(['main.liquid','other.liquid','.retouch/variables.json'].map(name=>[name,fs.readFileSync(path.join(root,name),'utf8')])),previous=process.env.RETOUCH_STATE_DIR;process.env.RETOUCH_STATE_DIR=path.join(root,'.history-cache');let server;
 try{
  server=require('../src/server.cjs').startServer({appRoot:root,adapter:liquid,port:0,quiet:true});await once(server,'listening');const base='http://127.0.0.1:'+server.address().port,markup=await fetch(base+'/rt').then(r=>r.text()),headers={'x-retouch-token':/window\.__RT_TOKEN = "([a-f0-9]+)"/.exec(markup)[1],'content-type':'application/json'};
  const post=async(url,body)=>{const r=await fetch(base+url,{method:'POST',headers,body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};const r=resolve(root,'main.liquid',source),op={type:'applyVariable',id:r.element.id,fileHash:r.hash,scope:'md:',property:'color',binding:{id:id(4)},context:r.context,libraryRevision:library.read(root).revision};
  assert.equal((await post('/rt/__api/op',{...op,libraryRevision:null})).status,409);const bound=await post('/rt/__api/op',op);assert.equal(bound.status,200,JSON.stringify(bound.body));assert.equal(bound.body.element.classVariables,true);const before=snapshot(),revision=library.read(root).revision;
  input.variables[0].values[id(2)]='#00ff00';input.variables[0].values[id(3)]='#9933ff';const updated=await post('/rt/__api/variables',{type:'replace',revision,library:input});assert.equal(updated.status,200,JSON.stringify(updated.body));assert.equal(updated.body.updated,2);
  for(const [name,value]of [['main.liquid','#00ff00ff'],['other.liquid','#9933ffff']]){const text=fs.readFileSync(path.join(root,name),'utf8');assert.ok(text.includes('{% if active %}font-bold{% else %}font-normal{% endif %}'));for(const active of [true,false]){const rendered=await engine.parseAndRender(text,{active,title:'Title'});assert.ok(rendered.includes(active?'font-bold':'font-normal'));assert.ok(rendered.includes('md:![color:'+value+']'));}}
  const after=snapshot(),removed=structuredClone(input);removed.variables=[];assert.equal((await post('/rt/__api/variables',{type:'replace',revision:updated.body.revision,library:removed})).status,409);assert.deepEqual(snapshot(),after);
  assert.equal((await post('/rt/__api/op',{type:'undo',undoId:updated.body.undoId})).status,200);assert.deepEqual(snapshot(),before);assert.equal((await post('/rt/__api/op',{type:'undo',undoId:bound.body.undoId})).status,200);assert.equal(fs.readFileSync(r.file,'utf8'),source);
 }finally{if(server){server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}if(previous===undefined)delete process.env.RETOUCH_STATE_DIR;else process.env.RETOUCH_STATE_DIR=previous;}
});
