'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),liquid=require('../src/adapters/liquid.cjs'),links=require('../src/liquid-effect-styles.cjs'),engine=new(require('liquidjs').Liquid)();
const source='<p class="{% if active %}blur-sm{% else %}blur-lg{% endif %} p-4">{{ title }}</p>',style={id:'11111111-1111-4111-8111-111111111111',name:'Floating',properties:{filter:'blur(2px)','box-shadow':'none'}};
function resolve(source,context){const elements=liquid.collect(source,'main.liquid').elements;return {source,file:'/tmp/main.liquid',relPath:'main.liquid',element:elements[0],elements,hash:liquid.contentHash(source),context};}
async function attrs(source,active){return Object.fromEntries(require('parse5').parseFragment(await engine.parseAndRender(source,{active,title:'Title'})).childNodes[0].attrs.map(a=>[a.name,a.value]));}
test('Liquid effect links retain conditional branches and refresh unopened source-owned patches',async()=>{
 assert.equal(links.plan(resolve(source),{type:'applyEffectStyle',scope:'md:'},style).ok,false);
 const result=links.plan(resolve(source,{className:'blur-sm p-4'}),{type:'applyEffectStyle',scope:'md:'},style);assert.equal(result.ok,true,result.reason);const before=result.edits[0].after;assert.ok(before.includes('{% if active %}blur-sm{% else %}blur-lg{% endif %} p-4'));
 const next={...style,properties:{filter:'blur(4px)','box-shadow':'none','backdrop-filter':'blur(3px)'}},updated=links.planFile('/tmp/main.liquid','main.liquid',before,next);assert.equal(updated.ok,true,updated.reason);assert.equal(updated.updated,1);
 for(const active of [false,true]){const rendered=await attrs(updated.edits[0].after,active);assert.ok(rendered.class.includes(active?'blur-sm':'blur-lg'));assert.ok(rendered.class.includes('md:![filter:blur(4px)]'));assert.ok(!rendered.class.includes('md:![backdrop-filter:'));const metadata=JSON.parse(rendered['data-rt-effect-styles'])['md:'];assert.deepEqual(metadata.overrides,['backdrop-filter']);}
 assert.deepEqual(links.planFile('/tmp/main.liquid','main.liquid',updated.edits[0].after,next).edits,[]);
});
test('Liquid effect local overrides survive project refresh until reset; detach preserves appearance classes',()=>{
 const plain='<p class="p-4">Paint</p>',applied=links.plan(resolve(plain),{type:'applyEffectStyle'},style).edits[0].after,local=applied.replace('![filter:blur(2px)]','![filter:blur(8px)]'),next={...style,properties:{filter:'blur(4px)'}};
 const updated=links.planFile('/tmp/main.liquid','main.liquid',local,next);assert.equal(updated.ok,true,updated.reason);const r=resolve(updated.edits[0].after);assert.deepEqual(links.describe(r).effectStyleOverrides[''],['filter']);assert.ok(liquid.describe(r).className.includes('![filter:blur(8px)]'));
 const reset=links.plan(r,{type:'resetEffectStyle'},next);assert.equal(reset.ok,true,reset.reason);const fresh=resolve(reset.edits[0].after);assert.deepEqual(links.describe(fresh).effectStyleOverrides[''],[]);assert.ok(!liquid.describe(fresh).className.includes('![box-shadow:'));const detached=links.plan(fresh,{type:'detachEffectStyle'});assert.equal(detached.ok,true);assert.equal(liquid.describe(resolve(detached.edits[0].after)).className,liquid.describe(fresh).className);
});
test('Liquid effects refuse stale, generated and malformed metadata without partial changes',()=>{
 for(const bad of ['<p {{ attrs }}>Text</p>','<p class="a" class="b">Text</p>','<p data-rt-effect-styles="{{ links }}">Text</p>','<p data-rt-effect-styles="bad">Text</p>']){const result=links.plan(resolve(bad),{type:'applyEffectStyle'},style);assert.equal(result.ok,false,bad);assert.equal(result.edits,undefined);}
 assert.equal(links.plan(resolve('<p>Text</p>'),{type:'applyEffectStyle',fileHash:'stale'},style).ok,false);
 const before=links.plan(resolve(source,{className:'blur-sm p-4'}),{type:'applyEffectStyle'},style).edits[0].after,element=liquid.collect(before,'main.liquid').elements[0],unpacked=require('../src/liquid-classes.cjs').unpack(element.classAttr.value,element.id),broken=before.replace(element.classAttr.value,unpacked.original);assert.equal(links.planFile('/tmp/main.liquid','main.liquid',broken,style).ok,false);
});
test('Liquid effect catalog HTTP updates include unopened conditional templates and undo all bytes together',async t=>{
 const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),catalog=require('../src/effect-styles.cjs'),root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-liquid-effects-')),library=catalog.change(root,{type:'create',revision:null,name:style.name,properties:style.properties}),saved=library.styles[0],files=['main.liquid','unopened.liquid'];
 for(const relPath of files){const file=path.join(root,relPath),r={...resolve(source,{className:'blur-sm p-4'}),file,relPath,element:liquid.collect(source,relPath).elements[0]},result=links.plan(r,{type:'applyEffectStyle',scope:'md:'},saved);assert.equal(result.ok,true,result.reason);fs.writeFileSync(file,result.edits[0].after);}
 const snapshot=()=>Object.fromEntries([...files,'.retouch/effect-styles.json'].map(name=>[name,fs.readFileSync(path.join(root,name),'utf8')])),before=snapshot(),server=require('../src/server.cjs').startServer({appRoot:root,adapter:liquid,port:0,quiet:true});t.after(async()=>{server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});});if(!server.listening)await require('node:events').once(server,'listening');
 const url='http://localhost:'+server.address().port,shell=await(await fetch(url+'/rt')).text(),token=/__RT_TOKEN = "([0-9a-f]+)"/.exec(shell)[1],headers={'x-retouch-token':token,'content-type':'application/json'},post=async(endpoint,body)=>{const response=await fetch(url+endpoint,{method:'POST',headers,body:JSON.stringify(body)});return {status:response.status,...await response.json()};};
 const operation={type:'update',revision:library.revision,id:saved.id,name:saved.name,properties:{filter:'blur(6px)'}},updated=await post('/rt/__api/effect-styles',operation);assert.equal(updated.ok,true,updated.reason);assert.equal(updated.updated,2);assert.ok(updated.undoId);
 for(const name of files)for(const active of [false,true]){const rendered=await attrs(fs.readFileSync(path.join(root,name),'utf8'),active);assert.ok(rendered.class.includes('md:![filter:blur(6px)]'));assert.ok(rendered.class.includes(active?'blur-sm':'blur-lg'));}
 assert.equal((await post('/rt/__api/op',{type:'undo',undoId:updated.undoId})).ok,true);assert.deepEqual(snapshot(),before);
 fs.appendFileSync(path.join(root,'unopened.liquid'),'<p data-rt-effect-styles="bad">Bad</p>');const broken=snapshot(),refused=await post('/rt/__api/effect-styles',operation);assert.equal(refused.ok,false);assert.equal(refused.status,409);assert.deepEqual(snapshot(),broken);
});
