'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{collectElements,contentHash}=require('../src/id.cjs'),move=require('../src/move-component.cjs');
function resolve(source){const relPath='Page.tsx',elements=collectElements(source,relPath).elements;return {source,relPath,file:'/project/Page.tsx',elements,element:elements.find(el=>el.kind==='instance'&&el.node.openingElement.name.name==='Card'),hash:contentHash(source)};}
for(const direction of ['before','after','first','last'])test('moving a component preserves its exact props/name and maps selection: '+direction,()=>{
 const prefix='import {Card} from "./Card";export default ()=> <main>\n ',suffix='\n</main>;export const unchanged=1;',usage='<Card /* @retouch-layer "Summary" */ key={item.id} {...props} ref={ref}><span>Child</span></Card>',children=['<header/>','{prefixText}',usage,'<aside/>','<footer/>'],source=prefix+children.join('\n ')+suffix,resolved=resolve(source),plan=move.plan(resolved,{fileHash:resolved.hash,direction});assert.equal(plan.ok,true,plan.reason);
 const expected=[...children],index=({before:1,after:3,first:0,last:4})[direction];expected.splice(2,1);expected.splice(index,0,usage);assert.equal(plan.edits[0].after,prefix+expected.join('\n ')+suffix);const mapped=collectElements(plan.edits[0].after,resolved.relPath).elements.find(el=>el.id===plan.movedComponent.instanceId);assert.equal(plan.edits[0].after.slice(mapped.node.start,mapped.node.end),usage);assert.equal(plan.movedComponent.previousInstanceId,resolved.element.id);assert.notEqual(mapped.id,resolved.element.id);const mapping=new Map(plan.movedComponent.sourceIdMap),afterIds=collectElements(plan.edits[0].after,resolved.relPath).elements.map(el=>el.id);assert.deepEqual(resolved.elements.map(el=>mapping.get(el.id)||el.id).sort(),afterIds.sort());
});
test('component ordering supports fragment children and expression/text siblings without moving non-rendering comments',()=>{
 const source='export default ()=> <>Hello<Card label="x"/>{/* note */}{ready && <Other/>}</>',resolved=resolve(source),plan=move.plan(resolved,{fileHash:resolved.hash,direction:'after'});assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits[0].after,'export default ()=> <>Hello{ready && <Other/>}{/* note */}<Card label="x"/></>');assert.ok(collectElements(plan.edits[0].after,resolved.relPath).elements.some(el=>el.id===plan.movedComponent.instanceId&&el.node.openingElement.name.name==='Card'));
});
test('component movement guards stale source, boundaries and roots while reporting available directions',()=>{
 const resolved=resolve('const Page=()=> <><Card/><Other/></>');assert.deepEqual(move.describe(resolved),{containers:[],selectionContainers:[],canReparent:false,ok:true,fileHash:resolved.hash,targets:[resolved.elements.find(el=>el.node.openingElement.name.name==='Other').id],canMoveBefore:false,canMoveAfter:true,canMoveFirst:false,canMoveLast:true});for(const direction of ['before','first','unknown'])assert.equal(move.plan(resolved,{fileHash:resolved.hash,direction}).ok,false);assert.equal(move.plan(resolved,{fileHash:'stale',direction:'after'}).ok,false);assert.equal(move.describe(resolve('const Page=()=> <Card/>')).ok,false);assert.equal(move.describe(resolve('const Page=()=> ready ? <Card/> : null')).ok,false);
});

for(const [direction,target,expected]of [['before','header','<Card/><header/><section><span/></section><footer/>'],['after','footer','<header/><section><span/></section><footer/><Card/>']])test('component drop uses a named sibling destination: '+direction,()=>{
 const resolved=resolve('const Page=()=> <main><header/><Card/><section><span/></section><footer/></main>'),destination=resolved.elements.find(el=>el.node.openingElement.name.name===target),plan=move.plan(resolved,{fileHash:resolved.hash,direction,destinationId:destination.id});assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits[0].after,'const Page=()=> <main>'+expected+'</main>');assert.ok(move.describe(resolved).targets.includes(destination.id));const nested=resolved.elements.find(el=>el.node.openingElement.name.name==='span');assert.equal(move.describe(resolved).targets.includes(nested.id),false);assert.equal(move.plan(resolved,{fileHash:resolved.hash,direction,destinationId:nested.id}).ok,false);assert.equal(move.plan(resolved,{fileHash:resolved.hash,direction,destinationId:resolved.element.id}).ok,false);
});

test('dropping at the existing position creates no source edit or movement map',()=>{
 const resolved=resolve('const Page=()=> <><Card/><Other/></>'),target=resolved.elements.find(el=>el.node.openingElement.name.name==='Other'),plan=move.plan(resolved,{fileHash:resolved.hash,direction:'before',destinationId:target.id});assert.equal(plan.ok,true);assert.equal(plan.unchanged,true);assert.deepEqual(plan.edits,[]);assert.equal(plan.movedComponent,undefined);
});
