'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
for(const language of ['react','liquid']){
 const adapter=require('../src/adapters/'+language+'.cjs'),tag=e=>language==='react'?e.node.openingElement.name.name:e.tag;
 const setup=markup=>{const source=language==='react'?'const view='+markup:markup,relPath=language==='react'?'view.jsx':'view.liquid',elements=adapter.collect(source,relPath).elements;return {source,relPath,file:'/project/'+relPath,elements,element:elements.find(e=>tag(e)==='b'),hash:adapter.contentHash(source)};};
 const run=(r,tags=['b','i'],destination='aside',position='inside')=>adapter.planOp(r,{type:tags.length===1?'reparentElement':'reparentSelection',ids:r.elements.filter(e=>tags.includes(tag(e))).map(e=>e.id),destinationId:r.elements.find(e=>tag(e)===destination)?.id,position,fileHash:r.hash});
 test(language+' reparent preserves exact subtrees and all identities across parents',()=>{
  const r=setup('<main><section><b id="bold"><em>B</em></b></section><nav><i>I</i></nav><aside><u>U</u></aside></main>'),result=run(r);assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,1);assert.equal(result.edits[0].after,r.source.replace('<b id="bold"><em>B</em></b>','').replace('<i>I</i>','').replace('</aside>','<b id="bold"><em>B</em></b><i>I</i></aside>'));const final=adapter.collect(result.edits[0].after,r.relPath).elements,map=new Map(result.sourceIdMap);for(const e of r.elements)assert.equal(tag(final.find(n=>n.id===(map.get(e.id)||e.id))),tag(e));assert.deepEqual(result.selectionIds.map(id=>tag(final.find(e=>e.id===id))),['b','i']);
 });
 test(language+' reparent supports earlier destinations, sibling anchors and nested selection normalization',()=>{
  for(const position of ['inside','before','after']){const r=setup('<main><aside><u>U</u></aside><section><b><em>B</em></b><i>I</i></section></main>'),result=run(r,['b','em','i'],position==='inside'?'aside':'u',position);assert.equal(result.ok,true,result.reason);assert.equal(result.rootCount,2);const chunk='<b><em>B</em></b><i>I</i>',expected=position==='before'?chunk+'<u>U</u>':'<u>U</u>'+chunk;assert.equal(result.edits[0].after,r.source.replace('<b><em>B</em></b><i>I</i>','').replace('<u>U</u>',expected));}
 });
 test(language+' reparent refuses stale, cyclic and dynamic moves atomically',()=>{
  const r=setup('<main><section><b><em>B</em></b><i>I</i></section><aside></aside></main>');const stale=adapter.planOp(r,{type:'reparentElement',destinationId:r.elements.at(-1).id,fileHash:'old'});assert.equal(stale.refused,true);assert.equal(stale.edits,undefined);for(const destination of ['b','em'])assert.equal(run(r,['b','i'],destination).refused,true);
  const invalidForm=setup('<main><section><b>B</b><form><i>I</i></form></section><aside><form></form></aside></main>');const forms=invalidForm.elements.filter(e=>tag(e)==='form');const formMove=adapter.planOp({...invalidForm,element:forms[0]},{type:'reparentElement',fileHash:invalidForm.hash,destinationId:forms[1].id});assert.equal(formMove.refused,true);
  const scoped=setup(language==='react'?'<main><b>B</b><i>I</i>{items.map(item=><aside></aside>)}</main>':'<main><b>B</b><i>I</i>{% for item in items %}<aside></aside>{% endfor %}</main>');assert.equal(run(scoped).refused,true);
  const vector=setup('<main><svg><circle /></svg><aside></aside></main>'),circle=vector.elements.find(e=>tag(e)==='circle');if(circle)assert.equal(adapter.planOp({...vector,element:circle},{type:'reparentElement',fileHash:vector.hash,destinationId:vector.elements.find(e=>tag(e)==='aside').id}).refused,true);
  const dynamic=setup(language==='react'?'<main><section><b>B</b><i>{value}</i></section><aside></aside></main>':'<main><section><b>B</b><i>{{ value }}</i></section><aside></aside></main>');assert.equal(run(dynamic).refused,true);
 });
}
test('React reparent expands an empty self-closing destination',()=>{const adapter=require('../src/adapters/react.cjs'),source='const v=<main><b>B</b><aside /></main>',relPath='view.jsx',elements=adapter.collect(source,relPath).elements,element=elements.find(e=>e.node.openingElement.name.name==='b'),result=adapter.planOp({source,relPath,file:'/p/view.jsx',elements,element,hash:adapter.contentHash(source)},{type:'reparentElement',fileHash:adapter.contentHash(source),destinationId:elements.at(-1).id});assert.equal(result.ok,true,result.reason);assert.equal(result.edits[0].after,'const v=<main><aside ><b>B</b></aside></main>');});
