'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),P=require('../src/prototype-interactions.cjs'),C=require('../src/prototype-connect.cjs'),{SourceHistory}=require('../src/history.cjs');
for(const name of ['html','react','liquid','vue'])for(const split of [false,true])for(const creating of [false,true])for(const nested of creating?[false]:[false,true])test(name+(nested?' nested':'')+' atomic '+(creating?'new ':'')+'scroll connection '+(split?'across files':'within one file'),t=>{
 const adapter=require('../src/adapters/'+name+'.cjs'),extension={html:'html',react:'jsx',liquid:'liquid',vue:'vue'}[name],root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-connect-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const wrap=content=>name==='react'?'export default function App(){return <main>'+content+'</main>}':name==='vue'?'<script setup></script><template><main>'+content+'</main></template>':'<main>'+content+'</main>',one=path.join(root,'one.'+extension),two=split?path.join(root,'two.'+extension):one;
 fs.writeFileSync(one,wrap('<button>Scroll</button>'+(split?'':'<section>Destination</section>')));if(split)fs.writeFileSync(two,wrap('<section>Destination</section>'));
 const resolve=(file,tag)=>{const source=fs.readFileSync(file,'utf8'),relPath=path.basename(file),elements=adapter.collect(source,relPath).elements;return {appRoot:root,file,relPath,source,hash:adapter.contentHash(source),elements,element:elements.find(e=>(e.tag||e.node?.openingElement?.name.name)===tag)};};
 let source=resolve(one,'button'),history=new SourceHistory();history.commit(root,P.plan(source,{fileHash:source.hash,interactions:creating?[]:nested?[{trigger:'click',actions:[{action:'conditional',condition:{kind:'literal',type:'boolean',value:true},then:[{action:'scroll',destination:'old',scrollOffset:{x:0,y:-20}}],else:[]}]}]:[{trigger:'click',action:'scroll',destination:'old',scrollOffset:{x:0,y:-20}}]},adapter));source=resolve(one,'button');let target=resolve(two,'section');const beforeOne=source.source,beforeTwo=target.source;
 const op={type:'connectPrototypeScroll',id:source.element.id,fileHash:source.hash,index:0,targetId:target.element.id,targetHash:target.hash,...(nested?{actionPath:[0,'then',0]}:{}),...(creating?{creation:{trigger:'click'}}:{})};const plan=C.plan(source,target,op,adapter);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits.length,split?2:1);const result=history.commit(root,plan);assert.equal(result.ok,true,result.reason);
 const afterOne=fs.readFileSync(one,'utf8'),afterTwo=fs.readFileSync(two,'utf8');target=resolve(two,'section');source=resolve(one,'button');const anchor=P.metadata(target,adapter,'id').old.value;assert.match(anchor,/^rt-[a-f0-9]{24}$/);assert.equal((nested?P.describe(source,adapter).prototypeInteractions[0].actions[0].then[0]:P.describe(source,adapter).prototypeInteractions[0]).destination,anchor);if(!creating)assert.equal((nested?P.describe(source,adapter).prototypeInteractions[0].actions[0].then[0]:P.describe(source,adapter).prototypeInteractions[0]).scrollOffset.y,-20);assert.equal(source.element.id,op.id);assert.equal(target.element.id,op.targetId);
 assert.equal(C.plan(source,target,op,adapter).ok,false,'stale connection refused');assert.equal(C.plan(source,target,{...op,fileHash:source.hash,targetHash:target.hash,index:1},adapter).ok,false,'non-scroll index refused');
 const repeat=C.plan(source,target,{...op,creation:undefined,fileHash:source.hash,targetHash:target.hash},adapter);assert.equal(repeat.ok,true,repeat.reason);assert.deepEqual(repeat.edits,[],'existing anchor is reused');
 assert.equal(history.apply(root,'undo',result.undoId,adapter).ok,true);assert.equal(fs.readFileSync(one,'utf8'),beforeOne);assert.equal(fs.readFileSync(two,'utf8'),beforeTwo);assert.equal(history.apply(root,'redo',result.undoId,adapter).ok,true);assert.equal(fs.readFileSync(one,'utf8'),afterOne);assert.equal(fs.readFileSync(two,'utf8'),afterTwo);
});
for(const [name,file,source]of [['react','App.jsx','export default ()=> <main><button/><section id={name}/></main>'],['vue','App.vue','<template><main><button/><section :id="name"/></main></template>'],['liquid','page.liquid','<main><button/><section id="{{ section.id }}"></section></main>']])test(name+' computed destination IDs are not overwritten',()=>{
 const adapter=require('../src/adapters/'+name+'.cjs'),elements=adapter.collect(source,file).elements,resolved={source,relPath:file,file,elements,hash:adapter.contentHash(source)},target={...resolved,element:elements.find(e=>(e.tag||e.node?.openingElement?.name.name)==='section')};assert.throws(()=>P.metadata(target,adapter,'id'));assert.equal(P.describe(target,adapter).prototypeAnchor,undefined);
});

test('new connections reject replacement indices, invalid triggers and capacity overflow',()=>{
 const adapter=require('../src/adapters/html.cjs');
 const resolve=source=>{const elements=adapter.collect(source,'index.html').elements;return {source,relPath:'index.html',file:'/tmp/index.html',elements,element:elements.find(e=>e.tag==='button'),hash:adapter.contentHash(source)};};
 const source=resolve('<main><button>Source</button><section>Destination</section></main>'),target={...source,element:source.elements.find(e=>e.tag==='section')},op={type:'connectPrototypeScroll',id:source.element.id,fileHash:source.hash,index:0,targetId:target.element.id,targetHash:target.hash};
 for(const creation of [null,[],true,{trigger:'click',action:'back'},{trigger:'click',delay:1},{trigger:'after-delay',delay:0},{trigger:'keyboard',shortcut:{code:'NoKey'}},{trigger:'click',extra:1}])assert.equal(C.plan(source,target,{...op,creation},adapter).ok,false,JSON.stringify(creation));
 assert.equal(C.plan(source,target,{...op,index:1,creation:{trigger:'click'}},adapter).ok,false);
 const interactions=require('../shell/prototype-keys.js').codes.slice(0,32).map(code=>({trigger:'keyboard',shortcut:{code,ctrl:false,alt:false,shift:false,meta:false},action:'back'})),filled=resolve(P.plan(source,{fileHash:source.hash,interactions},adapter).edits[0].after),filledTarget={...filled,element:filled.elements.find(e=>e.tag==='section')};assert.equal(C.plan(filled,filledTarget,{...op,fileHash:filled.hash,targetHash:filled.hash,index:32,creation:{trigger:'click'}},adapter).ok,false);
});
