'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{validate}=require('../src/screen-export.cjs');
const valid=()=>({html:'<p>Screen</p>',width:390,height:844,scale:1,baseURL:'http://localhost:9000/',fontFaces:[],scroll:[],rootScroll:{x:0,y:0}});
test('screen export validates dimensions and bounds pixel and document memory',()=>{assert.doesNotThrow(()=>validate(valid()));assert.doesNotThrow(()=>validate({...valid(),area:'page'}));for(const patch of [{width:0},{width:1.5},{height:7681},{scale:9},{area:'selection'},{width:7680,height:7680,scale:2},{html:null},{html:'x'.repeat(20*1024*1024+1)}])assert.throws(()=>validate({...valid(),...patch}));});
test('screen export refuses unsafe base addresses and unavailable font definitions',()=>{for(const baseURL of ['file:///tmp/index.html','https://user:secret@example.com/','data:text/html,hi'])assert.throws(()=>validate({...valid(),baseURL}));for(const fontFaces of [null,[{sheet:'https://example.com/font.css'}],[{css:'@font-face{}'}]])assert.throws(()=>validate({...valid(),fontFaces}));});
test('screen export admits finite scroll offsets and numeric snapshot identities only',()=>{assert.doesNotThrow(()=>validate({...valid(),scroll:[{id:'12',x:-2,y:45.5}]}));for(const patch of [{scroll:[{id:'12] img',x:0,y:0}]},{scroll:[{id:'12',x:NaN,y:0}]},{rootScroll:{x:Infinity,y:0}},{scroll:null}])assert.throws(()=>validate({...valid(),...patch}));});
test('screen export serializes requests per server and releases its slot after client cancellation',async()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{once}=require('node:events'),module=require('../src/screen-export.cjs'),original=module.render,root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-export-api-'));fs.writeFileSync(path.join(root,'index.html'),'<p>Screen</p>');const server=require('../src/html-site.cjs').start({root,port:0,quiet:true});if(!server.listening)await once(server,'listening');
 try{const origin='http://localhost:'+server.address().port,html=await (await fetch(origin+'/rt')).text(),token=/window\.__RT_TOKEN = "([^"]+)"/.exec(html)[1];let begin,abort;const started=new Promise(resolve=>begin=resolve),canceled=new Promise(resolve=>abort=resolve);
  module.render=async(_,{signal})=>{begin();await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>{abort();reject(Error('canceled'));},{once:true}));};
  const options={method:'POST',headers:{'content-type':'application/json','x-retouch-token':token},body:JSON.stringify(valid())},controller=new AbortController(),first=fetch(origin+'/rt/__api/screen-export',{...options,signal:controller.signal}).catch(error=>error);await started;
  const busy=await fetch(origin+'/rt/__api/screen-export',options);assert.equal(busy.status,409);controller.abort();await first;await canceled;await new Promise(resolve=>setImmediate(resolve));module.render=async()=>Buffer.from('png');const recovered=await fetch(origin+'/rt/__api/screen-export',options);assert.equal(recovered.status,200);assert.equal(recovered.headers.get('content-type'),'image/png');assert.equal(await recovered.text(),'png');
 }finally{module.render=original;server.retouchIndex.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
});

test('screen export validates the image format and JPEG quality without applying quality to PNG',()=>{assert.doesNotThrow(()=>validate({...valid(),format:'jpeg'}));for(const quality of [1,90,100])assert.doesNotThrow(()=>validate({...valid(),format:'jpeg',quality}));for(const patch of [{format:'pdf'},{quality:90},{format:'png',quality:90},...[-1,0,101,90.5,'90',null].map(quality=>({format:'jpeg',quality}))])assert.throws(()=>validate({...valid(),...patch}));});

test('PNG transparency is boolean and never applies to JPEG',()=>{assert.doesNotThrow(()=>validate({...valid(),transparent:true}));assert.doesNotThrow(()=>validate({...valid(),format:'jpeg',transparent:false}));for(const patch of [{transparent:'true'},{transparent:1},{transparent:null},{format:'jpeg',transparent:true}])assert.throws(()=>validate({...valid(),...patch}));});

 test('custom export scales enforce finite scale and actual output bounds',()=>{for(const scale of [0.01,0.5,1.25,3,4,8])assert.doesNotThrow(()=>validate({...valid(),scale}));for(const patch of [{scale:0},{scale:0.009},{scale:8.01},{scale:'2'},{scale:NaN},{scale:Infinity},{width:1,scale:0.5},{width:7680,height:1,scale:8},{width:7680,height:7680,scale:1.067}])assert.throws(()=>validate({...valid(),...patch}));});
