'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t,markup){const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-component-reparent-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte'),text='<script>import Tile from "./Tile.svelte";let items=[1,2];let show=true;let value="outer";</script>'+markup;fs.writeFileSync(file,text);fs.writeFileSync(path.join(root,'Tile.svelte'),'<script>let {label,children}=$props();let hits=$state(0);</script><section>{label}{hits}{@render children?.()}</section>');const index=new Index(root,adapter);index.scanAll();const parsed=adapter.collect(text,'App.svelte'),ids=parsed.elements.filter(e=>e.kind==='instance').map(e=>e.id),r=index.resolve(ids[0]);return {root,file,text,index,r,ids};}
const named=(r,name)=>r.elements.find(e=>e.attributes?.some(a=>a.name==='id'&&a.value===name));
const move=(r,target,direction='inside',ids)=>adapter.planOp(r,{type:ids?'reparentComponentSelection':'moveComponent',id:r.element.id,fileHash:r.hash,destinationId:target?.id,direction,...(ids?{ids}:{})});
function exact({root,file,text},plan){const h=new SourceHistory(),saved=h.commit(root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),text);assert.equal(h.apply(root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),plan.edits[0].after);}
test('Svelte linked instances move into empty and populated containers with complete identity maps and exact history',t=>{
 for(const empty of [true,false])for(const reverse of [true,false]){const from='<section id="from"><Tile label={value}><span>Child</span></Tile><p>Keep</p></section>',to=empty?'<section id="to"/>':'<section id="to"><p>Anchor</p></section>',f=fixture(t,'<main>'+(reverse?to+from:from+to)+'</main>'),{r}=f,plan=move(r,named(r,'to'));assert.equal(plan.ok,true,plan.reason);assert.equal(adapter.describe(r).componentMovement.canReparent,true);assert.ok(adapter.describe(r).componentMovement.containers.includes(named(r,'to').id));const next=adapter.collect(plan.edits[0].after,'App.svelte').elements,map=new Map(plan.movedComponent.sourceIdMap);for(const old of r.elements)assert.ok(next.some(e=>e.id===(map.get(old.id)||old.id)&&e.tag===old.tag&&e.kind===old.kind));assert.ok(plan.edits[0].after.includes(r.source.slice(r.element.start,r.element.end)));exact(f,plan);}
});
test('Svelte selected reparenting preserves authored order from distinct containers in one transaction',t=>{
 for(const direction of ['inside','before','after']){const f=fixture(t,'<main><section><Tile label="A"><Tile label="Nested"/></Tile></section><section><Tile label="B"/></section><section id="to"><Tile label="Anchor"/><p id="anchor">Keep</p></section></main>'),{r,ids}=f,plan=move(r,named(r,direction==='inside'?'to':'anchor'),direction,[ids[2],ids[1],ids[0]]);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.rootCount,2);assert.equal(plan.selectionIds.length,2);assert.equal(plan.edits.length,1);assert.ok(plan.edits[0].after.indexOf('label="A"')<plan.edits[0].after.indexOf('label="B"'));exact(f,plan);}
});
test('Svelte component movement preserves loop, branch, snippet and local declaration scope',t=>{
 const local=fixture(t,'<main>{#each items as value}<section><Tile label={value}/></section><section id="local"/>{/each}<section id="outside"/></main>');assert.equal(move(local.r,named(local.r,'local')).ok,true);assert.equal(move(local.r,named(local.r,'outside')).refused,true);
 for(const markup of ['<main>{#if show}<Tile label="A"/>{:else}<section id="to"/>{/if}</main>','<main><Tile label={value}/>{#each items as value}<section id="to"/>{/each}</main>','<main><Tile label={value}/><section id="to">{@const value="local"}</section></main>','<main><Tile label="A"/><Tile label="Receiver"><section id="to"/></Tile></main>']){const {r}=fixture(t,markup);assert.equal(move(r,named(r,'to')).refused,true);}
});
test('Svelte component reparenting refuses cycles, generated containers and stale/invalid atomic selections',t=>{
 const {r,ids,text,file}=fixture(t,'<main><Tile label="Outer"><section id="child"><Tile label="Nested"/></section></Tile><section id="to"/><section id="generated" {...{}}/></main>');for(const target of [r.element,named(r,'child'),named(r,'generated')])assert.equal(move(r,target).refused,true);assert.equal(adapter.planOp(r,{type:'moveComponent',fileHash:'stale',direction:'inside',destinationId:named(r,'to').id}).refused,true);for(const selection of [[ids[0],ids[0]],[ids[0],'0000000000']])assert.equal(move(r,named(r,'to'),'inside',selection).refused,true);assert.equal(fs.readFileSync(file,'utf8'),text);
});
test('Svelte reparenting preserves nested responsive style ownership and recognizes an existing final position',t=>{
 const {r}=fixture(t,'<main><section id="from"><Tile label="A"><div id="styled">Child</div></Tile></section><section id="to"/></main>'),child=named(r,'styled'),style=adapter.planOp({...r,element:child},{type:'setCSS',fileHash:r.hash,property:'padding',value:'17px',width:768});assert.equal(style.ok,true,style.reason);const text=style.edits[0].after,elements=adapter.collect(text,'App.svelte').elements,current={...r,source:text,hash:adapter.contentHash(text),elements,element:elements.find(e=>e.kind==='instance')},plan=move(current,named(current,'to'));assert.equal(plan.ok,true,plan.reason);const next=adapter.collect(plan.edits[0].after,'App.svelte').elements,final={...current,source:plan.edits[0].after,hash:plan.hash,elements:next,element:next.find(e=>e.id===plan.movedComponent.instanceId)};assert.equal(adapter.describe({...final,element:named(final,'styled')}).cssRules[768].padding,'17px');assert.equal(move(final,named(final,'to')).unchanged,true);
});
test('Svelte selected moves combine existing destination children and cross-parent component anchors',t=>{
 const f=fixture(t,'<main><section><Tile label="A"/></section><section id="to"><Tile label="B"/><Tile label="Anchor"/></section></main>'),{r,ids}=f;
 const into=move(r,named(r,'to'),'inside',[ids[0],ids[1]]);assert.equal(into.ok,true,into.reason);assert.equal(adapter.planOp(r,{type:'reparentComponentSelection',fileHash:r.hash,ids:[ids[0],ids[1]],destinationId:named(r,'to').id}).ok,true);assert.deepEqual(adapter.collect(into.edits[0].after,'App.svelte').elements.filter(e=>e.kind==='instance').map(e=>into.edits[0].after.slice(e.start,e.end)),['<Tile label="Anchor"/>','<Tile label="A"/>','<Tile label="B"/>']);exact(f,into);
 for(const direction of ['before','after']){const positioned=move(r,r.elements.find(e=>e.id===ids[2]),direction);assert.equal(positioned.ok,true,positioned.reason);const code=positioned.edits[0].after,order=adapter.collect(code,'App.svelte').elements.filter(e=>e.kind==='instance').map(e=>code.slice(e.start,e.end));assert.deepEqual(order,direction==='before'?['<Tile label="B"/>','<Tile label="A"/>','<Tile label="Anchor"/>']:['<Tile label="B"/>','<Tile label="Anchor"/>','<Tile label="A"/>']);}
});
