'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t,script){const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-default-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte'),def=path.join(root,'Badge.svelte'),text='<script>import Badge from "./Badge.svelte";</script><main><Badge/><Badge label="Override"/></main>',definition=script+'<section>{'+(script.includes('label:local')?'local':'label')+'}</section>';fs.writeFileSync(file,text);fs.writeFileSync(def,definition);const index=new Index(root,adapter);index.scanAll();const r=index.resolve(adapter.collect(text,'App.svelte').elements.find(e=>e.kind==='instance').id);return {root,file,def,text,definition,index,r};}
function edit(f,value,extra={}){const meta=adapter.describeComponent(f.r).props.find(p=>p.name==='label')?.defaultEditor;return adapter.planOp(f.r,{type:'setComponentDefault',name:'label',value,fileHash:f.r.hash,revision:meta?.revision,...extra});}
for(const script of ['<script>let {label="Before"}=$props();</script>','<script>export let label="Before";</script>','<script>let {label:local="Before"}=$props();</script>'])test('Svelte shared default writes only its literal and supports exact history: '+script,t=>{const f=fixture(t,script),plan=edit(f,'After </script>\n"quoted"');assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[1].after,/After \\u003c\/script>/);assert.equal(plan.edits[0].after,f.text);const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);f.index.scanAll();assert.equal(adapter.describeComponent(f.index.resolve(f.r.element.id)).props.find(p=>p.name==='label').defaultEditor.value,'After </script>\n"quoted"');assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.def,'utf8'),f.definition);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.def,'utf8'),plan.edits[1].after);});
test('Svelte shared default respects typed choices and stale definition revisions',t=>{const f=fixture(t,'<script lang="ts">let {label="quiet"}:{label?:"quiet"|"bold"}=$props();</script>');assert.deepEqual(adapter.describeComponent(f.r).props[0].defaultEditor.choices,['quiet','bold']);assert.equal(edit(f,'other').refused,true);assert.equal(edit(f,'bold',{revision:'stale'}).refused,true);assert.equal(edit(f,'bold',{fileHash:'stale'}).refused,true);const plan=edit(f,'bold');assert.equal(plan.ok,true,plan.reason);fs.writeFileSync(f.def,f.definition+' ');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);});
test('Svelte shared defaults do not expose computed, bindable, or unsupported declared defaults',t=>{for(const script of ['<script>let {label=String("x")}=$props();</script>','<script>let {label=$bindable("x")}=$props();</script>','<script lang="ts">let {label="x"}:{label:unknown}=$props();</script>','<script lang="ts">import type {Props} from "./types";let {label="x"}:Props=$props();</script>']){const f=fixture(t,script);assert.equal(adapter.describeComponent(f.r).props.some(p=>p.defaultEditor),false);assert.equal(edit(f,'next').refused,true);}});
test('Svelte shared numeric default preserves negative zero and rejects nonfinite values',t=>{const f=fixture(t,'<script>let {label=1}=$props();</script>');assert.equal(edit(f,Infinity).refused,true);assert.equal(edit(f,'2').refused,true);const plan=edit(f,-0);assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[1].after,/label=-0/);});
test('Svelte default history publishes exact script and nested-instance retention proofs, invalidated by external edits',t=>{
 const f=fixture(t,'<script>import Leaf from "./Leaf.svelte";let {label="Before"}=$props();let count=$state(0);</script>');fs.writeFileSync(f.def,f.definition.replace('</section>','<Leaf/></section>'));f.definition=fs.readFileSync(f.def,'utf8');const plan=edit(f,'After');assert.equal(plan.ok,true,plan.reason);const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);
 const migration=require('../src/svelte-component-migrations.cjs'),state=require('../src/svelte-component-state.cjs'),hash=require('../src/svelte-source.cjs').contentHash,after=plan.edits.find(e=>e.file===fs.realpathSync(f.def)).after,beforeMeta=state.metadata(f.definition,'Badge.svelte'),afterMeta=state.metadata(after,'Badge.svelte'),forward=migration.read(f.def,hash(after))[0];assert.equal(forward.fromScript,beforeMeta.script);assert.equal(forward.toScript,afterMeta.script);assert.deepEqual(forward.pairs,forward.ids.map(id=>[id,id]));assert.equal(forward.pairs.length,1);
 assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);const reverse=migration.read(f.def,hash(f.definition))[0];assert.equal(reverse.fromScript,afterMeta.script);assert.equal(reverse.toScript,beforeMeta.script);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(migration.read(f.def,hash(after)).length,1);migration.observe(f.def,hash(after),hash(after+' '));assert.deepEqual(migration.read(f.def,hash(after)),[]);
});
