'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),source=require('../src/svelte-source.cjs'),adapter=require('../src/adapters/svelte.cjs'),compiler=require('svelte/compiler');
function resolve(text,tag='h1'){const relPath='App.svelte',elements=source.collect(text,relPath).elements;return {source:text,relPath,file:'/tmp/App.svelte',elements,element:elements.find(e=>e.tag===tag),hash:source.contentHash(text)};}
test('Svelte compiler mapping traverses branches, loops, slots and snippets without entering JavaScript or head',()=>{
 const text='<script>let active=true;let items=[1];</script><svelte:head><title>Title</title></svelte:head><h1>Hello</h1>{#if active}<p>Yes</p>{:else}<p>No</p>{/if}{#each items as item}<span>{item}</span>{/each}{#snippet item()}<b>Snippet</b>{/snippet}<Widget><i>Slot</i></Widget><div {...props}><small>Child</small></div>',r=source.collect(text,'App.svelte');assert.deepEqual(r.elements.map(e=>e.tag),['h1','p','p','span','b','i','small']);assert.equal(new Set(r.elements.map(e=>e.id)).size,r.elements.length);assert.equal(r.excluded.length,1);assert.equal(r.elements.find(e=>e.tag==='span').scope.repeated,true);assert.equal(r.elements.find(e=>e.tag==='i').scope.slotted,true);assert.deepEqual(source.collect(text.replace('Hello','Different text').replace('<h1>','<h1 title="a>b">'),'App.svelte').elements.map(e=>e.id),r.elements.map(e=>e.id));
 const stamped=source.stamp(text,'/tmp/App.svelte','/tmp');assert.equal((stamped.code.match(/data-rt="/g)||[]).length,7);assert.equal((stamped.code.match(/data-rt-revision="/g)||[]).length,7);assert.ok(stamped.map);assert.equal(stamped.code.includes('<Widget data-rt'),false);
});
test('Svelte literal text rewrites preserve component logic and encode template syntax',()=>{
 const original='<script>let count=0;</script><h1 title="a>b">Hello &amp; world</h1><button onclick={()=>count++}>Count {count}</button><style>h1{color:red}</style>',r=resolve(original),info=adapter.describe(r);assert.equal(info.text,'Hello & world');
 const result=adapter.planOp(r,{type:'setText',fileHash:r.hash,text:'Literal {count} <b> & text'});assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,1);const after=result.edits[0].after;assert.ok(after.includes('Literal &#123;count&#125; &lt;b&gt; &amp; text'));assert.ok(after.endsWith(original.slice(original.indexOf('<button'))));assert.equal(adapter.describe(resolve(after)).text,'Literal {count} <b> & text');compiler.compile(source.stamp(after,'/tmp/App.svelte','/tmp').code,{filename:'App.svelte',generate:false});assert.deepEqual(adapter.planOp(resolve(after),{type:'setText',fileHash:source.contentHash(after),text:'Literal {count} <b> & text'}).edits,[]);
 const empty=resolve('<h1></h1>');assert.equal(adapter.planOp(empty,{type:'setText',fileHash:empty.hash,text:'New'}).edits[0].after,'<h1>New</h1>');
});
test('Svelte refuses expression, markup, binding, SVG and stale text writes without source edits',()=>{
 for(const text of ['<h1>{name}</h1>','<h1>Hello <b>world</b></h1>','<h1>{@html html}</h1>','<h1 contenteditable bind:textContent={text}>Hello</h1>','<svg><h1>SVG</h1></svg>']){const r=resolve(text),result=adapter.planOp(r,{type:'setText',fileHash:r.hash,text:'Replace'});assert.equal(result.ok,false,text);assert.equal(result.edits,undefined);}
 const r=resolve('<h1>Hello</h1>');assert.equal(adapter.planOp(r,{type:'setText',fileHash:'stale',text:'Replace'}).ok,false);assert.equal(adapter.planOp(r,{type:'setClasses',fileHash:r.hash,classes:'p-4'}).ok,false);
});
test('Svelte literal labels, links and image paths preserve bindings and surrounding bytes',()=>{
 const text='<h1>Hello</h1><a href="/old" onclick={click}>Link</a><img src="/old.png" alt="Photo"/>',r=resolve(text);const name=adapter.planOp(r,{type:'renameElement',fileHash:r.hash,name:'Hero {name}'});assert.equal(name.ok,true,name.reason);assert.ok(name.edits[0].after.startsWith('<h1 data-rt-name="Hero &#123;name&#125;">'));
 const link=resolve(text,'a'),changed=adapter.planOp(link,{type:'setHref',fileHash:link.hash,href:'/new?a=1&b=2'});assert.equal(changed.ok,true,changed.reason);assert.ok(changed.edits[0].after.includes('href="/new?a=1&amp;b=2" onclick={click}'));const img=resolve(text,'img');assert.equal(adapter.planOp(img,{type:'setSrc',fileHash:img.hash,src:'/new.png'}).ok,true);
 for(const text of ['<img src={url}/>','<picture><img src="/old.png"/></picture>','<img src="/old.png" srcset="/large.png 2x"/>']){const r=resolve(text,'img');assert.equal(adapter.planOp(r,{type:'setSrc',fileHash:r.hash,src:'/new.png'}).ok,false);}
});
test('Svelte live-text stamps compile with module scripts and keep text-only updates separate from logic',()=>{
 for(const original of ['<h1>Hello</h1>','<script module>export const title="Title";</script><h1>Hello</h1>','<script lang="ts">let count:number=0;</script><h1>Hello</h1><p>{count}</p>']){const stamped=source.stamp(original,'/tmp/App.svelte','/tmp',{runtime:true});compiler.compile(stamped.code,{filename:'App.svelte',generate:false});assert.match(stamped.code,/virtual:retouch-svelte-source/);const before=source.textSnapshot(original,'App.svelte'),next=source.textSnapshot(original.replace('Hello','Different &#123;literal&#125;'),'App.svelte');assert.equal(before.signature,next.signature);assert.notEqual(before.revision,next.revision);}
 for(const [before,after]of [['<h1>Hello</h1>','<h2>Hello</h2>'],['<script>let n=0;</script><h1>Hello</h1>','<script>let n=1;</script><h1>Hello</h1>'],['<h1>Hello</h1>','<h1>  Whitespace\n changed </h1>'],['<h1>Hello</h1><style>h1{color:red}</style>','<h1>Hello</h1><style>h1{color:blue}</style>']])assert.notEqual(source.textSnapshot(before,'App.svelte').signature,source.textSnapshot(after,'App.svelte').signature);
 const existing='<h1 DATA-RT="legacy">Hello</h1>';assert.equal((source.stamp(existing,'/tmp/App.svelte','/tmp').code.match(/data-rt=/gi)||[]).length,1);
});
test('Svelte source markers and literal attributes reject case-insensitive binding collisions',()=>{
 for(const text of ['<h1 DATA-RT={id}>Hello</h1>','<h1 data-rt="one" DATA-RT="two">Hello</h1>'])assert.equal(source.collect(text,'App.svelte').elements.length,0);
 for(const text of ['<a HREF={url}>Link</a>','<a href="/one" HREF="/two">Link</a>']){const r=resolve(text,'a');assert.equal(adapter.describe(r).canSetHref,false);assert.equal(adapter.planOp(r,{type:'setHref',fileHash:r.hash,href:'/new'}).ok,false);}
});
