'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),definitions=require('../src/svelte-component-definitions.cjs'),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
const badge='<script lang="ts">let {label,size="small",amount=1,enabled=true}:{label:string;size?:"small"|"large";amount?:number;enabled?:boolean}=$props();let hits=$state(0);</script><section>{label}{size}{amount}{enabled}{hits}</section>';
function fixture(t,text='<script>let count=$state(1);</script><main><section id="target"/><p>Keep</p></main>',def=badge){const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-insert-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte'),definition=path.join(root,'Badge.svelte');fs.writeFileSync(file,text);fs.writeFileSync(definition,def);const index=new Index(root,adapter);index.scanAll();const element=adapter.collect(text,'App.svelte').elements.find(e=>e.attributes?.some(a=>a.name==='id'&&a.value==='target'));return {root,file,text,definition,def,index,r:index.resolve(element.id)};}
function insert(f,overrides={}){const d=definitions.definitions(f.def,'Badge.svelte')[0];return adapter.planOp(f.r,{type:'insertComponent',fileHash:f.r.hash,definitionFile:'Badge.svelte',definitionId:d.definitionId,definitionHash:adapter.contentHash(f.def),contractHash:definitions.schema(f.def).revision,props:{label:'Hello'},...overrides});}
test('Svelte library discovers unused definitions and exposes required primitive insertion properties',t=>{const f=fixture(t),library=require('../src/component-usage.cjs').library(f.index),entry=library.components.find(e=>e.file==='Badge.svelte');assert.equal(entry.usageCount,0);assert.equal(entry.definitionOnly,true);const info=definitions.describe(f.index.resolve(entry.definitionId));assert.equal(info.insertion.ok,true);assert.deepEqual(info.insertion.properties.find(p=>p.name==='label'),{name:'label',type:'string',required:true,defaulted:false,supported:true});assert.deepEqual(info.insertion.properties.find(p=>p.name==='size').choices,['small','large']);assert.equal(adapter.describe(f.r).canInsertComponent,true);});
test('Svelte insertion adds a linked import and maps existing layers with exact undo/redo and script proofs',t=>{for(const text of [undefined,'<main><section id="target"></section></main>']){const f=fixture(t,text),plan=insert(f);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.insertedComponent.preserveScriptState,true);assert.match(plan.edits[0].after,/import Badge from "\.\/Badge.svelte"/);assert.match(plan.edits[0].after,/<Badge label={"Hello"}\/>/);const parsed=adapter.collect(plan.edits[0].after,'App.svelte'),map=new Map(plan.insertedComponent.sourceIdMap);for(const old of f.r.elements)assert.ok(parsed.elements.some(e=>e.id===(map.get(old.id)||old.id)&&e.kind===old.kind&&e.tag===old.tag));const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);const migrations=require('../src/svelte-component-migrations.cjs'),forward=migrations.read(f.file,plan.hash)[0];assert.ok(forward.fromScript&&forward.toScript);assert.notEqual(forward.fromScript,forward.toScript);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(migrations.read(f.file,f.r.hash)[0].fromScript,forward.toScript);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),plan.edits[0].after);}});
test('Svelte insertion reuses accessible imports and chooses a fresh alias around template shadowing',t=>{const f=fixture(t,'<script>import Existing from "./Badge.svelte";</script><main><section id="target"/></main>'),plan=insert(f);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.insertedComponent.preserveScriptState,false);assert.match(plan.edits[0].after,/<Existing label=/);assert.equal((plan.edits[0].after.match(/import /g)||[]).length,1);const shadow=fixture(t,'<script>import Badge from "./Badge.svelte";let items=[];</script><main>{#each items as Badge}<section id="target"/>{/each}</main>'),next=insert(shadow);assert.equal(next.ok,true,next.reason);assert.match(next.edits[0].after,/import Badge2 from/);assert.match(next.edits[0].after,/<Badge2 label=/);});
test('Svelte initial values preserve literals and enforce required fields, choices and definition snapshots',t=>{const f=fixture(t);for(const props of [{},{label:3},{label:'X',size:'unknown'},{label:'X',amount:Infinity},{label:'X',unknown:'bad'}])assert.equal(insert(f,{props}).refused,true);const plan=insert(f,{props:{label:'<script>\n"',amount:-0,enabled:false,size:'large'}});assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/amount={-0}/);assert.match(plan.edits[0].after,/\\u003cscript>/);assert.equal(insert(f,{fileHash:'stale'}).refused,true);assert.equal(insert(f,{contractHash:'stale'}).refused,true);fs.writeFileSync(f.definition,f.def+' ');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);});
test('Svelte library insertion refuses recursive definitions, fixed IDs and unsupported required contracts',t=>{const f=fixture(t),self={...definitions.definitions(f.text,'App.svelte')[0]};assert.equal(insert(f,{definitionFile:'App.svelte',definitionId:self.definitionId,definitionHash:f.r.hash}).refused,true);const cycle=fixture(t,undefined,badge.replace('<script lang="ts">','<script lang="ts">import App from "./App.svelte";'));assert.equal(insert(cycle).refused,true);const fixed=fixture(t,undefined,badge.replace('<section>','<section id="fixed">'));assert.equal(insert(fixed).refused,true);const unsupported=fixture(t,undefined,'<script>let {callback}=$props();</script><section/>');assert.equal(definitions.schema(unsupported.def).properties[0].supported,false);assert.equal(insert(unsupported,{props:{callback:'wrong'}}).refused,true);});
test('Svelte insertion guards transitive component definitions and refuses nested fixed identities or cycles',t=>{
 const def=badge.replace('<script lang="ts">','<script lang="ts">import Leaf from "./Leaf.svelte";').replace('</section>','<Leaf/></section>'),f=fixture(t,undefined,def),leaf=path.join(f.root,'Leaf.svelte');fs.writeFileSync(leaf,'<small>Leaf</small>');const plan=insert(f);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits.length,3);fs.writeFileSync(leaf,'<small>Changed</small>');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);fs.writeFileSync(leaf,'<small id="fixed">Leaf</small>');assert.equal(insert(f).refused,true);fs.writeFileSync(leaf,'<script>import App from "./App.svelte";</script><App/>');assert.equal(insert(f).refused,true);assert.equal(insert(f,{definitionFile:'../Badge.svelte'}).refused,true);
});
test('Svelte insertion resolves nested path aliases and guards inherited configuration and fallback paths',t=>{
 const def=badge.replace('<script lang="ts">','<script lang="ts">import Leaf from "@ui/Leaf.svelte";').replace('</section>','<Leaf/></section>'),f=fixture(t,undefined,def),config=path.join(f.root,'jsconfig.json'),base=path.join(f.root,'base.json'),leaf=path.join(f.root,'Leaf.svelte');
 fs.writeFileSync(config,'{"extends":"./base.json"}');fs.writeFileSync(base,'{"compilerOptions":{"paths":{"@ui/*":["preferred/*","*"]}}}');fs.writeFileSync(leaf,'<small>Leaf</small>');
 const plan=insert(f);assert.equal(plan.ok,true,plan.reason);assert.ok(plan.pathChecks.some(c=>c.file===path.join(fs.realpathSync(f.root),'preferred/Leaf.svelte')&&c.kind==='missing'));assert.ok(plan.edits.some(e=>e.file===fs.realpathSync(base)&&e.before===e.after));
 fs.mkdirSync(path.join(f.root,'preferred'));fs.writeFileSync(path.join(f.root,'preferred/Leaf.svelte'),'<small>Preferred</small>');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);fs.rmSync(path.join(f.root,'preferred'),{recursive:true});
 fs.writeFileSync(base,'{"compilerOptions":{"paths":{"@ui/*":["*"]}}}');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);const next=insert(f);assert.equal(next.ok,true,next.reason);fs.writeFileSync(path.join(f.root,'tsconfig.json'),'{}');assert.equal(new SourceHistory().commit(f.root,next).ok,false);fs.unlinkSync(path.join(f.root,'tsconfig.json'));
 const history=new SourceHistory(),saved=history.commit(f.root,insert(f));assert.equal(saved.ok,true,saved.reason);assert.equal(history.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(history.apply(f.root,'redo',saved.undoId,adapter).ok,true);
});
test('Svelte aliased dependencies retain cycle, fixed identity, symlink and containment checks',t=>{
 const def=badge.replace('<script lang="ts">','<script lang="ts">import Leaf from "@ui/Leaf.svelte";').replace('</section>','<Leaf/></section>'),f=fixture(t,undefined,def),config=path.join(f.root,'tsconfig.json'),leaf=path.join(f.root,'Leaf.svelte');
 fs.writeFileSync(config,'{"compilerOptions":{"paths":{"@ui/*":["*"]}}}');fs.writeFileSync(leaf,'<script>import App from "@ui/App.svelte";</script><App/>');assert.match(insert(f).reason,/cycle/);
 fs.writeFileSync(leaf,'<small id="fixed">Leaf</small>');assert.match(insert(f).reason,/fixed DOM ID/);fs.writeFileSync(path.join(f.root,'Actual.svelte'),'<small/>');fs.unlinkSync(leaf);fs.symlinkSync('./Actual.svelte',leaf);assert.match(insert(f).reason,/symlinks/);fs.unlinkSync(leaf);
 fs.writeFileSync(config,'{"compilerOptions":{"paths":{"@ui/*":["../*"]}}}');assert.match(insert(f).reason,/outside the project/);
 fs.writeFileSync(config,'{"compilerOptions":{"paths":{"@ui/*":["node_modules/*"]}}}');assert.match(insert(f).reason,/outside the project/);
 fs.writeFileSync(config,'{}');assert.match(insert(f).reason,/does not resolve/);
});
