'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const source=require('../src/svelte-source.cjs'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t,text='<script>import Badge from "./Badge.svelte";</script><main><Badge label="One"/><p>Between</p>{#if true}<Badge label="Two"/>{/if}<Badge label="Three"/></main>'){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-structure-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte'),def=path.join(root,'Badge.svelte');fs.writeFileSync(file,text);fs.writeFileSync(def,'<script>let {label}=$props();</script><section>{label}</section>');const index=new Index(root,adapter);index.scanAll();const ids=source.collect(text,'App.svelte').components.map(e=>e.id);return {root,file,def,text,index,ids,r:index.resolve(ids[0])};
}
function history(root,plan,file,text){const h=new SourceHistory(),saved=h.commit(root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),text);assert.equal(h.apply(root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),plan.edits[0].after);}
test('Svelte linked instance duplication maps every surviving native and component source layer',t=>{
 const {root,file,def,text,r}=fixture(t),info=adapter.describeComponent(r);assert.equal(info.canDuplicate,true,info.duplicateReason);const plan=adapter.planOp(r,{type:'duplicateComponent',fileHash:r.hash});assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits.length,2);const after=adapter.collect(plan.edits[0].after,'App.svelte').elements,map=new Map(plan.duplicatedComponent.sourceIdMap);for(const old of r.elements)assert.ok(after.some(e=>e.id===(map.get(old.id)||old.id)&&e.kind===old.kind&&e.tag===old.tag));assert.equal(after.find(e=>e.id===plan.duplicatedComponent.instanceId).tag,'Badge');assert.equal(fs.readFileSync(file,'utf8'),text);history(root,plan,file,text);
});
test('Svelte deletion preserves unrelated IDs, imports and exact history across conditional usages',t=>{
 const {root,file,text,index,ids}=fixture(t),r=index.resolve(ids[1]),plan=adapter.planOp(r,{type:'deleteComponent',fileHash:r.hash});assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/{#if true}{#if false}{\/if}{\/if}/);assert.match(plan.edits[0].after,/import Badge/);const remaining=adapter.collect(plan.edits[0].after,'App.svelte').elements;for(const e of r.elements.filter(e=>!plan.deletedComponent.removedSourceIds.includes(e.id)))assert.ok(remaining.some(item=>item.id===e.id&&item.tag===e.tag));history(root,plan,file,text);
});
test('Svelte batch duplication and deletion stage distinct usages in one atomic source transaction',t=>{
 const {root,file,text,r,ids,index}=fixture(t);for(const type of ['duplicateComponentSelection','deleteComponentSelection']){const plan=adapter.planOp(r,{type,ids:[ids[0],ids[2]],fileHash:r.hash});assert.equal(plan.ok,true,plan.reason);assert.equal(plan.rootCount,2);assert.equal(plan.edits.filter(e=>e.before!==e.after).length,1);assert.equal(source.collect(plan.edits[0].after,'App.svelte').components.length,type.startsWith('duplicate')?5:1);assert.equal(fs.readFileSync(file,'utf8'),text);}
 const bad=adapter.planOp(r,{type:'duplicateComponentSelection',ids:[ids[0],ids[0]],fileHash:r.hash});assert.equal(bad.refused,true);assert.equal(adapter.planOp(r,{type:'deleteComponent',fileHash:'stale'}).refused,true);
});
test('Svelte component duplication refuses identity conflicts and guards definition changes',t=>{
 for(const attribute of ['id="fixed"','bind:this={target}','{...attrs}','ref={target}']){const {r}=fixture(t,'<script>import Badge from "./Badge.svelte";let target;let attrs={};</script><main><Badge '+attribute+'/></main>');assert.equal(adapter.planOp(r,{type:'duplicateComponent',fileHash:r.hash}).refused,true);}
 const {root,r,def,file,text}=fixture(t),plan=adapter.planOp(r,{type:'duplicateComponent',fileHash:r.hash});fs.writeFileSync(def,'<section id={"fixed"}/>');assert.equal(adapter.describeComponent(r).canDuplicate,false);assert.equal(adapter.planOp(r,{type:'duplicateComponent',fileHash:r.hash}).refused,true);assert.equal(new SourceHistory().commit(root,plan).ok,false);assert.equal(fs.readFileSync(file,'utf8'),text);
});
test('Svelte component copies own their nested responsive styles and delete cleans only removed styles',t=>{
 const {root,file,r,text}=fixture(t,'<script>import Badge from "./Badge.svelte";</script><main><Badge label="One"><p>Child</p></Badge><Badge label="Two"/></main>');const child=r.elements.find(e=>e.tag==='p'),styled=adapter.planOp({...r,element:child},{type:'setCSS',fileHash:r.hash,property:'padding',value:'7px',width:0});assert.equal(styled.ok,true,styled.reason);const code=styled.edits[0].after,parsed=adapter.collect(code,'App.svelte'),current={...r,source:code,hash:source.contentHash(code),elements:parsed.elements,element:parsed.elements.find(e=>e.kind==='instance')};const copy=adapter.planOp(current,{type:'duplicateComponent',fileHash:current.hash});assert.equal(copy.ok,true,copy.reason);const css=require('../src/svelte-css.cjs'),before=css.documentState(code,'App.svelte'),after=css.documentState(copy.edits[0].after,'App.svelte');assert.equal(Object.keys(before.model.layers).length,1);assert.equal(Object.keys(after.model.layers).length,2);assert.deepEqual(Object.values(after.model.layers)[0],Object.values(after.model.layers)[1]);const deleted=adapter.planOp(current,{type:'deleteComponent',fileHash:current.hash});assert.equal(deleted.ok,true,deleted.reason);assert.equal(Object.keys(css.documentState(deleted.edits[0].after,'App.svelte').model.layers).length,0);
});
test('Svelte structural selections collapse nested usages and refuse an unsafe batch without writing',t=>{
 const {r,ids,text,file}=fixture(t,'<script>import Badge from "./Badge.svelte";</script><main><Badge label="Outer"><Badge label="Inner"/></Badge></main>');
 for(const type of ['duplicateComponentSelection','deleteComponentSelection']){const plan=adapter.planOp(r,{type,fileHash:r.hash,ids});assert.equal(plan.ok,true,plan.reason);assert.equal(plan.rootCount,1);assert.equal(source.collect(plan.edits[0].after,'App.svelte').components.length,type.startsWith('duplicate')?4:0);}assert.equal(fs.readFileSync(file,'utf8'),text);
 const unsafe=fixture(t,'<script>import Badge from "./Badge.svelte";</script><main><Badge label="Safe"/><Badge id="unsafe"/></main>'),refused=adapter.planOp(unsafe.r,{type:'duplicateComponentSelection',fileHash:unsafe.r.hash,ids:unsafe.ids});assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);assert.equal(fs.readFileSync(unsafe.file,'utf8'),unsafe.text);
});
test('Svelte ordering maps whole subtrees across hosts and control flow with exact history',t=>{
 const {root,file,text,r,ids,index}=fixture(t);assert.equal(adapter.describeComponent(r).movement.canMoveAfter,true);assert.equal(adapter.describe(r).componentMovement.canMoveAfter,true);
 const plan=adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'last'});assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/<main><p>Between<\/p>{#if true}<Badge label="Two"\/>{\/if}<Badge label="Three"\/><Badge label="One"\/><\/main>/);const next=adapter.collect(plan.edits[0].after,'App.svelte').elements,map=new Map(plan.movedComponent.sourceIdMap);for(const old of r.elements){const moved=next.find(e=>e.id===(map.get(old.id)||old.id));assert.equal(moved.tag,old.tag);if(old.kind==='instance')assert.equal(plan.edits[0].after.slice(moved.start,moved.end),text.slice(old.start,old.end));}history(root,plan,file,text);
 assert.equal(adapter.planOp(r,{type:'moveComponent',fileHash:'stale',direction:'after'}).refused,true);assert.equal(adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'inside'}).refused,true);assert.equal(adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'after',destinationId:ids[1]}).refused,true);
});
test('Svelte selected ordering is atomic and preserves source order within the selection',t=>{
 const {r,ids,text,file}=fixture(t),plan=adapter.planOp(r,{type:'reparentComponentSelection',fileHash:r.hash,ids:[ids[2],ids[0]],direction:'last'});assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/<Badge label="One"\/><Badge label="Three"\/><\/main>/);assert.equal(plan.selectionIds.length,2);assert.equal(plan.edits.length,1);assert.equal(fs.readFileSync(file,'utf8'),text);assert.equal(adapter.planOp(r,{type:'moveComponentSelection',fileHash:r.hash,ids:[ids[0],ids[1]],direction:'last'}).refused,true);
});
test('Same-shape Svelte moves publish reversible state identity migrations',t=>{
 const {root,file,r,text}=fixture(t,'<script>import Badge from "./Badge.svelte";</script><main><Badge label="One"/><Badge label="Two"/></main>'),plan=adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'after'});assert.equal(plan.ok,true,plan.reason);const after=plan.edits[0].after;assert.equal(source.textSnapshot(text,'App.svelte').signature,source.textSnapshot(after,'App.svelte').signature);const h=new SourceHistory(),saved=h.commit(root,plan);assert.equal(saved.ok,true,saved.reason);const migrations=require('../src/svelte-component-migrations.cjs'),edge=migrations.read(file,source.contentHash(after))[0];assert.equal(edge.from,edge.to);assert.deepEqual(edge.pairs,plan.movedComponent.sourceIdMap);assert.equal(h.apply(root,'undo',saved.undoId,adapter).ok,true);assert.deepEqual(migrations.read(file,source.contentHash(text))[0].pairs,edge.pairs.map(([a,b])=>[b,a]));
});
test('Svelte moves preserve nested calls and conditional scope and report boundary no-ops',t=>{
 const {r,index,ids,text}=fixture(t,'<script>import Badge from "./Badge.svelte";</script><main>{#if true}<Badge label="Outer"><Badge label="Nested"/></Badge><!--gap--><Badge label="Sibling"/>{/if}<Badge label="Outside"/></main>');
 const plan=adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'after',destinationId:ids[2]});assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/<Badge label="Sibling"\/><!--gap--><Badge label="Outer"><Badge label="Nested"\/><\/Badge>/);const moved=new Map(plan.movedComponent.sourceIdMap),next=adapter.collect(plan.edits[0].after,'App.svelte').elements;assert.equal(next.find(e=>e.id===moved.get(ids[1])).tag,'Badge');
 assert.equal(adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'before'}).unchanged,true);assert.equal(adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'before',destinationId:ids[2]}).unchanged,true);assert.equal(adapter.planOp(r,{type:'moveComponent',fileHash:r.hash,direction:'after',destinationId:ids[3]}).refused,true);
 const selected=adapter.planOp(r,{type:'reparentComponentSelection',ids:[ids[0],ids[1]],fileHash:r.hash,direction:'last'});assert.equal(selected.ok,true,selected.reason);assert.equal(selected.rootCount,1);assert.equal(selected.edits[0].after,plan.edits[0].after);
});
