'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),source=require('../src/svelte-source.cjs'),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t,usage='<Badge label={count}><span>Caller child</span></Badge><Badge label="Sibling"/>',definition='<script>import Leaf from "./Leaf.svelte";let {label,children}=$props();let hits=$state(0);</script><section><h2>Shared text</h2><Leaf/>{label}{hits}{@render children?.()}</section><style>h2{color:red}</style>'){const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-detach-')),file=path.join(root,'App.svelte'),def=path.join(root,'Badge.svelte'),text='<script>import Badge from "./Badge.svelte";let count=$state(2);</script><main>'+usage+'</main>';t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.writeFileSync(file,text);fs.writeFileSync(def,definition);fs.writeFileSync(path.join(root,'Leaf.svelte'),'<small>Nested</small>');const index=new Index(root,adapter);index.scanAll();const r=index.resolve(adapter.collect(text,'App.svelte').elements.find(e=>e.kind==='instance').id);return {root,file,def,text,definition,index,r};}
function detach(f,overrides={}){return adapter.planOp(f.r,{type:'detachComponent',fileHash:f.r.hash,definitionHash:source.contentHash(f.definition),...overrides});}
test('Svelte detach creates a same-directory independent module and preserves bound props, children and usage IDs',t=>{
 const f=fixture(t),info=adapter.describeComponent(f.r);assert.equal(info.canDetach,true,info.reason);const plan=detach(f);assert.equal(plan.ok,true,plan.reason);assert.equal(path.dirname(plan.createdFile),fs.realpathSync(f.root));assert.equal(plan.edits[0].after,f.definition);assert.match(plan.edits[1].after,/label={count}><span>Caller child<\/span><\/BadgeDetached_/);assert.match(plan.edits[1].after,/<Badge label="Sibling"\/>/);assert.deepEqual(adapter.collect(plan.edits[1].after,'App.svelte').elements.map(e=>[e.id,e.kind]),f.r.elements.map(e=>[e.id,e.kind]));assert.equal(fs.existsSync(plan.createdFile),false);assert.equal(fs.readFileSync(f.def,'utf8'),f.definition);
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);f.index.scanAll();assert.equal(adapter.describeComponent(f.index.resolve(f.r.element.id)).detached,true);assert.equal(adapter.describeComponent(f.index.resolve(f.r.element.id)).canDetach,false);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.existsSync(plan.createdFile),false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(plan.createdFile,'utf8'),f.definition);
});
test('Svelte detach gives managed styles independent identities while retaining original definitions and nested imports',t=>{
 const f=fixture(t),parsed=adapter.collect(f.definition,'Badge.svelte'),heading=parsed.elements.find(e=>e.tag==='h2'),styled=adapter.planOp({appRoot:f.root,file:f.def,relPath:'Badge.svelte',source:f.definition,elements:parsed.elements,element:heading,hash:source.contentHash(f.definition)},{type:'setCSS',fileHash:source.contentHash(f.definition),property:'padding',value:'19px',width:768});assert.equal(styled.ok,true,styled.reason);f.definition=styled.edits[0].after;fs.writeFileSync(f.def,f.definition);const plan=detach(f);assert.equal(plan.ok,true,plan.reason);const css=require('../src/svelte-css.cjs'),before=css.documentState(f.definition,'Badge.svelte'),after=css.documentState(plan.edits[0].after,plan.detachedFile);assert.deepEqual(Object.values(after.model.layers),Object.values(before.model.layers));assert.notEqual(Object.keys(after.model.layers)[0],Object.keys(before.model.layers)[0]);assert.match(plan.edits[0].after,/import Leaf from "\.\/Leaf.svelte"/);assert.equal(new SourceHistory().commit(f.root,plan).ok,true);assert.equal(fs.readFileSync(f.def,'utf8'),f.definition);
});
test('Svelte detach refuses stale dependencies and existing copies without overwriting files',t=>{
 const f=fixture(t);assert.equal(detach(f,{fileHash:'stale'}).refused,true);assert.equal(detach(f,{definitionHash:'stale'}).refused,true);const plan=detach(f);fs.writeFileSync(f.def,f.definition+' ');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(fs.existsSync(plan.createdFile),false);fs.writeFileSync(f.def,f.definition);fs.writeFileSync(plan.createdFile,'Existing source');assert.equal(detach(f).refused,true);assert.equal(fs.readFileSync(plan.createdFile,'utf8'),'Existing source');assert.equal(fs.readFileSync(f.file,'utf8'),f.text);
});
test('Svelte detach undo protects modules newly referenced by another Svelte or hidden source file',t=>{
 for(const filename of ['Other.svelte','.consumer.ts']){const f=fixture(t),plan=detach(f),h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);const other=path.join(f.root,filename);fs.writeFileSync(other,'import Detached from "./'+path.basename(plan.createdFile)+'";');const refused=h.apply(f.root,'undo',saved.undoId,adapter);assert.equal(refused.ok,false);assert.match(refused.reason,/Another file/);assert.equal(fs.existsSync(plan.createdFile),true);assert.equal(fs.readFileSync(f.file,'utf8'),plan.edits[1].after);fs.unlinkSync(other);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);}
});
test('Svelte detach preserves conditional and repeated source usages and publishes unaffected-state proofs',t=>{
 for(const usage of ['{#if count}<Badge label={count}/>{/if}<Badge label="Other"/>','{#each [1,2] as value}<Badge label={value}/>{/each}<Badge label="Other"/>']){const f=fixture(t,usage),plan=detach(f);assert.equal(plan.ok,true,plan.reason);assert.equal(new SourceHistory().commit(f.root,plan).ok,true);const edge=require('../src/svelte-component-migrations.cjs').read(f.file,plan.hash)[0];assert.ok(edge.fromScript&&edge.toScript);assert.equal(edge.pairs.some(([id])=>id===f.r.element.id),false);assert.equal(edge.pairs.length,1);}
});
