'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),compiler=require('svelte/compiler'),adapter=require('../src/adapters/svelte.cjs');
function resolve(source){const elements=adapter.collect(source,'App.svelte').elements;return {source,elements,element:elements.find(e=>e.tag==='div'),file:'/app/App.svelte',relPath:'App.svelte',hash:adapter.contentHash(source)};}
test('Svelte insertion expands empty hosts and preserves populated containers and existing source identities',()=>{
 for(const source of ['<script>let count=$state(1)</script>\r\n<main>\r\n  <div/>\r\n</main>','<main><div title={value}><span>{value}</span>{#if show}<p>Conditional</p>{/if}</div><aside>Outside</aside></main>'])for(const preset of ['text','frame']){
  const r=resolve(source),result=adapter.planOp(r,{type:'insertElement',preset,fileHash:r.hash});assert.equal(result.ok,true,result.reason);const after=result.edits[0].after;compiler.compile(after,{filename:'App.svelte',generate:'client'});const next=adapter.collect(after,'App.svelte').elements;assert.equal(next.length,r.elements.length+1);for(const e of r.elements)assert.ok(next.some(n=>n.id===e.id&&n.tag===e.tag));assert.equal(next.find(e=>e.id===result.createdId).tag,preset==='text'?'p':'div');assert.equal(result.parentId,r.element.id);if(source.includes('\r\n'))assert.match(after,/<div>\r\n    /);
 }
});
test('Svelte canvas text placement validates coordinates and sizes before writing',()=>{
 const r=resolve('<main><div></div></main>');for(const position of [{x:12.125,y:-3},{x:5,y:6,width:140,height:70}]){const result=adapter.planOp(r,{type:'insertElement',preset:'text',position,fileHash:r.hash});assert.equal(result.ok,true,result.reason);compiler.compile(result.edits[0].after,{filename:'App.svelte'});assert.match(result.edits[0].after,/position:absolute/);if(position.width)assert.match(result.edits[0].after,/width:140px;height:70px/);}
 for(const op of [{preset:'unknown'},{preset:'frame',position:{x:1,y:2}},{preset:'text',position:{x:Infinity,y:0}},{preset:'text',position:{x:0,y:0,width:0,height:10}},{preset:'text',fileHash:'stale'}])assert.equal(adapter.planOp(r,{type:'insertElement',fileHash:r.hash,...op}).refused,true);
 const bound=resolve('<div contenteditable bind:innerHTML={html}></div>');assert.equal(adapter.describe(bound).structure.canInsert,false);assert.equal(adapter.planOp(bound,{type:'insertElement',preset:'text',fileHash:bound.hash}).refused,true);
});
test('Svelte text and frame insertion undo restores exact source snapshots',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-svelte-insert-')),file=path.join(root,'App.svelte'),before='<main><div/></main>';t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const preset of ['text','frame']){fs.writeFileSync(file,before);const r={...resolve(before),file},history=new(require('../src/history.cjs').SourceHistory)(),result=history.commit(root,adapter.planOp(r,{type:'insertElement',preset,fileHash:r.hash}));assert.equal(result.ok,true,result.reason);const after=fs.readFileSync(file,'utf8');assert.equal(history.apply(root,'undo',result.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),before);assert.equal(history.apply(root,'redo',result.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),after);}
});
