'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),source=require('../src/svelte-source.cjs'),base=require('../src/adapters/svelte.cjs'),components=require('../src/svelte-components.cjs'),{Index}=require('../src/indexer.cjs');
function fixture(t,text='<script>import Badge from "./Badge.svelte";</script><main><h1>Title</h1><Badge label="First" amount={2}/><Badge label="Second"/></main>'){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-components-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.writeFileSync(path.join(root,'App.svelte'),text);fs.writeFileSync(path.join(root,'Badge.svelte'),'<script>let {label,amount=1}=$props();</script><section>{label} {amount}</section>');const adapter=components.create(base),index=new Index(root,adapter);index.scanAll();return {root,adapter,index,text,ids:source.collect(text,'App.svelte').components.map(e=>e.id)};
}
test('Svelte component adapter indexes usages and describes shared definitions with literal editors',t=>{
 const {adapter,index,ids}=fixture(t);const first=index.resolve(ids[0]),second=index.resolve(ids[1]),a=adapter.describeComponent(first),b=adapter.describeComponent(second);assert.equal(a.ok,true,a.reason);assert.equal(a.definitionId,b.definitionId);assert.equal(a.props.find(p=>p.name==='amount').editor.value,2);assert.equal(adapter.describe(first).kind,'instance');const usage=require('../src/component-usage.cjs').usage(index,ids[0]);assert.equal(usage.usageCount,2);assert.equal(usage.inlineComponent,false);assert.deepEqual(usage.rootGroups,[[a.definitionId]]);
 const plan=adapter.planOp(first,{type:'setComponentProp',fileHash:first.hash,name:'label',value:'Updated'});assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/label=\{"Updated"\}/);assert.match(plan.edits[0].after,/label="Second"/);assert.equal(adapter.planOp(first,{type:'setText',fileHash:first.hash,text:'No'}).refused,true);
});
test('Svelte component indexing preserves native planner inputs and source identities',t=>{
 const {adapter,index,root,text}=fixture(t);const id=source.collect(text,'App.svelte').elements.find(e=>e.tag==='h1').id,r=index.resolve(id);assert.ok(r.elements.some(e=>e.kind==='instance'));const plan=adapter.planOp(r,{type:'setText',fileHash:r.hash,text:'Edited'});assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/>Edited<\/h1>/);assert.equal(adapter.describe(r).kind,'host');assert.deepEqual(adapter.collect(text,'App.svelte').elements.filter(e=>e.kind==='host').map(e=>e.id),base.collect(text,'App.svelte').elements.map(e=>e.id));
});
test('Svelte component resolution refuses aliases, shadow bindings and external definitions',t=>{
 for(const text of ['<script>import Badge from "$lib/Badge.svelte";</script><Badge label="X"/>','<script>import Badge from "./Badge.svelte";let items=[];</script>{#each items as Badge}<Badge label="X"/>{/each}']){const {adapter,index,ids}=fixture(t,text);assert.equal(adapter.describeComponent(index.resolve(ids[0])).refused,true);}
 const {adapter,index,root,ids}=fixture(t);fs.unlinkSync(path.join(root,'Badge.svelte'));fs.symlinkSync(__filename,path.join(root,'Badge.svelte'));assert.equal(adapter.describeComponent(index.resolve(ids[0])).refused,true);
});

test('Svelte component definitions target the shared root even when a conditional root comes first',t=>{
 const {adapter,index,root,ids}=fixture(t);fs.writeFileSync(path.join(root,'Badge.svelte'),'<script>let {label}=$props();</script>{#if label}<aside/>{:else}<footer/>{/if}<main/>');const info=adapter.describeComponent(index.resolve(ids[0]));assert.equal(info.ok,true,info.reason);const roots=source.collect(fs.readFileSync(path.join(root,'Badge.svelte'),'utf8'),'Badge.svelte').elements;assert.equal(info.definitionId,roots.find(e=>e.tag==='main').id);assert.equal(info.rootGroups.length,2);assert.ok(info.rootGroups.every(ids=>ids.includes(info.definitionId)));
});

test('Svelte component property batches stage all targets and commit one exact history step',t=>{
 const {adapter,index,ids,root,text}=fixture(t),r=index.resolve(ids[0]),op={type:'pasteComponentProps',fileHash:r.hash,targets:[{id:ids[0],properties:[{name:'label',value:'Both'},{name:'amount',value:7}]},{id:ids[1],properties:[{name:'label',value:'Both'}]}]},plan=adapter.planOp(r,op);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits.length,1);assert.equal(plan.componentPaste.changed,true);assert.equal(fs.readFileSync(r.file,'utf8'),text);const {SourceHistory}=require('../src/history.cjs'),history=new SourceHistory(),saved=history.commit(root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(r.file,'utf8'),text);assert.equal(history.apply(root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(r.file,'utf8'),plan.edits[0].after);index.indexFile(r.file);assert.deepEqual(adapter.planOp(index.resolve(ids[0]),{...op,fileHash:plan.hash}).edits,[]);
});
test('Svelte shared property edits preserve target identities and refuse the entire batch on any invalid target',t=>{
 const {adapter,index,ids,text}=fixture(t),r=index.resolve(ids[0]),op={type:'setComponentPropSelection',ids,fileHash:r.hash,name:'label',value:'Shared'},plan=adapter.planOp(r,op);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.selection.length,2);assert.deepEqual(source.collect(plan.edits[0].after,'App.svelte').components.map(e=>e.id),ids);assert.equal((plan.edits[0].after.match(/label=\{"Shared"\}/g)||[]).length,2);
 for(const bad of [{...op,fileHash:'stale'},{...op,ids:[ids[0],ids[0]]},{...op,name:'amount',value:5},{...op,value:7},{...op,reset:true},{type:'pasteComponentProps',fileHash:r.hash,targets:[{id:ids[0],properties:[{name:'label',value:'Valid'}]},{id:ids[1],properties:[{name:'missing',value:'Invalid'}]}]}]){const result=adapter.planOp(r,bad);assert.equal(result.refused,true,result.reason);assert.equal(result.edits,undefined);assert.equal(fs.readFileSync(r.file,'utf8'),text);}
});

test('Svelte literal defaults support reset, inherited overrides and exact dependency-guarded history',t=>{
 const {adapter,index,root,ids,text}=fixture(t),r=index.resolve(ids[0]),info=adapter.describeComponent(r),meta=info.props.find(p=>p.name==='amount').editor;assert.equal(meta.canReset,true);const reset=adapter.planOp(r,{type:'setComponentProp',name:'amount',reset:true,fileHash:r.hash,definitionHash:meta.definitionHash});assert.equal(reset.ok,true,reset.reason);assert.equal(reset.edits.length,2);assert.equal(source.textSnapshot(text,'App.svelte').signature,source.textSnapshot(reset.edits[0].after,'App.svelte').signature);
 const {SourceHistory}=require('../src/history.cjs'),history=new SourceHistory(),saved=history.commit(root,reset);assert.equal(saved.ok,true,saved.reason);index.indexFile(r.file);const inherited=index.resolve(ids[0]),editor=adapter.describeComponent(inherited).props.find(p=>p.name==='amount').editor;assert.equal(editor.inherited,true);assert.equal(editor.value,1);const added=adapter.planOp(inherited,{type:'setComponentProp',name:'amount',value:8,fileHash:inherited.hash,definitionHash:editor.definitionHash});assert.equal(added.ok,true,added.reason);assert.match(added.edits[0].after,/amount=\{8\}/);assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(r.file,'utf8'),text);assert.equal(history.apply(root,'redo',saved.undoId,adapter).ok,true);
 fs.writeFileSync(path.join(root,'Badge.svelte'),fs.readFileSync(path.join(root,'Badge.svelte'),'utf8').replace('amount=1','amount=9'));assert.equal(history.commit(root,added).ok,false);assert.equal(adapter.planOp(index.resolve(ids[0]),{type:'setComponentProp',name:'amount',value:7,fileHash:inherited.hash,definitionHash:editor.definitionHash}).refused,true);
});
test('Svelte defaults read aliased rune and legacy literals but not computed fallbacks',()=>{
 const read=require('../src/svelte-component-defaults.cjs').read;const rune=read('<script>let {amount:count=-2,enabled=true,label="Hi",dynamic=call(),bound=$bindable(1)}=$props();</script>');assert.deepEqual([...rune.keys()],['amount','enabled','label']);assert.equal(rune.get('amount').value,-2);const legacy=read('<script>export let amount=3,label="Legacy",enabled=false;export const fixed=7;</script>');assert.deepEqual([...legacy.keys()],['amount','label','enabled']);assert.equal(legacy.get('label').value,'Legacy');
});

test('Svelte legacy fallback reset responds only to source removal and preserves local assignments',()=>{
 const wrap=require('../src/svelte-component-defaults.cjs').legacyProp,props={'data-rt-i-revision':'one',amount:2};let value=2;const access=(...args)=>args.length?value=args[0]:value,read=wrap(access,props,'amount',1);assert.equal(read(),2);
 props.amount=undefined;value=undefined;assert.equal(read(),undefined);props['data-rt-i-revision']='two';assert.equal(read(),undefined);
 delete props.amount;props['data-rt-i-revision']='three';assert.equal(read(),1);read(8);assert.equal(read(),8);props['data-rt-i-revision']='four';assert.equal(read(),8);
 props.amount=5;value=5;props['data-rt-i-revision']='five';assert.equal(read(),5);delete props.amount;value=undefined;assert.equal(read(),undefined);props['data-rt-i-revision']='six';assert.equal(read(),undefined);
});
