'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const choices=require('../src/svelte-component-choices.cjs'),source=require('../src/svelte-source.cjs'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-choice-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const definition='<script lang="ts">type Size="small"|"large"; interface Base {label:string} interface Props extends Base {size?:Size; amount:1|2|3} let {label,size="small",amount=1}:Props=$props();</script><section>{label}|{size}|{amount}</section>',text='<script>import Badge from "./Badge.svelte";</script><main><Badge label="A" size="small" amount={1}/><Badge label="B" amount={2}/></main>',file=path.join(root,'App.svelte'),def=path.join(root,'Badge.svelte');fs.writeFileSync(file,text);fs.writeFileSync(def,definition);const index=new Index(root,adapter);index.scanAll();const ids=source.collect(text,'App.svelte').components.map(e=>e.id);return {root,file,def,text,definition,index,ids,r:index.resolve(ids[0])};}
test('Svelte contracts resolve local aliases, inherited interfaces, intersections and legacy annotations',()=>{
 const text='<script lang="ts">type Size="small"|"large";interface Base {size:Size} type Props=Base & {amount:-2|1|3;enabled:boolean;label:string};let {size,amount,enabled,label}:Props=$props();</script>',contract=choices.read(text);assert.deepEqual(contract.get('size'),{supported:true,type:'string',choices:['small','large']});assert.deepEqual(contract.get('amount'),{supported:true,type:'number',choices:[-2,1,3]});assert.deepEqual(contract.get('enabled'),{supported:true,type:'boolean'});assert.deepEqual(contract.get('missing'),{supported:false});
 const legacy=choices.read('<script lang="ts">type Size="S"|"L";export let size:Size="S";export let plain="x";</script>');assert.deepEqual(legacy.get('size').choices,['S','L']);assert.equal(legacy.get('plain'),null);
});
test('Svelte unresolved and ambiguous declared contracts never become free-form editors',()=>{
 for(const declaration of ['type Props=Imported;','type Props={size:string|number};','type Props={size:any};','type Props={size:Record<string,string>};','type A=B;type B=A;type Props={size:A};','interface Props {size:"S"} interface Props {size:"L"}','type Props={size:"S"}&{size:"L"};','type Props={[key:string]:string};'])assert.equal(choices.read('<script lang="ts">'+declaration+'let {size}:Props=$props();</script>').get('size').supported,false,declaration);
});
test('Svelte imported or generic bindings cannot inherit a same-named local contract',()=>{
 const imported=choices.read('<script module lang="ts">type Size="small"|"large";</script><script lang="ts">import type {Size} from "./types";let {size}: {size:Size}=$props();</script>');assert.equal(imported.get('size').supported,false);
 const generic=choices.read('<script module lang="ts">type T="small"|"large";</script><script lang="ts" generics="T extends string">let {size}: {size:T}=$props();</script>');assert.equal(generic.get('size').supported,false);
});
test('Svelte choice descriptors support inherited controls and dependency-guarded source edits',t=>{
 const {root,file,def,text,definition,index,ids,r}=fixture(t),info=adapter.describeComponent(r),editor=info.props.find(p=>p.name==='size').editor;assert.deepEqual(editor.choices,['small','large']);assert.equal(editor.canReset,true);const inherited=adapter.describeComponent(index.resolve(ids[1])).props.find(p=>p.name==='size').editor;assert.equal(inherited.inherited,true);assert.deepEqual(inherited.choices,editor.choices);
 const op={type:'setComponentProp',fileHash:r.hash,name:'size',value:'large',definitionHash:editor.definitionHash},plan=adapter.planOp(r,op);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits.length,2);assert.equal(source.textSnapshot(text,'App.svelte').signature,source.textSnapshot(plan.edits[0].after,'App.svelte').signature);const history=new SourceHistory(),saved=history.commit(root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),text);assert.equal(history.apply(root,'redo',saved.undoId,adapter).ok,true);assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);
 for(const bad of [{...op,value:'medium'},{...op,definitionHash:'stale'},{...op,definitionHash:undefined}])assert.equal(adapter.planOp(r,bad).refused,true);
 fs.writeFileSync(def,definition.replace('"large"','"wide"'));assert.equal(history.commit(root,plan).ok,false);assert.equal(fs.readFileSync(file,'utf8'),text);
 fs.writeFileSync(def,'<script>let {size}= $props();</script><section>{size}</section>');assert.equal(adapter.planOp(r,op).refused,true);
});
test('Svelte choice contracts constrain all batch targets and retain atomic exact history',t=>{
 const {root,index,ids,r,text,file}=fixture(t),hash=adapter.describeComponent(r).hash,op={type:'setComponentPropSelection',fileHash:r.hash,ids,name:'size',value:'large',definitionHashes:Object.fromEntries(ids.map(id=>[id,hash]))},plan=adapter.planOp(r,op);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits.length,2);assert.equal((plan.edits[0].after.match(/size=\{"large"\}/g)||[]).length,2);
 const paste={type:'pasteComponentProps',fileHash:r.hash,targets:ids.map((id,i)=>({id,properties:[{name:'size',value:i?'invalid':'large',definitionHash:hash}]}))};assert.equal(adapter.planOp(r,paste).refused,true);assert.equal(fs.readFileSync(file,'utf8'),text);
 const history=new SourceHistory(),saved=history.commit(root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),text);assert.equal(history.apply(root,'redo',saved.undoId,adapter).ok,true);
});
test('Svelte declared unsupported types and invalid defaults cannot be written or reset',t=>{
 const {def,index,ids,r}=fixture(t);fs.writeFileSync(def,'<script lang="ts">let {label,size="wrong",amount=1}:{label:any;size:"small"|"large";amount:number}=$props();</script><section>{label}</section>');const info=adapter.describeComponent(r),size=info.props.find(p=>p.name==='size').editor;assert.equal(info.props.find(p=>p.name==='label').editor.editable,false);assert.equal(size.canReset,false);assert.equal(adapter.planOp(r,{type:'setComponentProp',fileHash:r.hash,name:'size',reset:true,definitionHash:info.hash}).refused,true);assert.equal(adapter.planOp(r,{type:'setComponentProp',fileHash:r.hash,name:'label',value:'Hi',definitionHash:info.hash}).refused,true);assert.deepEqual(adapter.describeComponent(index.resolve(ids[1])).props.find(p=>p.name==='size').editor.choices,['small','large']);
});

test('Svelte absent declared properties support typed insertion, unset and exact source history',t=>{
 const {root,def,index,ids,r,text,file}=fixture(t);fs.writeFileSync(def,'<script lang="ts">let {label,caption,tone,flag,required}:{label:string;caption?:string;tone?:"quiet"|"bold";flag?:boolean;required:number}=$props();</script><section>{caption}|{tone}|{flag}|{required}</section>');
 const info=adapter.describeComponent(r),caption=info.props.find(p=>p.name==='caption').editor,required=info.props.find(p=>p.name==='required').editor;assert.equal(caption.unset,true);assert.equal(caption.allowUnset,true);assert.equal(caption.canClear,true);assert.equal(required.allowUnset,false);assert.equal(required.unset,true);assert.deepEqual(info.props.find(p=>p.name==='flag').editor.choices,[true,false]);
 const history=new SourceHistory(),op={type:'setComponentProp',fileHash:r.hash,name:'caption',value:'',definitionHash:info.hash},plan=adapter.planOp(r,op);assert.equal(plan.ok,true,plan.reason);const saved=history.commit(root,plan);assert.equal(saved.ok,true,saved.reason);index.indexFile(file);const next=index.resolve(ids[0]);assert.equal(adapter.describeComponent(next).props.find(p=>p.name==='caption').editor.unset,undefined);const clear=adapter.planOp(next,{...op,fileHash:next.hash,value:undefined,clear:true});assert.equal(clear.ok,true,clear.reason);assert.equal(clear.edits[0].after,text);assert.equal(source.textSnapshot(text,'App.svelte').signature,source.textSnapshot(plan.edits[0].after,'App.svelte').signature);
 assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),text);assert.equal(history.apply(root,'redo',saved.undoId,adapter).ok,true);assert.equal(adapter.planOp(r,{...op,value:undefined,clear:true}).edits.length,0);assert.equal(adapter.planOp(r,{...op,name:'required',clear:true}).refused,true);assert.equal(adapter.planOp(r,{...op,name:'required',value:4}).ok,true);
});
test('Svelte optional unset batches, clipboard and whole-instance reset include absent no-ops',t=>{
 const {root,def,index,ids,r,file,text}=fixture(t);fs.writeFileSync(def,'<script lang="ts">let {label,amount=1,note}:{label?:string;amount?:number;note?:string}=$props();</script><section>{label}</section>');const info=adapter.describeComponent(r),hash=info.hash,op={type:'setComponentPropSelection',fileHash:r.hash,ids,name:'label',clear:true,definitionHashes:Object.fromEntries(ids.map(id=>[id,hash]))},plan=adapter.planOp(r,op);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.edits[0].after.includes('label='),false);assert.equal(plan.edits.length,2);assert.equal(fs.readFileSync(file,'utf8'),text);
 assert.equal(adapter.planOp(r,{...op,name:'amount'}).refused,true);assert.equal(adapter.planOp(r,{...op,reset:true}).refused,true);
 const paste=adapter.planOp(r,{type:'pasteComponentProps',fileHash:r.hash,targets:ids.map(id=>({id,properties:[{name:'label',unset:true,definitionHash:hash},{name:'note',unset:true,definitionHash:hash}]}))});assert.equal(paste.ok,true,paste.reason);assert.deepEqual(paste.edits,plan.edits);
 const reset=adapter.planOp(r,{type:'resetComponentProps',fileHash:r.hash,revision:info.resetProperties.revision});assert.equal(reset.ok,true,reset.reason);assert.deepEqual(source.collect(reset.edits[0].after,'App.svelte').components[0].node.attributes.map(a=>a.name),['size']);
 const history=new SourceHistory(),saved=history.commit(root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),text);assert.equal(history.apply(root,'redo',saved.undoId,adapter).ok,true);
});
test('Svelte computed defaults, bindings and spreads never become absent literal property controls',t=>{
 const {def,index,r,ids,file,text}=fixture(t);fs.writeFileSync(def,'<script lang="ts">let {label,caption=String(3),other=$bindable("Hi")}:{label:string;caption?:string;other?:string}=$props();</script><section>{caption}</section>');const info=adapter.describeComponent(r),meta=info.props.find(p=>p.name==='caption').editor;assert.equal(meta.editable,false);assert.equal(meta.allowUnset,false);assert.equal(info.props.find(p=>p.name==='other').editor.editable,false);for(const change of [{value:'Hi'},{clear:true}])assert.equal(adapter.planOp(r,{type:'setComponentProp',fileHash:r.hash,name:'caption',definitionHash:info.hash,...change}).refused,true);
 fs.writeFileSync(file,text.replace('label="A"','label={String(1)}'));index.indexFile(file);const bound=index.resolve(ids[0]);assert.equal(adapter.planOp(bound,{type:'setComponentProp',fileHash:bound.hash,name:'label',clear:true,definitionHash:info.hash}).refused,true);
 fs.writeFileSync(file,text.replace('label="A"','{...{label:"A"}}'));index.indexFile(file);const spread=index.resolve(ids[0]);assert.equal(adapter.describeComponent(spread).props.find(p=>p.name==='caption').editor.editable,false);
});
