'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t,text='<script>let count=$state(0);let label=$state("Card");</script><main><article><h2>{label}</h2><button onclick={()=>count++}>Count {count}</button></article><footer>Footer</footer></main>'){
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-create-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte');fs.writeFileSync(file,text);const index=new Index(root,adapter);index.scanAll();const id=adapter.collect(text,'App.svelte').elements.find(e=>e.tag==='article').id;return {root,file,text,index,id,r:index.resolve(id)};
}
const create=f=>adapter.planOp(f.r,{type:'createComponent',fileHash:f.r.hash,name:'Card'});
test('Svelte creation captures reactive values and callbacks with two-file exact history',t=>{
 const f=fixture(t),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.notEqual(plan.createdComponent.instanceId,f.id);assert.match(plan.edits[1].after,/<Card label=\{label\} value2=\{\(\)=>count\+\+\} count=\{count\}\/>/);assert.match(plan.edits[0].after,/onclick=\{value2\}/);
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);f.index.scanAll();const info=adapter.describeComponent(f.index.resolve(plan.createdComponent.instanceId));assert.equal(info.ok,true,info.reason);assert.equal(info.definitionId,plan.createdComponent.definitionId);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),plan.edits[1].after);
});
test('Svelte creation moves managed responsive styles and keeps surrounding identities',t=>{
 const f=fixture(t,'<main><article><h2>Card</h2></article><footer>Footer</footer></main>'),css=require('../src/svelte-css.cjs');const styled=adapter.planOp(f.r,{type:'setCSS',fileHash:f.r.hash,width:0,changes:{color:'#ff0000'}});assert.equal(styled.ok,true,styled.reason);const h=new SourceHistory();assert.equal(h.commit(f.root,styled).ok,true);f.index.scanAll();f.r=f.index.resolve(f.id);const plan=create(f);assert.equal(plan.ok,true,plan.reason);const child=css.documentState(plan.edits[0].after,'Card.svelte'),parent=css.documentState(plan.edits[1].after,'App.svelte');assert.equal(Object.keys(child.model.layers).length,1);assert.equal(Object.keys(parent.model.layers).length,0);const footer=adapter.collect(f.r.source,'App.svelte').elements.find(e=>e.tag==='footer');assert.equal(new Map(plan.createdComponent.sourceIdMap).get(footer.id),footer.id);
});
test('Svelte creation refuses stale sources, collisions and context-dependent subtrees atomically',t=>{
 for(const text of ['<article><p>{fn()}</p></article>','<article><input type="checkbox" bind:group={value}/></article>','<article>{#if show}<p>Hi</p>{/if}</article>','<article><Other/></article>','<article>Hi</article><style>article{color:red}</style>']){const f=fixture(t,text),plan=create(f);assert.equal(plan.refused,true,text);assert.equal(fs.readFileSync(f.file,'utf8'),text);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);}
 const f=fixture(t);assert.equal(adapter.planOp(f.r,{type:'createComponent',fileHash:'stale',name:'Card'}).refused,true);for(const name of ['../Card','card','main'])assert.equal(adapter.planOp(f.r,{type:'createComponent',fileHash:f.r.hash,name}).refused,true);const plan=create(f);fs.writeFileSync(path.join(f.root,'Card.svelte'),'Do not overwrite');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);
});
test('Svelte creation does not merge distinct callback expressions',t=>{
 const f=fixture(t,'<script>let n=$state(0)</script><article><button onclick={()=>n++}>One</button><button onclick={()=>n++}>Two</button></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.createdComponent.props.length,2);assert.notEqual(plan.createdComponent.props[0].name,plan.createdComponent.props[1].name);
});
test('Svelte creation keeps form bindings connected to parent identifiers and members',t=>{
 const f=fixture(t,'<script>let value=$state("a");let state=$state({done:false});</script><article><p>{value}</p><input bind:value/><textarea bind:value={value}></textarea><select bind:value={value}><option>a</option></select><input type="checkbox" bind:checked={state.done}/></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);const child=plan.edits[0].after,parent=plan.edits[1].after;
 assert.match(child,/value = \$bindable\(\)/);assert.match(child,/bind:value=\{value\}/);assert.match(child,/value2 = \$bindable\(\)/);assert.match(parent,/<Card bind:value=\{value\} bind:value2=\{state.done\}\/>/);assert.equal(plan.createdComponent.props.length,2,'text references and form bindings share one captured identifier');
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(path.join(f.root,'Card.svelte'),'utf8'),child);
});
test('Svelte creation refuses binding expressions with side effects or group context',t=>{
 for(const field of ['<input bind:value={values[next()]}/>','<input bind:this={node}/>','<input type="checkbox" bind:group={values}/>']){const f=fixture(t,'<article>'+field+'</article>');assert.equal(create(f).refused,true);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);}
});
test('Svelte creation aliases store bindings without moving store ownership',t=>{
 const f=fixture(t,'<script>import {writable} from "svelte/store";const title=writable("Hi");</script><article><input bind:value={$title}/><p>{$title}</p></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/value1 = \$bindable\(\)/);assert.match(plan.edits[1].after,/<Card bind:value1=\{\$title\}\/>/);assert.equal(plan.createdComponent.props.length,1);
});
