'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),source=require('../src/svelte-source.cjs'),props=require('../src/svelte-component-props.cjs');
const original='<script>import Badge from "./Badge.svelte";let value=$state(1);</script><main><Badge label="First &amp; last" amount={-2} enabled callback={()=>value++}/><Badge label="Second" amount={3}/><p>{value}</p></main>';
function resolve(text=original,index=0){return {source:text,relPath:'App.svelte',file:'/tmp/App.svelte',hash:source.contentHash(text),element:source.collect(text,'App.svelte').components[index]};}
test('Svelte component usages have distinct stable identities and typed literal property descriptors',()=>{
 const r=resolve(),parsed=source.collect(original,'App.svelte'),info=props.describe(r);assert.equal(parsed.components.length,2);assert.notEqual(parsed.components[0].id,parsed.components[1].id);assert.equal(parsed.elements.length,2);assert.deepEqual(info.props.slice(0,3).map(({name,type,value,editable})=>({name,type,value,editable})),[{name:'label',type:'string',value:'First & last',editable:true},{name:'amount',type:'number',value:-2,editable:true},{name:'enabled',type:'boolean',value:true,editable:true}]);assert.equal(info.props[3].editable,false);assert.deepEqual(props.plan(r,{fileHash:r.hash,name:'label',value:'First & last'}).edits,[]);
 for(const [name,value]of [['label','<b>{literal}</b>\n"quoted"'],['amount',-0],['enabled',false]]){const result=props.plan(r,{fileHash:r.hash,name,value});assert.equal(result.ok,true,result.reason);assert.ok(result.edits[0].after.includes('<Badge label="Second" amount={3}/>'));assert.ok(result.edits[0].after.includes('callback={()=>value++}'));assert.equal(result.componentProp.parentId,parsed.elements[0].id);}
});
test('Svelte component properties refuse bindings, spreads, stale writes and invalid values',()=>{
 for(const text of [original.replace('label="First &amp; last"','label={value}'),original.replace('label="First &amp; last"','{...value} label="First"'),original.replace('label="First &amp; last"','bind:label={value}')]){const r=resolve(text);assert.equal(props.plan(r,{fileHash:r.hash,name:'label',value:'Changed'}).ok,false);}
 const r=resolve();for(const op of [{name:'callback',value:'bad'},{name:'missing',value:'bad'},{name:'amount',value:Infinity},{name:'enabled',value:'false'},{name:'label',value:'bad\0'},{name:'label',value:'ok',fileHash:'stale'}])assert.equal(props.plan(r,{fileHash:r.hash,...op}).ok,false);
});
test('Svelte literal component properties support exact source history',t=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-props-'))),file=path.join(root,'App.svelte');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.writeFileSync(file,original);const r={...resolve(),file,appRoot:root},result=props.plan(r,{fileHash:r.hash,name:'label',value:'Updated'}),{SourceHistory}=require('../src/history.cjs'),history=new SourceHistory(),saved=history.commit(root,result);assert.equal(saved.ok,true,saved.reason);assert.equal(history.apply(root,'undo',saved.undoId,require('../src/adapters/svelte.cjs')).ok,true);assert.equal(fs.readFileSync(file,'utf8'),original);assert.equal(history.apply(root,'redo',saved.undoId,require('../src/adapters/svelte.cjs')).ok,true);assert.equal(fs.readFileSync(file,'utf8'),result.edits[0].after);
});
test('Svelte component property stamps use live source values without changing the template signature',()=>{
 const r=resolve(),changed=props.plan(r,{fileHash:r.hash,name:'amount',value:7}).edits[0].after,before=source.textSnapshot(original,'App.svelte'),after=source.textSnapshot(changed,'App.svelte');assert.equal(before.signature,after.signature);assert.notDeepEqual(before.componentProps,after.componentProps);
 const only='<script>import Badge from "./Badge.svelte";</script><Badge label="Only" amount={-0}/>',stamped=source.stamp(only,'/tmp/App.svelte','/tmp',{runtime:true});require('svelte/compiler').compile(stamped.code,{filename:'App.svelte'});assert.match(stamped.code,/literalProp/);assert.match(stamped.code,/\.componentProps,/);assert.ok(Object.values(source.textSnapshot(only,'App.svelte').componentProps).includes('-0'));
 assert.notEqual(source.textSnapshot(original.replace('amount={-2}','amount={value}'),'App.svelte').signature,before.signature);
});

test('Svelte literal property additions and removals keep one template signature and live spread',()=>{
 const texts=['<Badge/>','<Badge amount={3}/>','<Badge amount={3} label="Added"/>','<Badge label="Added"/>'];const snapshots=texts.map(text=>source.textSnapshot(text,'App.svelte'));assert.equal(new Set(snapshots.map(s=>s.signature)).size,1);
 for(const text of texts){const stamped=source.stamp(text,'/tmp/App.svelte','/tmp',{runtime:true});require('svelte/compiler').compile(stamped.code,{filename:'App.svelte'});assert.match(stamped.code,/\{\.\.\.__retouch_source_.*_props\(/);}
 const dynamic='<Badge amount={value}/>';assert.notEqual(source.textSnapshot(dynamic,'App.svelte').signature,snapshots[0].signature);const spread='<Badge {...value} amount={3}/>';assert.deepEqual(source.textSnapshot(spread,'App.svelte').componentProps,{});assert.doesNotMatch(source.stamp(spread,'/tmp/App.svelte','/tmp',{runtime:true}).code,/\{\.\.\.__retouch_source_/);
});
