'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-import-types-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const text='<script>import Badge from "./Badge.svelte";</script><main><Badge tone="quiet"/><Badge/></main>',definition='<script lang="ts">import type {Props} from "./types";type Tone="Local only";let {tone="quiet",amount=-1}:Props=$props();</script><section>{tone}|{amount}</section>',file=path.join(root,'App.svelte'),def=path.join(root,'Badge.svelte'),types=path.join(root,'types.ts');fs.writeFileSync(file,text);fs.writeFileSync(def,definition);fs.writeFileSync(types,'type Tone="quiet"|"bold";interface Base{tone?:Tone}export interface Props extends Base{amount?:-1|2}');const index=new Index(root,adapter);index.scanAll();const id=adapter.collect(text,'App.svelte').elements.find(e=>e.kind==='instance').id;return {root,file,def,types,text,definition,index,r:index.resolve(id)};}
function property(f,extra={}){const info=adapter.describeComponent(f.r);assert.equal(info.ok,true,info.reason);return adapter.planOp(f.r,{type:'setComponentProp',fileHash:f.r.hash,name:'tone',value:'bold',definitionHash:info.props.find(p=>p.name==='tone').editor.definitionHash,...extra});}
test('Svelte imported contracts expose inherited finite choices and exact property/default history',t=>{const f=fixture(t),info=adapter.describeComponent(f.r);assert.deepEqual(info.props.find(p=>p.name==='tone').editor.choices,['quiet','bold']);assert.deepEqual(info.props.find(p=>p.name==='amount').editor.choices,[-1,2]);assert.equal(property(f,{value:'unknown'}).refused,true);const plan=property(f);assert.equal(plan.ok,true,plan.reason);assert.ok(plan.edits.some(e=>e.file===f.types&&e.before===e.after));const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);const defaultPlan=adapter.planOp(f.r,{type:'setComponentDefault',fileHash:f.r.hash,name:'tone',value:'bold',revision:info.props.find(p=>p.name==='tone').defaultEditor.revision});assert.equal(defaultPlan.ok,true,defaultPlan.reason);assert.ok(defaultPlan.edits.some(e=>e.file===f.types));const changed=h.commit(f.root,defaultPlan);assert.equal(changed.ok,true,changed.reason);assert.equal(h.apply(f.root,'undo',changed.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.def,'utf8'),f.definition);});
test('Svelte imported type revisions guard review, pending transactions and missing preferred files',t=>{const f=fixture(t),info=adapter.describeComponent(f.r),plan=property(f);fs.writeFileSync(f.types,'export interface Props{tone?:"quiet"|"loud";amount?:number}');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(property(f,{definitionHash:info.props[0].editor.definitionHash}).refused,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);fs.unlinkSync(f.types);fs.mkdirSync(path.join(f.root,'types'));fs.writeFileSync(path.join(f.root,'types/index.ts'),'export interface Props{tone?:"quiet"|"bold";amount?:number}');const fallback=property(f);assert.equal(fallback.ok,true,fallback.reason);fs.writeFileSync(f.types,'export interface Props{tone?:string}');assert.equal(new SourceHistory().commit(f.root,fallback).ok,false);});
test('Svelte imported contracts retain lexical modules through namespace barrels and path mappings',t=>{const f=fixture(t);fs.writeFileSync(f.def,f.definition.replace('import type {Props} from "./types"','import type * as Types from "@types/barrel"').replace(':Props=',':Types.Props='));fs.writeFileSync(path.join(f.root,'barrel.ts'),'export type {Props} from "./types";');fs.writeFileSync(path.join(f.root,'tsconfig.json'),'{"compilerOptions":{"paths":{"@types/*":["./*"]}}}');const info=adapter.describeComponent(f.r);assert.equal(info.ok,true,info.reason);assert.deepEqual(info.props[0].editor.choices,['quiet','bold']);const plan=property(f);assert.equal(plan.ok,true,plan.reason);assert.ok(plan.edits.some(e=>e.file.endsWith('/barrel.ts')));assert.ok(plan.edits.some(e=>e.file.endsWith('/tsconfig.json')));fs.appendFileSync(path.join(f.root,'tsconfig.json'),' ');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);});
test('Svelte unknown, recursive and ambiguous imported contracts stay read-only',t=>{for(const type of ['export interface Props{tone:unknown}','export type Props=Props;','export * from "./a";export * from "./b";']){const f=fixture(t);fs.writeFileSync(f.types,type);fs.writeFileSync(path.join(f.root,'a.ts'),'export interface Props{tone:string}');fs.writeFileSync(path.join(f.root,'b.ts'),'export interface Props{tone:number}');const info=adapter.describeComponent(f.r);assert.equal(info.ok,true,info.reason);assert.equal(info.props.find(p=>p.name==='tone').editor.editable,false);assert.equal(property(f).refused,true);}});
test('Svelte library insertion uses imported required contracts and guards their source',t=>{const f=fixture(t),definitions=require('../src/svelte-component-definitions.cjs');fs.writeFileSync(f.def,f.definition.replace('tone="quiet"','tone'));fs.writeFileSync(f.types,'export interface Props{tone:"quiet"|"bold";amount?:number}');const text=fs.readFileSync(f.def,'utf8'),meta=definitions.definitions(text,'Badge.svelte')[0],r=f.index.resolve(adapter.collect(f.text,'App.svelte').elements.find(e=>e.tag==='main').id),schema=definitions.schema(text,{file:f.def,appRoot:f.root});assert.equal(schema.properties.find(p=>p.name==='tone').required,true);assert.deepEqual(schema.properties.find(p=>p.name==='tone').choices,['quiet','bold']);const op={type:'insertComponent',fileHash:r.hash,definitionFile:'Badge.svelte',definitionId:meta.definitionId,definitionHash:adapter.contentHash(text),contractHash:schema.revision,props:{tone:'bold'}},plan=adapter.planOp(r,op);assert.equal(plan.ok,true,plan.reason);assert.ok(plan.edits.some(e=>e.file===f.types));fs.writeFileSync(f.types,'export interface Props{tone:"other";amount?:number}');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(adapter.planOp(r,op).refused,true);});
test('Svelte library type inspection canonicalizes project directory aliases',t=>{const f=fixture(t),definitions=require('../src/svelte-component-definitions.cjs'),alias=f.root.replace(/^\/private\//,'/'),canonical=definitions.schema(f.definition,{file:f.def,appRoot:f.root}),alternate=definitions.schema(f.definition,{file:path.join(alias,'Badge.svelte'),appRoot:alias});assert.deepEqual(alternate,canonical);});
test('Legacy Svelte export-let properties resolve imported finite types',t=>{const f=fixture(t);fs.writeFileSync(f.types,'export type Tone="quiet"|"bold";');fs.writeFileSync(f.def,'<script lang="ts">import type {Tone} from "./types";export let tone:Tone="quiet";</script><section>{tone}</section>');const info=adapter.describeComponent(f.r);assert.equal(info.ok,true,info.reason);assert.deepEqual(info.props[0].editor.choices,['quiet','bold']);assert.equal(property(f).ok,true);assert.equal(property(f,{value:'other'}).refused,true);});
test('Svelte utility contracts preserve finite choices, optionality, source guards and exact history',t=>{
 const f=fixture(t);fs.writeFileSync(f.types,'type Tone="quiet"|"bold";interface Base{tone:Tone;amount:number;internal:object}type Keys="tone"|"amount";export type Props=Readonly<Partial<Pick<Base,Keys>>>;');
 const info=adapter.describeComponent(f.r);assert.deepEqual(info.props.find(p=>p.name==='tone').editor.choices,['quiet','bold']);
 const contracts=require('../src/svelte-component-choices.cjs').read(f.definition,{file:f.def,appRoot:f.root});assert.equal(contracts.get('tone').optional,true);assert.equal(contracts.get('internal').supported,false);
 const plan=property(f);assert.equal(plan.ok,true,plan.reason);const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);
 const pending=property(f);fs.appendFileSync(f.types,'\n// changed contract');assert.equal(h.commit(f.root,pending).ok,false);
});
test('Svelte required and omitted utility contracts drive initial library fields',t=>{
 const f=fixture(t),definitions=require('../src/svelte-component-definitions.cjs');
 const text=f.definition.replace('tone="quiet"','tone').replace('amount=-1','amount');fs.writeFileSync(f.def,text);
 fs.writeFileSync(f.types,'interface Base{tone?:"quiet"|"bold";amount?:number;internal:object}interface Public extends Required<Omit<Base,"internal">>{}export type Props=Pick<Public,keyof Public>;');
 const schema=definitions.schema(text,{file:f.def,appRoot:f.root});assert.equal(schema.properties.find(p=>p.name==='tone').required,true);assert.equal(schema.properties.find(p=>p.name==='amount').required,true);assert.deepEqual(schema.properties.find(p=>p.name==='tone').choices,['quiet','bold']);assert.equal(schema.properties.some(p=>p.name==='internal'),false);
});
test('Svelte utility names resolve lexically and unsupported contracts stay read-only',t=>{
 for(const type of ['type Partial<T>={tone:number};export type Props=Partial<{tone:string}>;','interface Base{tone:string;[key:string]:unknown}export type Props=Pick<Base,"tone">;','interface Base{tone:string}export type Props=Pick<Base,"missing">;','export type Props=Partial<Props>;','interface Base{tone:string}export type Props=Omit<Base,string>;']){
  const f=fixture(t);fs.writeFileSync(f.types,type);const info=adapter.describeComponent(f.r);assert.equal(info.props.find(p=>p.name==='tone').editor.editable,false,type);assert.equal(property(f).refused,true,type);
 }
 const f=fixture(t);fs.writeFileSync(f.def,f.definition.replace('type Tone="Local only"','type Tone="Local only";type Partial<T>={tone:number}'));fs.writeFileSync(f.types,'export type Props=Partial<{tone:"quiet"|"bold"}>;');assert.deepEqual(adapter.describeComponent(f.r).props.find(p=>p.name==='tone').editor.choices,['quiet','bold'],'a private name in the component does not shadow a builtin in the imported module');
});
test('Svelte local utility contracts support ESTree arguments without project context',()=>{
 const read=require('../src/svelte-component-choices.cjs').read;const c=read('<script lang="ts">type Base={tone:"quiet"|"bold";amount:number};let {tone="quiet"}:Readonly<Partial<Pick<Base,"tone">>>=$props();</script>');assert.deepEqual(c.get('tone'),{supported:true,type:'string',choices:['quiet','bold'],optional:true});
});
