'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),compiler=require('svelte/compiler'),adapter=require('../src/adapters/svelte.cjs');
const original='<script>let count=$state(1);</script><main><section id="from"><div aria-label="Mover"><span onclick={()=>count++}>{count}</span></div><div>Neighbor</div></section><section id="to"/></main>';
function resolve(source=original){const elements=adapter.collect(source,'App.svelte').elements;return {source,relPath:'App.svelte',file:'/app/App.svelte',hash:adapter.contentHash(source),elements,element:elements.find(e=>e.attributes.some(a=>a.name==='aria-label'&&a.value==='Mover'))};}
const target=(r,id)=>r.elements.find(e=>e.attributes.some(a=>a.name==='id'&&a.value===id));
function move(r,destination,position='inside'){return adapter.planOp(r,{type:'reparentElement',fileHash:r.hash,destinationId:destination.id,position});}
test('Svelte reparent preserves bound subtree bytes, responsive styles and every original identity mapping',()=>{
 let r=resolve();const styled=adapter.planOp(r,{type:'setCSS',fileHash:r.hash,width:768,property:'padding',value:'17px'});r=resolve(styled.edits[0].after);const destination=target(r,'to');assert.ok(adapter.describe(r).structure.reparentContainers.includes(destination.id));const result=move(r,destination);assert.equal(result.ok,true,result.reason);const after=result.edits[0].after;compiler.compile(after,{filename:'App.svelte'});const next=resolve(after);assert.equal(next.elements.length,r.elements.length);assert.equal(result.movedId,next.element.id);assert.notEqual(result.movedId,r.element.id);assert.equal(adapter.describe(next).cssRules[768].padding,'17px');assert.ok(target(next,'to').node.fragment.nodes.includes(next.element.node));assert.ok(after.includes(r.source.slice(r.element.start,r.element.end)));assert.ok(result.sourceIdMap.some(([from,to])=>from===r.element.id&&to===next.element.id));
});
test('Svelte reparent handles destinations before and after the source and exact undo/redo',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-svelte-reparent-')),file=path.join(root,'App.svelte');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 for(const position of ['inside','before','after'])for(const reversed of [false,true]){let source=original.replace('<section id="to"/>','<section id="to"><div id="anchor">Anchor</div></section>');if(reversed)source=source.replace(/(<section id="from">.*?<\/section>)(<section id="to">.*?<\/section>)/,'$2$1');fs.writeFileSync(file,source);const r={...resolve(source),file},result=move(r,target(r,position==='inside'?'to':'anchor'),position);assert.equal(result.ok,true,result.reason);compiler.compile(result.edits[0].after,{filename:'App.svelte'});const history=new(require('../src/history.cjs').SourceHistory)(),saved=history.commit(root,result);assert.equal(saved.ok,true,saved.reason);const after=fs.readFileSync(file,'utf8');assert.equal(history.apply(root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),source);assert.equal(history.apply(root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),after);}
});
test('Svelte reparent preserves loop and declaration scope boundaries',()=>{
 const inside='<section><div aria-label="Mover">{item}</div></section><section id="local"/>',r=resolve('<main>{#each items as item}'+inside+'{/each}<section id="outside"/></main>');const local=move(r,target(r,'local'));assert.equal(local.ok,true,local.reason);compiler.compile(local.edits[0].after,{filename:'App.svelte'});assert.equal(move(r,target(r,'outside')).refused,true);
 const outside=resolve('<main><section><div aria-label="Mover">{value}</div></section>{#each items as value}<section id="shadow"/>{/each}</main>');assert.equal(move(outside,target(outside,'shadow')).refused,true);
 const math=resolve('<main><math><mi aria-label="Mover">x</mi><mi>y</mi></math><section id="outside"/></main>');assert.equal(move(math,target(math,'outside')).refused,true);
 const conditional=resolve('<main>{#if show}<section><div aria-label="Mover">Text</div></section>{:else}<section id="other"/>{/if}</main>');assert.equal(move(conditional,target(conditional,'other')).refused,true);
 const declared=resolve('<main><section><div aria-label="Mover">{value}</div></section><section id="declarations">{#snippet value()}<b>Local</b>{/snippet}</section></main>');compiler.compile(declared.source,{filename:'App.svelte'});assert.equal(move(declared,target(declared,'declarations')).refused,true);
});
test('Svelte reparent refuses cycles, generated content, stale revisions and unrelated files',()=>{
 const r=resolve(original.replace('<span onclick', '<span id="descendant" onclick'));assert.equal(move(r,r.element).refused,true);assert.equal(move(r,target(r,'descendant')).refused,true);
 const bound=resolve(original.replace('<section id="to"/>','<section id="to" contenteditable bind:innerHTML={html}></section>'));assert.equal(move(bound,target(bound,'to')).refused,true);
 for(const op of [{fileHash:'stale'},{destinationId:'0000000000'},{position:'invalid'}])assert.equal(adapter.planOp(r,{type:'reparentElement',fileHash:r.hash,destinationId:target(r,'to').id,...op}).refused,true);
});
