'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),adapter=require('../src/svelte-components.cjs').create(require('../src/adapters/svelte.cjs')),{Index}=require('../src/indexer.cjs'),{SourceHistory}=require('../src/history.cjs');
function fixture(t,text='<script>let count=$state(0);let label=$state("Card");</script><main><article><h2>{label}</h2><button onclick={()=>count++}>Count {count}</button></article><footer>Footer</footer></main>'){
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-create-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte');fs.writeFileSync(file,text);const index=new Index(root,adapter);index.scanAll();const id=adapter.collect(text,'App.svelte').elements.find(e=>e.tag==='article').id;return {root,file,text,index,id,r:index.resolve(id)};
}
const create=f=>adapter.planOp(f.r,{type:'createComponent',fileHash:f.r.hash,name:'Card'});
test('Svelte creation captures reactive values and callbacks with two-file exact history',t=>{
 const f=fixture(t),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.notEqual(plan.createdComponent.instanceId,f.id);assert.match(plan.edits[1].after,/<Card label=\{label\} value2=\{\(\)=>count\+\+\} count=\{count\}\/>/);assert.match(plan.edits[0].after,/onclick=\{value2\}/);
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);f.index.scanAll();const info=adapter.describeComponent(f.index.resolve(plan.createdComponent.instanceId));assert.equal(info.ok,true,info.reason);assert.equal(info.definitionId,plan.createdComponent.definitionId);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),plan.edits[1].after);
});
test('Svelte creation moves managed responsive styles and keeps surrounding identities',t=>{
 const f=fixture(t,'<main><article><h2>Card</h2></article><footer>Footer</footer></main>'),css=require('../src/svelte-css.cjs');const styled=adapter.planOp(f.r,{type:'setCSS',fileHash:f.r.hash,width:0,changes:{color:'#ff0000'}});assert.equal(styled.ok,true,styled.reason);const h=new SourceHistory();assert.equal(h.commit(f.root,styled).ok,true);f.index.scanAll();f.r=f.index.resolve(f.id);const plan=create(f);assert.equal(plan.ok,true,plan.reason);const child=css.documentState(plan.edits[0].after,'Card.svelte'),parent=css.documentState(plan.edits[1].after,'App.svelte');assert.equal(Object.keys(child.model.layers).length,1);assert.equal(Object.keys(parent.model.layers).length,0);const footer=adapter.collect(f.r.source,'App.svelte').elements.find(e=>e.tag==='footer');assert.equal(new Map(plan.createdComponent.sourceIdMap).get(footer.id),footer.id);
});
test('Svelte creation refuses stale sources, collisions and context-dependent subtrees atomically',t=>{
 for(const text of ['<article><p>{fn()}</p></article>','<article><input type="checkbox" bind:group={value}/></article>','<article>{#await promise}<p>Wait</p>{/await}</article>','<article><Other/></article>','<article>Hi</article><style>article{color:red}</style>']){const f=fixture(t,text),plan=create(f);assert.equal(plan.refused,true,text);assert.equal(fs.readFileSync(f.file,'utf8'),text);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);}
 const f=fixture(t);assert.equal(adapter.planOp(f.r,{type:'createComponent',fileHash:'stale',name:'Card'}).refused,true);for(const name of ['../Card','card','main'])assert.equal(adapter.planOp(f.r,{type:'createComponent',fileHash:f.r.hash,name}).refused,true);const plan=create(f);fs.writeFileSync(path.join(f.root,'Card.svelte'),'Do not overwrite');assert.equal(new SourceHistory().commit(f.root,plan).ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);
});
test('Svelte creation does not merge distinct callback expressions',t=>{
 const f=fixture(t,'<script>let n=$state(0)</script><article><button onclick={()=>n++}>One</button><button onclick={()=>n++}>Two</button></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.createdComponent.props.length,2);assert.notEqual(plan.createdComponent.props[0].name,plan.createdComponent.props[1].name);
});
test('Svelte creation keeps form bindings connected to parent identifiers and members',t=>{
 const f=fixture(t,'<script>let value=$state("a");let state=$state({done:false});</script><article><p>{value}</p><input bind:value/><textarea bind:value={value}></textarea><select bind:value={value}><option>a</option></select><input type="checkbox" bind:checked={state.done}/></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);const child=plan.edits[0].after,parent=plan.edits[1].after;
 assert.match(child,/value = \$bindable\(\)/);assert.match(child,/bind:value=\{value\}/);assert.match(child,/value2 = \$bindable\(\)/);assert.match(parent,/<Card bind:value=\{value\} bind:value2=\{state.done\}\/>/);assert.equal(plan.createdComponent.props.length,2,'text references and form bindings share one captured identifier');
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(path.join(f.root,'Card.svelte'),'utf8'),child);
});
test('Svelte creation refuses binding expressions with side effects or group context',t=>{
 for(const field of ['<input bind:value={values[next()]}/>','<input bind:this={node}/>','<input type="checkbox" bind:group={values}/>']){const f=fixture(t,'<article>'+field+'</article>');assert.equal(create(f).refused,true);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);}
});
test('Svelte creation aliases store bindings without moving store ownership',t=>{
 const f=fixture(t,'<script>import {writable} from "svelte/store";const title=writable("Hi");</script><article><input bind:value={$title}/><p>{$title}</p></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/value1 = \$bindable\(\)/);assert.match(plan.edits[1].after,/<Card bind:value1=\{\$title\}\/>/);assert.equal(plan.createdComponent.props.length,1);
});

test('Svelte creation retains reactive class and style directives with exact history',t=>{
 const f=fixture(t,'<script>let active=$state(true);let color=$state("red");let size=$state(12);let r=$state(20);</script><article class:active class:large={size>10} style:color|important style:font-size|important={size+"px"} style:background="rgb({r}, 0, 0)" style:display="block"><p class:active>{color}</p></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);
 const child=plan.edits[0].after,parent=plan.edits[1].after;assert.match(child,/class:active=\{active\}/);assert.match(child,/class:large=\{value2\}/);assert.match(child,/style:color\|important=\{color\}/);assert.match(child,/style:font-size\|important=\{value4\}/);assert.match(child,/style:background="rgb\(\{r\}, 0, 0\)"/);assert.match(child,/style:display="block"/);assert.match(parent,/value2=\{size>10\}/);assert.match(parent,/value4=\{size\+"px"\}/);assert.equal(plan.createdComponent.props.length,5);
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(path.join(f.root,'Card.svelte'),'utf8'),child);
});
test('Svelte creation aliases store-valued class and style directives',t=>{
 const f=fixture(t,'<script>import {writable} from "svelte/store";const active=writable(true);const color=writable("red");</script><article class:active={$active} style:color={$color}><p>{$color}</p></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/class:active=\{value1\}/);assert.match(plan.edits[0].after,/style:color=\{value2\}/);assert.equal(plan.createdComponent.props.length,2);
});
test('Svelte creation refuses evaluated side effects in class and style directives',t=>{
 for(const attr of ['class:active={toggle()}','style:color={nextColor()}','style:width="{size++}px"']){const f=fixture(t,'<article '+attr+'>Hi</article>');assert.equal(create(f).refused,true,attr);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);}
});

test('Svelte creation preserves conditional evaluation and nested branches with lazy parent props',t=>{
 const f=fixture(t,'<script>let user=$state(null);let pending=$state(false);</script><article>{#if user}<h2>{user.name}</h2>{#if user.details}<p>{user.details.title}</p>{/if}{:else if pending}<p>Waiting</p>{:else}<p>Empty</p>{/if}</article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);
 const child=plan.edits[0].after,parent=plan.edits[1].after;assert.match(child,/\{#if value1\(\)\}/);assert.match(child,/\{value2\(\)\}/);assert.match(parent,/value1=\{\(\)=>\(user\)\}/);assert.match(parent,/value2=\{\(\)=>\(user.name\)\}/);assert.match(parent,/\(\)=>\(user.details.title\)/);assert.match(child,/\{:else if value5\(\)\}/);
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(path.join(f.root,'Card.svelte'),'utf8'),child);
});
test('Svelte conditional extraction keeps bindings lazy and setters in the parent scope',t=>{
 const f=fixture(t,'<script>let user=$state(null);let nextValue=$state("Outer");</script><article>{#if user}<input bind:value={user.name}/><p>{nextValue}</p><button onclick={()=>user=null}>Clear</button>{/if}</article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/bind:value=\{value2, value3\}/);assert.match(plan.edits[1].after,/value2=\{\(\)=>\(user.name\)\}/);assert.match(plan.edits[1].after,/value3=\{nextValueValue=>\(user.name=nextValueValue\)\}/);assert.match(plan.edits[1].after,/\(\)=>\(\(\)=>user=null\)/);assert.doesNotMatch(plan.edits[0].after,/\$bindable/);
});
test('Svelte extraction separates eager and lazy references without colliding prop names',t=>{
 const f=fixture(t,'<script>let label=$state("Label");let show=$state(true);</script><article>{#if show}<p class:label style:color={label}>{label}</p>{/if}<footer>{label}</footer></article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.equal(new Set(plan.createdComponent.props.map(p=>p.name)).size,plan.createdComponent.props.length);assert.match(plan.edits[1].after,/label=\{label\}/);assert.match(plan.edits[0].after,/class:label=\{value2\(\)\}/);assert.equal(plan.createdComponent.props.length,3);
});

test('Svelte extraction retains keyed and nested loops with parameterized parent expressions',t=>{
 const f=fixture(t,'<script>let items=$state([{id:1,name:"A",children:["B"]}]);let count=$state(0);</script><article>{#each items as item, i (item.id)}<p>{i}: {item.name}</p><button onclick={()=>{item.name="Updated";count++}}>Update</button>{#each item.children as child, j}<span>{i}/{j}: {child}</span>{/each}{:else}<p>Empty {count}</p>{/each}</article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);const child=plan.edits[0].after,parent=plan.edits[1].after;assert.match(child,/\{#each value1\(\) as item, i \(value2\(item, i\)\)\}/);assert.match(parent,/\(item, i\)=>\(item.name\)/);assert.match(parent,/\(item, i, child, j\)=>\(child\)/);assert.match(parent,/\(item, i\)=>\(\(\)=>\{item.name="Updated";count\+\+\}\)/);assert.match(parent,/\(\)=>\(count\)/);
 const h=new SourceHistory(),saved=h.commit(f.root,plan);assert.equal(saved.ok,true,saved.reason);assert.equal(h.apply(f.root,'undo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(f.file,'utf8'),f.text);assert.equal(h.apply(f.root,'redo',saved.undoId,adapter).ok,true);assert.equal(fs.readFileSync(path.join(f.root,'Card.svelte'),'utf8'),child);
});
test('Svelte extraction passes loop item bindings through parent setters',t=>{
 const f=fixture(t,'<script>let items=$state([{id:1,name:"A"}]);</script><article>{#each items as item (item.id)}<input bind:value={item.name}/>{/each}</article>'),plan=create(f);assert.equal(plan.ok,true,plan.reason);assert.match(plan.edits[0].after,/bind:value=\{\(\)=>value3\(item\), nextValue=>value4\(item, nextValue\)\}/);assert.match(plan.edits[1].after,/value4=\{\(item, nextValue\)=>\(item.name=nextValue\)\}/);
});
test('Svelte loop extraction refuses replacement bindings and legacy local mutation atomically',t=>{
 for(const text of ['<article>{#each items as item}<input bind:value={item}/>{/each}</article>','<article>{#each items as item}<button onclick={()=>item=other}>Replace</button>{/each}</article>','<script>let items=[{name:"A"}];</script><article>{#each items as item}<input bind:value={item.name}/>{/each}</article>','<article>{#each items as {name}}<p>{name}</p>{/each}</article>']){const f=fixture(t,text),plan=create(f);assert.equal(plan.refused,true,text);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);assert.equal(fs.readFileSync(f.file,'utf8'),text);}
});

test('Svelte loop extraction refuses replacement through destructuring and iteration targets',t=>{
 for(const callback of ['()=>{[item]=other}','()=>{({value:item}=other)}','()=>{for(item of other){}}','()=>{for(item in other){}}']){const f=fixture(t,'<article>{#each items as item}<button onclick={'+callback+'}>Replace</button>{/each}</article>'),plan=create(f);assert.equal(plan.refused,true,callback);assert.match(plan.reason,/original collection context/);assert.equal(fs.existsSync(path.join(f.root,'Card.svelte')),false);}
});
