'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),source=require('../src/svelte-source.cjs'),migrations=require('../src/svelte-component-migrations.cjs'),{applyPlan}=require('../src/transactions.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'rt-svelte-migration-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte'),before='<script>import Tile from "./Tile.svelte";</script><main><Tile label="A"/><Tile label="B"/></main>',after=before.replace('<Tile label="A"/>','<Tile label="A"/><Tile label="A"/>'),a=source.collect(before,'App.svelte').components,b=source.collect(after,'App.svelte').components;fs.writeFileSync(file,before);return {root,file,before,after,a,b,plan:{ok:true,duplicatedComponent:{sourceIdMap:[[a[1].id,b[2].id]]},edits:[{file,before,after}]}};}
test('Committed Svelte structural edits publish exact forward and inverse survivor proofs',t=>{
 const {root,file,before,after,a,b,plan}=fixture(t);assert.deepEqual(migrations.read(file,source.contentHash(after)),[]);assert.equal(applyPlan(root,plan).ok,true);const forward=migrations.read(file,source.contentHash(after))[0];assert.deepEqual(migrations.read(file,source.contentHash(before)),[]);assert.equal(applyPlan(root,{ok:true,edits:[{file,before:after,after:before}]}).ok,true);const reverse=migrations.read(file,source.contentHash(before))[0];assert.deepEqual(forward.pairs,[[a[0].id,b[0].id],[a[1].id,b[2].id]]);assert.deepEqual(reverse.pairs,forward.pairs.map(([a,b])=>[b,a]));assert.equal(forward.from,reverse.to);assert.equal(forward.to,reverse.from);
});
test('Failed transactions and unproved external edits never publish migration edges',t=>{
 const {root,file,before,after,plan}=fixture(t);fs.writeFileSync(file,before+' ');assert.equal(applyPlan(root,plan).ok,false);assert.deepEqual(migrations.read(file,source.contentHash(after)),[]);migrations.record(root,{ok:true,edits:plan.edits});assert.deepEqual(migrations.read(file,source.contentHash(after)),[]);
});

test('External transitions invalidate cached proofs until an exact committed undo or redo',t=>{
 const {root,file,before,after,plan}=fixture(t);assert.equal(applyPlan(root,plan).ok,true);migrations.observe(file,source.contentHash(before),source.contentHash(after));assert.equal(migrations.read(file,source.contentHash(after)).length,1);migrations.observe(file,source.contentHash(after),source.contentHash(after));assert.equal(migrations.read(file,source.contentHash(after)).length,1);migrations.observe(file,source.contentHash(after),source.contentHash(before+' '));assert.deepEqual(migrations.read(file,source.contentHash(after)),[]);migrations.observe(file,source.contentHash(before+' '),source.contentHash(after));assert.deepEqual(migrations.read(file,source.contentHash(after)),[]);assert.equal(applyPlan(root,{ok:true,edits:[{file,before:after,after:before}]}).ok,true);assert.equal(migrations.read(file,source.contentHash(before)).length,1);
});
