'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),compiler=require('svelte/compiler'),adapter=require('../src/adapters/svelte.cjs'),structure=require('../src/svelte-structure.cjs');
const original='<script>let count=$state(2);</script>\r\n<main>\n <div data-rt-name="First"><span onclick={()=>count++}>{count}</span></div>\n <div data-rt-name="Second">Two</div>\n <div data-rt-name="Third">Three</div>\n</main><style>div{padding:4px}</style>';
function resolve(source=original,name='First'){const elements=adapter.collect(source,'App.svelte').elements;return {source,relPath:'App.svelte',file:'/app/App.svelte',hash:adapter.contentHash(source),elements,element:elements.find(e=>e.attributes.some(a=>a.name==='data-rt-name'&&a.value===name))};}
function plan(r,op){const result=structure.plan(r,{fileHash:r.hash,...op},adapter);assert.equal(result.ok,true,result.reason);compiler.compile(result.edits[0].after,{filename:'App.svelte',generate:'client'});return result;}
test('Svelte sibling reorder preserves source bytes, bindings, responsive ownership and descendant identity mapping',()=>{
 let r=resolve(),styled=adapter.planOp(r,{type:'setCSS',fileHash:r.hash,width:768,property:'padding',value:'16px'});r=resolve(styled.edits[0].after);const result=plan(r,{type:'moveElement',direction:'last'}),after=result.edits[0].after,next=resolve(after),fragment=r.source.slice(r.element.start,r.element.end);
 assert.equal(after,r.source.replace(fragment+'\n <div data-rt-name="Second">Two</div>\n <div data-rt-name="Third">Three</div>','<div data-rt-name="Second">Two</div>\n <div data-rt-name="Third">Three</div>\n '+fragment));assert.equal(result.movedId,next.element.id);assert.equal(adapter.describe(next).cssRules[768].padding,'16px');assert.ok(result.sourceIdMap.some(([from,to])=>from===r.elements.find(e=>e.tag==='span').id&&to===next.elements.find(e=>e.tag==='span').id));
});
test('Svelte duplicate and paste allocate independent nested style owners; delete prunes only removed styles',()=>{
 let r=resolve();for(const tag of ['div','span']){const element=r.elements.find(e=>e.tag===tag),styled=adapter.planOp({...r,element},{type:'setCSS',fileHash:r.hash,width:768,property:'font-size',value:tag==='div'?'21px':'17px'});r=resolve(styled.edits[0].after);}
 const duplicated=plan(r,{type:'duplicateElement'}),next=resolve(duplicated.edits[0].after),runs=next.elements.filter(e=>e.tag==='span');assert.equal(runs.length,2);const ids=runs.map(e=>e.attributes.find(a=>a.name==='data-rt-style').value);assert.notEqual(ids[0],ids[1]);for(const element of runs)assert.equal(adapter.describe({...next,element}).cssRules[768]['font-size'],'17px');
 const selected={...next,element:next.elements.find(e=>e.id===duplicated.createdId)},deleted=plan(selected,{type:'deleteElement'}),clean=resolve(deleted.edits[0].after);assert.equal(clean.elements.filter(e=>e.tag==='span').length,1);assert.ok(!Object.hasOwn(require('../src/svelte-css.cjs').documentState(clean.source,clean.relPath).model.layers,ids[1]));assert.ok(deleted.removedSourceIds.includes(runs[1].id));
 const target=resolve(r.source,'Third'),pasted=plan(target,{type:'pasteElement',copiedId:r.element.id,copiedHash:r.hash});assert.equal(resolve(pasted.edits[0].after).elements.filter(e=>e.tag==='span').length,2);
 assert.equal(structure.plan(target,{type:'pasteElement',fileHash:target.hash,copiedId:r.element.id,copiedHash:'stale'},adapter).refused,true);
});
test('Svelte structural edits round-trip exact snapshots and preserve scripts and authored styles',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-svelte-structure-')),file=path.join(root,'App.svelte');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 for(const op of [{type:'duplicateElement'},{type:'deleteElement'},...['before','after','first','last'].map(direction=>({type:'moveElement',direction}))]){fs.writeFileSync(file,original);const r={...resolve(original,'Second'),file},history=new(require('../src/history.cjs').SourceHistory)(),result=history.commit(root,plan(r,op));assert.equal(result.ok,true,result.reason);const after=fs.readFileSync(file,'utf8');assert.match(after,/<script>let count=\$state\(2\);<\/script>\r\n/);assert.match(after,/<style>div\{padding:4px\}<\/style>/);assert.equal(history.apply(root,'undo',result.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),original);assert.equal(history.apply(root,'redo',result.undoId,adapter).ok,true);assert.equal(fs.readFileSync(file,'utf8'),after);}
});
test('Svelte structure refuses ambiguous sibling boundaries, copied identities and stale source',()=>{
 for(const sibling of ['{#if ready}<div>Conditional</div>{/if}','<Widget/>','{value}','mixed text','<!-- attached -->','<div {...props}/>','<svg/>']){const r=resolve('<main><div data-rt-name="First">One</div>'+sibling+'</main>');assert.equal(structure.describe(r,adapter).canMoveAfter,false,sibling);assert.equal(structure.plan(r,{type:'moveElement',direction:'after',fileHash:r.hash},adapter).refused,true,sibling);}
 for(const attrs of ['id="unique"','bind:this={reference}','{...props}','data-rt-style={identity}']){const r=resolve('<main><div data-rt-name="First"><span '+attrs+'>Text</span></div></main>');assert.equal(structure.describe(r,adapter).canDuplicate,false,attrs);assert.equal(structure.plan(r,{type:'duplicateElement',fileHash:r.hash},adapter).refused,true,attrs);}
 assert.equal(structure.plan(resolve(),{type:'deleteElement',fileHash:'stale'},adapter).refused,true);
});
