'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),group=require('../src/svg-boolean-group.cjs'),ids=require('../src/id.cjs');
const markup='<main><svg><rect width="100" height="80" fill="red" transform="translate(3 4)"/>\n<!--keep--><circle cx="50" cy="40" r="30"/><ellipse rx="2" ry="3"/></svg><p>After</p></main>',path='M0 0H100V80H0Z';
const tag=(kind,e)=>kind==='react'?ids.jsxElementName(e.node):e.tag;
function resolve(kind,source,id){const adapter=require('../src/adapters/'+kind+'.cjs'),relPath='art.'+(kind==='react'?'jsx':kind==='liquid'?'liquid':'html');if(source===undefined)source=kind==='react'?'export default function Art(){return '+markup.replace('<!--keep-->','{/*keep*/}')+'}':kind==='liquid'?markup.replace('<!--keep-->',''):markup;const elements=adapter.collect(source,relPath).elements;return {source,elements,element:id?elements.find(e=>e.id===id):elements.find(e=>tag(kind,e)==='rect'),hash:adapter.contentHash(source),file:'/tmp/'+relPath,relPath};}
function create(kind,r,extra={}){return group.plan(r,{type:'createSVGBooleanGroup',fileHash:r.hash,ids:['rect','circle'].map(t=>r.elements.find(e=>tag(kind,e)===t).id),path,operation:'union',...extra},kind);}
for(const kind of ['html','react','liquid']){
 test(kind+' boolean groups retain every original layer, base selection and exact release bytes',()=>{
  const r=resolve(kind),made=create(kind,r);assert.equal(made.ok,true,made.reason);assert.deepEqual(made.removedSourceIds,[]);
  const after=made.edits[0].after,fresh=resolve(kind,after,made.selectionIds[0]),info=group.describe(fresh,kind);assert.equal(info.operation,'union');assert.equal(info.operandIds.length,2);
  const mapping=new Map(made.sourceIdMap);for(const e of r.elements){const preserved=fresh.elements.find(n=>n.id===(mapping.get(e.id)||e.id));assert.ok(preserved);assert.equal(tag(kind,preserved),tag(kind,e));}assert.equal(info.baseId,mapping.get(r.element.id)||r.element.id);
  assert.ok(after.includes('display="none"'));assert.ok(after.includes('data-rt-boolean-result=""'));assert.ok(after.includes('transform="translate(3 4)"'));
  const released=group.plan(fresh,{type:'releaseSVGBooleanGroup',fileHash:fresh.hash},kind);assert.equal(released.ok,true,released.reason);assert.equal(released.edits[0].after,r.source);assert.equal(released.selectionIds.length,2);assert.equal(released.removedSourceIds.length,3);
 });
 test(kind+' changing boolean operation preserves operands and supports empty then nonempty results',()=>{
  const r=resolve(kind),made=create(kind,r,{path:''}),fresh=resolve(kind,made.edits?.[0].after,made.selectionIds?.[0]);assert.equal(made.ok,true,made.reason);assert.ok(fresh.source.includes('d=""'));const originalOperands=group.context(fresh,kind);const before=fresh.source.slice(originalOperands.opening(originalOperands.operands),originalOperands.closing(originalOperands.operands));
  for(const operation of ['subtract','intersect','exclude','union']){const changed=group.plan(fresh,{type:'setSVGBooleanOperation',fileHash:fresh.hash,operation,path},kind);assert.equal(changed.ok,true,changed.reason);const next=resolve(kind,changed.edits[0].after,made.selectionIds[0]),c=group.context(next,kind);assert.equal(c.operation,operation);assert.equal(next.source.slice(c.opening(c.operands),c.closing(c.operands)),before);assert.equal(group.plan(next,{type:'releaseSVGBooleanGroup',fileHash:next.hash},kind).edits[0].after,r.source);}
 });
 test(kind+' reversed selection remembers the first selected base without reordering source',()=>{
  const r=resolve(kind),selection=['circle','rect'].map(t=>r.elements.find(e=>tag(kind,e)===t).id),made=create(kind,r,{ids:selection});assert.equal(made.ok,true,made.reason);const fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]),info=group.describe(fresh,kind);assert.equal(tag(kind,fresh.elements.find(e=>e.id===info.baseId)),'circle');assert.equal(group.plan(fresh,{type:'releaseSVGBooleanGroup',fileHash:fresh.hash},kind).edits[0].after,r.source);
 });
 test(kind+' group operations reject stale, nonconsecutive, invalid and altered wrappers without edits',()=>{
  const r=resolve(kind);for(const changes of [{fileHash:'old'},{operation:'bad'},{path:'M0 0L1 1'},{ids:[r.element.id,r.elements.find(e=>tag(kind,e)==='ellipse').id]}])assert.equal(create(kind,r,changes).refused,true);
  const made=create(kind,r);for(const replacement of ['data-rt-boolean="union" transform="translate(invalid)"','data-rt-boolean="union" class="custom"']){const fresh=resolve(kind,made.edits[0].after.replace('data-rt-boolean="union"',replacement),made.selectionIds[0]);assert.equal(group.plan(fresh,{type:'releaseSVGBooleanGroup',fileHash:fresh.hash},kind).refused,true);}
  const identified=resolve(kind,r.source.replace('<rect ','<rect id="authored" '));assert.equal(create(kind,identified).refused,true);
 });
}
for(const kind of ['html','react','liquid'])test(kind+' operand geometry and derived result update atomically and release retains the edit',()=>{
 const r=resolve(kind),made=create(kind,r),fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]),info=group.describe(fresh,kind);
 const changed=group.plan(fresh,{type:'setSVGBooleanOperand',fileHash:fresh.hash,operandId:info.baseId,operandOp:{type:'setSVGGeometry',property:'width',value:'120'},path:'M0 0H120V80H0Z'},kind);
 assert.equal(changed.ok,true,changed.reason);assert.equal(changed.edits.length,1);assert.equal(changed.edits[0].before,fresh.source);assert.ok(changed.edits[0].after.includes('width="120"'));assert.ok(changed.edits[0].after.includes('120'));
 const edited=resolve(kind,changed.edits[0].after,made.selectionIds[0]),released=group.plan(edited,{type:'releaseSVGBooleanGroup',fileHash:edited.hash},kind);assert.equal(released.ok,true,released.reason);assert.equal(released.edits[0].after,r.source.replace('width="100"','width="120"'));
 for(const extra of [{path:'M0 0L1 1'},{operandId:'missing'},{operandOp:{type:'deleteElement'}},{operandOp:{type:'setSVGGeometry',property:'width',value:'invalid'}}])assert.equal(group.plan(fresh,{type:'setSVGBooleanOperand',fileHash:fresh.hash,operandId:info.baseId,operandOp:{type:'setSVGGeometry',property:'width',value:'120'},path,...extra},kind).refused,true);
});
for(const kind of ['html','react','liquid'])test(kind+' adapter routes boolean transactions and blocks stale direct operand/result edits',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=adapter.planOp(r,{type:'createSVGBooleanGroup',fileHash:r.hash,ids:['rect','circle'].map(t=>r.elements.find(e=>tag(kind,e)===t).id),path,operation:'union'});assert.equal(made.ok,true,made.reason);
 const fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]),info=adapter.describe(fresh);assert.equal(info.svgBooleanGroup.operation,'union');assert.equal(info.svgBooleanOwner,fresh.element.id);
 for(const id of [...info.svgBooleanGroup.operandIds,info.svgBooleanGroup.resultId]){const child=resolve(kind,fresh.source,id);assert.equal(adapter.describe(child).svgBooleanOwner,fresh.element.id);assert.equal(adapter.planOp(child,{type:'setSVGGeometry',fileHash:child.hash,property:'d',value:path}).refused,true);assert.equal(adapter.planOp(child,{type:'deleteElement',fileHash:child.hash}).refused,true);}
 const changed=adapter.planOp(fresh,{type:'setSVGBooleanOperand',fileHash:fresh.hash,operandId:info.svgBooleanGroup.baseId,operandOp:{type:'setSVGGeometry',property:'width',value:'120'},path});assert.equal(changed.ok,true,changed.reason);assert.equal(changed.edits.length,1);
 const released=adapter.planOp(fresh,{type:'releaseSVGBooleanGroup',fileHash:fresh.hash});assert.equal(released.edits[0].after,r.source);
});
for(const kind of ['html','react','liquid'])test(kind+' changing the base transform also updates the derived path coordinate space',()=>{
 const r=resolve(kind),made=create(kind,r),fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]),info=group.describe(fresh,kind),matrix=[1,0,0,1,20,30];
 const result=group.plan(fresh,{type:'setSVGBooleanOperand',fileHash:fresh.hash,operandId:info.baseId,operandOp:{type:'setSVGTransform',matrix},path},kind);assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,1);
 const next=resolve(kind,result.edits[0].after,made.selectionIds[0]),c=group.context(next,kind);assert.equal(c.attr(c.roots[c.base],'transform'),'matrix(1 0 0 1 20 30)');assert.equal(c.attr(c.result,'transform'),'matrix(1 0 0 1 20 30)');
 const released=group.plan(next,{type:'releaseSVGBooleanGroup',fileHash:next.hash},kind);assert.equal(released.edits[0].after,r.source.replace('translate(3 4)','matrix(1 0 0 1 20 30)'));
});
for(const kind of ['html','react','liquid'])test(kind+' transformed boolean groups release into an ordinary group without losing transforms or originals',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r),fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]);
 const transformed=adapter.planOp(fresh,{type:'setSVGTransform',fileHash:fresh.hash,matrix:[2,0,0,1.5,20,30]});assert.equal(transformed.ok,true,transformed.reason);const moved=resolve(kind,transformed.edits[0].after,made.selectionIds[0]);assert.equal(adapter.describe(moved).svgBooleanGroup.operation,'union');
 const changed=adapter.planOp(moved,{type:'setSVGBooleanOperation',fileHash:moved.hash,operation:'subtract',path});assert.equal(changed.ok,true,changed.reason);
 const edited=resolve(kind,changed.edits[0].after,made.selectionIds[0]),released=adapter.planOp(edited,{type:'releaseSVGBooleanGroup',fileHash:edited.hash});assert.equal(released.ok,true,released.reason);assert.equal(released.selectionIds.length,1);const final=resolve(kind,released.edits[0].after,released.selectionIds[0]);assert.equal(tag(kind,final.element),'g');assert.ok(final.source.includes('transform="matrix(2 0 0 1.5 20 30)"'));assert.ok(final.source.includes('transform="translate(3 4)"'));assert.ok(!final.source.includes('data-rt-boolean'));assert.equal(released.removedSourceIds.length,2);
 const mapping=new Map(released.sourceIdMap),removed=new Set(released.removedSourceIds);for(const old of edited.elements.filter(e=>!removed.has(e.id))){const retained=final.elements.find(e=>e.id===(mapping.get(old.id)||old.id));assert.ok(retained);assert.equal(tag(kind,retained),tag(kind,old));}
});
for(const kind of ['html','react','liquid'])test(kind+' batch transforms preserve boolean originals and reject protected members atomically',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),first=create(kind,r),one=resolve(kind,first.edits[0].after,first.selectionIds[0]);
 const duplicated=one.source.replace('</svg>',one.source.slice(group.context(one,kind).start(one.element),group.context(one,kind).end(one.element))+'</svg>');
 const all=resolve(kind,duplicated),groups=all.elements.filter(e=>group.describe({...all,element:e},kind)),primary={...all,element:groups[0]},selection=groups.map(e=>e.id);assert.equal(selection.length,2);
 const matrices=Object.fromEntries(selection.map((id,i)=>[id,[1,0,0,1,20+i*30,10]])),op={type:'setSVGTransforms',fileHash:primary.hash,ids:selection,matrices};
 const moved=adapter.planOp(primary,op);assert.equal(moved.ok,true,moved.reason);assert.equal(moved.edits.length,1);assert.equal(moved.edits[0].before,duplicated);
 for(const id of selection){const before=group.context({...all,element:all.elements.find(e=>e.id===id)},kind),after=group.context(resolve(kind,moved.edits[0].after,id),kind);assert.equal(after.attr(after.group,'transform'),'matrix('+matrices[id].join(' ')+')');assert.equal(moved.edits[0].after.slice(after.opening(after.group),after.closing(after.group)),duplicated.slice(before.opening(before.group),before.closing(before.group)));}
 const info=group.describe(primary,kind);for(const protectedId of [...info.operandIds,info.resultId]){const ids=[selection[1],protectedId],bad={type:'setSVGTransforms',fileHash:primary.hash,ids,matrices:Object.fromEntries(ids.map(id=>[id,[1,0,0,1,5,5]]))},result=adapter.planOp({...primary,element:groups[1]},bad);assert.equal(result.refused,true);assert.equal(result.edits,undefined);}
 const stale=adapter.planOp(primary,{...op,fileHash:'stale'});assert.equal(stale.refused,true);assert.equal(stale.edits,undefined);

});
for(const kind of ['html','react','liquid'])test(kind+' combined paints retain original appearance and survive operation changes',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r);let fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]);
 for(const [property,value]of [['fill','#12abcd'],['stroke','navy'],['stroke-width','3.5']]){const before=fresh.source,changed=adapter.planOp(fresh,{type:'setSVGBooleanPaint',fileHash:fresh.hash,property,value});assert.equal(changed.ok,true,changed.reason);assert.equal(changed.edits.length,1);assert.equal(changed.edits[0].before,before);fresh=resolve(kind,changed.edits[0].after,made.selectionIds[0]);assert.equal(group.describe(fresh,kind).paints[property],value);const c=group.context(fresh,kind);assert.equal(c.attr(c.roots[c.base],'fill'),'red');assert.equal(c.attr(c.roots[c.base],'stroke'),undefined);}
 const edited=adapter.planOp(fresh,{type:'setSVGBooleanOperation',fileHash:fresh.hash,operation:'subtract',path});assert.equal(edited.ok,true,edited.reason);fresh=resolve(kind,edited.edits[0].after,made.selectionIds[0]);for(const [key,value]of Object.entries({fill:'#12abcd',stroke:'navy','stroke-width':'3.5'}))assert.equal(group.describe(fresh,kind).paints[key],value);
 assert.equal(adapter.planOp(fresh,{type:'releaseSVGBooleanGroup',fileHash:fresh.hash}).edits[0].after,r.source);
 for(const extra of [{property:'d',value:path},{property:'constructor',value:null},{property:'fill',value:'red" onload="x'},{property:'stroke-width',value:'-1'},{property:'fill',value:'url(https://example.com)'},{property:'fill',value:'red',fileHash:'stale'}]){const result=adapter.planOp(fresh,{type:'setSVGBooleanPaint',fileHash:fresh.hash,...extra});assert.equal(result.refused,true);assert.equal(result.edits,undefined);}
 const removed=adapter.planOp(fresh,{type:'setSVGBooleanPaint',fileHash:fresh.hash,property:'stroke',value:null});assert.equal(removed.ok,true,removed.reason);assert.equal(group.describe(resolve(kind,removed.edits[0].after,made.selectionIds[0]),kind).paints.stroke,null);
});

test('React combined stroke width preserves an existing JSX spelling and refuses conflicting aliases',()=>{
 const r=resolve('react'),made=create('react',r),source=made.edits[0].after.replace('data-rt-boolean-result=""','data-rt-boolean-result="" stroke-width="2"'),fresh=resolve('react',source,made.selectionIds[0]);assert.equal(group.describe(fresh,'react').paints['stroke-width'],'2');
 const changed=group.plan(fresh,{type:'setSVGBooleanPaint',fileHash:fresh.hash,property:'stroke-width',value:'4'},'react');assert.equal(changed.ok,true,changed.reason);assert.ok(changed.edits[0].after.includes('stroke-width="4"'));assert.ok(!changed.edits[0].after.includes('strokeWidth='));
 const conflict=resolve('react',source.replace('stroke-width="2"','stroke-width="2" strokeWidth="3"'),made.selectionIds[0]),refused=group.plan(conflict,{type:'setSVGBooleanPaint',fileHash:conflict.hash,property:'stroke-width',value:'4'},'react');assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);
});
for(const kind of ['html','react','liquid'])test(kind+' combined stroke details preserve operands and source identity',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r);let fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]);const expectedIds=fresh.elements.map(e=>e.id);
 for(const [property,value]of [['stroke-linecap','round'],['stroke-linejoin','bevel'],['stroke-dasharray','8 4 2 4'],['stroke-dashoffset','-2'],['stroke-miterlimit','6'],['vector-effect','non-scaling-stroke']]){
  const changed=adapter.planOp(fresh,{type:'setSVGBooleanPaint',fileHash:fresh.hash,property,value});assert.equal(changed.ok,true,changed.reason);fresh=resolve(kind,changed.edits[0].after,made.selectionIds[0]);assert.equal(group.describe(fresh,kind).paints[property],value);assert.deepEqual(fresh.elements.map(e=>e.id),expectedIds);
  const c=group.context(fresh,kind);assert.ok(c.roots.every(e=>c.attrs(e).every(a=>!a.name.startsWith('stroke')&&!a.name.startsWith('vector'))));
 }
 assert.equal(adapter.planOp(fresh,{type:'releaseSVGBooleanGroup',fileHash:fresh.hash}).edits[0].after,r.source);
 for(const [property,value]of [['stroke-linecap','triangle'],['stroke-linejoin','unknown'],['stroke-dasharray','-2 4'],['stroke-miterlimit','0'],['vector-effect','fixed']]){const rejected=adapter.planOp(fresh,{type:'setSVGBooleanPaint',fileHash:fresh.hash,property,value});assert.equal(rejected.refused,true);assert.equal(rejected.edits,undefined);}
});

for(const kind of ['html','react','liquid'])test(kind+' nested boolean creation retains the complete operand tree and releases exactly',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),first=create(kind,r);let inner=resolve(kind,first.edits[0].after,first.selectionIds[0]);
 const moved=adapter.planOp(inner,{type:'setSVGTransform',fileHash:inner.hash,matrix:[2,0,0,2,10,20]});assert.equal(moved.ok,true,moved.reason);inner=resolve(kind,moved.edits[0].after,inner.element.id);
 const ellipse=inner.elements.find(e=>tag(kind,e)==='ellipse'),made=group.plan(inner,{type:'createSVGBooleanGroup',fileHash:inner.hash,ids:[inner.element.id,ellipse.id],operation:'subtract',path},kind);
 assert.equal(made.ok,true,made.reason);assert.deepEqual(made.removedSourceIds,[]);const next=resolve(kind,made.edits[0].after,made.selectionIds[0]),outer=group.context(next,kind),mapping=new Map(made.sourceIdMap);
 for(const old of inner.elements){const fresh=next.elements.find(e=>e.id===(mapping.get(old.id)||old.id));assert.ok(fresh,old.id);assert.equal(tag(kind,fresh),tag(kind,old));}
 const retained=outer.roots[0],nested=group.context({...next,element:retained},kind);assert.ok(nested);assert.equal(next.source.slice(outer.start(retained),outer.end(retained)),inner.source.slice(group.context(inner,kind).start(inner.element),group.context(inner,kind).end(inner.element)));
 assert.equal(outer.attr(outer.result,'transform'),'matrix(2 0 0 2 16 28)','result composes group transform with the base result transform');assert.equal(outer.attr(outer.result,'fill'),'red');
 const changed=group.plan(next,{type:'setSVGBooleanOperation',fileHash:next.hash,operation:'exclude',path:'M0 0H20V20H0Z'},kind);assert.equal(changed.ok,true,changed.reason);const changedResolved=resolve(kind,changed.edits[0].after,next.element.id);assert.equal(group.context(changedResolved,kind).attr(group.context(changedResolved,kind).roots[0],'data-rt-boolean'),'union');
 const released=group.plan(changedResolved,{type:'releaseSVGBooleanGroup',fileHash:changedResolved.hash},kind);assert.equal(released.ok,true,released.reason);assert.equal(released.edits[0].after,inner.source);assert.equal(released.removedSourceIds.length,3,'release removes only the outer wrappers and result');
 for(const op of [{type:'setSVGBooleanOperation',operation:'intersect',path},{type:'releaseSVGBooleanGroup'},{type:'setSVGTransform',matrix:[1,0,0,1,1,1]},{type:'deleteElement'}]){
  const rejected=adapter.planOp({...next,element:retained},{...op,fileHash:next.hash});assert.equal(rejected.refused,true,JSON.stringify(op));assert.equal(rejected.edits,undefined);
 }
});
for(const kind of ['html','react','liquid'])test(kind+' nested operands preserve first-selected appearance and reject dynamic descendant attributes',()=>{
 const r=resolve(kind),first=create(kind,r),inner=resolve(kind,first.edits[0].after,first.selectionIds[0]),ellipse=inner.elements.find(e=>tag(kind,e)==='ellipse');
 const made=group.plan({...inner,element:ellipse},{type:'createSVGBooleanGroup',fileHash:inner.hash,ids:[ellipse.id,inner.element.id],operation:'union',path:''},kind);assert.equal(made.ok,true,made.reason);const fresh=resolve(kind,made.edits[0].after,made.selectionIds[0]),c=group.context(fresh,kind);assert.equal(c.base,1);assert.equal(c.attr(c.result,'d'),'');assert.equal(group.plan(fresh,{type:'releaseSVGBooleanGroup',fileHash:fresh.hash},kind).edits[0].after,inner.source);
 const altered=resolve(kind,inner.source.replace('fill="red"',kind==='react'?'fill={paint}':'fill="red" id="authored"'),inner.element.id),other=altered.elements.find(e=>tag(kind,e)==='ellipse');const refused=group.plan(altered,{type:'createSVGBooleanGroup',fileHash:altered.hash,ids:[altered.element.id,other.id],operation:'union',path},kind);assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);
});
for(const kind of ['html','react','liquid'])test(kind+' nested geometry cascades every containing result in one unchanged-identity transaction',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),base=resolve(kind),r=resolve(kind,base.source.replace('</svg>','<polygon points="0,0 10,0 0,10"/></svg>')),first=create(kind,r);let current=resolve(kind,first.edits[0].after,first.selectionIds[0]);
 for(const shape of ['ellipse','polygon']){const next=group.plan(current,{type:'createSVGBooleanGroup',fileHash:current.hash,ids:[current.element.id,current.elements.find(e=>tag(kind,e)===shape).id],operation:'union',path},kind);assert.equal(next.ok,true,next.reason);current=resolve(kind,next.edits[0].after,next.selectionIds[0]);}
 const outer=group.context(current,kind),middle=group.context({...current,element:outer.roots[0]},kind),inner=group.context({...current,element:middle.roots[0]},kind),operand=inner.roots[inner.base];
 const request={type:'setSVGBooleanNested',fileHash:current.hash,targetId:inner.group.id,edit:{type:'setSVGBooleanOperand',operandId:operand.id,operandOp:{type:'setSVGTransform',matrix:[1,0,0,1,10,20]},path:'M0 0H20V30H0Z'},results:[{id:middle.group.id,path:'M0 0H40V50H0Z'},{id:outer.group.id,path:'M0 0H60V70H0Z'}]};
 const result=adapter.planOp(current,request);assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,1);assert.equal(result.edits[0].before,current.source);assert.deepEqual(result.sourceIdMap,[]);assert.deepEqual(result.removedSourceIds,[]);
 const fresh=resolve(kind,result.edits[0].after,current.element.id);assert.deepEqual(fresh.elements.map(e=>e.id),current.elements.map(e=>e.id));
 for(const [old,expected]of [[inner,'M 0 0 L 20 0 L 20 30 L 0 30 Z'],[middle,'M 0 0 L 40 0 L 40 50 L 0 50 Z'],[outer,'M 0 0 L 60 0 L 60 70 L 0 70 Z']]){const c=group.context({...fresh,element:fresh.elements.find(e=>e.id===old.group.id)},kind);assert.equal(c.attr(c.result,'d'),expected);assert.deepEqual(require('../shell/svg-affine.js').parse(c.attr(c.result,'transform')),[1,0,0,1,10,20]);}
 const releaseRequest={...request,edit:{type:'releaseSVGBooleanGroup'}},released=adapter.planOp(current,releaseRequest);assert.equal(released.ok,true,released.reason);assert.equal(released.edits.length,1);const releaseMap=new Map(released.sourceIdMap),afterRelease=resolve(kind,released.edits[0].after,releaseMap.get(outer.group.id)||outer.group.id);assert.ok(group.context(afterRelease,kind));for(const old of [middle,outer]){const c=group.context({...afterRelease,element:afterRelease.elements.find(e=>e.id===(releaseMap.get(old.group.id)||old.group.id))},kind);assert.ok(c);assert.equal(c.attr(c.result,'d'),require('../shell/svg-path.js').serializeCompound(require('../shell/svg-path.js').parseCompound(releaseRequest.results.find(item=>item.id===old.group.id).path)));}const failedRelease=adapter.planOp(current,{...releaseRequest,results:[request.results[0],{...request.results[1],path:'invalid'}]});assert.equal(failedRelease.refused,true);assert.equal(failedRelease.edits,undefined);
 const unchanged=adapter.planOp(fresh,{...request,fileHash:fresh.hash});assert.equal(unchanged.ok,true,unchanged.reason);assert.equal(unchanged.unchanged,true);
 for(const extra of [{results:request.results.slice(0,1)},{results:[...request.results].reverse()},{results:[request.results[0],{...request.results[1],path:'M0 0L1 1'}]},{fileHash:'stale'}]){const rejected=adapter.planOp(current,{...request,...extra});assert.equal(rejected.refused,true,JSON.stringify(extra));assert.equal(rejected.edits,undefined);}
});

for(const kind of ['html','react','liquid'])for(const transformed of [false,true])for(const reverse of [false,true])for(const outerBase of [false,true])test(kind+' nested release preserves base and originals transformed='+transformed+' reverse='+reverse+' outerBase='+outerBase,()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),affine=require('../shell/svg-affine.js'),initial=resolve(kind),made=create(kind,initial,{ids:(reverse?['circle','rect']:['rect','circle']).map(t=>initial.elements.find(e=>tag(kind,e)===t).id)});let current=resolve(kind,made.edits[0].after,made.selectionIds[0]);
 if(transformed){const edit=adapter.planOp(current,{type:'setSVGTransform',fileHash:current.hash,matrix:[2,0,0,3,7,9]});assert.equal(edit.ok,true,edit.reason);current=resolve(kind,edit.edits[0].after,current.element.id);}
 const outer=group.plan(current,{type:'createSVGBooleanGroup',fileHash:current.hash,ids:(outerBase?[current.elements.find(e=>tag(kind,e)==='ellipse').id,current.element.id]:[current.element.id,current.elements.find(e=>tag(kind,e)==='ellipse').id]),operation:'subtract',path},kind);assert.equal(outer.ok,true,outer.reason);current=resolve(kind,outer.edits[0].after,outer.selectionIds[0]);
 const parent=group.context(current,kind),inner=group.context({...current,element:parent.roots[0]},kind),request={type:'setSVGBooleanNested',fileHash:current.hash,targetId:inner.group.id,edit:{type:'releaseSVGBooleanGroup'},results:[{id:parent.group.id,path}]};
 const released=adapter.planOp(current,request);assert.equal(released.ok,true,released.reason);assert.equal(released.edits.length,1);assert.equal(released.edits[0].before,current.source);assert.equal(released.structural,true);assert.deepEqual(new Set(released.removedSourceIds),new Set([inner.group.id,inner.operands.id,inner.result.id]));const mapping=new Map(released.sourceIdMap),mapped=id=>mapping.get(id)||id,fresh=resolve(kind,released.edits[0].after,mapped(parent.group.id)),context=group.context(fresh,kind);assert.equal(context.roots.length,3);assert.equal(context.roots[context.base].id,mapped(outerBase?parent.roots[parent.base].id:inner.roots[inner.base].id));assert.deepEqual(released.selectionIds,[context.group.id]);
 for(const root of inner.roots){const preserved=fresh.elements.find(e=>e.id===mapped(root.id));assert.ok(preserved);const expected=affine.multiply(transformed?[2,0,0,3,7,9]:affine.identity(),affine.parse(inner.attr(root,'transform')));assert.deepEqual(affine.parse(context.attr(preserved,'transform')),expected);}
 for(const bad of [{results:[]},{results:[{id:parent.group.id,path:'M0 0L1 1'}]},{fileHash:'stale'}]){const rejected=adapter.planOp(current,{...request,...bad});assert.equal(rejected.refused,true);assert.equal(rejected.edits,undefined);}
});

for(const kind of ['html','react','liquid'])for(const nested of [false,true])for(const includedBase of [false,true])test(kind+' regroup originals atomically nested='+nested+' includedBase='+includedBase,()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),shapeIds=['rect','circle','ellipse'].map(t=>r.elements.find(e=>tag(kind,e)===t).id),made=create(kind,r,{ids:includedBase?shapeIds:[shapeIds[2],...shapeIds.slice(0,2)]});assert.equal(made.ok,true,made.reason);
 let current=resolve(kind,made.edits[0].after,made.selectionIds[0]);
 if(nested){const source=current.source.replace('</svg>','<polygon points="0,0 10,0 0,10"/></svg>');current=resolve(kind,source,current.element.id);const outer=group.plan(current,{type:'createSVGBooleanGroup',fileHash:current.hash,ids:[current.element.id,current.elements.find(e=>tag(kind,e)==='polygon').id],operation:'subtract',path},kind);assert.equal(outer.ok,true,outer.reason);current=resolve(kind,outer.edits[0].after,outer.selectionIds[0]);}
 const outer=group.context(current,kind),target=nested?group.context({...current,element:outer.roots[0]},kind):outer,selected=target.roots.slice(0,2).reverse().map(e=>e.id),request={type:'setSVGBooleanNested',fileHash:current.hash,targetId:target.group.id,edit:{type:'createSVGBooleanGroup',ids:selected,operation:'intersect',path:'M0 0H10V10H0Z'},results:[{id:target.group.id,path:'M0 0H20V20H0Z'},...(nested?[{id:outer.group.id,path:'M0 0H30V30H0Z'}]:[])]};
 const result=adapter.planOp(current,request);assert.equal(result.ok,true,result.reason);assert.equal(result.structural,true);assert.equal(result.edits.length,1);assert.equal(result.edits[0].before,current.source);assert.deepEqual(result.removedSourceIds,[]);
 const mapping=new Map(result.sourceIdMap),mapped=id=>mapping.get(id)||id,fresh=resolve(kind,result.edits[0].after,result.selectionIds[0]),created=group.context(fresh,kind),parent=group.context({...fresh,element:fresh.elements.find(e=>e.id===mapped(target.group.id))},kind);
 assert.equal(created.operation,'intersect');assert.equal(created.roots[created.base].id,mapped(selected[0]));assert.equal(parent.roots.length,2);assert.equal(parent.roots[parent.base].id,includedBase?created.group.id:mapped(target.roots[target.base].id));
 for(const old of current.elements){const preserved=fresh.elements.find(e=>e.id===mapped(old.id));assert.ok(preserved);assert.equal(tag(kind,preserved),tag(kind,old));}
 for(const old of target.roots){const preserved=fresh.elements.find(e=>e.id===mapped(old.id));assert.equal(fresh.source.slice(parent.start(preserved),parent.end(preserved)),current.source.slice(target.start(old),target.end(old)));}
 for(const supplied of request.results){const c=group.context({...fresh,element:fresh.elements.find(e=>e.id===mapped(supplied.id))},kind);assert.equal(c.attr(c.result,'d'),require('../shell/svg-path.js').serializeCompound(require('../shell/svg-path.js').parseCompound(supplied.path)));}
 for(const bad of [{results:[]},{results:request.results.map((e,i)=>i===request.results.length-1?{...e,path:'invalid'}:e)},{edit:{...request.edit,ids:[]}},{edit:{...request.edit,ids:[selected[0],outer.result.id]}},{edit:{...request.edit,ids:[selected[0],selected[0]]}},{fileHash:'old'}]){const refused=adapter.planOp(current,{...request,...bad});assert.equal(refused.refused,true,JSON.stringify(bad));assert.equal(refused.edits,undefined);}
 const bypass=adapter.planOp({...current,element:current.elements.find(e=>e.id===selected[0])},{...request.edit,fileHash:current.hash});assert.equal(bypass.refused,true);
});

for(const kind of ['html','react','liquid'])test(kind+' regrouping every original retains an editable single-operand parent',()=>{
 const r=resolve(kind),made=create(kind,r),current=resolve(kind,made.edits[0].after,made.selectionIds[0]),c=group.context(current,kind),adapter=require('../src/adapters/'+kind+'.cjs');
 const changed=adapter.planOp(current,{type:'setSVGBooleanNested',fileHash:current.hash,targetId:c.group.id,edit:{type:'createSVGBooleanGroup',ids:c.roots.map(e=>e.id),operation:'subtract',path},results:[{id:c.group.id,path}]});assert.equal(changed.ok,true,changed.reason);const mapping=new Map(changed.sourceIdMap),fresh=resolve(kind,changed.edits[0].after,mapping.get(c.group.id)||c.group.id),parent=group.context(fresh,kind);assert.equal(parent.roots.length,1);assert.equal(parent.base,0);assert.ok(group.describe(fresh,kind).canRelease);
 const released=adapter.planOp(fresh,{type:'setSVGBooleanNested',fileHash:fresh.hash,targetId:parent.roots[0].id,edit:{type:'releaseSVGBooleanGroup'},results:[{id:parent.group.id,path}]});assert.equal(released.ok,true,released.reason);const releasedMap=new Map(released.sourceIdMap),restored=resolve(kind,released.edits[0].after,releasedMap.get(parent.group.id)||parent.group.id);assert.equal(group.context(restored,kind).roots.length,2);assert.equal(adapter.planOp(restored,{type:'releaseSVGBooleanGroup',fileHash:restored.hash}).edits[0].after,r.source);
});

for(const kind of ['html','react','liquid'])for(const nested of [false,true])for(const removeBase of [false,true])test(kind+' remove boolean original nested='+nested+' base='+removeBase,()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r);let current=resolve(kind,made.edits[0].after,made.selectionIds[0]);
 if(nested){const outer=group.plan(current,{type:'createSVGBooleanGroup',fileHash:current.hash,ids:[current.element.id,current.elements.find(e=>tag(kind,e)==='ellipse').id],operation:'union',path},kind);assert.equal(outer.ok,true,outer.reason);current=resolve(kind,outer.edits[0].after,outer.selectionIds[0]);}
 const outer=group.context(current,kind),target=nested?group.context({...current,element:outer.roots[0]},kind):outer,operand=target.roots[removeBase?0:1],remaining=target.roots[removeBase?1:0],edit={type:'removeSVGBooleanOperand',operandId:operand.id,path:'M0 0H30V40H0Z'},request=nested?{type:'setSVGBooleanNested',fileHash:current.hash,targetId:target.group.id,edit,results:[{id:outer.group.id,path:'M0 0H50V60H0Z'}]}:{...edit,fileHash:current.hash};
 const changed=adapter.planOp(current,request);assert.equal(changed.ok,true,changed.reason);assert.equal(changed.structural,true);assert.equal(changed.edits.length,1);assert.equal(changed.edits[0].before,current.source);assert.deepEqual(changed.removedSourceIds,[operand.id]);const mapping=new Map(changed.sourceIdMap),mapped=id=>mapping.get(id)||id,fresh=resolve(kind,changed.edits[0].after,mapped(target.group.id)),next=group.context(fresh,kind);assert.equal(next.roots.length,1);assert.equal(next.roots[0].id,mapped(remaining.id));assert.deepEqual(changed.selectionIds,[next.group.id]);assert.equal(next.attr(next.result,'fill'),'red');assert.equal(fresh.source.slice(next.start(next.roots[0]),next.end(next.roots[0])),current.source.slice(target.start(remaining),target.end(remaining)));assert.deepEqual(require('../shell/svg-affine.js').parse(next.attr(next.result,'transform')),removeBase?[1,0,0,1,0,0]:[1,0,0,1,3,4]);
 const last=adapter.planOp(fresh,{type:'removeSVGBooleanOperand',fileHash:fresh.hash,operandId:next.roots[0].id,path:''});if(nested){assert.equal(last.refused,true);assert.equal(last.edits,undefined);}else{assert.equal(last.ok,true,last.reason);assert.ok(!last.edits[0].after.includes('data-rt-boolean'));}
 const invalid=nested?{...request,results:[{id:outer.group.id,path:'not a path'}]}:{...request,path:'not a path'};const refused=adapter.planOp(current,invalid);assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);
});

for(const kind of ['html','react','liquid'])test(kind+' removing a retained boolean operand removes its entire subtree only',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r),inner=resolve(kind,made.edits[0].after,made.selectionIds[0]),outer=group.plan(inner,{type:'createSVGBooleanGroup',fileHash:inner.hash,ids:[inner.element.id,inner.elements.find(e=>tag(kind,e)==='ellipse').id],operation:'subtract',path},kind),current=resolve(kind,outer.edits[0].after,outer.selectionIds[0]),c=group.context(current,kind),removed=c.roots[0],expected=current.elements.filter(e=>c.start(e)>=c.start(removed)&&c.end(e)<=c.end(removed)).map(e=>e.id);
 const result=adapter.planOp(current,{type:'removeSVGBooleanOperand',fileHash:current.hash,operandId:removed.id,path:'M0 0H2V3H0Z'});assert.equal(result.ok,true,result.reason);assert.deepEqual(new Set(result.removedSourceIds),new Set(expected));const fresh=resolve(kind,result.edits[0].after,result.selectionIds[0]),next=group.context(fresh,kind);assert.equal(next.roots.length,1);assert.equal(tag(kind,next.roots[0]),'ellipse');assert.equal(next.attr(next.result,'fill'),'red');assert.ok(fresh.source.includes('<p>After</p>'));assert.equal((fresh.source.match(/data-rt-boolean=/g)||[]).length,1);
});

for(const kind of ['html','react','liquid'])for(const survives of [false,true])test(kind+' final original removes empty ancestor chain survivingParent='+survives,()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r);let current=resolve(kind,made.edits[0].after,made.selectionIds[0]),c=group.context(current,kind);
 const regrouped=adapter.planOp(current,{type:'setSVGBooleanNested',fileHash:current.hash,targetId:c.group.id,edit:{type:'createSVGBooleanGroup',ids:c.roots.map(e=>e.id),operation:'union',path},results:[{id:c.group.id,path}]});assert.equal(regrouped.ok,true,regrouped.reason);const mapping=new Map(regrouped.sourceIdMap);current=resolve(kind,regrouped.edits[0].after,mapping.get(c.group.id)||c.group.id);
 if(survives){const wrap=group.plan(current,{type:'createSVGBooleanGroup',fileHash:current.hash,ids:[current.element.id,current.elements.find(e=>tag(kind,e)==='ellipse').id],operation:'union',path},kind);assert.equal(wrap.ok,true,wrap.reason);current=resolve(kind,wrap.edits[0].after,wrap.selectionIds[0]);}
 const descend=resolved=>{let context=group.context(resolved,kind);while(group.context({...resolved,element:context.roots[0]},kind))context=group.context({...resolved,element:context.roots[0]},kind);return context;};
 const request=(resolved,target,operandId,final)=>{const results=[];let child=target.group;for(let id=group.ancestor({...resolved,element:child},kind);id;id=group.ancestor({...resolved,element:child},kind)){child=resolved.elements.find(e=>e.id===id);const ancestor=group.context({...resolved,element:child},kind);results.push({id,path:final&&ancestor.roots.length===1?'':path});}return {type:'setSVGBooleanNested',fileHash:resolved.hash,targetId:target.group.id,edit:{type:'removeSVGBooleanOperand',operandId,path:final?'':path},results};};
 let target=descend(current);const first=adapter.planOp(current,request(current,target,target.roots[1].id,false));assert.equal(first.ok,true,first.reason);const firstMap=new Map(first.sourceIdMap);current=resolve(kind,first.edits[0].after,firstMap.get(current.element.id)||current.element.id);target=descend(current);assert.equal(target.roots.length,1);
 const finalRequest=request(current,target,target.roots[0].id,true),removed=adapter.planOp(current,finalRequest);assert.equal(removed.ok,true,removed.reason);assert.equal(removed.edits.length,1);assert.equal(removed.edits[0].before,current.source);const fresh=resolve(kind,removed.edits[0].after,removed.selectionIds[0]);assert.ok(fresh.element);assert.equal((fresh.source.match(/data-rt-boolean=/g)||[]).length,survives?1:0);assert.ok(fresh.source.includes('<p>After</p>'));if(survives)assert.equal(tag(kind,group.context(fresh,kind).roots[0]),'ellipse');else assert.equal(tag(kind,fresh.element),'svg');
 const bad={...finalRequest,results:finalRequest.results.map((entry,i)=>i===finalRequest.results.length-1?{...entry,path:'invalid'}:entry)},refused=adapter.planOp(current,bad);assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);
});

for(const kind of ['html','react','liquid'])for(const nested of [false,true])for(const positions of [[0,2],[1,2],[0,1,2]])for(const reverse of [false,true])test(kind+' remove original selection nested='+nested+' positions='+positions+' reverse='+reverse,()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r,{ids:['rect','circle','ellipse'].map(t=>r.elements.find(e=>tag(kind,e)===t).id)});let current=resolve(kind,made.edits[0].after,made.selectionIds[0]);
 if(nested){const source=current.source.replace('</svg>','<polygon points="0,0 10,0 0,10"/></svg>');current=resolve(kind,source,current.element.id);const wrap=group.plan(current,{type:'createSVGBooleanGroup',fileHash:current.hash,ids:[current.element.id,current.elements.find(e=>tag(kind,e)==='polygon').id],operation:'union',path},kind);assert.equal(wrap.ok,true,wrap.reason);current=resolve(kind,wrap.edits[0].after,wrap.selectionIds[0]);}
 const outer=group.context(current,kind),target=nested?group.context({...current,element:outer.roots[0]},kind):outer,operandIds=(reverse?[...positions].reverse():positions).map(i=>target.roots[i].id),edit={type:'removeSVGBooleanOperand',operandIds,path:positions.length===3?'':path},request=nested?{type:'setSVGBooleanNested',fileHash:current.hash,targetId:target.group.id,edit,results:[{id:outer.group.id,path}]}:{...edit,fileHash:current.hash},result=adapter.planOp(current,request);assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,1);assert.equal(result.edits[0].before,current.source);const fresh=resolve(kind,result.edits[0].after,result.selectionIds[0]),mapping=new Map(result.sourceIdMap),removed=new Set(result.removedSourceIds);for(const old of current.elements){if(removed.has(old.id))continue;assert.ok(fresh.elements.some(e=>e.id===(mapping.get(old.id)||old.id)),'surviving identity '+old.id);}assert.ok(fresh.source.includes('<p>After</p>'));
 if(positions.length<3){const c=group.context(fresh,kind);assert.equal(c.roots.length,1);assert.equal(c.attr(c.result,'fill'),'red');assert.equal(tag(kind,c.roots[0]),positions.includes(0)?'circle':'rect');}else assert.equal((fresh.source.match(/data-rt-boolean=/g)||[]).length,nested?1:0);
 for(const badIds of [[],[operandIds[0],operandIds[0]],[operandIds[0],'missing']]){const bad=nested?{...request,edit:{...edit,operandIds:badIds}}:{...request,operandIds:badIds},refused=adapter.planOp(current,bad);assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);}
 const bad=nested?{...request,results:[{id:outer.group.id,path:'invalid'}]}:{...request,path:'invalid'};assert.equal(adapter.planOp(current,bad).refused,true);
});

for(const kind of ['html','react','liquid'])for(const nested of [false,true])for(const mode of ['partial','wholeAndPartial','all'])test(kind+' cross-parent boolean deletion nested='+nested+' mode='+mode,()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),initial=resolve(kind),r=resolve(kind,initial.source.replace('<ellipse rx="2" ry="3"/>','<rect width="20" height="30" fill="green"/><circle cx="15" cy="15" r="10"/>')),first=create(kind,r);assert.equal(first.ok,true,first.reason);let current=resolve(kind,first.edits[0].after,first.selectionIds[0]);
 const pair=current.elements.filter(e=>['rect','circle'].includes(tag(kind,e))).slice(-2),second=group.plan({...current,element:pair[0]},{type:'createSVGBooleanGroup',fileHash:current.hash,ids:pair.map(e=>e.id),operation:'subtract',path},kind);assert.equal(second.ok,true,second.reason);current=resolve(kind,second.edits[0].after,second.selectionIds[0]);
 const leafGroups=resolved=>resolved.elements.map(element=>group.context({...resolved,element},kind)).filter(c=>c&&c.roots.every(element=>!group.context({...resolved,element},kind)));let [a,b]=leafGroups(current);
 if(nested){const wrapped=group.plan({...current,element:a.group},{type:'createSVGBooleanGroup',fileHash:current.hash,ids:[a.group.id,b.group.id],operation:'union',path},kind);assert.equal(wrapped.ok,true,wrapped.reason);current=resolve(kind,wrapped.edits[0].after,wrapped.selectionIds[0]);[a,b]=leafGroups(current);}
 const outer=nested?group.context(current,kind):null,ids=mode==='partial'?[a.roots[0].id,b.roots[1].id]:mode==='wholeAndPartial'?[a.group.id,a.roots[0].id,b.roots[0].id]:[...a.roots,...b.roots].map(e=>e.id),results=mode==='all'?[]:[...(mode==='partial'?[{id:a.group.id,path}]:[]),{id:b.group.id,path},...(outer?[{id:outer.group.id,path}]:[])],selected={...current,element:current.elements.find(e=>e.id===ids[0])},request={type:'removeSVGBooleanSelection',fileHash:current.hash,ids,results};
 const changed=adapter.planOp(selected,request);assert.equal(changed.ok,true,changed.reason);assert.equal(changed.edits.length,1);assert.equal(changed.edits[0].before,current.source);const mapping=new Map(changed.sourceIdMap),removed=new Set(changed.removedSourceIds),fresh=resolve(kind,changed.edits[0].after,changed.selectionIds[0]);assert.ok(fresh.element);assert.equal(fresh.elements.length,current.elements.length-removed.size);for(const old of current.elements)if(!removed.has(old.id))assert.ok(fresh.elements.some(e=>e.id===(mapping.get(old.id)||old.id)));assert.ok(fresh.source.includes('<p>After</p>'));
 const count=(fresh.source.match(/data-rt-boolean=/g)||[]).length;assert.equal(count,mode==='all'?0:(mode==='partial'?2:1)+(nested?1:0));if(mode==='all')assert.equal(tag(kind,fresh.element),'svg');else{const remaining=leafGroups(fresh);assert.equal(remaining.length,mode==='partial'?2:1);for(const c of remaining)assert.equal(c.roots.length,1);const last=remaining.at(-1);assert.equal(last.attr(last.result,'fill'),'green');}
 for(const bad of [{fileHash:'stale'},{ids:[ids[0],ids[0]]},{results:results.length?results.map((entry,i)=>i===results.length-1?{...entry,path:'invalid'}:entry):[{id:a.group.id,path}]}]){const refused=adapter.planOp(selected,{...request,...bad});assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);}
 if(results.length>1){const refused=adapter.planOp(selected,{...request,results:[...results].reverse()});assert.equal(refused.refused,true);}
});

for(const kind of ['html','react','liquid'])for(const whole of [false,true])for(const reverse of [false,true])test(kind+' mixed ordinary SVG and boolean deletion whole='+whole+' reverse='+reverse,()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r),current=resolve(kind,made.edits[0].after,made.selectionIds[0]),c=group.context(current,kind),plain=current.elements.find(e=>tag(kind,e)==='ellipse'),ids=[whole?c.group.id:c.roots[0].id,plain.id];if(reverse)ids.reverse();const selected={...current,element:current.elements.find(e=>e.id===ids[0])},request={type:'removeSVGBooleanSelection',fileHash:current.hash,ids,results:whole?[]:[{id:c.group.id,path}]},result=adapter.planOp(selected,request);assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,1);assert.equal(result.edits[0].before,current.source);const fresh=resolve(kind,result.edits[0].after,result.selectionIds[0]);assert.ok(fresh.element);assert.ok(!fresh.elements.some(e=>tag(kind,e)==='ellipse'));assert.ok(fresh.source.includes('<p>After</p>'));if(whole)assert.equal(tag(kind,fresh.element),'svg');else{const next=group.context(fresh,kind);assert.equal(next.roots.length,1);assert.equal(tag(kind,next.roots[0]),'circle');assert.equal(next.attr(next.result,'fill'),'red');}
 const paragraph=current.elements.find(e=>tag(kind,e)==='p'),bad=adapter.planOp(selected,{...request,ids:[...ids,paragraph.id]});assert.equal(bad.refused,true);assert.equal(bad.edits,undefined);const invalid=adapter.planOp(selected,{...request,results:[{id:c.group.id,path:'invalid'}]});assert.equal(invalid.refused,true);assert.equal(invalid.edits,undefined);
});

for(const kind of ['html','react','liquid'])test(kind+' mixed deletion rejects HTML descendants of foreignObject',()=>{
 const adapter=require('../src/adapters/'+kind+'.cjs'),r=resolve(kind),made=create(kind,r),source=made.edits[0].after.replace('</svg>','<foreignObject><g data-rt-name="html-group"></g></foreignObject></svg>'),current=resolve(kind,source,made.selectionIds[0]),v=group.view(current,kind),html=v.elements.find(e=>v.attr(e,'data-rt-name')==='html-group'),c=group.context(current,kind),selected={...current,element:c.roots[0]},refused=adapter.planOp(selected,{type:'removeSVGBooleanSelection',fileHash:current.hash,ids:[c.roots[0].id,html?.id||'unselectable-html-group'],results:[{id:c.group.id,path}]});assert.equal(refused.refused,true);assert.equal(refused.edits,undefined);
});
