'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),ids=require('../src/id.cjs');
for(const kind of ['html','react','liquid']){
 const adapter=require('../src/adapters/'+kind+'.cjs'),color=kind==='react'?'stopColor':'stop-color',wrap=body=>kind==='react'?'export default()=>('+body+');':'<html><body>'+body+'</body></html>';
 const definition='<linearGradient id="paint" aria-labelledby="stop-name" '+(kind==='react'?'key="original" ':'')+'><stop id="stop-name" offset="0" '+color+'="#ff0000"/><stop id="ff0000" offset="1" '+color+'="blue"/></linearGradient>',original=wrap('<svg><defs>'+definition+'<radialGradient id="other"><stop offset="0"/></radialGradient></defs><rect fill="url(#paint)" stroke="url(#paint)" width="40"/><circle fill="url(#paint)" r="10"/></svg>');
 const resolve=source=>{const relPath=kind==='react'?'app/page.jsx':kind==='liquid'?'sections/main.liquid':'index.html',elements=adapter.collect(source,relPath).elements;return {source,relPath,elements,element:elements.find(el=>(kind==='react'?ids.jsxElementName(el.node):el.tag)==='rect'),hash:ids.contentHash(source),file:'/tmp/'+relPath};};
 test(kind+' makes a unique gradient without changing original resources or existing identities',()=>{
  const r=resolve(original),result=adapter.planOp(r,{type:'setSVGGradient',fileHash:r.hash,paint:'fill',action:'detach'});assert.equal(result.ok,true,result.reason);const after=result.edits[0].after,fresh=resolve(after),g=adapter.describe(fresh).svgGradients;
  assert.ok(after.includes(definition));assert.ok(after.includes('<circle fill="url(#paint)" r="10"/>'));assert.equal(fresh.element.id,r.element.id);assert.ok(r.elements.every(el=>fresh.elements.some(n=>n.id===el.id)));
  assert.notEqual(g.find(g=>g.paint==='fill').id,'paint');assert.equal(g.find(g=>g.paint==='stroke').id,'paint');assert.equal(g[0].stops[0].color,'#ff0000','A color that resembles a resource ID remains a color');
  const sourceIDs=[...after.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(sourceIDs).size,sourceIDs.length);const cloneLabel=[...after.matchAll(/aria-labelledby="([^"]+)"/g)][1][1];assert.notEqual(cloneLabel,'stop-name');assert.ok(sourceIDs.includes(cloneLabel));
  const edit=adapter.planOp(fresh,{type:'setSVGGradient',fileHash:fresh.hash,paint:'fill',stop:0,changes:{'stop-color':'green'}});assert.equal(edit.ok,true,edit.reason);assert.ok(edit.edits[0].after.includes(definition));assert.equal(adapter.describe(resolve(edit.edits[0].after)).svgGradients.find(g=>g.paint==='fill').stops[0].color,'green');
 });
 test(kind+' preserves identities when the unique resource is appended after the painted layer',()=>{const r=resolve(original.replace('<defs>','').replace('</defs>','')),result=adapter.planOp(r,{type:'setSVGGradient',fileHash:r.hash,paint:'stroke',action:'detach'});assert.equal(result.ok,true,result.reason);const fresh=resolve(result.edits[0].after);assert.ok(r.elements.every(el=>fresh.elements.some(n=>n.id===el.id)));assert.equal(adapter.describe(fresh).svgGradients.find(g=>g.paint==='fill').id,'paint');assert.notEqual(adapter.describe(fresh).svgGradients.find(g=>g.paint==='stroke').id,'paint');});
 test(kind+' refuses stale or mixed detach operations',()=>{const r=resolve(original);for(const extra of [{fileHash:'stale'},{stop:0},{changes:{x2:'20%'}},{value:{color:'red'}}]){const result=adapter.planOp(r,{type:'setSVGGradient',fileHash:r.hash,paint:'fill',action:'detach',...extra});assert.equal(result.refused,true);assert.equal(result.edits,undefined);}});
}
