'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),html=require('../src/adapters/html.cjs'),linked=require('../src/html-variable-bindings.cjs'),css=require('../src/html-css.cjs'),batch=require('../src/variable-selection.cjs');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),library={version:1,collections:[{id:id(1),name:'Theme',defaultMode:id(2),modes:[{id:id(2),name:'Light'},{id:id(3),name:'Dark'}]}],variables:[{id:id(4),collectionId:id(1),name:'Brand',type:'color',values:{[id(2)]:'#123456',[id(3)]:'#cc3300'}}]},original='<html><head></head><body><h1>First</h1><p>Second</p></body></html>';
function resolve(source){const elements=html.collect(source,'index.html').elements;return {file:'/tmp/index.html',relPath:'index.html',source,hash:html.contentHash(source),elements,element:elements.find(e=>e.tag==='h1')};}
function operation(source,type,extra={}){const r=resolve(source);return {type,id:r.element.id,ids:r.elements.filter(e=>['h1','p'].includes(e.tag)).map(e=>e.id),fileHash:r.hash,width:0,property:'color',...extra};}
test('batch bindings produce one source edit and preserve each layer mode when resetting',()=>{
 let r=resolve(original),first=linked.plan(r,{type:'applyVariable',width:0,property:'color',binding:{id:id(4)}},library);let source=first.edits[0].after;r=resolve(source);r.element=r.elements.find(e=>e.tag==='p');source=linked.plan(r,{type:'applyVariable',width:0,property:'color',binding:{id:id(4),modes:{[id(1)]:id(3)}}},library).edits[0].after;
 for(const tag of ['h1','p']){r=resolve(source);r.element=r.elements.find(e=>e.tag===tag);source=css.plan(r,{width:0,property:'color',value:'#00ff00'}).edits[0].after;}
 const reset=batch.plan(resolve(source),operation(source,'resetVariableSelection'),library);assert.equal(reset.ok,true,reset.reason);assert.equal(reset.edits.length,1);assert.deepEqual(reset.selection.map(info=>info.variableLinks[0].color.value),['#123456ff','#cc3300ff']);
 const applied=batch.plan(resolve(original),operation(original,'applyVariableSelection',{binding:{id:id(4)}}),library);assert.equal(applied.ok,true,applied.reason);assert.equal(applied.selection.length,2);assert.equal(applied.edits.length,1);assert.ok(applied.selection.every(info=>info.variableLinks[0].color.id===id(4)));
});
test('batch failures never return partial edits; reset and detach leave unbound layers untouched',()=>{
 const blocked=original.replace('<p>','<p style="color:red!important">');const fail=batch.plan(resolve(blocked),operation(blocked,'applyVariableSelection',{binding:{id:id(4)}}),library);assert.equal(fail.ok,false);assert.equal(fail.edits,undefined);
 const first=linked.plan(resolve(original),{type:'applyVariable',width:0,property:'color',binding:{id:id(4)}},library).edits[0].after;
 const detached=batch.plan(resolve(first),operation(first,'detachVariableSelection'));assert.equal(detached.ok,true,detached.reason);assert.ok(detached.edits[0].after.includes('<p>Second</p>'));assert.ok(detached.selection.every(info=>!Object.keys(info.variableLinks).length));assert.equal(css.describe(resolve(detached.edits[0].after)).cssRules[0].color,'#123456ff');
 for(const extra of [{fileHash:'old'},{ids:['bad','bad']},{property:'unknown'},{width:-1}]){const result=batch.plan(resolve(original),operation(original,'applyVariableSelection',{binding:{id:id(4)},...extra}),library);assert.equal(result.ok,false);assert.equal(result.edits,undefined);}
});

test('React batch bindings preserve independent modes and refuse any ambiguous selected layer',()=>{
 const react=require('../src/adapters/react.cjs'),jsx=require('../src/jsx-variable-bindings.cjs'),source='export default function Page(){return <main><h1 className="text-xl">First</h1><p>Second</p></main>}',resolveReact=source=>{const elements=react.collect(source,'Page.jsx').elements;return {file:'/tmp/Page.jsx',relPath:'Page.jsx',source,elements,element:elements.find(e=>e.node.openingElement.name.name==='h1'),hash:react.contentHash(source)};},op=(source,type,extra={})=>{const r=resolveReact(source);return {type,fileHash:r.hash,scope:'md:',property:'color',ids:r.elements.filter(e=>['h1','p'].includes(e.node.openingElement.name.name)).map(e=>e.id),...extra};};
 let applied=batch.plan(resolveReact(source),op(source,'applyVariableSelection',{binding:{id:id(4)}}),library,react);assert.equal(applied.ok,true,applied.reason);assert.equal(applied.edits.length,1);let current=applied.edits[0].after,r=resolveReact(current);r.element=r.elements.find(e=>e.node.openingElement.name.name==='p');current=jsx.plan(r,{type:'applyVariable',scope:'md:',property:'color',binding:{id:id(4),modes:{[id(1)]:id(3)}}},library).edits[0].after;
 current=current.replaceAll('md:![color:#123456ff]','md:![color:#00ff00ff]').replaceAll('md:![color:#cc3300ff]','md:![color:#00ff00ff]');const reset=batch.plan(resolveReact(current),op(current,'resetVariableSelection'),library,react);assert.equal(reset.ok,true,reset.reason);assert.deepEqual(reset.selection.map(info=>info.variableLinks['md:'].color.value),['#123456ff','#cc3300ff']);
 const detached=batch.plan(resolveReact(reset.edits[0].after),op(reset.edits[0].after,'detachVariableSelection'),undefined,react);assert.equal(detached.ok,true,detached.reason);assert.deepEqual(detached.selection.map(info=>info.className),reset.selection.map(info=>info.className));
 for(const bad of [source.replace('<p>','<p {...props}>'),source.replace('<p>','<p className={dynamic}>'),source.replace('<p>','<p className="md:!custom">')]){const result=batch.plan(resolveReact(bad),op(bad,'applyVariableSelection',{binding:{id:id(4)}}),library,react);assert.equal(result.ok,false);assert.equal(result.edits,undefined);}
});

test('Liquid batches preserve separate conditional classes and modes, and refuse partial writes',async()=>{
 const liquid=require('../src/adapters/liquid.cjs'),single=require('../src/liquid-variable-bindings.cjs'),engine=new(require('liquidjs').Liquid)(),source='<h1 class="{% if active %}font-bold{% else %}font-normal{% endif %}">First</h1><p class="{% if active %}tracking-wide{% else %}tracking-normal{% endif %}">Second</p>';
 const resolve=source=>{const elements=liquid.collect(source,'main.liquid').elements;return {file:'/tmp/main.liquid',relPath:'main.liquid',source,elements,element:elements[0],hash:liquid.contentHash(source)};};
 const operation=(source,type,extra={})=>{const r=resolve(source);return {type,fileHash:r.hash,scope:'md:',property:'color',ids:r.elements.map(element=>element.id),contexts:Object.fromEntries(r.elements.map(element=>[element.id,{className:element.tag==='h1'?'font-bold':'tracking-wide'}])),...extra};};
 const applied=batch.plan(resolve(source),operation(source,'applyVariableSelection',{binding:{id:id(4)}}),library,liquid);assert.equal(applied.ok,true,applied.reason);assert.equal(applied.edits.length,1);assert.equal(applied.selection.length,2);assert.ok(applied.selection.every(info=>info.collectionSelection));
 let current=applied.edits[0].after,r=resolve(current);r.element=r.elements[1];r.context={className:'tracking-wide'};current=single.plan(r,{type:'applyVariable',scope:'md:',property:'color',binding:{id:id(4),modes:{[id(1)]:id(3)}}},library).edits[0].after;
 current=current.replaceAll('md:![color:#123456ff]','md:![color:#00ff00ff]').replaceAll('md:![color:#cc3300ff]','md:![color:#00ff00ff]');
 const reset=batch.plan(resolve(current),operation(current,'resetVariableSelection'),library,liquid);assert.equal(reset.ok,true,reset.reason);assert.deepEqual(reset.selection.map(info=>info.variableLinks['md:'].color.value),['#123456ff','#cc3300ff']);
 for(const active of [true,false]){const rendered=await engine.parseAndRender(reset.edits[0].after,{active});assert.ok(rendered.includes(active?'font-bold':'font-normal'));assert.ok(rendered.includes(active?'tracking-wide':'tracking-normal'));assert.ok(rendered.includes('md:![color:#123456ff]'));assert.ok(rendered.includes('md:![color:#cc3300ff]'));const hosts=liquid.collect(rendered,'main.liquid').elements;assert.ok(!hosts[0].classAttr.value.includes('tracking-'));assert.ok(!hosts[1].classAttr.value.includes('font-'));}
 const detached=batch.plan(resolve(reset.edits[0].after),operation(reset.edits[0].after,'detachVariableSelection'),undefined,liquid);assert.equal(detached.ok,true,detached.reason);assert.deepEqual(detached.selection.map(info=>info.className),reset.selection.map(info=>info.className));
 for(const bad of [source.replace('<p class=','<p style="{{ style }}" class='),source.replace('<p class=','<p data-rt-variables="bad" class=')]){const result=batch.plan(resolve(bad),operation(bad,'applyVariableSelection',{binding:{id:id(4)}}),library,liquid);assert.equal(result.ok,false);assert.equal(result.edits,undefined);}
 const missing=operation(source,'applyVariableSelection',{binding:{id:id(4)}});delete missing.contexts[missing.ids[1]];assert.equal(batch.plan(resolve(source),missing,library,liquid).ok,false);
});
