'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),base=require('../src/adapters/svelte.cjs'),source=require('../src/svelte-source.cjs'),{create}=require('../src/vite-picture-adapter.cjs');
function fixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'rt-vite-picture-adapter-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'App.svelte'),text='<main><img src="/wide.svg" alt="Art"/><span>Caption</span></main><style>main>img{width:40px}</style>';fs.writeFileSync(file,text);const css=path.join(root,'theme.css');fs.writeFileSync(css,'img+span{margin-left:8px}');const nodes=new Map([[file,{id:file,file}],[css,{id:css,file:css}]]),server={environments:{client:{moduleGraph:{idToModuleMap:nodes}}}},resolved={file,appRoot:root,relPath:'App.svelte',source:text,hash:source.contentHash(text),element:source.collect(text,'App.svelte').elements.find(e=>e.tag==='img')},adapter=create(base,server,root),op={type:'setPictureSources',action:'add',src:'/phone.svg',media:'(max-width:600px)',fileHash:resolved.hash,pictureStyles:[{sheets:[],issues:[]}]};return {root,file,css,resolved,adapter,op};}
test('Vite Svelte adapter exposes picture creation and plans markup plus dependency styles',async t=>{
 const f=fixture(t),info=f.adapter.describe(f.resolved);assert.equal(info.pictureSourceAuthoring,true);assert.equal(info.pictureStylesRequired,true);assert.equal(base.describe(f.resolved).pictureSourceAuthoring,false);
 const result=await f.adapter.planOp(f.resolved,f.op);assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,2);assert.ok(result.createdSourceIds.length===2);assert.notEqual(result.imageId,info.id);assert.match(result.edits[0].after,/<picture data-rt-picture/);assert.match(result.edits[1].after,/data-rt-picture/);require('svelte/compiler').compile(result.edits[0].after,{filename:'App.svelte'});
});
test('Vite Svelte picture creation refuses missing coverage and stale component bytes before writes',async t=>{
 const f=fixture(t);for(const op of [{...f.op,pictureStyles:undefined},{...f.op,pictureStyles:[{sheets:[],issues:['Unmapped style']}]},{...f.op,fileHash:'old'}]){const result=await f.adapter.planOp(f.resolved,op);assert.equal(result.ok,false);assert.equal(fs.readFileSync(f.file,'utf8'),f.resolved.source);}
 fs.writeFileSync(f.file,f.resolved.source+' ');const result=await f.adapter.planOp(f.resolved,f.op);assert.equal(result.ok,false);assert.match(result.reason,/changed/);
});
