'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const adapter=require('../src/adapters/vue.cjs'),factory=require('../src/vue-linked-styles.cjs'),selection=require('../src/text-style-selection.cjs'),{SourceHistory}=require('../src/history.cjs');
const original='<script setup>const count=1;</script><template><main><p :title="String(count)" @click="count++">Hello {{ count }}</p><p>Second</p></main></template><style scoped>p{margin:0}</style>';
const definitions={color:{color:'#123456'},effect:{'box-shadow':'0px 2px 4px #000000',filter:'blur(2px)'}};
function resolve(source=original,file='/app/App.vue'){const relPath=path.basename(file),elements=adapter.collect(source,relPath).elements;return {source,file,relPath,elements,element:elements.find(e=>e.tag==='p'),hash:adapter.contentHash(source)};}
function after(result,source){assert.equal(result.ok,true,result.reason);return result.edits[0]?.after||source;}
for(const family of ['color','effect']){
 const linked=factory.create(family,adapter),title=family==='color'?'Color':'Effect',style={id:'11111111-1111-4111-8111-111111111111',name:'Shared '+family,properties:definitions[family]},property=family==='color'?'color':'filter',changed=family==='color'?'#abcdef':'blur(4px)',override=family==='color'?'#fedcba':'blur(8px)';
 test('Vue '+family+' styles preserve bindings, responsive scopes, overrides and atomic selections',()=>{
  let r=resolve(),source=after(linked.plan(r,{type:'apply'+title+'Style',width:768,property},style),r.source);r=resolve(source);assert.match(source,/@click="count\+\+"/);assert.match(source,/Hello \{\{ count \}\}/);assert.deepEqual(adapter.describe(r).cssRules[768],definitions[family]);assert.ok(linked.links(r)[768]);
  source=after(adapter.planOp(r,{type:'setCSS',width:768,property,value:override}),source);r=resolve(source);const next={...style,properties:{...style.properties,[property]:changed}};source=after(linked.plan(r,{type:'refresh'+title+'Style',width:768,property},next),source);r=resolve(source);assert.equal(adapter.describe(r).cssRules[768][property],override);
  source=after(linked.plan(r,{type:'reset'+title+'Style',width:768,property},next),source);r=resolve(source);assert.equal(adapter.describe(r).cssRules[768][property],changed);const visible=adapter.describe(r).cssRules;source=after(linked.plan(r,{type:'detach'+title+'Style',width:768,property}),source);assert.deepEqual(linked.links(resolve(source)),{});assert.deepEqual(adapter.describe(resolve(source)).cssRules,visible);
  r=resolve();const ids=r.elements.filter(e=>e.tag==='p').map(e=>e.id),result=selection.plan(r,{type:'apply'+title+'StyleSelection',ids,fileHash:r.hash,width:0,property},style,adapter,family);assert.equal(result.ok,true,result.reason);assert.equal(result.edits.length,1);assert.equal(result.selection.length,2);for(const info of result.selection)assert.equal(info.cssRules[0][property],style.properties[property]);
  const bad=resolve(original.replace('<p>Second','<p :style="computed">Second'));assert.equal(selection.plan(bad,{type:'apply'+title+'StyleSelection',ids,fileHash:bad.hash,width:0,property},style,adapter,family).refused,true);
 });
 test('Vue '+family+' project updates include unvisited files and exact catalog/source history',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-vue-'+family+'-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const catalog=require('../src/'+family+'-styles.cjs'),saved=catalog.change(root,{type:'create',revision:null,name:style.name,properties:style.properties}),definition=saved.styles[0];
  for(const name of ['App.vue','Unvisited.vue']){const file=path.join(root,name);fs.writeFileSync(file,after(linked.plan(resolve(original,file),{type:'apply'+title+'Style',width:0,property},definition),original));}
  fs.writeFileSync(path.join(root,'Unlinked.vue'),'<template><button v-bind="attrs">Unlinked</button></template>');const snapshot=()=>Object.fromEntries(['App.vue','Unvisited.vue','.retouch/'+family+'-styles.json'].map(name=>[name,fs.readFileSync(path.join(root,name),'utf8')])),before=snapshot(),plan=require('../src/text-style-update.cjs').plan(root,{type:'update',revision:saved.revision,id:saved.id,name:style.name,properties:{...style.properties,[property]:changed}},'vue',family,adapter);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.updated,2);assert.deepEqual(snapshot(),before);const history=new SourceHistory(),result=history.commit(root,plan);assert.equal(result.ok,true,result.reason);const updated=snapshot();assert.equal(adapter.describe(resolve(updated['Unvisited.vue'],path.join(root,'Unvisited.vue'))).cssRules[0][property],changed);assert.equal(history.apply(root,'undo',result.undoId,adapter).ok,true);assert.deepEqual(snapshot(),before);assert.equal(history.apply(root,'redo',result.undoId,adapter).ok,true);assert.deepEqual(snapshot(),updated);
 });
 test('Vue '+family+' style metadata and stale source refuse before writes',()=>{
  const attribute='data-rt-'+family+'-styles';let r=resolve('<template><p :'+attribute+'="links">Text</p></template>');assert.equal(linked.plan(r,{type:'apply'+title+'Style',width:0,property},style).refused,true);r=resolve();assert.equal(linked.plan(r,{type:'apply'+title+'Style',width:0,property,fileHash:'stale'},style).refused,true);const source=after(linked.plan(r,{type:'apply'+title+'Style',width:0,property},style),r.source),marker=source.match(new RegExp(attribute+'="[^"]*"'))[0];assert.equal(linked.planFile('/app/App.vue','App.vue','<template><Widget '+marker+'/></template>',style).refused,true);assert.equal(linked.planFile('/app/App.vue','App.vue','<template><template><p '+marker+'>Hidden</p></template></template>',style).refused,true);
 });
}
test('Vue effect styles preserve hidden Display P3 shadows and reset visibility overrides',()=>{
 const S=require('../shell/shadow-visibility.js'),linked=factory.create('effect',adapter),shadow={x:2,y:4,blur:8,spread:0,color:'color(display-p3 0.2 0.4 0.6 / 0.75)',inset:false,hidden:true},style={id:'11111111-1111-4111-8111-111111111111',name:'Hidden shadow',properties:S.write([shadow])};
 let source=after(linked.plan(resolve(),{type:'applyEffectStyle',width:768},style),original);assert.deepEqual(adapter.describe(resolve(source)).cssRules[768],style.properties);
 source=after(adapter.planOp(resolve(source),{type:'setCSS',width:768,changes:S.write([{...shadow,hidden:false}])}),source);const local=adapter.describe(resolve(source)).cssRules[768];source=after(linked.plan(resolve(source),{type:'refreshEffectStyle',width:768},{...style,properties:S.write([{...shadow,x:19}])}),source);assert.deepEqual(adapter.describe(resolve(source)).cssRules[768],local);assert.deepEqual(linked.describe(resolve(source)).effectStyleOverrides[768],['box-shadow']);source=after(linked.plan(resolve(source),{type:'resetEffectStyle',width:768},style),source);assert.deepEqual(adapter.describe(resolve(source)).cssRules[768],style.properties);assert.deepEqual(linked.describe(resolve(source)).effectStyleOverrides[768],[]);
});
