'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const adapter=require('../src/adapters/vue.cjs'),linked=require('../src/vue-linked-styles.cjs').create('variable',adapter),selection=require('../src/variable-selection.cjs'),{SourceHistory}=require('../src/history.cjs'),{id,model}=require('./fixtures/vue-variable-model.cjs');
const original='<script setup>const count=1;</script><template><main><p :title="String(count)" @click="count++">Hello {{ count }}</p><p>Second</p></main></template><style scoped>p{margin:0}</style>';
function resolve(source=original,file='/app/App.vue'){const relPath=path.basename(file),elements=adapter.collect(source,relPath).elements;return {source,file,relPath,elements,element:elements.find(e=>e.tag==='p'),hash:adapter.contentHash(source)};}
function after(result,source){assert.equal(result.ok,true,result.reason);return result.edits[0]?.after||source;}
test('Vue variables preserve aliases, responsive modes, numeric units and source expressions',()=>{
 let source=original;for(const [property,binding,width]of [['color',{id:id(6)},0],['color',{id:id(6),modes:{[id(1)]:id(3)}},768],['padding',{id:id(5),unit:'px'},0]])source=after(linked.plan(resolve(source),{type:'applyVariable',property,binding,width},model()),source);let info=adapter.describe(resolve(source));assert.equal(info.variables,true);assert.equal(info.cssRules[0].color,'#123456ff');assert.equal(info.cssRules[768].color,'#cc3300ff');assert.equal(info.cssRules[0].padding,'12px');assert.match(source,/@click="count\+\+"/);assert.match(source,/Hello \{\{ count \}\}/);
 source=after(linked.plan(resolve(source),{type:'removeVariable',property:'color',width:768}),source);info=adapter.describe(resolve(source));assert.equal(info.variableLinks[768],undefined);assert.equal(info.cssRules[768],undefined);assert.equal(info.cssRules[0].color,'#123456ff');const rules=info.cssRules;source=after(linked.plan(resolve(source),{type:'detachVariable',property:'padding',width:0}),source);assert.deepEqual(adapter.describe(resolve(source)).cssRules,rules);
});
test('Vue variable refresh preserves local overrides and selection reset keeps distinct modes',()=>{
 const library=model();let source=original,r=resolve(),ids=r.elements.filter(e=>e.tag==='p').map(e=>e.id);
 for(let i=0;i<ids.length;i++){r=resolve(source);r.element=r.elements.find(e=>e.id===ids[i]);source=after(linked.plan(r,{type:'applyVariable',property:'color',width:0,binding:{id:id(6),modes:i?{[id(1)]:id(3)}:{}}},library),source);}
 r=resolve(source);source=after(adapter.planOp(r,{type:'setCSSSelection',ids,fileHash:r.hash,width:0,property:'color',value:'#00ff00'}),source);const overridden=source;library.variables[0].values[id(2)]='#abcdef';source=after(linked.planFile(r.file,r.relPath,source,library),source);r=resolve(source);assert.equal(adapter.describe(r).cssRules[0].color,'#00ff00');const reset=selection.plan(r,{type:'resetVariableSelection',ids,fileHash:r.hash,property:'color',width:0},library,adapter);assert.equal(reset.ok,true,reset.reason);assert.deepEqual(reset.selection.map(info=>info.cssRules[0].color),['#abcdefff','#cc3300ff']);assert.notEqual(reset.edits[0].after,overridden);
});
test('Vue collection updates commit unvisited sources and catalog atomically and undo includes stylesheet revisions',t=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'retouch-vue-vars-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const library=require('../src/variable-library.cjs'),initial=library.planChange(root,{type:'replace',revision:null,library:model()});library.commitPlan(root,initial);
 for(const name of ['App.vue','Unvisited.vue']){const file=path.join(root,name);fs.writeFileSync(file,after(linked.plan(resolve(original.replace('<main>','<main :style="theme">'),file),{type:'applyVariable',property:'color',width:0,binding:{id:id(6)}},model()),original));}
 const snapshot=()=>Object.fromEntries(['App.vue','Unvisited.vue','.retouch/variables.json'].map(name=>[name,fs.readFileSync(path.join(root,name),'utf8')])),before=snapshot(),next=model();next.variables[0].values[id(2)]='#abcdef';const plan=require('../src/variable-update.cjs').plan(root,{type:'replace',revision:library.read(root).revision,library:next},'vue',adapter);assert.equal(plan.ok,true,plan.reason);assert.equal(plan.updated,2);assert.deepEqual(snapshot(),before);const history=new SourceHistory(),result=history.commit(root,plan);assert.equal(result.ok,true,result.reason);const changed=snapshot(),undone=history.apply(root,'undo',result.undoId,adapter);assert.equal(undone.ok,true);assert.deepEqual(snapshot(),before);const manifest=require('../src/history-render-revisions.cjs')(root,undone.edits,adapter);assert.equal(manifest.renderer,'vue');assert.equal(manifest.groups.length,2);assert.ok(manifest.groups.every(group=>group.css.property==='--retouch-css-revision'));assert.equal(history.apply(root,'redo',result.undoId,adapter).ok,true);assert.deepEqual(snapshot(),changed);
 next.variables=[];const refused=require('../src/variable-update.cjs').plan(root,{type:'replace',revision:library.read(root).revision,library:next},'vue',adapter);assert.equal(refused.refused,true);assert.deepEqual(snapshot(),changed);
});
test('Vue variable bindings refuse computed metadata and unsupported types without edits',()=>{
 const r=resolve('<template><p :data-rt-variables="links">Text</p></template>');assert.equal(linked.plan(r,{type:'applyVariable',property:'color',width:0,binding:{id:id(4)}},model()).refused,true);
 for(const op of [{property:'color',binding:{id:id(5)}},{property:'padding',binding:{id:id(5),unit:''}},{property:'color',binding:{id:id(4)},fileHash:'stale'}])assert.equal(linked.plan(resolve(),{type:'applyVariable',width:0,...op},model()).refused,true);
});
