'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{create}=require('../scripts/notarize.cjs');
const id='12345678-1234-1234-1234-123456789abc';
function fixture(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-notary-')),app=path.join(root,'Retouch.app'),out=path.join(root,'out'),calls=[];fs.mkdirSync(app);let response={id,status:'In Progress'},uploadError=false,signature='Authority=Developer ID Application: Example\nTimestamp=Sep 14, 2026\nCodeDirectory=v=20500 flags=0x10000(runtime)';
 const api=create({verify:()=>({sourceCommit:'abc'}),run(command,args){calls.push([command,args]);if(command==='codesign')return {stdout:'',stderr:signature};if(command==='ditto'){fs.writeFileSync(args.at(-1),'signed archive');return {stdout:'',stderr:''};}if(args[1]==='submit'&&uploadError)throw Error('connection lost');return {stdout:JSON.stringify(response),stderr:''};}});
 try{fn({app,out,api,calls,setResponse:value=>response=value,failUpload:()=>uploadError=true,adhoc:()=>signature='Signature=adhoc'});}finally{fs.rmSync(root,{recursive:true,force:true});}}
test('submission retains exact bytes and status polls the same job without uploading again',()=>fixture(({app,out,api,calls,setResponse})=>{const first=api.submit(app,out,'profile with spaces');assert.equal(first.submissionId,id);assert.equal(api.status(out).appleStatus,'In Progress');setResponse({id,status:'Accepted'});assert.equal(api.status(out).appleStatus,'Accepted');assert.equal(calls.filter(([,args])=>args[1]==='submit').length,1);assert.throws(()=>api.submit(app,out,'profile'),/already exists/);assert.equal(fs.readFileSync(path.join(out,'submission.zip'),'utf8'),'signed archive');assert.equal(fs.existsSync(path.join(out,'Retouch.app')),true);}));
test('ambiguous upload failure persists evidence and refuses automatic resubmission',()=>fixture(({app,out,api,failUpload,calls})=>{failUpload();assert.throws(()=>api.submit(app,out,'profile'),/connection lost/);assert.equal(JSON.parse(fs.readFileSync(path.join(out,'notarization.json'))).phase,'submission-unknown');assert.throws(()=>api.submit(app,out,'profile'),/already exists/);assert.throws(()=>api.status(out),/No resumable/);assert.equal(calls.filter(([,args])=>args[1]==='submit').length,1);}));
test('archive tampering prevents remote polling',()=>fixture(({app,out,api,calls})=>{api.submit(app,out,'profile');fs.appendFileSync(path.join(out,'submission.zip'),'changed');const count=calls.length;assert.throws(()=>api.status(out),/archive changed/);assert.equal(calls.length,count);}));
test('mismatched Apple job cannot record acceptance',()=>fixture(({app,out,api,setResponse})=>{api.submit(app,out,'profile');setResponse({id:'aaaaaaaa-1234-1234-1234-123456789abc',status:'Accepted'});assert.throws(()=>api.status(out),/Unexpected Apple/);assert.equal(JSON.parse(fs.readFileSync(path.join(out,'notarization.json'))).phase,'submitted');}));
test('ad hoc signature rejected before packaging or network access',()=>fixture(({app,out,api,adhoc,calls})=>{adhoc();assert.throws(()=>api.submit(app,out,'profile'),/Developer ID/);assert.equal(calls.length,1);assert.deepEqual(fs.readdirSync(out),['Retouch.app']);}));
test('competing lock remains intact and path overlap is rejected',()=>fixture(({app,out,api,calls})=>{fs.mkdirSync(out);fs.writeFileSync(path.join(out,'.notarization.lock'),'owner');assert.throws(()=>api.submit(app,out,'profile'),/Another notarization/);assert.equal(fs.readFileSync(path.join(out,'.notarization.lock'),'utf8'),'owner');assert.throws(()=>api.submit(app,app,'profile'),/must be separate/);assert.equal(calls.length,0);}));
