'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{create}=require('../scripts/notarize.cjs');
const id='12345678-1234-1234-1234-123456789abc';
function fixture(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'retouch-notary-')),app=path.join(root,'Retouch.app'),out=path.join(root,'out'),calls=[];fs.mkdirSync(app);let response={id,status:'In Progress'},uploadError=false,failure=null,logOverride=null,signature='Authority=Developer ID Application: Example\nTimestamp=Sep 14, 2026\nCodeDirectory=v=20500 flags=0x10000(runtime)';
 const api=create({verify:()=>({sourceCommit:'abc'}),run(command,args){calls.push([command,args]);if(failure&&failure(command,args))throw Error('Injected command failure');if(command==='codesign')return {stdout:'',stderr:signature};if(command==='ditto'){if(args[0]==='-x'){fs.mkdirSync(path.join(args.at(-1),'Retouch.app'));fs.writeFileSync(path.join(args.at(-1),'Retouch.app','payload'),'submitted');}else fs.writeFileSync(args.at(-1),fs.existsSync(path.join(args.at(-2),'ticket'))?'stapled archive':'signed archive');return {stdout:'',stderr:''};}if(command==='xcrun'&&args[0]==='stapler'&&args[1]==='staple')fs.writeFileSync(path.join(args[2],'ticket'),'ticket');if(command==='xcrun'&&args[1]==='log')return {stdout:JSON.stringify(logOverride||{jobId:id,status:response.status,issues:null}),stderr:''};if(args[1]==='submit'&&uploadError)throw Error('connection lost');return {stdout:JSON.stringify(response),stderr:''};}});
 try{fn({app,out,api,calls,setResponse:value=>response=value,failUpload:()=>uploadError=true,adhoc:()=>signature='Signature=adhoc',setFailure:value=>failure=value,setLog:value=>logOverride=value});}finally{fs.rmSync(root,{recursive:true,force:true});}}
test('submission retains exact bytes and status polls the same job without uploading again',()=>fixture(({app,out,api,calls,setResponse})=>{const first=api.submit(app,out,'profile with spaces');assert.equal(first.submissionId,id);assert.equal(api.status(out).appleStatus,'In Progress');setResponse({id,status:'Accepted'});assert.equal(api.status(out).appleStatus,'Accepted');assert.equal(calls.filter(([,args])=>args[1]==='submit').length,1);assert.throws(()=>api.submit(app,out,'profile'),/already exists/);assert.equal(fs.readFileSync(path.join(out,'submission.zip'),'utf8'),'signed archive');assert.equal(fs.existsSync(path.join(out,'Retouch.app')),true);}));
test('ambiguous upload failure persists evidence and refuses automatic resubmission',()=>fixture(({app,out,api,failUpload,calls})=>{failUpload();assert.throws(()=>api.submit(app,out,'profile'),/connection lost/);assert.equal(JSON.parse(fs.readFileSync(path.join(out,'notarization.json'))).phase,'submission-unknown');assert.throws(()=>api.submit(app,out,'profile'),/already exists/);assert.throws(()=>api.status(out),/No resumable/);assert.equal(calls.filter(([,args])=>args[1]==='submit').length,1);}));
test('archive tampering prevents remote polling',()=>fixture(({app,out,api,calls})=>{api.submit(app,out,'profile');fs.appendFileSync(path.join(out,'submission.zip'),'changed');const count=calls.length;assert.throws(()=>api.status(out),/archive changed/);assert.equal(calls.length,count);}));
test('mismatched Apple job cannot record acceptance',()=>fixture(({app,out,api,setResponse})=>{api.submit(app,out,'profile');setResponse({id:'aaaaaaaa-1234-1234-1234-123456789abc',status:'Accepted'});assert.throws(()=>api.status(out),/Unexpected Apple/);assert.equal(JSON.parse(fs.readFileSync(path.join(out,'notarization.json'))).phase,'submitted');}));
test('ad hoc signature rejected before packaging or network access',()=>fixture(({app,out,api,adhoc,calls})=>{adhoc();assert.throws(()=>api.submit(app,out,'profile'),/Developer ID/);assert.equal(calls.length,1);assert.deepEqual(fs.readdirSync(out),['Retouch.app']);}));
test('competing lock remains intact and path overlap is rejected',()=>fixture(({app,out,api,calls})=>{fs.mkdirSync(out);fs.writeFileSync(path.join(out,'.notarization.lock'),'owner');assert.throws(()=>api.submit(app,out,'profile'),/Another notarization/);assert.equal(fs.readFileSync(path.join(out,'.notarization.lock'),'utf8'),'owner');assert.throws(()=>api.submit(app,app,'profile'),/must be separate/);assert.equal(calls.length,0);}));

test('finish waits without stapling or publishing while Apple processes the job',()=>fixture(({app,out,api,calls})=>{api.submit(app,out,'profile');assert.equal(api.finish(out).pending,true);assert.equal(fs.existsSync(path.join(out,'distribution')),false);assert.equal(calls.some(([,args])=>args[0]==='stapler'),false);}));
test('finish packages stapled submitted bytes and records a distinct final checksum',()=>fixture(({app,out,api,setResponse,calls})=>{api.submit(app,out,'profile');fs.writeFileSync(path.join(out,'Retouch.app','payload'),'changed independently');setResponse({id,status:'Accepted'});const result=api.finish(out);assert.notEqual(result.sha256,result.submittedSha256);assert.equal(fs.readFileSync(path.join(out,'distribution','Retouch.app','payload'),'utf8'),'submitted');assert.equal(fs.readFileSync(path.join(out,'distribution','Retouch-mac.zip'),'utf8'),'stapled archive');assert.equal(result.nativeLaunch,'not tested');assert.equal(calls.filter(([,args])=>args[1]==='submit').length,1);assert.equal(fs.existsSync(path.join(out,'Retouch.app','ticket')),false);}));
test('Apple rejection preserves the log and old distribution',()=>fixture(({app,out,api,setResponse})=>{api.submit(app,out,'profile');fs.mkdirSync(path.join(out,'distribution'));fs.writeFileSync(path.join(out,'distribution','old'),'old');setResponse({id,status:'Invalid'});assert.throws(()=>api.finish(out),/Apple rejected/);assert.equal(JSON.parse(fs.readFileSync(path.join(out,'apple-log.json'))).status,'Invalid');assert.equal(fs.readFileSync(path.join(out,'distribution','old'),'utf8'),'old');}));
test('stapler and Gatekeeper failures preserve prior outputs and allow clean retries',()=>{for(const target of ['staple','validate','spctl'])fixture(({app,out,api,setResponse,setFailure,calls})=>{api.submit(app,out,'profile');fs.mkdirSync(path.join(out,'distribution'));fs.writeFileSync(path.join(out,'distribution','old'),'old');setResponse({id,status:'Accepted'});setFailure((command,args)=>command===target||(command==='xcrun'&&args[0]==='stapler'&&args[1]===target));assert.throws(()=>api.finish(out),/Injected/);assert.equal(fs.readFileSync(path.join(out,'distribution','old'),'utf8'),'old');assert.equal(fs.readdirSync(out).some(name=>name.startsWith('.notarization-finish-')),false);setFailure(null);api.finish(out);assert.equal(fs.existsSync(path.join(out,'distribution','old')),false);assert.equal(calls.filter(([,args])=>args[1]==='submit').length,1);});});
test('inconsistent approval log or Apple checksum cannot publish',()=>{for(const log of [{jobId:'wrong',status:'Accepted'},{jobId:id,status:'Invalid'},{jobId:id,status:'Accepted',sha256:'0'.repeat(64)}])fixture(({app,out,api,setResponse,setLog})=>{api.submit(app,out,'profile');setResponse({id,status:'Accepted'});setLog(log);assert.throws(()=>api.finish(out),/does not match/);assert.equal(fs.existsSync(path.join(out,'distribution')),false);});});
test('final archive verification failure cannot replace the previous distribution',()=>fixture(({app,out,api,setResponse,setFailure})=>{api.submit(app,out,'profile');fs.mkdirSync(path.join(out,'distribution'));fs.writeFileSync(path.join(out,'distribution','old'),'old');setResponse({id,status:'Accepted'});setFailure((command,args)=>command==='spctl'&&args.at(-1).includes('archive-check'));assert.throws(()=>api.finish(out),/Injected/);assert.equal(fs.readFileSync(path.join(out,'distribution','old'),'utf8'),'old');assert.equal(fs.readdirSync(out).some(name=>name.startsWith('.notarization-finish-')),false);}));
