(function(){
 'use strict';
 const trigger=document.getElementById('quickActions');let dialog,context,contextOpener,contextObserver,contextPreview;
 const enabled=row=>row?.element?.isConnected&&!row.element.matches(':disabled')&&!row.element.hidden&&!row.element.closest('[inert]')&&(!row.available||row.available());
 function run(id){const row=commands().find(item=>item.id===id);if(!enabled(row))return false;closeContext();if(row.run)row.run();else row.element.click();return true;}
 function closeContext(restore=false){contextPreview?.(null);contextPreview=null;contextObserver?.disconnect();contextObserver=null;context?.remove();context=null;if(restore&&contextOpener?.isConnected)contextOpener.focus();contextOpener=null;}
 function contextMenu({x,y,opener,layerChoices=[],onLayerPreview,onLayerError=console.error,canSelectLayer=()=>true}){
  closeContext();if(document.querySelector('dialog[open]'))return;
  contextOpener=opener;contextPreview=onLayerPreview;const menu=document.createElement('div');context=menu;menu.className='rt-context-menu';menu.setAttribute('role','menu');menu.setAttribute('aria-label','Canvas actions');
  const mod=/Mac|iPhone|iPad/.test(navigator.platform)?'⌘':'Ctrl+',shift=/Mac|iPhone|iPad/.test(navigator.platform)?'⇧':'Shift+';
  const maskShortcut=/Mac|iPhone|iPad/.test(navigator.platform)?'⌃⌘M':'Ctrl+Alt+M';
  const shortcuts={'component-copy-properties':mod+(/Mac|iPhone|iPad/.test(navigator.platform)?'⌥':'Alt+')+'C','component-paste-properties':mod+(/Mac|iPhone|iPad/.test(navigator.platform)?'⌥':'Alt+')+'V','shape-scale':'K','layer-groupSelection':mod+'G','layer-frameSelection':mod+(/Mac|iPhone|iPad/.test(navigator.platform)?'⌥':'Alt+')+'G','layer-removeFrame':mod+shift+'G','mask-create':maskShortcut,'mask-release':maskShortcut,'flip-x':shift+'H','flip-y':shift+'V','layer-before':mod+'[','layer-after':mod+']','layer-first':mod+shift+'[','layer-last':mod+shift+']','layer-copyElement':mod+'C','layer-pasteElement':mod+'V','layer-duplicateElement':mod+'D','rename-layer':'F2','layer-deleteElement':'Delete',undoBtn:mod+'Z',redoBtn:mod+shift+'Z','selection-visibility':mod+shift+'H','layer-lockSelection':mod+shift+'L','layer-unlockSelection':mod+shift+'L','navigate-parent':shift+'Enter','navigate-child':'Enter','navigate-next':'Tab','navigate-previous':shift+'Tab',zoomSelection:shift+'2','export-selection':mod+shift+'E'};
  const ids=['undoBtn','redoBtn',null,'layer-copyElement','layer-pasteElement','layer-duplicateElement','rename-layer','textInlineEdit','component-view','component-definition','component-detach','component-copy-properties','component-paste-properties',null,'shape-scale','flip-x','flip-y','selection-visibility','layer-lockSelection','layer-unlockSelection',null,'navigate-parent','navigate-child','navigate-next','navigate-previous','navigate-siblings','zoomSelection','export-selection',null,'layer-insertText','layer-insertFrame','layer-groupSelection','layer-frameSelection','layer-removeFrame','layer-reparentElement',null,'mask-create','mask-edit','mask-back','mask-release','mask-outlines',null,'layer-before','layer-after','layer-first','layer-last','layer-deleteElement'];
  const rows=commands();for(const id of ids){if(id===null){const separator=document.createElement('div');separator.setAttribute('role','separator');menu.append(separator);continue;}const row=rows.find(row=>row.id===id);if(!row)continue;const button=document.createElement('button');button.type='button';button.setAttribute('role','menuitem');button.tabIndex=-1;button.dataset.actionId=id;button.hidden=!row.element;button.setAttribute('aria-label',row.label);const label=document.createElement('span');label.className='context-label';label.textContent=row.label;button.append(label);if(shortcuts[id]){const hint=document.createElement('kbd');hint.setAttribute('aria-hidden','true');hint.textContent=shortcuts[id];button.append(hint);}button.disabled=!enabled(row);if(button.disabled)button.title=row.reason||'Unavailable';button.onclick=()=>{const latest=commands().find(item=>item.id===id);if(!enabled(latest))return;closeContext();if(latest.run)latest.run();else latest.element.click();};menu.append(button);}
  let layerMenu=null,layerTrigger=null;
  const hideLayers=(focus=false)=>{layerMenu?.remove();layerMenu=null;layerTrigger?.setAttribute('aria-expanded','false');onLayerPreview?.(null);if(focus)layerTrigger?.focus();};
  if(layerChoices.length){
    layerTrigger=document.createElement('button');layerTrigger.type='button';layerTrigger.tabIndex=-1;layerTrigger.setAttribute('role','menuitem');layerTrigger.setAttribute('aria-haspopup','menu');layerTrigger.setAttribute('aria-expanded','false');layerTrigger.textContent='Select layer';const arrow=document.createElement('span');arrow.textContent='›';arrow.setAttribute('aria-hidden','true');layerTrigger.append(arrow);menu.prepend(layerTrigger);
    const showLayers=(focus=false)=>{
      if(!canSelectLayer())return;if(layerMenu){if(focus)layerMenu.querySelector('button')?.focus();return;}
      layerMenu=document.createElement('div');layerMenu.className='rt-context-menu rt-layer-menu';layerMenu.id='context-layer-choices';layerTrigger.setAttribute('aria-controls',layerMenu.id);layerMenu.setAttribute('role','menu');layerMenu.setAttribute('aria-label','Select layer');layerTrigger.setAttribute('aria-expanded','true');
      for(const choice of layerChoices){if(!choice.el.isConnected)continue;const button=document.createElement('button');button.type='button';button.tabIndex=-1;button.setAttribute('role','menuitem');button.setAttribute('aria-label',choice.label+(choice.locked?' · Locked':''));button.className='context-layer-choice';button.dataset.layerKind=choice.kind;button.title=choice.label;const label=document.createElement('span');label.textContent=choice.label;button.append(label);if(choice.locked){const lock=document.createElement('span');lock.textContent='Locked';lock.className='context-layer-lock';button.append(lock);}
        const preview=()=>onLayerPreview?.(choice.el.isConnected?choice.el:null);button.onpointerenter=preview;button.onfocus=preview;button.onclick=()=>{if(!canSelectLayer()||!choice.el.isConnected)return;closeContext();Promise.resolve(choice.run()).catch(onLayerError);};layerMenu.append(button);
      }
      menu.append(layerMenu);const anchor=layerTrigger.getBoundingClientRect(),bounds=layerMenu.getBoundingClientRect(),right=menu.getBoundingClientRect().right;
      layerMenu.style.left=Math.max(4,Math.min(right+bounds.width<=innerWidth-4?right:menu.getBoundingClientRect().left-bounds.width,innerWidth-bounds.width-4))+'px';layerMenu.style.top=Math.max(4,Math.min(anchor.top,innerHeight-bounds.height-4))+'px';
      if(focus)layerMenu.querySelector('button')?.focus();
    };
    layerTrigger.onclick=()=>showLayers(true);layerTrigger.onpointerenter=()=>showLayers();layerTrigger.onkeydown=event=>{if(event.key==='ArrowRight'){event.preventDefault();event.stopPropagation();showLayers(true);}};
    menu.addEventListener('pointerover',event=>{if(event.target.closest('button[data-action-id]'))hideLayers();});
  }
  menu.addEventListener('scroll',event=>{if(event.target===menu)hideLayers();});
  const refresh=()=>{const latest=commands();for(const button of menu.querySelectorAll('button[data-action-id]')){const row=latest.find(item=>item.id===button.dataset.actionId);button.hidden=!row?.element;if(!row)continue;button.disabled=!enabled(row);button.setAttribute('aria-label',row.label);button.querySelector('.context-label').textContent=row.label;button.title=button.disabled?row.reason||'Unavailable':'';}};
  contextObserver=new MutationObserver(refresh);for(const id of ['layersPanel','panelBody','toolbar']){const target=document.getElementById(id);if(target)contextObserver.observe(target,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled','hidden','inert','aria-selected','title']});}
  document.body.append(menu);const rect=menu.getBoundingClientRect();menu.style.left=Math.max(4,Math.min(x,innerWidth-rect.width-4))+'px';menu.style.top=Math.max(4,Math.min(y,innerHeight-rect.height-4))+'px';
  menu.addEventListener('keydown',event=>{const current=event.target.closest('[role=menu]')||menu,buttons=[...current.querySelectorAll('button:not(:disabled):not([hidden])')].filter(button=>button.closest('[role=menu]')===current),index=buttons.indexOf(document.activeElement);if(current===layerMenu&&['ArrowLeft','Escape'].includes(event.key)){event.preventDefault();event.stopPropagation();hideLayers(true);return;}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();event.stopPropagation();buttons[event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowUp'?-1:1)+buttons.length)%buttons.length]?.focus();}else if(['Escape','Tab'].includes(event.key)){event.preventDefault();event.stopPropagation();closeContext(true);}});menu.querySelector('button:not(:disabled):not([hidden])')?.focus();
 }
 document.addEventListener('pointerdown',event=>{if(context&&!context.contains(event.target))closeContext();},true);
 window.addEventListener('blur',()=>closeContext());window.addEventListener('resize',()=>closeContext());
 function commands(){
  const button=(id,label,keywords='',reason='Finish the current operation first.')=>({id,label,keywords,element:document.getElementById(id),reason});
  const rows=[button('exportScreen','Export screen','png jpeg jpg image download screenshot'),button('manageCanvasGuides','Manage guides','canvas ruler saved positions'),button('addCanvasGuide','Add guide','canvas ruler position coordinates'),button('toggleRulers','Toggle rulers','canvas coordinates measurement'),button('undoBtn','Undo last edit','history revert','No edit to undo, or an edit is still in progress.'),button('redoBtn','Redo last edit','history restore','No edit to redo, or an edit is still in progress.'),button('screenUndo','Undo preview size','screen viewport history revert','No preview size change to undo.'),button('screenRedo','Redo preview size','screen viewport history restore','No preview size change to redo.'),button('screenRotate','Rotate preview size','screen viewport orientation landscape portrait'),button('previewBreakpoint','Preview this breakpoint','responsive scope matching screen size'),button('compareBreakpoint','Compare this breakpoint','responsive scope matching screen side by side'),button('compareBreakpointBoundary','Compare across breakpoint','responsive boundary before after screen side by side'),button('fitScreen','Fit screen','zoom canvas'),button('zoomSelection','Zoom to selection','focus layer','Select an editable layer first.'),button('canvasHand','Toggle Hand tool','pan canvas'),button('compareScreens','Toggle screen comparisons','responsive phone tablet desktop'),button('toggleLayers','Toggle Layers panel','sidebar tree'),button('toggleInspector','Toggle Inspector panel','properties styles sidebar'),button('componentLibrary','Browse project components','library instances'),button('variableLibrary','Browse variable collections','variables tokens design system'),button('modeBtn','Toggle edit / interact mode','preview navigation')].filter(row=>row.element&&!row.element.hidden);
  if(window.RetouchScreenExport)rows.push({id:'export-selection',label:'Export selection',keywords:'selected layers png jpeg jpg image download',element:document.getElementById('exportScreen'),available:()=>!!window.RetouchExportSelection?.().length,run:()=>window.RetouchScreenExport.open({selection:true}),reason:'Select a layer and finish the current edit first.'});
  if(document.getElementById('textInlineEdit'))rows.push(button('textInlineEdit','Edit text','format inline content text runs','Select editable text and finish the current operation first.'));
  if(window.RetouchComparisons)rows.push({id:'add-comparison-screen',label:'Add screen',keywords:'new custom named responsive comparison viewport width height',element:document.getElementById('compareScreens'),available:()=>window.RetouchComparisons.canAddScreen(),run:()=>window.RetouchComparisons.addScreen(),reason:'Remove a comparison screen to make room, or wait for screen changes to finish.'});
  const aspect=document.getElementById('screenAspect');if(aspect)rows.push(button('screenAspect',(aspect.getAttribute('aria-pressed')==='true'?'Unlock':'Lock')+' preview aspect ratio','screen proportions width height'));
  const editPreview=document.getElementById('editPreviewBreakpoint');if(editPreview)rows.push(button(editPreview.id,editPreview.textContent,'responsive breakpoint scope current preview width'));
  if(!document.getElementById('screenComparisons')?.hidden)for(const id of ['comparisonFocus','comparisonVisibility','comparisonRevealAll']){const element=document.getElementById(id);if(element)rows.push(button(id,element.getAttribute('aria-label')||element.textContent,'screen comparisons responsive',id==='comparisonRevealAll'?'Select a layer and add comparison screens first.':'Add a comparison screen first.'));}
  const pin=document.getElementById('comparisonPin');if(pin&&!document.getElementById('screenComparisons').hidden)rows.push(button(pin.id,pin.getAttribute('aria-label'),'screen comparisons responsive add pin reveal current size',pin.title));
  const restoreScreen=document.getElementById('comparisonRestore');if(restoreScreen&&!restoreScreen.closest('[hidden]'))rows.push(button(restoreScreen.id,restoreScreen.textContent,'undo remove restore screen comparison responsive',restoreScreen.title));
  for(const element of document.querySelectorAll('#screenComparisons button[data-comparison-action]'))if(!element.closest('[hidden]'))rows.push({id:element.dataset.comparisonCommand,label:element.getAttribute('aria-label'),keywords:'screen comparison responsive '+element.dataset.comparisonAction,element,reason:element.dataset.comparisonAction==='reveal'?'Select a layer that is visible on this screen.':'Finish the current operation first.'});
  const preset=document.getElementById('screenPreset'),seen=new Set();for(const option of preset.options){if(option.value==='custom')continue;const identity=option.value.replace(/^saved:/,'')+'|'+option.textContent.split(' · ')[0];if(seen.has(identity))continue;seen.add(identity);rows.push({id:'screen-'+option.value,label:'Preview: '+option.textContent,keywords:'screen size responsive viewport',element:preset,run:()=>{preset.value=option.value;preset.dispatchEvent(new Event('change',{bubbles:true}));},reason:'Screen controls are unavailable.'});}
  const scope=document.querySelector('#panelBody [aria-label="Style screen scope"]');if(scope)for(const option of scope.options)rows.push({id:'style-scope-'+option.value,label:'Style changes: '+option.textContent,keywords:'responsive breakpoint scope base all sizes',element:scope,reason:'Select an editable layer and finish the current operation first.',run:()=>{scope.value=option.value;scope.dispatchEvent(new Event('change',{bubbles:true}));}});
  for(const element of document.querySelectorAll('#layersPanel button[data-design-action]'))if(!element.hidden)rows.push({id:'layer-'+element.dataset.designAction,label:element.textContent,keywords:'selection layer '+element.dataset.designAction,element,reason:element.title||'Select a compatible layer, or finish the current edit.'});
  if(document.querySelector('#panelBody .component-section'))for(const [action,label]of [['view','View component'],['definition','Edit component definition'],['detach','Detach instance']]){const element=document.querySelector('#panelBody [data-component-action="'+action+'"]');rows.push({id:'component-'+action,label,keywords:'component instance shared main independent',element,reason:element?.title||'The component definition is loading or this operation is unavailable.'});}
  for(const element of document.querySelectorAll('#panelBody button[data-component-clipboard]'))rows.push({id:'component-'+element.dataset.componentClipboard+'-properties',label:element.textContent,keywords:'component instance clipboard properties',element,reason:'Select compatible component instances and finish the current edit.'});
  for(const element of document.querySelectorAll('#panelBody button[data-align]'))rows.push({id:'align-'+element.dataset.align,label:element.getAttribute('aria-label'),keywords:(element.dataset.distribution?'distribute spacing':'align')+' selection position',element,reason:element.dataset.distribution?'Select at least three layers and a selection or frame target.':'Select editable absolute layers and finish the current edit.'});
  for(const element of document.querySelectorAll('#panelBody button[data-flip-axis]'))rows.push({id:'flip-'+element.dataset.flipAxis,label:element.getAttribute('aria-label'),keywords:'mirror reflect transform position',element,reason:element.title||'Select a compatible layer and finish the current edit.'});
  for(const element of document.querySelectorAll('#panelBody button[data-mask-action]'))rows.push({id:'mask-'+element.dataset.maskAction,label:element.textContent,keywords:'mask alpha luminance crop clipping shape',element,reason:'Select editable mask layers and finish the current edit.'});
  rows.push(...(window.RetouchShapeTools?.commands()||[]));
  const rename=document.getElementById('layerNameInput');if(rename)rows.push({id:'rename-layer',label:'Rename layer',keywords:'name selection instance',element:rename,reason:'Finish the current edit first.',run:()=>{window.RetouchWorkspacePanels?.showInspector();rename.focus();rename.select();}});
  const propertyCommands=[
   ['vertical-text-alignment','vertical text alignment',['Vertical text alignment'],'typography top middle bottom'],
   ['text-content','text content',['Text content'],'copy label paragraph heading'],
   ['width','width',['Width (px)','Width (CSS)'],'layout dimensions'],['height','height',['Height (px)','Height (CSS)'],'layout dimensions'],['rotation','rotation',['Rotation (°)'],'position angle'],['opacity','opacity',['Opacity (%)'],'appearance transparency'],
   ['font-family','font family',['Page font'],'typography typeface'],['font-size','font size',['Font size (px)','Font size (CSS)'],'typography text'],['font-weight','font weight',['Font weight (1–1000)','Font weight (CSS)'],'typography bold'],['line-height','line height',['Line height (px)','Line height (CSS)'],'typography leading'],['letter-spacing','letter spacing',['Letter spacing (px)','Letter spacing (CSS)'],'typography tracking'],['relative-letter-spacing','relative letter spacing',['Letter spacing (%)'],'typography tracking percent'],['radius','corner radius',['Corner radius (px)','Corner radius (CSS)'],'appearance rounding']
  ];
  for(const [id,label,labels,keywords]of propertyCommands){const candidates=labels.flatMap(label=>[label,'Shared '+label,'Shared '+label.replace(' (CSS)','')]),element=candidates.map(label=>document.querySelector('#panelBody [aria-label="'+label+'"]')).find(Boolean);if(element){const shared=element.getAttribute('aria-label').startsWith('Shared ');rows.push({id:'property-'+id,label:'Edit '+(shared?'shared ':'')+label,keywords:'property inspector '+keywords,element,available:()=>!element.readOnly,reason:'Select editable layers and finish the current operation first.',run:()=>window.RetouchInspectorUI?.reveal(element)});}}
  const visibility=document.querySelector('#panelBody select[aria-label="Shared Visibility"],#panelBody select[aria-label="Visibility"],#panelBody input[aria-label="Visible layer"]');
  if(visibility){const hidden=visibility.type==='checkbox'?!visibility.checked:['hidden','collapse'].includes(visibility.value);rows.push({id:'selection-visibility',label:hidden?'Show selection':'Hide selection',keywords:'visible hidden appearance layers Command Ctrl Shift H',element:visibility,reason:'Visibility is controlled by an inline style, or editing is unavailable.',run:()=>{if(visibility.type==='checkbox')visibility.checked=hidden;else visibility.value=hidden?'visible':'hidden';visibility.dispatchEvent(new Event('change',{bubbles:true}));}});}
  if(window.RetouchLayerNavigation)for(const [direction,label]of [['parent','Select parent layer'],['child','Select child layer'],['next','Select next sibling'],['previous','Select previous sibling'],['siblings','Select sibling layers']])rows.push({id:'navigate-'+direction,label,keywords:'selection hierarchy canvas layers',element:document.getElementById('app'),available:()=>window.RetouchLayerNavigation.available(direction),run:()=>window.RetouchLayerNavigation.run(direction),reason:direction==='siblings'?'Select host layers with unlocked siblings. Component instances cannot be selected together here.':'Select one layer with an unlocked target in this direction, in Edit mode.'});
  return rows;
 }
 function open(){
  if(dialog?.open||document.querySelector('dialog[open]'))return;
  closeContext();dialog=document.createElement('dialog');dialog.className='quick-actions';dialog.setAttribute('aria-label','Actions');
  const header=document.createElement('header'),heading=document.createElement('h2'),close=document.createElement('button');heading.textContent='Actions';close.type='button';close.className='control-button';close.textContent='Close';close.onclick=()=>dialog.close();header.append(heading,close);
  const input=document.createElement('input');input.type='search';input.placeholder='Find an action…';input.setAttribute('aria-label','Search actions');input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','true');input.setAttribute('aria-controls','quickActionResults');
  const status=document.createElement('p');status.setAttribute('role','status');const list=document.createElement('div');list.id='quickActionResults';list.setAttribute('role','listbox');list.setAttribute('aria-label','Matching actions');
  dialog.append(header,input,status,list);document.body.append(dialog);let rows=[],active=-1,revision='';
  const unavailableReason=row=>row?.element?.closest('[inert]')?'Finish the current operation first.':row?.reason||'Choose an available action.';
  function highlight(){[...list.children].forEach((el,index)=>el.setAttribute('aria-selected',String(index===active)));if(active>=0){input.setAttribute('aria-activedescendant','quickAction-'+active);list.children[active]?.scrollIntoView({block:'nearest'});}else input.removeAttribute('aria-activedescendant');}
  function render(preserve=false){const previous=preserve?rows[active]?.id:null;const terms=input.value.trim().toLowerCase().split(/\s+/).filter(Boolean);const next=commands().filter(row=>terms.every(term=>(row.label+' '+row.keywords).toLowerCase().includes(term))),signature=JSON.stringify(next.map(row=>[row.id,row.label,row.owner,unavailableReason(row),enabled(row)]));if(preserve&&signature===revision&&next.every((row,index)=>row.element===rows[index]?.element))return;revision=signature;rows=next;list.replaceChildren();active=previous?rows.findIndex(row=>row.id===previous&&enabled(row)):-1;if(active<0)active=rows.findIndex(enabled);for(const [index,row]of rows.entries()){const option=document.createElement('div');option.id='quickAction-'+index;option.setAttribute('role','option');option.setAttribute('aria-disabled',String(!enabled(row)));option.textContent=row.label;if(!enabled(row)){const reason=document.createElement('small');reason.textContent=unavailableReason(row);option.append(reason);}option.onmousedown=event=>event.preventDefault();option.onclick=()=>execute(index);list.append(option);}status.textContent=rows.length?rows.length+' matching actions':'No matching actions.';highlight();}
  function execute(index){const row=rows[index];if(!enabled(row)){status.textContent=unavailableReason(row);return;}dialog.close();if(row.run)row.run();else row.element.click();}
  input.addEventListener('input',()=>render());input.addEventListener('keydown',event=>{
   if(event.isComposing)return;
   if(event.key==='Escape'){event.preventDefault();event.stopPropagation();dialog.close();return;}
   if(event.key==='Enter'){event.preventDefault();execute(active);return;}
   if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();
   const indices=rows.map((row,index)=>enabled(row)?index:-1).filter(index=>index>=0);if(!indices.length)return;
   const position=indices.indexOf(active);active=event.key==='Home'?indices[0]:event.key==='End'?indices.at(-1):indices[(position+(event.key==='ArrowDown'?1:-1)+indices.length)%indices.length];highlight();
  });
  const current=dialog,observer=new MutationObserver(()=>{if(current.open)render(true);});
  for(const id of ['layersPanel','panelBody','toolbar','screenPreset','screenUndo','screenRedo','screenAspect','screenComparisons']){const target=document.getElementById(id);if(target)observer.observe(target,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled','hidden','title','aria-pressed','aria-label','aria-selected','inert']});}
  current.addEventListener('close',()=>{observer.disconnect();current.remove();if(dialog===current)dialog=null;});current.showModal();render();input.focus();
 }
 function shortcut(event){
  if(window.RetouchPresentation?.active)return false;
  if(event.defaultPrevented||event.isComposing||event.target.isContentEditable||event.target.closest?.('input,textarea,select,[contenteditable]:not([contenteditable="false"]),[role="textbox"],[role="menu"]')||document.querySelector('dialog[open]'))return false;
  const key=event.key.toLowerCase(),mac=/Mac|iPhone|iPad/.test(navigator.platform);
  if((key==='e'||event.code==='KeyE')&&event.shiftKey&&!event.altKey&&(mac?event.metaKey&&!event.ctrlKey:event.ctrlKey&&!event.metaKey)){const row=commands().find(row=>row.id==='export-selection');if(!enabled(row))return false;event.preventDefault();event.stopPropagation();if(!event.repeat)run(row.id);return true;}
  if((key==='g'||event.code==='KeyG')&&(mac?event.metaKey&&!event.ctrlKey:event.ctrlKey&&!event.metaKey)&&!(event.altKey&&event.shiftKey)){const id=event.altKey?'layer-frameSelection':event.shiftKey?'layer-removeFrame':'layer-groupSelection',row=commands().find(row=>row.id===id);if(!enabled(row))return false;event.preventDefault();event.stopPropagation();if(!event.repeat)run(id);return true;}
  if(key==='m'&&!event.shiftKey&&(mac?event.ctrlKey&&event.metaKey&&!event.altKey:event.ctrlKey&&event.altKey&&!event.metaKey)){const rows=commands(),row=rows.find(row=>row.id==='mask-release')||rows.find(row=>row.id==='mask-create');if(!enabled(row))return false;event.preventDefault();event.stopPropagation();if(!event.repeat)run(row.id);return true;}
  if(event.altKey&&!event.shiftKey&&(mac?event.metaKey&&!event.ctrlKey:event.ctrlKey&&!event.metaKey)&&['KeyC','KeyV'].includes(event.code)){const id=event.code==='KeyC'?'component-copy-properties':'component-paste-properties',row=commands().find(row=>row.id===id);if(!enabled(row))return false;event.preventDefault();event.stopPropagation();if(!event.repeat)run(id);return true;}
  if(event.altKey)return false;
  if(event.shiftKey&&(key!=='l'||event.metaKey||event.ctrlKey))return false;
  if(event.metaKey||event.ctrlKey){if(key!=='k')return false;event.preventDefault();event.stopPropagation();open();return true;}
  const preset={r:'rectangle',o:'ellipse',l:event.shiftKey?'arrow':'line',p:'pen',v:'move',k:'scale',t:'text'}[key];if(!preset)return false;
  const rows=commands(),row=['pen','move','scale','text'].includes(preset)?rows.find(row=>row.id==='shape-'+preset):rows.find(row=>row.id==='shape-draw-'+preset)||rows.find(row=>row.id==='shape-add-'+preset);
  if(!enabled(row))return false;event.preventDefault();event.stopPropagation();if(!event.repeat)run(row.id);return true;
 }

 trigger.onclick=open;window.addEventListener('keydown',shortcut);window.RetouchActions={open,shortcut,contextMenu,closeContext,run};
})();
