(function(){
 'use strict';
 const trigger=document.getElementById('quickActions');let dialog;
 function commands(){
  const button=(id,label,keywords='',reason='Finish the current operation first.')=>({id,label,keywords,element:document.getElementById(id),reason});
  const rows=[button('undoBtn','Undo last edit','history revert','No edit to undo, or an edit is still in progress.'),button('redoBtn','Redo last edit','history restore','No edit to redo, or an edit is still in progress.'),button('screenUndo','Undo preview size','screen viewport history revert','No preview size change to undo.'),button('screenRedo','Redo preview size','screen viewport history restore','No preview size change to redo.'),button('screenRotate','Rotate preview size','screen viewport orientation landscape portrait'),button('fitScreen','Fit screen','zoom canvas'),button('zoomSelection','Zoom to selection','focus layer','Select an editable layer first.'),button('canvasHand','Toggle Hand tool','pan canvas'),button('compareScreens','Toggle screen comparisons','responsive phone tablet desktop'),button('toggleLayers','Toggle Layers panel','sidebar tree'),button('toggleInspector','Toggle Inspector panel','properties styles sidebar'),button('componentLibrary','Browse project components','library instances'),button('variableLibrary','Browse variable collections','variables tokens design system'),button('modeBtn','Toggle edit / interact mode','preview navigation')].filter(row=>row.element&&!row.element.hidden);
  const aspect=document.getElementById('screenAspect');if(aspect)rows.push(button('screenAspect',(aspect.getAttribute('aria-pressed')==='true'?'Unlock':'Lock')+' preview aspect ratio','screen proportions width height'));
  if(!document.getElementById('screenComparisons')?.hidden)for(const id of ['comparisonVisibility','comparisonRevealAll']){const element=document.getElementById(id);if(element)rows.push(button(id,element.textContent,'screen comparisons responsive',id==='comparisonRevealAll'?'Select a layer and add comparison screens first.':'Add a comparison screen first.'));}
  for(const element of document.querySelectorAll('#screenComparisons button[data-comparison-action]'))if(!element.closest('[hidden]'))rows.push({id:element.dataset.comparisonCommand,label:element.getAttribute('aria-label'),keywords:'screen comparison responsive '+element.dataset.comparisonAction,element,reason:element.dataset.comparisonAction==='reveal'?'Select a layer that is visible on this screen.':'Finish the current operation first.'});
  const preset=document.getElementById('screenPreset'),seen=new Set();for(const option of preset.options){if(option.value==='custom')continue;const identity=option.value.replace(/^saved:/,'')+'|'+option.textContent.split(' · ')[0];if(seen.has(identity))continue;seen.add(identity);rows.push({id:'screen-'+option.value,label:'Preview: '+option.textContent,keywords:'screen size responsive viewport',element:preset,run:()=>{preset.value=option.value;preset.dispatchEvent(new Event('change',{bubbles:true}));},reason:'Screen controls are unavailable.'});}
  for(const element of document.querySelectorAll('#layersPanel button[data-design-action]'))if(!element.hidden)rows.push({id:'layer-'+element.dataset.designAction,label:element.textContent,keywords:'selection layer '+element.dataset.designAction,element,reason:element.title||'Select a compatible layer, or finish the current edit.'});
  const rename=document.getElementById('layerNameInput');if(rename)rows.push({id:'rename-layer',label:'Rename layer',keywords:'name selection instance',element:rename,reason:'Finish the current edit first.',run:()=>{window.RetouchWorkspacePanels?.showInspector();rename.focus();rename.select();}});
  const visibility=document.querySelector('#panelBody select[aria-label="Shared Visibility"],#panelBody select[aria-label="Visibility"],#panelBody input[aria-label="Visible layer"]');
  if(visibility){const hidden=visibility.type==='checkbox'?!visibility.checked:['hidden','collapse'].includes(visibility.value);rows.push({id:'selection-visibility',label:hidden?'Show selection':'Hide selection',keywords:'visible hidden appearance layers Command Ctrl Shift H',element:visibility,reason:'Visibility is controlled by an inline style, or editing is unavailable.',run:()=>{if(visibility.type==='checkbox')visibility.checked=hidden;else visibility.value=hidden?'visible':'hidden';visibility.dispatchEvent(new Event('change',{bubbles:true}));}});}
  if(window.RetouchLayerNavigation)for(const [direction,label]of [['parent','Select parent layer'],['child','Select child layer'],['next','Select next sibling'],['previous','Select previous sibling']])rows.push({id:'navigate-'+direction,label,keywords:'selection hierarchy canvas layers',element:document.getElementById('app'),available:()=>window.RetouchLayerNavigation.available(direction),run:()=>window.RetouchLayerNavigation.run(direction),reason:'Select one layer with an unlocked target in this direction, in Edit mode.'});
  return rows;
 }
 function open(){
  if(dialog?.open||document.querySelector('dialog[open]'))return;
  dialog=document.createElement('dialog');dialog.className='quick-actions';dialog.setAttribute('aria-label','Actions');
  const header=document.createElement('header'),heading=document.createElement('h2'),close=document.createElement('button');heading.textContent='Actions';close.type='button';close.className='control-button';close.textContent='Close';close.onclick=()=>dialog.close();header.append(heading,close);
  const input=document.createElement('input');input.type='search';input.placeholder='Find an action…';input.setAttribute('aria-label','Search actions');input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','true');input.setAttribute('aria-controls','quickActionResults');
  const status=document.createElement('p');status.setAttribute('role','status');const list=document.createElement('div');list.id='quickActionResults';list.setAttribute('role','listbox');list.setAttribute('aria-label','Matching actions');
  dialog.append(header,input,status,list);document.body.append(dialog);let rows=[],active=-1,revision='';
  const enabled=row=>row?.element?.isConnected&&!row.element.matches(':disabled')&&!row.element.hidden&&!row.element.closest('[inert]')&&(!row.available||row.available());
  const unavailableReason=row=>row?.element?.closest('[inert]')?'Finish the current operation first.':row?.reason||'Choose an available action.';
  function highlight(){[...list.children].forEach((el,index)=>el.setAttribute('aria-selected',String(index===active)));if(active>=0){input.setAttribute('aria-activedescendant','quickAction-'+active);list.children[active]?.scrollIntoView({block:'nearest'});}else input.removeAttribute('aria-activedescendant');}
  function render(preserve=false){const previous=preserve?rows[active]?.id:null;const terms=input.value.trim().toLowerCase().split(/\s+/).filter(Boolean);const next=commands().filter(row=>terms.every(term=>(row.label+' '+row.keywords).toLowerCase().includes(term))),signature=JSON.stringify(next.map(row=>[row.id,row.label,unavailableReason(row),enabled(row)]));if(preserve&&signature===revision&&next.every((row,index)=>row.element===rows[index]?.element))return;revision=signature;rows=next;list.replaceChildren();active=previous?rows.findIndex(row=>row.id===previous&&enabled(row)):-1;if(active<0)active=rows.findIndex(enabled);for(const [index,row]of rows.entries()){const option=document.createElement('div');option.id='quickAction-'+index;option.setAttribute('role','option');option.setAttribute('aria-disabled',String(!enabled(row)));option.textContent=row.label;if(!enabled(row)){const reason=document.createElement('small');reason.textContent=unavailableReason(row);option.append(reason);}option.onmousedown=event=>event.preventDefault();option.onclick=()=>execute(index);list.append(option);}status.textContent=rows.length?rows.length+' matching actions':'No matching actions.';highlight();}
  function execute(index){const row=rows[index];if(!enabled(row)){status.textContent=unavailableReason(row);return;}dialog.close();if(row.run)row.run();else row.element.click();}
  input.addEventListener('input',()=>render());input.addEventListener('keydown',event=>{
   if(event.isComposing)return;
   if(event.key==='Escape'){event.preventDefault();event.stopPropagation();dialog.close();return;}
   if(event.key==='Enter'){event.preventDefault();execute(active);return;}
   if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();
   const indices=rows.map((row,index)=>enabled(row)?index:-1).filter(index=>index>=0);if(!indices.length)return;
   const position=indices.indexOf(active);active=event.key==='Home'?indices[0]:event.key==='End'?indices.at(-1):indices[(position+(event.key==='ArrowDown'?1:-1)+indices.length)%indices.length];highlight();
  });
  const current=dialog,observer=new MutationObserver(()=>{if(current.open)render(true);});
  for(const id of ['layersPanel','panelBody','toolbar','screenPreset','screenUndo','screenRedo','screenAspect','screenComparisons']){const target=document.getElementById(id);if(target)observer.observe(target,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled','hidden','title','aria-pressed','aria-label','aria-selected','inert']});}
  current.addEventListener('close',()=>{observer.disconnect();current.remove();if(dialog===current)dialog=null;});current.showModal();render();input.focus();
 }
 function shortcut(event){if(event.defaultPrevented||event.isComposing||!(event.metaKey||event.ctrlKey)||event.altKey||event.shiftKey||event.key.toLowerCase()!=='k'||event.target.isContentEditable||event.target.closest?.('input,textarea,select,[contenteditable]:not([contenteditable="false"]),[role="textbox"]')||document.querySelector('dialog[open]'))return false;event.preventDefault();event.stopPropagation();open();return true;}
 trigger.onclick=open;window.addEventListener('keydown',shortcut);window.RetouchActions={open,shortcut};
})();
