(function(root){
 'use strict';
 const V=()=>root.RetouchHTMLCSSValues||require('./html-css-values.js'),expanded={},mountCleanups=new Map();
 const types={blur:{label:'Blur',unit:'px',initial:'4px',max:1000},brightness:{label:'Brightness',unit:'%',initial:'100%',max:10000},contrast:{label:'Contrast',unit:'%',initial:'100%',max:10000},grayscale:{label:'Grayscale',unit:'%',initial:'100%',max:100},'hue-rotate':{label:'Hue rotation',unit:'deg',initial:'0deg',min:-10000,max:10000},invert:{label:'Invert',unit:'%',initial:'100%',max:100},opacity:{label:'Opacity',unit:'%',initial:'100%',max:100},saturate:{label:'Saturation',unit:'%',initial:'100%',max:10000},sepia:{label:'Sepia',unit:'%',initial:'100%',max:100},'drop-shadow':{label:'Drop shadow',initial:'0px 2px 4px rgba(0, 0, 0, 0.25)'}};
 function change(value,action,index,argument){
  const parsed=V().parseFilters(value);if(!parsed)throw Error('This filter stack contains unsupported values.');const stack=parsed.map(item=>item.raw);
  if(action==='add'){if(!Object.hasOwn(types,argument))throw Error('Choose a supported effect.');stack.push(argument+'('+types[argument].initial+')');}
  else{
   if(!Number.isInteger(index)||index<0||index>=stack.length)throw Error('The selected effect no longer exists.');
   if(action==='remove')stack.splice(index,1);
   else if(action==='duplicate')stack.splice(index+1,0,stack[index]);
   else if(action==='up'||action==='down'){const other=index+(action==='up'?-1:1);if(other<0||other>=stack.length)throw Error('The effect cannot move farther.');[stack[index],stack[other]]=[stack[other],stack[index]];}
   else if(action==='type'){if(!Object.hasOwn(types,argument))throw Error('Choose a supported effect.');stack[index]=argument+'('+types[argument].initial+')';}
   else if(action==='value'){if(typeof argument!=='string'||!argument.trim())throw Error('Enter an effect value.');const next=parsed[index].name+'('+argument.trim()+')',single=V().parseFilters(next);if(!single||single.length!==1||single[0].name!==parsed[index].name)throw Error('Enter a value for this effect only.');stack[index]=next;}
   else throw Error('Unsupported filter edit.');
  }
  const next=stack.join(' ')||'none';if(!V().parseFilters(next))throw Error('The effect value is unsupported or the stack exceeds 16 effects.');return next;
 }
 function dropShadow(value,index,changes){
  const stack=V().parseFilters(value);if(!stack||!Number.isInteger(index)||stack[index]?.name!=='drop-shadow')throw Error('Select a drop shadow effect.');
  if(!changes||typeof changes!=='object'||Array.isArray(changes)||!Object.keys(changes).length||Object.keys(changes).some(key=>!['x','y','blur','color'].includes(key)))throw Error('Choose a shadow offset, blur or color.');
  for(const [key,item]of Object.entries(changes))if(key==='color'?typeof item!=='string'||!V().valid('color',item):!Number.isFinite(item)||Math.abs(item)>10000||key==='blur'&&item<0)throw Error('Enter a supported shadow value.');
  const shadow={...V().parseShadows(stack[index].arg)[0],...changes};
  return change(value,'value',index,`${shadow.x}px ${shadow.y}px ${shadow.blur}px ${shadow.color}`);
 }
 function amount(filter){const type=types[filter.name];if(type.unit==='%')return parseFloat(filter.arg)*(filter.arg.endsWith('%')?1:100);if(type.unit==='deg'){const value=parseFloat(filter.arg);return filter.arg.endsWith('turn')?value*360:filter.arg.endsWith('grad')?value*.9:filter.arg.endsWith('rad')?value*180/Math.PI:value;}return parseFloat(filter.arg);}
 function mount(parent,property,value,save,{disabled=false,reset=false,model=null,saveModel=null,active=()=>true,element=null}={}){
  const I=root.RetouchInspector,d=parent.ownerDocument,prefix=property==='filter'?'Layer':'Backdrop',details=d.createElement('details'),summary=d.createElement('summary');summary.textContent=prefix+' filter stack';details.append(summary);details.open=!!expanded[property];details.ontoggle=()=>{if(details.isConnected)expanded[property]=details.open;};parent.append(details);
  if(model)value=model.map(item=>item.raw).join(' ')||'none';
  const writeModel=async next=>{if(disabled||!active())return;try{await saveModel(next);}catch(error){I.note(details,error.message,'refused');}},parsed=V().parseFilters(value),write=async next=>{if(disabled||!active())return;try{if(model&&saveModel&&next!==null){const updated=V().parseFilters(next);if(!updated)throw Error('Unsupported filter stack.');await saveModel(updated.map((item,i)=>({raw:item.raw,hidden:model[i]?.hidden??false})));}else await save(next);}catch(error){I.note(details,error.message,'refused');}},edit=(action,index,arg)=>{try{if(model&&saveModel){const next=model.map(item=>({...item}));if(action==='remove')next.splice(index,1);else if(action==='duplicate'){if(next.length>=16)throw Error('A filter stack supports up to 16 effects.');next.splice(index+1,0,{...next[index]});}else if(action==='up'||action==='down'){const other=index+(action==='up'?-1:1);[next[index],next[other]]=[next[other],next[index]];}else{const changed=V().parseFilters(change(value,action,index,arg));if(action==='add')next.push({raw:changed.at(-1).raw,hidden:false});else next[index].raw=changed[index].raw;}return writeModel(next);}return write(change(value,action,index,arg));}catch(error){I.note(details,error.message,'refused');}};
  if(!parsed)I.note(details,'This stack contains filters these controls cannot edit.');
  else{
   parsed.forEach((filter,index)=>{const group=d.createElement('fieldset'),legend=d.createElement('legend'),label=prefix+' effect '+(index+1),type=types[filter.name];group.className='filter-controls';legend.textContent=type.label;const actions=d.createElement('span');actions.className='gradient-actions';legend.append(actions);group.append(legend);
    if(model&&saveModel){const hidden=model[index].hidden,eye=I.button((hidden?'Show ':'Hide ')+label,()=>{root.RetouchPanelFocus?.queueControl(eye,(hidden?'Hide ':'Show ')+label);writeModel(model.map((item,i)=>i===index?{...item,hidden:!hidden}:item));});eye.className='control-button gradient-action';eye.setAttribute('aria-label',(hidden?'Show ':'Hide ')+label);eye.setAttribute('aria-pressed',String(!hidden));eye.innerHTML=root.RetouchBackgroundPaintUI.visibilityIcon(hidden,false);actions.append(eye);}
    I.select(group,label+' type',Object.entries(types).map(([key,item])=>[key,item.label]),filter.name,name=>edit('type',index,name)).closest('.inspector-field').querySelector(':scope > span').textContent='Type';
    if(type.unit)I.number(group,label+' '+type.label+' ('+type.unit+')',amount(filter),type.min??0,type.max,number=>edit('value',index,String(number)+type.unit)).closest('.inspector-field').querySelector(':scope > span').textContent=type.label;
    else{
     const shadow=V().parseShadows(filter.arg)[0],update=changes=>{try{write(dropShadow(value,index,changes));}catch(error){I.note(group,error.message,'refused');}};
     for(const [key,title]of [['x','X'],['y','Y'],['blur','Blur']])I.number(group,label+' Shadow '+title+' (px)',shadow[key],key==='blur'?0:-10000,10000,number=>update({[key]:number})).closest('.inspector-field').querySelector(':scope > span').textContent=title;
     const color=d.createElement('input');color.value=shadow.color;I.field(group,label+' Shadow color',color);color.oninput=()=>color.setCustomValidity('');color.onchange=()=>{if(color.disabled||!active())return;try{const next=dropShadow(value,index,{color:color.value.trim()});if(!d.defaultView.CSS.supports('color',color.value.trim()))throw Error('Enter a supported color.');write(next);}catch(error){color.setCustomValidity(error.message);color.reportValidity();}};
     color.closest('.inspector-field').querySelector(':scope > span').textContent='Color';
     if(element){const picker=root.RetouchPaintPicker;picker.mountSelectionField(color,[element],'color',undefined,undefined,()=>shadow.color);color.dataset.paintProperty='shadow-color';color.retouchHasScopedValues=()=>active();color.retouchPaintPreview=()=>{const preview=picker.propertyPreview({el:element,input:color,property});return {update:paint=>{if(color.disabled||!active())return;const next=dropShadow(value,index,{color:paint}),parsed=V().parseFilters(next);preview.update(model?root.RetouchFilterVisibility.write(property,parsed.map((item,i)=>({raw:item.raw,hidden:model[i].hidden})))[property]:next);},restore:()=>preview.restore()};};}
    }
    const action=(name,kind,path)=>{const button=I.button(name,()=>{if(button.disabled)return;const target=kind==='up'?index:kind==='down'||kind==='duplicate'?index+2:parsed.length>1?Math.min(index+1,parsed.length-1):null;if(target)root.RetouchPanelFocus?.queueControl(button,prefix+' effect '+target+' type');edit(kind,index);});button.className='control-button gradient-action';button.setAttribute('aria-label',name);button.title=name;button.innerHTML='<svg viewBox="0 0 20 20" aria-hidden="true">'+path+'</svg>';actions.append(button);return button;};if(index>0)action('Move '+label.toLowerCase()+' up','up','<path d="M5 12l5-5 5 5"/>');if(index<parsed.length-1)action('Move '+label.toLowerCase()+' down','down','<path d="M5 8l5 5 5-5"/>');const duplicate=action('Duplicate '+label.toLowerCase(),'duplicate','<rect x="7" y="7" width="9" height="9" rx="1"/><path d="M12 5V4H4v8h1"/>');duplicate.disabled=parsed.length>=16;action('Remove '+label.toLowerCase(),'remove','<path d="M5 10h10"/>');details.append(group);root.RetouchInspectorUI?.keyboardToolbar(actions,label+' actions');
   });
   let next='blur';I.select(details,'New '+prefix.toLowerCase()+' effect',Object.entries(types).map(([key,item])=>[key,item.label]),next,value=>{next=value;});const add=I.button('Add '+prefix.toLowerCase()+' effect',()=>edit('add',0,next));add.disabled=parsed.length>=16;details.append(add);
  }
  const clear=I.button('Clear '+prefix.toLowerCase()+' filters',()=>write('none'));clear.disabled=parsed?.length===0;details.append(clear);if(reset)details.append(I.button('Reset '+prefix.toLowerCase()+' filters',()=>write(null)));
  if(disabled){for(const input of details.querySelectorAll('input,select,button'))input.disabled=true;I.note(details,'An inline important filter controls this layer.');}
  if(element){const controls=[...details.querySelectorAll('input,select,button')].map(input=>[input,input.disabled,input.title]),sync=()=>{const ready=active();for(const [input,ownDisabled,title]of controls){input.disabled=ownDisabled||!ready;input.title=ready?title:'Preview this screen range to edit its filters.';}},w=element.ownerDocument.defaultView,cleanup=()=>w.removeEventListener('resize',resize),resize=()=>{if(!details.isConnected){cleanup();return;}sync();};mountCleanups.get(property)?.();mountCleanups.set(property,cleanup);w.addEventListener('resize',resize);sync();}
  I.note(details,'Filters run in order. Moving an effect can change the result.');return details;
 }
 const sharedCleanups=new Map();
 function mountSharedBlur(parent,infos,elements,scope,property,save){
  const I=root.RetouchInspector,B=root.RetouchBackgroundPaintUI,label='Shared '+(property==='filter'?'Layer':'Backdrop')+' blur (px)',own=()=>infos.map(info=>B.sourceEffect(info,scope,property)),states=()=>elements.map((el,i)=>B.filterState(infos[i],scope,el,property)),readable=()=>own().every(value=>value!==null)||B.rangeActive(input,elements[0]);
  const input=I.number(parent,label,NaN,0,1000,amount=>{if(input.disabled||!readable())return;try{const current=states(),next=current.map((state,i)=>B.filterChanges(property,root.RetouchFilterVisibility.withBlur(state.model,amount),infos[i]));if(next.every((value,i)=>JSON.stringify(value)===JSON.stringify(B.filterChanges(property,current[i].model,infos[i]))))return;Promise.resolve(save(next)).catch(error=>I.note(parent,error.message,'refused'));}catch(error){I.note(parent,error.message,'refused');}});
  input.closest('.inspector-field').querySelector(':scope > span').textContent=property==='filter'?'Blur':'Background';
  const eyeLabel='shared '+(property==='filter'?'layer':'backdrop')+' blur',participants=()=>states().flatMap(state=>(state.model||[]).filter(item=>V().parseFilters(item.raw)[0].name==='blur')),eye=I.button('Hide '+eyeLabel,()=>{if(eye.disabled||!readable())return;try{const hidden=!participants().every(item=>item.hidden),current=states(),next=current.map((state,i)=>{const model=state.model.map(item=>V().parseFilters(item.raw)[0].name==='blur'?{...item,hidden}:item);return JSON.stringify(model)===JSON.stringify(state.model)?undefined:B.filterChanges(property,model,infos[i]);});if(next.every(value=>value===undefined))return;root.RetouchPanelFocus?.queueControl(eye,(hidden?'Show ':'Hide ')+eyeLabel);Promise.resolve(save(next)).catch(error=>I.note(parent,error.message,'refused'));}catch(error){I.note(parent,error.message,'refused');}}),field=input.closest('.inspector-field'),row=parent.ownerDocument.createElement('div');row.className='property-row';field.before(row);row.append(field,eye);eye.className='background-visibility';

  const sync=()=>{const current=states(),parsed=current.map(state=>V().parseFilters(state.value)),blurs=parsed.map(stack=>stack?.filter(item=>item.name==='blur')),amounts=blurs.map(stack=>stack?.length===1?parseFloat(stack[0].arg):stack?.length===0?0:NaN),mixed=amounts.some(value=>!Number.isFinite(value)||value!==amounts[0]);input.disabled=!readable()||elements.some((el,i)=>!el.isConnected||!current[i].model||!parsed[i]||blurs[i].length>1||el.style.getPropertyPriority(property)==='important');input.title=!readable()?'Preview this screen range to preserve each layer’s existing filters.':input.disabled?'A selected filter cannot be adjusted with a single blur value.':'Preserves each layer’s other filters.';input.placeholder=mixed?'Mixed':'';if(input.ownerDocument.activeElement!==input)input.value=mixed?'':String(amounts[0]);const items=participants(),hidden=items.length>0&&items.every(item=>item.hidden),mixedVisibility=!hidden&&items.some(item=>item.hidden);eye.disabled=input.disabled||!items.length;eye.setAttribute('aria-label',(hidden?'Show ':'Hide ')+eyeLabel);eye.setAttribute('aria-pressed',mixedVisibility?'mixed':String(items.length>0&&!hidden));eye.innerHTML=B.visibilityIcon(hidden,mixedVisibility);eye.title=!items.length?'Add a blur before changing its visibility.':!readable()?'Preview this screen range to change blur visibility.':mixedVisibility?'Mixed visibility · hide existing blurs on selected layers':eye.getAttribute('aria-label');};
  const w=elements[0].ownerDocument.defaultView,cleanup=()=>w.removeEventListener('resize',resize),resize=()=>{if(!input.isConnected){cleanup();return;}sync();};sharedCleanups.get(property)?.();sharedCleanups.set(property,cleanup);w.addEventListener('resize',resize);sync();return input;
 }
 let sharedShadowType='drop';
 function mountSharedShadows(parent,infos,elements,scope,save){
  const I=root.RetouchInspector,B=root.RetouchBackgroundPaintUI,own=()=>infos.map(info=>B.sourceShadows(info,scope)),stacks=()=>{const source=own();return elements.map((el,i)=>source[i]??B.readShadows(infos[i],el));};
  const input=I.select(parent,'Shared shadow type',[['drop','Drop shadow'],['inner','Inner shadow']],sharedShadowType,value=>{sharedShadowType=value;}),row=input.closest('.inspector-field'),add=I.button('Add shared shadow',()=>{sync();if(add.disabled)return;try{const next=stacks().map((stack,i)=>B.shadowChanges([...stack,{x:0,y:4,blur:8,spread:0,color:'rgba(0, 0, 0, 0.25)',inset:input.value==='inner'}],infos[i]));Promise.resolve(save(next)).catch(error=>I.note(parent,error.message,'refused'));}catch(error){I.note(parent,error.message,'refused');}});
  row.querySelector(':scope > span').textContent='Shadow';const pair=parent.ownerDocument.createElement('div');pair.className='property-row';row.before(pair);pair.append(row,add);add.textContent='+';add.setAttribute('aria-label','Add shared shadow');add.classList.add('property-reset');
  const rowUpdates=[],actionGroups=[],editable=current=>current.every((stack,i)=>stack&&elements[i].isConnected&&elements[i].style.getPropertyPriority('box-shadow')!=='important')&&(own().every(stack=>stack!==null)||B.rangeActive(input,elements[0]));
  const initial=stacks();if(initial.every(Boolean))for(let index=0;index<Math.max(0,...initial.map(stack=>stack.length));index++){
   const group=parent.ownerDocument.createElement('fieldset'),legend=parent.ownerDocument.createElement('legend');group.className='shadow-controls';const count=initial.filter(stack=>stack[index]).length;legend.textContent='Shadow '+(index+1)+(count<elements.length?' · '+count+' of '+elements.length+' layers':'');group.append(legend);parent.append(group);
   const label='Shared Shadow '+(index+1),update=change=>{try{const current=stacks();if(!editable(current))return;const next=current.map((stack,layer)=>{if(!stack[index])return undefined;const value=B.shadowChanges(change(stack,index,layer),infos[layer]);return JSON.stringify(value)===JSON.stringify(B.shadowChanges(stack,infos[layer]))?undefined:value;});if(next.every(value=>value===undefined))return;Promise.resolve(save(next)).catch(error=>I.note(parent,error.message,'refused'));}catch(error){I.note(parent,error.message,'refused');}};
   const type=I.select(group,label+' type',[['','Mixed'],['drop','Drop shadow'],['inner','Inner shadow']],'',value=>{if(value)update((stack,i)=>stack.map((item,n)=>n===i?{...item,inset:value==='inner'}:item));});type.closest('.inspector-field').querySelector(':scope > span').textContent='Type';
   const controls=[];for(const pair of [[['x','X'],['y','Y']],[['blur','Blur'],['spread','Spread']]]){const row=parent.ownerDocument.createElement('div');row.className='property-pair';group.append(row);for(const [key,name]of pair){const field=I.number(row,label+' '+name+' (px)',NaN,key==='blur'?0:-10000,10000,value=>{if(!field.disabled)update((stack,i)=>stack.map((item,n)=>n===i?{...item,[key]:value}:item));});field.closest('.inspector-field').querySelector(':scope > span').textContent=name;controls.push([key,field]);}}
   const participants=initial.flatMap((stack,i)=>stack[index]?[i]:[]),color=parent.ownerDocument.createElement('input');color.type='text';I.field(group,label+' color',color);
   const saveColors=values=>update((stack,i,layer)=>stack.map((item,n)=>n===i?{...item,color:values[participants.indexOf(layer)]}:item));color.oninput=()=>color.setCustomValidity('');color.onchange=()=>{if(color.disabled)return;const value=color.value.trim();if(!V().valid('color',value)||participants.some(i=>!elements[i].ownerDocument.defaultView.CSS.supports('box-shadow','0px 0px '+value))){color.setCustomValidity('Enter a supported CSS shadow color.');color.reportValidity();return;}saveColors(participants.map(()=>value));};
   root.RetouchPaintPicker.mountSelectionField(color,participants.map(i=>elements[i]),'color',undefined,saveColors,i=>stacks()[participants[i]]?.[index]?.color??null);color.dataset.paintProperty='shadow-color';color.retouchHasScopedValues=()=>own().every(stack=>stack!==null);
   color.retouchPaintPreview=()=>{const previews=participants.map(i=>root.RetouchPaintPicker.shadowPreview({el:elements[i],group,shadows:B.readShadows(infos[i],elements[i])||[],index}));return {update:value=>previews.forEach(preview=>preview.update(value)),restore:()=>previews.forEach(preview=>preview.restore())};};
   B.shadowEye(color,()=>stacks().flatMap(stack=>stack?.[index]?[stack[index]]:[]),hidden=>update((stack,i)=>stack.map((item,n)=>n===i?{...item,hidden}:item)),()=>editable(stacks()),elements[0],'shared shadow '+(index+1));
   const remove=I.button('Remove shared shadow '+(index+1),()=>update((stack,i)=>stack.filter((_,n)=>n!==i)));remove.setAttribute('aria-label','Remove shared shadow '+(index+1));remove.title='Remove this shadow from layers that have it.';remove.textContent='−';remove.classList.add('property-reset');legend.append(remove);
   const actions=parent.ownerDocument.createElement('span');actions.className='gradient-actions';actionGroups.push([actions,label+' actions']);legend.append(actions);
   const specs=[['up','Move shared shadow '+(index+1)+' up','<path d="M5 12l5-5 5 5"/>',stack=>index>0&&!!stack[index],(stack,i)=>{const next=[...stack];[next[i-1],next[i]]=[next[i],next[i-1]];return next;}],['down','Move shared shadow '+(index+1)+' down','<path d="M5 8l5 5 5-5"/>',stack=>!!stack[index+1],(stack,i)=>{const next=[...stack];[next[i],next[i+1]]=[next[i+1],next[i]];return next;}],['duplicate','Duplicate shared shadow '+(index+1),'<rect x="7" y="7" width="9" height="9" rx="1"/><path d="M12 5V4H4v8h1"/>',stack=>!!stack[index]&&stack.length<16,(stack,i)=>[...stack.slice(0,i+1),{...stack[i]},...stack.slice(i+1)]]],actionButtons=[];
   for(const [action,name,icon,allowed,change]of specs){const button=I.button(name,()=>{if(button.disabled)return;root.RetouchPanelFocus?.queueControl(button,'Shared Shadow '+(action==='up'?index:index+2)+' type');update((stack,i)=>allowed(stack)?change(stack,i):stack);});button.setAttribute('aria-label',name);button.title=name;button.className='control-button gradient-action';button.innerHTML='<svg viewBox="0 0 20 20" aria-hidden="true">'+icon+'</svg>';actions.append(button);actionButtons.push([button,allowed,action]);}remove.className='control-button gradient-action';remove.innerHTML='<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M5 10h10"/></svg>';actions.append(remove);
   rowUpdates.push(current=>{const items=current.filter(Boolean).map(stack=>stack[index]).filter(Boolean),disabled=!items.length||!editable(current);type.disabled=remove.disabled=color.disabled=disabled;for(const [button,allowed,action]of actionButtons)button.disabled=disabled||(action==='duplicate'?current.some(stack=>stack?.[index]&&stack.length>=16):!current.some(stack=>stack&&allowed(stack)));if(![...actions.children].some(button=>!button.disabled&&button.tabIndex===0)){const first=[...actions.children].find(button=>!button.disabled);if(first)first.tabIndex=0;}color.parentElement.querySelector('.gradient-stop-swatch').disabled=disabled;const types=items.map(item=>item.inset?'inner':'drop');if(type.ownerDocument.activeElement!==type)type.value=types.every(value=>value===types[0])?types[0]||'':'';for(const [key,field]of controls){const values=items.map(item=>item[key]),mixed=values.some(value=>value!==values[0]);field.disabled=disabled;field.placeholder=mixed?'Mixed':'';if(field.ownerDocument.activeElement!==field)field.value=mixed||!values.length?'':String(values[0]);}});
  }
  const sync=()=>{const current=stacks(),readable=own().every(stack=>stack!==null)||B.rangeActive(input,elements[0]);add.disabled=!readable||elements.some((el,i)=>!el.isConnected||!current[i]||current[i].length>=16||el.style.getPropertyPriority('box-shadow')==='important');add.title=!readable?'Preview this screen range to preserve each layer’s existing shadows.':add.disabled?'A selected shadow stack cannot accept another shadow.':'Add a shadow to every selected layer; existing shadows stay unchanged.';input.disabled=add.disabled;rowUpdates.forEach(update=>update(current));};
  const w=elements[0].ownerDocument.defaultView,cleanup=()=>w.removeEventListener('resize',resize),resize=()=>{if(!input.isConnected){cleanup();return;}sync();};sharedCleanups.get('box-shadow')?.();sharedCleanups.set('box-shadow',cleanup);w.addEventListener('resize',resize);sync();actionGroups.forEach(([group,label])=>root.RetouchInspectorUI.keyboardToolbar(group,label));return input;
 }
 const api={change,dropShadow,amount,mount,mountSharedBlur,mountSharedShadows};if(typeof module==='object'&&module.exports)module.exports=api;else root.RetouchFilterStack=api;
})(typeof window==='object'?window:globalThis);
