(function(root){
 'use strict';
 function available(el){const css=el.ownerDocument.defaultView.getComputedStyle(el);return !['absolute','fixed'].includes(css.position)&&!['inline','contents','none'].includes(css.display)&&!['width','height','inline-size','block-size','flex','flex-grow','flex-shrink','flex-basis'].some(p=>el.style.getPropertyValue(p));}
 function changes(el,sizes){const css=el.ownerDocument.defaultView.getComputedStyle(el),parent=root.RetouchInspector.layoutParent(el),p=parent&&el.ownerDocument.defaultView.getComputedStyle(parent),result={};for(const [axis,value]of Object.entries(sizes))result[axis]=root.RetouchReactSelection.dimensionValue(css,axis,value)+'px';if(p&&/flex/.test(p.display)&&Object.hasOwn(sizes,root.RetouchLayout.layoutAxes({direction:p.flexDirection,writingMode:p.writingMode}).main))Object.assign(result,{'flex-grow':'0','flex-shrink':'0','flex-basis':'auto'});return result;}
 function control(el,save){if(!available(el))return null;const button=root.RetouchInspector.canvasTool('resize',(opener,initial)=>root.resizeFlowOnCanvas(el,opener,save,initial));button.dataset.flowResize='true';return button;}
 function mount({target,frame,canvas,control,save,current,onEnd,onError,initial=null}){
  let g;const measure=()=>root.RetouchInspector.geometry(target,{allowRotation:true,layoutOnly:true});try{if(!available(target))throw Error('Choose a layer whose flow size can be edited.');g=measure();}catch(error){onError(error.message);return null;}
  const doc=root.document,w=target.ownerDocument.defaultView,f=frame.getBoundingClientRect(),c=canvas.getBoundingClientRect(),scale=f.width/w.innerWidth,left=Math.max(f.left,c.left),top=Math.max(f.top,c.top),right=Math.min(f.right,c.right),bottom=Math.min(f.bottom,c.bottom);
  if(!Number.isFinite(scale)||scale<=0||right<=left||bottom<=top||g.width<=0||g.height<=0){onError('Bring a visible layer into view before resizing.');return null;}
  const surface=doc.createElement('div');surface.className='canvas-flow-resize-surface';surface.tabIndex=0;surface.setAttribute('aria-label','Resize layer in flow');Object.assign(surface.style,{position:'fixed',left:left+'px',top:top+'px',width:right-left+'px',height:bottom-top+'px',overflow:'hidden',zIndex:40,touchAction:'none'});
  const handles=['e','s','se'].map(handle=>{const b=doc.createElement('button');b.type='button';b.dataset.flowHandle=handle;b.className='canvas-selection-resize';b.setAttribute('aria-label','Resize flow '+({e:'right',s:'bottom',se:'bottom right'}[handle]));surface.append(b);return b;});
  const hint=doc.createElement('div');Object.assign(hint.style,{position:'fixed',bottom:'76px',left:'50%',transform:'translateX(-50%)',padding:'8px 12px',background:'var(--panel)',color:'var(--ink)',border:'1px solid var(--line)',borderRadius:'6px',fontSize:'11px',pointerEvents:'none'});hint.textContent='Drag to resize in layout · Shift keeps proportions · Arrows: 1px · Enter applies · Escape cancels';surface.append(hint);
  const readouts=[...doc.querySelectorAll('input')].filter(input=>input.retouchDimension?.target===target).map(input=>({input,original:input.value,last:null,...input.retouchDimension}));
  let state=null,ended=false,raf,sizes=null,expectedStyle=target.getAttribute('style');const previews=new Map(),cleanups=[];
  const listen=(el,name,fn,options)=>{el.addEventListener(name,fn,options);cleanups.push(()=>el.removeEventListener(name,fn,options));};
  function valid(){return target.isConnected&&control.isConnected&&target.getAttribute('style')===expectedStyle&&current();}
  function finish(commit=false){if(ended)return;const next=commit&&valid()?sizes:null;ended=true;root.cancelAnimationFrame(raf);surface.remove();cleanups.forEach(fn=>fn());[...previews.values()].reverse().forEach(p=>p.restore());for(const field of readouts)if(field.last!==null&&field.input.value===field.last)field.input.value=field.original;onEnd();if(next&&Object.entries(next).some(([axis,value])=>Math.abs(value-g[axis])>.01))save(next);}
  function paint(){const next=measure();if(sizes){const css=w.getComputedStyle(target);for(const field of readouts){if(!field.input.isConnected)continue;field.last=field.box==='css'?css.getPropertyValue(field.axis):String(Math.round(next[field.axis]*100)/100);field.input.value=field.last;}}hint.textContent=Math.round(next.width*100)/100+' × '+Math.round(next.height*100)/100+' px · Resize in layout · Shift keeps proportions · Arrows: 1px · Enter applies · Escape cancels';const points=root.RetouchCanvasRotate.resizeHandles(next,scale);for(const b of handles){const p=points.find(p=>p.handle===b.dataset.flowHandle);Object.assign(b.style,{left:f.left+p.x-left+'px',top:f.top+p.y-top+'px',rotate:next.rotation+'deg',cursor:root.RetouchCanvasRotate.resizeCursor(p.handle,next.rotation)});}}
  function update(e){if(!state||!valid()){finish();return;}try{const delta=state.keyboard?{x:state.dx,y:state.dy}:root.RetouchCanvasMove.rotateVector(state.dx/scale,state.dy/scale,-g.rotation),r=root.RetouchCanvasMove.resize((state.base||g).width,(state.base||g).height,state.handle,delta.x,delta.y,{shiftKey:e.shiftKey}),requested={...state.previous};if(state.handle.includes('e')||e.shiftKey)requested.width=r.width;if(state.handle.includes('s')||e.shiftKey)requested.height=r.height;const css=w.getComputedStyle(target);for(const axis of Object.keys(requested)){const edges=axis==='width'?['left','right']:['top','bottom'],minimum=edges.reduce((sum,edge)=>sum+(parseFloat(css.getPropertyValue('padding-'+edge))||0)+(parseFloat(css.getPropertyValue('border-'+edge+'-width'))||0),0);requested[axis]=Math.max(minimum,requested[axis]);}const values=changes(target,requested);for(const [property,preview]of previews)if(!Object.hasOwn(values,property)){preview.restore();previews.delete(property);}for(const property of Object.keys(values))if(!previews.has(property))previews.set(property,root.RetouchPaintPicker.propertyPreview({el:target,input:control,property,respectScope:true}));for(const [property,value]of Object.entries(values))previews.get(property).update(value);expectedStyle=target.getAttribute('style');const actual=measure();sizes=Object.fromEntries(Object.keys(requested).map(axis=>[axis,actual[axis]]));paint();}catch(error){finish();onError(error.message);}}
  function begin(e,handle){if(e.button!==0||!['e','s','se'].includes(handle))return;e.preventDefault();e.stopPropagation();state={id:e.pointerId,handle,x:e.clientX,y:e.clientY,dx:0,dy:0};surface.setPointerCapture(e.pointerId);}
  listen(surface,'pointerdown',e=>begin(e,e.target.dataset.flowHandle));listen(surface,'pointermove',e=>{if(state?.id!==e.pointerId)return;state.dx=e.clientX-state.x;state.dy=e.clientY-state.y;update(e);});listen(surface,'pointerup',e=>{if(state?.id===e.pointerId)finish(Math.hypot(state.dx,state.dy)>=4);});listen(surface,'pointercancel',()=>finish());listen(surface,'lostpointercapture',()=>finish());listen(root,'pointerdown',e=>{if(!surface.contains(e.target))finish();},true);
  listen(surface,'keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();finish();return;}if(e.key==='Enter'){e.preventDefault();finish(true);return;}const directions={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},d=directions[e.key],handle=e.target.dataset.flowHandle;if(!d||!handle||state&&!state.keyboard)return;e.preventDefault();e.stopPropagation();if(!state||state.handle!==handle)state={keyboard:true,handle,dx:0,dy:0,base:{...g,...sizes},previous:sizes};state.dx+=d[0];state.dy+=d[1];update(e);},true);
  for(const event of ['keydown','keyup'])listen(root,event,e=>{if(e.key==='Shift'&&state){e.preventDefault();update(e);}},true);
  for(const event of ['blur','resize','retouch:screen','retouch:viewport','retouch:before-zoom'])listen(root,event,()=>finish());listen(w,'scroll',()=>finish(),true);listen(canvas,'scroll',()=>finish(),true);listen(frame,'load',()=>finish());
  function tick(){if(!valid()){finish();return;}try{paint();}catch{finish();return;}raf=root.requestAnimationFrame(tick);}
  doc.body.append(surface);paint();handles[2].focus({preventScroll:true});if(initial)begin(initial.event,initial.handle);raf=root.requestAnimationFrame(tick);return ()=>finish();
 }
 root.RetouchFlowResize={available,changes,control,mount};
})(window);
