(function(root){
 'use strict';
 function box(width,height,zoom,x,y){if(![width,height,zoom,x,y].every(Number.isFinite)||width<=0||height<=0||width>32768||height>32768||zoom<1||zoom>8||x<0||x>100||y<0||y>100)throw Error('Choose zoom from 100% to 800% and positions from 0% to 100%.');const w=width/zoom,h=height/zoom;return [(width-w)*x/100,(height-h)*y/100,w,h];}
 function layout(width,height,zoom,x,y,rotation=0){
  box(width,height,zoom,x,y);if(!Number.isFinite(rotation)||rotation<-180||rotation>180)throw Error('Choose an image rotation from -180 to 180 degrees.');
  const radians=rotation*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians),cover=Math.max(Math.abs(c)+height/width*Math.abs(s),Math.abs(c)+width/height*Math.abs(s)),w=width/(zoom*cover),h=height/(zoom*cover),extentX=(Math.abs(c)*w+Math.abs(s)*h)/2,extentY=(Math.abs(s)*w+Math.abs(c)*h)/2,rangeX=Math.max(0,width-2*extentX),rangeY=Math.max(0,height-2*extentY),sourceX=extentX+rangeX*x/100-width/2,sourceY=extentY+rangeY*y/100-height/2;
  return {view:[c*sourceX-s*sourceY+width/2-w/2,s*sourceX+c*sourceY+height/2-h/2,w,h].map(value=>Number(value.toFixed(8))),rangeX,rangeY,c,s};
 }
 function pan(model,dx,dy,displayWidth){const g=layout(model.width,model.height,model.zoom,model.x,model.y,model.rotation),scale=displayWidth/g.view[2],x=g.c*dx+g.s*dy,y=-g.s*dx+g.c*dy;return {...model,x:g.rangeX<1e-7?model.x:Math.max(0,Math.min(100,model.x-x/scale/g.rangeX*100)),y:g.rangeY<1e-7?model.y:Math.max(0,Math.min(100,model.y-y/scale/g.rangeY*100))};}
 function markup({width,height,zoom,x,y,data,rotation=0}){const view=layout(width,height,zoom,x,y,rotation).view;if(typeof data!=='string'||!/^data:image\/(?:png|jpeg|webp|avif|gif|svg\+xml|x-icon|vnd.microsoft.icon);base64,[a-z\d+/=\r\n]+$/i.test(data))throw Error('Choose a self-contained image.');return '<svg xmlns="http://www.w3.org/2000/svg" width="'+width+'" height="'+height+'" viewBox="'+view.join(' ')+'" data-retouch-crop="1" data-zoom="'+zoom+'" data-x="'+x+'" data-y="'+y+'" data-rotation="'+rotation+'"><image width="'+width+'" height="'+height+'"'+(rotation?' transform="rotate('+rotation+' '+width/2+' '+height/2+')"':'')+' href="'+data+'"/></svg>';}
 async function load(target){
  const response=await root.fetch(target.currentSrc||target.src);if(!response.ok)throw Error('The original image could not be loaded.');const blob=await response.blob();if(blob.size>10000000)throw Error('This image exceeds the 10 MB crop limit.');
  if(blob.type.split(';')[0]==='image/svg+xml'){const d=new root.DOMParser().parseFromString(await blob.text(),'image/svg+xml'),svg=d.documentElement,image=svg.firstElementChild;if(svg.getAttribute('data-retouch-crop')==='1'&&svg.localName==='svg'&&svg.children.length===1&&image?.localName==='image'&&[...svg.attributes].every(attr=>['xmlns','width','height','viewBox','data-retouch-crop','data-zoom','data-x','data-y','data-rotation'].includes(attr.name))&&[...image.attributes].every(attr=>['width','height','href','transform'].includes(attr.name))){const model={width:Number(svg.getAttribute('width')),height:Number(svg.getAttribute('height')),zoom:Number(svg.getAttribute('data-zoom')),x:Number(svg.getAttribute('data-x')),y:Number(svg.getAttribute('data-y')),rotation:Number(svg.getAttribute('data-rotation')||0),data:image.getAttribute('href')};markup(model);if(image.getAttribute('width')===svg.getAttribute('width')&&image.getAttribute('height')===svg.getAttribute('height')&&(image.getAttribute('transform')||'')===(model.rotation?'rotate('+model.rotation+' '+model.width/2+' '+model.height/2+')':'')&&svg.getAttribute('viewBox')?.trim().split(/[ ,]+/).length===4&&svg.getAttribute('viewBox').trim().split(/[ ,]+/).every((value,i)=>Math.abs(Number(value)-layout(model.width,model.height,model.zoom,model.x,model.y,model.rotation).view[i])<1e-6))return model;}}
  if(blob.size>7000000)throw Error('Choose an original image smaller than 7 MB for cropping.');
  const normalized=new Blob([blob],{type:blob.type.split(';')[0]});const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('The image could not be read.'));reader.readAsDataURL(normalized);});const model={width:target.naturalWidth,height:target.naturalHeight,zoom:1,x:50,y:50,rotation:0,data};markup(model);return model;
 }
 async function open({target,current,onApply,onError}){
  if(document.querySelector('dialog[open]'))return;const I=root.RetouchInspector,opener=document.activeElement,dialog=document.createElement('dialog'),header=document.createElement('header'),heading=document.createElement('h2'),status=document.createElement('p'),preview=document.createElement('img'),fields=document.createElement('fieldset'),footer=document.createElement('footer');dialog.className='quick-actions image-crop-dialog';dialog.setAttribute('aria-label','Crop image');heading.textContent='Crop image';status.setAttribute('role','status');status.textContent='Loading image…';preview.alt='Crop preview';preview.className='image-crop-preview';fields.disabled=true;fields.style.border='0';
  let model=null,url=null,saving=false,drag=null;const controls={};for(const [key,label,min,max,value]of [['zoom','Image zoom (%)',100,800,100],['rotation','Image rotation (°)',-180,180,0],['x','Crop horizontal position (%)',0,100,50],['y','Crop vertical position (%)',0,100,50]]){const input=document.createElement('input');input.type='number';input.min=min;input.max=max;input.step='any';input.value=value;input.required=true;controls[key]=input;I.field(fields,label,input);input.closest('label').querySelector('span').textContent={zoom:'Zoom (%)',rotation:'Rotation (°)',x:'Position X (%)',y:'Position Y (%)'}[key];input.oninput=()=>{if(!model||!Object.values(controls).every(el=>el.checkValidity()))return;model={...model,zoom:Number(controls.zoom.value)/100,x:Number(controls.x.value),y:Number(controls.y.value),rotation:Number(controls.rotation.value)};paint();};}
  preview.draggable=false;preview.style.touchAction='none';preview.style.cursor='move';preview.title='Drag to position the crop';
  preview.onpointerdown=event=>{if(event.button!==0||!model||saving)return;event.preventDefault();const aspect=model.width/model.height,width=Math.min(preview.clientWidth,preview.clientHeight*aspect),height=width/aspect;drag={id:event.pointerId,x:event.clientX,y:event.clientY,model:{...model},width,height};preview.setPointerCapture(event.pointerId);};
  preview.onpointermove=event=>{if(!drag||event.pointerId!==drag.id)return;model=pan(drag.model,event.clientX-drag.x,event.clientY-drag.y,drag.width);controls.x.value=String(Math.round(model.x*10000)/10000);controls.y.value=String(Math.round(model.y*10000)/10000);paint();};
  preview.onpointerup=preview.onpointercancel=preview.onlostpointercapture=()=>{drag=null;};
  const cancel=I.button('Cancel',()=>{if(!saving)dialog.close();}),apply=I.button('Apply crop',async()=>{if(saving||!model||!Object.values(controls).every(el=>el.reportValidity()))return;if(!current()){status.textContent='The selected image changed. Close this crop and select it again.';return;}saving=true;fields.disabled=apply.disabled=cancel.disabled=true;try{const blob=new Blob([markup(model)],{type:'image/svg+xml'});if(blob.size>10000000)throw Error('The cropped image exceeds the 10 MB upload limit.');await onApply(blob);dialog.close();}catch(error){status.textContent=error.message;}finally{saving=false;fields.disabled=apply.disabled=cancel.disabled=false;}});apply.disabled=true;header.append(heading,cancel);footer.append(apply);dialog.append(header,preview,fields,status,footer);document.body.append(dialog);
  function paint(){const next=URL.createObjectURL(new Blob([markup(model)],{type:'image/svg+xml'}));preview.src=next;if(url)URL.revokeObjectURL(url);url=next;status.textContent='Creates a cropped copy for all screen sizes. The original is kept.';}
  dialog.addEventListener('cancel',event=>{if(saving)event.preventDefault();});dialog.addEventListener('close',()=>{if(url)URL.revokeObjectURL(url);dialog.remove();opener?.focus({preventScroll:true});});dialog.showModal();
  try{model=await load(target);if(!dialog.open)return;controls.zoom.value=model.zoom*100;controls.rotation.value=model.rotation||0;controls.x.value=model.x;controls.y.value=model.y;fields.disabled=apply.disabled=false;paint();controls.zoom.focus();controls.zoom.select();}catch(error){if(dialog.open)status.textContent=error.message;}
 }
 const api={box,layout,pan,markup,open};if(typeof module==='object'&&module.exports)module.exports=api;else root.RetouchImageCrop=api;
})(typeof window==='object'?window:globalThis);
