(function(root){
 'use strict';
 function box(width,height,zoom,x,y){if(![width,height,zoom,x,y].every(Number.isFinite)||width<=0||height<=0||width>32768||height>32768||zoom<1||zoom>8||x<0||x>100||y<0||y>100)throw Error('Choose zoom from 100% to 800% and positions from 0% to 100%.');const w=width/zoom,h=height/zoom;return [(width-w)*x/100,(height-h)*y/100,w,h];}
 function layout(width,height,zoom,x,y,rotation=0){
  box(width,height,zoom,x,y);if(!Number.isFinite(rotation)||rotation<-180||rotation>180)throw Error('Choose an image rotation from -180 to 180 degrees.');
  const radians=rotation*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians),cover=Math.max(Math.abs(c)+height/width*Math.abs(s),Math.abs(c)+width/height*Math.abs(s)),w=width/(zoom*cover),h=height/(zoom*cover),extentX=(Math.abs(c)*w+Math.abs(s)*h)/2,extentY=(Math.abs(s)*w+Math.abs(c)*h)/2,rangeX=Math.max(0,width-2*extentX),rangeY=Math.max(0,height-2*extentY),sourceX=extentX+rangeX*x/100-width/2,sourceY=extentY+rangeY*y/100-height/2;
  return {view:[c*sourceX-s*sourceY+width/2-w/2,s*sourceX+c*sourceY+height/2-h/2,w,h].map(value=>Number(value.toFixed(8))),rangeX,rangeY,c,s};
 }
 function pan(model,dx,dy,displayWidth,displayHeight=displayWidth*model.height/model.width){const g=layout(model.width,model.height,model.zoom,model.x,model.y,model.rotation),px=dx*g.view[2]/displayWidth,py=dy*g.view[3]/displayHeight,x=g.c*px+g.s*py,y=-g.s*px+g.c*py;return {...model,x:g.rangeX<1e-7?model.x:Math.max(0,Math.min(100,model.x-x/g.rangeX*100)),y:g.rangeY<1e-7?model.y:Math.max(0,Math.min(100,model.y-y/g.rangeY*100))};}

 function transform({width,height,rotation=0,flipX=false,flipY=false}){if(typeof flipX!=='boolean'||typeof flipY!=='boolean')throw Error('Choose a valid image flip.');return [(rotation?'rotate('+rotation+' '+width/2+' '+height/2+')':''),(flipX||flipY?'translate('+(flipX?width:0)+' '+(flipY?height:0)+') scale('+(flipX?-1:1)+' '+(flipY?-1:1)+')':'')].filter(Boolean).join(' ');}
 function toneCurve(shadows=0,highlights=0){if(![shadows,highlights].every(value=>Number.isFinite(value)&&Math.abs(value)<=100))throw Error('Choose highlights and shadows from -100 to 100.');return Array.from({length:257},(_,i)=>{const x=i/256;return Number(Math.max(0,Math.min(1,x+shadows/100*x*Math.pow(1-x,3)+highlights/100*Math.pow(x,3)*(1-x))).toFixed(6));});}
 function adjustments({exposure=0,contrast=0,saturation=0,temperature=0,tint=0,highlights=0,shadows=0}){
  if(!Number.isFinite(exposure)||Math.abs(exposure)>3||![contrast,saturation,temperature,tint,highlights,shadows].every(value=>Number.isFinite(value)&&Math.abs(value)<=100))throw Error('Choose exposure from -3 to 3 and other adjustments from -100 to 100.');
  if(!exposure&&!contrast&&!saturation&&!temperature&&!tint&&!highlights&&!shadows)return '';const factor=1+contrast/100,slope=Math.pow(2,exposure)*factor,intercept=(1-factor)/2;
  const gains=[Math.pow(2,temperature/200+tint/400),Math.pow(2,-tint/200),Math.pow(2,-temperature/200+tint/400)],balance=temperature||tint?'<feComponentTransfer>'+['R','G','B'].map((channel,i)=>'<feFunc'+channel+' type="linear" slope="'+gains[i]+'"/>').join('')+'</feComponentTransfer>':'';
  const tones=highlights||shadows?'<feComponentTransfer>'+['R','G','B'].map(channel=>'<feFunc'+channel+' type="table" tableValues="'+toneCurve(shadows,highlights).join(' ')+'"/>').join('')+'</feComponentTransfer>':'';
  return '<defs><filter id="rt-crop-adjust" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB"><feComponentTransfer>'+['R','G','B'].map(channel=>'<feFunc'+channel+' type="linear" slope="'+slope+'" intercept="'+intercept+'"/>').join('')+'</feComponentTransfer><feColorMatrix type="saturate" values="'+(1+saturation/100)+'"/>'+balance+tones+'</filter></defs>';
 }
 // Let CSS size the cropped image like a raster, including non-proportional background sizes.
 function markup({width,height,zoom,x,y,data,rotation=0,flipX=false,flipY=false,exposure=0,contrast=0,saturation=0,temperature=0,tint=0,highlights=0,shadows=0}){const filter=adjustments({exposure,contrast,saturation,temperature,tint,highlights,shadows}),view=layout(width,height,zoom,x,y,rotation).view,t=transform({width,height,rotation,flipX,flipY});if(typeof data!=='string'||!/^data:image\/(?:png|jpeg|webp|avif|gif|svg\+xml|x-icon|vnd.microsoft.icon);base64,[a-z\d+/=\r\n]+$/i.test(data))throw Error('Choose a self-contained image.');return '<svg xmlns="http://www.w3.org/2000/svg" width="'+width+'" height="'+height+'" viewBox="'+view.join(' ')+'" preserveAspectRatio="none" data-retouch-crop="1" data-zoom="'+zoom+'" data-x="'+x+'" data-y="'+y+'" data-rotation="'+rotation+'" data-flip-x="'+flipX+'" data-flip-y="'+flipY+'" data-exposure="'+exposure+'" data-contrast="'+contrast+'" data-saturation="'+saturation+'" data-temperature="'+temperature+'" data-tint="'+tint+'" data-highlights="'+highlights+'" data-shadows="'+shadows+'">'+filter+'<image width="'+width+'" height="'+height+'"'+(t?' transform="'+t+'"':'')+(filter?' filter="url(#rt-crop-adjust)"':'')+' href="'+data+'"/></svg>';}
 async function load(target,signal){
  const response=await root.fetch(target.currentSrc||target.src,{signal});if(!response.ok)throw Error('The original image could not be loaded.');const blob=await response.blob();if(signal.aborted)throw Error('Image loading canceled.');if(blob.size>10000000)throw Error('This image exceeds the 10 MB crop limit.');
  if(blob.type.split(';')[0]==='image/svg+xml'){const d=new root.DOMParser().parseFromString(await blob.text(),'image/svg+xml'),svg=d.documentElement,image=svg.lastElementChild;if(svg.getAttribute('data-retouch-crop')==='1'&&svg.localName==='svg'&&(svg.children.length===1||svg.children.length===2&&svg.firstElementChild.localName==='defs')&&image?.localName==='image'&&[...svg.attributes].every(attr=>['xmlns','width','height','viewBox','preserveAspectRatio','data-retouch-crop','data-zoom','data-x','data-y','data-rotation','data-flip-x','data-flip-y','data-exposure','data-contrast','data-saturation','data-temperature','data-tint','data-highlights','data-shadows'].includes(attr.name))&&[...image.attributes].every(attr=>['width','height','href','transform','filter'].includes(attr.name))){const model={width:Number(svg.getAttribute('width')),height:Number(svg.getAttribute('height')),zoom:Number(svg.getAttribute('data-zoom')),x:Number(svg.getAttribute('data-x')),y:Number(svg.getAttribute('data-y')),rotation:Number(svg.getAttribute('data-rotation')||0),flipX:svg.getAttribute('data-flip-x')==='true',flipY:svg.getAttribute('data-flip-y')==='true',exposure:Number(svg.getAttribute('data-exposure')||0),contrast:Number(svg.getAttribute('data-contrast')||0),saturation:Number(svg.getAttribute('data-saturation')||0),temperature:Number(svg.getAttribute('data-temperature')||0),tint:Number(svg.getAttribute('data-tint')||0),highlights:Number(svg.getAttribute('data-highlights')||0),shadows:Number(svg.getAttribute('data-shadows')||0),data:image.getAttribute('href')};const expected=new root.DOMParser().parseFromString(markup(model),'image/svg+xml').documentElement,filterMatches=svg.children.length===expected.children.length&&(svg.children.length===1||svg.firstElementChild.isEqualNode(expected.firstElementChild));if(filterMatches&&(!svg.hasAttribute('preserveAspectRatio')||svg.getAttribute('preserveAspectRatio')==='none')&&(image.getAttribute('filter')||'')===(expected.lastElementChild.getAttribute('filter')||'')&&image.getAttribute('width')===svg.getAttribute('width')&&image.getAttribute('height')===svg.getAttribute('height')&&(image.getAttribute('transform')||'')===transform(model)&&svg.getAttribute('viewBox')?.trim().split(/[ ,]+/).length===4&&svg.getAttribute('viewBox').trim().split(/[ ,]+/).every((value,i)=>Math.abs(Number(value)-layout(model.width,model.height,model.zoom,model.x,model.y,model.rotation).view[i])<1e-6))return model;}}
  if(blob.size>7000000)throw Error('Choose an original image smaller than 7 MB for cropping.');
  const normalized=new Blob([blob],{type:blob.type.split(';')[0]});const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('The image could not be read.'));reader.readAsDataURL(normalized);});const model={width:target.naturalWidth,height:target.naturalHeight,zoom:1,x:50,y:50,rotation:0,data};markup(model);return model;
 }
 async function open({target,source=target,frame=null,scopeNote="Creates a cropped copy for all screen sizes. The original is kept.",current,onApply,onError}){
  if(document.querySelector('dialog[open]'))return;const I=root.RetouchInspector,opener=document.activeElement,dialog=document.createElement('dialog'),header=document.createElement('header'),heading=document.createElement('h2'),status=document.createElement('p'),preview=document.createElement('img'),fields=document.createElement('fieldset'),footer=document.createElement('footer');dialog.className='quick-actions image-crop-dialog';dialog.setAttribute('aria-label','Crop image');heading.textContent='Crop image';status.setAttribute('role','status');status.textContent='Loading image…';preview.alt='Crop preview';preview.className='image-crop-preview';fields.disabled=true;fields.style.border='0';
  const controlsViewport=document.createElement('div');controlsViewport.className='image-crop-controls';controlsViewport.append(fields);const stage=document.createElement('div');stage.className='image-crop-stage';stage.append(preview);const style=frame||target.ownerDocument.defaultView.getComputedStyle(target),px=name=>parseFloat(style[name])||0,frameWidth=px('width')-(style.boxSizing==='border-box'?px('paddingLeft')+px('paddingRight')+px('borderLeftWidth')+px('borderRightWidth'):0),frameHeight=px('height')-(style.boxSizing==='border-box'?px('paddingTop')+px('paddingBottom')+px('borderTopWidth')+px('borderBottomWidth'):0),fw=frameWidth>0?frameWidth:source.naturalWidth,fh=frameHeight>0?frameHeight:source.naturalHeight;let displayScale=1;
  preview.style.width=fw+'px';preview.style.height=fh+'px';preview.style.maxWidth='none';preview.style.objectFit=style.objectFit;preview.style.objectPosition=style.objectPosition;
  function sizePreview(){displayScale=Math.min(stage.clientWidth/fw,Math.min(240,Math.max(80,root.innerHeight*.28))/fh);stage.style.height=fh*displayScale+'px';preview.style.transform='scale('+displayScale+')';preview.style.left=(stage.clientWidth-fw*displayScale)/2+'px';}
  function paintedSize(){const space=root.RetouchImagePosition.freeSpace(fw,fh,model.width,model.height,style.objectFit);return [(fw-space[0])*displayScale,(fh-space[1])*displayScale];}
  let model=null,url=null,saving=false,drag=null,saved=null,loading=null;const past=[],future=[];const controls={};for(const [key,label,min,max,value]of [['zoom','Image zoom (%)',100,800,100],['rotation','Image rotation (°)',-180,180,0],['x','Crop horizontal position (%)',0,100,50],['y','Crop vertical position (%)',0,100,50],['exposure','Image exposure',-3,3,0],['contrast','Image contrast (%)',-100,100,0],['saturation','Image saturation (%)',-100,100,0],['temperature','Image temperature',-100,100,0],['tint','Image tint',-100,100,0],['highlights','Image highlights',-100,100,0],['shadows','Image shadows',-100,100,0]]){const input=document.createElement('input');input.type='number';input.min=min;input.max=max;input.step='any';input.value=value;input.required=true;controls[key]=input;I.field(fields,label,input);input.closest('label').querySelector('span').textContent={zoom:'Zoom (%)',rotation:'Rotation (°)',x:'Position X (%)',y:'Position Y (%)',exposure:'Exposure',contrast:'Contrast',saturation:'Saturation',temperature:'Temperature',tint:'Tint',highlights:'Highlights',shadows:'Shadows'}[key];input.oninput=()=>{if(!model||!Object.values(controls).every(el=>el.checkValidity()))return;model={...model,zoom:Number(controls.zoom.value)/100,x:Number(controls.x.value),y:Number(controls.y.value),rotation:Number(controls.rotation.value),exposure:Number(controls.exposure.value),contrast:Number(controls.contrast.value),saturation:Number(controls.saturation.value),temperature:Number(controls.temperature.value),tint:Number(controls.tint.value),highlights:Number(controls.highlights.value),shadows:Number(controls.shadows.value)};paint();};input.onchange=()=>record();}
  const sliders={};for(const key of ['exposure','contrast','saturation','temperature','tint','highlights','shadows']){
   const input=controls[key],label=input.closest('label'),row=document.createElement('div'),group=document.createElement('div'),slider=document.createElement('input');row.className='inspector-field image-adjustment-field';group.className='image-adjustment-controls';slider.type='range';slider.min=input.min;slider.max=input.max;slider.step=key==='exposure'?'0.05':'1';slider.value='0';slider.setAttribute('aria-label',input.getAttribute('aria-label')+' slider');sliders[key]=slider;
   label.replaceWith(row);row.append(label.querySelector('span'),group);group.append(slider,input);let held=false;
   slider.oninput=()=>{input.value=slider.value;input.oninput();};slider.onchange=()=>{if(!held)record();};slider.onkeydown=event=>{if(!event.ctrlKey&&!event.metaKey&&!event.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(event.key))held=true;};slider.onkeyup=()=>{if(held){held=false;record();}};slider.onblur=()=>{held=false;record();};
  }
  preview.draggable=false;preview.style.touchAction='none';preview.style.cursor='move';preview.title='Drag or use arrow keys to position the crop. Hold Shift for larger steps.';preview.tabIndex=0;preview.setAttribute('aria-label','Crop preview');preview.setAttribute('aria-description',preview.title);
  function position(next){model=next;controls.x.value=String(Math.round(model.x*10000)/10000);controls.y.value=String(Math.round(model.y*10000)/10000);paint();}
  preview.onkeydown=event=>{const direction={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[event.key];if(!direction||event.metaKey||event.ctrlKey||event.altKey||event.isComposing||!model||saving||drag||!Object.values(controls).every(el=>el.checkValidity()))return;event.preventDefault();event.stopPropagation();const [width,height]=paintedSize(),step=event.shiftKey?10:1;position(pan(model,direction[0]*step,direction[1]*step,width,height));};
  preview.onkeyup=event=>{if(event.key.startsWith('Arrow'))record();};preview.onblur=()=>record();
  preview.onpointerdown=event=>{if(event.button!==0||!model||saving||!Object.values(controls).every(el=>el.checkValidity()))return;event.preventDefault();preview.focus({preventScroll:true});const [width,height]=paintedSize();drag={id:event.pointerId,x:event.clientX,y:event.clientY,model:{...model},width,height};preview.setPointerCapture(event.pointerId);};
  preview.onpointermove=event=>{if(!drag||event.pointerId!==drag.id)return;position(pan(drag.model,event.clientX-drag.x,event.clientY-drag.y,drag.width,drag.height));};
  preview.onpointerup=preview.onpointercancel=preview.onlostpointercapture=()=>{drag=null;record();};
  const flipRow=document.createElement('div');flipRow.className='image-crop-flips';fields.append(flipRow);const flips={};for(const [key,label]of [['flipX','Flip image horizontally'],['flipY','Flip image vertically']]){const button=I.button(label,()=>{if(!model||saving)return;drag=null;record();model={...model,[key]:!model[key]};paint();record();});button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',label);button.textContent=key==='flipX'?'Flip horizontal':'Flip vertical';flips[key]=button;flipRow.append(button);}
  const reset=I.button('Reset crop',()=>{if(!model||saving)return;drag=null;record();model={...model,zoom:1,rotation:0,x:50,y:50,flipX:false,flipY:false};controls.zoom.value=100;controls.rotation.value=0;controls.x.value=controls.y.value=50;paint();record();});fields.append(reset);fields.append(I.button('Reset adjustments',()=>{if(!model||saving)return;record();model={...model,exposure:0,contrast:0,saturation:0,temperature:0,tint:0,highlights:0,shadows:0};for(const key of ['exposure','contrast','saturation','temperature','tint','highlights','shadows'])controls[key].value=0;paint();record();}));
  const undo=I.button('Undo crop edit',()=>restore(false)),redo=I.button('Redo crop edit',()=>restore(true));undo.textContent='Undo';redo.textContent='Redo';undo.setAttribute('aria-label','Undo crop edit');redo.setAttribute('aria-label','Redo crop edit');const history=document.createElement('div');history.className='image-crop-history';history.append(undo,redo);
  function signature(value){return value?[value.zoom,value.rotation||0,value.x,value.y,!!value.flipX,!!value.flipY,value.exposure||0,value.contrast||0,value.saturation||0,value.temperature||0,value.tint||0,value.highlights||0,value.shadows||0].join('|'):'';}
  function historyState(){undo.disabled=saving||!saved||(!past.length&&signature(model)===signature(saved));redo.disabled=saving||!future.length||signature(model)!==signature(saved);}
  function record(){if(!model||!saved||saving)return;if(signature(model)!==signature(saved)){past.push(saved);if(past.length>100)past.shift();saved={...model};future.length=0;}historyState();}
  function restore(forward){if(!model||saving)return;drag=null;record();const from=forward?future:past,to=forward?past:future;if(!from.length)return;to.push(saved);saved=from.pop();model={...saved};controls.zoom.value=model.zoom*100;controls.rotation.value=model.rotation||0;controls.x.value=model.x;controls.y.value=model.y;for(const key of ['exposure','contrast','saturation','temperature','tint','highlights','shadows'])controls[key].value=model[key]||0;paint();}
  dialog.addEventListener('keydown',event=>{if(event.isComposing||event.altKey||!(event.ctrlKey||event.metaKey))return;const key=event.key.toLowerCase();if(key!=='z'&&key!=='y')return;event.preventDefault();event.stopPropagation();restore(key==='y'||event.shiftKey);});
  const cancel=I.button('Cancel',()=>{if(!saving)dialog.close();}),apply=I.button('Apply crop',async()=>{if(saving||!model||!Object.values(controls).every(el=>el.reportValidity()))return;if(!current()){status.textContent='The selected image changed. Close this crop and select it again.';return;}saving=true;historyState();fields.disabled=apply.disabled=cancel.disabled=true;try{const blob=new Blob([markup(model)],{type:'image/svg+xml'});if(blob.size>10000000)throw Error('The cropped image exceeds the 10 MB upload limit.');await onApply(blob);dialog.close();}catch(error){status.textContent=error.message;}finally{saving=false;fields.disabled=apply.disabled=cancel.disabled=false;historyState();}});apply.disabled=true;header.append(heading,cancel);footer.append(history,apply);dialog.append(header,stage,controlsViewport,status,footer);document.body.append(dialog);
  function paint(){for(const [key,slider]of Object.entries(sliders))slider.value=model[key]||0;historyState();for(const [key,button]of Object.entries(flips))button.setAttribute('aria-pressed',String(!!model[key]));const next=URL.createObjectURL(new Blob([markup(model)],{type:'image/svg+xml'}));preview.src=next;if(url)URL.revokeObjectURL(url);url=next;status.textContent=scopeNote;}
  const resize=new ResizeObserver(sizePreview);resize.observe(stage);root.addEventListener('resize',sizePreview);
  dialog.addEventListener('cancel',event=>{if(saving)event.preventDefault();});dialog.addEventListener('close',()=>{loading?.abort();resize.disconnect();root.removeEventListener('resize',sizePreview);if(url)URL.revokeObjectURL(url);dialog.remove();const popup=opener?.closest('[popover]');if(popup?.isConnected)popup.retouchOpen?.();opener?.focus({preventScroll:true});});dialog.showModal();sizePreview();
  const retry=I.button('Retry image loading',()=>beginLoad());retry.hidden=true;dialog.insertBefore(retry,footer);
  async function beginLoad(){
   if(loading||!dialog.open)return;
   if(!current()){status.textContent='The selected image changed. Close this crop and select it again.';retry.hidden=true;return;}
   const controller=new AbortController();loading=controller;let timedOut=false;const timer=setTimeout(()=>{timedOut=true;controller.abort();},15000);retry.hidden=true;status.textContent='Loading image…';
   try{const next=await load(source,controller.signal);if(!dialog.open||controller.signal.aborted)return;model=next;saved={...model};controls.zoom.value=model.zoom*100;controls.rotation.value=model.rotation||0;controls.x.value=model.x;controls.y.value=model.y;for(const key of ['exposure','contrast','saturation','temperature','tint','highlights','shadows'])controls[key].value=model[key]||0;fields.disabled=apply.disabled=false;paint();controls.zoom.focus();controls.zoom.select();}
   catch(error){if(dialog.open){status.textContent=timedOut?'The image took too long to load. Try again.':error.message;retry.hidden=false;}}
   finally{clearTimeout(timer);if(loading===controller)loading=null;}
  }
  historyState();await beginLoad();
 }
 const api={box,layout,pan,toneCurve,adjustments,markup,open};if(typeof module==='object'&&module.exports)module.exports=api;else root.RetouchImageCrop=api;
})(typeof window==='object'?window:globalThis);
