(function(root){
 'use strict';
 // A quarter turn maps every point p to R(p-pivot)+pivot. Recovering that
 // fixed point also handles content-box origins and authored matrix offsets.
 function pivot(before,after){return {x:(after.x+before.y-after.y+before.x)/2,y:(after.x+before.y+after.y-before.x)/2};}
 function mount({target,frame,canvas,input,current,onEnd,onError,initialPointer=null}){
  const I=root.RetouchInspector,C=root.RetouchCanvasRotate,w=target.ownerDocument.defaultView,doc=root.document,measure=()=>{const g=I.localPositionGeometry(target,{allowFlow:true});return {...g,rotation:g.rotation||0};};let g,space,center;
  try{
   g=measure();space=root.RetouchSVGDraw.nativeSpace(target.offsetParent);
   const calibration=root.RetouchPaintPicker.propertyPreview({el:target,input,property:'rotate',respectScope:true});
   try{const before=I.localPositionCorners(g,[[0,0]])[0];calibration.update((g.rotation+90)+'deg');const after=measure();if(Math.abs(after.rotation-g.rotation-90)>.01)throw Error('The layer’s rotation rules prevent canvas rotation.');center=pivot(before,I.localPositionCorners(after,[[0,0]])[0]);}finally{calibration.restore();}
  }catch(error){onError(error.message);return null;}
  const f=frame.getBoundingClientRect(),c=canvas.getBoundingClientRect(),zoom=f.width/w.innerWidth,clip={left:Math.max(c.left,f.left),top:Math.max(c.top,f.top),right:Math.min(c.right,f.right),bottom:Math.min(c.bottom,f.bottom)},inverse=space.matrix.inverse();
  if(!Number.isFinite(zoom)||zoom<=0||clip.right-clip.left<32||clip.bottom-clip.top<32){onError('Bring the layer into view before rotating it.');return null;}
  const screen=p=>{const q=new w.DOMPoint(p.x,p.y).matrixTransform(space.matrix);return {x:f.left+q.x*zoom-clip.left,y:f.top+q.y*zoom-clip.top};},local=e=>new w.DOMPoint((e.clientX-f.left)/zoom,(e.clientY-f.top)/zoom).matrixTransform(inverse);
  const surface=doc.createElement('div');surface.className='canvas-rotate-surface canvas-local-rotate-surface';surface.dataset.localMove=target.getAttribute('data-rt');surface.tabIndex=0;surface.setAttribute('aria-label','Rotate layer on canvas');Object.assign(surface.style,{position:'fixed',left:clip.left+'px',top:clip.top+'px',width:clip.right-clip.left+'px',height:clip.bottom-clip.top+'px',zIndex:40,overflow:'hidden',touchAction:'none'});
  const svg=doc.createElementNS('http://www.w3.org/2000/svg','svg'),outline=doc.createElementNS(svg.namespaceURI,'polygon');Object.assign(svg.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none'});outline.setAttribute('fill','none');outline.setAttribute('stroke','var(--accent)');outline.setAttribute('stroke-width','1');svg.append(outline);
  const marker=doc.createElement('div'),p=screen(center);Object.assign(marker.style,{position:'absolute',left:p.x+'px',top:p.y+'px',width:'6px',height:'6px',border:'1px solid var(--accent)',borderRadius:'50%',background:'white',transform:'translate(-50%,-50%)',pointerEvents:'none'});
  const handle=doc.createElement('button');handle.type='button';handle.setAttribute('aria-label','Drag to rotate layer');handle.textContent='↻';Object.assign(handle.style,{position:'absolute',width:'24px',height:'24px',padding:'0',border:'1px solid var(--accent)',borderRadius:'50%',background:'var(--panel)',color:'var(--accent)',transform:'translate(-50%,-50%)',cursor:'grab',touchAction:'none'});
  const hint=doc.createElement('div');Object.assign(hint.style,{position:'absolute',left:'8px',padding:'6px 8px',border:'1px solid var(--line)',borderRadius:'4px',background:'var(--panel)',color:'var(--ink)',fontSize:'11px',pointerEvents:'none'});surface.append(svg,marker,handle,hint);doc.body.append(surface);
  const initialValue=input.value,preview=input.retouchNumericPreview(),cleanup=[],signature=()=>{const css=w.getComputedStyle(target);return [css.transform,css.translate,css.scale,css.transformOrigin,css.transformBox,css.zoom].join('|');},originalSignature=signature();let expectedStyle=target.getAttribute('style'),rotation=g.rotation,ended=false,drag=null,raf;
  const listen=(el,event,fn,options)=>{el.addEventListener(event,fn,options);cleanup.push(()=>el.removeEventListener(event,fn,options));};
  function valid(){if(!target.isConnected||!input.isConnected||!current()||!space.current()||target.getAttribute('style')!==expectedStyle||signature()!==originalSignature)return false;try{const next=measure(),now=frame.getBoundingClientRect();return ['left','top','width','height'].every(k=>Math.abs(now[k]-f[k])<.5)&&['x','y','width','height'].every(k=>Math.abs(next[k]-g[k])<.6)&&Math.abs(next.rotation-rotation)<.05;}catch{return false;}}
  function end(commit=false){if(ended)return;const save=commit&&valid();ended=true;root.cancelAnimationFrame(raf);cleanup.forEach(fn=>fn());surface.remove();preview.restore();input.value=initialValue;onEnd();if(save&&Math.abs(rotation-g.rotation)>.005){input.value=String(rotation);input.dispatchEvent(new root.Event('change',{bubbles:true}));}}
  function paint(){const points=I.localPositionCorners(measure()).map(screen);outline.setAttribute('points',points.map(p=>p.x+','+p.y).join(' '));const corner=points[1],dx=corner.x-p.x,dy=corner.y-p.y,length=Math.hypot(dx,dy)||1;handle.style.left=Math.max(16,Math.min(clip.right-clip.left-16,corner.x+dx/length*24))+'px';handle.style.top=Math.max(16,Math.min(clip.bottom-clip.top-16,corner.y+dy/length*24))+'px';const dock=doc.querySelector('.design-tool-dock')?.getBoundingClientRect();hint.style.bottom=Math.max(8,dock?clip.bottom-dock.top+8:8)+'px';hint.textContent=rotation+'° · Shift: 15° · Arrows: 1° · Enter applies · Escape cancels';input.value=String(rotation);}
  function update(next){if(!valid()){end();return;}rotation=next;preview.update(rotation);expectedStyle=target.getAttribute('style');paint();}
  function begin(e){if(e.button!==0)return;e.preventDefault();const q=local(e);drag={id:e.pointerId,last:C.angle(q.x,q.y,center),change:0,start:rotation};handle.setPointerCapture(e.pointerId);}
  listen(handle,'pointerdown',begin);listen(handle,'pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const q=local(e),next=C.angle(q.x,q.y,center);drag.change+=C.difference(next,drag.last);drag.last=next;update(C.value(drag.start,drag.change,e.shiftKey));});listen(handle,'pointerup',e=>{if(drag?.id===e.pointerId){drag=null;end(true);}});listen(handle,'pointercancel',()=>end());
  listen(surface,'keydown',e=>{if(!['Escape','Enter','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape')end();else if(e.key==='Enter')end(true);else update(C.value(rotation,(['ArrowLeft','ArrowDown'].includes(e.key)?-1:1)*(e.shiftKey?15:1)));},true);
  for(const event of ['blur','resize','retouch:screen','retouch:viewport','retouch:before-zoom'])listen(root,event,()=>end());listen(w,'scroll',()=>end(),true);listen(canvas,'scroll',()=>end(),true);
  function tick(){if(!valid()){end();return;}raf=root.requestAnimationFrame(tick);}paint();surface.focus({preventScroll:true});if(initialPointer)begin(initialPointer);raf=root.requestAnimationFrame(tick);return ()=>end();
 }
 const api={pivot,mount};if(typeof module==='object'&&module.exports)module.exports=api;else root.RetouchLocalRotate=api;
})(typeof window==='object'?window:globalThis);
