(function(root){
 'use strict';
 function anchored(before,after,offset){
  const I=root.RetouchInspector||require('./inspector.js'),wanted=I.localPositionCorners(before,[[offset.x,offset.y]])[0],actual=I.localPositionCorners(after,[[0,0]])[0];
  return {...after,x:after.x+wanted.x-actual.x,y:after.y+wanted.y-actual.y};
 }
 function mount({target,frame,canvas,opener=root.document.activeElement,onCommit,onEnd,onError,current=()=>true,initial=null}){
  const I=root.RetouchInspector,w=target.ownerDocument.defaultView,doc=root.document;let g,space,bounds;
  try{g=I.localPositionGeometry(target);space=root.RetouchSVGDraw.nativeSpace(target.offsetParent);bounds=root.RetouchCanvasMove.limits(target,true);}catch(error){onError(error.message);return null;}
  const f=frame.getBoundingClientRect(),c=canvas.getBoundingClientRect(),zoom=f.width/w.innerWidth,left=Math.max(f.left,c.left),top=Math.max(f.top,c.top),right=Math.min(f.right,c.right),bottom=Math.min(f.bottom,c.bottom);
  if(right<=left||bottom<=top||!Number.isFinite(zoom)||zoom<=0){onError('Bring the layer into view before resizing.');return null;}
  const surface=doc.createElement('div');surface.className='canvas-move-surface canvas-local-resize-surface';surface.dataset.canvasMode='resize';surface.dataset.localMove=target.getAttribute('data-rt');surface.tabIndex=0;surface.setAttribute('aria-label','Resize layer on canvas');Object.assign(surface.style,{position:'fixed',left:left+'px',top:top+'px',width:right-left+'px',height:bottom-top+'px',zIndex:40,overflow:'hidden',touchAction:'none'});
  const svg=doc.createElementNS('http://www.w3.org/2000/svg','svg'),polygon=doc.createElementNS(svg.namespaceURI,'polygon');Object.assign(svg.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none'});polygon.setAttribute('fill','rgba(13,153,255,.06)');polygon.setAttribute('stroke','var(--accent)');polygon.setAttribute('stroke-width','2');svg.append(polygon);surface.append(svg);
  const fractions={nw:[0,0],n:[.5,0],ne:[1,0],e:[1,.5],se:[1,1],s:[.5,1],sw:[0,1],w:[0,.5]},names={nw:'top left',n:'top',ne:'top right',e:'right',se:'bottom right',s:'bottom',sw:'bottom left',w:'left'},handles=[];
  for(const [handle,p]of Object.entries(fractions)){const button=doc.createElement('button');button.type='button';button.dataset.resizeHandle=handle;button.setAttribute('aria-label','Resize '+names[handle]);Object.assign(button.style,{position:'absolute',width:'10px',height:'10px',minWidth:'0',padding:'0',border:'1px solid var(--accent)',background:'white',transform:'translate(-50%,-50%)'});surface.append(button);handles.push({button,handle,p});}
  const hint=doc.createElement('div');Object.assign(hint.style,{position:'absolute',bottom:'8px',left:'8px',padding:'6px 8px',background:'var(--panel)',border:'1px solid var(--line)',borderRadius:'4px',fontSize:'11px',pointerEvents:'none',maxWidth:'calc(100% - 16px)',boxSizing:'border-box'});surface.append(hint);
  const readouts=[...doc.querySelectorAll('input')].filter(input=>input.retouchDimension?.target===target).map(input=>({input,original:input.value,last:null,...input.retouchDimension}));
  const originalStyle=target.getAttribute('style'),previews=new Map(),cleanup=[];let expectedStyle=originalStyle,state=null,next=null,ended=false,raf,translation=null;
  const signature=()=>{const css=w.getComputedStyle(target);return [css.transform,css.rotate,css.scale,css.translate,css.transformOrigin,css.transformBox,css.zoom].join('|');};let expectedTransform=signature();
  function valid(){return target.isConnected&&opener?.isConnected&&space.current()&&current()&&target.getAttribute('style')===expectedStyle&&signature()===expectedTransform;}
  const listen=(el,event,fn,options)=>{el.addEventListener(event,fn,options);cleanup.push(()=>el.removeEventListener(event,fn,options));};
  function finish(commit=false){if(ended)return;const save=commit&&valid()?next:null,owned=target.getAttribute('style')===expectedStyle;ended=true;root.cancelAnimationFrame(raf);surface.remove();cleanup.forEach(fn=>fn());translation?.restore();[...previews.values()].reverse().forEach(p=>p.restore());if(owned){if(originalStyle===null)target.removeAttribute('style');else target.setAttribute('style',originalStyle);}for(const field of readouts)if(field.last!==null&&field.input.value===field.last)field.input.value=field.original;onEnd();if(save&&['x','y','width','height'].some(key=>Math.abs(save[key]-g[key])>1/32))onCommit({x:save.x-g.x,y:save.y-g.y,width:save.width,height:save.height},{keyboard:!!state?.keyboard});}
  const pagePoints=geometry=>I.localPositionCorners(geometry).map(p=>new w.DOMPoint(p.x,p.y).matrixTransform(space.matrix));
  function paint(geometry){const dock=doc.querySelector('.design-tool-dock')?.getBoundingClientRect();hint.style.bottom=Math.max(8,dock?bottom-dock.top+8:8)+'px';if(next){const css=w.getComputedStyle(target);for(const field of readouts)if(field.input.isConnected){field.last=field.box==='css'?css.getPropertyValue(field.axis):String(Math.round(geometry[field.axis]*100)/100);field.input.value=field.last;}}const points=pagePoints(geometry),screen=points.map(p=>({x:f.left+p.x*zoom-left,y:f.top+p.y*zoom-top}));polygon.setAttribute('points',screen.map(p=>p.x+','+p.y).join(' '));for(const {button,handle,p:[x,y]}of handles){const dx=(screen[1].x-screen[0].x)*(x-.5)+(screen[3].x-screen[0].x)*(y-.5),dy=(screen[1].y-screen[0].y)*(x-.5)+(screen[3].y-screen[0].y)*(y-.5),angle=(Math.atan2(dy,dx)*180/Math.PI+180)%180,cursor=['ew','nwse','ns','nesw'][Math.round(angle/45)%4];Object.assign(button.style,{left:screen[0].x+(screen[1].x-screen[0].x)*x+(screen[3].x-screen[0].x)*y+'px',top:screen[0].y+(screen[1].y-screen[0].y)*x+(screen[3].y-screen[0].y)*y+'px',cursor:cursor+'-resize'});}hint.textContent=Math.round(geometry.width*100)/100+' × '+Math.round(geometry.height*100)/100+' px · Shift: proportions · Option/Alt: center · Enter applies · Escape cancels';}
  function apply(modifiers){
   if(!valid())throw Error('The layer or frame changed during resizing.');
   const base=state.base,requested=root.RetouchCanvasMove.resize(base.width,base.height,state.handle,state.dx,state.dy,{...bounds,...modifiers});
   translation?.restore();translation=null;expectedStyle=target.getAttribute('style');
   const css=w.getComputedStyle(target);for(const axis of ['width','height']){if(!previews.has(axis))previews.set(axis,root.RetouchPaintPicker.propertyPreview({el:target,input:opener,property:axis}));previews.get(axis).update(root.RetouchReactSelection.dimensionValue(css,axis,requested[axis])+'px');expectedStyle=target.getAttribute('style');}
   const measured=I.localPositionGeometry(target);if(['width','height'].some(axis=>Math.abs(measured[axis]-requested[axis])>.6))throw Error('The layer’s size rules prevent this resize.');
   next=anchored(base,measured,requested);translation=root.RetouchPaintPicker.propertyPreview({el:target,input:opener,property:'translate'});translation.update(root.RetouchTranslateValues.add(measured.translate||'none',{x:next.x-measured.x,y:next.y-measured.y}));expectedStyle=target.getAttribute('style');expectedTransform=signature();paint(next);
  }
  function start(handle,event,keyboard=false){const base=next||g,points=pagePoints(base),a=(points[1].x-points[0].x)/base.width,b=(points[1].y-points[0].y)/base.width,c=(points[3].x-points[0].x)/base.height,d=(points[3].y-points[0].y)/base.height,det=a*d-b*c;if(Math.abs(det)<1e-9)throw Error('The layer has no resizable coordinate system.');state={handle,base,keyboard,id:event?.pointerId,x:event?.clientX,y:event?.clientY,dx:0,dy:0,a,b,c,d,det};}
  const modifiers=e=>({shiftKey:e.shiftKey,altKey:e.altKey});
  function move(e){if(!state||state.keyboard||e.pointerId!==state.id)return;try{const dx=(e.clientX-state.x)/zoom,dy=(e.clientY-state.y)/zoom;state.dx=(state.d*dx-state.c*dy)/state.det;state.dy=(-state.b*dx+state.a*dy)/state.det;apply(modifiers(e));}catch(error){finish();onError(error.message);}}
  listen(surface,'pointerdown',e=>{const handle=e.target.dataset.resizeHandle;if(e.button!==0)return;if(!handle){finish();return;}e.preventDefault();e.stopImmediatePropagation();try{e.target.focus({preventScroll:true});start(handle,e);surface.setPointerCapture(e.pointerId);}catch(error){finish();onError(error.message);}});
  const up=e=>{if(!state||state.id!==e.pointerId)return;e.preventDefault();move(e);finish(Math.hypot(e.clientX-state.x,e.clientY-state.y)>=4);};listen(surface,'pointermove',move);listen(surface,'pointerup',up);for(const event of ['pointercancel','lostpointercapture'])listen(surface,event,()=>finish());
  listen(root,'keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();finish();return;}if(!surface.contains(e.target)||e.metaKey||e.ctrlKey)return;if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();finish(true);return;}const direction={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key],handle=e.target.dataset.resizeHandle;if(!direction||!handle)return;e.preventDefault();e.stopImmediatePropagation();try{if(!state?.keyboard||state.handle!==handle)start(handle,null,true);state.dx+=direction[0];state.dy+=direction[1];apply(modifiers(e));}catch(error){finish();onError(error.message);}},true);
  for(const event of ['keydown','keyup'])listen(root,event,e=>{if(state&&['Shift','Alt'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();try{apply(modifiers(e));}catch(error){finish();onError(error.message);}}},true);
  for(const event of ['retouch:selection-layout','retouch:before-zoom','retouch:screen','retouch:viewport','resize','blur','pagehide'])listen(root,event,()=>finish());listen(root,'retouch:selection',e=>{if(e.detail!==target.getAttribute('data-rt'))finish();});listen(frame,'load',()=>finish());listen(w,'resize',()=>finish());listen(w,'scroll',()=>finish(),true);listen(canvas,'scroll',()=>finish());
  function observe(){if(ended)return;if(!valid()){finish();return;}raf=root.requestAnimationFrame(observe);}doc.body.append(surface);paint(g);handles.find(item=>item.handle==='se').button.focus({preventScroll:true});raf=root.requestAnimationFrame(observe);
  if(initial){try{const convert=e=>initial.framePointer?{pointerId:e.pointerId,clientX:f.left+e.clientX*zoom,clientY:f.top+e.clientY*zoom,shiftKey:e.shiftKey,altKey:e.altKey,preventDefault:()=>e.preventDefault()}:e;if(initial.framePointer){listen(w,'pointermove',e=>move(convert(e)),true);listen(w,'pointerup',e=>up(convert(e)),true);listen(w,'pointercancel',()=>finish(),true);listen(w,'lostpointercapture',()=>finish(),true);}start(initial.handle,convert(initial.event));if(!initial.released)(initial.framePointer?initial.target:surface).setPointerCapture(initial.event.pointerId);if(initial.move)move(convert(initial.move));if(initial.released&&initial.move)up(convert(initial.move));}catch(error){finish();onError(error.message);}}
  return ()=>finish();
 }
 const api={anchored,mount};if(typeof module==='object'&&module.exports)module.exports=api;else root.RetouchLocalResize=api;
})(typeof window==='object'?window:globalThis);
