(function(root){
 'use strict';
 let cancel=null,click=null;
 function pick(frame){cancel?.();return new Promise(resolve=>{
  const d=frame.contentDocument,w=d.defaultView,panel=document.createElement('div'),heading=document.createElement('strong'),search=document.createElement('input'),list=document.createElement('div'),note=document.createElement('p'),close=document.createElement('button'),outline=document.createElement('div'),listeners=[];
  panel.className='prototype-target-picker';panel.setAttribute('popover','manual');panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Choose scroll destination');heading.textContent='Choose destination';search.type='search';search.placeholder='Find a layer…';search.setAttribute('aria-label','Find scroll destination');close.textContent='Cancel';close.type='button';close.className='control-button';note.textContent='Click a layer on the page, or choose from the list. Escape cancels.';note.setAttribute('role','status');outline.className='prototype-target-outline';outline.setAttribute('aria-hidden','true');
  panel.append(heading,close,search,note,list);document.body.append(panel,outline);panel.showPopover();search.focus();
  const listen=(target,type,fn)=>{target.addEventListener(type,fn,true);listeners.push(()=>target.removeEventListener(type,fn,true));};
  function finish(value){if(cancel!==abort)return;cancel=null;click=null;listeners.forEach(fn=>fn());observer.disconnect();panel.remove();outline.remove();resolve(value);}
  const abort=()=>finish(null);cancel=abort;close.onclick=abort;
  function name(el){return el.getAttribute('data-rt-name')||el.getAttribute('aria-label')||el.getAttribute('alt')||el.textContent?.trim().replace(/\s+/g,' ').slice(0,65)||el.id||el.localName;}
  let sourceCounts=new Map(),idCounts=new Map();
  function count(){sourceCounts=new Map();idCounts=new Map();for(const el of d.querySelectorAll('[data-rt],[id]')){const id=el.getAttribute('data-rt');if(id)sourceCounts.set(id,(sourceCounts.get(id)||0)+1);if(el.id)idCounts.set(el.id,(idCounts.get(el.id)||0)+1);}}
  function valid(el){if(!el?.isConnected||!el.getClientRects().length||['script','style','link','meta','title'].includes(el.localName))return false;const id=el.getAttribute('data-rt');return id&&sourceCounts.get(id)===1&&(!el.id||idCounts.get(el.id)===1);}

  function highlight(el){if(!el){outline.hidden=true;return;}const rect=el.getBoundingClientRect(),frameRect=frame.getBoundingClientRect(),sx=frameRect.width/frame.clientWidth,sy=frameRect.height/frame.clientHeight;outline.hidden=false;Object.assign(outline.style,{left:frameRect.left+rect.left*sx+'px',top:frameRect.top+rect.top*sy+'px',width:rect.width*sx+'px',height:rect.height*sy+'px'});}
  function choose(el){count();if(!valid(el)){note.textContent='Choose one uniquely rendered layer. Repeated layers and duplicate IDs are ambiguous.';return;}finish(el);}
  function refresh(){count();list.replaceChildren();const query=search.value.toLowerCase(),nodes=[...d.querySelectorAll('[data-rt]')].filter(el=>valid(el)&&(name(el)+' '+el.id+' '+el.localName).toLowerCase().includes(query)).sort((a,b)=>Number(name(b).toLowerCase()===query)-Number(name(a).toLowerCase()===query));for(const el of nodes.slice(0,60)){const button=document.createElement('button');button.type='button';button.className='prototype-target-option';button.textContent=name(el);button.title=el.localName+(el.id?' #'+el.id:'');button.onclick=()=>choose(el);button.onfocus=button.onmouseenter=()=>highlight(el);list.append(button);}if(!nodes.length){const empty=document.createElement('p');empty.textContent='No matching layers.';list.append(empty);}else if(nodes.length>60){const more=document.createElement('p');more.textContent='Keep typing to narrow '+nodes.length+' layers.';list.append(more);}}
  const observer=new MutationObserver(refresh);observer.observe(d.body,{subtree:true,childList:true,attributes:true,attributeFilter:['id','data-rt','data-rt-name']});search.oninput=refresh;search.onkeydown=event=>{if(event.key==='ArrowDown'){event.preventDefault();list.querySelector('button')?.focus();}else if(event.key==='Enter'){event.preventDefault();list.querySelector('button')?.click();}};
  listen(w,'pointerdown',event=>{event.preventDefault();event.stopImmediatePropagation();});click=event=>{event.preventDefault();event.stopImmediatePropagation();choose(event.target?.closest?.('[data-rt]'));return true;};listen(w,'dblclick',event=>{event.preventDefault();event.stopImmediatePropagation();});listen(w,'mousemove',event=>highlight(event.target?.closest?.('[data-rt]')));listen(w,'scroll',()=>highlight(null));
  const escape=event=>{if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();abort();}};listen(root,'keydown',escape);listen(w,'keydown',event=>{if(event.key==='Escape'){escape(event);return;}event.stopImmediatePropagation();if(!['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(event.key)){event.preventDefault();if(event.key==='Tab')search.focus();}});listen(frame,'load',abort);listen(root,'retouch:selection',abort);listen(root,'retouch:before-zoom',abort);listen(root,'resize',()=>highlight(null));refresh();
 });}
 root.RetouchPrototypePicker={pick,click:event=>click?.(event)||false,cancel:()=>cancel?.()};
})(window);
