(function(root){
 'use strict';
 const I=RetouchInspector,V=RetouchPrototypeValues,S=RetouchPrototypeSpring,K=RetouchPrototypeKeys,host=root.RetouchPrototypeHost,panel=document.getElementById('panel'),body=document.getElementById('prototypePanel'),design=document.getElementById('designTab'),prototype=document.getElementById('prototypeTab');let active=false,busy=false,serial=0,selectionKey=null,opened=0;
 const triggers=[['click','On click'],['mouseenter','Mouse enter'],['mouseleave','Mouse leave'],['mousedown','Mouse down / Touch press'],['mouseup','Mouse up / Touch release'],['after-delay','After delay'],['keyboard','Keyboard']],actions=[['navigate','Navigate to'],['back','Back'],['scroll','Scroll to'],['open-overlay','Open overlay'],['swap-overlay','Swap overlay'],['close-overlay','Close overlay']];
 async function tab(next){if(busy)return;try{await host.prepare();active=next;if(!next)root.RetouchPrototypeDetails.dismiss();panel.classList.toggle('prototype-inspector',next);body.hidden=!next;design.classList.toggle('active',!next);prototype.classList.toggle('active',next);design.setAttribute('aria-selected',String(!next));prototype.setAttribute('aria-selected',String(next));design.tabIndex=next?-1:0;prototype.tabIndex=next?0:-1;if(next)render();}catch(error){host.error(error.message);}}
 design.onclick=()=>tab(false);prototype.onclick=()=>tab(true);
 for(const button of [design,prototype]){button.addEventListener('pointerdown',e=>e.preventDefault());button.addEventListener('keydown',async e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='End'||e.key==='ArrowRight';await tab(next);(next?prototype:design).focus();});}
 async function render(){if(!active||busy)return;const ticket=++serial,selection=host.selection();body.inert=true;root.RetouchPrototypeDetails.setBusy(true);
  let items=structuredClone(selection?.prototypeInteractions||[]),pages=[];if(selection?.prototypeEditable)try{pages=await host.pages();}catch{}if(ticket!==serial||!active)return;
  const key=selection?.id+'|'+JSON.stringify(selection?.context),detailState=key===selectionKey?root.RetouchPrototypeDetails.snapshot():null;if(key!==selectionKey){selectionKey=key;opened=0;}root.RetouchPrototypeDetails.reset();body.replaceChildren();body.inert=false;
  const section=I.section('Interactions');body.append(section);const status=I.note(section,'');status.setAttribute('role','status');
  if(!selection?.prototypeEditable){status.textContent=selection?.prototypeReason||'Select a layer to add an interaction.';return;}
  I.note(section,'Play interactions in Present mode. This source layer’s copies share these connections.');
  const rows=document.createElement('div');section.append(rows);
  async function save(next){if(busy)return;++serial;busy=true;body.inert=true;root.RetouchPrototypeDetails.setBusy(true);status.textContent='Saving…';try{await host.save(selection,next);status.textContent='Saved';}catch(error){status.textContent=error.message;return;}finally{busy=false;body.inert=false;root.RetouchPrototypeDetails.setBusy(false);}await render();}
  for(const [index,item]of items.entries()){
   const row=document.createElement('button');row.type='button';row.className='prototype-connection-row';row.dataset.index=String(index+1);row.setAttribute('aria-label','Edit interaction '+(index+1));
   const title=document.createElement('span'),summary=document.createElement('span'),arrow=document.createElement('span');title.textContent=item.trigger==='keyboard'?K.label(item.shortcut):triggers.find(([value])=>value===item.trigger)[1];summary.textContent=actions.find(([value])=>value===item.action)[1]+(item.destination?' · '+item.destination:'');title.id='prototype-trigger-summary-'+index;summary.id='prototype-action-summary-'+index;row.setAttribute('aria-describedby',title.id+' '+summary.id);arrow.textContent='→';arrow.setAttribute('aria-hidden','true');row.append(title,summary,arrow);rows.append(row);
   const card=document.createElement('fieldset');card.className='prototype-interaction';const legend=document.createElement('legend');legend.textContent=title.textContent+' → '+summary.textContent;card.append(legend);
   const details=root.RetouchPrototypeDetails.create(row,card,()=>{opened=null;});row.onclick=()=>{opened=index;details.open(true);};

   const draft={...item};
   const modify=()=>{const next=items.map((value,i)=>i===index?draft:value);try{V.validate(next);}catch(error){status.textContent=error.message;return;}return save(next);};
   const triggerControl=I.select(card,'Trigger '+(index+1),triggers.filter(([value])=>value===item.trigger||value==='keyboard'||!items.some(i=>i.trigger===value)),item.trigger,value=>{draft.trigger=value;if(value==='keyboard')draft.shortcut=K.next(items.filter((_,i)=>i!==index));else delete draft.shortcut;if(value==='after-delay')draft.delay=800;else delete draft.delay;modify();});
   const triggerRow=triggerControl.parentElement;details.dialog.querySelector('header strong').replaceWith(triggerControl);triggerRow.remove();
   if(item.trigger==='keyboard')root.RetouchPrototypeKeyPanel.mount(card,{value:item.shortcut,index:index+1,change:value=>{draft.shortcut=value;return modify();}});
   if(item.trigger==='after-delay'){const delay=document.createElement('input');delay.type='number';delay.min='1';delay.max='10000';delay.step='1';delay.value=item.delay;I.field(card,'Delay (ms) '+(index+1),delay);delay.onchange=()=>{draft.delay=Number(delay.value);modify();};I.note(card,'Runs once while this layer is mounted in the active preview. Covered or hidden previews pause the timer.');}
   I.select(card,'Action '+(index+1),actions,item.action,value=>{const destination=draft.destination;draft.action=value;delete draft.preserveScroll;delete draft.destination;delete draft.overlay;delete draft.transition;delete draft.scrollOffset;if(!['back','close-overlay'].includes(value))draft.destination=value==='scroll'?'top':(V.route(destination)?destination:pages.find(page=>page.url!==host.route())?.url||'/');if(value==='open-overlay')draft.overlay=V.overlay();modify();});
   if(['navigate','open-overlay','swap-overlay'].includes(item.action)){
    if(pages.length)I.select(card,'Destination page '+(index+1),[['','Custom URL'],...pages.map(page=>[page.url,page.path||page.url])],pages.some(page=>page.url===item.destination)?item.destination:'',value=>{if(value){draft.destination=value;modify();}});
    const input=document.createElement('input');input.value=item.destination;input.placeholder='/page';input.maxLength=2048;I.field(card,'Destination URL '+(index+1),input);input.addEventListener('change',()=>{draft.destination=input.value;modify();});
    if(item.action==='navigate'){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=!!item.preserveScroll;check.setAttribute('aria-label','Preserve scroll position '+(index+1));label.append(check,' Preserve scroll position');card.append(label);check.onchange=()=>{draft.preserveScroll=check.checked;modify();};}
   }else if(item.action==='scroll'){
    const input=document.createElement('input');input.value=item.destination;input.maxLength=256;I.field(card,'Destination element ID '+(index+1),input);input.addEventListener('change',()=>{draft.destination=input.value.replace(/^#/,'');modify();});
    for(const axis of ['x','y']){const offset=document.createElement('input');offset.type='number';offset.min='-100000';offset.max='100000';offset.step='any';offset.value=item.scrollOffset?.[axis]||0;I.field(card,'Scroll offset '+axis.toUpperCase()+' '+(index+1),offset);offset.onchange=()=>{draft.scrollOffset={x:0,y:0,...item.scrollOffset,[axis]:offset.value===''?NaN:Number(offset.value)};modify();};}
    I.note(card,'Offsets adjust the final scroll position in pixels. Negative values leave space before the destination.');
   }else I.note(card,item.action==='close-overlay'?'Dismiss the current overlay.':'Return to the previous page or dismiss the current overlay.');
   if(item.action==='open-overlay'){
    draft.overlay={...item.overlay};
    for(const key of ['width','height']){const input=document.createElement('input');input.type='number';input.min='80';input.max='7680';input.step='1';input.value=item.overlay[key];I.field(card,'Overlay '+key+' '+(index+1),input);input.onchange=()=>{draft.overlay[key]=Number(input.value);modify();};}
    I.select(card,'Overlay position '+(index+1),V.positions.map(value=>[value,value.split('-').map(word=>word[0].toUpperCase()+word.slice(1)).join(' ')]),item.overlay.position,value=>{draft.overlay.position=value;modify();});
    const color=document.createElement('input');color.type='color';color.value=item.overlay.background.slice(0,7);I.field(card,'Overlay background '+(index+1),color);color.onchange=()=>{draft.overlay.background=color.value+item.overlay.background.slice(7);modify();};
    const opacity=document.createElement('input');opacity.type='number';opacity.min='0';opacity.max='100';opacity.value=String(Math.round(parseInt(item.overlay.background.slice(7),16)/255*100));I.field(card,'Background opacity (%) '+(index+1),opacity);opacity.onchange=()=>{const value=Number(opacity.value);if(!opacity.value||!Number.isFinite(value)||value<0||value>100){status.textContent='Choose a background opacity from 0% to 100%.';return;}draft.overlay.background=item.overlay.background.slice(0,7)+Math.round(value*255/100).toString(16).padStart(2,'0');modify();};
    const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=item.overlay.closeOutside;check.setAttribute('aria-label','Close when clicking outside '+(index+1));label.append(check,' Close when clicking outside');card.append(label);check.onchange=()=>{draft.overlay.closeOutside=check.checked;modify();};
   }else if(item.action==='swap-overlay')I.note(card,'Replace the current overlay, keeping its size, position and background.');
   if(V.transitions[item.action]){
    const current=item.transition||{type:'instant'},names={'instant':'Instant','animate':'Animate','dissolve':'Dissolve','move-in':'Move in','move-out':'Move out','push':'Push','slide-in':'Slide in','slide-out':'Slide out'};
    I.select(card,'Animation '+(index+1),V.transitions[item.action].map(value=>[value,names[value]]),current.type,value=>{draft.transition=V.transition({type:value},item.action);modify();});
    if(current.type!=='instant'){
     draft.transition={...current};
     const duration=document.createElement('input');duration.type='number';duration.min='1';duration.max='10000';duration.step='1';duration.value=current.duration;duration.readOnly=current.easing?.type==='spring';if(duration.readOnly)duration.title='Duration follows the spring settling time.';I.field(card,'Duration (ms) '+(index+1),duration);duration.onchange=()=>{draft.transition.duration=Number(duration.value);modify();};
     const springName=current.easing?.type==='spring'?Object.keys(S.presets).find(name=>Object.entries(S.presets[name]).every(([key,value])=>current.easing[key]===value)):null;
     I.select(card,'Easing '+(index+1),[...V.easings.map(value=>[value,value.split('-').map(word=>word[0].toUpperCase()+word.slice(1)).join(' ')]),['custom','Custom Bézier'],...Object.keys(S.presets).map(name=>['spring-'+name,name[0].toUpperCase()+name.slice(1)+' spring']),['spring-custom','Custom spring']],typeof current.easing==='string'?current.easing:current.easing.type==='spring'?'spring-'+(springName||'custom'):'custom',value=>{draft.transition.easing=value==='custom'?{type:'cubic-bezier',values:[...(V.curves[current.easing]||current.easing.values||V.curves['ease-out'])]}:value.startsWith('spring-')?(value==='spring-custom'&&current.easing?.type==='spring'?current.easing:{type:'spring',...(S.presets[value.slice(7)]||S.presets.gentle)}):value;modify();});
     if(current.easing?.type==='cubic-bezier')root.RetouchPrototypeCurve.mount(card,{value:current.easing,index:index+1,duration:current.duration,change:value=>{draft.transition.easing=value;return modify();}});
     if(current.easing?.type==='spring')root.RetouchPrototypeSpringPanel.mount(card,{value:current.easing,index:index+1,change:value=>{draft.transition.easing=value;return modify();}});
     if(!['dissolve','animate'].includes(current.type))I.select(card,'Direction '+(index+1),[['left','Left'],['right','Right'],['top','Top'],['bottom','Bottom']],current.direction,value=>{draft.transition.direction=value;modify();});
    }
   }
   const remove=I.button('Remove',()=>{opened=Math.max(0,index-1);return save(items.filter((_,i)=>i!==index));});remove.setAttribute('aria-label','Remove interaction '+(index+1));card.append(remove);
   if(opened===index&&!document.body.classList.contains('presenting'))details.open();
   for(const label of card.querySelectorAll('.inspector-field > span'))label.textContent=label.textContent.replace(/ \d+$/,'').replace('Destination page','Destination').replace('Destination URL','URL').replace('Destination element ID','Element ID');
  }
  const nextTrigger=triggers.find(([value])=>value==='keyboard'||!items.some(i=>i.trigger===value))?.[0];
  const add=I.button('Add interaction',()=>{opened=items.length;return save([...items,{trigger:nextTrigger,...(nextTrigger==='keyboard'?{shortcut:K.next(items)}:{}),...(nextTrigger==='after-delay'?{delay:800}:{}),action:'navigate',destination:pages.find(page=>page.url!==host.route())?.url||'/'}]);});add.disabled=items.length>=32||!nextTrigger;add.textContent='+';add.setAttribute('aria-label','Add interaction');add.title='Add interaction';add.classList.add('prototype-add');section.querySelector('h3').append(add);
  root.RetouchPrototypeDetails.place();root.RetouchPrototypeDetails.restore(detailState);
  if(!items.length)I.note(section,'Connect this layer to another page, go back, or scroll to an element.');
 }
 root.addEventListener('retouch:selection',()=>queueMicrotask(render));root.addEventListener('retouch:prototype',render);
 root.RetouchPrototypePanel={refresh:render};
})(window);
