(function(root){
 'use strict';
 const button=document.createElement('button');button.type='button';button.id='exportScreen';button.textContent='Export screen';button.setAttribute('aria-label','Export screen');(document.querySelector('.screen-options-body')||document.getElementById('screenToolbar')).append(button);
 button.onclick=()=>{
  const dialog=document.createElement('dialog');dialog.className='screen-export-dialog';dialog.setAttribute('aria-label','Export screen');const title=document.createElement('h2');title.textContent='Export screen';const note=document.createElement('p');note.textContent='Export the visible viewport with its current page state.';
  const source=document.createElement('select');source.setAttribute('aria-label','Screen to export');const frames=[document.getElementById('app'),...document.querySelectorAll('.compare-surface iframe')].filter(frame=>{try{return frame.contentDocument?.body&&frame.contentDocument.URL!=='about:blank';}catch{return false;}});for(const [i,frame]of frames.entries()){const label=i===0?'Canvas':frame.title.replace(' comparison preview','');source.add(new Option(label+' · '+frame.contentWindow.innerWidth+' × '+frame.contentWindow.innerHeight,String(i)));}
  const area=document.createElement('select');area.setAttribute('aria-label','Export area');area.add(new Option('Visible viewport','viewport'));area.add(new Option('Full page','page'));area.onchange=()=>{note.textContent=area.value==='page'?'Full page keeps this screen width. Nested panels retain their current scroll position.':'Export the visible viewport with its current page state.';};
  const scale=document.createElement('select');scale.setAttribute('aria-label','Export scale');scale.add(new Option('1×','1'));scale.add(new Option('2×','2'));const status=document.createElement('p');status.setAttribute('role','status');const save=document.createElement('button');save.type='button';save.textContent='Export PNG';save.className='screen-export-primary';const close=document.createElement('button');close.type='button';close.textContent='Close';let controller=null;
  for(const control of [source,area,scale])control.addEventListener('change',()=>{status.textContent='';});
  close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{controller?.abort();dialog.remove();button.focus();});
  save.onclick=async()=>{if(controller)return;controller=new AbortController();save.disabled=true;source.disabled=true;scale.disabled=true;area.disabled=true;status.textContent='Preparing image…';try{const frame=frames[Number(source.value)];if(!frame?.isConnected)throw Error('This screen is no longer open.');if(!frame.contentDocument?.body||frame.contentDocument.URL==='about:blank')throw Error('Wait for this screen to finish loading.');const snapshot=root.RetouchCaptureDocument({sourceDocument:frame.contentDocument,exportState:true});if(snapshot.warnings.length)throw Error(snapshot.warnings.join(' '));const response=await fetch('/rt/__api/screen-export',{method:'POST',headers:{'content-type':'application/json','x-retouch-token':root.__RT_TOKEN},body:JSON.stringify({...snapshot,width:frame.contentWindow.innerWidth,height:frame.contentWindow.innerHeight,scale:Number(scale.value),area:area.value}),signal:controller.signal});if(!response.ok){const result=await response.json();throw Error(result.reason||'Could not export this screen.');}const blob=await response.blob();if(!dialog.open)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(snapshot.title||'retouch-screen').replace(/[^a-z\d_-]+/gi,'-').slice(0,80)+(area.value==='page'?'-full-page':'')+'@'+scale.value+'x.png';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='PNG exported.';}catch(error){if(dialog.open)status.textContent=error.name==='AbortError'?'Export canceled.':error.message;}finally{controller=null;save.disabled=false;source.disabled=false;scale.disabled=false;area.disabled=false;}};
  const areaLabel=document.createElement('label'),sourceLabel=document.createElement('label'),scaleLabel=document.createElement('label'),footer=document.createElement('footer');areaLabel.textContent='Area';areaLabel.append(area);sourceLabel.textContent='Screen';sourceLabel.append(source);scaleLabel.textContent='Scale';scaleLabel.append(scale);footer.append(close,save);dialog.append(title,note,sourceLabel,areaLabel,scaleLabel,status,footer);document.body.append(dialog);dialog.showModal();source.focus();
 };
})(window);
