(function(root){
 'use strict';
 const button=document.createElement('button');button.type='button';button.id='exportScreen';button.textContent='Export screen';button.setAttribute('aria-label','Export screen');(document.querySelector('.screen-options-body')||document.getElementById('screenToolbar')).append(button);
 button.onclick=()=>{
  const dialog=document.createElement('dialog');dialog.className='screen-export-dialog';dialog.setAttribute('aria-label','Export screen');const title=document.createElement('h2');title.textContent='Export screen';const note=document.createElement('p');note.textContent='Export the visible viewport with its current page state.';
  const source=document.createElement('select');source.setAttribute('aria-label','Screen to export');const frames=[document.getElementById('app'),...document.querySelectorAll('.compare-surface iframe')].filter(frame=>{try{return frame.contentDocument?.body&&frame.contentDocument.URL!=='about:blank';}catch{return false;}});for(const [i,frame]of frames.entries()){const label=i===0?'Canvas':frame.title.replace(' comparison preview','');source.add(new Option(label+' · '+frame.contentWindow.innerWidth+' × '+frame.contentWindow.innerHeight,String(i)));}
  const area=document.createElement('select');area.setAttribute('aria-label','Export area');area.add(new Option('Visible viewport','viewport'));area.add(new Option('Full page','page'));const selectedNodes=root.RetouchExportSelection?.()||[];if(selectedNodes.length)area.add(new Option('Selected layers','selection'));area.onchange=()=>{note.textContent=area.value==='selection'?'Export selected layers within their bounds. Shadows outside those bounds are clipped.':area.value==='page'?'Full page keeps this screen width. Nested panels retain their current scroll position.':'Export the visible viewport with its current page state.';};
  const format=document.createElement('select');format.setAttribute('aria-label','Export format');format.add(new Option('PNG','png'));format.add(new Option('JPEG','jpeg'));const quality=document.createElement('input');quality.type='number';quality.min='1';quality.max='100';quality.step='1';quality.required=true;quality.value='90';quality.setAttribute('aria-label','JPEG quality');const qualityLabel=document.createElement('label');qualityLabel.textContent='Quality · 1–100';qualityLabel.append(quality);qualityLabel.hidden=true;
  const transparent=document.createElement('input');transparent.type='checkbox';transparent.setAttribute('aria-label','Transparent background');const transparentLabel=document.createElement('label');transparentLabel.className='screen-export-transparent';transparentLabel.append(transparent,document.createTextNode('Transparent background'));const transparentHint=document.createElement('p');transparentHint.className='hint';transparentHint.textContent='Backgrounds painted by the page remain visible.';
  const scale=document.createElement('select');scale.setAttribute('aria-label','Export scale');for(const value of [0.5,1,1.5,2,3,4])scale.add(new Option(value+'×',String(value)));scale.add(new Option('Custom…','custom'));scale.value='1';const customScale=document.createElement('input');customScale.type='number';customScale.min='0.01';customScale.max='8';customScale.step='any';customScale.required=true;customScale.value='1';customScale.setAttribute('aria-label','Custom export scale');const customScaleLabel=document.createElement('label');customScaleLabel.textContent='Custom scale · 0.01–8×';customScaleLabel.append(customScale);customScaleLabel.hidden=true;scale.onchange=()=>{customScaleLabel.hidden=scale.value!=='custom';};const exportScale=()=>Number(scale.value==='custom'?customScale.value:scale.value);const status=document.createElement('p');status.setAttribute('role','status');const save=document.createElement('button');save.type='button';save.textContent='Export PNG';save.className='screen-export-primary';const close=document.createElement('button');close.type='button';close.textContent='Close';let controller=null;
  format.onchange=()=>{qualityLabel.hidden=format.value!=='jpeg';transparentLabel.hidden=transparentHint.hidden=format.value!=='png';save.textContent='Export '+(format.value==='jpeg'?'JPEG':'PNG');};
  for(const control of [source,area,scale,customScale,format,quality,transparent])control.addEventListener('change',()=>{status.textContent='';});
  close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{controller?.abort();dialog.remove();button.focus();});
  save.onclick=async()=>{if(controller||format.value==='jpeg'&&!quality.reportValidity()||scale.value==='custom'&&!customScale.reportValidity())return;controller=new AbortController();save.disabled=true;source.disabled=true;scale.disabled=true;area.disabled=true;format.disabled=true;quality.disabled=true;transparent.disabled=true;customScale.disabled=true;status.textContent='Preparing image…';try{const frame=frames[Number(source.value)];if(!frame?.isConnected)throw Error('This screen is no longer open.');if(!frame.contentDocument?.body||frame.contentDocument.URL==='about:blank')throw Error('Wait for this screen to finish loading.');if(area.value==='selection'&&selectedNodes.some(el=>!el.isConnected||el.ownerDocument!==frame.contentDocument))throw Error('Choose the canvas containing the selected layers.');const snapshot=root.RetouchCaptureDocument({sourceDocument:frame.contentDocument,exportState:true,selectedNodes:area.value==='selection'?selectedNodes:[]});if(area.value==='selection'&&snapshot.selectionIds.length!==selectedNodes.length)throw Error('A selected layer could not be captured.');if(snapshot.warnings.length)throw Error(snapshot.warnings.join(' '));const response=await fetch('/rt/__api/screen-export',{method:'POST',headers:{'content-type':'application/json','x-retouch-token':root.__RT_TOKEN},body:JSON.stringify({...snapshot,width:frame.contentWindow.innerWidth,height:frame.contentWindow.innerHeight,scale:exportScale(),area:area.value,format:format.value,...(format.value==='jpeg'?{quality:Number(quality.value)}:{transparent:transparent.checked})}),signal:controller.signal});if(!response.ok){const result=await response.json();throw Error(result.reason||'Could not export this screen.');}const blob=await response.blob();if(!dialog.open)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(snapshot.title||'retouch-screen').replace(/[^a-z\d_-]+/gi,'-').slice(0,80)+(area.value==='page'?'-full-page':area.value==='selection'?'-selection':'')+'@'+exportScale()+'x.'+(format.value==='jpeg'?'jpg':'png');document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent=(format.value==='jpeg'?'JPEG':'PNG')+' exported.';}catch(error){if(dialog.open)status.textContent=error.name==='AbortError'?'Export canceled.':error.message;}finally{controller=null;save.disabled=false;source.disabled=false;scale.disabled=false;area.disabled=false;format.disabled=false;quality.disabled=false;transparent.disabled=false;customScale.disabled=false;}};
  const formatLabel=document.createElement('label'),areaLabel=document.createElement('label'),sourceLabel=document.createElement('label'),scaleLabel=document.createElement('label'),footer=document.createElement('footer');formatLabel.textContent='Format';formatLabel.append(format);areaLabel.textContent='Area';areaLabel.append(area);sourceLabel.textContent='Screen';sourceLabel.append(source);scaleLabel.textContent='Scale';scaleLabel.append(scale);footer.append(close,save);dialog.append(title,note,sourceLabel,areaLabel,formatLabel,scaleLabel,customScaleLabel,qualityLabel,transparentLabel,transparentHint,status,footer);document.body.append(dialog);dialog.showModal();source.focus();
 };
})(window);
