(function(root){
 'use strict';
 const button=document.createElement('button');button.type='button';button.id='exportScreen';button.textContent='Export screen';button.setAttribute('aria-label','Export screen');(document.querySelector('.screen-options-body')||document.getElementById('screenToolbar')).append(button);
 function open({selection=false,opener=button}={}){
  if(document.querySelector('dialog[open]')||selection&&!root.RetouchExportSelection?.().length)return;
  const dialog=document.createElement('dialog');dialog.className='screen-export-dialog';dialog.setAttribute('aria-label','Export screen');const title=document.createElement('h2');title.textContent='Export screen';const note=document.createElement('p');note.textContent='Export the visible viewport with its current page state.';
  const source=document.createElement('select');source.setAttribute('aria-label','Screen to export');const openFrames=[document.getElementById('app'),...document.querySelectorAll('.compare-surface iframe')].filter(Boolean);const frames=openFrames.filter(frame=>{try{return frame.contentDocument?.body&&frame.contentDocument.URL!=='about:blank';}catch{return false;}});for(const [i,frame]of frames.entries()){const label=frame.id==='app'?'Canvas':frame.title.replace(' comparison preview','');source.add(new Option(label+' · '+frame.contentWindow.innerWidth+' × '+frame.contentWindow.innerHeight,String(i)));}if(openFrames.length>1)source.add(new Option('All open screens (ZIP)','all'));const allScreens=()=>source.value==='all';
  const area=document.createElement('select');area.setAttribute('aria-label','Export area');area.add(new Option('Visible viewport','viewport'));area.add(new Option('Full page','page'));const selectedNodes=root.RetouchExportSelection?.()||[];if(selectedNodes.length)area.add(new Option('Selected layers','selection'));area.onchange=()=>{outputLabel.hidden=area.value!=='selection';updateButton();note.textContent=area.value==='selection'?'Export selected layers within their bounds. Shadows outside those bounds are clipped.':area.value==='page'?'Full page keeps this screen width. Nested panels retain their current scroll position.':'Export the visible viewport with its current page state.';};
  const output=document.createElement('select');output.setAttribute('aria-label','Selection output');output.add(new Option('Together as one file','together'));output.add(new Option('Separate files (ZIP · up to 20)','separate'));output.options[1].disabled=selectedNodes.length>20;const outputLabel=document.createElement('label');outputLabel.textContent='Export selected layers';outputLabel.append(output);outputLabel.hidden=true;const separate=()=>area.value==='selection'&&output.value==='separate';const zipped=()=>allScreens()||separate();
  const format=document.createElement('select');format.setAttribute('aria-label','Export format');format.add(new Option('PNG','png'));format.add(new Option('JPEG','jpeg'));format.add(new Option('PDF','pdf'));const quality=document.createElement('input');quality.type='number';quality.min='1';quality.max='100';quality.step='1';quality.required=true;quality.value='90';quality.setAttribute('aria-label','JPEG quality');const qualityLabel=document.createElement('label');qualityLabel.textContent='Quality · 1–100';qualityLabel.append(quality);qualityLabel.hidden=true;
  const transparent=document.createElement('input');transparent.type='checkbox';transparent.checked=selection;transparent.setAttribute('aria-label','Transparent background');const transparentLabel=document.createElement('label');transparentLabel.className='screen-export-transparent';transparentLabel.append(transparent,document.createTextNode('Transparent background'));const transparentHint=document.createElement('p');transparentHint.className='hint';transparentHint.textContent='Backgrounds painted by the page remain visible.';
  const scale=document.createElement('select');scale.setAttribute('aria-label','Export scale');for(const value of [0.5,1,1.5,2,3,4])scale.add(new Option(value+'×',String(value)));scale.add(new Option('Custom…','custom'));scale.value='1';const customScale=document.createElement('input');customScale.type='number';customScale.min='0.01';customScale.max='8';customScale.step='any';customScale.required=true;customScale.value='1';customScale.setAttribute('aria-label','Custom export scale');const customScaleLabel=document.createElement('label');customScaleLabel.textContent='Custom scale · 0.01–8×';customScaleLabel.append(customScale);customScaleLabel.hidden=true;scale.onchange=()=>{customScaleLabel.hidden=scale.value!=='custom';};const exportScale=()=>Number(scale.value==='custom'?customScale.value:scale.value);const status=document.createElement('p');status.setAttribute('role','status');const save=document.createElement('button');save.type='button';save.textContent='Export PNG';save.className='screen-export-primary';const close=document.createElement('button');close.type='button';close.textContent='Close';let controller=null;
  const updateButton=()=>{save.textContent=zipped()?'Export ZIP':'Export '+(format.value.toUpperCase());};output.onchange=updateButton;source.onchange=()=>{const selectionOption=[...area.options].find(option=>option.value==='selection');if(selectionOption)selectionOption.disabled=allScreens();if(allScreens()&&area.value==='selection')area.value='viewport';area.onchange();};
  format.onchange=()=>{qualityLabel.hidden=format.value!=='jpeg';transparentLabel.hidden=transparentHint.hidden=format.value!=='png';updateButton();};
  for(const control of [source,area,scale,customScale,format,quality,transparent,output])control.addEventListener('change',()=>{status.textContent='';});
  close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{controller?.abort();dialog.remove();(opener?.isConnected?opener:button).focus();});
  save.onclick=async()=>{if(controller||format.value==='jpeg'&&!quality.reportValidity()||scale.value==='custom'&&!customScale.reportValidity())return;controller=new AbortController();save.disabled=true;source.disabled=true;scale.disabled=true;area.disabled=true;format.disabled=true;quality.disabled=true;transparent.disabled=true;customScale.disabled=true;output.disabled=true;status.textContent='Preparing export…';try{const chosen=allScreens()?openFrames:[frames[Number(source.value)]];const snapshots=chosen.map(frame=>{if(!frame?.isConnected)throw Error('This screen is no longer open.');if(!frame.contentDocument?.body||frame.contentDocument.URL==='about:blank')throw Error('Wait for this screen to finish loading.');if(area.value==='selection'&&selectedNodes.some(el=>!el.isConnected||el.ownerDocument!==frame.contentDocument))throw Error('Choose the canvas containing the selected layers.');const captured=root.RetouchCaptureDocument({sourceDocument:frame.contentDocument,exportState:true,selectedNodes:area.value==='selection'?selectedNodes:[]});if(area.value==='selection'&&captured.selectionIds.length!==selectedNodes.length)throw Error('A selected layer could not be captured.');const name=frame.id==='app'?'Canvas':frame.title.replace(' comparison preview','');if(captured.warnings.length)throw Error(name+': '+captured.warnings.join(' '));return {...captured,name,width:frame.contentWindow.innerWidth,height:frame.contentWindow.innerHeight};});const snapshot=snapshots[0];const response=await fetch('/rt/__api/screen-export',{method:'POST',headers:{'content-type':'application/json','x-retouch-token':root.__RT_TOKEN},body:JSON.stringify({...(allScreens()?{screens:snapshots}:snapshot),scale:exportScale(),area:area.value,separate:separate(),format:format.value,...(format.value==='jpeg'?{quality:Number(quality.value)}:{transparent:format.value==='png'&&transparent.checked})}),signal:controller.signal});if(!response.ok){const result=await response.json();throw Error(result.reason||'Could not export this screen.');}const blob=await response.blob();if(!dialog.open)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(allScreens()?'retouch-screens':snapshot.title||'retouch-screen').replace(/[^a-z\d_-]+/gi,'-').slice(0,80)+(area.value==='page'?'-full-page':area.value==='selection'?'-selection':'')+'@'+exportScale()+'x.'+(zipped()?'zip':format.value==='jpeg'?'jpg':format.value);document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent=(zipped()?'ZIP':format.value.toUpperCase())+' exported.';}catch(error){if(dialog.open)status.textContent=error.name==='AbortError'?'Export canceled.':error.message;}finally{controller=null;save.disabled=false;source.disabled=false;scale.disabled=false;area.disabled=false;format.disabled=false;quality.disabled=false;transparent.disabled=false;customScale.disabled=false;output.disabled=false;}};
  const formatLabel=document.createElement('label'),areaLabel=document.createElement('label'),sourceLabel=document.createElement('label'),scaleLabel=document.createElement('label'),footer=document.createElement('footer');formatLabel.textContent='Format';formatLabel.append(format);areaLabel.textContent='Area';areaLabel.append(area);sourceLabel.textContent='Screen';sourceLabel.append(source);scaleLabel.textContent='Scale';scaleLabel.append(scale);footer.append(close,save);dialog.append(title,note,sourceLabel,areaLabel,outputLabel,formatLabel,scaleLabel,customScaleLabel,qualityLabel,transparentLabel,transparentHint,status,footer);if(selection){area.value='selection';area.onchange();}document.body.append(dialog);dialog.showModal();source.focus();
 }
 button.onclick=()=>open();
 root.RetouchScreenExport={open};
})(window);
