(function(root){
 'use strict';
 const sizeLocks=new Set();
 const A=()=>root.RetouchSVGAffine,keys=['nw','n','ne','e','se','s','sw','w'],names=['top left','top','top right','right','bottom right','bottom','bottom left','left'];
 const matrix=m=>[m.a,m.b,m.c,m.d,m.e,m.f];
 function measure(target){const w=target.ownerDocument.defaultView;for(let el=target;el;el=el.parentElement){const css=w.getComputedStyle(el);if(css.perspective!=='none'||css.transform!=='none'&&new w.DOMMatrix(css.transform).is2D===false)throw Error('Perspective transforms cannot be resized on canvas yet.');}const g=target.getBBox(),m=target.getScreenCTM();if(!m||![g.x,g.y,g.width,g.height,...matrix(m)].every(Number.isFinite)||g.width<0||g.height<0||!g.width&&!g.height||Math.abs(m.a*m.d-m.b*m.c)<1e-9)throw Error('Choose a visible vector with an invertible transform.');const r=target.getBoundingClientRect(),ps=[[g.x,g.y],[g.x+g.width,g.y],[g.x+g.width,g.y+g.height],[g.x,g.y+g.height]].map(([x,y])=>new w.DOMPoint(x,y).matrixTransform(m)),xs=ps.map(p=>p.x),ys=ps.map(p=>p.y);if(Math.abs(Math.min(...xs)-r.left)>.75||Math.abs(Math.max(...xs)-r.right)>.75||Math.abs(Math.min(...ys)-r.top)>.75||Math.abs(Math.max(...ys)-r.bottom)>.75)throw Error('This vector’s screen transform cannot be measured accurately.');return {g:{x:g.x,y:g.y,width:g.width,height:g.height},m};}
 function reason(target,info,probe=false){
  if(!info.svgTransform?.editable||!target?.isConnected)return info.svgTransform?.reason||'Select an editable SVG vector.';
  if(target.querySelector('animate,animateTransform,set')||target.getAnimations?.().length)return 'Pause vector animations before resizing.';
  if(target.style.getPropertyValue('transform'))return 'CSS controls this vector’s transform. Edit those styles before resizing its SVG geometry.';
  const ownMatrix=el=>{const parent=el.parentElement?.getScreenCTM?.(),own=el.getScreenCTM?.();try{return parent&&own?matrix(parent.inverse().multiply(own)):null;}catch{return null;}};
  if(!A().equivalent(ownMatrix(target),info.svgTransform.matrix))return 'CSS controls this vector’s transform. Edit those styles before resizing its SVG geometry.';
  if(probe){const copy=target.cloneNode(true),test=[1.123,.1,.2,.917,1.173,2.271];copy.setAttribute('transform',A().format(test));copy.style.setProperty('visibility','hidden','important');try{target.after(copy);if(!A().equivalent(ownMatrix(copy),test))return 'CSS controls this vector’s transform. Edit those styles before resizing its SVG geometry.';}finally{copy.remove();}}
  return null;
 }
 function frameClip(frame,canvas){const f=frame.getBoundingClientRect(),c=canvas.getBoundingClientRect();return {f,left:Math.max(c.left,f.left),top:Math.max(c.top,f.top),right:Math.min(c.right,f.right),bottom:Math.min(c.bottom,f.bottom),scale:f.width/frame.contentWindow.innerWidth};}
 function positions(g,m,scale){const width=g.width||12/(Math.hypot(m.a,m.b)*scale),height=g.height||12/(Math.hypot(m.c,m.d)*scale),x=g.width?g.x:g.x-width/2,y=g.height?g.y:g.y-height/2;return [[0,0],[.5,0],[1,0],[1,.5],[1,1],[.5,1],[0,1],[0,.5]].map(([a,b])=>({x:m.a*(x+a*width)+m.c*(y+b*height)+m.e,y:m.b*(x+a*width)+m.d*(y+b*height)+m.f}));}
 function makeButton(i){const button=root.document.createElement('button');button.type='button';button.tabIndex=-1;button.setAttribute('aria-label','Resize vector from '+names[i]);button.title='Resize vector · Shift: keep proportions · Option / Alt: from center';Object.assign(button.style,{position:'absolute',width:'10px',height:'10px',padding:'0',border:'1px solid var(--accent)',background:'white',pointerEvents:'auto',touchAction:'none',transform:'translate(-50%,-50%)',cursor:['nwse-resize','ns-resize','nesw-resize','ew-resize','nwse-resize','ns-resize','nesw-resize','ew-resize'][i]});return button;}
 function controls({frame,canvas,onStart}){
  const host=root.document.createElement('div');host.className='svg-resize-handles';Object.assign(host.style,{position:'fixed',pointerEvents:'none',zIndex:30,overflow:'hidden'});host.hidden=true;root.document.body.append(host);let active;
  const buttons=keys.map((key,i)=>{const b=makeButton(i);b.onpointerdown=e=>{if(e.button!==0||!active)return;e.preventDefault();e.stopPropagation();onStart(active.info,active.target,e,key);};b.onclick=e=>{if(e.detail===0&&active)onStart(active.info,active.target,null,key);};host.append(b);return b;});
  return {update(target,info){active=null;host.hidden=true;if(!target||!info||reason(target,info))return;try{const {g,m}=measure(target),c=frameClip(frame,canvas),points=positions(g,m,c.scale),seen=[];Object.assign(host.style,{left:c.left+'px',top:c.top+'px',width:c.right-c.left+'px',height:c.bottom-c.top+'px'});buttons.forEach((b,i)=>{const x=c.f.left+points[i].x*c.scale-c.left,y=c.f.top+points[i].y*c.scale-c.top;b.hidden=x<6||y<6||x>c.right-c.left-6||y>c.bottom-c.top-6||seen.some(p=>Math.hypot(x-p.x,y-p.y)<9);if(!b.hidden)seen.push({x,y});b.style.left=x+'px';b.style.top=y+'px';});active={target,info};host.hidden=false;}catch{}}};
 }
 function sizeFields(section,info,target,{save,current}){
  const I=root.RetouchInspector,key=info.file+'|'+info.id;let locked=sizeLocks.has(key),initial;
  try{const blocked=reason(target,info,true);if(blocked)throw Error(blocked);initial=measure(target);}catch(error){I.note(section,error.message);return;}
  const size=A().dimensions(info.svgTransform.matrix,initial.g);if(!size)return;
  const inputs={};
  for(const axis of ['width','height']){const input=root.document.createElement('input');input.type='text';input.inputMode='decimal';input.value=String(Math.round(size[axis]*10000)/10000);input.oninput=()=>input.setCustomValidity('');input.onchange=()=>{try{if(!current())throw Error('Re-select this vector before editing its size.');const blocked=reason(target,info,true);if(blocked)throw Error(blocked);const g=measure(target).g;if(['x','y','width','height'].some(k=>Math.abs(g[k]-initial.g[k])>.01))throw Error('The vector changed. Re-select it before resizing.');const value=input.value.trim(),matrix=/^(?:\d+\.?\d*|\.\d+)$/.test(value)&&A().resizeDimension(info.svgTransform.matrix,g,axis,Number(value),locked);if(!matrix)throw Error('Enter a size greater than 0 and at most 100000 SVG units.');save(matrix);}catch(error){input.setCustomValidity(error.message);input.reportValidity();}};I.field(section,'Vector '+axis,input);inputs[axis]=input;}
  const lock=I.button('Lock vector proportions',()=>{locked=!locked;if(locked)sizeLocks.add(key);else sizeLocks.delete(key);lock.setAttribute('aria-pressed',String(locked));});lock.setAttribute('aria-pressed',String(locked));lock.setAttribute('aria-label','Lock vector proportions');lock.title='Lock vector proportions';lock.innerHTML='<svg viewBox="0 0 20 20" width="16" height="16" fill="none" stroke="currentColor" aria-hidden="true"><path d="M8 6V4a3 3 0 0 1 6 0v4a3 3 0 0 1-3 3M12 14v2a3 3 0 0 1-6 0v-4a3 3 0 0 1 3-3M10 6v8"/></svg>';lock.disabled=!size.width||!size.height;section.append(lock);I.note(section,'Size along the vector’s axes, including its SVG transform. Shared across screen sizes.');return inputs;
 }
 function mount({target,info,frame,canvas,current,onCommit,onEnd,onError,initialPointer=null,handle='se'}){
  let data;try{const blocked=reason(target,info,true);if(blocked)throw Error(blocked);data=measure(target);}catch(error){onError(error.message);return null;}
  const c=frameClip(frame,canvas),w=target.ownerDocument.defaultView,base=info.svgTransform.matrix,original=target.getAttribute('transform'),g=data.g,virtual={width:g.width||12/(Math.hypot(data.m.a,data.m.b)*c.scale),height:g.height||12/(Math.hypot(data.m.c,data.m.d)*c.scale)};
  const surface=root.document.createElement('div');surface.className='svg-resize-surface';surface.setAttribute('aria-label','Resize SVG vector on canvas');Object.assign(surface.style,{position:'fixed',left:c.left+'px',top:c.top+'px',width:c.right-c.left+'px',height:c.bottom-c.top+'px',overflow:'hidden',touchAction:'none',zIndex:40});const button=makeButton(keys.indexOf(handle));button.tabIndex=0;
  const hint=root.document.createElement('div');Object.assign(hint.style,{position:'fixed',bottom:'116px',left:'50%',transform:'translateX(-50%)',padding:'8px 12px',border:'1px solid var(--line)',borderRadius:'6px',background:'var(--panel)',color:'var(--ink)',fontSize:'11px',pointerEvents:'none'});surface.append(button,hint);root.document.body.append(surface);
  let ended=false,last=null,changed=false,next=base,bounds={...g},drag=null,keyboard={x:0,y:0},raf;const cleanup=[];
  const listen=(el,key,fn,options)=>{el.addEventListener(key,fn,options);cleanup.push(()=>el.removeEventListener(key,fn,options));};
  // Chromium re-hints SVG glyphs when their transform changes. Measure the
  // original transform for ownership checks so that rounding is not an edit.
  function baselineBounds(){if(last===null||!(target.localName==='text'||target.querySelector('text')))return target.getBBox();const copy=target.cloneNode(true);if(original===null)copy.removeAttribute('transform');else copy.setAttribute('transform',original);copy.style.setProperty('visibility','hidden','important');try{target.after(copy);return copy.getBBox();}finally{copy.remove();}}
  function valid(){if(!current()||!target.isConnected||target.getAttribute('transform')!==(last??original))return false;try{const now=measure(target),before=baselineBounds(),f=frame.getBoundingClientRect();if(!['x','y','width','height'].every(k=>Math.abs(before[k]-g[k])<.01)||!['left','top','width','height'].every(k=>Math.abs(f[k]-c.f[k])<.5))return false;const local=A().resize(A().identity(),g,bounds),expected=A().multiply(matrix(data.m),local);return A().equivalent(matrix(now.m),expected);}catch{return false;}}
  function end(commit=false){if(ended)return;const save=commit&&changed&&valid();ended=true;root.cancelAnimationFrame(raf);cleanup.forEach(fn=>fn());surface.remove();if(last!==null&&target.getAttribute('transform')===last){if(original===null)target.removeAttribute('transform');else target.setAttribute('transform',original);}onEnd();if(save)onCommit(next);}
  function point(e){return new w.DOMPoint((e.clientX-c.f.left)/c.scale,(e.clientY-c.f.top)/c.scale).matrixTransform(data.m.inverse());}
  function paint(){const p=positions(bounds,data.m,c.scale)[keys.indexOf(handle)];button.style.left=c.f.left+p.x*c.scale-c.left+'px';button.style.top=c.f.top+p.y*c.scale-c.top+'px';const size=A().dimensions(base,bounds);hint.textContent=Math.round(size.width*100)/100+' × '+Math.round(size.height*100)/100+' · Shift: proportions · Option / Alt: center · Arrows: 1 · Enter applies · Escape cancels';}
  function update(dx,dy,modifiers={}){if(!valid()){end();return;}try{if(modifiers.shiftKey&&(!g.width||!g.height)){if(!g.width)dx=0;if(!g.height)dy=0;}const d=root.RetouchCanvasMove.resize(virtual.width,virtual.height,handle,dx,dy,{altKey:!!modifiers.altKey,shiftKey:!!g.width&&!!g.height&&!!modifiers.shiftKey,minWidth:g.width?1:virtual.width,minHeight:g.height?1:virtual.height,maxWidth:100000,maxHeight:100000});bounds={x:g.x+d.x,y:g.y+d.y,width:g.width?d.width:d.width-virtual.width,height:g.height?d.height:d.height-virtual.height};next=A().resize(base,g,bounds);if(!next)throw Error('Keep vector bounds within the supported range.');last=A().format(next);changed=!A().equivalent(next,base);target.setAttribute('transform',last);paint();}catch(error){end();onError(error.message);}}
  function begin(e){if(e.button!==0)return;e.preventDefault();e.stopPropagation();drag={id:e.pointerId,a:point(e)};button.setPointerCapture(e.pointerId);}
  listen(button,'pointerdown',begin);listen(button,'pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const p=point(e);update(p.x-drag.a.x,p.y-drag.a.y,e);});listen(button,'pointerup',e=>{if(drag&&e.pointerId===drag.id){drag=null;end(true);}});listen(button,'pointercancel',()=>end());listen(button,'lostpointercapture',()=>{if(drag)end();});
  listen(surface,'keydown',e=>{if(e.ctrlKey||e.metaKey||!['Escape','Enter','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape')end();else if(e.key==='Enter')end(true);else{const step=e.shiftKey?10:1;if(e.key==='ArrowLeft')keyboard.x-=step;if(e.key==='ArrowRight')keyboard.x+=step;if(e.key==='ArrowUp')keyboard.y-=step;if(e.key==='ArrowDown')keyboard.y+=step;update(keyboard.x,keyboard.y,{altKey:e.altKey});}},true);
  for(const key of ['blur','resize','retouch:screen','retouch:viewport','retouch:before-zoom'])listen(root,key,()=>end());listen(w,'scroll',()=>end(),true);listen(canvas,'scroll',()=>end(),true);const tick=()=>{if(!valid()){end();return;}raf=root.requestAnimationFrame(tick);};paint();button.focus({preventScroll:true});if(initialPointer)begin(initialPointer);raf=root.requestAnimationFrame(tick);return ()=>end();
 }
 const api={measure,reason,positions,controls,sizeFields,mount};if(typeof module==='object'&&module.exports)module.exports=api;else root.RetouchSVGResize=api;
})(typeof window==='object'?window:globalThis);
