(function(root){
 'use strict';
 const sizeLocks=new Set(),alignmentTargets=new Map();
 const A=()=>root.RetouchSVGAffine,keys=['nw','n','ne','e','se','s','sw','w'],names=['top left','top','top right','right','bottom right','bottom','bottom left','left'];
 const nudgeDelta=(m,x,y)=>{const d=m[0]*m[3]-m[1]*m[2];return Math.abs(d)<1e-9?null:{x:(m[3]*x-m[2]*y)/d,y:(m[0]*y-m[1]*x)/d};};
 const constrainRatio=(locked,modifiers={})=>!modifiers.ctrlKey&&(locked||!!modifiers.shiftKey);
 const matrix=m=>[m.a,m.b,m.c,m.d,m.e,m.f];
 function maskDefinition(target){const mask=target.closest('mask');return mask?.parentElement?.matches('[data-rt-mask-group]')&&mask.getAttribute('maskContentUnits')==='userSpaceOnUse'?mask:null;}
 function screenBounds(target){
  if(!maskDefinition(target))return target.getBoundingClientRect();
  const g=target.getBBox(),m=target.getScreenCTM();if(!m)throw Error('The mask coordinate system is unavailable.');
  const points=[[g.x,g.y],[g.x+g.width,g.y],[g.x+g.width,g.y+g.height],[g.x,g.y+g.height]].map(([x,y])=>({x:m.a*x+m.c*y+m.e,y:m.b*x+m.d*y+m.f})),left=Math.min(...points.map(p=>p.x)),top=Math.min(...points.map(p=>p.y)),right=Math.max(...points.map(p=>p.x)),bottom=Math.max(...points.map(p=>p.y));
  return {x:left,y:top,left,top,right,bottom,width:right-left,height:bottom-top};
 }
 function measure(target){const w=target.ownerDocument.defaultView;for(let el=target;el;el=el.parentElement){const css=w.getComputedStyle(el);if(css.perspective!=='none'||css.transform!=='none'&&new w.DOMMatrix(css.transform).is2D===false)throw Error('Perspective transforms cannot be resized on canvas yet.');}const g=target.getBBox(),m=target.getScreenCTM();if(!m||![g.x,g.y,g.width,g.height,...matrix(m)].every(Number.isFinite)||g.width<0||g.height<0||!g.width&&!g.height||Math.abs(m.a*m.d-m.b*m.c)<1e-9)throw Error('Choose a visible vector with an invertible transform.');const r=screenBounds(target),ps=[[g.x,g.y],[g.x+g.width,g.y],[g.x+g.width,g.y+g.height],[g.x,g.y+g.height]].map(([x,y])=>new w.DOMPoint(x,y).matrixTransform(m)),xs=ps.map(p=>p.x),ys=ps.map(p=>p.y);if(Math.abs(Math.min(...xs)-r.left)>.75||Math.abs(Math.max(...xs)-r.right)>.75||Math.abs(Math.min(...ys)-r.top)>.75||Math.abs(Math.max(...ys)-r.bottom)>.75)throw Error('This vector’s screen transform cannot be measured accurately.');return {g:{x:g.x,y:g.y,width:g.width,height:g.height},m};}
 function reason(target,info,probe=false){
  if(info.svgBooleanOwner&&!info.svgBooleanGroup&&!info.booleanOperandPreview)return 'Edit original geometry in the Boolean group section.';
  if(!info.svgTransform?.editable||!target?.isConnected)return info.svgTransform?.reason||'Select an editable SVG vector.';
  if(target.querySelector('animate,animateTransform,set')||target.getAnimations?.().length)return 'Pause vector animations before resizing.';
  if(target.style.getPropertyValue('transform'))return 'CSS controls this vector’s transform. Edit those styles before resizing its SVG geometry.';
  const ownMatrix=el=>{const parent=(el.parentElement===maskDefinition(el)?el.parentElement.parentElement:el.parentElement)?.getScreenCTM?.(),own=el.getScreenCTM?.();try{return parent&&own?matrix(parent.inverse().multiply(own)):null;}catch{return null;}};
  if(!A().equivalent(ownMatrix(target),info.svgTransform.matrix))return 'CSS controls this vector’s transform. Edit those styles before resizing its SVG geometry.';
  if(probe&&!info.svgStrokeSource&&!target.querySelector('[data-rt-stroke-alignment]')){const copy=target.cloneNode(true),test=[1.123,.1,.2,.917,1.173,2.271];copy.setAttribute('transform',A().format(test));copy.style.setProperty('visibility','hidden','important');try{target.after(copy);if(!A().equivalent(ownMatrix(copy),test))return 'CSS controls this vector’s transform. Edit those styles before resizing its SVG geometry.';}finally{copy.remove();}}
  return null;
 }
 function frameClip(frame,canvas){const f=frame.getBoundingClientRect(),c=canvas.getBoundingClientRect();return {f,left:Math.max(c.left,f.left),top:Math.max(c.top,f.top),right:Math.min(c.right,f.right),bottom:Math.min(c.bottom,f.bottom),scale:f.width/frame.contentWindow.innerWidth};}
 function positions(g,m,scale){const width=g.width||12/(Math.hypot(m.a,m.b)*scale),height=g.height||12/(Math.hypot(m.c,m.d)*scale),x=g.width?g.x:g.x-width/2,y=g.height?g.y:g.y-height/2;return [[0,0],[.5,0],[1,0],[1,.5],[1,1],[.5,1],[0,1],[0,.5]].map(([a,b])=>({x:m.a*(x+a*width)+m.c*(y+b*height)+m.e,y:m.b*(x+a*width)+m.d*(y+b*height)+m.f}));}
 function makeButton(i){const button=root.document.createElement('button');button.type='button';button.tabIndex=-1;button.setAttribute('aria-label','Resize vector from '+names[i]);button.title='Resize vector · Shift: keep proportions · Control: unlock proportions · Option / Alt: from center';Object.assign(button.style,{position:'absolute',zIndex:2,width:'10px',height:'10px',padding:'0',border:'1px solid var(--accent)',background:'white',pointerEvents:'auto',touchAction:'none',transform:'translate(-50%,-50%)',cursor:['nwse-resize','ns-resize','nesw-resize','ew-resize','nwse-resize','ns-resize','nesw-resize','ew-resize'][i]});return button;}
 function rotationPositions(g,m,scale){const ps=positions(g,m,scale),center={x:m.a*(g.x+g.width/2)+m.c*(g.y+g.height/2)+m.e,y:m.b*(g.x+g.width/2)+m.d*(g.y+g.height/2)+m.f};return [0,2,4,6].map(i=>{const p=ps[i],dx=p.x-center.x,dy=p.y-center.y,length=Math.hypot(dx,dy)||1;return {x:p.x+dx/length*18/scale,y:p.y+dy/length*18/scale};});}
 function rotationButton(i){const b=makeButton(i);b.setAttribute('aria-label','Rotate vector from '+names[i]);b.title='Rotate vector · Shift: snap to 15°';Object.assign(b.style,{zIndex:1,width:'24px',height:'24px',border:'0',background:'transparent',cursor:'grab'});return b;}
 function controls({frame,canvas,onStart,onRotate}){
  const host=root.document.createElement('div');host.className='svg-resize-handles';Object.assign(host.style,{position:'fixed',pointerEvents:'none',zIndex:30,overflow:'hidden'});host.hidden=true;root.document.body.append(host);let active;
  const buttons=keys.map((key,i)=>{const b=makeButton(i);b.onpointerdown=e=>{if(e.button!==0||!active)return;e.preventDefault();e.stopPropagation();onStart(active.info,active.target,e,key);};b.onclick=e=>{if(e.detail===0&&active)onStart(active.info,active.target,null,key);};host.append(b);return b;});
  const rotations=[0,2,4,6].map(i=>{const b=rotationButton(i);b.onpointerdown=e=>{if(e.button!==0||!active)return;e.preventDefault();e.stopPropagation();onRotate?.(active.info,active.target,e,keys[i]);};host.append(b);return b;});
  return {update(target,info){active=null;host.hidden=true;if(!target||!info||reason(target,info))return;try{const {g,m}=measure(target),c=frameClip(frame,canvas),points=positions(g,m,c.scale),seen=[];Object.assign(host.style,{left:c.left+'px',top:c.top+'px',width:c.right-c.left+'px',height:c.bottom-c.top+'px'});buttons.forEach((b,i)=>{const x=c.f.left+points[i].x*c.scale-c.left,y=c.f.top+points[i].y*c.scale-c.top;b.hidden=x<6||y<6||x>c.right-c.left-6||y>c.bottom-c.top-6||seen.some(p=>Math.hypot(x-p.x,y-p.y)<9);if(!b.hidden)seen.push({x,y});b.style.left=x+'px';b.style.top=y+'px';});rotationPositions(g,m,c.scale).forEach((p,i)=>{const b=rotations[i],x=c.f.left+p.x*c.scale-c.left,y=c.f.top+p.y*c.scale-c.top;b.hidden=x<12||y<12||x>c.right-c.left-12||y>c.bottom-c.top-12;b.style.left=x+'px';b.style.top=y+'px';});active={target,info};host.hidden=false;}catch{}}};
 }
 function scrubField(input,info,target,{current,matrixFor,min,max,render=()=>{}}){
  root.RetouchInspector.numericLabelDrag(input,raw=>{try{return {value:root.RetouchNumericExpression.evaluate(raw),min,max};}catch{return null;}});
  input.retouchNumericPreview=()=>{
   const blocked=reason(target,info,true);if(blocked)throw Error(blocked);if(!current())throw Error('Re-select this vector before editing.');const original=target.getAttribute('transform'),data=measure(target),g=data.g,w=target.ownerDocument.defaultView,parent=new w.DOMMatrix(matrix(data.m)).multiply(new w.DOMMatrix(info.svgTransform.matrix).inverse());let last=original,expected=data.m;
   const valid=()=>{if(!current()||!target.isConnected||target.getAttribute('transform')!==last)return false;try{const actual=target.getBBox(),screen=matrix(target.getScreenCTM()),want=matrix(expected);return ['x','y','width','height'].every(k=>Math.abs(actual[k]-g[k])<.01)&&screen.every((v,i)=>Math.abs(v-want[i])<.1);}catch{return false;}};
   return {current:valid,update:value=>{if(!valid())throw Error('The vector changed. Re-select it.');const matrix=matrixFor(value,g);if(!matrix)throw Error('Keep this value within the supported range.');last=A().format(matrix);expected=parent.multiply(new w.DOMMatrix(matrix));target.setAttribute('transform',last);render(matrix);},restore:()=>{if(target.getAttribute('transform')===last){if(original===null)target.removeAttribute('transform');else target.setAttribute('transform',original);}render(info.svgTransform.matrix);}};
  };input.retouchNumericHandle(input,{canvas:true,keyboardOnly:true,keys:['ArrowDown','ArrowUp'],onCommit:()=>root.RetouchPanelFocus?.queue(input)});return input;
 }
 function positionFields(section,info,target,{save,current,onCanvas}){
  const I=root.RetouchInspector;let initial;try{const blocked=reason(target,info,true);if(blocked)throw Error(blocked);initial=measure(target);}catch(error){I.note(section,error.message);return;}
  const pose=A().pose(info.svgTransform.matrix,initial.g);if(!pose)return;const inputs={};
  const alignmentKey=info.file+'|'+info.id;let alignmentTarget=alignmentTargets.get(alignmentKey)||'parent';
  const toolbar=root.RetouchSelectionLayout.alignmentToolbar((mode,event,button)=>{try{if(!current())throw Error('Re-select this vector before aligning.');const S=root.RetouchSVGSelection,{members}=S.capture([info],[target]),container=alignmentTarget==='viewport'||event.shiftKey?target.ownerSVGElement:target.parentElement===maskDefinition(target)?target.parentElement.parentElement:target.parentElement;if(!container?.isConnected)throw Error('Choose a vector with a visible alignment container.');const matrices=S.alignmentMatrices(members,mode,container.getBoundingClientRect()),next=matrices[info.id];if(!A().equivalent(next,info.svgTransform.matrix)){root.RetouchPanelFocus?.queue(button);save(next);}}catch(error){I.note(section,error.message,'refused');}});
  toolbar.setAttribute('aria-label','Align vector');for(const button of toolbar.querySelectorAll('button'))button.title+=' · Shift: align to SVG viewport';section.append(toolbar);
  I.select(section,'Align to',[['parent','Parent'],['viewport','SVG viewport']],alignmentTarget,value=>{alignmentTarget=value;alignmentTargets.set(alignmentKey,value);});

  for(const axis of ['x','y','rotation']){const input=root.document.createElement('input');input.type='text';input.inputMode='decimal';input.value=String(Math.round((axis==='rotation'?-pose[axis]:pose[axis])*10000)/10000);input.oninput=()=>input.setCustomValidity('');input.onchange=()=>{try{if(!current())throw Error('Re-select this vector before editing its position.');const blocked=reason(target,info,true);if(blocked)throw Error(blocked);const g=measure(target).g;if(['x','y','width','height'].some(k=>Math.abs(g[k]-initial.g[k])>.01))throw Error('The vector changed. Re-select it before editing.');const value=root.RetouchNumericExpression.evaluate(input.value),matrix=A().setPose(info.svgTransform.matrix,g,axis,value*(axis==='rotation'?-1:1));if(!matrix)throw Error(axis==='rotation'?'Enter an angle from -360 to 360 degrees.':'Enter a position within 100000 SVG units of the parent origin.');input.value=String(Math.round(value*10000)/10000);if(!A().equivalent(matrix,info.svgTransform.matrix))save(matrix);}catch(error){input.setCustomValidity(error.message);input.reportValidity();}};root.RetouchNumericExpression.field(input);I.field(section,axis==='rotation'?'Vector rotation (°)':'Vector '+axis.toUpperCase(),input);inputs[axis]=input;scrubField(input,info,target,{current,matrixFor:(value,g)=>A().setPose(info.svgTransform.matrix,g,axis,value*(axis==='rotation'?-1:1)),min:axis==='rotation'?-360:-100000,max:axis==='rotation'?360:100000,render:matrix=>{const pose=A().pose(matrix,initial.g);for(const other of ['x','y','rotation'])if(other!==axis&&inputs[other])inputs[other].value=String(Math.round((other==='rotation'?-pose[other]:pose[other])*10000)/10000);}});}
  const flips=root.RetouchFlip.mount(target,()=>{});flips.classList.add('svg-flip-controls');
  for(const button of flips.querySelectorAll('button')){button.disabled=false;button.title=button.getAttribute('aria-label')+' around the vector center';button.onclick=()=>{if(!current())return;try{const blocked=reason(target,info,true);if(blocked)throw Error(blocked);const g=measure(target).g;if(['x','y','width','height'].some(k=>Math.abs(g[k]-initial.g[k])>.01))throw Error('The vector changed. Re-select it before flipping.');const next=A().reflect(info.svgTransform.matrix,g,button.dataset.flipAxis);if(!next)throw Error('Keep the reflected vector within the supported range.');root.RetouchPanelFocus?.queue(button);save(next);}catch(error){I.note(section,error.message,'refused');}};}section.append(flips);
  if(onCanvas){const button=I.button('Rotate vector on canvas',onCanvas);button.dataset.canvasTool='svg-rotate';section.append(button);}
  I.note(section,'X/Y locates the vector’s transformed origin in its SVG parent. Rotation keeps its center fixed. Shared across screen sizes.');
 }
 function sizeFields(section,info,target,{save,current}){
  const I=root.RetouchInspector,key=info.file+'|'+info.id;let locked=sizeLocks.has(key),initial;
  try{const blocked=reason(target,info,true);if(blocked)throw Error(blocked);initial=measure(target);}catch(error){I.note(section,error.message);return;}
  const size=A().dimensions(info.svgTransform.matrix,initial.g);if(!size)return;
  const inputs={};
  for(const axis of ['width','height']){const input=root.document.createElement('input');input.type='text';input.inputMode='decimal';input.value=String(Math.round(size[axis]*10000)/10000);input.oninput=()=>input.setCustomValidity('');input.onchange=()=>{try{if(!current())throw Error('Re-select this vector before editing its size.');const blocked=reason(target,info,true);if(blocked)throw Error(blocked);const g=measure(target).g;if(['x','y','width','height'].some(k=>Math.abs(g[k]-initial.g[k])>.01))throw Error('The vector changed. Re-select it before resizing.');const value=root.RetouchNumericExpression.evaluate(input.value),matrix=A().resizeDimension(info.svgTransform.matrix,g,axis,value,locked);if(!matrix)throw Error('Enter a size greater than 0 and at most 100000 SVG units.');input.value=String(Math.round(value*10000)/10000);if(!A().equivalent(matrix,info.svgTransform.matrix))save(matrix);}catch(error){input.setCustomValidity(error.message);input.reportValidity();}};root.RetouchNumericExpression.field(input);I.field(section,'Vector '+axis,input);inputs[axis]=input;scrubField(input,info,target,{current,matrixFor:(value,g)=>A().resizeDimension(info.svgTransform.matrix,g,axis,value,locked),min:.0001,max:100000,render:matrix=>{const size=A().dimensions(matrix,initial.g);for(const other of ['width','height'])if(other!==axis&&inputs[other])inputs[other].value=String(Math.round(size[other]*10000)/10000);}});}
  const lock=I.button('Lock vector proportions',()=>{locked=!locked;if(locked)sizeLocks.add(key);else sizeLocks.delete(key);lock.setAttribute('aria-pressed',String(locked));});lock.setAttribute('aria-pressed',String(locked));lock.setAttribute('aria-label','Lock vector proportions');lock.title='Lock vector proportions';lock.innerHTML='<svg viewBox="0 0 20 20" width="16" height="16" fill="none" stroke="currentColor" aria-hidden="true"><path d="M8 6V4a3 3 0 0 1 6 0v4a3 3 0 0 1-3 3M12 14v2a3 3 0 0 1-6 0v-4a3 3 0 0 1 3-3M10 6v8"/></svg>';lock.disabled=!size.width||!size.height;section.append(lock);I.note(section,'Size along the vector’s axes, including its SVG transform. Shared across screen sizes.');return inputs;
 }
 function mount({target,info,frame,canvas,current,onCommit,onEnd,onError,onPreview=null,outline=false,initialPointer=null,handle='se',action='resize',framePointer=false,initialMove=null,initialReleased=false,initialKey=null}){
  let data;try{const blocked=reason(target,info,true);if(blocked)throw Error(blocked);data=measure(target);}catch(error){onError(error.message);return null;}
  const c=frameClip(frame,canvas),w=target.ownerDocument.defaultView,base=info.svgTransform.matrix,original=target.getAttribute('transform'),g=data.g,virtual={width:g.width||12/(Math.hypot(data.m.a,data.m.b)*c.scale),height:g.height||12/(Math.hypot(data.m.c,data.m.d)*c.scale)};
  const rotating=action==='rotate',moving=action==='move',parentMatrix=new w.DOMMatrix(matrix(data.m)).multiply(new w.DOMMatrix(base).inverse()),center=new w.DOMPoint(g.x+g.width/2,g.y+g.height/2).matrixTransform(new w.DOMMatrix(base)),initialAngle=A().pose(base,g).rotation;
  const surface=root.document.createElement('div');surface.className='svg-resize-surface';surface.setAttribute('aria-label',rotating?'Rotate SVG vector on canvas':moving?'Move SVG vector on canvas':'Resize SVG vector on canvas');Object.assign(surface.style,{position:'fixed',left:c.left+'px',top:c.top+'px',width:c.right-c.left+'px',height:c.bottom-c.top+'px',overflow:'hidden',touchAction:'none',zIndex:40});const button=rotating?rotationButton(keys.indexOf(handle)):makeButton(keys.indexOf(handle));if(rotating){button.textContent='↻';button.style.color='var(--accent)';}if(moving){button.setAttribute('aria-label','Move vector');button.title='Move vector · Shift: lock axis';button.textContent='✥';Object.assign(button.style,{width:'24px',height:'24px',cursor:'move',color:'var(--accent)'});}if(moving&&(framePointer||initialKey))button.style.opacity='0';button.tabIndex=0;
  const hint=root.document.createElement('div');Object.assign(hint.style,{position:'fixed',bottom:'116px',left:'50%',transform:'translateX(-50%)',padding:'8px 12px',border:'1px solid var(--line)',borderRadius:'6px',background:'var(--panel)',color:'var(--ink)',fontSize:'11px',pointerEvents:'none'});surface.append(button,hint);
  let previewOutline=null;if(outline){const svg=root.document.createElementNS('http://www.w3.org/2000/svg','svg');Object.assign(svg.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',overflow:'visible'});previewOutline=root.document.createElementNS(svg.namespaceURI,'polygon');previewOutline.setAttribute('fill','none');previewOutline.setAttribute('stroke','var(--accent)');previewOutline.setAttribute('stroke-width','1');svg.append(previewOutline);surface.prepend(svg);}root.document.body.append(surface);
  let ended=false,last=null,changed=false,next=base,bounds={...g},drag=null,keyboard={x:0,y:0},raf;const cleanup=[],heldKeys=new Set(),startRect=screenBounds(target),paintSnaps=moving?root.RetouchSVGSnapping.mount(surface,c):()=>{};
  const capture=framePointer?target:button,eventTarget=framePointer?w:button;
  const listen=(el,key,fn,options)=>{el.addEventListener(key,fn,options);cleanup.push(()=>el.removeEventListener(key,fn,options));};
  // Chromium re-hints SVG glyphs when their transform changes. Measure the
  // original transform for ownership checks so that rounding is not an edit.
  function baselineBounds(){if(last===null||!(target.localName==='text'||target.querySelector('text')))return target.getBBox();const copy=target.cloneNode(true);if(original===null)copy.removeAttribute('transform');else copy.setAttribute('transform',original);copy.style.setProperty('visibility','hidden','important');try{target.after(copy);return copy.getBBox();}finally{copy.remove();}}
  function valid(){if(!current()||!target.isConnected||target.getAttribute('transform')!==(last??original))return false;try{const now=measure(target),before=baselineBounds(),f=frame.getBoundingClientRect();if(!['x','y','width','height'].every(k=>Math.abs(before[k]-g[k])<.01)||!['left','top','width','height'].every(k=>Math.abs(f[k]-c.f[k])<.5))return false;const expected=matrix(parentMatrix.multiply(new w.DOMMatrix(next)));return A().equivalent(matrix(now.m),expected);}catch{return false;}}
  function end(commit=false){if(ended)return;const save=commit&&changed&&valid();ended=true;root.cancelAnimationFrame(raf);cleanup.forEach(fn=>fn());surface.remove();if(last!==null&&target.getAttribute('transform')===last){if(original===null)target.removeAttribute('transform');else target.setAttribute('transform',original);}onEnd();if(save)onCommit(next);}
  function point(e){return new w.DOMPoint(framePointer?e.clientX:(e.clientX-c.f.left)/c.scale,framePointer?e.clientY:(e.clientY-c.f.top)/c.scale).matrixTransform((rotating||moving?parentMatrix:data.m).inverse());}
  function publish(){try{onPreview?.(next);paint();}catch(error){end();onError(error.message);}}
  function paint(){if(previewOutline){const m=target.getScreenCTM();previewOutline.setAttribute('points',[[g.x,g.y],[g.x+g.width,g.y],[g.x+g.width,g.y+g.height],[g.x,g.y+g.height]].map(([x,y])=>{const p=new w.DOMPoint(x,y).matrixTransform(m);return [c.f.left+p.x*c.scale-c.left,c.f.top+p.y*c.scale-c.top].join(',');}).join(' '));}const p=moving?new w.DOMPoint(g.x+g.width/2,g.y+g.height/2).matrixTransform(parentMatrix.multiply(new w.DOMMatrix(next))):rotating?rotationPositions(g,parentMatrix.multiply(new w.DOMMatrix(next)),c.scale)[[0,2,4,6].indexOf(keys.indexOf(handle))]:positions(bounds,data.m,c.scale)[keys.indexOf(handle)];button.style.left=c.f.left+p.x*c.scale-c.left+'px';button.style.top=c.f.top+p.y*c.scale-c.top+'px';const size=A().dimensions(base,bounds);if(moving){const pose=A().pose(next,g);hint.textContent='X '+Math.round(pose.x*100)/100+' · Y '+Math.round(pose.y*100)/100+' · Shift: lock axis · Control: no snapping · '+(initialKey?'Arrows: 1 · Shift: 10 · Release applies':framePointer?'Release applies':'Arrows: 1 · Enter applies')+' · Escape cancels';return;}if(rotating){hint.textContent=Math.round(-A().pose(next,g).rotation*100)/100+'° · Shift: snap 15° · Arrows: 1° · Enter applies · Escape cancels';return;}hint.textContent=Math.round(size.width*100)/100+' × '+Math.round(size.height*100)/100+' · '+(sizeLocks.has(info.file+'|'+info.id)?'Proportions locked · Control: unlock':'Shift: proportions')+' · Option / Alt: center · Arrows: 1 · Enter applies · Escape cancels';}
  function update(dx,dy,modifiers={}){if(!valid()){end();return;}try{const proportional=constrainRatio(sizeLocks.has(info.file+'|'+info.id),modifiers);if(proportional&&(!g.width||!g.height)){if(!g.width)dx=0;if(!g.height)dy=0;}const d=root.RetouchCanvasMove.resize(virtual.width,virtual.height,handle,dx,dy,{altKey:!!modifiers.altKey,shiftKey:!!g.width&&!!g.height&&proportional,minWidth:g.width?1:virtual.width,minHeight:g.height?1:virtual.height,maxWidth:100000,maxHeight:100000});bounds={x:g.x+d.x,y:g.y+d.y,width:g.width?d.width:d.width-virtual.width,height:g.height?d.height:d.height-virtual.height};next=A().resize(base,g,bounds);if(!next)throw Error('Keep vector bounds within the supported range.');last=A().format(next);changed=!A().equivalent(next,base);target.setAttribute('transform',last);publish();}catch(error){end();onError(error.message);}}
  function rotate(delta,snap=false){if(!valid()){end();return;}let angle=initialAngle+delta;if(snap)angle=Math.round(angle/15)*15;angle=((angle+180)%360+360)%360-180;next=A().setPose(base,g,'rotation',angle);if(!next){end();onError('Keep the rotated vector within the supported range.');return;}last=A().format(next);changed=!A().equivalent(next,base);target.setAttribute('transform',last);publish();}
  function move(dx,dy,constrain=false,snapping=false){if(!valid()){end();return;}const screen=root.RetouchSVGSnapping.movement(matrix(parentMatrix),dx,dy,constrain),snapped=snapping?root.RetouchCanvasMove.snap(startRect,screen,root.RetouchSVGSnapping.targets(target),{tolerance:6/c.scale,lock:screen.lock}):screen,delta=nudgeDelta(matrix(parentMatrix),snapped.x,snapped.y);paintSnaps(snapped);if(!delta){end();return;}dx=delta.x;dy=delta.y;next=base.slice();next[4]+=dx;next[5]+=dy;if(!A().valid(next)){end();onError('Keep the vector within 100000 SVG units.');return;}last=A().format(next);changed=!A().equivalent(next,base);target.setAttribute('transform',last);publish();}
  function begin(e){if(e.button!==0)return;e.preventDefault();e.stopPropagation();drag={id:e.pointerId,a:point(e)};if(!initialReleased)capture.setPointerCapture(e.pointerId);}
  if(!framePointer)listen(button,'pointerdown',begin);const applyModifiers=e=>{if(!drag?.p)return;const p=drag.p;if(moving)move(p.x-drag.a.x,p.y-drag.a.y,e.shiftKey,!e.ctrlKey);else if(rotating)rotate((Math.atan2(p.y-center.y,p.x-center.x)-Math.atan2(drag.a.y-center.y,drag.a.x-center.x))*180/Math.PI,e.shiftKey);else update(p.x-drag.a.x,p.y-drag.a.y,e);};const pointerMove=e=>{if(!drag||e.pointerId!==drag.id)return;drag.p=point(e);applyModifiers(e);};listen(eventTarget,'pointermove',pointerMove,framePointer);listen(eventTarget,'pointerup',e=>{if(drag&&e.pointerId===drag.id){drag=null;end(true);}},framePointer);listen(eventTarget,'pointercancel',()=>end(),framePointer);listen(eventTarget,'lostpointercapture',()=>{if(drag)end();},framePointer);
  for(const type of ['keydown','keyup'])listen(root,type,e=>{if(!e.isComposing&&['Shift','Control','Alt'].includes(e.key))applyModifiers(e);});
  const keyDown=e=>{if(e.ctrlKey||e.metaKey||!['Escape','Enter','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape')end();else if(e.key==='Enter')end(true);else{if(rotating){keyboard.x+=(e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1)*(e.shiftKey?15:1);rotate(keyboard.x);return;}if(initialKey)heldKeys.add(e.key);const step=e.shiftKey?10:1;if(e.key==='ArrowLeft')keyboard.x-=step;if(e.key==='ArrowRight')keyboard.x+=step;if(e.key==='ArrowUp')keyboard.y-=step;if(e.key==='ArrowDown')keyboard.y+=step;if(moving){const delta=initialKey?nudgeDelta(matrix(parentMatrix),keyboard.x,keyboard.y):keyboard;if(delta)move(delta.x,delta.y);}else update(keyboard.x,keyboard.y,{altKey:e.altKey});}};listen(surface,'keydown',keyDown,true);
  if(initialKey)listen(root,'keyup',e=>{if(!heldKeys.delete(e.key))return;e.preventDefault();e.stopImmediatePropagation();if(!heldKeys.size)end(true);},true);
  for(const key of ['blur','resize','retouch:screen','retouch:viewport','retouch:before-zoom'])listen(root,key,()=>end());listen(w,'scroll',()=>end(),true);listen(canvas,'scroll',()=>end(),true);const tick=()=>{if(!valid()){end();return;}raf=root.requestAnimationFrame(tick);};paint();button.focus({preventScroll:true});if(initialKey)keyDown(initialKey);if(initialPointer)begin(initialPointer);if(initialMove)pointerMove(initialMove);if(initialReleased){root.queueMicrotask(()=>end(true));return ()=>end();}raf=root.requestAnimationFrame(tick);return ()=>end();
 }
 const api={screenBounds,nudgeDelta,constrainRatio,measure,reason,positions,rotationPositions,controls,positionFields,sizeFields,mount};if(typeof module==='object'&&module.exports)module.exports=api;else root.RetouchSVGResize=api;
})(typeof window==='object'?window:globalThis);
