(function(){
 'use strict';
 const I=RetouchInspector,open=document.createElement('button');open.type='button';open.id='variableLibrary';open.textContent='Variables';document.getElementById('toolbar').append(open);
 const dialog=document.createElement('dialog');dialog.className='variable-library';dialog.setAttribute('aria-label','Variable collections');document.body.append(dialog);
 const heading=document.createElement('h2');heading.textContent='Variable collections';const close=I.button('Close variable collections',()=>dialog.close()),status=document.createElement('p'),body=document.createElement('fieldset');status.setAttribute('role','status');body.style.cssText='border:0;padding:0;min-width:0';const header=document.createElement('header');header.append(heading,close);dialog.append(header,status,body);
 let importDraft=null,library=null,collectionId='',variableId='',newType='color',busy=false,previewOpen=false,previewSerial=0;const previewModes={},collectionSearch={},openModeGroups=new Set();
 const clone=value=>JSON.parse(JSON.stringify(value));
 const data=()=>({version:1,collections:clone(library.collections),variables:clone(library.variables)});
 const copyName=(name,names)=>{const used=new Set(names.map(value=>value.toLowerCase())),base=name.slice(0,110).trim()+' copy';let result=base,index=2;while(used.has(result.toLowerCase()))result=base+' '+index++;return result;};
 const blank=type=>({color:'#2563eb',number:0,boolean:false,string:''})[type];
 async function run(action,message='Saved in this project.'){if(busy)return;busy=true;body.disabled=true;status.textContent='Working…';try{await action();render();status.textContent=message;return true;}catch(error){status.textContent=error.message;return false;}finally{busy=false;body.disabled=false;}}
 async function load(){await run(async()=>{library=await window.RetouchVariableLibraryRequest();},'Collections loaded.');}
 async function save(next){library=await window.RetouchVariableLibraryRequest({type:'replace',revision:library.revision,library:next});}
 function input(parent,label,value=''){const field=document.createElement('input');field.type='text';field.value=value;field.maxLength=120;I.field(parent,label,field);return field;}
 function modePreview(){
  const panel=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Preview variable modes';panel.append(summary);panel.open=previewOpen;panel.addEventListener('toggle',()=>{previewOpen=panel.open;if(panel.open)resolve();});
  I.note(panel,'Preview resolved values without changing the page or saved defaults. Choose each collection mode independently.');
  const message=I.note(panel,''),results=document.createElement('div');message.setAttribute('role','status');
  const selected={};for(const collection of library.collections){selected[collection.id]=collection.modes.some(mode=>mode.id===previewModes[collection.id])?previewModes[collection.id]:collection.defaultMode;I.select(panel,'Preview mode for '+collection.name,collection.modes.map(mode=>[mode.id,mode.name]),selected[collection.id],value=>{selected[collection.id]=value;previewModes[collection.id]=value;resolve();});}
  panel.append(message,results);
  async function resolve(){const serial=++previewSerial;results.replaceChildren();message.textContent='Resolving modes…';try{const resolved=await window.RetouchVariableModePreview({revision:library.revision,modes:{...selected}});if(serial!==previewSerial||!panel.isConnected)return;
   const table=document.createElement('table');table.className='variable-preview-table';table.setAttribute('aria-label','Resolved variable values');const header=document.createElement('tr');for(const title of ['Variable','Type','Value','Resolution path']){const cell=document.createElement('th');cell.textContent=title;cell.scope='col';header.append(cell);}table.append(header);
   for(const value of resolved.values){const variable=library.variables.find(item=>item.id===value.id),collection=library.collections.find(item=>item.id===variable.collectionId),row=document.createElement('tr');row.setAttribute('aria-label',collection.name+' / '+variable.name);
    const path=value.path.map(item=>{const variable=library.variables.find(v=>v.id===item.variableId),collection=library.collections.find(c=>c.id===item.collectionId);return collection.name+' / '+variable.name+' ('+collection.modes.find(mode=>mode.id===item.modeId).name+')';}).join(' → ');
    for(const text of [collection.name+' / '+variable.name,value.type,String(value.value),path]){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}table.append(row);
   }results.append(table);message.textContent=resolved.values.length+' variables resolved.';
  }catch(error){if(serial===previewSerial&&panel.isConnected)message.textContent=error.message;}}
  if(panel.open)queueMicrotask(resolve);return panel;
 }
 async function exportCollections(selectedId=null){
  library=await window.RetouchVariableLibraryRequest();let output=data();
  if(selectedId){
   if(!output.collections.some(item=>item.id===selectedId))throw Error('The selected collection no longer exists. Reload collections before exporting.');
   const included=new Set([selectedId]),variables=new Map(output.variables.map(item=>[item.id,item]));
   // Include entire dependency collections so every mode and alias remains portable.
   for(const id of included)for(const item of output.variables.filter(variable=>variable.collectionId===id))for(const value of Object.values(item.values))if(typeof value==='object')included.add(variables.get(value.alias).collectionId);
   output={version:1,collections:output.collections.filter(item=>included.has(item.id)),variables:output.variables.filter(item=>included.has(item.collectionId))};
  }
  const url=URL.createObjectURL(new Blob([JSON.stringify(output,null,2)+'\n'],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='retouch-variable-collections.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
 }
 let closeModeMenu=null;dialog.addEventListener('close',()=>closeModeMenu?.());
 function render(){
  closeModeMenu?.();previewSerial++;body.replaceChildren();if(!library)return;
  if(!library.collections.some(item=>item.id===collectionId))collectionId=library.collections[0]?.id||'';
  const help=document.createElement('details'),helpTitle=document.createElement('summary');helpTitle.textContent='About variables';help.append(helpTitle);body.append(help);I.note(help,'Collections share typed variables across named modes. Definitions are saved to the project. In HTML, React or Liquid projects, select a layer and open Collection bindings to apply variables and choose modes.');
  const transfer=document.createElement('details'),transferTitle=document.createElement('summary');transferTitle.textContent='Import / export collections';transfer.append(transferTitle);transfer.open=!!importDraft;body.append(transfer);I.note(transfer,'Transfer collection JSON between projects. Import preserves identities and existing definitions. Conflicting identities or names must be resolved before importing.');
  transfer.append(I.button('Export collections',()=>run(()=>exportCollections(),'Collections exported.')));const exportSelected=I.button('Export selected collection',()=>run(()=>exportCollections(collectionId),'Selected collection and alias dependencies exported.'));exportSelected.disabled=!collectionId;transfer.append(exportSelected);I.note(transfer,'Selected exports include whole collections required by aliases in any mode.');
  const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.hidden=true;file.setAttribute('aria-label','Variable collection library file');transfer.append(I.button('Choose collection file',()=>file.click()),file);
  file.onchange=async()=>{const chosen=file.files[0];file.value='';if(!chosen)return;const loaded=await run(async()=>{if(chosen.size>2*1024*1024)throw Error('Collection files must be 2 MiB or smaller.');let value;try{value=JSON.parse(await chosen.text());}catch{throw Error('Choose a valid collection JSON file.');}if(value?.version!==1||!Array.isArray(value.collections)||!Array.isArray(value.variables))throw Error('Choose a version 1 collection library.');importDraft={name:chosen.name,library:value};},'Review the selected collections before importing.');if(!loaded){importDraft=null;render();}};
  if(importDraft){I.note(transfer,importDraft.name+' · '+importDraft.library.collections.length+' collections · '+importDraft.library.variables.length+' variables');transfer.append(I.button('Import selected collections',()=>run(async()=>{library=await window.RetouchVariableLibraryRequest({type:'import',revision:library.revision,library:importDraft.library});collectionId=importDraft.library.collections[0]?.id||collectionId;variableId='';importDraft=null;},'Collections imported. Existing definitions were preserved.')),I.button('Cancel collection import',()=>{importDraft=null;render();status.textContent='Import canceled.';}));}
  if(library.collections.length)body.append(modePreview());

  I.select(body,'Variable collection',[['','Choose a collection…'],...library.collections.map(item=>[item.id,item.name])],collectionId,value=>{collectionId=value;variableId='';render();});
  const settings=document.createElement('details'),settingsTitle=document.createElement('summary');settingsTitle.textContent='Collection settings';settings.append(settingsTitle);settings.open=!library.collections.length;body.append(settings);settings.append(I.button('Reload collections',load));
  const create=input(settings,'New collection name');settings.append(I.button('Create collection',()=>run(async()=>{const next=data(),id=crypto.randomUUID(),mode=crypto.randomUUID();next.collections.push({id,name:create.value,defaultMode:mode,modes:[{id:mode,name:'Default'}]});await save(next);collectionId=id;variableId='';})));
  const collection=library.collections.find(item=>item.id===collectionId);if(!collection)return;
  const name=input(settings,'Collection name',collection.name);settings.append(I.button('Rename collection',()=>run(async()=>{const next=data();next.collections.find(item=>item.id===collectionId).name=name.value;await save(next);})),I.button('Delete collection',()=>run(async()=>{const next=data();next.collections=next.collections.filter(item=>item.id!==collectionId);next.variables=next.variables.filter(item=>item.collectionId!==collectionId);await save(next);})));
  const duplicateCollection=I.button('Duplicate collection',()=>run(async()=>{const next=data(),id=crypto.randomUUID(),sourceVariables=next.variables.filter(item=>item.collectionId===collection.id),modeIds=new Map(collection.modes.map(mode=>[mode.id,crypto.randomUUID()])),variableIds=new Map(sourceVariables.map(item=>[item.id,crypto.randomUUID()]));next.collections.push({id,name:copyName(collection.name,next.collections.map(item=>item.name)),defaultMode:modeIds.get(collection.defaultMode),modes:collection.modes.map(mode=>({id:modeIds.get(mode.id),name:mode.name}))});for(const item of sourceVariables)next.variables.push({...item,id:variableIds.get(item.id),collectionId:id,values:Object.fromEntries(Object.entries(item.values).map(([mode,value])=>[modeIds.get(mode),typeof value==='object'?{alias:variableIds.get(value.alias)||value.alias}:value]))});await save(next);collectionId=id;variableId='';}));duplicateCollection.disabled=library.collections.length>=32||library.variables.length+library.variables.filter(item=>item.collectionId===collection.id).length>1000;duplicateCollection.title='Copy this collection. Internal aliases follow the copies; aliases to other collections stay linked.';settings.append(duplicateCollection);
  const modes=document.createElement('details'),modeTitle=document.createElement('summary');modeTitle.textContent='Collection modes';modes.append(modeTitle);modes.open=openModeGroups.has(collection.id);modes.addEventListener('toggle',()=>{if(modes.isConnected){if(modes.open)openModeGroups.add(collection.id);else openModeGroups.delete(collection.id);}});body.append(modes);
  const copyMode=(next,sourceId,name)=>{const id=crypto.randomUUID();next.collections.find(item=>item.id===collectionId).modes.push({id,name});for(const variable of next.variables.filter(item=>item.collectionId===collectionId))variable.values[id]=clone(variable.values[sourceId]);};
  const modeControls=new Map();
  for(const mode of collection.modes){const row=document.createElement('div'),label=input(row,'Mode name '+mode.name,mode.name);if(mode.id===collection.defaultMode)I.note(row,'Default mode');row.append(I.button('Rename mode '+mode.name,()=>run(async()=>{const next=data();next.collections.find(item=>item.id===collectionId).modes.find(item=>item.id===mode.id).name=label.value;await save(next);})),I.button('Use '+mode.name+' as default',()=>run(async()=>{const next=data();next.collections.find(item=>item.id===collectionId).defaultMode=mode.id;await save(next);})));
   const remove=I.button('Remove mode '+mode.name,()=>run(async()=>{const next=data(),target=next.collections.find(item=>item.id===collectionId);target.modes=target.modes.filter(item=>item.id!==mode.id);if(target.defaultMode===mode.id)target.defaultMode=target.modes[0].id;for(const variable of next.variables.filter(item=>item.collectionId===collectionId))delete variable.values[mode.id];await save(next);}));remove.disabled=collection.modes.length===1;const duplicate=I.button('Duplicate mode '+mode.name,()=>run(async()=>{const next=data();copyMode(next,mode.id,copyName(mode.name,collection.modes.map(item=>item.name)));await save(next);}));duplicate.disabled=collection.modes.length>=16;row.append(duplicate,remove);
   const index=collection.modes.indexOf(mode);for(const [delta,direction,icon]of [[-1,'left','←'],[1,'right','→']]){const label='Move mode '+mode.name+' '+direction,move=I.button(icon,async()=>{const ok=await run(async()=>{const next=data(),ordered=next.collections.find(item=>item.id===collectionId).modes;[ordered[index],ordered[index+delta]]=[ordered[index+delta],ordered[index]];await save(next);});if(ok&&dialog.open){const labels=[label,'Move mode '+mode.name+' '+(delta<0?'right':'left')];for(const name of labels){const target=[...body.querySelectorAll('button')].find(button=>button.getAttribute('aria-label')===name&&!button.disabled);if(target){target.focus();break;}}}});move.setAttribute('aria-label',label);move.title=label;move.disabled=index+delta<0||index+delta>=collection.modes.length;row.append(move);}modeControls.set(mode.id,{row,label});modes.append(row);}
  const modeName=input(modes,'New mode name'),copyFrom=I.select(modes,'Copy values from mode',collection.modes.map(mode=>[mode.id,mode.name]),collection.defaultMode,()=>{});const addMode=I.button('Add mode',()=>run(async()=>{const next=data();copyMode(next,copyFrom.value,modeName.value);await save(next);}));addMode.disabled=collection.modes.length>=16;modes.append(addMode);I.note(modes,'Copy an existing mode as a starting point. Aliases keep their links.');
  const variables=library.variables.filter(item=>item.collectionId===collectionId);if(!variables.some(item=>item.id===variableId))variableId='';
  if(variables.length){
   const wrap=document.createElement('div'),table=document.createElement('table'),thead=document.createElement('thead'),head=document.createElement('tr'),tbody=document.createElement('tbody');wrap.className='variable-grid-scroll';wrap.tabIndex=0;wrap.setAttribute('aria-label','Scroll collection values');table.className='variable-grid';table.setAttribute('aria-label',collection.name+' variables');
   const search=document.createElement('input'),count=document.createElement('p');search.type='search';search.className='variable-grid-search';search.placeholder='Search variables';search.setAttribute('aria-label','Search collection variables');search.value=collectionSearch[collectionId]||'';count.className='variable-grid-count';count.setAttribute('role','status');count.setAttribute('aria-label','Variable search results');
   function filter(){const terms=search.value.trim().toLowerCase().split(/\s+/).filter(Boolean);let visible=0;for(const row of tbody.children){row.hidden=!terms.every(term=>row.dataset.search.includes(term));if(!row.hidden)visible++;}count.textContent=visible?visible+' of '+variables.length+' variables':'No matching variables';collectionSearch[collectionId]=search.value;}search.addEventListener('input',filter);
   const nameHeader=document.createElement('th');nameHeader.scope='col';nameHeader.textContent='Name';head.append(nameHeader);
   const focusMode=id=>{const target=[...body.querySelectorAll('[data-variable-mode]')].find(button=>button.dataset.variableMode===id)||body.querySelector('[data-variable-mode]');target?.focus();};
   for(const mode of collection.modes){
    const cell=document.createElement('th'),button=I.button(mode.name,showMenu);cell.scope='col';cell.className='variable-mode-header';button.dataset.variableMode=mode.id;button.setAttribute('aria-label','Mode actions for '+mode.name);button.setAttribute('aria-haspopup','menu');button.setAttribute('aria-expanded','false');button.title=mode.id===collection.defaultMode?'Default mode · Click for actions':'Click for mode actions';cell.append(button);head.append(cell);
    function rename(){
     const field=document.createElement('input');field.className='variable-mode-name';field.setAttribute('aria-label','Rename mode '+mode.name);field.maxLength=120;field.value=mode.name;cell.replaceChildren(field);field.focus();field.select();
     field.addEventListener('keydown',async event=>{if(event.isComposing)return;if(event.key==='Escape'){event.preventDefault();event.stopPropagation();cell.replaceChildren(button);button.focus();}else if(event.key==='Enter'){event.preventDefault();const ok=await run(async()=>{const next=data();next.collections.find(item=>item.id===collectionId).modes.find(item=>item.id===mode.id).name=field.value;await save(next);});if(ok)focusMode(mode.id);else field.focus();}});
    }
    function showMenu(){
     if(busy)return;closeModeMenu?.();const popup=document.createElement('div');popup.className='variable-mode-menu';popup.setAttribute('popover','auto');popup.setAttribute('role','menu');popup.setAttribute('aria-label',mode.name+' mode actions');body.append(popup);
     let closed=false;const dismiss=(focus=false)=>{if(closed)return;closed=true;if(popup.matches(':popover-open'))popup.hidePopover();popup.remove();button.setAttribute('aria-expanded','false');if(closeModeMenu===dismiss)closeModeMenu=null;if(focus)button.focus();};closeModeMenu=dismiss;
     const add=(text,action,disabled=false)=>{const item=I.button(text,async()=>{dismiss();await action();});item.setAttribute('role','menuitem');item.tabIndex=-1;item.disabled=disabled;popup.append(item);};
     add('Rename',rename);
     const controls=modeControls.get(mode.id).row;
     for(const [text,label]of [['Duplicate','Duplicate mode '+mode.name],['Make default','Use '+mode.name+' as default'],['Move left','Move mode '+mode.name+' left'],['Move right','Move mode '+mode.name+' right'],['Remove','Remove mode '+mode.name]]){const control=[...controls.querySelectorAll('button')].find(item=>(item.getAttribute('aria-label')||item.textContent)===label);add(text,async()=>{await control.onclick();if(dialog.open)focusMode(mode.id);},control.disabled||(text==='Make default'&&mode.id===collection.defaultMode));}
     popup.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();dismiss(true);}else if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const items=[...popup.querySelectorAll('button:not(:disabled)')],index=items.indexOf(document.activeElement),next=event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowDown'?1:-1)+items.length)%items.length;items[next]?.focus();}else if(event.key==='Tab'){dismiss();button.focus();}});
     popup.addEventListener('beforetoggle',event=>{if(event.newState==='closed')queueMicrotask(()=>dismiss());});popup.showPopover();button.setAttribute('aria-expanded','true');const rect=button.getBoundingClientRect();popup.style.left=Math.max(8,Math.min(rect.left,innerWidth-popup.offsetWidth-8))+'px';popup.style.top=Math.max(8,Math.min(rect.bottom+4,innerHeight-popup.offsetHeight-8))+'px';popup.querySelector('button').focus();
    }
    button.addEventListener('keydown',event=>{if(event.key==='ArrowDown'){event.preventDefault();showMenu();}});
   }thead.append(head);table.append(thead,tbody);
   let cancelCell=null;
   function editCell(cell,button,item,mode){
    if(busy)return;cancelCell?.();const value=item.values[mode.id],editor=document.createElement('div'),valueHost=document.createElement('div'),source=document.createElement('select');editor.className='variable-cell-editor';valueHost.className='variable-cell-value';let isAlias=typeof value==='object',field;const drafts={literal:isAlias?String(blank(item.type)):String(value),alias:isAlias?value.alias:''};
    source.setAttribute('aria-label',item.name+' in '+mode.name+' source');for(const [id,label]of [['literal','Value'],['alias','Alias']]){const option=document.createElement('option');option.value=id;option.textContent=label;source.append(option);}source.value=isAlias?'alias':'literal';
    function renderValue(){
     if(isAlias||item.type==='boolean'){field=document.createElement('select');const choices=isAlias?[['','Choose a variable…'],...library.variables.filter(other=>other.type===item.type&&other.id!==item.id).map(other=>[other.id,library.collections.find(c=>c.id===other.collectionId).name+' / '+other.name])]:[['false','False'],['true','True']];for(const [id,label]of choices){const option=document.createElement('option');option.value=id;option.textContent=label;field.append(option);}}
     else{field=document.createElement('input');field.type=item.type==='number'?'number':'text';if(item.type==='number')field.step='any';field.maxLength=item.type==='string'?4096:150;}
     field.value=drafts[isAlias?'alias':'literal'];field.setAttribute('aria-label',item.name+' in '+mode.name);valueHost.replaceChildren(field);
    }
    source.onchange=()=>{drafts[isAlias?'alias':'literal']=field.value;isAlias=source.value==='alias';renderValue();field.focus();};renderValue();
    const cancel=()=>{cell.replaceChildren(button);cancelCell=null;status.textContent='Edit canceled.';button.focus();};cancelCell=cancel;
    const commit=async()=>{const ok=await run(async()=>{if(item.type==='number'&&!isAlias&&field.value.trim()==='')throw Error('Enter a number for '+mode.name+'.');if(isAlias&&!field.value)throw Error('Choose a variable for '+mode.name+'.');const next=data(),target=next.variables.find(other=>other.id===item.id);target.values[mode.id]=isAlias?{alias:field.value}:item.type==='number'?Number(field.value):item.type==='boolean'?field.value==='true':field.value;await save(next);});if(ok)[...body.querySelectorAll('button[aria-label]')].find(el=>el.getAttribute('aria-label')===button.getAttribute('aria-label'))?.focus();else field.focus();};
    const apply=I.button('Save value',commit),discard=I.button('Cancel edit',cancel);editor.append(source,valueHost,apply,discard);editor.addEventListener('keydown',event=>{if(event.isComposing)return;if(event.key==='Escape'){event.preventDefault();event.stopPropagation();cancel();}else if(event.key==='Enter'&&event.target===field){event.preventDefault();commit();}});cell.replaceChildren(editor);field.focus();if(field.tagName==='INPUT')field.select();
   }
   function choose(item,mode){variableId=item.id;render();const label=mode?mode.name+(typeof item.values[mode.id]==='object'?' alias':' value'):'Collection variable name';[...body.querySelectorAll('[aria-label]')].find(el=>el.getAttribute('aria-label')===label)?.focus();}
   for(const item of variables){const row=document.createElement('tr');row.dataset.search=(item.name+' '+item.type).toLowerCase();row.dataset.selected=String(item.id===variableId);const name=document.createElement('th');name.scope='row';const pick=I.button(item.name,()=>choose(item));pick.setAttribute('aria-label','Edit variable '+item.name);const kind=document.createElement('small');kind.textContent=item.type;pick.append(kind);name.append(pick);row.append(name);
    for(const mode of collection.modes){const cell=document.createElement('td'),value=item.values[mode.id],alias=typeof value==='object'?library.variables.find(other=>other.id===value.alias):null,button=I.button(alias?'↗ '+alias.name:String(value),()=>editCell(cell,button,item,mode));button.setAttribute('aria-label','Edit '+item.name+' in '+mode.name);if(item.type==='color'&&!alias){const swatch=document.createElement('span');swatch.className='variable-color-swatch';swatch.style.backgroundColor=String(value);button.prepend(swatch);}cell.append(button);row.append(cell);}tbody.append(row);
   }wrap.append(table);body.append(search,count,wrap);filter();
  }
  I.select(body,'Collection variable',[['','New variable…'],...variables.map(item=>[item.id,item.name])],variableId,value=>{variableId=value;render();});const variable=variables.find(item=>item.id===variableId),type=variable?.type||newType,variableName=input(body,'Collection variable name',variable?.name||'');
  const typePicker=I.select(body,'Variable type',['color','number','boolean','string'].map(value=>[value,value[0].toUpperCase()+value.slice(1)]),type,value=>{newType=value;render();});typePicker.disabled=!!variable;
  const readers={};
  for(const mode of collection.modes){const row=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=mode.name;row.append(legend);body.append(row);let current=variable?.values[mode.id]??blank(type);const editor=document.createElement('div');
   function valueEditor(kind){editor.replaceChildren();if(kind==='alias'){const options=library.variables.filter(item=>item.type===type&&(item.id!==variableId||typeof current==='object'&&item.id===current.alias)).map(item=>[item.id,library.collections.find(c=>c.id===item.collectionId).name+' / '+item.name]),pick=I.select(editor,mode.name+' alias',[['','Choose a variable…'],...options],typeof current==='object'?current.alias:'',()=>{});readers[mode.id]=()=>({alias:pick.value});}
    else if(type==='boolean'){const pick=I.select(editor,mode.name+' value',[['false','False'],['true','True']],String(typeof current==='boolean'?current:false),()=>{});readers[mode.id]=()=>pick.value==='true';}
    else{const field=input(editor,mode.name+' value',typeof current==='object'?blank(type):current);field.maxLength=type==='string'?4096:150;if(type==='number'){field.type='number';field.step='any';}readers[mode.id]=()=>{if(type==='number'&&field.value.trim()==='')throw Error('Enter a number for '+mode.name+'.');return type==='number'?Number(field.value):field.value;};}}
   I.select(row,mode.name+' value source',[['literal','Value'],['alias','Alias']],typeof current==='object'?'alias':'literal',valueEditor);row.append(editor);valueEditor(typeof current==='object'?'alias':'literal');
  }
  body.append(I.button('Save collection variable',()=>run(async()=>{const next=data(),id=variable?.id||crypto.randomUUID(),entry={id,collectionId,name:variableName.value,type,values:Object.fromEntries(collection.modes.map(mode=>[mode.id,readers[mode.id]()]))},index=next.variables.findIndex(item=>item.id===id);if(index<0)next.variables.push(entry);else next.variables[index]=entry;await save(next);variableId=id;})));
  if(variable)body.append(I.button('Delete collection variable',()=>run(async()=>{const next=data();next.variables=next.variables.filter(item=>item.id!==variable.id);await save(next);variableId='';})));
 }
 open.addEventListener('click',()=>{dialog.showModal();load();});
})();
